### PR TITLE
[Editor] Move the alt text button in the editor toolbar

### LINKED ISSUE #17298: Alt-text and delete buttons may overlap
Attach (recommended) or Link to PDF file here: N/A

Configuration:
- Web browser and its version: N/A
- Operating system and its version: N/A
- PDF.js version: 4.0.242 [3459615ec]
- Is a browser extension: N/A

Steps to reproduce the problem:
1. Open the demo viewer, https://mozilla.github.io/pdf.js/web/viewer.html#locale=en-US 
2. Add a StampAnnotation, e.g. `firefox_logo.svg` from the test-suite.
3. Rotate the document once. *Edit:* It also reproduces without rotating, simply by making the Annotation small enough.

What is the expected behavior? (add screenshot)
That both the alt-text *and* delete buttons are visible and clickable.

What went wrong? (add screenshot)
The buttons overlap, see 

overlap

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): N/A

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Comment by calixteman** [comment]
We must wait for an approval from UX it's why I keep it as a draft for the moment.

File: src/display/editor/alt_text.js [hunk 1]
```diff
@@ -0,0 +1,181 @@
...
+    }
+    if (!enabled && this.#altTextTooltipTimeout) {
+      clearTimeout(this.#altTextTooltipTimeout);
+      this.#altTextTooltipTimeout = null;
+    }
+    this.#altTextButton.disabled = !enabled;
+  }
+
+  destroy() {
+    console.log("DESTROY ALT TEXT");
```
Comment (Snuffleupagus) [inline src/display/editor/alt_text.js:110]: Left-over debug statement?

File: web/images/editor-toolbar-divider.svg
Comment (Snuffleupagus) [inline web/images/editor-toolbar-divider.svg:1]: Do we really *need* an image for this, can't we simply use an element with a suitable background-color?

Please see now the viewer handles a similar thing in the primary UI: https://github.com/mozilla/pdf.js/blob/d679078beb45314aa45f12c212ea9e21d3f3154f/web/viewer.css#L1055-L1068

File: src/display/editor/editor.js [hunk 2]
```diff
@@ -627,11 +618,6 @@ class AnnotationEditor {
     if (!this.#keepAspectRatio) {
       this.div.style.height = `${((100 * height) / parentHeight).toFixed(2)}%`;
     }
-    this.#altTextButton?.classList.toggle(
-      "small",
-      width < AnnotationEditor.SMALL_EDITOR_SIZE ||
-        height < AnnotationEditor.SMALL_EDITOR_SIZE
-    );
```
Comment (Snuffleupagus) [inline src/display/editor/editor.js:634]: Can we also remove this code now?
https://github.com/mozilla/pdf.js/blob/d679078beb45314aa45f12c212ea9e21d3f3154f/src/display/editor/editor.js#L98-L100

File: web/annotation_editor_layer_builder.css [hunk 3]
```diff
@@ -285,6 +281,84 @@
           outline: 2px solid var(--editor-toolbar-focus-outline-color);
         }
       }
+
+      .altText {
+        display: flex;
+        align-items: center;
+        justify-content: center;
+        width: max-content;
+        padding-inline: 16px;
```
Comment (Snuffleupagus) [inline web/annotation_editor_layer_builder.css:290]: Do we still want this all that "much" padding here, since it feels unnecessarily large now that it's a toolbar button?

Comment (calixteman) [reply web/annotation_editor_layer_builder.css:286]: I don't know, it's what I read in the specs.
I raised the question to UX.

File: src/display/editor/editor.js [hunk 4]
```diff
@@ -1563,7 +1431,10 @@ class AnnotationEditor {
   select() {
     this.makeResizable();
     this.div?.classList.add("selectedEditor");
-    this.addEditToolbar();
+    if (!this.#editToolbar) {
+      this.addEditToolbar().then(() => this.#editToolbar?.show());
```
Comment (Snuffleupagus) [inline src/display/editor/editor.js:1435]: Is there not a *theoretically* risk that the `unselect`-method, defined below, could have been called before this promise resolves?
In that case the edit-toolbar could incorrectly become visible, so we might need a way to prevent that.

File: web/annotation_editor_layer_builder.css [hunk 5]
```diff
@@ -42,21 +42,8 @@
   --editorInk-editing-cursor: url(images/cursor-editorInk.svg) 0 16, pointer;
   /*#endif*/
 
-  --alt-text-opacity: 0.8;
   --alt-text-add-image: url(images/altText_add.svg);
   --alt-text-done-image: url(images/altText_done.svg);
```
Comment (Snuffleupagus) [inline web/annotation_editor_layer_builder.css:46]: Can't these definitions be moved into the `.altText` block, further down, now?

File: web/annotation_editor_layer_builder.css [hunk 6]
```diff
@@ -270,6 +262,14 @@
       }
 
       > * {
+        height: var(--editor-toolbar-height);
+      }
+
+      > :not(:is(.divider)) {
```
Comment (Snuffleupagus) [inline web/annotation_editor_layer_builder.css:268]: Isn't the `:is`-part redundant here?
```suggestion
      > :not(.divider) {
```

File: web/annotation_editor_layer_builder.css [hunk 7]
```diff
@@ -281,10 +281,88 @@
...
+          height: 13px;
+          background-color: var(--editor-toolbar-fg-color);
+          margin-inline-end: 4px;
+        }
+
+        &.done::before {
+          mask-image: var(--alt-text-done-image);
+        }
+
+        & .tooltip {
```
Comment (Snuffleupagus) [inline web/annotation_editor_layer_builder.css:321]: Nit:
```suggestion
        .tooltip {
```

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]

File: l10n/en-US/viewer.ftl [hunk 8]
```diff
@@ -326,6 +326,14 @@ pdfjs-editor-stamp-button-label = Add or edit images
 pdfjs-editor-remove-button =
     .title = Remove
```
Comment (Snuffleupagus) [inline l10n/en-US/viewer.ftl:327]: Shouldn't this entry be removed now, since it's no longer used?

Comment (flodolo) [reply l10n/en-US/viewer.ftl:327]: If it's unused (and it looks like it), indeed it should be removed

**Review by flodolo — APPROVED** [review]
(with the obsolete string removed)

File: l10n/en-US/viewer.ftl [hunk 9]
```diff
@@ -323,8 +323,14 @@ pdfjs-editor-ink-button-label = Draw
 pdfjs-editor-stamp-button =
     .title = Add or edit images
 pdfjs-editor-stamp-button-label = Add or edit images
-pdfjs-editor-remove-button =
-    .title = Remove
+
+# Remove button for the various kind of editor.
```
Comment (flodolo) [inline l10n/en-US/viewer.ftl:327]: Sorry, missed the comment here.

This is a single string comment that only applies to the next string. You want a group-level comment (two hashes), if you want it to show up in Pontoon, or a stand-alone comment (one hash, leave an empty line after), which won't be displayed to localizers. If you go with the group-level comment, you also need to "reset it" (add an empty group-level comment after the strings).

Comment (flodolo) [reply l10n/en-US/viewer.ftl:327]: With a group comment, it would look like this (notice the empty lines before and after).

```

## Remove button for the various kinds of editor.

pdfjs-editor-remove-ink-button =
    .title = Remove drawing
pdfjs-editor-remove-freetext-button =
    .title = Remove text
pdfjs-editor-remove-stamp-button =
    .title = Remove image

##

# Editor Parameters
pdfjs-editor-free-text-color-input = Color
```

**Review by Snuffleupagus — APPROVED** [review]
This is really nice since it not only fixes the button overlap, but it improves consistency in the editing-UI *and* does so with less code overall.

r=me, thank you!
