### PR TITLE
[api-major] Add openjpeg.wasm to pdf.js (bug 1935076)

### LINKED ISSUE #17950: Embed a .wasm file for the jpeg2000 decoder in order to reduce the bundle size
For reference:
https://github.com/mozilla/pdf.js/pull/17946#discussion_r1566004430

### PR DESCRIPTION
**Pull request by calixteman**
In order to fix bug 1935076, we'll have to add a pure js fallback in case wasm is disabled or simd isn't supported. Unfortunately, this fallback will take some space.

So, the main goal of this patch is to reduce the overall size (by ~93k). As a side effect, it should make easier to use an other wasm file (which must export _jp2_decode, _malloc and _free).

### CODE REVIEW

File: src/core/jpx.js [hunk 1]
```diff
@@ -24,20 +24,101 @@ class JpxError extends BaseException {
...
-      throw new JpxError(imageData);
+  static #buffer = null;
+
+  static #handler = null;
+
+  static #instantiationFailed = false;
+
+  static #modulePromise = null;
+
+  static #openjpegWasmUrl = "";
```
Comment (Snuffleupagus) [inline src/core/jpx.js:35]: Please keep the initial value consistent with e.g. DefaultPartialEvaluatorOptions.
```suggestion
  static #openjpegWasmUrl = null;
```

File: src/core/jpx.js [hunk 2]
```diff
@@ -24,20 +24,101 @@ class JpxError extends BaseException {
...
+
+  static setOptions({ handler, openjpegWasmUrl }) {
+    if (!this.#buffer) {
+      this.#openjpegWasmUrl = openjpegWasmUrl;
+      if (!openjpegWasmUrl) {
+        this.#handler = handler;
+      }
+    }
```
Comment (Snuffleupagus) [inline src/core/jpx.js:43]: Why do we need the `this.#buffer` check here, since that's not immediately obvious to me?

File: src/core/jpx.js [hunk 3]
```diff
@@ -24,20 +24,101 @@ class JpxError extends BaseException {
...
+  }
+
+  static async #instantiateWasm(imports, successCallback) {
+    try {
+      if (!this.#buffer) {
+        const wasmFile = "openjpeg.wasm";
```
Comment (Snuffleupagus) [inline src/core/jpx.js:49]:
```suggestion
    const wasmFile = "openjpeg.wasm";
    try {
      if (!this.#buffer) {
```

File: src/core/jpx.js [hunk 4]
```diff
@@ -24,20 +24,101 @@ class JpxError extends BaseException {
...
+              filename: wasmFile,
+            }
+          );
+        }
+      }
+      const results = await WebAssembly.instantiate(this.#buffer, imports);
+      return successCallback(results.instance);
+    } catch (e) {
+      this.#instantiationFailed = true;
+      warn(`Cannot load openjpeg.wasm ${e}`);
```
Comment (Snuffleupagus) [inline src/core/jpx.js:66]:
```suggestion
      warn(`Cannot load ${wasmFile}: "${e}".`);
```

File: src/core/jpx.js [hunk 5]
```diff
@@ -24,20 +24,101 @@ class JpxError extends BaseException {
...
+      }
+    }
+  }
+
+  static async #instantiateWasm(imports, successCallback) {
+    try {
+      if (!this.#buffer) {
+        const wasmFile = "openjpeg.wasm";
+        if (this.#openjpegWasmUrl) {
+          const response = await fetch(`${this.#openjpegWasmUrl}/${wasmFile}`);
```
Comment (Snuffleupagus) [inline src/core/jpx.js:51]: This looks wrong, since these kinds of URLs all should include a trailing slash.
```suggestion
          const response = await fetch(`${this.#openjpegWasmUrl}${wasmFile}`);
```

File: src/core/jpx.js [hunk 6]
```diff
@@ -24,20 +24,101 @@ class JpxError extends BaseException {
...
+          this.#buffer = await response.arrayBuffer();
+        } else {
+          this.#buffer = await this.#handler.sendWithPromise(
+            "FetchOpenjpegWasm",
+            {
+              filename: wasmFile,
+            }
```
Comment (Snuffleupagus) [inline src/core/jpx.js:58]: Nit:
```suggestion
            { filename: wasmFile }
```

File: src/core/jpx.js [hunk 7]
```diff
@@ -24,20 +24,101 @@ class JpxError extends BaseException {
...
+      }
+      const results = await WebAssembly.instantiate(this.#buffer, imports);
+      return successCallback(results.instance);
+    } catch (e) {
+      this.#instantiationFailed = true;
+      warn(`Cannot load openjpeg.wasm ${e}`);
+      return false;
+    } finally {
+      this.#handler = null;
+      this.#openjpegWasmUrl = "";
```
Comment (Snuffleupagus) [inline src/core/jpx.js:70]:
```suggestion
      this.#openjpegWasmUrl = null;
```

File: src/core/jpx.js [hunk 8]
```diff
@@ -24,20 +24,101 @@ class JpxError extends BaseException {
...
+    }
+  }
+
+  static async decode(
+    bytes,
+    { numComponents = 4, isIndexedColormap = false, smaskInData = false } = {}
+  ) {
+    if (this.#instantiationFailed) {
+      throw new JpxError("OpenJPEG failed to instantiate");
```
Comment (Snuffleupagus) [inline src/core/jpx.js:79]:
```suggestion
      throw new JpxError("OpenJPEG failed to instantiate.");
```

File: src/core/jpx.js [hunk 9]
```diff
@@ -24,20 +24,101 @@ class JpxError extends BaseException {
...
+      if (ptr) {
+        module._free(ptr);
+      }
     }
-    return imageData;
   }
 
   static cleanup() {
-    this.#module = null;
+    this.#modulePromise = null;
```
Comment (Snuffleupagus) [inline src/core/jpx.js:121]: Don't we also want to clear out `this.#buffer` here, since that's a lot of data that we're otherwise never removing?

File: src/display/api.js [hunk 10]
```diff
@@ -153,6 +159,12 @@ const DefaultStandardFontDataFactory =
  *   when reading the standard font files. Providing a custom factory is useful
  *   for environments without Fetch API or `XMLHttpRequest` support, such as
  *   Node.js. The default value is {DOMStandardFontDataFactory}.
+ * @property {string} [openjpegWasmUrl] - The URL where the openjpeg wasm file
+ * is located.
```
Comment (Snuffleupagus) [inline src/display/api.js:163]: This parameter should be consistent with the other URL ones above.
```suggestion
 *   is located. Include the trailing slash.
```

File: src/core/jpx.js [hunk 11]
```diff
@@ -24,20 +24,101 @@ class JpxError extends BaseException {
...
+        this.#handler = handler;
+      }
+    }
+  }
+
+  static async #instantiateWasm(imports, successCallback) {
+    try {
+      if (!this.#buffer) {
+        const wasmFile = "openjpeg.wasm";
+        if (this.#openjpegWasmUrl) {
```
Comment (Snuffleupagus) [inline src/core/jpx.js:50]: Please let's keep this consistent with the other URL parameters, for CMaps and StandardFonts, used in the evaluator.
```suggestion
        if (this.#openjpegWasmUrl !== null) {
```

File: src/display/openjpeg_wasm_factory.js [hunk 12]
```diff
@@ -0,0 +1,65 @@
...
+import { fetchData } from "./display_utils.js";
+import { unreachable } from "../shared/util.js";
+
+class BaseOpenjpegWasmFactory {
+  constructor({ baseUrl = null }) {
+    if (
+      (typeof PDFJSDev === "undefined" || PDFJSDev.test("TESTING")) &&
+      this.constructor === BaseOpenjpegWasmFactory
+    ) {
+      unreachable("Cannot initialize BaseStandardFontDataFactory.");
```
Comment (Snuffleupagus) [inline src/display/openjpeg_wasm_factory.js:25]:
```suggestion
      unreachable("Cannot initialize BaseOpenjpegWasmFactory.");
```

**Comment by Snuffleupagus** [comment]
A little while back you mentioned potentially replacing the JBIG2 decoder with a wasm-based one, is this still something that we might at one point want to do? (Or if we want to introduce any other wasm-code, e.g. for ICC profile support.)

If so, it'd probably make sense to replace the `openjpegWasmUrl`/`OpenjpegWasmFactory` API-parameters (and the class/file names) with more general `wasmUrl`/`WasmFactory` ones instead to make that easier without having to duplicate a lot of code.

**Comment by calixteman** [comment]
> A little while back you mentioned potentially replacing the JBIG2 decoder with a wasm-based one, is this still something that we might at one point want to do? (Or if we want to introduce any other wasm-code, e.g. for ICC profile support.)
> 

Yep replacing the JBIG2 decoder with the pdfium one (afaik it's the only one with a license compatible with ours) is still something we'd like to do.
I already have more than wip for using qcms for the ICC stuff.

> If so, it'd probably make sense to replace the `openjpegWasmUrl`/`OpenjpegWasmFactory` API-parameters (and the class/file names) with more general `wasmUrl`/`WasmFactory` ones instead to make that easier without having to then duplicate a lot of code.

Yes I thought about that too but then I thought it could be done later when an other wasm file will be added.
Do you prefer we do it now ?

**Comment by Snuffleupagus** [comment]
> Yes I thought about that too but then I thought it could be done later when an other wasm file will be added.
> Do you prefer we do it now ?

By doing this *now* we avoid breaking backwards compatibility at a later date, which definitely seems worthwhile to me!

File: src/core/jpx.js (hunk 2 above)
Comment (calixteman) [reply src/core/jpx.js:43]: Once we've a buffer we don't need get it again so those options are useless.

File: gulpfile.mjs [hunk 13]
```diff
@@ -646,6 +649,13 @@ function createStandardFontBundle() {
   );
 }
 
+function createOpenjpegWasmBundle() {
+  return gulp.src(["external/openjpeg/openjpeg.wasm"], {
+    base: "external/openjpeg",
+    encoding: false,
+  });
+}
+
```
Comment (Snuffleupagus) [inline gulpfile.mjs:658]: This should prepare for having more than one wasm file.
```suggestion
function createWasmBundle() {
  return gulp.src(["external/openjpeg/openjpeg.wasm"], {
    base: "external/openjpeg",
    encoding: false,
  });
}

```

File: gulpfile.mjs [hunk 14]
```diff
@@ -1068,6 +1078,7 @@ function buildGeneric(defines, dir) {
       .pipe(gulp.dest(dir + "web")),
     createCMapBundle().pipe(gulp.dest(dir + "web/cmaps")),
     createStandardFontBundle().pipe(gulp.dest(dir + "web/standard_fonts")),
+    createOpenjpegWasmBundle().pipe(gulp.dest(dir + "web/openjpeg")),
```
Comment (Snuffleupagus) [inline gulpfile.mjs:1081]: Here, and similar in the rest of this file.
```suggestion
    createOpenjpegWasmBundle().pipe(gulp.dest(dir + "web/wasm")),
```

File: src/display/api.js [hunk 15]
```diff
@@ -153,6 +159,11 @@ const DefaultStandardFontDataFactory =
  *   when reading the standard font files. Providing a custom factory is useful
  *   for environments without Fetch API or `XMLHttpRequest` support, such as
  *   Node.js. The default value is {DOMStandardFontDataFactory}.
+ * @property {string} [wasmUrls] - The URLs to the wasm files.
```
Comment (Snuffleupagus) [inline src/display/api.js:162]: Sorry, but I don't understand why this isn't just `wasmUrl` and supporting *only one* URL in the same way that both cMapUrl and standardFontDataUrl works since this add a bunch of complexity!?

In the built viewer we should place all wasm-files in a `web/wasm` folder. (And for the development viewer it should be simple to run `createWasmBundle` as part of `gulp server`.)

```suggestion
 * @property {string} [wasmUrl] - The URL where the wasm files are located.
 *   Include the trailing slash.

Comment (calixteman) [reply src/display/api.js:162]: It's because I thought about keeping the same directory structure.

File: src/core/jpx.js [hunk 16]
```diff
@@ -24,20 +24,97 @@ class JpxError extends BaseException {
...
+  static async #instantiateWasm(imports, successCallback) {
+    try {
+      if (!this.#buffer) {
+        if (this.#wasmUrl !== null) {
+          const response = await fetch(`${this.#wasmUrl}openjpeg.wasm`);
+          this.#buffer = await response.arrayBuffer();
+        } else {
+          this.#buffer = await this.#handler.sendWithPromise("FetchWasm", {
+            filename: "openjpeg.wasm",
+          });
```
Comment (Snuffleupagus) [inline src/core/jpx.js:55]: I don't believe that we have proper test-coverage for this code-path, so I'd suggest adding the following to address that (since it's a fairly small and simple PDF/image).
```diff
diff --git a/test/test_manifest.json b/test/test_manifest.json
index 71751285b..1a7418b9a 100644
--- a/test/test_manifest.json
+++ b/test/test_manifest.json
@@ -6371,6 +6371,14 @@
     "rounds": 1,
     "type": "eq"
   },
+  {
+    "id": "issue19326_main_thread_fetch",
+    "file": "pdfs/issue19326.pdf",
+    "md5": "b4d937017daf439a6318501428e0c6ba",
+    "rounds": 1,
+    "type": "eq",
+    "useWorkerFetch": false
+  },
   {
     "id": "bug1140761",
     "file": "pdfs/bug1140761.pdf",
```

File: web/app_options.js [hunk 17]
```diff
@@ -396,6 +396,17 @@ const defaultOptions = {
...
+    /** @type {string} */
+    value:
+      // eslint-disable-next-line no-nested-ternary
+      typeof PDFJSDev === "undefined"
+        ? "../external/openjpeg/"
+        : PDFJSDev.test("MOZCENTRAL")
+          ? "resource://pdf.js/web/wasm/"
+          : "../web/wasm/",
+    kind: OptionKind.API,
+  },
```
Comment (Snuffleupagus) [inline web/app_options.js:409]: Please move this down, such that the options are sorted alphabetically.

**Review by Snuffleupagus — APPROVED** [review]
r=me, with the final comments addressed; thank you!
