### PR TITLE
fixing #7590 by delaying div shrink after mouse up

### LINKED ISSUE #7590: Double-click highlighting broken with enhanced text selection turned on.
Link to PDF file (or attach file here): 
[tracemonkey.pdf](https://github.com/mozilla/pdf.js/files/452993/tracemonkey.pdf)

Configuration:
- Web browser and its version: Chrome 53, Safari 9.1.2
- Operating system and its version: Mac OS X
- PDF.js version: 

Steps to reproduce the problem:
1. turn on enhanceTextSelection
2. try to double click text, especially if the text is in two columns

What is the expected behavior? (add screenshot)
The word that is being double clicked should be selected

What went wrong? (add screenshot)
A word a few words back was selected

Video demonstrating the problem:
[example.zip](https://github.com/mozilla/pdf.js/files/452999/example.zip)

### PR DESCRIPTION
**Pull request by jeremypress**
Uses a timeout to delay shrinking of divs, if another mousedown event occurs, it resets the timer. This fixes double click and right click highlighting on webkit browsers. This logic only applies when the enhanced text selection is turned on.

Fixes #7590.

### CODE REVIEW

File: web/text_layer_builder.js [hunk 1]
```diff
@@ -321,9 +321,13 @@ var TextLayerBuilder = (function TextLayerBuilderClosure() {
     _bindMouse: function TextLayerBuilder_bindMouse() {
       var div = this.textLayerDiv;
       var self = this;
+      var expandDivsTimer;
       div.addEventListener('mousedown', function (e) {
         if (self.enhanceTextSelection && self.textLayerRenderTask) {
           self.textLayerRenderTask.expandTextDivs(true);
+          if (expandDivsTimer) {
+            window.clearTimeout(expandDivsTimer);
```
Comment (timvandermeij) [inline web/text_layer_builder.js]: I think you can leave out `window.` and just use `clearTimeout`.

File: web/text_layer_builder.js [hunk 2]
```diff
@@ -350,7 +354,9 @@ var TextLayerBuilder = (function TextLayerBuilderClosure() {
       });
       div.addEventListener('mouseup', function (e) {
         if (self.enhanceTextSelection && self.textLayerRenderTask) {
-          self.textLayerRenderTask.expandTextDivs(false);
+          expandDivsTimer = window.setTimeout(function() {
```
Comment (timvandermeij) [inline web/text_layer_builder.js]: I think you can leave out `window.` and just use `setTimeout`.

File: web/text_layer_builder.js [hunk 3]
```diff
@@ -321,9 +321,13 @@ var TextLayerBuilder = (function TextLayerBuilderClosure() {
     _bindMouse: function TextLayerBuilder_bindMouse() {
       var div = this.textLayerDiv;
       var self = this;
+      var expandDivsTimer;
```
Comment (timvandermeij) [inline web/text_layer_builder.js]: Initialize this to `null`: `var expandDivsTimer = null;`

File: web/text_layer_builder.js [hunk 4]
```diff
@@ -350,7 +354,9 @@ var TextLayerBuilder = (function TextLayerBuilderClosure() {
       });
       div.addEventListener('mouseup', function (e) {
         if (self.enhanceTextSelection && self.textLayerRenderTask) {
-          self.textLayerRenderTask.expandTextDivs(false);
+          expandDivsTimer = window.setTimeout(function() {
+            self.textLayerRenderTask.expandTextDivs(false);
+          }, 300);
```
Comment (timvandermeij) [inline web/text_layer_builder.js]: Make the value 300 a constant named `EXPAND_TEXT_DIVS_TIMEOUT` and add it here: https://github.com/jeremypress/pdf.js/blob/eebbc2d4034781ef9bab93a0ae6ce90481d11853/web/text_layer_builder.js#L30

File: web/text_layer_builder.js [hunk 5]
```diff
@@ -321,9 +321,13 @@ var TextLayerBuilder = (function TextLayerBuilderClosure() {
     _bindMouse: function TextLayerBuilder_bindMouse() {
       var div = this.textLayerDiv;
       var self = this;
+      var expandDivsTimer;
       div.addEventListener('mousedown', function (e) {
         if (self.enhanceTextSelection && self.textLayerRenderTask) {
           self.textLayerRenderTask.expandTextDivs(true);
+          if (expandDivsTimer) {
+            window.clearTimeout(expandDivsTimer);
+          }
```
Comment (timvandermeij) [inline web/text_layer_builder.js]: Set `expandDivsTimer = null;` after clearing the timeout, otherwise the `if` clause will always be true after activating the timer one time.

File: web/text_layer_builder.js [hunk 6]
```diff
@@ -28,6 +28,7 @@
   }
 }(this, function (exports, domEvents, pdfjsLib) {
 
+var EXPAND_DIVS_TIMEOUT = 300; // ms
```
Comment (timvandermeij) [inline web/text_layer_builder.js]: Add a newline below this constant for readability.

File: web/text_layer_builder.js [hunk 7]
```diff
@@ -350,7 +357,9 @@ var TextLayerBuilder = (function TextLayerBuilderClosure() {
       });
       div.addEventListener('mouseup', function (e) {
         if (self.enhanceTextSelection && self.textLayerRenderTask) {
-          self.textLayerRenderTask.expandTextDivs(false);
+          expandDivsTimer = setTimeout(function() {
+            self.textLayerRenderTask.expandTextDivs(false);
```
Comment (Snuffleupagus) [inline web/text_layer_builder.js]: Similar to the above, let's set `expandDivsTimer = null;`.

File: web/text_layer_builder.js [hunk 8]
```diff
@@ -321,9 +323,14 @@ var TextLayerBuilder = (function TextLayerBuilderClosure() {
...
       var div = this.textLayerDiv;
       var self = this;
+      var expandDivsTimer = null;
       div.addEventListener('mousedown', function (e) {
         if (self.enhanceTextSelection && self.textLayerRenderTask) {
           self.textLayerRenderTask.expandTextDivs(true);
+          if (expandDivsTimer) {
+            clearTimeout(expandDivsTimer);
+            expandDivsTimer = null;
+          }
```
Comment (Snuffleupagus) [inline web/text_layer_builder.js]: Given that this only appears to be an issue in non-Firefox browsers, I think that we should thus enclose this code in appropriate preprocessor tags; i.e. something like this:
```javascript
//#if !(MOZCENTRAL || FIREFOX)
          if (expandDivsTimer) {
            clearTimeout(expandDivsTimer);
            expandDivsTimer = null;
          }
//#endif
```

File: web/text_layer_builder.js [hunk 9]
```diff
@@ -350,7 +357,9 @@ var TextLayerBuilder = (function TextLayerBuilderClosure() {
       });
       div.addEventListener('mouseup', function (e) {
         if (self.enhanceTextSelection && self.textLayerRenderTask) {
-          self.textLayerRenderTask.expandTextDivs(false);
+          expandDivsTimer = setTimeout(function() {
+            self.textLayerRenderTask.expandTextDivs(false);
+          }, EXPAND_DIVS_TIMEOUT);
```
Comment (Snuffleupagus) [inline web/text_layer_builder.js]: Similar to comment https://github.com/mozilla/pdf.js/pull/7618/files#r78131484, let's do:
```javascript
//#if !(MOZCENTRAL || FIREFOX)
          expandDivsTimer = setTimeout(function() {
            self.textLayerRenderTask.expandTextDivs(false);
            expandDivsTimer = null;
          }, EXPAND_DIVS_TIMEOUT);
//#else
//        self.textLayerRenderTask.expandTextDivs(false);
//#endif
```

File: web/text_layer_builder.js [hunk 10]
```diff
@@ -321,11 +323,18 @@ var TextLayerBuilder = (function TextLayerBuilderClosure() {
     _bindMouse: function TextLayerBuilder_bindMouse() {
       var div = this.textLayerDiv;
       var self = this;
+      var expandDivsTimer = null;
       div.addEventListener('mousedown', function (e) {
         if (self.enhanceTextSelection && self.textLayerRenderTask) {
           self.textLayerRenderTask.expandTextDivs(true);
-          return;
+//#if !(MOZCENTRAL || FIREFOX)
+        if (expandDivsTimer) {
```
Comment (timvandermeij) [inline web/text_layer_builder.js]: The indenting is off here. This needs two more spaces, as well as the lines below, including the `return` and `}`. The preprocessor tags are fine like this and should not be indented.

**Comment by jeremypress** [comment]
Hi @timvandermeij, anything else needed here?

**Comment by timvandermeij** [comment]
I think it only needs to be tested in Chrome and other browsers. We will probably get to that soon though. In terms of code it looks good to me.

**Comment by jeremypress** [comment]
hey @timvandermeij, any update on this PR?

**Comment by timvandermeij** [comment]
I'm sorry for the late response here. The last few days have been rather busy and I forgot about reviewing this. I'll probably be able to review this later this week. I'll assign it to myself so it's in my review queue and create a new preview to get things going. Thanks for reminding me!

**Comment by jeremypress** [comment]
no worries @timvandermeij, thanks!

**Comment by timvandermeij** [comment]
Thank you for fixing this!

**Comment by agentcooper** [comment]
@jeremypress @timvandermeij 
Thanks for fixing this. However this brakes stuff in our app related to normal selection (click and drag). We rely on using [`Range.getClientRects`](http://devdocs.io/dom/range/getclientrects) to calculate selection boundaries and with the timeout we get wrong values there.

Because this fix is for double-clicking, I found following solves my problem and keeps the fix:

```diff
diff --git a/web/text_layer_builder.js b/web/text_layer_builder.js
index 0a03a42..19cefe1 100644
--- a/web/text_layer_builder.js
+++ b/web/text_layer_builder.js
@@ -363,7 +363,7 @@ var TextLayerBuilder = (function TextLayerBuilderClosure() {
           expandDivsTimer = setTimeout(function() {
             self.textLayerRenderTask.expandTextDivs(false);
             expandDivsTimer = null;
-          }, EXPAND_DIVS_TIMEOUT);
+          }, getSelection().isCollapsed ? EXPAND_DIVS_TIMEOUT : 0);
 //#else
 //        self.textLayerRenderTask.expandTextDivs(false);
 //#endif
```

Would you mind me sending a pull request for this?

**Comment by Snuffleupagus** [comment]
This patch is already a hack to fix a browser specific issue, but was deemed acceptable since double-clicking on words probably is a somewhat common operation.

However adding yet *another* hack on top of it (as https://github.com/mozilla/pdf.js/pull/7618#issuecomment-251116837 suggests) to deal with a use-case that doesn't really apply to the default viewer, but rather only to a custom deployment of it, does not seem wanted to me. (Note that it's mentioned in [multiple](http://mozilla.github.io/pdf.js/getting_started/) [places](https://github.com/mozilla/pdf.js/wiki/Setup-pdf.js-in-a-website#from-examples) that the default viewer isn't intended to be used as-is, but rather built upon in custom implementations.)

Hence a modification such as the mentioned in https://github.com/mozilla/pdf.js/pull/7618#issuecomment-251116837 seems to me to belong in custom implementation, rather than the default PDF.js viewer.

**Comment by timvandermeij** [comment]
I agree with the above. It's fine for a custom deployment, but not for the default viewer.
