### PR TITLE
Fallback to the built-in JPEG decoder when browser decoding fails, and attempt to handle JPEG images with DNL (Define Number of Lines) markers (issue 8614)

### LINKED ISSUE #8614: not possible to render (Error during JPEG image loading)
Link to PDF file (or attach file here): [OBW-OVK.pdf](https://github.com/mozilla/pdf.js/files/1125123/OBW-OVK.pdf)

Configuration:

- Webbrowser and its version: Chrome 59.0.3071.115

- Operatingsystem and its version: Microsoft Windows 7 Enterprise SP1

- PDF.js version: 1.8.516

- Is an extension: no

Steps to reproduce the problem:
1. Load attached pdf-file
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
Pdf has been rendered as blank pages. Error trace:

 Error: Invalid XRef stream header
util.js:296     at error (https://mozilla.github.io/pdf.js/build/pdf.worker.js:355:17)
    at XRef_readXRef [as readXRef] (https://mozilla.github.io/pdf.js/build/pdf.worker.js:21322:29)
    at XRef_parse [as parse] (https://mozilla.github.io/pdf.js/build/pdf.worker.js:20992:28)
    at PDFDocument_setup [as setup] (https://mozilla.github.io/pdf.js/build/pdf.worker.js:29900:17)
    at PDFDocument_parse [as parse] (https://mozilla.github.io/pdf.js/build/pdf.worker.js:29789:12)
    at _util.Util.inherit.ensure (https://mozilla.github.io/pdf.js/build/pdf.worker.js:39550:28)
    at Promise (<anonymous>)
    at LocalPdfManager_ensure [as ensure] (https://mozilla.github.io/pdf.js/build/pdf.worker.js:39545:14)
    at LocalPdfManager.BasePdfManager_ensureDoc [as ensureDoc] (https://mozilla.github.io/pdf.js/build/pdf.worker.js:39497:19)
util.js:282 Warning: Indexing all PDF objects
app.js:1056 PDF f5a022ce9c1cfd977eedadde6a39bd36 [1.2 - / -] (PDF.js: 1.8.516)
util.js:282 Warning: Error during JPEG image loading
util.js:282 Warning: Dependent image isn't ready yet
util.js:282 Warning: Error during JPEG image loading
util.js:282 Warning: Dependent image isn't ready yet

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### PR DESCRIPTION
**Pull request by Snuffleupagus**
*Please refer to the individual commit messages for additional details.*

Fixes #8614.

### CODE REVIEW

File: src/core/evaluator.js [hunk 1]
```diff
@@ -419,28 +420,47 @@ var PartialEvaluator = (function PartialEvaluatorClosure() {
...
-          };
-        }
-        return Promise.resolve();
+        return this.handler.sendWithPromise('obj', [
+          objId, this.pageIndex, 'JpegStream',
+          image.getIR(this.options.forceDataSchema)
+        ]).then(function() {
+          // Only add the dependency once we know that the native JPEG decoding
+          // succeeded, to ensure that rendering will always complete.
+          operatorList.addDependency(objId);
```
Comment (Rob--W) [inline src/core/evaluator.js]: I don't know this code, so correct me if I say something stupid.

Does the move of `addDependency` introduce any side effects? E.g. is it possible that by deferring the dependency, that at some point the operator list does not observe any dependencies and finishes too early?
If so, is it feasible to ensure that the dependency is resolved, even on failure?

File: src/core/evaluator.js [hunk 2]
```diff
@@ -419,28 +420,47 @@ var PartialEvaluator = (function PartialEvaluatorClosure() {
...
 
-      var nativeImageDecoderSupport = this.options.nativeImageDecoderSupport;
+      const nativeImageDecoderSupport = forceDisableNativeImageDecoder ?
+        NativeImageDecoding.NONE : this.options.nativeImageDecoderSupport;
       // If there is no imageMask, create the PDFImage and a lot
       // of image processing can be done here.
-      var objId = 'img_' + this.idFactory.createObjId();
-      operatorList.addDependency(objId);
-      args = [objId, w, h];
+      const objId = 'img_' + this.idFactory.createObjId();
```
Comment (Rob--W) [inline src/core/evaluator.js]: This change is unrelated to the commit. Can you undo it? It might be better to consistently convert the whole function (or even file) from `var` to `let` / `const` in one commit or PR (e.g. for consistency, I would expect `w` and `h` to also be constant, at the very least).

File: src/core/jpg.js [hunk 3]
```diff
@@ -635,7 +655,8 @@ var JpegImage = (function JpegImageClosure() {
   }
 
   JpegImage.prototype = {
-    parse: function parse(data) {
+    parse(data, options = {}) {
+      const dnlScanLines = options.dnlScanLines || null;
```
Comment (Rob--W) [inline src/core/jpg.js]: Why not:

```javascript
parse(data, { dnlScanLines = null }) {
```

File: src/core/jpg.js [hunk 4]
```diff
@@ -839,6 +862,13 @@ var JpegImage = (function JpegImageClosure() {
             break;
 
           case 0xFFDA: // SOS (Start of Scan)
+            numScanSegments++;
+            // A DNL marker (0xFFDC), if it exists, is only allowed at the end
+            // of the first scan segment and may only occur once in an image.
+            // Furthermore, to prevent an infinite loop, do *not* attempt to
+            // check DNL markers during re-parsing of the first scan segment.
+            const checkDNLMarker = numScanSegments === 1 && !dnlScanLines;
```
Comment (Rob--W) [inline src/core/jpg.js]: `dnlScanLines !== null` to avoid infinite recursion when the value is `0`.

File: src/core/jpg.js [hunk 5]
```diff
@@ -839,6 +862,13 @@ var JpegImage = (function JpegImageClosure() {
             break;
 
           case 0xFFDA: // SOS (Start of Scan)
+            numScanSegments++;
```
Comment (Rob--W) [inline src/core/jpg.js]: Do you really need to count? Can't you use a boolean `hasSeenSOS` ;)?

File: src/core/jpg.js [hunk 6]
```diff
@@ -28,6 +28,18 @@ let JpegError = (function JpegErrorClosure() {
   return JpegError;
 })();
 
+let DNLMarkerError = (function DNLMarkerErrorClosure() {
+  function DNLMarkerError(scanLines) {
```
Comment (Rob--W) [inline src/core/jpg.js]: This is an atypical Error constructor. Where is `message`?

**Review by Rob--W — CHANGES_REQUESTED** [review]
Thanks for this PR!
Have you tried jpeg-width-height-mismatch.pdf from #8628 ? If I recall correctly, that is the minimal test case that I created based on the original bug report.

File: src/core/evaluator.js (hunk 2 above)
Comment (Snuffleupagus) [reply src/core/evaluator.js]: This change was reverted.

File: src/core/evaluator.js (hunk 1 above)
Comment (Snuffleupagus) [reply src/core/evaluator.js]: > Does the move of addDependency introduce any side effects?

It shouldn't since we're still adding the dependency *before* the operator here; more below...

> E.g. is it possible that by deferring the dependency, that at some point the operator list does not observe any dependencies and finishes too early?

As far as I can tell, that shouldn't be a problem since the (now async) `buildPaintImageXObject` method won't be resolved until *either* this code-path or the fallback just below has completed successfully. This should thus ensure that the `operatorList` cannot be finished before the image resources are fully parsed and handled.

File: src/core/jpg.js (hunk 3 above)
Comment (Snuffleupagus) [reply src/core/jpg.js]: I've made the suggested change; however I also added some validation here, to ensure that the parameter is consistent with the JPEG specification.

File: src/core/jpg.js (hunk 6 above)
Comment (Snuffleupagus) [reply src/core/jpg.js]: (In this case, given that this `Error` is completely internal, it's perhaps not strictly needed.)

Fair point, I've updated the signature of `DNLMarkerError` to address this.

File: src/core/jpg.js (hunk 4 above)
Comment (Snuffleupagus) [reply src/core/jpg.js]: I think you meant `dnlScanLines === null` here!?
Otherwise it will have the opposite effect, regarding the infinite recursion issue.

Given that zero isn't a valid value, which is now being enforced, I left this comparison intact.

File: src/core/jpg.js (hunk 5 above)
Comment (Snuffleupagus) [reply src/core/jpg.js]: Perhaps not, but I do find the current state slightly clearer w.r.t. the specification.
With the proposed change you'd need to compare `hasSeenSOS === false` below (before setting `hasSeenSOS = true;`), which seems slightly strange when we've in fact actually encountered a SOS marker by entering this block.

File: src/display/dom_utils.js [hunk 7]
```diff
@@ -480,16 +480,17 @@ class DummyStatTimer {
...
-  img.onerror = (function loadJpegStream_onerrorClosure() {
-    objs.resolve(id, null);
-    warn('Error during JPEG image loading');
+function loadJpegStream(imageUrl) {
+  return new Promise((resolve, reject) => {
+    const img = new Image();
+    img.onload = function() {
+      resolve(img);
+    };
+    img.onerror = function(error) {
```
[the remark this answers is not in the document]
Comment (Snuffleupagus) [reply src/display/dom_utils.js]: Good point, it's removed now.

Also, in the new version of the PR this code was moved/re-factored such that https://github.com/mozilla/pdf.js/pull/9427#discussion_r165848545 is addressed as well.

**Review by Snuffleupagus — COMMENTED** [review]
Thank you for the review; I've attempted to address/answer all the comments/questions, please take a look.

> Have you tried jpeg-width-height-mismatch.pdf from #8628 ? If I recall correctly, that is the minimal test case that I created based on the original bug report.

I've tested that one, but it doesn't render in any of the other PDF readers that I tried: Adobe Reader, PDFium in Chrome, nor PDF.js (with this PR).
Comparing that PDF file with the original one, there isn't a DNL marker in that JPEG image so I'm not sure if it's really a good reduced test-case!?

File: src/display/api.js [hunk 8]
```diff
@@ -1818,8 +1817,18 @@ var WorkerTransport = (function WorkerTransportClosure() {
...
+              img.onload = function() {
+                resolve(img);
+              };
+              img.onerror = function() {
+                reject(new Error('Error during JPEG image loading'));
+              };
+              img.src = imageData;
+            }).then((img) => {
+              pageProxy.objs.resolve(id, img);
+            });
```
Comment (Rob--W) [inline src/display/api.js]: In case of an error, `pageProxy.objs.resolve` is not called any more. Is that change intentional?

File: src/core/jpg.js [hunk 9]
```diff
@@ -635,7 +657,13 @@ var JpegImage = (function JpegImageClosure() {
...
 
   JpegImage.prototype = {
-    parse: function parse(data) {
+    parse(data, { dnlScanLines = null, } = {}) {
+      if (dnlScanLines !== null && !Number.isInteger(dnlScanLines) &&
+          !(dnlScanLines >= 0x0001 && dnlScanLines <= 0xFFFF)) {
+        warn('JpegImage.parse - invalid "dnlScanLines" parameter: ' +
+             dnlScanLines);
+        dnlScanLines = null;
+      }
```
Comment (Rob--W) [inline src/core/jpg.js]: Since `dnlScanLines` is an internal parameter, and you already enforce that it is greater than 0, is it really necessary to strictly validate the value of `dnlScanLines` ?

Comment (Snuffleupagus) [reply src/core/jpg.js]: I suppose that we can do without this, I'll remove it.

File: src/display/api.js (hunk 8 above)
Comment (Snuffleupagus) [reply src/display/api.js]: Yes, this was intentional considering that when the native loading/decoding fails here we're now falling back to the built-in JPEG decoder. Hence we'll instead add the image to `pageProxy.objs` in the `case 'Image':` branch below, once the built-in decoding has happened.

Comment (Rob--W) [reply src/display/api.js]: I see. Can you add a comment after `reject(new Error('Error during JPEG image loading'));` that briefly explains that the error is handled by the fallback logic in `core/evaluator.js`?

**Review by Rob--W — APPROVED** [review]
Changes look good to me, with one more nit.

File: src/display/api.js (hunk 8 above)
Comment (Snuffleupagus) [reply src/display/api.js]: Sure, a comment has been added; thank you!

**Comment by Rob--W** [comment]
Since I'm not very familiar with the image processing code, I'd like another pair of eyes before merging it.

@yurydelendik Can you take a look?

**Comment by Snuffleupagus** [comment]
> Since I'm not very familiar with the image processing code, I'd like another pair of eyes before merging it.
> 
> @yurydelendik Can you take a look?

@yurydelendik Ping; do you have time to provide a final round of review here, so that this can land?

**Review by yurydelendik — APPROVED** [review]
Look good. Thank you for the patch.

**Comment by timvandermeij** [comment]
Thank you!
