### PR TITLE
[api-minor] Implement basic support for OptionalContent `Usage` dicts (issue 5764, bug 1826783)

### LINKED ISSUE #5764: 'Only print' watermark is shown ( incorrectly ) when viewed in browser
If to add a watermark to pdf file with Acrobat with 'Show when printing' (advanced option) enabled but 'Show when displaying on screen' option unchecked, then desktop pdf viewers view and print file correctly (show no watermarks, but print watermarks ), 

pdf.js will show watermark in both cases ( will not hide it when displaying on screen )

edit: example file http://www.sim-ai.org/errPage2.pdf

edit  I'm sorry to confuse bookmark with watermark - now text is correct ( but example is clear what the problem is - if to open file in desktop pdf viewer no across text is visible, but is incorrectly shown in pdf.js viewer )

### PR DESCRIPTION
**Pull request by Snuffleupagus**
The following are some highlights of this patch:
 - In the Worker we only extract a *subset* of the potential contents of the `Usage` dictionary, to avoid having to implement/test a bunch of code that'd be completely unused in the viewer.

 - In order to still allow the user to *manually* override the default visible layers in the viewer, the viewable/printable state is purposely *not* enforced during initialization in the `OptionalContentConfig` constructor.

 - Printing will now always use the *default* visible layers, rather than using the same state as the viewer (as was the case previously).
   This ensures that the printing-output will correctly take the `Usage` dictionary into account, and in practice toggling of visible layers rarely seem to be necessary except in the viewer itself (if at all).[1]

---
[1] In the unlikely case that it'd ever be deemed necessary to support fine-grained control of optional content visibility during printing, some new (additional) UI would likely be needed to support that case.

### CODE REVIEW

File: src/core/catalog.js [hunk 1]
```diff
@@ -469,7 +459,64 @@ class Catalog {
...
+    let intent = group.getArray("Intent");
+    if (!Array.isArray(intent)) {
+      intent = [intent];
+    }
+    if (intent.every(i => i instanceof Name)) {
+      obj.intent = intent.map(i => i.name);
+    }
+
+    const usage = group.get("Usage");
+    if (usage instanceof Dict) {
```
Comment (calixteman) [inline src/core/catalog.js:488]: nit: use the negation and a return in order to reduce the indentation.

**Review by calixteman — APPROVED** [review]
Overall it looks good to me. Thank you.
