### PR TITLE
Fix the "must highlight text in the right position" integration test

### LINKED ISSUE #17843: Fix integration test "find bar highlight all must highlight text in the right position"
This test is the only integration test that permafails for me locally on Linux; all other tests pass as expected. Interestingly it worked all this time on the bots, and looking at the purpose of the test it presumably has something to do with font size/settings being different on the bots. However, the test should be written in such a way that that doesn't matter, or Puppeteer should be configured to enforce a certain value so the host configuration doesn't matter for the test.

The full traceback is:

```
Failures:
1) find bar highlight all must highlight text in the right position
  Message:
    In chrome: Expected 38 to be less than 34.66.
  Stack:
        at <Jasmine>
        at fuzzyMatch (file:///home/timvandermeij/Documenten/Ontwikkeling/pdf.js/Code/test/integration/find_spec.mjs:21:6)
        at file:///home/timvandermeij/Documenten/Ontwikkeling/pdf.js/Code/test/integration/find_spec.mjs:65:11
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Promise.all (index 1)
  Message:
    In chrome: Expected 38 to be less than 34.66.
  Stack:
        at <Jasmine>
        at fuzzyMatch (file:///home/timvandermeij/Documenten/Ontwikkeling/pdf.js/Code/test/integration/find_spec.mjs:21:6)
        at file:///home/timvandermeij/Documenten/Ontwikkeling/pdf.js/Code/test/integration/find_spec.mjs:66:11
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Promise.all (index 1)
  Message:
    In firefox: Expected 38 to be less than 34.66.
  Stack:
        at <Jasmine>
        at fuzzyMatch (file:///home/timvandermeij/Documenten/Ontwikkeling/pdf.js/Code/test/integration/find_spec.mjs:21:6)
        at file:///home/timvandermeij/Documenten/Ontwikkeling/pdf.js/Code/test/integration/find_spec.mjs:65:11
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Promise.all (index 0)
  Message:
    In firefox: Expected 38 to be less than 34.66.
  Stack:
        at <Jasmine>
        at fuzzyMatch (file:///home/timvandermeij/Documenten/Ontwikkeling/pdf.js/Code/test/integration/find_spec.mjs:21:6)
        at file:///home/timvandermeij/Documenten/Ontwikkeling/pdf.js/Code/test/integration/find_spec.mjs:66:11
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Promise.all (index 0)
```

We should find out what this test aims to test exactly and either do the assertions differently (which is also nice so we don't have to hardcode a number) or configure Puppeteer such that host configuration becomes irrelevant for the test.

### PR DESCRIPTION
**Pull request by timvandermeij**
This commit implements the following improvements for the test:

- Replace the hardcoded highlight padding with a dynamic calculation. It turns out that the amount of padding can differ per system, possibly due to e.g. local (font) settings, which could cause the test to fail. The test now no longer implicitly depends on the environment.
- Remove the page offset subtraction. It's only needed for one assertion, and we can simply add the page offset there once.
- Improve the "magic" numbers in the test. The number 5 is removed now that the padding calculation made it obsolete, the number 28 is changed to 30 because that's the actual value in the PDF data and the number 4 is explained a bit more to state that the space also counts as a glyph.
- Annotate the steps and checks to improve readability of the test and to explain why certain calculations have to be performed.

Fixes #17843. The integration tests now consistently pass locally too :tada:

### CODE REVIEW

File: test/integration/find_spec.mjs [hunk 1]
```diff
@@ -39,35 +39,49 @@ describe("find bar", () => {
...
+          const parentBox = await parentSpan.boundingBox();
           const firstA = await highlights[0].boundingBox();
           const secondA = await highlights[1].boundingBox();
-          // Subtract the page offset from the text bounding boxes;
-          firstA.x -= pageBox.x;
-          firstA.y -= pageBox.y;
-          secondA.x -= pageBox.x;
-          secondA.y -= pageBox.y;
-          // They should be on the same line.
+          firstA.height -= firstA.height - parentBox.height;
```
Comment (calixteman) [inline test/integration/find_spec.mjs:63]: Isn't it equivalent to `firstA.height = parentBox.height` ?

**Review by calixteman — APPROVED** [review]
LGTM. Thank you for fixing this.

File: test/integration/find_spec.mjs (hunk 1 above)
Comment (timvandermeij) [reply test/integration/find_spec.mjs]: Yes, indeed. I have amended the patch to simplify this expression. Thanks!
