### PR TITLE
Apply bounding box before using shading patterns.

### LINKED ISSUE #8092: shading pattern bbox ignored
Link to PDF file (or attach file here):
https://issues.apache.org/jira/secure/attachment/12658953/axsh02.pdf

Configuration:
- Web browser and its version: FF 51.0.1  32bit
- Operating system and its version: W7
- PDF.js version: latest

Steps to reproduce the problem:
1. display file

What is the expected behavior? (add screenshot)
axsh02-screenshot-adobe

What went wrong? (add screenshot)
axsh02-screenshot-pdfjs

The shading pattern fills the whole page, but it should leave some white margins on all sides. I suspect that the BBox is ignored.

axsh02-screenshot-pdfdebugger

### PR DESCRIPTION
**Pull request by brendandahl**
Fixes #8092

### CODE REVIEW

File: src/core/pattern.js [hunk 1]
```diff
@@ -96,6 +96,7 @@ Shadings.RadialAxial = (function RadialAxialClosure() {
     var cs = dict.get('ColorSpace', 'CS');
     cs = ColorSpace.parse(cs, xref, res, pdfFunctionFactory);
     this.cs = cs;
+    this.bbox = dict.getArray('BBox');
```
Comment (Snuffleupagus) [inline src/core/pattern.js]: Would it make sense to normalize the bounding box here (as is done elsewhere in this file), i.e. `Util.normalizeRect(dict.getArray('BBox'));`, to prevent future issues?

Comment (timvandermeij) [reply src/core/pattern.js]: I agree since we have seen breakage because of that before (see #8168 and #10162).

File: src/display/pattern_helper.js [hunk 2]
```diff
@@ -17,17 +17,30 @@ import { FormatError, info, Util } from '../shared/util';
 
 var ShadingIRs = {};
 
+function applyBoundingBox(ctx, bbox) {
+  if (!bbox || typeof Path2D === 'undefined') {
+    return;
+  }
+  let width = bbox[2] - bbox[0];
```
Comment (timvandermeij) [inline src/display/pattern_helper.js]: This variable (and the two below) can be `const` instead of `let`.

**Comment by timvandermeij** [comment]
I think this is good to merge once the two comments above are resolved.

**Comment by brendandahl** [comment]
Sorry for the delay on this and the other patch. I ended up finding quite a few problems with how we're doing patterns with respect to transforms and the patch is turning into much more work. I'll hopefully have some more time this week to give it another stab.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Looks good; thank you!

/botio makeref
