### PR TITLE
Dont revoke blob URLs while printing but do it after

### LINKED ISSUE #19988: [Bug]: Print is broken with prebuilt on Firefox
### Attach (recommended) or Link to PDF file

.

### Web browser and its version

Firefox 139

### Operating system and its version

Windows 11

### PDF.js version

5.3.31

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Host the latest version of the prebuild on a personal server without any modifications.
3. Open the viewer page with the default PDF or upload any pdf
4. Try to print

### What is the expected behavior?

The print window open this the PDF preview

### What went wrong?

A blank page is previewed, except for a broken image in the center
If you press Shift + reload button, the print preview works.
But if I refresh again without the shift, the printout is broken again.

No error in console.

This works correctly with Chrome.

The demo of the https://mozilla.github.io/pdf.js/web/viewer.html site works correctly.

### Link to a viewer

_No response_

### Additional context

Image

What could be causing this?

### PR DESCRIPTION
**Pull request by calixteman**
It fixes #19988.

In Firefox, when printing, the document is cloned and use an image cache which isn't available when there's a service worker.

### CODE REVIEW

File: web/pdf_print_service.js [hunk 1]
```diff
@@ -201,13 +213,9 @@ class PDFPrintService {
...
-    promise
-      .catch(() => {
-        // Avoid "Uncaught promise" messages in the console.
-      })
-      .then(() => {
-        URL.revokeObjectURL(img.src);
-      });
+    promise.catch(() => {
+      // Avoid "Uncaught promise" messages in the console.
+    });
```
Comment (Snuffleupagus) [inline web/pdf_print_service.js:218]: Nit: Is this still needed, now that the promise is no longer being "used" here?

**Review by Snuffleupagus — APPROVED** [review]
r=me, thanks.

File: web/pdf_print_service.js (hunk 1 above)
Comment (calixteman) [reply web/pdf_print_service.js:218]: I'd have said yes in case `img.onerror` fired, it's consistent with the code we had before at least.

**Comment by jdeepwell** [comment]
Many thx to @calixteman for dealing with this!
