### PR TITLE
Fix failing integration test on Windows with Chrome

### LINKED ISSUE #18775: Fix the "Select text with the pointer hovering an existing highlight must check that an existing highlight is ignored on hovering" integration test
This integration test fails consistently on _only_ the Windows bot with the following traceback (see http://54.193.163.58:8877/662f7dec318944a/output.txt):

```
Failures:
1) Highlight Editor Select text with the pointer hovering an existing highlight must check that an existing highlight is ignored on hovering
  Message:
[31m    In chrome: Expected 1 to equal 0.[0m
  Stack:
        at <Jasmine>
        at file:///C:/pdfjs/botio-files-pdfjs/private/662f7dec318944a/test/integration/highlight_editor_spec.mjs:1880:58
        at async Promise.all (index 1)
        at async UserContext.<anonymous> (file:///C:/pdfjs/botio-files-pdfjs/private/662f7dec318944a/test/integration/highlight_editor_spec.mjs:1834:7)
```

The earliest occurrence I could find of this test failure is https://github.com/mozilla/pdf.js/pull/18698#issuecomment-2336406803, so perhaps that patch introduced a regression (other than https://github.com/mozilla/pdf.js/pull/18716). We could try to check if it still fails without that patch, and if so we might have a better idea about what changed.

PR #18721 attempts to debug/resolve this issue.

### PR DESCRIPTION
**Pull request by calixteman**
It fixes #18775.

### CODE REVIEW

**Comment by calixteman** [comment]
@timvandermeij The issue is fixed now: the root cause was about not having integer coordinates. I don't know if some was selected but for sure the `selectionchange` event wasn't triggered because of that.

File: test/integration/highlight_editor_spec.mjs [hunk 1]
```diff
@@ -1841,14 +1848,18 @@ describe("Highlight Editor", () => {
             "ternative compilation technique for dynamically-typed languages"
           );
           const editorSelector = getEditorSelector(0);
-          const x = rect.x + rect.width / 2;
+          const x = Math.round(rect.x + rect.width / 2);
```
Comment (timvandermeij) [inline test/integration/highlight_editor_spec.mjs:1851]: Instead of rounding values in this specific test, I think as indicated in https://github.com/mozilla/pdf.js/issues/18774#issuecomment-2395452333 it might be better to move this into `getSpanRectFromText` since that would also fix #18774 which is impacted by the same issue. Getting integer coordinates from this function is also what I would have expected somehow.

I'm still not _entirely_ sure why the current float coordinates don't work anymore after the mentioned PR, but I do know that float calculations can differ in precision depending on the browser implementation or architecture, so I think it's indeed best to remove that variable from the equation if we don't need that precision in the first place (which I'm assuming we don't).

File: test/integration/highlight_editor_spec.mjs [hunk 2]
```diff
@@ -1841,14 +1848,18 @@ describe("Highlight Editor", () => {
...
           let y = rect.y + rect.height / 2;
           await page.mouse.click(x, y, { count: 3, delay: 100 });
           await page.waitForSelector(editorSelector);
           await waitForSerialized(page, 1);
           await page.keyboard.press("Escape");
           await page.waitForSelector(`${editorSelector}:not(.selectedEditor)`);
 
+          const clickHandle = await waitForPointerUp(page);
```
Comment (timvandermeij) [inline test/integration/highlight_editor_spec.mjs:1859]: Why does this section have to be moved up in the test?

**Review by timvandermeij — COMMENTED** [review]
I'm happy that we have a solution in the works for this test now. Mostly looks good to me, with a few questions and s/Windws/Windows in the commit message.

File: test/integration/highlight_editor_spec.mjs (hunk 2 above)
Comment (calixteman) [reply test/integration/highlight_editor_spec.mjs:1859]: I'm not sure it's useful... my idea was to make sure that the pointerover callback is set after the pointer has been moved at its initial position.

File: test/integration/highlight_editor_spec.mjs (hunk 1 above)
Comment (calixteman) [reply test/integration/highlight_editor_spec.mjs]: So I added some rounding in th `getSpanRect` but we still need to round here because we divide the height by 2.

Comment (calixteman) [reply test/integration/highlight_editor_spec.mjs:1851]: We just need to have rounded values when we move the pointer in order to select some text, so I don't think it's useful, in general, to round the values returned by `getSpanRect...` (and it led to some issues).

File: test/integration/highlight_editor_spec.mjs [hunk 3]
```diff
@@ -1811,6 +1815,9 @@ describe("Highlight Editor", () => {
           }
```
Comment (timvandermeij) [inline test/integration/highlight_editor_spec.mjs:1815]: Shouldn't we also use `Math.round(y)` in the line above since `y` is divided in the loop? That'd also make it equal to the changes below.

File: test/integration/highlight_editor_spec.mjs [hunk 4]
```diff
@@ -1841,14 +1848,18 @@ describe("Highlight Editor", () => {
...
           let y = rect.y + rect.height / 2;
           await page.mouse.click(x, y, { count: 3, delay: 100 });
           await page.waitForSelector(editorSelector);
           await waitForSerialized(page, 1);
           await page.keyboard.press("Escape");
           await page.waitForSelector(`${editorSelector}:not(.selectedEditor)`);
 
+          const clickHandle = await waitForPointerUp(page);
+          y = rect.y - 3 * rect.height;
+          await page.mouse.move(x, Math.round(y));
```
Comment (timvandermeij) [inline test/integration/highlight_editor_spec.mjs:1861]: To increase similarity with the other test updated above in this PR I suggest we move the `Math.round` call for `y` here to line 1852 where the actual division happens so that this block is equal.

File: test/integration/text_layer_spec.mjs [hunk 5]
```diff
@@ -39,15 +39,21 @@ describe("Text layer", () => {
     }
 
     function middlePosition(rect) {
-      return { x: rect.x + rect.width / 2, y: rect.y + rect.height / 2 };
+      return {
```
Comment (timvandermeij) [inline test/integration/text_layer_spec.mjs:42]: I checked out this patch locally, but unfortunately these changes aren't enough to fix #18774. I'd therefore suggest we remove the changes to this file from this PR and work on this test in a separate PR, to speed up landing this PR first because the highlight test is more important as it fails on the bots.

(I initially thought both issues shared the same root cause after playing around with rounding in `getSpanRect`, but I should probably have thought about that better before suggesting we try to fix that one too in this PR; sorry for that.)

**Review by timvandermeij — APPROVED** [review]
r=me, with the comments below addressed. Thank you for doing this!

File: test/integration/text_layer_spec.mjs (hunk 5 above)
Comment (calixteman) [reply test/integration/text_layer_spec.mjs]: It's probably because I just keep the floor around the division because with a previous version, rect.x was an integer but now it isn't anymore.
That said it's probably better to do that in an other patch.
