### PR TITLE
Remove the tag for missing font subset when trying to find a substitution

### LINKED ISSUE #17929: Not embedded font subset can't be substitute
Attach (recommended) or Link to PDF file here:
[a.html.pdf](https://github.com/mozilla/pdf.js/files/14948183/a.html.pdf)

Configuration:
- Web browser and its version: Firefox nightly
- Operating system and its version: Windows 11

Steps to reproduce the problem:
1. Install the GoNotoCurrent-Regular font
2. Open the pdf with `pdfBug=all`
3. In looking the Font Inspector, we can infer that no substitution occurred.

Since the font is a subset, its name is prefixed with a tag which should be stripped out before trying to guess a substitution.

### PR DESCRIPTION
**Pull request by calixteman**
Fixes #17929.

### CODE REVIEW

File: src/core/font_substitutions.js [hunk 1]
```diff
@@ -456,19 +456,29 @@ function generateFont(
...
   if (baseFontName.startsWith("InvalidPDFjsFont_")) {
     return null;
   }
 
+  if (
+    (type === "TrueType" || type === "Type1") &&
+    /^[A-Z]{6}\+/.test(baseFontName)
+  ) {
+    // When the font is a subset, we need to remove the prefix (see 9.6.4).
+    baseFontName = baseFontName.slice(7);
```
Comment (timvandermeij) [inline src/core/font_substitutions.js:479]: Could you add the PDF file from the issue as a reference test so we have a PDF file that exercises this new logic to avoid regressions?

**Comment by timvandermeij** [comment]
It also looks like the Windows bot is down. @calixteman Could you reboot it?

File: src/core/font_substitutions.js [hunk 2]
```diff
@@ -456,19 +456,29 @@ function generateFont(
...
+  standardFontName,
+  type
 ) {
   if (baseFontName.startsWith("InvalidPDFjsFont_")) {
     return null;
   }
 
+  if (
+    (type === "TrueType" || type === "Type1") &&
+    /^[A-Z]{6}\+/.test(baseFontName)
```
Comment (timvandermeij) [inline src/core/font_substitutions.js:476]: I just noticed that we fortunately have unit tests for this function at https://github.com/mozilla/pdf.js/blob/master/test/unit/font_substitutions_spec.js so aside from the reference test it might be good to, if possible of course, add a unit test for this too since that could surface any regressions sooner since the unit tests are much faster to run.

**Review by timvandermeij — APPROVED** [review]
Looks like a good and simple solution to me, with the optional comment below; thanks! It would be good to also have @Snuffleupagus (when time permits) check this given my limited experience with the font conversion code.

**Review by Snuffleupagus — APPROVED** [review]
r=me, thanks.
