### PR TITLE
[Editor] Add the ability to make multiple selections (bug 1779582)

### LINKED ISSUE #15042: Support selecting multiple drawn elements
Currently you can select one by one, it would be nice to be able to select multiple elements and apply the same action to them (e.g. move them together by maintaining the relative distance between them, deleting them all, copying them all, etc.).

### PR DESCRIPTION
**Pull request by calixteman**
- several editors can be selected/unselected using ctrl+click;
- and then they can be copied, pasted, their properties can be changed.

### CODE REVIEW

File: src/display/editor/tools.js [hunk 1]
```diff
@@ -826,51 +889,25 @@ class AnnotationEditorUIManager {
...
 
-      this.addCommands({ cmd, undo, mustExec: true });
-    } else {
-      if (!this.#activeEditor) {
-        return;
-      }
-      const editor = this.#activeEditor;
-      this.#previousActiveEditor = this.#activeEditor = null;
-      cmd = () => {
+    const editors = [...this.#selectedEditors];
```
Comment (Snuffleupagus) [inline src/display/editor/tools.js:900]: *This __potential__ issue exists in the old code as well, but it's something that I just noticed:*

By the time that the `cmd` or `undo` functions run, is it possible the `#selectedEditors` has changed (e.g. it could have become empty) such that the constant `editors`-Array created here is no longer accurate?
So, should we perhaps instead be iterating through `this.#selectedEditors` in the loops below?

File: src/display/editor/tools.js [hunk 2]
```diff
@@ -904,42 +939,63 @@ class AnnotationEditorUIManager {
       return;
     }
 
+    this.unselectAll();
+
     const layer = this.#allLayers.get(this.#currentPageIndex);
     const newEditors = this.#clipboardManager
       .paste()
       .map(data => layer.deserialize(data));
```
Comment (Snuffleupagus) [inline src/display/editor/tools.js:947]: *A similar sort of question as above applies here as well.*

File: web/annotation_editor_layer_builder.css [hunk 3]
```diff
@@ -94,21 +99,17 @@
   outline: none;
 }
 
-.annotationEditorLayer .freeTextEditor:focus-within {
-  outline: var(--focus-outline);
-}
-
-.annotationEditorLayer .inkEditor:not(:focus) {
+.annotationEditorLayer .inkEditor.disabled:not(.selectedEditor) {
```
Comment (Snuffleupagus) [inline web/annotation_editor_layer_builder.css:102]: Is the *last* part actually necessary here, or does the following work (given the rule just below which override it when necessary)?
```suggestion
.annotationEditorLayer .inkEditor.disabled {
```

File: web/annotation_editor_layer_builder.css [hunk 4]
```diff
@@ -123,9 +124,8 @@
   cursor: auto;
 }
 
-.annotationEditorLayer .inkEditor:focus {
-  outline: var(--focus-outline);
-  resize: both;
+.annotationEditorLayer .background {
+  z-index: 0;
```
Comment (Snuffleupagus) [inline web/annotation_editor_layer_builder.css:128]: This was just removed, in another PR, so is this perhaps a rebase mistake?

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]

File: src/display/editor/tools.js [hunk 5]
```diff
@@ -757,22 +764,78 @@ class AnnotationEditorUIManager {
...
+      if (this.#selectedEditors.has(editor)) {
+        if (this.#selectedEditors.size >= 2) {
+          for (const ed of this.#selectedEditors) {
+            if (ed !== editor) {
+              ed.unselect();
+            }
+          }
+          this.#selectedEditors.clear();
+          this.#selectedEditors.add(editor);
+          this.#dispatchUpdateUI(editor.propertiesToUpdate);
```
[the remark this answers is not in the document]
Comment (calixteman) [reply src/display/editor/tools.js:788]: It's useless because the only value we could update is `hasSelectedEditor` but its value won't change since we already know that the `#selectedEditors` is non-empty, and after the removal it's still non-empty (we let the select editor inside).

File: src/display/editor/tools.js (hunk 1 above)
Comment (calixteman) [reply src/display/editor/tools.js:900]: Let's do the following:
 - create 2 editors A & B;
 - select all;
 - delete
 - undo

After deleting, `#selectedEditors` is empty (nothing is selected!) then if you undo in iterating on `#selectedEditors` then you'll get nothing.

File: src/display/editor/tools.js (hunk 2 above)
Comment (calixteman) [reply src/display/editor/tools.js:947]: The same, we'll undo/redo on the current state and not on what it was before.

File: src/display/editor/editor.js [hunk 6]
```diff
@@ -494,6 +536,29 @@ class AnnotationEditor {
   get contentDiv() {
     return this.div;
   }
+
+  /**
+   * If true then the editor is currently edited.
+   * @return {boolean}
```
Comment (Snuffleupagus) [inline src/display/editor/editor.js:542]: Looking at our other getters, elsewhere in the code-base, I believe that you want the following for things to work generally:
```suggestion
   * @type {boolean}
```

File: test/integration/freetext_editor_spec.js [hunk 7]
```diff
@@ -252,4 +252,176 @@ describe("Editor", () => {
...
+
+          await page.keyboard.down("Control");
+          await page.keyboard.press("c");
+          await page.keyboard.up("Control");
+
+          await page.keyboard.down("Control");
+          await page.keyboard.press("v");
+          await page.keyboard.up("Control");
+
+          // 0,1,3 are unselected and new paster editors are selected.
```
Comment (Snuffleupagus) [inline test/integration/freetext_editor_spec.js:357]: Nit: Did you mean the following?
```suggestion
          // 0,1,3 are unselected and newly pasted editors are selected.
```

File: test/integration/freetext_editor_spec.js [hunk 8]
```diff
@@ -252,4 +252,176 @@ describe("Editor", () => {
...
+          // Dismiss it.
+          await page.keyboard.press("Escape");
+
+          // Select all.
+          await page.keyboard.down("Control");
+          await page.keyboard.press("a");
+          await page.keyboard.up("Control");
+
+          // Select that all the editors are correctly selected (and the focus
+          // didn't move on the body when the empty editor has been removed).
```
Comment (Snuffleupagus) [inline test/integration/freetext_editor_spec.js:419]: Nit: Did you mean the following?
```suggestion
          // Check that all the editors are correctly selected (and the focus
          // didn't move to the body when the empty editor was removed).
```

File: test/integration/freetext_editor_spec.js [hunk 9]
```diff
@@ -252,4 +252,176 @@ describe("Editor", () => {
...
+            .withContext(`In ${browserName}`)
+            .toEqual([0, 2, 4, 5, 6]);
+
+          // Create an empty editor.
+          await page.mouse.click(rect.x + 700, rect.y + 100);
+          expect(await getSelected(page))
+            .withContext(`In ${browserName}`)
+            .toEqual([7]);
+
+          // Get the focus to 2 and check that only 2 is selected.
```
Comment (Snuffleupagus) [inline test/integration/freetext_editor_spec.js:399]: Nit: Did you mean the following?
```suggestion
          // Set the focus to 2 and check that only 2 is selected.
```

File: src/display/editor/tools.js [hunk 10]
```diff
@@ -757,22 +767,78 @@ class AnnotationEditorUIManager {
...
+    return this.#selectedEditors.size !== 0;
+  }
+
+  get isMultipleSelection() {
+    return this.#isMultipleSelection;
+  }
+
+  /**
+   * An editor just got a mousedown with ctrl key pressed.
+   * @param {boolean}} isMultiple
```
Comment (Snuffleupagus) [inline src/display/editor/tools.js:838]:
```suggestion
   * @param {boolean} isMultiple
```

File: src/display/editor/annotation_editor_layer.js [hunk 11]
```diff
@@ -546,6 +542,42 @@ class AnnotationEditorLayer {
...
+    this.#uiManager.unselect(editor);
+  }
+
+  get isMultipleSelection() {
+    return this.#uiManager.isMultipleSelection;
+  }
+
+  /**
+   * An editor just got a mousedown with ctrl key pressed.
+   * @param {boolean}} isMultiple
```
Comment (Snuffleupagus) [inline src/display/editor/annotation_editor_layer.js:575]:
```suggestion
   * @param {boolean} isMultiple
```

**Review by Snuffleupagus — APPROVED** [review]
