### PR TITLE
Revert "Remove the overflowing text special-case from `scrollIntoView` (issue 15714)"

### LINKED ISSUE #15739: Search Functionality Highlighting in white space
Attach (recommended) or Link to PDF file here:
https://mozilla.github.io/pdf.js/web/viewer.html
Configuration:
- Web browser and its version: Microsoft Edge v107.0.1418.56
- Operating system and its version: Windows 11 Enterprise v22H2
- PDF.js version:https://mozilla.github.io/pdf.js/web/viewer.html
- Is a browser extension: No

Steps to reproduce the problem:
1. Browse the site and search for "For" text - https://mozilla.github.io/pdf.js/web/viewer.html
2. which will highlight in white space

What is the expected behavior? (add screenshot)
Searching for text **"for"** and it got highlighted in while space
What went wrong? (add screenshot)
image

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Reverts mozilla/pdf.js#15721 for breaking Chromium browsers.

### CODE REVIEW

**Review by calixteman — APPROVED** [review]

File: web/ui_utils.js [hunk 1]
```diff
@@ -126,7 +126,9 @@ function scrollIntoView(element, spot, scrollMatches = false) {
   while (
     (parent.clientHeight === parent.scrollHeight &&
       parent.clientWidth === parent.scrollWidth) ||
-    (scrollMatches && parent.classList.contains("markedContent"))
+    (scrollMatches &&
+      (parent.classList.contains("markedContent") ||
+        getComputedStyle(parent).overflow === "hidden"))
```
Comment (Snuffleupagus) [inline web/ui_utils.js:131]: The following could possibly work as well, and would likely be more efficient than a `getComputedStyle` call, but with the upcoming release we probably shouldn't take unnecessary risks here.
```suggestion
        parent.classList.contains("textLayer")
```
