### PR TITLE
Parse Type1 font files to determine the various `Length{n}` properties, instead of trusting the PDF file (issue 5686, issue 3928)

### LINKED ISSUE #3928: Stops displaying the document, loops with 100% cpu power
```
[01:29:59.423] "PDF 506c30131bcce57b9e2d34b85f6f152 [1.5 Mac OS X 10.6.8 Quartz PDFContext / TeX] (PDF.js: 0.8.699)"

[01:30:00.447] "Warning: Unhandled rejection: [Exception... "The operation is insecure."  code: "18" nsresult: "0x80530012 (SecurityError)"  location: "resource://pdf.js/web/viewer.js Line: 1002"]"
```

stops displaying the document, loops with 100% cpu power

file: http://dl.acm.org/citation.cfm?id=2212350

### LINKED ISSUE #5686: Squares instead of spaces
In the recent builds, the spaces are replaced by the missing glyph indicator (squares in Firefox, squares with a '?' in Chrome) for some documents.

This is an improvement since previous versions didn't show any text at all, but we're not quite there yet.
Current pdf.js built-in version in Firefox v35 shows no text content for our test doc.

You can check a testcase at:
http://mozilla.github.io/pdf.js/web/viewer.html?file=http://ringabell.org/pdf_ko.pdf
current version is 1.0.1130, and the described behavior is present since at least 1.0.990

This issue seems close to https://github.com/mozilla/pdf.js/issues/5564 but it's not the exact same, as the test document provided there shows the missing glyph indicators in the current built-in viewer, whereas our testcase just shows no text at all.

### PR DESCRIPTION
**Pull request by Snuffleupagus**
- Make `Type1Font` more class-like, by adding closure
  
  > _Note:_ Ignoring whitespace should simplify reviewing a great deal.
  > https://github.com/Snuffleupagus/pdf.js/commit/a7978cc54781b482e11547336211d6132d4ea277?w=1
- Parse Type1 font files to determine the various `Length{n}` properties, instead of trusting the PDF file (issue 5686, issue 3928)
  
  > _Please note:_ In order to save time, I've not yet included any reduced test-cases in this patch. I'm happy to include tests, but I'd like the patch to be reviewed first, so that I don't waste time creating reduced test-cases for a patch before knowing if it's acceptable.
  > 
  > Fixes #5686.
  > Fixes #3928.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
@brendandahl Can you please provide feedback on the general direction of this patch (so that I know if it's worthwhile to continue working on it)?

/botio-windows preview

**Comment by brendandahl** [comment]
> @brendandahl Can you please provide feedback on the general direction of this patch (so that I know if it's worthwhile to continue working on it)?

General direction looks good. It may be worth looking at freetype within pdfium to see how they handle this case as well.

**Comment by Snuffleupagus** [comment]
> It may be worth looking at freetype within pdfium to see how they handle this case as well.

*Disclamer:* My knowledge of C isn't what it should be, so I might be misunderstanding the code, but from a cursory look through the [`t1parse.c` source code](https://pdfium.googlesource.com/pdfium/+/master/third_party/freetype/src/type1/t1parse.c#328) it appears that FreeType:
 1. Parses the font file to locate the "eexec" string, to determine the length of the header block.
 2. Parses the rest of the font file, i.e. the `eexec` block, not caring about a potential fixed-content block.

Again, I might not understant the FreeType code correctly!
But if the above is approximately correct, it looks to me that PR is doing something that is at least *similar*.

File: src/core/fonts.js [hunk 1]
```diff
@@ -3637,231 +3638,351 @@ var CFFStandardStrings = [
...
+          length: suggestedLength,
+        };
+      }
+    }
+    warn('Invalid "Length1" property in Type1 font -- trying to recover.');
+    stream.pos = streamStartPos; // Reset the stream position.
+
+    var actualLength = 0;
+    while (true) {
+      var scanBytes = stream.peekBytes(headerBytesLength);
```
Comment (brendandahl) [inline src/core/fonts.js]: `headerBytesLength` is potentially undefined here, is that okay?

File: src/core/fonts.js [hunk 2]
```diff
@@ -3637,231 +3638,351 @@ var CFFStandardStrings = [
...
+    var signatureLength = signature.length;
+    var scanLength = streamBytesLength - signatureLength;
+
+    var i = startIndex, j, found = false;
+    while (i < scanLength) {
+      j = 0;
+      while (j < signatureLength && streamBytes[i + j] === signature[j]) {
+        j++;
+      }
+      if (j >= signatureLength) { // `signature` found, skip over whitespace.
```
Comment (brendandahl) [inline src/core/fonts.js]: Why `>=` and not just `===`?

Comment (Snuffleupagus) [inline src/core/fonts.js]: I "copy-pasted" the basic functionality from https://github.com/mozilla/pdf.js/blob/master/src/core/parser.js#L477, so it's just a left over from that code. Do you want me to change it?

File: src/core/fonts.js (hunk 1 above)
Comment (Snuffleupagus) [inline src/core/fonts.js]: Yes, it's fine, since `undefined` just means that we'll get the entire stream. See the comment at https://github.com/mozilla/pdf.js/pull/7066/files#diff-d9f16d4d656cd2e962e0ad032dfba903R3681.

Comment (Snuffleupagus) [inline src/core/fonts.js]: Actually, it seems kind of dumb to get the *entire* stream at once like that, since the header usually isn't that long compared to the total length of a Type1 font file.
So I've pushed a new version of the patch, that searches the stream in smaller chunks instead.
