### PR TITLE
Use BiDi protocol for Chrome tests

### LINKED ISSUE #17961: Use WebDriver BiDi for Chrome
I have been looking at the integration test code and noticed the following code: https://github.com/mozilla/pdf.js/blob/master/test/test.mjs#L908-L910

Some time ago I tried using WebDriver BiDi for Chrome too and I recall it failed pretty soon back then. However, I tried again today with the current Puppeteer version and the results are much better now: only one test failure remains! Hence I figured now might be a good time to re-investigate WebDriver BiDi compatibility for Chrome, since it would be great if we could move away from CDP for all browsers we support.

I tried debugging this test, `FreeText Editor Freetext must stay focused after having been moved must keep the focus`, but I can't figure out why this works with CDP and fails with WebDriver BiDi. The traceback of the failing test is:

```
Failures:
1) FreeText Editor Freetext must stay focused after having been moved must keep the focus
  Message:
    ProtocolError: Protocol error (script.callFunction): unknown error Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed. ProtocolError: Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
        at <instance_members_initializer> (file:///home/timvandermeij/Documenten/Ontwikkeling/pdf.js/Code/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:89:14)
        at new Callback (file:///home/timvandermeij/Documenten/Ontwikkeling/pdf.js/Code/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:93:16)
        at CallbackRegistry.create (file:///home/timvandermeij/Documenten/Ontwikkeling/pdf.js/Code/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:19:26)
        at Connection._rawSend (file:///home/timvandermeij/Documenten/Ontwikkeling/pdf.js/Code/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:77:26)
        at CdpCDPSession.send (file:///home/timvandermeij/Documenten/Ontwikkeling/pdf.js/Code/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/CDPSession.js:63:33)
        at CDPClientAdapter.sendCommand (file:///home/timvandermeij/Documenten/Ontwikkeling/pdf.js/Code/node_modules/puppeteer-core/lib/esm/puppeteer/bidi/BidiOverCdp.js:106:39)
        at WindowRealm.callFunction (/home/timvandermeij/Documenten/Ontwikkeling/pdf.js/Code/node_modules/chromium-bidi/lib/cjs/bidiMapper/modules/script/Realm.js:243:58)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async WindowRealm.callFunction (/home/timvandermeij/Documenten/Ontwikkeling/pdf.js/Code/node_modules/chromium-bidi/lib/cjs/bidiMapper/modules/script/WindowRealm.js:136:16)
        at async ScriptProcessor.callFunction (/home/timvandermeij/Documenten/Ontwikkeling/pdf.js/Code/node_modules/chromium-bidi/lib/cjs/bidiMapper/modules/script/ScriptProcessor.js:59:16)
  Stack:
        at <instance_members_initializer> (file:///home/timvandermeij/Documenten/Ontwikkeling/pdf.js/Code/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:89:14)
        at new Callback (file:///home/timvandermeij/Documenten/Ontwikkeling/pdf.js/Code/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:93:16)
        at CallbackRegistry.create (file:///home/timvandermeij/Documenten/Ontwikkeling/pdf.js/Code/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:19:26)
        at BidiConnection.send (file:///home/timvandermeij/Documenten/Ontwikkeling/pdf.js/Code/node_modules/puppeteer-core/lib/esm/puppeteer/bidi/Connection.js:51:32)
        at Session.send (file:///home/timvandermeij/Documenten/Ontwikkeling/pdf.js/Code/node_modules/puppeteer-core/lib/esm/puppeteer/bidi/core/Session.js:172:42)
        at Session.<anonymous> (file:///home/timvandermeij/Documenten/Ontwikkeling/pdf.js/Code/node_modules/puppeteer-core/lib/esm/puppeteer/util/decorators.js:94:27)
        at WindowRealm.callFunction (file:///home/timvandermeij/Documenten/Ontwikkeling/pdf.js/Code/node_modules/puppeteer-core/lib/esm/puppeteer/bidi/core/Realm.js:92:51)
        at WindowRealm.<anonymous> (file:///home/timvandermeij/Documenten/Ontwikkeling/pdf.js/Code/node_modules/puppeteer-core/lib/esm/puppeteer/util/decorators.js:94:27)
        at #evaluate (file:///home/timvandermeij/Documenten/Ontwikkeling/pdf.js/Code/node_modules/puppeteer-core/lib/esm/puppeteer/bidi/Realm.js:126:42)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Interestingly I found that the test passes with WebDriver BiDi if I comment out this: https://github.com/mozilla/pdf.js/blob/7290faf840ab5a3828d12bbbb460bd8ad49f6ffa/test/integration/freetext_editor_spec.mjs#L2362-L2366

I have enabled verbose logging using the Puppeteer debugging instructions from https://github.com/puppeteer/puppeteer/blob/ef8c4c808aa9dddd4d2501c8fc160cfcd0c4b9d1/docs/guides/debugging.md?plain=1#L131 but I can't really interpret the output because I don't know much about the WebDriver BiDi protocol and Puppeteer internals.

To reproduce the issue:

1. Clone the repository.
2. Run `npm install`.
3. Change `cdp` to `webDriverBiDi` in https://github.com/mozilla/pdf.js/blob/7290faf840ab5a3828d12bbbb460bd8ad49f6ffa/test/test.mjs#L881
4. Change `it` to `fit` in https://github.com/mozilla/pdf.js/blob/7290faf840ab5a3828d12bbbb460bd8ad49f6ffa/test/integration/freetext_editor_spec.mjs#L2315 to only run this test.
5. Run `npx gulp integrationtest` and notice that the test hangs. If the protocol is changed to CDP the test passes. The verbose debugging logging can be obtained with `env DEBUG="puppeteer:*" npx gulp integrationtest`, for which it helps to change https://github.com/mozilla/pdf.js/blob/master/test/test.mjs#L961 to only run Chrome (otherwise Firefox also spams the logs).

@whimboo Is this perhaps something you could help out with? It could have surfaced a bug in the WebDriver BiDi implementation, but because I'm stuck on debugging this I also can't create a reduced test case to report to upstream...

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

File: test/test.mjs [hunk 1]
```diff
@@ -878,7 +878,7 @@ function unitTestPostHandler(req, res) {
 async function startBrowser({ browserName, headless, startUrl }) {
   const options = {
     product: browserName,
-    protocol: "cdp",
+    protocol: "webDriverBiDi",
```
Comment (timvandermeij) [inline test/test.mjs:881]: Please also amend the comment below to remove the `(CDP)` bit.

File: test/integration/scripting_spec.mjs [hunk 2]
```diff
@@ -418,41 +419,37 @@ describe("Interaction", () => {
...
 
-    afterAll(async () => {
-      await closePages(pages);
-    });
-
     it("must execute WillPrint and DidPrint actions", async () => {
-      await Promise.all(
-        pages.map(async ([browserName, page]) => {
-          if (process.platform === "win32" && browserName === "firefox") {
-            pending("Disabled in Firefox on Windows, because of bug 1662471.");
```
Comment (timvandermeij) [inline test/integration/scripting_spec.mjs:429]: It's really nice that we can now actually run this test everywhere now!

File: test/integration/freetext_editor_spec.mjs [hunk 3]
```diff
@@ -2354,14 +2354,14 @@ describe("FreeText Editor", () => {
             `${getEditorSelector(1)} .overlay.enabled`
           );
 
-          rect = await page.$eval(getEditorSelector(0), el => {
+          rect = await page.$eval(getEditorSelector(1), el => {
```
Comment (timvandermeij) [inline test/integration/freetext_editor_spec.mjs:2357]: Could you explain why the changes in this file are necessary and how they fix the issue? Looking at this test earlier I was a bit confused as to what this part of the test is achieving. Perhaps it could be resolved with more accompanying comments in the test to explain the intent of each "block" of logic (since the test is quite lengthy).

**Review by timvandermeij — COMMENTED** [review]
I'll have a detailed look at this tomorrow, but in the meantime here are my first observations.

File: test/integration/freetext_editor_spec.mjs (hunk 3 above)
Comment (calixteman) [reply test/integration/freetext_editor_spec.mjs:2357]: When taking the rect for editor 0 which now contains "A" and then clicking at rect.x+5*rect.width,rect.y+5*rect.height doesn't guarantee to be on the second editor.
I probably copy/paste some code without thinking about this.

**Comment by calixteman** [comment]
@OrKoN the ref tests failed on the linux bot because of an OOM crash. The bot has a 64 bits OS with 16Gb of RAM and afaik we never had this kind of issues with CDP in the last years.
And on the windows bot, it failed in the middle of the unit test with an exception (`TargetCloseError: Protocol error (Runtime.callFunctionOn): Target closed`).

**Comment by OrKoN** [comment]
@calixteman do all tests use Puppeteer or only integration?

**Comment by OrKoN** [comment]
I think I am not able to view the logs but I will give it a try later

**Comment by calixteman** [comment]
> @calixteman do all tests use Puppeteer or only integration?

The unit/ref/integration tests are using Puppeteer.

**Comment by calixteman** [comment]
> I think I am not able to view the logs but I will give it a try later

You should be able to just look at  http://54.193.163.58:8877/81255050207bcff/output.txt

**Comment by timvandermeij** [comment]
@OrKoN The logs of the run that crashed due to OOM can be found here: http://54.241.84.105:8877/17e8528589e75e3/output.txt. For completeness I'll also include the relevant bit here (the `TEST-PASS` line is the last bit of the PDF.js code):

```
TEST-PASS | eq test issue13751 | in firefox

<--- Last few GCs --->

[4032:0x6eba470]   422579 ms: Scavenge (reduce) 4087.8 (4127.6) -> 4087.9 (4128.6) MB, 2.1 / 0.0 ms  (average mu = 0.145, current mu = 0.047) allocation failure; 
[4032:0x6eba470]   422585 ms: Scavenge (reduce) 4088.8 (4128.6) -> 4088.7 (4129.3) MB, 3.1 / 0.0 ms  (average mu = 0.145, current mu = 0.047) allocation failure; 


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb7a940 node::Abort() [node]
 2: 0xa8e823  [node]
 3: 0xd5c940 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xd5cce7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xf3a3e5  [node]
 6: 0xf3b2e8 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
 7: 0xf4b7f3  [node]
 8: 0xf4c668 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xf26fce v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xf28397 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
11: 0xf088e0 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [node]
12: 0xf00354 v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawWithImmortalMap(int, v8::internal::AllocationType, v8::internal::Map, v8::internal::AllocationAlignment) [node]
13: 0xf02608 v8::internal::FactoryBase<v8::internal::Factory>::NewRawOneByteString(int, v8::internal::AllocationType) [node]
14: 0x1042959 v8::internal::JsonParser<unsigned short>::MakeString(v8::internal::JsonString const&, v8::internal::Handle<v8::internal::String>) [node]
15: 0x1044676 v8::internal::JsonParser<unsigned short>::ParseJsonValue() [node]
16: 0x104515f v8::internal::JsonParser<unsigned short>::ParseJson() [node]
17: 0xde2523 v8::internal::Builtin_JsonParse(int, unsigned long*, v8::internal::Isolate*) [node]
18: 0x16fb7b9  [node]
[11:30:57] 'runBotTest' errored after 8.62 min
[11:30:57] Error: Running browser tests failed.
    at ChildProcess.<anonymous> (file:///home/ubuntu/pdfjs/botio-files-pdfjs/private/17e8528589e75e3/gulpfile.mjs:731:15)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:552:15)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
    at Process.callbackTrampoline (node:internal/async_hooks:130:17)
```

**Comment by timvandermeij** [comment]
Would it perhaps be an idea to pull the test improvements out into a separate PR so we can already land them while we're figuring out what to do with the Chrome/WebDriver BiDi OOM bot issue?

It would make this PR smaller and we can then already benefit from the improved code, and run the previously disabled test on Windows. Together with the `waitForTimeout` removals I'm hoping that all these stability improvements will fix most of the flakiness in the integration tests and make debugging any remaining issues easier.

File: test/test.mjs [hunk 4]
```diff
@@ -907,13 +907,10 @@ async function startBrowser({
     options.args = ["--no-sandbox", "--disable-setuid-sandbox"];
     // silent printing in a pdf
     options.args.push("--kiosk-printing");
+    options.executablePath = "/tmp/chrome-linux64/chrome";
```
Comment (timvandermeij) [inline test/test.mjs:910]: I think we can remove this now that we confirmed a while ago that the Chrome Canary release didn't change behavior back then. This should also make the tests on the Windows bot work again.

**Comment by timvandermeij** [comment]
Looks good so far; let's see if the full test suite doesn't trigger the OOM killer anymore now that both Node.js and Puppeteer have been upgraded:

/botio test

**Comment by timvandermeij** [comment]
Yikes, it looks like the OOM killer still kicks in for Chrome. Somehow it keeps on eating memory; maybe it's not emptying the canvas memory anymore and it just keeps on reallocating? In any case, this does look like a bug at least triggered by using WebDriver BiDi. Time permitting I'll check if I can reproduce it locally soon, even though in the linked issue this was already tried and it didn't show up there...

**Comment by timvandermeij** [comment]
For Windows this is the same error as before in https://github.com/mozilla/pdf.js/pull/17962#issuecomment-2062133652, but it's not the OOM one anymore. Interestingly it fails after the same test, but those are probably run in a random order.

Let's await Linux and otherwise just try this again.

**Comment by timvandermeij** [comment]
Nice; aside from the usual intermittents the Linux bot now works!

Let's try Windows again:

/botio-windows test

**Comment by calixteman** [comment]
Let's retry.
/botio-windows test

**Comment by timvandermeij** [comment]
Let's try it a couple more times to see if the bots remain happy now that the old processes have been killed. Fingers crossed!

/botio test

**Comment by timvandermeij** [comment]
Hm, that's the third time it crashes right after the `TEST-PASSED | gets operatorList, with page resources containing corrupt /CCITTFaxDecode data | in chrome` line, so sadly it looks like something we'll have to address on Windows before we can continue with this patch.

**Comment by calixteman** [comment]
The last run failed on the same test and let a chrome process running and using some cpu.
There is nothing especially interesting in the logs unfortunately.
^^ @OrKoN

**Comment by timvandermeij** [comment]
I've found an issue in our testing framework that, under some circumstances, causes Chrome to remain alive if Firefox is already closed. It's reproducible and I _think_ it's also what made the Chrome process linger around here. Even though it's hard to tell for sure if that's also exactly what caused the issue above, simply because I cannot reproduce this exact Windows bot issue locally, I'm working on a PR to fix that because either way that's an issue in our code.

We should rebase this and try again once that fix and #18367 are in place (so we have the most recent Puppeteer versions, the most recent Chrome version and the fix for https://github.com/GoogleChromeLabs/chromium-bidi/issues/2317 which should improve the logs we get). I hope that with all that in place we won't have the problem of lingering processes anymore and that the logs are more actionable if any problems remain.

**Comment by timvandermeij** [comment]
@calixteman Now that the above is all done, could you rebase this patch onto the current master so we can try this again and hopefully have better logs if the problem still occurs?

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
It's really nice that after all this time we can now land this. Thanks everyone for helping out with this effort, because this now works due to a combination of fixes here and upstream in the Puppeteer project!
