### PR TITLE
Fix bad truetype loca tables.

### LINKED ISSUE #11131: Certain PDF displays with Scrambled Text in PDF.js
Attach (recommended) or Link to PDF file here:

[IOICityHotel-SCB 4198-Bank statement-July17 6.pdf](https://github.com/mozilla/pdf.js/files/3591674/IOICityHotel-SCB.4198-Bank.statement-July17.6.pdf)

Configuration:
- Web browser and its version: Chrome 76.0.3809.132, Firefox 69.0, Internet Explorer 11.950.17134.0, Edge 42.17134.1.0
- Operating system and its version: Windows 10 (version 1803, OS Build 17134.984)
- PDF.js version: 1.7.225, also version used in latest firefox
- Is a browser extension: no

Steps to reproduce the problem:
1. Open attached PDF in PDF.js (drag into empty tab of latest Firefox)
2. Visually inspect PDF and observe dev console

What is the expected behavior? (add screenshot) 

PDF displays correct. See pic of PDF opened in Adobe Acrobat. 

What went wrong? (add screenshot)

PDF.js displays blank pane. See screenshot of embedded viewer. 

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### PR DESCRIPTION
**Pull request by brendandahl**
Some fonts have loca tables that aren't sorted or use 0 as an offset to
signal a missing glyph. This fixes the bad loca tables by sorting them
and then rewriting the loca table and potentially re-ordering the glyf
table to match.

Fixes #11131, #11561
and
https://bugzilla.mozilla.org/show_bug.cgi?id=1650302
https://bugzilla.mozilla.org/show_bug.cgi?id=846014
https://bugzilla.mozilla.org/show_bug.cgi?id=844092

### CODE REVIEW

File: src/core/fonts.js [hunk 1]
```diff
@@ -2050,35 +2050,45 @@ var Font = (function FontClosure() {
...
+            endOffset: 0,
+          });
+        }
+        locaEntries.sort((a, b) => {
+          return a.offset - b.offset;
+        });
+        // Now the offsets are sorted, calculate the end offset of each glyph.
+        for (i = 0; i < numGlyphs; i++) {
+          locaEntries[i].endOffset = locaEntries[i + 1].offset;
+        }
```
Comment (Snuffleupagus) [inline src/core/fonts.js:2078]: Doesn't this mean that the *last* loca-table entry will still have a zero `endOffset`, i.e. `locaEntries[numGlyphs].endOffset === 0`; is that not a problem?

Unless I'm overlooking something here, this means that `sanitizeGlyph` will just reject the glyph since it's deemed empty!?

File: src/core/fonts.js [hunk 2]
```diff
@@ -2050,35 +2050,45 @@ var Font = (function FontClosure() {
         var oldGlyfData = glyf.data;
         var oldGlyfDataLength = oldGlyfData.length;
         var newGlyfData = new Uint8Array(oldGlyfDataLength);
-        var startOffset = itemDecode(locaData, 0);
-        var writeOffset = 0;
+
+        // The spec says the offsets should be in ascending order, however
+        // this is not true for some fonts or they use the offset of 0 to mark a
+        // glyph as missing. OTS requires the offsets in order and not to
```
Comment (Snuffleupagus) [inline src/core/fonts.js:2056]: Nit: Looks like a missing "to be" here, i.e. it probably should read:
`// glyph as missing. OTS requires the offsets to be in order and not to`

File: src/core/fonts.js (hunk 1 above)
Comment (brendandahl) [reply src/core/fonts.js:2078]: It's a bit confusing since there are `numGlyphs + 1` loca entries. Down below we don't iterate over the last loca entry (`i < numGlyphs`), but it's data is effectively saved in the previous entry when endOffset is read here.

I think I'll add some more comments, and maybe change the above `i <= numGlyphs` to `i < numGlyphs + 1` to make it more explicit.

**Review by Snuffleupagus — APPROVED** [review]
r=me, with passing tests; really nice work fixing a bunch of font bugs all at once!

**Comment by brendandahl** [comment]
Also fixes https://bugzilla.mozilla.org/show_bug.cgi?id=844092
