### PR TITLE
Avoid exceptions in the console with ill-formed flate streams

### LINKED ISSUE #18876: [Bug]: Uncaught error on unexpected data after end of stream
### Attach (recommended) or Link to PDF file

[PDF_FILE-1.pdf](https://github.com/user-attachments/files/17320406/PDF_FILE-1.pdf)

### Web browser and its version

Chrome 129.0.6668.10 / Firefox 131.0

### Operating system and its version

macOS Sonoma 14.6.1 / Ubuntu 22.04.5

### PDF.js version

4.4.168

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Go to https://jsfiddle.net/tr2h1j8f/
1. Open the DevTools console
1. Click the Run button

### What is the expected behavior?

No errors should appear in the console.

### Chrome

The `Uncaught (in promise) TypeError: Junk found after end of compressed data.` error appears in the console.

image

### Firefox

The `TypeError: Unexpected input after the end of stream` error appears in the console.

image

### Link to a viewer

_No response_

### Additional context

Related code:

https://github.com/mozilla/pdf.js/blob/233ac1773da43cf7557615b659b56ac5ef2fc431/src/core/flate_stream.js#L157-L197

This error occurs because promises returned by `writer.write(bytes);` and `writer.close();` are not being awaited. There’s a reason for this though which is explained in https://github.com/whatwg/compression/issues/55#issuecomment-1614476837.

A potential solution could be to discard the errors
```js
writer.write(bytes).catch(() => {});
writer.close().catch(() => {});
```
They will still be caught by the `catch` block when awaited here

https://github.com/mozilla/pdf.js/blob/233ac1773da43cf7557615b659b56ac5ef2fc431/src/core/flate_stream.js#L170

### PR DESCRIPTION
**Pull request by calixteman**
It fixes #18876.

### CODE REVIEW

File: src/core/flate_stream.js [hunk 1]
```diff
@@ -161,8 +161,19 @@ class FlateStream extends DecodeStream {
...
+      // starts which happens few lines below.
+      writer
+        .write(bytes)
+        .then(async () => {
+          try {
+            await writer.ready;
+            await writer.close();
+          } catch {}
+        })
+        .catch(() => {});
```
Comment (Snuffleupagus) [inline src/core/flate_stream.js:176]: Isn't the try-catch redundant here, since any error thrown there *should* already be caught by the catch-handler at the end!?
```suggestion
        .then(async () => {
          await writer.ready;
          await writer.close();
        })
        .catch(() => {});
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you.
