### PR TITLE
Add support for right-clicking on images (bug 1012805)

### LINKED ISSUE #6347: Add option to copy/export images
Is there a way to implement the Adobe Reader selection tool (and have it the default option when opening new files) so that parts of the text and/or images can be copied and pasted outside as an image?

Expected behavior for copying image:
1. move mouse cursor over image in pdf
2. press the right mouse button OR double click left mouse button
3. option to copy image displayed in dropdown menu OR CTRL+C

Expected behavior for copying a selection of an image
1. move mouse cursor over image
2. press and hold the left mouse button
3. drag the mouse cursor until desired part of the image is highlighted
4. right click and select copy image OR press CTRL+C
5. open external image editor and paste selection of image

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
> Add support for right-clicking on images
> 
> This patch adds right-click support for images in the PDF, allowing
> users to download them. To minimize memory consumption, we:
> - Do not store the images separately, and instead crop them out of the
>   PDF page canvas
> - Only extract the images when needed (i.e. when the user right-clicks
>   on them), rather than eagerly having all of them available.
> 
> To do so, we layer one empty 0x0 canvas per image, stretched to cover
> the whole image, and only populate its contents on right click.
> These images need to be inside the text layer: they cannot be _behind_
> it, otherwise they would be covered by the text layer's container and
> not be clickable, and they cannot be in front of it, otherwise they
> would make the text spans unselectable.
> 
> This feature is managed by a new preference, `imagesRightClickMinSize`:
> - when it's set to `-1`, right-click support is disabled
> - when set to `0`, all images are available for right click
> - when set to a positive integer, only images whose width and height are
>   greater than or equal to that value (in the PDF page frame of
>   reference) are available for right click.

Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1012805

TODO:
- [x] Fix handling of images that are rotated (see TODO in the code)
- [x] Add tests

### CODE REVIEW

File: test/integration/text_layer_images_spec.mjs [hunk 1]
```diff
@@ -0,0 +1,159 @@
+/* Copyright 2024 Mozilla Foundation
```
Comment (timvandermeij) [inline test/integration/text_layer_images_spec.mjs]: Nit: s/2024/2026

File: test/webserver.mjs [hunk 2]
```diff
@@ -46,7 +46,7 @@ class WebServer {
   constructor({ root, host, port, cacheExpirationTime }) {
     const cwdURL = pathToFileURL(process.cwd()) + "/";
     this.rootURL = new URL(`${root || "."}/`, cwdURL);
-    this.host = host || "localhost";
+    this.host = host; // || "localhost";
```
Comment (timvandermeij) [inline test/webserver.mjs]: This change should probably be reverted.

File: src/display/text_layer_images.js [hunk 3]
```diff
@@ -0,0 +1,133 @@
+import { Util } from "../shared/util.js";
+
+function percentage(value) {
+  return `${(value * 100).toFixed(2)}%`;
+}
+
+class TextLayerImages {
```
Comment (timvandermeij) [inline src/display/text_layer_images.js:26]: It might be good to add a small docstring to this class to explain its purpose.

File: src/display/canvas_dependency_tracker.js [hunk 4]
```diff
@@ -909,4 +917,141 @@ const Dependencies = {
   transformAndFill: ["transform", "fillColor"],
 };
 
-export { CanvasDependencyTracker, CanvasNestedDependencyTracker, Dependencies };
+class CanvasImagesTracker {
```
Comment (timvandermeij) [inline src/display/canvas_dependency_tracker.js:1101]: It might be good to add a small docstring to this class to explain its purpose.

File: web/text_layer_builder.js [hunk 5]
```diff
@@ -83,7 +83,7 @@ class TextLayerBuilder {
    * @param {TextLayerBuilderRenderOptions} options
    * @returns {Promise<void>}
    */
-  async render({ viewport, textContentParams = null }) {
+  async render({ viewport, images, textContentParams = null }) {
```
Comment (timvandermeij) [inline web/text_layer_builder.js:89]: The `TextLayerBuilderRenderOptions` type should be updated accordingly.

**Review by timvandermeij — COMMENTED** [review]
I did a first pass over this PR, which resulted in the following comments. Overall this looks really good, and we can run the tests after this has been addressed.

File: test/webserver.mjs (hunk 2 above)
Comment (nicolo-ribaudo) [reply test/webserver.mjs]: I opened https://github.com/mozilla/pdf.js/pull/20646 so that I can stop having to comment this line out when testing on mobile.

File: web/pdf_page_view.js [hunk 6]
```diff
@@ -664,6 +676,7 @@ class PDFPageView extends BasePDFPageView {
         this.detailView ??= new PDFPageDetailView({
           pageView: this,
           enableOptimizedPartialRendering: this.enableOptimizedPartialRendering,
+          imagesRightClickMinSize: false,
```
Comment (calixteman) [inline web/pdf_page_view.js]: Shoudn't it be -1 ?

File: src/display/api.js [hunk 7]
```diff
@@ -1761,6 +1776,10 @@ class PDFPageProxy {
     return textContent;
   }
 
+  getImagesCoordinates() {
```
Comment (calixteman) [inline src/display/api.js]: It's unused or am I missing something ?

File: src/display/api.js [hunk 8]
```diff
@@ -1483,6 +1488,7 @@ class PDFPageProxy {
     pageColors = null,
     printAnnotationStorage = null,
     isEditing = false,
+    recordImages = true,
```
Comment (calixteman) [inline src/display/api.js]: I think it should false by default.

File: src/display/text_layer_images.js [hunk 9]
```diff
@@ -0,0 +1,144 @@
...
+      }
+
+      if (TextLayerImages.#activeImage === imgElement) {
+        return;
+      }
+      if (TextLayerImages.#activeImage) {
+        TextLayerImages.#activeImage.width = 0;
+        TextLayerImages.#activeImage.height = 0;
+      }
+      TextLayerImages.#activeImage = imgElement;
```
Comment (calixteman) [inline src/display/text_layer_images.js]: Maybe we could use a WeakRef here.

File: src/display/canvas.js [hunk 10]
```diff
@@ -3068,11 +3070,19 @@ class CanvasGraphics {
       imgData.interpolate
     );
 
-    this.dependencyTracker
-      ?.resetBBox(opIdx)
-      .recordBBox(opIdx, ctx, 0, width, -height, 0)
-      .recordDependencies(opIdx, Dependencies.imageXObject)
-      .recordOperation(opIdx);
+    if (this.dependencyTracker) {
+      this.dependencyTracker
```
Comment (calixteman) [inline src/display/canvas.js:3070]: So here we're recording all the dependencies just for having the clipbox.
Could it induce some performance regressions in general ?
If yes would it be possible to have a kind of lightweight clip-box tracker ?

Comment (nicolo-ribaudo) [reply src/display/canvas.js:3070]: I'm going to record the overhead here to see if it's worth it.

Comment (nicolo-ribaudo) [reply src/display/canvas.js:3070]: Done, we indeed skip a significant chunk of work because we don't care about updating the bboxes of the dependencies. I left it in a separate commit to simplify reviewing.

**Comment by nicolo-ribaudo** [comment]
The "Separate bbox tracking from dependencies tracking" commit does not add any new logic in `canvas_dependency_tracker.js`. It only extracts some of the existing logic in a new `CanvasBBoxTracker` class, that `CanvasDependencyTracker` delegates to for the bboxes logic.

File: src/display/text_layer_images.js [hunk 11]
```diff
@@ -0,0 +1,145 @@
+import { Util } from "../shared/util.js";
```
Comment (Snuffleupagus) [inline src/display/text_layer_images.js:16]: Nit: This file is missing a license header.

File: web/app_options.js [hunk 12]
```diff
@@ -245,6 +245,12 @@ const defaultOptions = {
     value: typeof PDFJSDev === "undefined" || PDFJSDev.test("TESTING"),
     kind: OptionKind.VIEWER + OptionKind.PREFERENCE,
   },
+  imagesRightClickMinSize: {
+    /** @type {number} */
+    value:
+      typeof PDFJSDev !== "undefined" && PDFJSDev.test("GECKOVIEW") ? -1 : 16,
+    kind: OptionKind.VIEWER + OptionKind.PREFERENCE,
+  },
```
Comment (Snuffleupagus) [inline web/app_options.js]: Nit: Please keep each option-kind sorted alphabetically.

**Comment by nicolo-ribaudo** [comment]
The text selection failures _might_ be related to this PR, as it adds things to the text layer.

**Comment by nicolo-ribaudo** [comment]
Updated to be only enabled by default in MOZCENTRAL, as these images break the workaround for text selection in Chrome/Safari. The tests for text selection explicitly enable the preference in Firefox to check that they don't conflict there.

Hopefully that workaround won't be needed anymore once https://github.com/WebKit/WebKit/pull/59016 and https://chromium-review.googlesource.com/c/chromium/src/+/7617189 are merged/released, and then we can enable this new feature by default everywhere.

/botio-linux integrationtest

File: src/display/api.js [hunk 13]
```diff
@@ -1555,6 +1563,10 @@ class PDFPageProxy {
         }
       }
 
+      if (shouldRecordImages) {
+        this.imageCoordinates = internalRenderTask.gfx?.imagesTracker.take();
```
Comment (calixteman) [inline src/display/api.js:1567]: Is it a good idea to save the coordinates in case of error ?

File: src/display/canvas_dependency_tracker.js [hunk 14]
```diff
@@ -918,4 +1092,147 @@ const Dependencies = {
...
+
+          const finalBBoxWidth = maxX - minX;
+          const finalBBoxHeight = maxY - minY;
+
+          const sin2 = sin * sin;
+          const cos2 = cos * cos;
+          const cosSin = cos * sin;
+          const denom = cos2 - sin2;
+
+          const a = (finalBBoxHeight * cos2 - finalBBoxWidth * cosSin) / denom;
```
Comment (calixteman) [inline src/display/canvas_dependency_tracker.js:1213]: What about denom being 0 ?

Comment (nicolo-ribaudo) [reply src/display/canvas_dependency_tracker.js:1213]: Uhm this is tricky. If denom is 0 it's because the image was rotated by 45deg, which means that the final bbox is a square, so here we are getting a `0 / 0` division.

When the angle is 45deg there are indeed multiple solutions to this equation (think about a rectangle rotated by 45deg and put inside a square: you can make one side longer and the other shorter, while still fitting inside the square). We can choose multiple approaches:
- Assume that the image fits in a square, and give as result a square rotated by 45deg that fits in the bounding box
- Assume that the cut/shrank image has the same aspect ratio as the original version, and return a rectangle rotated by 45deg that preserves that original aspect ratio and fits in the square

There isn't enough data here to know which one is correct, because it would require fully track the _exact_ clip path (rather than just its bounding box) across all operations.

One last option is to "give up" when there is a 45deg rotation and just return a non-rotated rectangle that covers the bounding box.

**Comment by nicolo-ribaudo** [comment]
The reftest failures are probably a regression in the extracted bbox tracking logic.

File: src/display/api.js (hunk 13 above)
Comment (nicolo-ribaudo) [reply src/display/api.js:1567]: It's indeed useless, as we don't create the text layer images if there is an error. I'll remove it.

**Comment by nicolo-ribaudo** [comment]
I think both the Windows unit test failure and the Linux integration test failure are unrelated. The reftest failure is the same one that's happening elsewhere.

**Review by calixteman — APPROVED** [review]
LGTM. Thank you.
