### PR TITLE
Take into account PageOpen and PageClose actions which are present in some fields

### LINKED ISSUE #18305: Widget Annotation: PageOpen (/PO) and PageClose (/PC) events are not reacted upon
Attach (recommended) or Link to PDF file here: [triggers.pdf](https://github.com/user-attachments/files/15914263/triggers.pdf)

Configuration:
- Web browser and its version: Firefox 126.0.1
- Operating system and its version: Gentoo Linux
- PDF.js version: 4.1.379
- Is a browser extension: no

Steps to reproduce the problem:
1. Open the attached two-page PDF. On the second page, there is a pushbutton that, within its `AA` (AdditionalActions) dictionary, defines actions for the `PageOpen`/`PageClose` (`/PO` and `/PC` entries) and for the `MouseDown`/`MouseUp` (`/D` and `/U` entries) trigger events. As actions, appropriate debug messages are written into the browser console.
2. When scrolling forth and back to and from the page with the Widget Annotation, the expected debug messages `PageOpen` and `PageClose` should be printed into the console.
 
What is the expected behavior?

When scrolling forth and back in the 2-page document, corresponding debug messages should appear in the browser console.

What went wrong?

Nothing happens when scrolling between the document pages. Thus, `PageOpen` and `PageClose` do not trigger the associated actions. Only  mouse interaction with the Widget Annotation is functional, `MouseDown` and `MouseUp` events are reacted upon and corresponding debug messages appear in the browser console.

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

File: test/integration/scripting_spec.mjs [hunk 1]
```diff
@@ -2456,4 +2456,58 @@ describe("Interaction", () => {
...
+      );
+      pages = await loadAndWait("issue18305.pdf", getSelector("7R"));
+    });
+
+    afterAll(async () => {
+      await closePages(pages);
+      await Promise.all(otherPages.map(page => page.close()));
+    });
+
+    it("must check the actions PageOpen/PageClose are correctly executed", async () => {
```
Comment (Snuffleupagus) [inline test/integration/scripting_spec.mjs:2478]: Nit:
```suggestion
    it("must check that PageOpen/PageClose actions are correctly executed", async () => {
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you!
