### PR TITLE
[JS] Try to guess what the date is when it doesn't follow the given format (issue #15490)

### LINKED ISSUE #15490: Form Field with date format is handled incorrectly for different browsers.
Attach (recommended) or Link to PDF file here:
[PDF mit Datum_edit.pdf](https://github.com/mozilla/pdf.js/files/9622672/PDF.mit.Datum_edit.pdf)

Configuration:
- Web browser and its version: Chrome Version 105.0.5195.127 (Offizieller Build) (64-Bit) / Firefox 105.0 (64-Bit)
- Operating system and its version: Windows 11 Pro 21H2 (German de-DE)
- PDF.js version: v2.16.105
- Is a browser extension: no
- PDF is in en-EN, but same behaviour for de-DE (or de-AT, which was the original problem)

Steps to reproduce the problem in **Chrome**:
1. Open attached PDF with PDFjs in Chrome
2. Enter a date into a date field (e.g. field labeled "von") in the format "d.M.yyyy" (e.g. skipping the leading zero from 01.09.2022 -> 1.9.2022)
3. Click out of the Field to lose focus
4. Date is displayed in format "MM.dd.yyyy"

What is the expected behavior? (add screenshot)
Date is displayed in original format OR date is displayed in "dd.MM.yyyy" format OR an error is shown in the browser stating the format is invalid

Steps to reproduce the problem in **Firefox**:
1. Open attached PDF with PDFjs in Firefox
2. Enter a date into a date field (e.g. field labeled "von") in the format "d.M.yyyy"
3. Click out of the Field to lose focus
4. An Error is shown in the browser stating the format is invalid.

What is the expected behavior? (add screenshot)
Date is displayed in original format OR date is displayed in "dd.MM.yyyy" format OR an error is shown in the browser stating the format is invalid

What went wrong? (add screenshot)
As far as I can tell, the browsers support different date Formats when parsing a string to a date. 
With chrome the date beeing swapped can easily be overlooked. 
Entering "1.9.2022" in a date field and instead of the 1st of september you get the 9th of january can be fatal.

### PR DESCRIPTION
**Pull request by calixteman**
We use the format to guess in which order we can find month, day, ... we get the numbers in the date and consider them as month, day, ...

### CODE REVIEW

File: test/unit/scripting_spec.js [hunk 1]
```diff
@@ -608,14 +608,23 @@ describe("Scripting", function () {
...
+          expect(value).toEqual(
+            new Date(expected).toISOString().replace(/T.*$/, "")
           );
-          expect(value).toEqual(new Date(expected).toISOString());
         };
 
         await check("05", "dd", "2000/01/05");
         await check("12", "mm", "2000/12/01");
         await check("2022", "yyyy", "2022/01/01");
+        await check("a1$9bbbb21", "dd/mm/yyyy", "2021/09/01");
```
[the remark this answers is not in the document]
Comment (calixteman) [reply test/unit/scripting_spec.js:621]: Astonishingly... yes
image

File: src/scripting_api/aform.js [hunk 2]
```diff
@@ -52,6 +53,94 @@ class AForm {
     return event.target ? `[ ${event.target.name} ]` : "";
   }
 
+  _tryToGuessDate(cFormat, cDate) {
+    // We use the format to know the order of day, month, year, ...
+    // Hence we've it we know how to interpret the numbers we've in the date.
```
Comment (Snuffleupagus) [inline src/scripting_api/aform.js:58]: I'm finding this second sentence is a little difficult to parse, do we need it?

File: src/scripting_api/aform.js [hunk 3]
```diff
@@ -52,6 +53,94 @@ class AForm {
...
+          }
+          return "";
+        }
+      );
+    }
+
+    const number = /\d+/g;
+    let i = 0;
+    let array;
+    const now = new Date();
```
Comment (Snuffleupagus) [inline src/scripting_api/aform.js:126]: This feels *a little* confusing as a variable name, since it may contain *any* date and not just "now"; how about the following instead? 
```suggestion
    const date = new Date();
```

**Review by Snuffleupagus — APPROVED** [review]

**Comment by calixteman** [comment]
Oh I missed your approval, sorry for the noise.
