### PR TITLE
[Editor] Don't steal the keyboard events when editing mode is enabled

### LINKED ISSUE #17167: Global 'keydown' event listener for the AnnotationEditorUIManager hijacks keystrokes.
Attach (recommended) or Link to PDF file here: Any PDF will work

Configuration:
- Web browser and its version: Tested on multiple browsers, including Firefox v118.0.2 and Electron v24.4.0
- Operating system and its version: Windows 10
- PDF.js version: v3.11.174

Steps to reproduce the problem:
1.  Navigate to https://codesandbox.io/s/pdfjs-dist-with-ts-forked-4jczx7?file=/src/index.ts
2.  Upload PDF
3.  Type in the textbox (note that deleting with backspace or DEL key works at this point)
4.  Press "Toggle Highlight" button (which toggles the viewer to between "NONE" and "INK" annotation modes)
5.  Attempt to Delete text in input field using either backspace or DEL keys.

What is the expected behavior? (add screenshot)

You should be able to delete text from the input field, ideally when the focus leaves the pdf viewer container for another element, but at the least when the annotationEditorMode for the viewer is set to NONE.

What went wrong? (add screenshot)

Backspace and DEL keys no longer function once highlighting is toggled on, even if it is later toggled off.
Keydown event listener in src/display/editor/tools.js is hijacking the DEL and backspace keys, even after the annotationEditoMode for the viewer is set to NONE. 

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://codesandbox.io/s/pdfjs-dist-with-ts-forked-4jczx7?file=/src/index.ts

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

File: web/pdf_find_bar.js [hunk 1]
```diff
@@ -51,16 +51,21 @@ class PDFFindBar {
     this.findField.addEventListener("input", () => {
       this.dispatchEvent("");
     });
+    this.findField.addEventListener("keydown", e => {
+      e.stopPropagation();
+    });
```
Comment (Snuffleupagus) [inline web/pdf_find_bar.js:56]: Did you successfully test this, since I'd expect that doing this will break the "keydown"-handler just below?
Those keyboard shortcuts have previously always worked also when *the input is focused*, which this patch now breaks.

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]
I'm sorry to say that I'm not a fan of having to sprinkle event-handlers throughout the viewer code-base, since it really doesn't feel like a very maintainable solution.

Can't we handle this at the Editor-level instead, e.g. by checking that the active element is within the page and/or viewer?

**Comment by calixteman** [comment]
> I'm sorry to say that I'm not a fan of having to sprinkle event-handlers throughout the viewer code-base, since it really doesn't feel like a very maintainable solution.
> 
> Can't we handle this at the Editor-level instead, e.g. by checking that the active element is within the page and/or viewer?

To be honest, my feeling is that nothing is exciting here. If in 6 months we've to add an element in the UI which can be controlled with the keyboard, we've to remember that it can badly interact with the editing mode, even if it's unrelated.
In an ideal world, events should have a flag which would be true when they've been consumed during the bubbling phase...
That said, it isn't that simple: for example if you click on a slider on then press ctrl+Z, the active element is the slider but.
So we've to take of the type of the active element and when it's an input we've to take care of the type of input (a slider isn't the same as a text input) so it leads to more complexity.
That said, your inline comment is the best argument to say that this patch is not doing the right thing: I'll fix that.

File: src/display/editor/tools.js [hunk 2]
```diff
@@ -611,15 +611,27 @@ class AnnotationEditorUIManager {
       );
     };
 
+    const textInputChecker = (_self, { target: el }) => {
```
Comment (Snuffleupagus) [inline src/display/editor/tools.js:614]: Given that `FreeText` has its own `KeyboardManager`-instance, do we need to add the same kind of check for any of those shortcuts or is that fine as-is?

https://github.com/mozilla/pdf.js/blob/f95a2bbe2944d63fc39916113c617339194dcbf1/src/display/editor/freetext.js#L65

Comment (calixteman) [reply src/display/editor/tools.js:614]: It should be fine since when we're editing a freetext, we've to move the focus on an input and then the editing session will be stopped.

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you!
