### PR TITLE
Avoid exception after having moved an annotation

### LINKED ISSUE #20571: [Bug]: Text tool throws an uncaught TypeError
### Attach (recommended) or Link to PDF file

https://mozilla.github.io/pdf.js/web/viewer.html

### Web browser and its version

Chrome, Edge

### Operating system and its version

Windows 11 Pro 24H2

### PDF.js version

5.4.530

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. click on text tool
2. write some text
3. click on text tool to close it
4. double click on written text
5. move the text
6. click to text tool again - it does not wrok

Image

### What is the expected behavior?

expected behaviour is that is works normal :)

### What went wrong?

text tool does not worka s expected

### Link to a viewer

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by calixteman**
It fixes #20571.

### CODE REVIEW

File: test/integration/freetext_editor_spec.mjs [hunk 1]
```diff
@@ -3645,4 +3645,53 @@ describe("FreeText Editor", () => {
...
+
+    beforeEach(async () => {
+      pages = await loadAndWait(
+        "tracemonkey.pdf",
+        ".annotationEditorLayer",
+        100,
+        {
+          eventBusSetup: eventBus => {
+            eventBus.on("annotationeditorstateschanged", ({ details }) => {
+              window.editingEvents?.push(details);
```
Comment (timvandermeij) [inline test/integration/freetext_editor_spec.mjs]: It looks like we don't actually use this in the test, so the whole event bus setup can probably be removed to simplify the test?

File: test/integration/freetext_editor_spec.mjs [hunk 2]
```diff
@@ -3645,4 +3645,53 @@ describe("FreeText Editor", () => {
...
+          },
+        }
+      );
+    });
+
+    afterEach(async () => {
+      await closePages(pages);
+    });
+
+    it("must check that the buttons works correctly", async () => {
```
Comment (timvandermeij) [inline test/integration/freetext_editor_spec.mjs]: s/works/work

**Review by timvandermeij — APPROVED** [review]
r=me, with the comments addressed. Thank you for fixing this!
