### PR TITLE
Rotate annotations based on the MK::R value (bug 1675139)

### LINKED ISSUE #9596: Acroform Field not rotating with document
Acrobat form fields are not rotated correctly on the page.

Attach (recommended) or Link to PDF file here:
[private-patient-hospital-claim.pdf](https://github.com/mozilla/pdf.js/files/1836330/private-patient-hospital-claim.pdf)

Configuration:
- Web browser and its version: 65.0.3325.181 (Official Build) (64-bit)
- Operating system and its version: Windows 2016
- PDF.js version: pdfjs-1.10.88-dist
- Is a browser extension: No

Steps to reproduce the problem:
1. Set `renderInteractiveForms` to `true` on the viewer
2. Open the attached PDF. The two Acrobat fields have the wrong rotation applied.

What is the expected behavior? (add screenshot)
Adobe Reader 11:
image

What went wrong? (add screenshot)
Text fields did not rotate with the page correctly:
image

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Default viewer from pdfjs-1.10.88-dist. 
Edit, tested on mozilla.github.io/pdf.js with the same issue

### PR DESCRIPTION
**Pull request by calixteman**
- it aims to fix: https://bugzilla.mozilla.org/show_bug.cgi?id=1675139;
- An annotation can be rotated (counterclockwise);
- the rotation can be set in using JS.

### CODE REVIEW

File: src/core/annotation.js [hunk 1]
```diff
@@ -704,6 +708,46 @@ class Annotation {
     }
   }
 
+  setRotation(mk) {
+    this.rotation = 0;
+    if (mk instanceof Dict) {
+      let angle = mk.get("R") || 0;
+      if (angle !== 0) {
```
Comment (Snuffleupagus) [inline src/core/annotation.js:715]: Let's ensure that the angle is also an *integer*, since otherwise none of the code below makes sense.
```suggestion
      if (Number.isInteger(angle) && angle !== 0) {
```

File: src/core/annotation.js [hunk 2]
```diff
@@ -704,6 +708,46 @@ class Annotation {
...
+        // If the angle is negative then angle % 360 is still negative.
+        angle = (360 + (angle % 360)) % 360;
```
Comment (Snuffleupagus) [inline src/core/annotation.js:717]: I'm finding this a bit less clear than what we have in other parts of the code-base, see e.g.

https://github.com/mozilla/pdf.js/blob/45de73bd00d56c6f0df2edac98eccf51c7ca42ca/src/display/display_utils.js#L179-L183 and https://github.com/mozilla/pdf.js/blob/45de73bd00d56c6f0df2edac98eccf51c7ca42ca/web/base_viewer.js#L509-L513

File: src/core/annotation.js [hunk 3]
```diff
@@ -704,6 +708,46 @@ class Annotation {
...
+
+    switch (rotation) {
+      case 90:
+        return [0, 1, -1, 0, width, 0];
+      case 180:
+        return [-1, 0, 0, -1, width, height];
+      case 270:
+        return [0, -1, 1, 0, 0, height];
+      default:
+        return [1, 0, 0, 1, 0, 0];
```
Comment (Snuffleupagus) [inline src/core/annotation.js:747]: This should be unreachable, given the `if (rotation === 0) { ... }` block above, right?
Hence I'd suggest replacing this with:
```suggestion
        throw new Error("Invalid rotation");
```

File: src/display/annotation_layer.js [hunk 4]
```diff
@@ -264,12 +264,40 @@ class AnnotationElement {
...
+      container.style.height = `${(100 * height) / pageHeight}%`;
+    } else {
+      this.setRotation(rotation, container);
+    }
 
     return container;
   }
 
+  setRotation(angle, container) {
+    container ||= this.container;
```
Comment (Snuffleupagus) [inline src/display/annotation_layer.js:280]: Can't we just do the following?
```suggestion
  setRotation(angle, container = this.container) {
```

File: src/scripting_api/field.js [hunk 5]
```diff
@@ -188,6 +188,18 @@ class Field extends PDFObject {
     throw new Error("field.page is read-only");
   }
 
+  get rotation() {
+    return this._rotation;
+  }
+
+  set rotation(angle) {
+    angle = Math.floor(angle);
```
Comment (Snuffleupagus) [inline src/scripting_api/field.js:196]: Is it *correct* to accept a non-integer angle here?

File: src/scripting_api/field.js [hunk 6]
```diff
@@ -188,6 +188,18 @@ class Field extends PDFObject {
...
+    if (angle % 90 !== 0) {
+      throw new Error("Invalid rotation: must be a multiple of 90");
+    }
+    this._rotation = (360 + (angle % 360)) % 360;
```
Comment (Snuffleupagus) [inline src/scripting_api/field.js:200]: As above, regarding the normalization of the rotation angle.

**Review by Snuffleupagus — COMMENTED** [review]
Does this perhaps also fix issue #9596?

File: test/test_manifest.json [hunk 7]
```diff
@@ -6583,5 +6583,34 @@
       "rounds": 1,
       "type": "eq",
       "annotations": true
+   },
+   { "id": "bug1675139",
+      "file": "pdfs/bug1675139.pdf",
```
Comment (Snuffleupagus) [inline test/test_manifest.json:6588]: Also, this file doesn't seem to be included in the patch :-)

File: src/scripting_api/field.js (hunk 5 above)
Comment (calixteman) [reply src/scripting_api/field.js:196]: Yes it's: I checked in Acrobat.

File: test/test_manifest.json (hunk 7 above)
Comment (calixteman) [reply test/test_manifest.json:6588]: pffff....

File: src/core/annotation.js [hunk 8]
```diff
@@ -704,6 +708,47 @@ class Annotation {
...
   }
 
+  setRotation(mk) {
+    this.rotation = 0;
+    if (mk instanceof Dict) {
+      let angle = mk.get("R") || 0;
+      if (Number.isInteger(angle) && angle !== 0) {
+        // If the angle is negative then angle % 360 is still negative.
+        angle %= 360;
+        angle = angle >= 0 ? angle : 360 + angle;
```
Comment (Snuffleupagus) [inline src/core/annotation.js:718]: Can't we just do *exactly* what's done elsewhere in the code-base, since re-assigning the value when it's non-negative just feels unnecessary?
```suggestion
        // Normalize the rotation, by clamping it to the [0, 360) range.
        angle %= 360;
        if (angle < 0) {
          angle += 360;
        }
```

**Review by Snuffleupagus — APPROVED** [review]
What about the question in https://github.com/mozilla/pdf.js/pull/15060#pullrequestreview-1011555218 :-)

---

r=me, with passing tests; thank you!

File: src/core/annotation.js [hunk 9]
```diff
@@ -704,6 +716,51 @@ class Annotation {
     }
   }
 
+  setRotation(mk) {
+    this.rotation = 0;
+    if (mk instanceof Dict) {
+      let angle = mk.get("R") || 0;
+      if (Number.isInteger(angle) && angle !== 0) {
+        // If the angle is negative then angle % 360 is still negative.
```
Comment (Snuffleupagus) [inline src/core/annotation.js:724]: This comment can probably be removed.

File: src/core/annotation.js [hunk 10]
```diff
@@ -704,6 +716,51 @@ class Annotation {
...
+          angle += 360;
+        }
+        if (angle % 90 === 0) {
+          this.rotation = angle;
+        }
+      }
+    }
+  }
+
+  getRotationMatrix(annotationStorage) {
```
Comment (Snuffleupagus) [inline src/core/annotation.js:736]: Is this necessary for all Annotation-types, or can we perhaps move it into the `WidgetAnnotation`-class instead?

File: src/core/annotation.js [hunk 11]
```diff
@@ -721,13 +778,24 @@ class Annotation {
     }
   }
 
-  getBorderAndBackgroundAppearances() {
+  getBorderAndBackgroundAppearances(annotationStorage) {
```
Comment (Snuffleupagus) [inline src/core/annotation.js:781]: This is existing code, but the question above (regarding `WidgetAnnotation`) applies here as well.

File: src/core/annotation.js [hunk 12]
```diff
@@ -1606,12 +1681,26 @@ class WidgetAnnotation extends Annotation {
     dict.set("AP", AP);
     dict.set("M", `D:${getModificationDate()}`);
 
+    if (rotation || this.borderColor || this.backgroundColor) {
+      const MK = new Dict(xref);
+      MK.set("R", rotation);
+      MK.set("BC", getPDFRgbArray(this.borderColor));
+      MK.set("BG", getPDFRgbArray(this.backgroundColor));
+      dict.set("MK", MK);
+    }
```
[the remark this answers is not in the document]
Comment (Snuffleupagus) [reply src/core/annotation.js:1690]: Maybe if you add a method like this, on the `WidgetAnnotation`-class:
```javascript
_getMKDict(rotation) {
  const mk = new Dict(null); // `null` can probably be used here, since none of the data below will be a /Ref
  if (rotation) {
    mk.set("R", rotation);
  }
  if (this.borderColor) {
    mk.set("BC", Array.from(this.borderColor).map(c => c / 255));
  }
  if (this.backgroundColor) {
    mk.set("BG", Array.from(this.backgroundColor).map(c => c / 255));
  }
  return mk.size > 0 ? mk : null;
}
```

and then you can simply do (here and elsewhere):
```suggestion
    const maybeMK = this._getMKDict(rotation);
    if (maybeMK) {
      dict.set("MK", maybeMK);
    }
```

File: src/core/annotation.js [hunk 13]
```diff
@@ -704,6 +716,51 @@ class Annotation {
...
+    const storageEntry = annotationStorage
+      ? annotationStorage.get(this.data.id)
+      : undefined;
+    let rotation = storageEntry && storageEntry.rotation;
+    if (rotation === undefined) {
+      rotation = this.rotation;
+    }
+
+    if (rotation === 0) {
+      return [1, 0, 0, 1, 0, 0];
```
Comment (Snuffleupagus) [inline src/core/annotation.js:746]: I don't know how much it matters, but you may want to return `IDENTITY_MATRIX` here (can be imported from `src/shared/util.js`)?

File: src/core/annotation.js [hunk 14]
```diff
@@ -2220,6 +2343,17 @@ class ButtonWidgetAnnotation extends WidgetAnnotation {
       : this.uncheckedAppearance;
     if (appearance) {
       const savedAppearance = this.appearance;
+      const savedMatrix = appearance.dict.getArray("Matrix") || [
+        1, 0, 0, 1, 0, 0,
```
Comment (Snuffleupagus) [inline src/core/annotation.js:2347]: Again, you could maybe just fallback on `IDENTITY_MATRIX` here?

File: src/core/annotation.js [hunk 15]
```diff
@@ -2279,6 +2425,14 @@ class ButtonWidgetAnnotation extends WidgetAnnotation {
...
     dict.set("M", `D:${getModificationDate()}`);
 
+    if (rotation || this.borderColor || this.backgroundColor) {
+      const MK = new Dict(evaluator.xref);
+      MK.set("R", rotation);
+      MK.set("BC", getPDFRgbArray(this.borderColor));
+      MK.set("BG", getPDFRgbArray(this.backgroundColor));
+      dict.set("MK", MK);
+    }
+
```
Comment (Snuffleupagus) [inline src/core/annotation.js:2435]: Please see previous comments.

File: src/core/annotation.js [hunk 16]
```diff
@@ -2346,6 +2512,14 @@ class ButtonWidgetAnnotation extends WidgetAnnotation {
...
```
Comment (Snuffleupagus) [inline src/core/annotation.js:2522]: Please see previous comments.

**Comment by calixteman** [comment]
The "regression" is due to a rotation of 270deg on a checkbox and this one is not exactly a square, hence the change, so it's an improvement.

File: src/core/annotation.js [hunk 17]
```diff
@@ -1535,20 +1596,42 @@ class WidgetAnnotation extends Annotation {
     );
   }
 
+  _getMKDict(rotation) {
+    const mk = new Dict(null); // `null` can probably be used here, since none of the data below will be a /Ref
```
Comment (Snuffleupagus) [inline src/core/annotation.js:1600]: Please remove the comment, since I only included it to explain my reasoning as part of the review comment.

**Review by Snuffleupagus — APPROVED** [review]
