### PR TITLE
[Editor] Take into account the device pixel ratio when drawing an added image

### LINKED ISSUE #18626: [Bug]: StampAnnotation is blurry on retina screen
### Attach (recommended) or Link to PDF file

(see the section "Steps to reproduce the problem")

### Web browser and its version

Chrome 127.0.6533.100

### Operating system and its version

MacOS 14.6.1

### PDF.js version

4.5.722

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. On a Mac with retina screen: Open the Showcase https://mozilla.github.io/pdf.js/web/viewer.html
2. Click "Add or edit image" in the toolbar
3. Upload a SVG (e.g. PDF.js logo  https://mozilla.github.io/pdf.js/images/logo.svg)
4. Resize the stamp to a smaller size => the image gets blurry 

Bildschirmfoto 2024-08-19 um 15 59 10

### What is the expected behavior?

On a retina screen, the image of the canvas should be rendere twice the size as the html element. The code would look something like this:
```
canvas.style.width = width
canvas.style.height = height
canvas.width = width * window.devicePixelRatio;
canvas.height = height * window.devicePixelRatio;
```
 This would look in the editor something like this:
Bildschirmfoto 2024-08-19 um 16 00 28

Since the normal PDF is perfectly sharp rendered (also on a canvas), i assume the problem is already solved, it is just not applied to the StampEditor.

### What went wrong?

(see the section "What is the expected behavior?")

### Link to a viewer

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by calixteman**
Fixes #18626.

### CODE REVIEW

File: src/display/display_utils.js [hunk 1]
```diff
@@ -1124,6 +1124,36 @@ function setLayerDimensions(
...
+  }
+
+  /**
+   * @type {boolean} Returns `true` when scaling is required, `false` otherwise.
+   */
+  get scaled() {
+    return this.sx !== 1 || this.sy !== 1;
+  }
+
+  get homothetic() {
```
Comment (Snuffleupagus) [inline src/display/display_utils.js:1152]: It might just be being uneducated, but I had to lookup this word :-)
Could we perhaps pick a different, slightly "easier", name here; i.e. would the following convey approximately the same thing?

```suggestion
  get symmetric() {
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, with a naming suggestion; thank you.
