### PR TITLE
For missing font, use a local font if it exists even if there's no standard substitution

### LINKED ISSUE #10878: Multiple issues for an NVIDIA pdf
Attach (recommended) or Link to PDF file here: http://us.download.nvidia.com/Windows/361.43/361.43-win10-win8-win7-winvista-desktop-release-notes.pdf

Configuration:
- Web browser and its version: Firefox 68 beta 6
- Operating system and its version: Fedora 30 fully updated + proprietary NVIDIA drivers
- PDF.js version: no idea
- Is a browser extension: no

Steps to reproduce the problem:
1. Open this PDF

What is the expected behavior? (add screenshot)
(Google Chrome on the same PC)
chrome

What went wrong? (add screenshot)
* Wrong (varying) spacing between letters
* Wrong strokes width
* Bad kerning 

notfixed

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### PR DESCRIPTION
**Pull request by calixteman**
If the font foo is missing we just try lo load local(foo) and maybe we'll be lucky.

### CODE REVIEW

**Review by Snuffleupagus — DISMISSED** [review]
Given that we could now be passing an undefined `standardFontName` to the `getFontSubstitution` function, please update [this part of the JSDoc](https://github.com/mozilla/pdf.js/blob/e738e15aa397ef91b75fcf952abd0d368b232f20/src/core/font_substitutions.js#L381-L382) to actually reflect that:
```javascript
  * @param {String} [standardFontName] The standard font name to use if the base
  *   font is not available. 
```

r=me, with the above fixed and passing tests; thank you!

**Comment by Snuffleupagus** [comment]
Looking at the Windows bot, there's a few things that doesn't look like improvements:
 - `firefox-issue9195-page1`, there's no longer a bold font used.
 - `firefox-issue1096-page1`, `firefox-non-embedded-NuptialScript-page1`, `firefox-issue6117-page6`; no longer uses a serif-font (Adobe Reader renders these with serif-fonts).

**Comment by Snuffleupagus** [comment]
Given some of the test "failures", should we perhaps pass in the font-`flags` to the `getFontSubstitution`-function such that we're able to better choose between serif and sans-serif fonts in the fallback?

**Comment by calixteman** [comment]
> Given some of the test "failures", should we perhaps pass in the font-`flags` to the `getFontSubstitution`-function such that we're able to better choose between serif and sans-serif fonts in the fallback?

Yep, the flags aren't available when `getFontSubstitution` is called but it's the idea. I'll push my update soon.

File: src/core/font_substitutions.js [hunk 1]
```diff
@@ -437,7 +437,8 @@ function getFontSubstitution(
       (italic && ITALIC) ||
       NORMAL;
     substitutionInfo = {
-      css: `${loadedName},sans-serif`,
+      css: loadedName,
+      mustGuessFallback: true,
```
Comment (Snuffleupagus) [inline src/core/font_substitutions.js:441]: How about a slightly shorter name?
```suggestion
      guessFallback: true,
```

Comment (Snuffleupagus) [reply src/core/font_substitutions.js:441]: Also, how about including an explicit `guessFallback: false,` line below such that the objects returned by this function always have a consistent "shape"?

https://github.com/mozilla/pdf.js/pull/16416/files#diff-84365a5fa783e74d4c83766a21305541dedb5d8ccefa51df9f95fa3a38bf0cfcR482-R487

File: src/core/fonts.js [hunk 2]
```diff
@@ -999,7 +1000,10 @@ class Font {
       this.fallbackName = "sans-serif";
     }
 
-    this.systemFontInfo = properties.systemFontInfo;
+    if (this.systemFontInfo?.mustGuessFallback) {
+      this.systemFontInfo.css = `${this.systemFontInfo.css},${this.fallbackName}`;
```
Comment (Snuffleupagus) [inline src/core/fonts.js:1004]: This would be shorter as:
```suggestion
      this.systemFontInfo.css += `,${this.fallbackName}`;
```

File: src/display/font_loader.js [hunk 3]
```diff
@@ -97,9 +97,17 @@ class FontLoader {
...
         this.#systemFonts.add(loadedName);
       } catch {
-        warn(
-          `Cannot load system font: ${loadedName} for style ${style.style} and weight ${style.weight}.`
-        );
+        if (info.mustGuessFallback) {
+          // We're trying to load only one system font.
+          const match = src.match(/^local\((.*)\)$/);
+          warn(
+            `Cannot load system font: ${match[1]}, installing it could help to have a better PDF rendering.`
```
Comment (Snuffleupagus) [inline src/display/font_loader.js:104]: Let's ensure that the line below cannot possibly throw, by guarding the `match`-access.
Also, I've suggested a slightly wording tweak:
```suggestion
            `Cannot load system font: ${match?.[1]}, installing it could help improve PDF rendering.`
```

**Comment by Snuffleupagus** [comment]
That looks better, however we still have some "problems" at least on the Windows bot:
 - `firefox-issue9195-page1`, some of the text still isn't bold as expected.
 - `firefox-issue11915-page1`, the Arial Italic font isn't working correctly (the font is named `/Arial-ItalicMT,Italic`).

**Comment by calixteman** [comment]
About `issue11915`, I added the font in the standard font map and the "weird" aspect is because we've an italic monospace (because the font is detected as monospace).
The monospace flag is because of:
https://github.com/mozilla/pdf.js/blob/master/src/core/evaluator.js#L3961
and it's why in the last version of the patch I clear the bit if it's required.

**Comment by Snuffleupagus** [comment]
It seems that the ArialBlack has now regressed on Windows, see e.g. `firefox-artofwar` (many pages), `firefox-issue5801-page1`, and `firefox-issue7835-page1`.

**Review by Snuffleupagus — APPROVED** [review]
That seems to work, and improves Calibri fonts on Windows. (It's too bad that the `getFontSubstitution` function becomes even more complex, but I suppose that cannot really be helped.)

r=me, thank you!
