### PR TITLE
Ensure that the result of |constructStichedFromIRResult| is a number (issue 6113)

### LINKED ISSUE #6113: Wrong shadow color
This is a regression. The "Niseko United" logo is shadowed with a wrong color.

URL: http://www.niseko.ne.jp/en/map/pdf/FPmap_en.pdf
1.1.205: http://i.imgur.com/x09GnzT.png
0.8.990: http://i.imgur.com/HJY7S4W.png

f750e35224d344f068542411bcb4f750b2d4dcdb is the first bad commit
commit f750e35224d344f068542411bcb4f750b2d4dcdb
Author: Yury Delendik
Date:   Mon Aug 4 11:12:51 2014 -0500

    Optimizes functions to not create arrays

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Fixes #6113.

It appears that when we switched to using `Float32Array` (in PR #5134), we may now occasionally encounter rounding errors, which cause the result to become `NaN` thus leading to incorrect rendering.

### CODE REVIEW

File: src/core/function.js [hunk 1]
```diff
@@ -364,7 +364,9 @@ var PDFFunction = (function PDFFunctionClosure() {
         var rmin = encode[2 * i];
         var rmax = encode[2 * i + 1];
 
-        tmpBuf[0] = rmin + (v - dmin) * (rmax - rmin) / (dmax - dmin);
+        // Ensure that this is always a valid number, since rounding errors
+        // may cause it to become NaN (fixes issue6113.pdf).
+        tmpBuf[0] = (rmin + (v - dmin) * (rmax - rmin) / (dmax - dmin)) || 0;
```
Comment (yurydelendik) [inline src/core/function.js]: I think we shall return value in range from rmin..rmax, can we use `rmin + (((v - dmin) * (rmax - rmin) / (dmax - dmin)) || 0);` here?

Also, it might be useful to check for 0 before div, e.g. `dmax === dmin` and return 0, e.g. `dmax === dmin ? rmin : (rmin + (v - dmin) * (rmax - rmin) / (dmax - dmin))`

Comment (Snuffleupagus) [inline src/core/function.js]: Really good point, thanks! I'll update the patch to clamp the value to the range of the function.

**Comment by Snuffleupagus** [comment]
The *one* time that I don't bother testing locally before pushing a patch, since I figured it's probably fine anyway, I *obviously* break something. :-(
Unsurprisingly I should just have done what Yury suggested right away. Anyway, a new and locally tested patch has been pushed. Sorry about the wasted time/testing here!

/botio-linux preview

**Comment by timvandermeij** [comment]
Nice, thanks!
