### PR TITLE
Make `XRef_indexObjects` more robust against bad PDF files (issue 5752)

### LINKED ISSUE #5752: PDF errors on rendering (Chinese document)
http://222.247.54.152/Fulltext/qkyxlcyjy200504007.pdf
This PDF throws the following error:

Renders correctly in Adobe Acrobat.

PDF.js v1.0.1149 (build: bc7a110)
Message: Invalid PDF structure

Windows x64, Chrome 39

### PR DESCRIPTION
**Pull request by Snuffleupagus**
This patch improves the detection of `xref` in files where it is followed by an arbitrary whitespace character (not just a line-breaking char).
It also adds a check for missing whitespace, e.g. `1 0 obj<<`, to speed up `readToken` for the PDF file in the referenced issue.
Finally, the patch also replaces a bunch of magic numbers with suitably named constants.

Fixes #5752.

Also improves #6243, but there are still issues.

### CODE REVIEW

File: src/core/obj.js [hunk 1]
```diff
@@ -1054,23 +1060,23 @@ var XRef = (function XRefClosure() {
...
             }
             ch = buffer[position];
-          } while (ch !== 13 && ch !== 10);
+          } while (ch !== LF && ch !== CR);
           continue;
         }
         var token = readToken(buffer, position);
         var m;
-        if (token === 'xref') {
+        if (/^xref\b/.test(token)) { // 'xref'
```
Comment (yurydelendik) [inline src/core/obj.js]: We need to minimize use of regular expression here. Can you: check `token[0] === 'x'` before running regexp, or `token.indexOf('xref') === 0` and then check token[3] for whitespace?

**Comment by yurydelendik** [comment]
Looks good, thanks.

File: src/core/obj.js (hunk 1 above)
Comment (Snuffleupagus) [inline src/core/obj.js]: Done.

**Comment by yurydelendik** [comment]
Thank you for the patch.

/botio makeref
