### PR TITLE
Use FDSelect and FDArray when converting CFF CID font to paths

### LINKED ISSUE #9355: PDF Font size displaying incorrectly
I test attached PDF on different platforms. And font size looks bigger than it should be in browser vs standalone app.
[Infosec Rain Phishing.pdf](https://github.com/mozilla/pdf.js/files/1622160/Infosec.Rain.Phishing.pdf)

Several examples:

**Configuration 1(Linux):**
- Ubuntu 16.04 Linux 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)
- PDFJS.version "2.0.258" Online here(https://mozilla.github.io/pdf.js/web/viewer.html)
Result 1:
linux_pdfjs-google-chrome-font-issue

Standard linux viewer display this file properly:
linux_viewer-looks-good

**Configuration 2(Windows 8.1):**
- Windows 8.1 Enterprise Evaluation 32-bit Operating System(Test image with IE11 see details below)
- Windows 8.1 Mozila FireFox 57.0.4 32 Bit
- PDFJS.version "2.0.258" Online here(https://mozilla.github.io/pdf.js/web/viewer.html)
Result 2:
windows-8 1-firefox

Free FixitPdfReader 9.0.0.29935 displaying file properly:
windows-8 1-free-foxitpdfviewer

**Configuration 3(Windows 8.1):**
- Windows 8.1 Enterprise Evaluation 32-bit Operating System(Test image with IE11 see details below)
- IE 11.0.9600.17416
- PDFJS.version "2.0.258" Online here(https://mozilla.github.io/pdf.js/web/viewer.html)

Result 3:
ie11_pdfjs-issue

I use Windows image available here https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

### PR DESCRIPTION
**Pull request by janpe2**
Fixes #9355

When text rendering mode `Tr` specifies that text should produce clipping paths, font's glyphs are converted to canvas paths in `font_renderer.js`. However, it ignores entries FDSelect and FDArray in CFF CID fonts. Those entries are needed to get the correct FontMatrix (and to execute local subroutines).

The font in issue #9355 has no FontMatrix in the Top DICT, so `font_renderer.js` uses the default matrix, which is `[0.001 0 0 0.001 0 0]`. The correct FontMatrix is in the FDArray and it specifies about 50% smaller scaling factors: `[.00048828099 0 0 .00048828099 0 0]`.

I have ignored Top DICT's FontMatrix because `CFFParser` always [removes and copies](https://github.com/mozilla/pdf.js/blob/99060e2485cacb8513e7bc50d88b70101069b1c9/src/core/cff_parser.js#L1250) it to FDArray dictionaries when needed.

### CODE REVIEW

File: src/core/font_renderer.js [hunk 1]
```diff
@@ -612,17 +637,29 @@ var FontRendererFactory = (function FontRendererFactoryClosure() {
...
         return noop;
       }
 
+      let fontMatrix = this.fontMatrix;
+      if (this.isCFFCIDFont) {
+        let fdIndex = this.fdSelect.getFDIndex(glyphId);
+        if (fdIndex >= 0 && fdIndex < this.fdArray.length) {
+          let fontDict = this.fdArray[fdIndex];
+          fontMatrix = fontDict.getByName('FontMatrix') ||
+                       [0.001, 0, 0, 0.001, 0, 0];
```
Comment (Snuffleupagus) [inline src/core/font_renderer.js]: Please use `FONT_IDENTITY_MATRIX` from `src/shared/util.js` rather than hard-coding this array here.

File: test/test_manifest.json [hunk 2]
```diff
@@ -2254,6 +2254,12 @@
       "link": true,
       "type": "eq"
     },
+    { "id": "text_clip_cff_cid",
+      "file": "pdfs/text_clip_cff_cid.pdf",
+      "md5": "92d4920586f177cc0e83326e5b5d2ee1",
+      "rounds": 1,
+      "type": "eq",
```
Comment (brendandahl) [inline test/test_manifest.json]: Trailing comma needs to be removed.

**Comment by timvandermeij** [comment]
@brendandahl Could you take another look at this?

File: src/core/font_renderer.js [hunk 3]
```diff
@@ -612,17 +637,28 @@ var FontRendererFactory = (function FontRendererFactoryClosure() {
...
 
-    compileGlyph(code) {
+    compileGlyph(code, glyphId) {
       if (!code || code.length === 0 || code[0] === 14) {
         return noop;
       }
 
+      let fontMatrix = this.fontMatrix;
+      if (this.isCFFCIDFont) {
+        let fdIndex = this.fdSelect.getFDIndex(glyphId);
```
Comment (brendandahl) [inline src/core/font_renderer.js]: Let's add a comment here about why we ignore the top dict's font matrix (similar to your comment in the PR).

**Review by brendandahl — CHANGES_REQUESTED** [review]
r+ pending the one little change

File: src/core/font_renderer.js (hunk 3 above)
Comment (janpe2) [reply src/core/font_renderer.js]: I added a comment.

**Review by brendandahl — APPROVED** [review]

**Comment by brendandahl** [comment]
Thanks for pull request!
