### PR TITLE
Disable link annotations during text selection

### LINKED ISSUE #18266: Link text could not be selected
Attach (recommended) or Link to PDF file here:
[hyperlink_text_selection.pdf](https://github.com/user-attachments/files/15875472/hyperlink_text_selection.pdf)

Configuration:
- Web browser and its version: Chrome Version 126.0.6478.62
- Operating system and its version: windows 11
- PDF.js version: pdf.js-4.3.136
- Is a browser extension: no

Steps to reproduce the problem:
1. Open the attached pdf file named hyperlink_text_selection.pdf
2. Try to select the text "Microsoft"

What is the expected behavior? The text "Microsoft" should be selected

What went wrong? (add screenshot)
image

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
Commit message:

> **Disable link annotations during text selection**
>
> When selecting text, hovering over an element causes all the text between (according the the dom order) the current selection and that element to be selected.
> 
> This means that when, while selecting, the cursor moves over a link, all the text in the page gets selected. Setting `user-select: none` on the link annotations would improve the situation, but it still makes it impossible to extend the selection within a link without using Shift+arrows keys on the keyboard.
> 
> This commit fixes the problem by setting `pointer-events: none` on the `<section>`s in the annotation layer while selecting some text. This way, they are ignored for hit-testing and do not affect selection.
> 
> It is still impossible to _start_ a selection inside a link, as the link text is covered by the link annotation.
> 
> Fixes #18266

A lot of changes are just indentation: the `selectionchange` event handler has a single changed line, and the pre-existing tests none. I recommend reviewing with whitespace diff disabled.

### CODE REVIEW

File: web/text_layer_builder.js [hunk 1]
```diff
@@ -187,107 +187,112 @@ class TextLayerBuilder {
...
+      this.#textLayers.forEach(reset);
+    });
+    on("keyup", () => {
+      if (!isPointerDown) {
         this.#textLayers.forEach(reset);
-      },
-      { signal }
-    );
+      }
+    });
```
Comment (Snuffleupagus) [inline web/text_layer_builder.js:214]: Don't we need a "blur" listener as well, such that the state is reset correctly if user leaves the browser window since that may prevent pointerup/keyup events from being received?

Comment (nicolo-ribaudo) [reply web/text_layer_builder.js:214]: Good point, let me try

Comment (nicolo-ribaudo) [reply web/text_layer_builder.js:214]: Yes we indeed need it. Browsers still fire "pointerup" when a user starts selecting and moves the mouse outside of the window, but as soon as somebody clicks (with a different mouse button) outside of the window then pointerup is not fired.

**Comment by nicolo-ribaudo** [comment]
@timvandermeij Could you also label this as `text-selection`? :)

File: test/integration/text_layer_spec.mjs [hunk 2]
```diff
@@ -98,111 +99,270 @@ describe("Text layer", () => {
...
+
+              await page.mouse.click(positionEnd.x, positionEnd.y);
+
+              const clicked = await awaitPromise(clickPromiseHandle);
+              expect(clicked).toBeTrue();
+            })
+          );
+        });
+
+        function waitForClick(page, selector, timeout) {
```
Comment (timvandermeij) [inline test/integration/text_layer_spec.mjs:337]: Let's move this helper function to the top of the `describe` block so it's defined before using it (we generally prefer this in the tests).

File: web/text_layer_builder.js [hunk 3]
```diff
@@ -187,107 +187,116 @@ class TextLayerBuilder {
     this.#selectionChangeAbortController = new AbortController();
     const { signal } = this.#selectionChangeAbortController;
 
+    const on = (target, event, handler) =>
```
Comment (timvandermeij) [inline web/text_layer_builder.js:190]: I'm not really sure how I feel about this helper function yet. On the one hand it makes the call sites a bit simpler, but on the other hand it does introduce some indirection for an otherwise fairly regular `addEventListener` call. What do others think about this?

**Review by timvandermeij — COMMENTED** [review]
I'll trigger a run of the tests, but these are my comments based on a first look at the diff.

File: web/text_layer_builder.js (hunk 3 above)
Comment (Snuffleupagus) [reply web/text_layer_builder.js:190]: Agreed, my initial reaction was that it feels a bit "unnecessary" to do this (even more so when the patch was updated to add the `target`-parameter).

Comment (nicolo-ribaudo) [reply web/text_layer_builder.js:190]: I did it because I was disliking the way passing the third param to addEventListener caused it to be formatted when having multiple short event listeners one after the other, but I'm happy to revert.

File: test/integration/text_layer_spec.mjs [hunk 4]
```diff
@@ -98,111 +99,270 @@ describe("Text layer", () => {
...
+          )
+        );
 
-            await page.mouse.move(positionStartPage1.x, positionStartPage1.y);
-            await page.mouse.down();
+        function waitForClick(page, selector, timeout) {
+          return page.evaluateHandle(
+            (sel, timeoutDelay) => {
+              const element = document.querySelector(sel);
+              const timeoutSignal = AbortSignal.timeout(timeoutDelay);
```
Comment (Snuffleupagus) [inline test/integration/text_layer_spec.mjs:235]: *This doesn't require any changes, but just an observation for future reference:*

According to MDN this feature is newer than the minimum browsers that we support, compare https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/timeout_static#browser_compatibility and https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

However, given that this is test-only code this seems totally fine since I don't believe that we've ever said anything about the test-suite(s) being fully runnable in older browsers.

File: test/integration/text_layer_spec.mjs [hunk 5]
```diff
@@ -98,111 +99,270 @@ describe("Text layer", () => {
...
+              return [
+                new Promise(resolve => {
+                  timeoutSignal.addEventListener(
+                    "abort",
+                    () => resolve(false),
+                    {
+                      once: true,
+                    }
```
Comment (Snuffleupagus) [inline test/integration/text_layer_spec.mjs:243]: Nit: This can be a one-liner.
```suggestion
                    { once: true }
```

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you for improving this!
