### PR TITLE
Don't take into account the INVISIBLE flag for well-known annotations

### LINKED ISSUE #17169: Support for Displaying Image Stamps in Signed PDFs
## Attach (recommended) or Link to PDF file here:
[stamp-signature.pdf](https://github.com/mozilla/pdf.js/files/13161366/stamp-signature.pdf)

## Configuration:
- Web browser and its version: Chrome 19.0.0
- Operating system and its version: Windows10
- PDF.js version: 3.4.120
- Is a browser extension:

## Steps to reproduce the problem:
1. Open the attached/linked PDF file using PDF.js.
2. Navigate to the page with the electronic stamp.

## What is the expected behavior? (add screenshot)

The electronic stamp should be displayed correctly on the signed PDF document.

## What went wrong? (add screenshot)

The electronic stamp is not rendering/displaying correctly.

## Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): 

Cannot provide

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

File: src/core/annotation.js [hunk 1]
```diff
@@ -1817,7 +1828,9 @@ class WidgetAnnotation extends Annotation {
     // since the visibility can be changed by js code, hence in case
     // it's made viewable, we should render it (with visibility set to
     // hidden).
-    return !this._hasFlag(flags, AnnotationFlag.INVISIBLE);
+    // We don't take into account the `INVISIBLE` flag here, since we've a known
+    // type annotation.
```
Comment (Snuffleupagus) [inline src/core/annotation.js:1832]: Nit:
```suggestion
    // annotation type.
```

File: test/unit/annotation_spec.js [hunk 2]
```diff
@@ -4082,7 +4082,7 @@ describe("annotation", function () {
         const popupDict = new Dict();
         popupDict.set("Type", Name.get("Annot"));
         popupDict.set("Subtype", Name.get("Popup"));
-        popupDict.set("F", 25); // not viewable
+        popupDict.set("F", 56); // not viewable
```
Comment (Snuffleupagus) [inline test/unit/annotation_spec.js:4085]: Does the unit-test still "make sense" with these changes, i.e. does this updated flag still equal `not viewable` as the comment says?

**Review by Snuffleupagus — COMMENTED** [review]
Given the changes in this patch, it doesn't feel entirely meaningful to review it until *all* tests are shown to be passing.

File: test/unit/annotation_spec.js (hunk 2 above)
Comment (calixteman) [reply test/unit/annotation_spec.js:4085]: I removed 1 (Invisible) and added 32 (NoView) so it should be `not viewable`.

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you!
