### PR TITLE
[Annotation] Take into account the stroke alpha for a FreeText without appearance

### LINKED ISSUE #16021: Mailto links render an href on top of link text since version 3.1.81
Attach (recommended) or Link to PDF file here:
[MSD_IRMA_Disclosure_-_trs_update_11-17-14.DRU65gKY7.pdf](https://github.com/mozilla/pdf.js/files/10678322/MSD_IRMA_Disclosure_-_trs_update_11-17-14.DRU65gKY7.pdf)

Configuration:
- Web browser and its version: Chrome 109.0.5414.87 
- Operating system and its version: macOS Monterrey 12.5.1
- PDF.js version: 3.1.81 and above
- Is a browser extension: No

Steps to reproduce the problem:
1. Open attached document in the hosted PDF.js viewer at https://mozilla.github.io/pdf.js/web/viewer.html
2. Mailto links for email links render on top of link text.

What is the expected behavior? (add screenshot)
The links should render normally (screenshot from version 3.0.279):
Screen Shot 2023-02-07 at 1 39 27 PM

What went wrong?
The links render in a weird overlapping format (screenshot from versions 3.1.81 and above):
Screen Shot 2023-02-07 at 1 41 03 PM

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

File: src/core/default_appearance.js [hunk 1]
```diff
@@ -321,6 +321,18 @@ endcmap CMapName currentdict /CMap defineresource pop end end`;
       `/${this.fontName.name} ${numberToString(newFontSize)} Tf`,
     ];
 
+    const { resources } = this;
+    if (strokeAlpha !== 1) {
```
Comment (Snuffleupagus) [inline src/core/default_appearance.js:325]: Don't you need to check that it's actually a number as well, because in a corrupt PDF it could really be anything?

File: src/core/default_appearance.js [hunk 2]
```diff
@@ -321,6 +321,22 @@ endcmap CMapName currentdict /CMap defineresource pop end end`;
       `/${this.fontName.name} ${numberToString(newFontSize)} Tf`,
     ];
 
+    const { resources } = this;
+    strokeAlpha =
+      typeof strokeAlpha === "number"
+        ? Math.min(1, Math.max(0, strokeAlpha))
+        : 1;
```
Comment (Snuffleupagus) [inline src/core/default_appearance.js:328]: Is this sort of clamping what e.g. Adobe Reader does, for a value outside of the [0, 1] range?

Please note that I've not checked, but wanted to ask if we should perhaps just do something like the following instead:
```suggestion
    strokeAlpha =
      typeof strokeAlpha === "number" && strokeAlpha >= 0 && strokeAlpha <= 1
        ? strokeAlpha
        : 1;
```

File: test/test_manifest.json [hunk 3]
```diff
@@ -7349,5 +7349,12 @@
             "value": "bar"
          }
       }
+   },
+   {
+      "id": "issue16021",
+      "file": "pdfs/issue16021.pdf",
+      "md5": "78a12254cac90ba5219a4c5555ea35ed",
+      "rounds": 1,
+      "type": "eq"
```
Comment (Snuffleupagus) [inline test/test_manifest.json:7358]: Do we perhaps also want to add `"annotations": true` for this test-case?

**Review by Snuffleupagus — APPROVED** [review]
r=me, with a couple of questions and passing tests; thanks!

File: test/test_manifest.json (hunk 3 above)
Comment (calixteman) [reply test/test_manifest.json:7358]: I tried locally and it works correctly without adding this.
