### PR TITLE
Adjust the heuristics for handling of incomplete path operators (issue 14917)

### LINKED ISSUE #14917: [Bug] A PDF is not rendered correctly. Something is missing.
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
   Google Chrome Version  101.0.4951.54  (arm64)
- Operating system and its version:
  macOS Monterey 12.3.1
- PDF.js version:
  "pdfjs-dist": "^2.13.216",
- Is a browser extension:

Steps to reproduce the problem:
The PDF url is: https://pdf.cdn.readpaper.com/spd/2963250244.pdf
1. open with Chrome directly:
image

3. render with PDF.js:
image

What is the expected behavior? (add screenshot)

Page 1 is not correct. Right column is missing.

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### PR DESCRIPTION
**Pull request by Snuffleupagus**
This limits the heuristics for handling of incomplete path operators, see PR #9838, to only apply to *sequences* of such operators. In practice a couple of invalid path operators are (hopefully) unlikely to completely break rendering, whereas a sequence of them will easily lead to fairly chaotic rendering artifacts.

### CODE REVIEW

File: src/core/evaluator.js [hunk 1]
```diff
@@ -4837,8 +4845,7 @@ class EvaluatorPreprocessor {
             // used to error, rather than just warn, once a number of invalid
             // path operators have been encountered (fixes bug1443140.pdf).
             if (
-              fn >= OPS.moveTo &&
-              fn <= OPS.endPath && // Path operator
+              this._isPathOp &&
               ++this._numInvalidPathOPS >
                 EvaluatorPreprocessor.MAX_INVALID_PATH_OPS
             ) {
```
Comment (calixteman) [inline src/core/evaluator.js:4851]: Maybe we could remove this `throw` and just warn that the page rendering could be wrong because of incomplete operators.
Do you know if Acrobat (or pdfium-based viewers) has such a threshold (i.e. `MAX_INVALID_PATH_OPS`) to decide to "invalidate" a pdf ?

Comment (Snuffleupagus) [reply src/core/evaluator.js:4851]: > Maybe we could remove this `throw` and just warn that the page rendering could be wrong because of incomplete operators.

That's what we used to do, but if you look at e.g. `bug1443140.pdf` *without* this heuristic you'll see why it's done :-)

> Do you know if Acrobat (or pdfium-based viewers) has such a threshold (i.e. `MAX_INVALID_PATH_OPS`) to decide to "invalidate" a pdf ?

No idea unfortunately; and how different PDF viewer deal with corrupt data seem (as far as I can tell) to vary a fair bit...

Comment (calixteman) [reply src/core/evaluator.js:4851]: Ok, it makes sense.
Just for information, it seems that pdfium (and the same in Preview on mac) doesn't stop to parse: in Chrome, on page 4 of `bug1443140.pdf` in the bottom left there are some garbage text which is at the end of the content stream.
Anyway as said it just for information and I don't think it's worth spending so much time to fix that stuff so r=me.

**Review by calixteman — APPROVED** [review]
LGTM, thank you.
