### PR TITLE
[api-minor] Replace the CCITT and JBig2 fallback decoders with a JS version of the PDFium decoder

### LINKED ISSUE #19049: [Bug]: HC-PDF - Images are loaded in low resolution/quality, making them unreadable
### Attach (recommended) or Link to PDF file

https://sbc.org.pl/Content/874002/PDF/BŚ-RIII6831-1921.pdf

### Web browser and its version

Chrome 131.0.6778.70 / Firefox 132.0.2

### Operating system and its version

Windows 10/11

### PDF.js version

4.0.269 and latest

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open linked PDF file in viewer or directly in Firefox or go to https://sbc.org.pl/formats/pdf/web/viewer.html?file=https%3A%2F%2Fsbc.org.pl%2FContent%2F874002%2FPDF%2FB%25C5%259A-RIII6831-1921.pdf

### What is the expected behavior?

Images are rendered in high resolution/quality, texts are readable. Just like in default PDF viewer in chromium based browsers or Adobe Acrobat.
image

### What went wrong?

Images are loaded in low resolution/quality.

image

### Link to a viewer

https://sbc.org.pl/formats/pdf/web/viewer.html?file=https%3A%2F%2Fsbc.org.pl%2FContent%2F874002%2FPDF%2FB%25C5%259A-RIII6831-1921.pdf

### Additional context

Problem could be related to sizes of underlying images as other, smaller PDFs created with the same method render just fine.
Example: https://sbc.org.pl/formats/pdf/web/viewer.html?file=https%3A%2F%2Fsbc.org.pl%2FContent%2F849032%2FPDF%2FB%25C5%259A-BTLw3193-1901.pdf

### LINKED ISSUE #20046: [Bug]: A memory leak occurred when processing some special PDF files.
### Attach (recommended) or Link to PDF file

[test-2.pdf](https://github.com/user-attachments/files/20977185/test-2.pdf)

### Web browser and its version

node 20.17.0

### Operating system and its version

windows11 

### PDF.js version

5.3.31

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { getDocument } from 'pdfjs-dist/legacy/build/pdf.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const CMAP_URL      = new URL('./node_modules/pdfjs-dist/cmaps/',           import.meta.url).href;
const STD_FONT_URL  = new URL('./node_modules/pdfjs-dist/standard_fonts/',  import.meta.url).href;

(async () => {
  
  const pdfPath = path.resolve(__dirname, 'test-2.pdf');
  const data = new Uint8Array(await fs.readFile(pdfPath));

  
  const loadingTask = getDocument({
    data,
    cMapUrl: CMAP_URL,
    standardFontDataUrl: STD_FONT_URL,
    disableWorker: true,             
  });
  const pdfDoc = await loadingTask.promise;
  console.log(`PDF loaded, total pages: ${pdfDoc.numPages}`);

  const page = await pdfDoc.getPage(1);
  const opList = await page.getOperatorList();
  console.log('Operator list length =', opList.fnArray.length);
})();

### What is the expected behavior?

The PDF file I gave him is a small blank file, so he should be able to process it quickly and return it.

### What went wrong?

I encountered a memory leak when running the following code.

Image

### Link to a viewer

_No response_

### Additional context

_No response_

### LINKED ISSUE #20461: [Bug]: pdf.js busy-loops forever on JBIG2 image that uses the symbol dictionary context retain/reuse feature
### Attach (recommended) or Link to PDF file

[bitmap-symbol-context-reuse.pdf](https://github.com/user-attachments/files/23752672/bitmap-symbol-context-reuse.pdf)

### Web browser and its version

Firefox 145.0

### Operating system and its version

macOS 15.6.1

### PDF.js version

Whatever is in the latest firefox

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

Open file above.

### What is the expected behavior?

Renders fine (or fails to render).

### What went wrong?

Spins forever, keeping one core at 100%

### Link to a viewer

_No response_

### Additional context

This is a synthetic test case. https://github.com/SerenityOS/serenity/pull/26419 has some more details on it. The json file in https://github.com/SerenityOS/serenity/commit/38ebe688245ac23954cc87cede37f40883738767 shows the file contents.

Since this file only uses up to 3 referred-to segments, I believe this is a different bug than #20439.

The file was written by a tool I wrote, and it's possible that the bitstream is somehow off. However, PDFium and Acrobat Reader can both decode it fine. (And even if it's not decoded fine, it at least shouldn't busy-loop.)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
*Note:* This is similar to PR #19525, which did the same thing for the OpenJPEG decoder.

The advantages of doing this are:
 - The same JBig2 decoder is used regardless of WASM being supported or not, which means consistent rendering.
 - The old `Jbig2Image` implementation has various bugs and missing features.
 - Less code that needs to be maintained in the PDF.js project, since both the CCITT and the JBig2 decoder is replaced.

The disadvantage of doing this is:
 - Slightly larger bundle size, however the effect is limited since a fair amount of PDF.js code can be removed. For the `gulp mozcentral` target the size increase is approximately 54 kilo-bytes (which is small compared to the 452 kilo-bytes for the JS version of the OpenJPEG decoder).

### CODE REVIEW

**Comment by calixteman** [comment]
@Snuffleupagus did you use https://github.com/mozilla/pdf.js.jbig2 ?
If yes, could you make a PR to update it with your changes ?

**Comment by Snuffleupagus** [comment]
> did you use https://github.com/mozilla/pdf.js.jbig2 ?

Yes, of course :-)

> If yes, could you make a PR to update it with your changes ?

I didn't make any changes, but I simply ran `node build.js --compile --output output_dir -t=js` to get a `.js` file instead of the default `.wasm` one.

**Comment by calixteman** [comment]
Is this patch causing the unit test failure ?

**Comment by Snuffleupagus** [comment]
> Is this patch causing the unit test failure ?

Yes, but I believe it might be partially a pre-existing issue since just updating this line doesn't actually seem to help:
https://github.com/mozilla/pdf.js/blob/fe48736846e2043696738bd54435ebb5ab24ecff/test/unit/test_utils.js#L35

Compared to other resources such as CMaps and StandardFonts, the wasm files are placed in separate folders (under the top-level `external/` folder) and I've had zero luck updating that line to make this work both locally and on the bots :-(

**Comment by calixteman** [comment]
> > Is this patch causing the unit test failure ?
> 
> Yes, but I believe it might be partially a pre-existing issue since just updating this line doesn't actually seem to help:
> 
> https://github.com/mozilla/pdf.js/blob/fe48736846e2043696738bd54435ebb5ab24ecff/test/unit/test_utils.js#L35
> 
> Compared to other resources such as CMaps and StandardFonts, the wasm files are placed in separate folders (under the top-level `external/` folder) and I've had zero luck updating that line to make this work both locally and on the bots :-(

I think it could work with: 
`const WASM_URL = isNodeJS  ? "./external/openjpeg/"  : "../../build/generic/web/wasm/";`

**Comment by Snuffleupagus** [comment]
> I think it could work with:
> `const WASM_URL = isNodeJS ? "./external/openjpeg/" : "../../build/generic/web/wasm/";`

That seems to have worked, thank you!

---

Looking at the ref-test failures, they should be fine since:
 - `firefox-xfa_annual_expense_report-page6` and `firefox-issue19753-page1` looks unrelated, probably caused by the Firefox 152 update.
 - `firefox-issue15942-page1` has corrupt JBig2 images, so exactly how it fails seems irrelevant (and we match Adobe Reader now).
 - `firefox-issue17779-partial-page1` should be unrelated, since it's been "failing" in other PRs for a little while.
 - `firefox-jbig2_bitmap_...`, a lot of files, are all fixed now.

File: src/core/jbig2_ccittFax.js [hunk 1]
```diff
@@ -41,6 +46,24 @@ class JBig2CCITTFaxWasmImage {
     }
   }
 
+  static async #getJsModule(fallbackCallback) {
```
Comment (calixteman) [inline src/core/jbig2_ccittFax.js:49]: We've pretty similar code here and in the jpx one. So we should follow-up for refactoring that stuff for having almost one class and 2 subclasses, something like that.

**Review by calixteman — APPROVED** [review]
LGTM. Thank you for doing that.

File: src/core/jbig2_ccittFax.js (hunk 1 above)
Comment (Snuffleupagus) [reply src/core/jbig2_ccittFax.js:49]: Completely agreed, and it did occur to me when writing the patch however I wanted to avoid this PR becoming unnecessarily large.

**Comment by timvandermeij** [comment]
Nice work! That's a big reduction in code we have to maintain here.

**Comment by Snuffleupagus** [comment]
@calixteman When this patch reaches mozilla-central, please make sure that the new `web/wasm/jbig2_nowasm_fallback.js` file is added to the list in https://searchfox.org/firefox-main/source/toolkit/components/pdfjs/jar.mn to prevent rendering errors for users that have WASM disabled.
