### PR TITLE
Don't render corrupted inlined images

### LINKED ISSUE #17794: Incorrect rendering with some inlined images
Attach (recommended) or Link to PDF file here:
[image1.pdf](https://github.com/mozilla/pdf.js/files/14607428/image1.pdf)

For context, the pdf has been found on the PDFBox bug tracker:
https://issues.apache.org/jira/projects/PDFBOX/issues/PDFBOX-5776

Configuration:
- Web browser and its version: Firefox nightly
- Operating system and its version: Mac

Steps to reproduce the problem:
1. Open the pdf
2. only one image is rendered

What is the expected behavior? (add screenshot)
From Preview
image

The file contains some inlined images without the closing `EI`.

### PR DESCRIPTION
**Pull request by calixteman**
Fixes #17794.

### CODE REVIEW

File: src/core/evaluator.js [hunk 1]
```diff
@@ -739,27 +739,31 @@ class PartialEvaluator {
...
+        );
+        operatorList.isOffscreenCanvasSupported =
+          this.options.isOffscreenCanvasSupported;
+        operatorList.addImageOps(
+          OPS.paintInlineImageXObject,
+          [imgData],
+          optionalContent
+        );
+      } catch (reason) {
+        warn(`Unable to decode inline image: "${reason}".`);
```
Comment (Snuffleupagus) [inline src/core/evaluator.js:765]: Please don't forget about the `ignoreErrors` mode.
 ```suggestion
         const msg = `Unable to decode inline image: "${reason}".`;
        
         if (!this.options.ignoreErrors) {
           throw new Error(msg);
         }
         warn(msg);     
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, with the comment addressed and passing tests; thank you!
