### PR TITLE
Prevent interaction with form elements in PresentationMode (issue 12232)

### LINKED ISSUE #12232: Checkmarks can be edited while in Presentation mode
**Affected versions**
* 81.0a1 (2020-08-17)

**Affected platforms**
* Windows 10
* macOS 10.15
* Ubuntu 18.04 64bit

**Steps to reproduce**
pdfjs.renderInteractiveForms - true

1. Launch Firefox
2. Access a PDF form with fillable content (eg: https://www.irs.gov/pub/irs-pdf/f1040.pdf)
3. Enter presentation mode
4. Scroll to page 2 and try and fill the form

**Expected result**
* Form can't be edited since we are in presentation mode.

**Actual result**
* Checkmarks can still be edited while in presentation mode.

**Additional notes**
* S3 as suggested severity, not sure how many people use presentation mode
* Not sure if this is intended behavior or not though

### PR DESCRIPTION
**Pull request by Snuffleupagus**
- Prevent mouse interaction with form elements in PresentationMode (issue 12232)
 - Prevent keyboard interaction with form elements in PresentationMode (issue 12232)

   This uses the relatively new `HTMLElement.inert` property, see https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/inert for additional information. The only "problem" is that this isn't yet available in all Firefox channels, but until https://bugzilla.mozilla.org/show_bug.cgi?id=1764263 is fixed we're no worse off than before.

### CODE REVIEW

File: web/annotation_layer_builder.js [hunk 1]
```diff
@@ -147,6 +174,29 @@ class AnnotationLayerBuilder {
...
+    switch (state) {
+      case PresentationModeState.FULLSCREEN:
+        disableFormElements = true;
+        break;
+      case PresentationModeState.NORMAL:
+        break;
+      default:
+        return;
+    }
+    for (const section of this.div.childNodes) {
```
Comment (calixteman) [inline web/annotation_layer_builder.js:193]: Isn't enough to add an `inert` in the `annotationLayer` div ?
I just tried:
```html
<div inert="true">
<input type="text" size="10"></input>
</div>
```
and the `input` is disabled.

File: web/annotation_layer_builder.js [hunk 2]
```diff
@@ -147,6 +174,29 @@ class AnnotationLayerBuilder {
...
+      if (section.hasAttribute("data-internal-link")) {
+        continue;
+      }
+      section.inert = disableFormElements;
```
Comment (calixteman) [inline web/annotation_layer_builder.js:197]: I think the attribute must be removed when `false`.

File: web/annotation_layer_builder.js (hunk 1 above)
Comment (Snuffleupagus) [reply web/annotation_layer_builder.js:193]: We still want *internal links* to be clickable, note the check just below, hence why this is done.

File: web/annotation_layer_builder.js (hunk 2 above)
Comment (Snuffleupagus) [reply web/annotation_layer_builder.js:197]: The current code seems to work, but I can certainly change this if you prefer that.

Comment (calixteman) [reply web/annotation_layer_builder.js:197]: Yeah, I just tested and it's working like this, so I'm ok with it.

**Review by calixteman — APPROVED** [review]
LGTM.

File: web/viewer.css [hunk 3]
```diff
@@ -222,8 +222,8 @@ body {
   user-select: none;
 }
 
-.pdfPresentationMode:fullscreen a:not(.internalLink) {
-  display: none;
+.pdfPresentationMode:fullscreen section:not([data-internal-link]) {
+  pointer-events: none;
```
[the remark this answers is not in the document]
Comment (Snuffleupagus) [reply web/viewer.css:226]: Given that we're already setting `user-select: none` on the entire viewerContainer, in PresentationMode, that part should already be covered:
https://github.com/mozilla/pdf.js/blob/e42e1cde6180b285a029b947c80c0583eeabca9c/web/viewer.css#L215-L223
