### PR TITLE
Move svg:clipPath generation from clip to endPath

### LINKED ISSUE #8527: SVG: TypeError: Cannot read property 'cloneNode' of undefined
Steps to reproduce, attached file: 
[cloneNode-undefined.pdf](https://github.com/mozilla/pdf.js/files/1074501/cloneNode-undefined.pdf)

````
npm install
gulp dist-install
node examples/node/pdf2svg.js /tmp/cloneNode-undefined.pdf
````

Console:
````
# Document Loaded
Number of Pages: 65

# Page 1
Size: 787.9433x525.2961

Error: TypeError: Cannot read property 'cloneNode' of undefined
````

### PR DESCRIPTION
**Pull request by Rob--W**
See the commit message for a detailed explanation.

I think that we also need to check whether it is necessary to add more `.endPath` calls to src/display/svg.js, similar to the many `consumePath` calls in src/display/canvas.js. However I don't understand that part of the code well enough to tell whether it's needed.

Fixes #8527 
Seems to improve #8496 (https://github.com/mozilla/pdf.js/issues/8496#issuecomment-309432026)

### CODE REVIEW

File: src/display/svg.js [hunk 1]
```diff
@@ -264,6 +264,7 @@ var SVGExtraState = (function SVGExtraStateClosure() {
     this.dependencies = [];
 
     // Clipping
+    this.pendingClip = null;
```
Comment (timvandermeij) [inline src/display/svg.js]: It does not look like you store the pending clip in the `SVGExtraState` object (but instead as a property of `SVGGraphics`), so I think this should be moved to above https://github.com/mozilla/pdf.js/pull/8542/files?w=1#diff-84f753e2bb39669e059ce3447e5a0057R365, just like in `canvas.js`.

File: src/display/svg.js [hunk 2]
```diff
@@ -894,36 +896,41 @@ SVGGraphics = (function SVGGraphicsClosure() {
       current.setCurrentPoint(x, y);
     },
 
-    endPath: function SVGGraphics_endPath() {},
+    endPath: function SVGGraphics_endPath() {
+      if (this.pendingClip) {
```
Comment (timvandermeij) [inline src/display/svg.js]: I think we should use this instead:

```javascript
if (!this.pendingClip) {
  return;
}
```

That way we avoid a level of indenting, which improves readability.

**Review by timvandermeij — CHANGES_REQUESTED** [review]

File: src/display/svg.js (hunk 1 above)
Comment (Rob--W) [inline src/display/svg.js]: You're right, fixed.

File: src/display/svg.js (hunk 2 above)
Comment (Rob--W) [inline src/display/svg.js]: Done too.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you for fixing this!
