### PR TITLE
XFA - Add back empty subforms (which can have a background)

### LINKED ISSUE #13579: XFA background color not drawn in issue13500
Attach (recommended) or Link to PDF file here:
issue13500 (in test corpus)

This regressed when landing #13566. 

What is the expected behavior? (add screenshot)
image

What went wrong? (add screenshot)
image

### PR DESCRIPTION
**Pull request by calixteman**
It aims to fix issue #13579.

### CODE REVIEW

File: src/core/xfa/template.js [hunk 1]
```diff
@@ -4649,7 +4641,8 @@ class Template extends XFAObject {
       const flush = index => {
         const html = root[$flushHTML]();
         if (html) {
-          hasSomething = true;
+          hasSomething =
+            hasSomething || (html.children && html.children.length !== 0);
```
Comment (Snuffleupagus) [inline src/core/xfa/template.js:4645]: Nit: Here, and similarly below, this can be a bit more compact by instead formatting it as:
```javascript
hasSomething ||= (html.children && html.children.length !== 0);
```

Comment (calixteman) [reply src/core/xfa/template.js:4645]: I wrote that but the linter failed. And I tried again with parenthesis and it failed again. Do I miss something ?

**Review by marco-c — APPROVED** [review]
