### PR TITLE
[Editor] Remove almost all the waitForTimeout from the freetext integration tests

### LINKED ISSUE #16968: Fix integration test "FreeText Editor FreeText rotation must check that the dimensions of a rotated annotations are correct after a font size change"
Introduction date: July 4, 2023
Introduction PR: https://github.com/mozilla/pdf.js/commit/1ce6668a7071178bd08e5b817473eea780cd4d07 (/cc @calixteman)
Type: intermittent (sometimes it works, indicating a possible timing/waiting issue)
OS: Windows
Logs: http://54.193.163.58:8877/d67e98b920493b4/output.txt
Traceback:

```
Failures:
1) FreeText Editor FreeText rotation must check that the dimensions of a rotated annotations are correct after a font size change
  Message:
[31m    In firefox: Expected false to equal true.[0m
  Stack:
        at <Jasmine>
        at C:\pdfjs\botio-files-pdfjs\private\d67e98b920493b4\test\integration\freetext_editor_spec.js:1341:14
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Promise.all (index 0)
        at async UserContext.<anonymous> (C:\pdfjs\botio-files-pdfjs\private\d67e98b920493b4\test\integration\freetext_editor_spec.js:1273:7)
```

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

File: test/integration/test_utils.js [hunk 1]
```diff
@@ -119,6 +119,17 @@ const waitForStorageEntries = async (page, nEntries) => {
...
+  await page.waitForFunction(
+    n =>
+      (window.PDFViewerApplication.pdfDocument.annotationStorage.serializable
+        ?.map?.size ?? 0) === n,
+    {},
+    nEntries
+  );
+};
+exports.waitForSerialized = waitForSerialized;
+
```
Comment (Snuffleupagus) [inline test/integration/test_utils.js:132]: I'm probably missing some details here but do we actually "need" this new function, or can we perhaps make use the existing `waitForStorageEntries` one just above instead?

File: test/integration/test_utils.js [hunk 2]
```diff
@@ -203,6 +214,7 @@ async function dragAndDropAnnotation(page, startX, startY, tX, tY) {
   await page.waitForTimeout(10);
   await page.mouse.move(startX + tX, startY + tY);
   await page.mouse.up();
+  await page.waitForTimeout(10);
```
Comment (Snuffleupagus) [inline test/integration/test_utils.js:217]: In recent intermittent-fixes done by Tim the use of this sort of *very short* timeout was identified as a potential issue on slower hardware.
Any chance that we could await *something* rather than relying on a timeout here?

File: test/integration/freetext_editor_spec.js [hunk 3]
```diff
@@ -45,17 +46,58 @@ const copyPaste = async page => {
...
+    () => !!document.querySelector(".freeTextEditor:not(.selectedEditor)")
+  );
+};
+
+const clearAll = async page => {
+  await selectAll(page);
   await page.keyboard.down("Control");
   await page.keyboard.press("Backspace");
   await page.keyboard.up("Control");
   await page.waitForTimeout(10);
```
Comment (Snuffleupagus) [inline test/integration/freetext_editor_spec.js:63]: In recent intermittent-fixes done by Tim the use of this sort of *very short* timeout was identified as a potential issue on slower hardware.
Any chance that we could await *something* rather than relying on a timeout here?

File: test/integration/test_utils.js (hunk 1 above)
Comment (calixteman) [reply test/integration/test_utils.js:132]: The annotationStorage can contain pre-existing annotations but if they haven't been changed they won't be serialized.

File: test/integration/test_utils.js [hunk 4]
```diff
@@ -97,16 +97,31 @@ function getSelectedEditors(page) {
...
+        new Promise(resolve => {
+          document.addEventListener(name, () => resolve(false), { once: true });
+        }),
+      eventName
+    ),
+    page.evaluate(
+      (timeOut, name) =>
+        new Promise(resolve => {
+          setTimeout(() => {
+            console.log(`Timeout waiting for ${name}`);
```
Comment (Snuffleupagus) [inline test/integration/test_utils.js:114]: Given the logging below, why do we need this line as well?
If there's a good reason, please add a (short) comment explaining why.

File: test/integration/test_utils.js [hunk 5]
```diff
@@ -97,16 +97,31 @@ function getSelectedEditors(page) {
...
+            resolve(true);
+          }, timeOut);
+        }),
+      timeout,
+      eventName
+    ),
   ]);
+  if (hasTimedout === true) {
+    console.log(`waitForEvent: timeout waiting for ${eventName}`, hasTimedout);
```
Comment (Snuffleupagus) [inline test/integration/test_utils.js:123]: Given the condition just above, isn't it sufficient to simply do the following?
```suggestion
    console.log(`waitForEvent: timeout waiting for ${eventName}`);
```

File: test/integration/test_utils.js [hunk 6]
```diff
@@ -203,6 +225,8 @@ async function dragAndDropAnnotation(page, startX, startY, tX, tY) {
   await page.waitForTimeout(10);
   await page.mouse.move(startX + tX, startY + tY);
   await page.mouse.up();
+  await page.waitForTimeout(10);
```
Comment (Snuffleupagus) [inline test/integration/test_utils.js:228]: Given the explicit waiting on the next line, do we still need this one?

**Review by Snuffleupagus — APPROVED** [review]
Please run the integration-tests a couple of times to ensure that there's no new intermittent failures.

r=me, with a few more questions; thank you!

**Comment by calixteman** [comment]
@Snuffleupagus, are you still ok with the patch ?

**Comment by Snuffleupagus** [comment]
> are you still ok with the patch ?

First of all, there's now been a fair number of changes since I last looked and the earliest that I'll be able to re-review is tomorrow.
Secondly, with this no longer being a *test only* patch but it now also making changes to "regular" code this will probably require another level of scrutiny. Any chance that this could be split-up a bit, at least into multiple commits, to aid reviewing?

File: test/integration/test_utils.js [hunk 7]
```diff
@@ -119,13 +130,20 @@ const waitForStorageEntries = async (page, nEntries) => {
 };
 exports.waitForStorageEntries = waitForStorageEntries;
 
-const waitForSelectedEditor = async (page, selector) => {
+const waitForSerialized = async (page, nEntries) => {
   await page.waitForFunction(
-    sel => document.querySelector(sel).classList.contains("selectedEditor"),
+    n =>
+      (window.PDFViewerApplication.pdfDocument.annotationStorage.serializable
+        ?.map?.size ?? 0) === n,
```
Comment (Snuffleupagus) [inline test/integration/test_utils.js:137]: Nit: Looking at [the `serializable` getter](https://github.com/mozilla/pdf.js/blob/52862893f5bef7ff6c7b8f816154d8fec00f49e7/src/display/annotation_storage.js#L178-L215) it should always return something, hence we ought to be able to skip the *first* optional chaining here.
```suggestion
      (window.PDFViewerApplication.pdfDocument.annotationStorage.serializable
        .map?.size ?? 0) === n,
```

File: test/integration/freetext_editor_spec.js [hunk 8]
```diff
@@ -45,17 +47,58 @@ const copyPaste = async page => {
...
+  await page.click("#editorFreeText");
+  await page.waitForSelector(".annotationEditorLayer.freetextEditing");
 };
 
+const waitForBeingSelected = (page, selector) =>
+  page.waitForFunction(
+    sel => document.querySelector(sel).classList.contains("selectedEditor"),
+    {},
+    selector
+  );
```
Comment (Snuffleupagus) [inline test/integration/freetext_editor_spec.js:77]: This looks quite similar to the general `waitForSelectedEditor` helper, in the `test_utils.js` file; can we perhaps use that one instead?

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you!
