### PR TITLE
[api-minor] Add basic support for the `SetOCGState` action (issue 15372)

### LINKED ISSUE #15372: 'SetOCGState' action is not supported
Attach (recommended) or Link to PDF file here:
[sample2.pdf](https://github.com/mozilla/pdf.js/files/9460818/sample2.pdf)

Configuration:
- Web browser and its version: Firefox 104.0 (64-bit)
- Operating system and its version: Windows 10 Enterprise 20H2
- PDF.js version: 2.15.303 and 3.0.11
- Is a browser extension: No

Steps to reproduce the problem:
1. Show Layers panel
2. Uncheck 'Layer' to hide a layer
3. Show Document Outline panel
4. Click 'Display Layer' outline and see if the hidden layer appears back

**What is the expected behaviour? (add screenshot)**
image
According to PDF Reference, set-OCG-state action should set the state of one or more optional content groups and for this sample pdf, the hidden layer should be back visible.

**What went wrong? (add screenshot)**
The outline performs no action.
When the sample pdf is opened in Adobe Reader, the outline works fine.

On loading the sample pdf, below message is displayed in console.
```console
Warning: parseDestDictionary - unsupported action: "SetOCGState".
```

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Note that this patch implements the `SetOCGState`-handling in `PDFLinkService`, rather than as a new method in `OptionalContentConfig`[1], since this action is nothing but a series of `setVisibility`-calls and that it seems quite uncommon in real-world PDF documents.

The new functionality also required some tweaks in the `PDFLayerViewer`, to ensure that the `layersView` in the sidebar is updated correctly when the optional-content visibility changes from "outside" of `PDFLayerViewer`.

---
[1] We can obviously move this code into `OptionalContentConfig` instead, if deemed necessary, but for an initial implementation I figured that doing it this way might be acceptable.

### CODE REVIEW

File: web/pdf_link_service.js [hunk 1]
```diff
@@ -493,6 +493,48 @@ class PDFLinkService {
...
+    const optionalContentConfig = await this.pdfViewer
+      .optionalContentConfigPromise;
+
+    if (pdfDocument !== this.pdfDocument) {
+      return; // The document was closed while the optional content resolved.
+    }
+    let operator;
+
+    for (const elem of action.state) {
+      switch (elem) {
```
Comment (timvandermeij) [inline web/pdf_link_service.js:510]: I don't really see why this `switch` and the `operator` variable are necessary. Simply switching on `elem` instead of `operator` below should do the same as far as I can tell: only ON/OFF/Toggle are handled anyway and any other value simply does nothing.

File: src/core/catalog.js [hunk 2]
```diff
@@ -1533,6 +1534,38 @@ class Catalog {
...
+            break;
+          }
+          const stateArr = [];
+
+          for (const elem of state) {
+            if (elem instanceof Name) {
+              switch (elem.name) {
+                case "ON":
+                case "OFF":
+                case "Toggle":
```
Comment (timvandermeij) [inline src/core/catalog.js:1551]: Does this casing originate from the PDF specification? It seems a bit odd that ON/OFF are written with capital letters only while Toggle is not.

Comment (Snuffleupagus) [reply src/core/catalog.js:1551]: Yes, unfortunately this is how it's being specified; please see https://web.archive.org/web/20220309040754if_/https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf#G11.1990554

File: web/pdf_link_service.js (hunk 1 above)
Comment (Snuffleupagus) [reply web/pdf_link_service.js:510]: *Sorry, I forgot to include a spec-link above.*

As you can see in the example in https://web.archive.org/web/20220309040754if_/https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf#G11.1990554 there can be *multiple* layer-Refs after any "operator", which thus (as far as I can tell) require us to track of the last seen operator.

Comment (timvandermeij) [reply web/pdf_link_service.js:510]: Ah, right, that explains it indeed. Thanks!

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you for implementing this!
