### PR TITLE
Fix the intermittent failures with PageOpen/PageClose test

### LINKED ISSUE #17200: Fix integration test "Interaction in doc_actions.pdf for page actions must execute PageOpen and PageClose actions"
Introduction date: January 6, 2021
Introduction PR: https://github.com/mozilla/pdf.js/commit/6523f8880bd91cf1f8ccbf0215dd7e1ea1590e9f (/cc @calixteman)
Type: intermittent (sometimes it works, indicating a possible timing/waiting issue)
OS: Windows
Logs: http://54.193.163.58:8877/fd28713f242b505/output.txt (first occurence in PR https://github.com/mozilla/pdf.js/pull/17189) and http://54.193.163.58:8877/5b351a2570b0587/output.txt (example of a later occurrence from yesterday)
Traceback:

```
Failures:
1) Interaction in doc_actions.pdf for page actions must execute PageOpen and PageClose actions
  Message:
[31m    Error: Timeout - Async function did not complete within 30000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)[0m
  Stack:
        at <Jasmine>
        at listOnTimeout (node:internal/timers:569:17)
        at process.processTimers (node:internal/timers:512:7)
```

Additional notes: it looks like this one started failing quite often on Windows since https://github.com/mozilla/pdf.js/commit/d72fd9ce4f1c4727cc07652fa3dc6c1208cd7d53 because it didn't seem to fail before that. The integration test itself wasn't touched in that PR, but the `scrollIntoView` helper function that is uses was in https://github.com/mozilla/pdf.js/commit/d72fd9ce4f1c4727cc07652fa3dc6c1208cd7d53#diff-9a5f53e72714b4209a2aa581af6e316d1908ce47d7d3d4992ae6a99174fc4869L254-L283 so perhaps that has something to do with this?

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

File: test/integration/test_utils.mjs [hunk 1]
```diff
@@ -252,26 +252,19 @@ async function waitForTextLayer(page) {
...
-      return (
-        Math.abs(top) < toolbarHeight + 100 ||
-        Math.abs(bottom - window.innerHeight) < 100 ||
-        (top > toolbarHeight && bottom < window.innerHeight)
-      );
-    },
-    {},
-    selector
-  );
+  await promise;
```
Comment (timvandermeij) [inline test/integration/test_utils.mjs:267]: Would it be possible to just `await page.evaluate` here so we don't need to define the logic above and get rid of the intermediate `promise` variable? Maybe even better: can't we just put this logic in the existing `await page.evaluate` block right after the `element.scrollIntoView` call? That way this function becomes smaller and easier to read. We'd end up with something like this:

```js
async function scrollIntoView(page, selector) {
  await page.evaluate(sel => {
    const element = document.querySelector(sel);
    element.scrollIntoView({ behavior: "instant", block: "start" });
    return new Promise(resolve => {
        document
          .getElementById("viewerContainer")
          .addEventListener("scrollend", resolve, { once: true });
      });
  }, selector);
}
```

**Review by timvandermeij — COMMENTED** [review]
The approach in this PR looks a lot easier than what we had. It does seem to fail the "must compute sum of fields" on both Linux and Windows, but it could also be that the fix here highlights an issue with that particular test, or we need to await something else here. In any case, I think this patch is going in the right direction.

**Review by timvandermeij — APPROVED** [review]
r=me if this test doesn't fail anymore after e.g. two more runs; thank you for fixing and simplifying this!
