### PR TITLE
[api-minor] Highlight search results correctly for normalized text (PR 9448)

### LINKED ISSUE #5668: Search feature is highlighting wrong text
https://pdf.yt/d/BeioWriXAn-DkFcO

When searching the above pdf for the phrase 'acute' the second hit hightlights the nearby word ' especi'.  Almost certainly this is the same issue that I raised in #5667 

However, when examining the generated html you can see that the highlighted text is incorrect - it contains the text ' especi' and not the search term 'acute' - it is not a positioning issue.  (see screenshot).

I am using Chrome 39, windows 8.1 x64 and pdf.js 1.0.1093

image

### LINKED ISSUE #7230: searching is selecting the context next to the exact word
Here, i have attached the PDF, that PDF document contains "Nudi" as an embedded font. When i searching the particular word (that in Nudi font), the search result selecting the word that context next to the exact word.

Link to PDF file (or attach file here):
[sample_pdf.zip](https://github.com/mozilla/pdf.js/files/229582/sample_pdf.zip)

Configuration:
- Web browser and its version: Mozilla 45.0.2
- Operating system and its version: Windows 7
- PDF.js version: 1.4.20-disc

What is the expected behavior? (add screenshot)
find_01

### LINKED ISSUE #10708: Find highlight all does not always mark words correctly
Attach (recommended) or Link to PDF file [here:]
[Ring 5_Final_low.pdf](https://github.com/mozilla/pdf.js/files/3033095/Ring.5_Final_low.pdf)

Configuration:
- Web browser and its version: Chrome Version 73.0.3683.86 (Official Build) (64-bit)
- Operating system and its version: MacOS 10.14.3
- PDF.js version: the problem is seen in https://mozilla.github.io/pdf.js/web/viewer.html?file= so I guess that is the newest one.
- Is a browser extension: no

Steps to reproduce the problem:
1. Load Ring.5_Final_low.pdf
2. Search for Hillerød
3. Check Highlight all
4. Go to page 13

What is the expected behavior? (add screenshot)
The word Hillerød should be highlighted twice

What went wrong? (add screenshot)
Some other words are highlighted.
Screenshot 2019-04-02 at 10 59 26

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### PR DESCRIPTION
**Pull request by Snuffleupagus**
This patch is a rebased *and* refactored version of PR 9448, such that it applies cleanly given that `PDFFindController` has changed since that PR was opened; obviously keeping the original author information intact.

This patch will thus ensure that e.g. fractions, and other things that we normalize before searching, will still be highlighted correctly in the textLayer.

Furthermore, this patch also adds basic unit-tests for this functionality.

*Note:* The `[api-minor]` tag is added, since third-party implementations of the `PDFFindController` must now always use the `pageMatchesLength` property to get accurate length information (see the `web/text_layer_builder.js` changes).

Fixes #5668
Fixes #7230
Fixes #10708
Fixes [bug 1680858](https://bugzilla.mozilla.org/show_bug.cgi?id=1680858)

### CODE REVIEW

File: test/unit/clitests_helper.js [hunk 1]
```diff
@@ -18,6 +18,9 @@ import { isNodeJS } from "../../src/shared/is_node.js";
 import { PDFNodeStream } from "../../src/display/node_stream.js";
 import { setPDFNetworkStreamFactory } from "../../src/display/api.js";
 
+// Sets longer timeout, similar to `jasmine-boot.js`.
+jasmine.DEFAULT_TIMEOUT_INTERVAL = 30000;
+
```
Comment (Snuffleupagus) [inline test/unit/clitests_helper.js:23]: As far as I can tell this timeout has been too low since "forever", but apparently it hasn't really been an issue previously.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thanks a lot for fixing up this old PR! I found this version easier to follow, and with the added unit tests I have much more trust in that the functionality is correct.
