### PR TITLE
[Editor] Commit the current drawing before switching the current mode

### LINKED ISSUE #19793: [Bug]: Annotations issue. TypeError: null is not an object (evaluating 'this.#touchMoveAC.abort')
### Attach (recommended) or Link to PDF file

[blank.pdf](https://github.com/user-attachments/files/19669325/blank.pdf)

Im using a simple plain blank pdf file. I have this issue with all pdf's. Its not document specific.

### Web browser and its version

latest safari version on iPhone

### Operating system and its version

iOS latest

### PDF.js version

5.1.91 latest

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

If i draw in my pdf document i can provoke an error that i can basically only fix by restarting pdf.js.
Unfortunately I didnt figure out a way to reliably reproduce it every time but it happens really often and regularly nearly every time I try to draw. I see it happen most often if i zoom a bit draw something move around and draw again. Sometimes it happens immediately but sometimes it takes me a few drawings but definitely way to often to ignore. The error is happening as soon as i lift the finger after a I tried to draw a line (makes sense bcs its ontouchend).

"TypeError: null is not an object (evaluating 'this.#touchMoveAC.abort')"

Image

### What is the expected behavior?

If i start to use annotations / drawings i can't move the page and I can no longer draw.

### What went wrong?

Its hard to see but right at the beginning I zoom into the document and if i switch to annotation I cant draw bcs the console error appears. As written above sometimes like in this case right from the start sometimes it takes a few scribbles but defenetly in every session.

https://github.com/user-attachments/assets/b9996f13-f07a-4eb8-9c5f-2db842efd3e2

### Link to a viewer

_No response_

### Additional context

Bonus: If i debug and check the lines i can see this

Image

This is the context where the error happens so as you can see this.#touchmoveac is null therefore the error is valid

Image

### PR DESCRIPTION
**Pull request by calixteman**
It fixes #19793.

### CODE REVIEW

File: src/display/touch_manager.js [hunk 1]
```diff
@@ -215,9 +215,12 @@ class TouchManager {
     if (evt.touches.length >= 2) {
       return;
     }
-    this.#touchMoveAC.abort();
-    this.#touchMoveAC = null;
-    this.#onPinchEnd?.();
+    // #touchMoveAC shouldn't be null be it seems that irl it can (see #19793).
```
Comment (Snuffleupagus) [inline src/display/touch_manager.js:218]: Nit:
```suggestion
    // #touchMoveAC shouldn't be null but it seems that irl it can (see #19793).
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you.
