### PR TITLE
Don't read past the EOI marker for JPEG images with non-default restart interval (issue 7828)

### LINKED ISSUE #7828: JPEG error: unexpected marker ffd9
Link to PDF file (or attach file here):
[Untitled_20160807_114311.pdf](https://github.com/mozilla/pdf.js/files/601312/Untitled_20160807_114311.pdf)

Configuration:
- Web browser and its version: Chrome 54.0
- Operating system and its version: Window 10
- PDF.js version: 1.6.329
- Is an extension:

What is the expected behavior? (add screenshot)

untitled_20160807_114311

What went wrong? (add screenshot)
Show a white page.

* Console:
console log

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### PR DESCRIPTION
**Pull request by Snuffleupagus**
*After browsing through (a version of) the JPEG specification, see https://www.w3.org/Graphics/JPEG/itu-t81.pdf, I hope that this patch makes sense.*

Note that while issue #7828 became a problem after PR #7661, it isn't really a regression from that PR. The explanation is rather that we're now relying on `core/jpg.js` instead of the Native Image decoder in more situations than before, which thus exposed an *existing* issue in our JPEG decoder.
Another factor also seems to be that in many JPEG images, the DRI (Define Restart Interval) marker isn't present, in which case this bug won't manifest either.

According to https://www.w3.org/Graphics/JPEG/itu-t81.pdf#page=89 (at the bottom of the page):
> "NOTE – The final restart interval may be smaller than the size specified by the DRI marker segment, as it includes only the number of MCUs remaining in the scan."

Furthermore, according to https://www.w3.org/Graphics/JPEG/itu-t81.pdf#page=39 (in the middle of the page):
> "[...] If restart is enabled and the restart interval is defined to be Ri, each entropy-coded segment except the last one shall contain Ri MCUs. The last one shall contain whatever number of MCUs completes the scan."

Based on the above, it thus seem to me that we should simply ensure that we're not attempting to continue to parse Scan data once we've found all MCUs (Minimum Coded Unit) of the image.

Fixes #7828.

### CODE REVIEW

File: src/core/jpg.js [hunk 1]
```diff
@@ -332,6 +332,7 @@ var JpegImage = (function JpegImageClosure() {
     if (!resetInterval) {
       resetInterval = mcuExpected;
     }
+    var nonDefaultResetInterval = resetInterval !== mcuExpected;
```
Comment (yurydelendik) [inline src/core/jpg.js]: Can this logic here be expressed by replacing new code and the if above to `resetInterval = resetInterval ? Math.min(mcuExpected, resetInterval) : mcuExpected;`?

Comment (Snuffleupagus) [inline src/core/jpg.js]: I don't think so, and quick testing seem confirm it, since provided that I'm reading the specification correctly (see the quotes above) it should only be the *last* `mcu` where the `resetInterval` could potentially be an issue.

Comment (yurydelendik) [inline src/core/jpg.js]: duh. how about `var toRead = resetInterval ? Math.min(mcuExpected - mcu, resetInterval) : mcuExpected;` inside the loop?

Comment (Snuffleupagus) [inline src/core/jpg.js]: That works better, and it's less code as well :-)

**Review by yurydelendik — APPROVED** [review]
Looks good.
