### PR TITLE
Remove/deprecate specifying a pageNumber directly after the hash symbol (#), to improve compatibility since other PDF viewers don't support this form (issue 7746)

### LINKED ISSUE #7746: Numeric destination in URL taken as page number
**Link to PDF file (or attach file here):**
http://unesdoc.unesco.org/images/0021/002160/216066f.pdf#216095
http://unesdoc.unesco.org/images/0013/001346/134685E.pdf#4.3
http://unesdoc.unesco.org/images/0013/001346/134685E.pdf#4

**Configuration:**
- Web browser and its version:
Firefox 49.0.2
- Operating system and its version:
Windows 10
- PDF.js version:
[don't know], the regular version for Fx 49
- Is an extension:
[don't know]

**Steps to reproduce the problem:**
Open the 3 PDFs given above in Firefox+pdf.js or IE + Acrobat Reader

**What is the expected behavior? (add screenshot)**
The expected behavior is Acrobat Reader's behavior : the document opens at the given destination which is on
page 14 for first example
page 42 for second example
page 41 for third example

**What went wrong? (add screenshot)**
With pdf.js, only the second example opens correctly
The first one opens on first page
The third one opens on page 4

I suspect that pdf.js takes the destination as a page number when the destination is a integer decimal number (in the first example, the given number is too big)

At UNESCO, we rely heavily on destinations often formed of a single integer number and the behavior of pdf.js does not allow to get the correct document part

### PR DESCRIPTION
**Pull request by Snuffleupagus**
There's no mention of our `#{pagenum}` form in http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_open_parameters.pdf, and Adobe Reader doesn't seem to support it either.
Hence this patch removes support for it in the extensions, but keeps it in the `GENERIC` build with a deprecation warning and a fallback to handle it as a destination.

Fixes #7746.

### CODE REVIEW

File: web/pdf_link_service.js [hunk 1]
```diff
@@ -258,9 +258,15 @@ var PDFLinkService = (function PDFLinkServiceClosure() {
             mode: params.pagemode
           });
         }
-      } else if (isPageNumber(hash)) { // Page number.
-        this.page = hash | 0;
       } else { // Named (or explicit) destination.
+        if ((typeof PDFJSDev === 'undefined' || PDFJSDev.test('GENERIC')) &&
+            (isPageNumber(hash) && hash < this.pagesCount)) {
```
Comment (timvandermeij) [inline web/pdf_link_service.js]: This should be `hash <= this.pagesCount`. Try with the Tracemonkey paper: #13 will give the warning, #14 will not, even though it's a valid page number.

Moreover, we can get rid of the extra parentheses around the second condition.

Comment (Snuffleupagus) [inline web/pdf_link_service.js]: D'oh! You're obviously correct, don't know how I managed to make that kind of mistake in such a small patch. Good eye, thanks :-)

**Comment by timvandermeij** [comment]
Nice work!
