### PR TITLE
Ensure that Mesh /Shadings have non-zero width/height (issue 17848)

### LINKED ISSUE #17848: Error with 0 width / height shaders
I've come across some PDFs where pages are partially rendered in PDF.js but display fully in Acrobat & Chrome. These files appear to be CAD drawings converted to PDF format. The PDFs have a `Creator` value of `AcroPlot Pro (Build 2018-01-24) - www.cadzation.com` and a `Producer` of `PDF-XChange (xcpro40.dll v4.0.0316.0001) (Windows)`.

I've tracked the issue down to some problematic shaders in the page's `/Shading` resource dictionary. Specifically, there are some shaders that seem to have 0 width and/or 0 height, which causes a rendering error in PDF.js.

The relevant shader handling code is around here: https://github.com/mozilla/pdf.js/blob/841d57df462a19a4db8acfaa18ebe85269fb0c03/src/display/pattern_helper.js#L342

With these problematic shaders, any of boundsWidth / boundsHeight / width / height may be 0, and scaleX / scaleY can end up as `NaN`, with the eventual thrown error coming from `createImageData()`. Perhaps such shaders need to be detected & ignored during rendering.

Attach (recommended) or Link to PDF file here:
I've hand written a sample file that uses one of these problematic shaders:
[minimal - shader issue.pdf](https://github.com/mozilla/pdf.js/files/14765362/minimal.-.shader.issue.pdf)

Configuration:
- Web browser and its version: Chrome 123, Firefox 124
- Operating system and its version: Windows 11
- PDF.js version: 4.1, 4.0.379
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the sample PDF
2. Notice error in browser console and lack of page content

What is the expected behavior? (add screenshot)
The document should show "Hello World"
image

What went wrong? (add screenshot)
PDF.js shows a blank page with error in console
image

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### PR DESCRIPTION
**Pull request by Snuffleupagus**

### CODE REVIEW

File: src/core/pattern.js [hunk 1]
```diff
@@ -956,13 +956,20 @@ class MeshShading extends BaseShading {
   }
 
   getIR() {
+    const { bounds } = this;
+    // Ensure that the shading has non-zero width and height, to prevent errors
+    // in `pattern_helper.js` (fixes issue17848.pdf).
+    if (bounds[2] - bounds[0] === 0 || bounds[3] - bounds[1] === 0) {
+      throw new FormatError(`Invalid MeshShading bounds: [${bounds}].`);
```
Comment (calixteman) [inline src/core/pattern.js:963]: It's useless to draw an empty shading but why is it an error ?

Comment (Snuffleupagus) [reply src/core/pattern.js:963]: Since we didn't previously handle errors properly during /Shading parsing, which this patch also adds, it seemed overall easier (implementation wise) to treat this case as an error as well.
And in some ways I think this particular case *can* be thought of as an error too, since the "empty" /Shading shouldn't have been included in the PDF document in the first place.

**Review by calixteman — APPROVED** [review]
LGTM. Thank you.
