### PR TITLE
Take into account CharProcs keys when computing the type3 hash

### LINKED ISSUE #19634: [Bug]: Incorrect rendering of type3 fonts
### Attach (recommended) or Link to PDF file

[PDFIUM-362796158-type3.pdf](https://github.com/user-attachments/files/19160554/PDFIUM-362796158-type3.pdf)

### Web browser and its version

FF 136.0

### Operating system and its version

Microsoft Windows [Version 10.0.19045.5555]

### PDF.js version

v4.10.38

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

open file

### What is the expected behavior?

Image

### What went wrong?

Image

### Link to a viewer

_No response_

### Additional context

The red glow around the glyphs is missing.
Note that the resources are not in the charprocs, but in the font itself, e.g. at `Root/Pages/Kids/[0]/Resources/Font/F8/Resources`
The File is from the google pdfium error tracker.

### PR DESCRIPTION
**Pull request by calixteman**
It fixes #19634.

### CODE REVIEW

File: src/core/evaluator.js [hunk 1]
```diff
@@ -4469,6 +4469,23 @@ class PartialEvaluator {
...
+      if (type.name === "Type3") {
+        // Type3 fonts with the same metrics/encoding but different CharProcs
+        // must not be aliased, since their glyphs may render completely
+        // differently (e.g. one font uses SMask glyph programs, another uses
+        // plain paths, see issue 19634).
+        const charProcs = baseDict.get("CharProcs");
+        if (charProcs instanceof Dict) {
+          for (const key of charProcs.getKeys()) {
+            hash.update(key);
+            const entry = charProcs.getRaw(key);
```
Comment (Snuffleupagus) [inline src/core/evaluator.js]: Nit:
```suggestion
          for (const [key, entry] of charProcs.getRawEntries()) {
            hash.update(key);
```

File: src/core/evaluator.js [hunk 2]
```diff
@@ -4469,6 +4469,22 @@ class PartialEvaluator {
...
+        // must not be aliased, since their glyphs may render completely
+        // differently (e.g. one font uses SMask glyph programs, another uses
+        // plain paths, see issue 19634).
+        const charProcs = baseDict.get("CharProcs");
+        if (charProcs instanceof Dict) {
+          for (const [key, entry] of charProcs.getRawEntries()) {
+            hash.update(key);
+            if (entry instanceof Ref) {
+              hash.update(entry.toString());
+            }
```
Comment (Snuffleupagus) [inline src/core/evaluator.js]: Given that a Type3 font could have up to 256 glyphs, this could theoretically mean updating the hash 512 times here.
Would that affect performance in any noticeable way?

Comment (calixteman) [reply src/core/evaluator.js]: I updated to just update the hash 256 times. I tried to profile with the Firefox profiler and overall it's under the millisec.

**Review by Snuffleupagus — APPROVED** [review]
(The patch is small, and I've basically reviewed it already given the previous nits/questions so "stealing" this.)

r=me, thank you.
