### PR TITLE
Ensure that hidden popups do not use any space

### LINKED ISSUE #6806: Popup annotations reserve space even when they are hidden
**STR:** Open http://www.nyc.gov/html/dcp/pdf/zone/map8c.pdf.

**ER:** No horizontal scrollbar, since the Popup annotation is hidden by default.

**AR:** The horizontal scrollbar *is* displayed, since the Popup annotation isn't hidden correctly. See screen-shot below.

This is a regression from PR #6792.
/cc @timvandermeij 

---
popup

### PR DESCRIPTION
**Pull request by timvandermeij**
Fixes #6806.

### CODE REVIEW

File: src/display/annotation_layer.js [hunk 1]
```diff
@@ -490,9 +490,16 @@ var PopupElement = (function PopupElementClosure() {
...
 
+      if (!this.container) {
+        // A separate container only exists for Popup annotations.
+        // When a Text annotation creates its own popup, it is placed inside
+        // the Text annotation container. Hiding the wrapper is enough then.
+        this.container = wrapper;
+      }
+      this.container.setAttribute('hidden', true);
+
       var popup = this.popup = document.createElement('div');
```
Comment (Snuffleupagus) [inline src/display/annotation_layer.js]: Nit: `this.popup` doesn't seems necessary any more.

**Comment by Snuffleupagus** [comment]
It appears that the `z-index` isn't being set on the correct element with this patch. Note how the popup gets placed *below* the other annotations in e.g. http://tug.ctan.org/tex-archive/macros/latex/contrib/pdfcomment/doc/pdfcomment.pdf#page=6.

File: src/display/annotation_layer.js (hunk 1 above)
Comment (timvandermeij) [inline src/display/annotation_layer.js]: Done in the new commit.

**Comment by timvandermeij** [comment]
The `z-index` placement was indeed incorrect, which has been fixed in the new commit. I tried creating reduced test cases without several tools, but all of them did not expose the issue that the `pdfcomments.pdf` file has (for an unknown reason). Then I tried including the `pdfcomments.pdf` file as a linked test, but the SVG rasterizer from the test suite does not appear to take `z-index` into account, causing the icons to overlap the popups in the reference image, but not when testing it manually. Hence I don't really think it's possible to add a test case for this at this point, unfortunately.

File: src/display/annotation_layer.js [hunk 2]
```diff
@@ -469,11 +471,12 @@ var PopupElement = (function PopupElementClosure() {
...
 
   function PopupElement(parameters) {
-    this.parentContainer = parameters.parentContainer;
-    this.parentTrigger = parameters.parentTrigger;
+    this.container = parameters.container;
+    this.trigger = parameters.trigger;
     this.color = parameters.color;
     this.title = parameters.title;
     this.contents = parameters.contents;
+    this.hideContainer = parameters.hideContainer;
```
Comment (Snuffleupagus) [inline src/display/annotation_layer.js]: Since the case of a Text annotation *without* an associated Popup annotation is special, it would seem a bit more logical if the the parameter was such that the caller *explicitly* had to set it to `true`, in order to get the special case (`this.hideElement = wrapper;` in the current code).

File: src/display/annotation_layer.js [hunk 3]
```diff
@@ -490,9 +493,18 @@ var PopupElement = (function PopupElementClosure() {
...
 
-      var popup = this.popup = document.createElement('div');
+      // For Popup annotations we hide the entire section, but for Text
+      // annotations we do not want the image to be hidden too, so there
+      // we just hide the wrapper.
+      if (this.hideContainer) {
+        this.hideElement = this.container;
+      } else {
+        this.hideElement = wrapper;
+      }
```
Comment (Snuffleupagus) [inline src/display/annotation_layer.js]: If you wanted to, this could probably be made a one-liner, e.g.
`this.hideElement = this.hideContainer ? this.container : wrapper;`

File: src/display/annotation_layer.js (hunk 2 above)
Comment (timvandermeij) [inline src/display/annotation_layer.js]: Done in the new commit.

File: src/display/annotation_layer.js (hunk 3 above)
Comment (timvandermeij) [inline src/display/annotation_layer.js]: Done in the new commit.

**Comment by Snuffleupagus** [comment]
Thanks for fixing this so quickly!
