### PR TITLE
Set correctly the change property for the event triggered when a choice list is changed

### LINKED ISSUE #17998: Javascript is not executed by pdf.js
Attach (recommended) or Link to PDF file here:
[verordnungsformular_1d_0.pdf](https://github.com/mozilla/pdf.js/files/15091394/verordnungsformular_1d_0.pdf)
https://www.lungenliga.ch/sites/default/files/documents/verordnungsformular_1d_0.pdf 

Configuration:
- Web browser and its version: Chrome Version 124.0.6367.79 (Official Build) (64-bit)
- Operating system and its version: Windows 10 Pro Version 22H2
- PDF.js version: https://mozilla.github.io/pdf.js/web/viewer.html
- Is a browser extension: ?

Steps to reproduce the problem:
1. Open https://mozilla.github.io/pdf.js/web/viewer.html
2. Open attached PDF file in the viewer
3. Scroll to the bottom
4. Select any item from the dropdown "Verordnung senden an"

What is the expected behavior? 
Text area next to dropdown is populated with respective text
image

What went wrong? 
Nothing happens:
image

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### PR DESCRIPTION
**Pull request by calixteman**
It fixes #17998.

### CODE REVIEW

File: test/integration/scripting_spec.mjs [hunk 1]
```diff
@@ -2425,4 +2425,49 @@ describe("Interaction", () => {
...
+            "window.PDFViewerApplication.scriptingReady === true"
+          );
+
+          for (const [value, expected] of [
+            ["b", "change=B,changeEx=b,value=A"],
+            ["c", "change=C,changeEx=c,value=B"],
+            ["a", "change=A,changeEx=a,value=C"],
+          ]) {
+            await page.select(getSelector("7R"), value);
+            await page.waitForFunction(
```
Comment (timvandermeij) [inline test/integration/scripting_spec.mjs:2460]: Similar to what we did in https://github.com/mozilla/pdf.js/pull/17974/files#diff-c0973b2c3b147db1eccd21c6b1af307f33a7e5d2658b4a0738a2386470b9c0caL2271, could we change this to the template string approach since it overall seems easier to read?

```js
await page.waitForFunction(`${getQuerySelector("10R")}.value !== ""`);
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, thanks.
