### PR TITLE
Attempt to throw `MissingPDFException` when applicable in `node_stream.js` (issue 9791)

### LINKED ISSUE #9791: Enable the missing PDF unit test for the API in NodeJS
The objective is to remove https://github.com/mozilla/pdf.js/blob/master/test/unit/api_spec.js#L166-L170 by fixing up `src/display/node_stream.js` to throw `MissingPDFException` when a PDF file is not found. Right now, this file is not handling errors in a consistent or even correct way compared with `src/display/network.js` and `src/display/fetch_stream.js`. Using the `createResponseStatusError` utility function might not make much sense in a Node.js environment. However, at the very least it seems that `MissingPDFException` or `UnknownErrorException` when we cannot tell that a PDF file is missing should be thrown manually. As is, the API (i.e., `getDocument`) is not returning the expected errors when loading fails in Node.js environments (as evident from this pending API unit test).

### PR DESCRIPTION
**Pull request by Snuffleupagus**
While I'm not very familiar with Node.js, this patch should (hopefully) cover the *multiple* ways in which files can be loaded in Node.js environments; while also taking into account e.g. the differences between the `XMLHttpRequest` and the `{http, https}.request` methods.
Furthermore, the `creates pdf doc from non-existent URL` API unit-test now passes in Node.js/Travis.

Fixes #9791.

### CODE REVIEW

File: src/display/node_stream.js [hunk 1]
```diff
@@ -359,17 +365,23 @@ class PDFNodeStreamRangeReader extends BaseRangeReader {
     }
     this._httpHeaders['Range'] = `bytes=${start}-${end - 1}`;
 
+    let handleResponse = (response) => {
+      if (response.statusCode === 404) {
+        const error = new MissingPDFException(`Missing PDF "${this._url}".`);
+        this._storedError = error;
```
Comment (timvandermeij) [inline src/display/node_stream.js]: I think we should `return` after this too to avoid setting the readable stream to a failed response, just like above.

Comment (Snuffleupagus) [reply src/display/node_stream.js]: Yes, that seems reasonable; fixed now.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Nice work!
