### PR TITLE
Apply transfer filters to any graphic commands

### LINKED ISSUE #16114: Transfer Maps must applied with all the graphic commands
Attach (recommended) or Link to PDF file here:
[spider.pdf](https://github.com/mozilla/pdf.js/files/10896497/spider.pdf)
The pdf is coming from: https://bugs.ghostscript.com/show_bug.cgi?id=696534

Configuration:
- Web browser and its version: Firefox nightly
- Operating system and its version: Windows 11

Steps to reproduce the problem:
1.  Open the pdf
2. The spider should be colored with a shade of greens.

What is the expected behavior? (add screenshot)
image

What went wrong? (add screenshot)
image

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
As far as I can tell, this won't actually work in environments without `OffscreenCanvas` support (i.e. older browsers and Node.js); do we consider that to be a problem?
My gut feeling is that the answer is *no*, especially considering just how rare transferMaps are in practice, but I wanted to ask nonetheless.

**Comment by Snuffleupagus** [comment]
> So we could just always have the filter factory and only keep a ref on the maps array when we're in non-offscreencanvas mode.

This situation seems to (mostly) apply to Node.js, and it's not clear to me if the `node-canvas` package first of all supports canvas-filters at all. Secondly the `FilterFactory` will definitely not work in Node.js, and it's again not clear to me if a Node-version of that code could actually be (easily) created.

> Wdyt of filing a bug for this case and I'll fix that later (or someone else could it, it could be a good first bug) ?

Given the points above, I'm somewhat doubtful if we can even make it work (for Node.js) and thus it's probably not a good beginner bug unfortunately.

**Comment by Snuffleupagus** [comment]
Also, do we need to include the `filter` when copying the canvas state?
https://github.com/mozilla/pdf.js/blob/e11371c75f91bf871cc7d33abbd324857fbfbb05/src/display/canvas.js#L828-L840

File: src/display/canvas.js [hunk 1]
```diff
@@ -3051,6 +3054,13 @@ class CanvasGraphics {
     const ctx = this.ctx;
 
     this.save();
+
+    // The filter, if any, will be applied in applyTransferMapsToBitmap.
+    // It must be applied to the image before rescaling else some artifacts
+    // could appear.
+    // The final restore will reset it to its value.
+    ctx.filter = "none";
```
Comment (Snuffleupagus) [inline src/display/canvas.js:3062]: You might want to simply ignore Node.js here, to prevent any possible issue?
```suggestion
    if (!isNodeJS) {
      // The filter, if any, will be applied in applyTransferMapsToBitmap.
      // It must be applied to the image before rescaling else some artifacts
      // could appear.
      // The final restore will reset it to its value.
      ctx.filter = "none";
    }
```

File: src/display/canvas.js [hunk 2]
```diff
@@ -863,6 +865,7 @@ function resetCtxToDefault(ctx, foregroundColor) {
     ctx.setLineDash([]);
     ctx.lineDashOffset = 0;
   }
+  ctx.filter = "none";
```
Comment (Snuffleupagus) [inline src/display/canvas.js:868]: Similar to below, should we ignore this in Node to prevent any possible issues?
```suggestion
 if (!isNodeJS) {
   ctx.filter = "none";
 }
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, with passing tests; thank you!

**Comment by calixteman** [comment]
I had frequently this error with Firefox and local dev but when I switched to `workerModule=true` it disappeared.
@Snuffleupagus, should we enable workerModule for tests either ?

**Comment by Snuffleupagus** [comment]
> I had frequently this error with Firefox and local dev but when I switched to `workerModule=true` it disappeared. @Snuffleupagus, should we enable workerModule for tests either ?

I don't understand how that option matters for the browser-tests, since the default viewer isn't actually being used there (the tests call the API directly).
