### PR TITLE
Correctly generate the NormalizeWithNFKC string in generic build

### LINKED ISSUE #20689: [Bug]: Search fails on some hyphenated words (under well-defined circumstances)
### Attach (recommended) or Link to PDF file

https://mozilla.github.io/pdf.js/web/viewer.html

### Web browser and its version

Firefox 147.0.3

### Operating system and its version

Ubuntu 24.04.4 LTS

### PDF.js version

v5.4.624

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. visit the online demo: https://mozilla.github.io/pdf.js/web/viewer.html
2. use PDF.js search (Ctrl-F) to search for "inference"

This correctly finds "inference" in the following sentence on page 1 of the TraceMonkey PDF:

> [...] While compile-time static type **infer-**
> **ence** might be able to gather type information to generate **opti-**
> **mized** machine code, traditional static analysis is very expensive
> and hence not well suited for the highly interactive environment of
> a web browser.

3. now search for "optimized"

This incorrectly skips "optimized" in the same sentence on page 1. (It does find "optimized" on page 2.)

4. now search for "opti- mized"

This (incorrectly) finds the word "opti-\nmized" in the example sentence on page 1

5. (optional) search for more words to confirm that words hyphenated directly after a character included in the regex character class `[undefi]` (like the 'i' in "opti- mized") aren't found

### What is the expected behavior?

When using the PDF.js search function, (almost) all hyphenated words can be found.

### What went wrong?

When using the PDF.js search function in the generic web viewer, words hyphenated directly after a character included in the regex class [undefi] are not found.

### Link to a viewer

_No response_

### Additional context

I think this issue was introduced by eee20cf https://github.com/mozilla/pdf.js/commit/eee20cf138172ef2872fa6e4f49f0041bb840109#diff-203c1b0630891e94c2134f55cca99b497523b679c4a7b049d43a1998fb504bc4R119.

The `PDFJSDev` checks cause generic builds to leave `NormalizeWithNFKC` undefined, which is later interpolated into a regular expression. (Hence the significance of the `[undefi]` / `[undefined]` characters.)

I'm not sure about the `PDFJSDev` checks. It may be intentional to leave `NormalizeWithNFKC` undefined, but then I think there should be a check before it's embedded in the normalize function in `pdf_find_controller.js` (see `const regexps`: p2).

### PR DESCRIPTION
**Pull request by calixteman**
It fixes #20689.

### CODE REVIEW

**Review by timvandermeij — APPROVED** [review]
Looks good to me, with passing integration tests. Thank you for fixing this!

**Review by Snuffleupagus — COMMENTED** [review]
That code is starting to look very complex now, would it make sense to just always generate the regular expression or is that too slow in Firefox?

File: web/pdf_find_utils.js [hunk 1]
```diff
@@ -120,11 +120,21 @@ function getNormalizeWithNFKC() {
...
     /* eslint-disable no-irregular-whitespace */
     NormalizeWithNFKC ||= `\xA0¨ª¯²-µ¸-º¼-¾Ĳ-ĳĿ-ŀŉſǄ-ǌǱ-ǳʰ-ʸ˘-˝ˠ-ˤʹͺ;΄-΅·ϐ-ϖϰ-ϲϴ-ϵϹևٵ-ٸक़-य़ড়-ঢ়য়ਲ਼ਸ਼ਖ਼-ਜ਼ਫ਼ଡ଼-ଢ଼ำຳໜ-ໝ༌གྷཌྷདྷབྷཛྷཀྵჼᴬ-ᴮᴰ-ᴺᴼ-ᵍᵏ-ᵪᵸᶛ-ᶿẚ-ẛάέήίόύώΆ᾽-῁ΈΉ῍-῏ΐΊ῝-῟ΰΎ῭-`ΌΏ´-῾ - ‑‗․-… ″-‴‶-‷‼‾⁇-⁉⁗ ⁰-ⁱ⁴-₎ₐ-ₜ₨℀-℃℅-ℇ℉-ℓℕ-№ℙ-ℝ℠-™ℤΩℨK-ℭℯ-ℱℳ-ℹ℻-⅀ⅅ-ⅉ⅐-ⅿ↉∬-∭∯-∰〈-〉①-⓪⨌⩴-⩶⫝̸ⱼ-ⱽⵯ⺟⻳⼀-⿕　〶〸-〺゛-゜ゟヿㄱ-ㆎ㆒-㆟㈀-㈞㈠-㉇㉐-㉾㊀-㏿ꚜ-ꚝꝰ꟱-ꟴꟸ-ꟹꭜ-ꭟꭩ豈-嗀塚晴凞-羽蘒諸逸-都飯-舘並-龎ﬀ-ﬆﬓ-ﬗיִײַ-זּטּ-לּמּנּ-סּףּ-פּצּ-ﮱﯓ-ﴽﵐ-ﶏﶒ-ﷇﷰ-﷼︐-︙︰-﹄﹇-﹒﹔-﹦﹨-﹫ﹰ-ﹲﹴﹶ-ﻼ！-ﾾￂ-ￇￊ-ￏￒ-ￗￚ-ￜ￠-￦`;
   }
 
-  if (typeof PDFJSDev === "undefined" || PDFJSDev.test("TESTING")) {
+  if (
+    !NormalizeWithNFKC ||
+    typeof PDFJSDev === "undefined" ||
+    PDFJSDev.test("TESTING")
+  ) {
```
Comment (Snuffleupagus) [inline web/pdf_find_utils.js:137]: This condition will cause all of the code below to be included in the MOZCENTRAL build, which probably isn't what you want?

**Comment by calixteman** [comment]
> That code is starting to look very complex now, would it make sense to just always generate the regular expression or is that too slow in Firefox?

I can't disagree about the complexity...
On my mac pro with a M2 processor, it takes around 3,4ms which is not really a bottleneck especially because it's called one time.
It's just a pity to waste few ms just because Chrome hasn't updated ICU or whatever they use.
So I'm inclined to think that we should keep this code but if you've any ideas to simplify, they're welcome.

**Review by Snuffleupagus — APPROVED** [review]
