### PR TITLE
Refactor the copy/paste logic in the integration tests and fix a race condition involving the `waitForEvent` integration test helper function

### LINKED ISSUE #17931: Fix integration test "FreeText Editor Paste some html must check that pasting html just keep the text"
This integration test is quite new, but has failed a couple of times on (as far as I have seen only) the Windows bot now with the following traceback:

```
1) FreeText Editor Paste some html must check that pasting html just keep the text
  Message:
[31m    In firefox:
        Expected 'FooFooBar
        OofHello PDF.js World !!' to equal 'FooBar
        OofHello PDF.js World !!'.[0m
  Stack:
        at <Jasmine>
        at file:///C:/pdfjs/botio-files-pdfjs/private/d21e23ccf06497a/test/integration/freetext_editor_spec.mjs:3667:57
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Promise.all (index 0)
        at async UserContext.<anonymous> (file:///C:/pdfjs/botio-files-pdfjs/private/d21e23ccf06497a/test/integration/freetext_editor_spec.mjs:3567:7)
```

The most recent logs can be found here: http://54.193.163.58:8877/d21e23ccf06497a/output.txt

It was introduced in commit https://github.com/mozilla/pdf.js/commit/2dbd7acc41f07ad84989dfc7a7f087a1cbb27f93 and it fails at https://github.com/mozilla/pdf.js/blob/master/test/integration/freetext_editor_spec.mjs#L3666-L3667.

@calixteman Do you have an idea why this could be failing intermittently?

### PR DESCRIPTION
**Pull request by timvandermeij**
The commit messages contain more details about the individual changes.

Note that this patch should fix the `waitForEvent` timeout logs (but not the `waitForEvent` validation logs yet) and reduce the likelyhood of the `FreeText Editor Paste some html must check that pasting html just keep the text` integration test, and other related integration tests, failing (but not completely fix it yet). I'm fairly sure I now know how to fix it completely, but that'll be done in a follow-up which builds on top of this patch and the previous patches.

Fixes a part of #17931.

### CODE REVIEW

File: test/integration/copy_paste_spec.mjs [hunk 1]
```diff
@@ -15,17 +15,18 @@
...
+  copy,
   kbSelectAll,
   loadAndWait,
   mockClipboard,
   waitForEvent,
 } from "./test_utils.mjs";
 
 const selectAll = async page => {
-  const promise = waitForEvent(page, "selectionchange");
+  const generator = waitForEvent(page, "selectionchange");
```
Comment (calixteman) [inline test/integration/copy_paste_spec.mjs:26]: Can't we just add a third param to `waitForEvent` which will be here `async () => await kbSelectAll(page)` and then do the equivalent of the two `generator.next` in the `waitForEvent` ?
Or maybe keep `waitForEvent` like this and add another function to call the function triggering the event wrapped in generator.next calls,... something like that...

Comment (timvandermeij) [reply test/integration/copy_paste_spec.mjs:26]: Good idea! I was also hoping to keep most of that logic inside `waitForEvent`, but couldn't think of a better way to handle the control flow until you mentioned this, so I'll definitely give that a try; thanks!

Comment (timvandermeij) [reply test/integration/copy_paste_spec.mjs]: Fixed in the new commit. This is indeed much nicer/simpler!

**Review by calixteman — APPROVED** [review]
LGTM. Thank you.
