### PR TITLE
[api-minor] Use a Path2D when doing a path operation in the canvas (bug 1946953)

### LINKED ISSUE #10908: Transform improperly applied to path
Attach (recommended) or Link to PDF file here:
[strokepath-visible-simple-scale-fixed.pdf](https://github.com/mozilla/pdf.js/files/3293372/strokepath-visible-simple-scale-fixed.pdf)

Configuration:
- Web browser and its version: Firefox Nightly

Steps to reproduce the problem:
1. Load the PDF

What is the expected behavior?
Last coordinate of the path should not be scaled by 10. Chrome, Ghostscript, Poppler, and Acroread all correctly draw the path. pdf.js and Preview seem to get it wrong.

What went wrong?
Last coordinate of the path should not be scaled by 10

### LINKED ISSUE #14520: PDF render problem on PDF.js
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Mozilla 96.0.3
- Operating system and its version: Windows 10
- PDF.js version: Chrome/Firefox Extension
- Is a browser extension: Yes

Steps to reproduce the problem:
1.  I will give you a file who have a visual problem beetween pdf.js on firefox (not on chrome/opera). With PDF.js i have this render : 
 
image

What is the expected behavior? Normally i need to have this render : 

image
 

What went wrong? 

See first screenshot

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Firefo/Chrome Extension

File : 

[3b750e51-2f97-4a51-b3f1-2589135d9d09_1643386353 (1).pdf](https://github.com/mozilla/pdf.js/files/7972015/3b750e51-2f97-4a51-b3f1-2589135d9d09_1643386353.1.pdf)

### LINKED ISSUE #19498: [Bug]: displaying a PDF that has undergone redactions
### Attach (recommended) or Link to PDF file

[file-mark-updated.pdf](https://github.com/user-attachments/files/18814015/file-mark-updated.pdf)

### Web browser and its version

chrome 126

### Operating system and its version

angular 17

### PDF.js version

4.8

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

Display The attach file

[file-mark-updated.pdf](https://github.com/user-attachments/files/18814049/file-mark-updated.pdf)

### What is the expected behavior?

Display the file in chrome or Edge ,It is displayed correctly

### What went wrong?

the file is not displayed correctly

### Link to a viewer

_No response_

### Additional context

Hi everyone,

I’m encountering an issue with displaying a PDF that has undergone redactions. When I apply redactions to the document and save it, everything seems fine when opened directly in a browser (e.g., Chrome), but when I load the same PDF using ngx-extended-pdf-viewer, the document is not displayed correctly.

The ngx-extended-pdf-viewer used with pdf.js.

Has anyone experienced similar issues with redactions in PDFs, and if so, what steps should I take to resolve this? Could this be related to how pdf.js handles redacted content, or is it more of a problem with how the file was saved after the redactions?

Any insights or suggestions would be greatly appreciated!

I uploaded example file.

Thanks in advance!

### PR DESCRIPTION
**Pull request by calixteman**
With this patch, all the paths components are collected in the worker until a path operation is met (i.e., stroke, fill, ...).
Then in the canvas a Path2D is created and will replace the path data transfered from the worker, this way when rescaling, the Path2D can be reused. 
In term of performances, using Path2D is very slightly improving speed when scaling the canvas. Since some maps can contain some consecutive operations like save, transform, path op, restore, this patch adds an optimizer for such a pattern.

### CODE REVIEW

File: src/core/evaluator.js [hunk 1]
```diff
@@ -4935,6 +4992,16 @@ class EvalState {
...
+
+    // Path stuff.
+    this.currentPointX = this.currentPointY = 0;
+    this.pathMinMax = new Float32Array([
+      Infinity,
+      Infinity,
+      -Infinity,
+      -Infinity,
+    ]);
+    this.pathBuffer = [];
```
Comment (Snuffleupagus) [inline src/core/evaluator.js:5004]: *Possibly a stupid question, but:*
Given that objects are passed by reference in JavaScript, do we perhaps want to *copy* these structures when cloning the `EvalState` to avoid affecting a previous save-restore block?

See the `TextState.prototype.clone`-method, and how it handles "objects", for comparison:
https://github.com/mozilla/pdf.js/blob/cd4a30341f048d722e06d078a94911cc19bfc3a6/src/core/evaluator.js#L4921-L4927

**Comment by Snuffleupagus** [comment]
I'd suggest splitting this PR into *two separate* ones, the first containing the "basic" implementation and the second containing only the new `addState`-optimization.
If we do this it's possible to review, but more importantly test and makeref just the "basic" changes first. *Immediately after* that lands, the next PR with the optimization can then be reviewed and tested separately.

That way we'd reduce the risk of a situation where a bug in the "basic" implementation is (currently unknowingly) worked-around in the `addState`-optimization.

**Review by Snuffleupagus — COMMENTED** [review]
Obviously not something that needs to be fixed in this patch, but I noticed (based on previous test runs) that an earlier version also improved rendering of the `issue17779` test-case; perhaps something for a follow-up?

**Comment by calixteman** [comment]
> Obviously not something that needs to be fixed in this patch, but I noticed (based on previous test runs) that an earlier version also improved rendering of the `issue17779` test-case; perhaps something for a follow-up?

It seems that it's because I was merging consecutive fill or stroke, i.e. `path1... f path2... f` was merged into `path1+path2 f`.
But it's something I removed at some point because it's wrong in general, for example it can depend on the composition op and if the different shapes overlap or not.
Anyway, I'll have a look on that, but for sure it'll be in a follow-up.

File: src/display/canvas.js [hunk 2]
```diff
@@ -1612,253 +1589,170 @@ class CanvasGraphics {
...
+              path[i++],
+              path[i++],
+              path[i++]
+            );
+            break;
+          case DrawOPS.closePath:
+            path2d.closePath();
+            break;
+          default:
+            warn(`Unrecognized drawing path operator: ${path[i]}`);
```
Comment (Snuffleupagus) [inline src/display/canvas.js:1625]: Is this warning printing the intended element, given that `i` was incremented in the `switch` statement?
```suggestion
            warn(`Unrecognized drawing path operator: ${path[i - 1]}`);
```

File: src/display/canvas.js [hunk 3]
```diff
@@ -1612,253 +1589,170 @@ class CanvasGraphics {
...
+            break;
+        }
+      }
+      path = path2d;
     }
-
-    current.setCurrentPoint(x, y);
```
Comment (Snuffleupagus) [inline src/display/canvas.js:1757]: It appears that this method is completely unused now, so please remove it from the `CanvasExtraState` class as well.

File: src/display/canvas.js [hunk 4]
```diff
@@ -3267,15 +3161,16 @@ class CanvasGraphics {
...
-    const { ctx } = this;
-    const { lineWidth } = this.current;
+  rescaleAndStroke(path, saveRestore) {
+    const {
+      ctx,
+      current: { lineWidth },
+    } = this;
     const [scaleX, scaleY] = this.getScaleForStroking();
 
-    ctx.lineWidth = lineWidth || 1;
```
Comment (Snuffleupagus) [inline src/display/canvas.js:3275]: Is it intended to no longer set `ctx.lineWidth` unconditionally here?

File: src/display/canvas.js [hunk 5]
```diff
@@ -527,22 +520,6 @@ class CanvasExtraState {
     this.maxY = Math.max(this.maxY, p1[1], p2[1], p3[1], p4[1]);
   }
 
-  updateScalingPathMinMax(transform, minMax) {
-    Util.scaleMinMax(transform, minMax);
```
Comment (Snuffleupagus) [inline src/display/canvas.js:531]: Also, is that `Util` method unused now?
If so, please remove that one as well.

File: src/display/canvas.js (hunk 4 above)
Comment (calixteman) [reply src/display/canvas.js:3275]: Good catch, thank you.

File: src/display/canvas.js [hunk 6]
```diff
@@ -3285,6 +3179,10 @@ class CanvasGraphics {
     }
 
     ctx.scale(scaleX, scaleY);
+    const newPath = new Path2D();
+    SCALE_MATRIX[0] = 1 / scaleX;
+    SCALE_MATRIX[3] = 1 / scaleY;
```
Comment (Snuffleupagus) [inline src/display/canvas.js:3184]: Could this explain the new test failures, since I don't believe that you can change a `DOMMatrix`-instance that way?

Maybe this would work?
```suggestion
    SCALE_MATRIX.a = 1 / scaleX;
    SCALE_MATRIX.d = 1 / scaleY;
```

**Review by Snuffleupagus — APPROVED** [review]
While there's movement in many existing ref-tests, that's however not unexpected for a patch like this *and* the changes appear to be invisible to the naked eye.

r=me, thank you.
