### PR TITLE
[api-minor] Respect the `drawingDelay` also when CSS-only zooming is used (issue 18022)

### LINKED ISSUE #18022: Text layer constantly re-rendered when zooming large PDF (or large zoom)
**Attach (recommended) or Link to PDF file here:** [A1.pdf](https://github.com/mozilla/pdf.js/files/15151235/A1.pdf) (it also happens with the Trace-based JIT ... PDF, but you have to be close to the max zoom to see it)

**Configuration:**
- Web browser and its version: Firefox 124, Firefox Android 125, Chrome Android 123
- Operating system and its version:
- PDF.js version: The one in that firefox version, and the current `main`
- Is a browser extension: no

**Steps to reproduce the problem:**
1. Add a logpoint in https://github.com/mozilla/pdf.js/blob/627fe2d82604ac0d2d6918b74cec13dff57fc86a/web/pdf_page_view.js#L710
2. Zoom enough so that the size is bigger than `this.maxCanvasPixels`, so zooming becomes css-only

**What is the expected behavior? (add screenshot)**

It should respect `defaultZoomDelay`, and do not re-draw the text layer (and not emit `pagerendered`) until when zooming is done.

When zooming at small enough scales that the size is less than `this.maxCanvasPixels` (i.e. less than 100% in that A1.pdf), the event handler that handles zoom does very little work:

_Stack Chart (over ~300ms)_
image

_Flame Graph (over ~300ms)_
image

**What went wrong? (add screenshot)**

When zooming at big sizes, a lot of the time is spent re-rendering the text layer.

_Stack Chart (over ~200ms)_
image

_Flame Graph (over ~200ms)_
image

As you can see from the two stack charts, most of the time in the first one is spend doing _nothing_ while in the second one it's doing _something_. This isn't really noticeable on my desktop, but it introduces some lagging on my phone (both in Firefox and Chrome, but Chrome is doing noticeably worse).

**Other info:**

The relevant code is https://github.com/mozilla/pdf.js/blob/627fe2d82604ac0d2d6918b74cec13dff57fc86a/web/pdf_page_view.js#L654-L717.

Looking at https://github.com/mozilla/pdf.js/pull/16507, it seems like the "fast" behavior is indeed the expected behavior: page re-rendering shouldn't happen until the "final" rendering. However, a combination of https://github.com/mozilla/pdf.js/commit/7bca3c81a9440ae50d7b37d4f88630b742e8830a and https://github.com/mozilla/pdf.js/commit/0ee2a352ecd0ab587123918f6d5ea29b5feccf47 changed how PDF.js behaves in this case:

- 7bca3c81a9440ae50d7b37d4f88630b742e8830a disabled the rendering delay when PDF.js is configured to use css-only zoom, because there won't be a "next render"
- 0ee2a352ecd0ab587123918f6d5ea29b5feccf47 unified the "css-only zoom because configured as such" and "css-only zoom because the canvas would be too big" cases

I think there are two possible solutions, but I saw that there were many regressions related to this rendering delay so I'm not sure about what's best:
1. `onlyCssZoom` should only affect whether or not we cancel the ongoing rendering, and not whether or not we delay the text layer and the "pagerendered" event
2. we distinguish the "`onlyCssZoom` because of `this.maxCanvasPixels === 0`" and "`onlyCssZoom` because the canvas would be too big" cases

### PR DESCRIPTION
**Pull request by Snuffleupagus**
If a user manually calls `PDFPageView.prototype.update()` with a `drawingDelay`-option then it'll always be necessary to re-call the method *without* a delay afterwards, regardless of the `maxCanvasPixels`-value (e.g. even when CSS-only zooming is used).

### CODE REVIEW

File: web/pdf_page_view.js [hunk 1]
```diff
@@ -667,12 +667,12 @@ class PDFPageView {
             this.maxCanvasPixels;
         }
       }
-      const postponeDrawing =
-        !onlyCssZoom && drawingDelay >= 0 && drawingDelay < 1000;
+      const postponeDrawing = drawingDelay >= 0 && drawingDelay < 1000;
```
Comment (timvandermeij) [inline web/pdf_page_view.js:670]: This is not directly related to this patch, but this code somewhat confuses me. AFAICT `drawingDelay` originates from the `defaultZoomDelay` viewer option, see: https://github.com/mozilla/pdf.js/blob/44b7cc517de7c2cb428f67a5db232a6c56675999/web/app_options.js#L119-L123
However, that doesn't specify any maximum value yet here we seem to only respect the value if it's below 1000. Moreover, if the value is 0 we also postpone drawing because of `>=` even though I'd think in that case we don't have to postpone at all.

Do you happen to know what the rationale for the current code is? As said it doesn't have to be changed in this patch, but I figured I should ask because it felt a bit odd to me.

Comment (Snuffleupagus) [reply web/pdf_page_view.js:670]: This is implemented to delay the actual re-rendering during quick zooming, e.g. with the mouse-wheel or touch gestures, since that improves performance.
The reason that we cap the value is to prevent the user from essentially breaking things by setting the pref to a ridiculously large value.
As far as the zero-case goes, since setTimeout is being used even `0` is actually a delay (albeit perhaps not that useful); note https://github.com/mozilla/pdf.js/blob/7e5e06b88639fbe4c2034809a56922a3f56fca30/web/pdf_viewer.js#L1248-L1253

Hopefully this helps clear up some of confusion, if not please ask again :-)

**Comment by nicolo-ribaudo** [comment]
> I assume it's not really easy/possible to add a test for this particular issue

I believe it is possible to test this by listening to the `pagerendered` event while zooming, I can try providing a test in the next few days.

**Comment by Snuffleupagus** [comment]
> The change looks good to me aside from the comment above, and two questions:

 - I probably won't have time to create tests for this, unfortunately.
 
 - Given that this is part of `viewer components`, note https://github.com/mozilla/pdf.js/blob/master/web/pdf_viewer.component.js which "power" [these examples](https://github.com/mozilla/pdf.js/tree/master/examples/components), I figured that `[api-minor]` might not hurt. Although you're obviously correct that this isn't the primary library API.

**Comment by timvandermeij** [comment]
> I believe it is possible to test this by listening to the pagerendered event while zooming, I can try providing a test in the next few days.

If that's possible that'd be great; thanks! It's not a must-have for landing this PR, but if it's possible to have some (basic) testing for either this issue or CSS zooming in general that would increase confidence in the code.

> [...] I figured that [api-minor] might not hurt [...]

I agree. Let's keep this as-is then.

File: web/pdf_page_view.js (hunk 1 above)
Comment (timvandermeij) [reply web/pdf_page_view.js:670]: Yes, that does clear it up; thanks! (I was wondering if we should document the lower and upper limits at e.g. the preference definition, but I'm not sure if it's really needed because zero or very large values should hopefully be edge cases anyway.)

**Review by timvandermeij — APPROVED** [review]
The change looks good from my point of view, now that the questions above have been addressed. I'd prefer we wait a few days with merging this until we know if we can include a test for this, but otherwise I'm also not opposed to doing that in a separate PR if that turns out to be more complicated than anticipated.

**Comment by nicolo-ribaudo** [comment]
@timvandermeij Unfortunately I don't think I'll be able to submit a test until next week.

**Comment by timvandermeij** [comment]
> Unfortunately I don't think I'll be able to submit a test until next week.

No worries; we're already happy that you're willing to help out with this, so no rush. Let's land this PR so the issue is resolved, and I'll open a follow-up issue for introducing tests for this functionality (since that scope is a bit broader than just this particular patch).

@Snuffleupagus Thank you for the patch!
