### PR TITLE
[Editor] Try to make the position of an edited FreeText the more accurated as possible

### LINKED ISSUE #16633: Existing Text Annotations change position while editing
Attach (recommended) or Link to PDF file here: [sample.pdf](https://github.com/mozilla/pdf.js/files/11933959/sample.pdf)

Configuration:
- Web browser and its version: Chrome 114 (Firefox 113 too)
- Operating system and its version: Windows
- PDF.js version: 3.8.162
- Is a browser extension: no

Steps to reproduce the problem:
1. open viewer https://mozilla.github.io/pdf.js/web/viewer.html
2. Open attached PDF
3. Press Button to edit text annotations
4. Annotation are on a slightly different position:

Screenshot 1
image

Screenshot 2
image

What is the expected behavior? (add screenshot)
Same as Screenshot 1, position has to be the same when editing Text annotations.

What went wrong? (add screenshot)

It looks like Screenshot 2, the annotation is moved a little bit in the lower left corner.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### PR DESCRIPTION
**Pull request by calixteman**
- Take into account the page translation,
- Take into account the correct translation for the editor border,
- Take into account the position of the first glyph in the annotation,
- Take into account the rotation of the editor.

Close #16633.

### CODE REVIEW

File: src/display/editor/freetext.js [hunk 1]
```diff
@@ -492,8 +492,54 @@ class FreeTextEditor extends AnnotationEditor {
...
       const [parentWidth, parentHeight] = this.parentDimensions;
       if (this.annotationElementId) {
-        const [tx] = this.getInitialTranslation();
-        this.setAt(baseX * parentWidth, baseY * parentHeight, tx, tx);
+        // This stuff is hard to test: if something is changed here, please
+        // test with the following PDF file:
+        //  - freetexts.pdf
+        //  - rotated_freetexts.pdf
+        // Only small variations between the original annotation and its editor
+        // are allowed.
```
Comment (Snuffleupagus) [inline src/display/editor/freetext.js:500]: Is there no way that we could have e.g. a rudimentary integration-test for this?
E.g. something along these lines:
 - Load the PDF document from issue #16633
 - Get the coordinates of the relevant FreeText-annotation.
 - Enable editing.
 - Get the coordinates of the "new" Editor-element.
 - Compare the two sets of coordinates, and ensure that their difference is "small".

Comment (calixteman) [reply src/display/editor/freetext.js:500]: I already tried...
For the foxit annotation in freetexts.pdf:
 - without the patch (temp0 is the annotation and temp1 the editor):
   image
 - with the patch:
   image

This patch takes into account the padding added by the editor when generating the appearance so I don't really see how I can test that... The only solution I can imagine is to make a screenshot and then compare it with a reference but we've nothing to do that.

Comment (calixteman) [reply src/display/editor/freetext.js:500]: I really don't like having to test manually something.... I'm really lazy but I way prefer spending one hour in writing a test instead of having to remember that I need to test something manually and then test the stuff in trying to remember the different scenarios.
So I think we should screenshot the page, put it somewhere and then compare it with a ref we've.
Do you think it's feasible ? Can you imagine something easier ?

Comment (Snuffleupagus) [reply src/display/editor/freetext.js:500]: Taking the document from the issue, i.e. https://github.com/mozilla/pdf.js/files/11933959/sample.pdf, and modifying it as follows might help with writing an integration-test?
 - Changing the /MediaBox entries to e.g. `[-75 -75 600 850]`.
 - Removing *all* /BleedBox, /CropBox, and /TrimBox entries.

With these changes the differences between the annotationLayer and the annotationEditorLayer should be big enough (on `master`) that we could just compare the coordinates and ensure that they at least overlap.
Maybe I'm overlooking or oversimplifying a bunch of things, but would this be a possible solution?

Comment (calixteman) [reply src/display/editor/freetext.js:500]: With the patch I get `{ x: 377.433349609375, y: 335.3666687011719, ...` for the annotation and `{ x: 372.1000061035156, y: 330.0333251953125,...} for the editor.
So we could that we've a tolerance of 5px but if we've a diff of 4px in the opposite direction then the test will be ok and rendering will be wrong.
And I'm wondering if these differences could be different with another screen resolution.
That said, for this specific case, the difference corresponds to the value returned by:
https://github.com/mozilla/pdf.js/blob/master/src/display/editor/freetext.js#L217

**Comment by Snuffleupagus** [comment]
It seems that the new integration-tests failed on Windows, please look into that (hopefully it's not a new intermittent failure).

File: src/display/editor/freetext.js [hunk 2]
```diff
@@ -502,8 +502,54 @@ class FreeTextEditor extends AnnotationEditor {
...
+
+        // position is the position of the first glyph in the annotation
+        // and it's relative to its container.
+        const position = this.#initialData.position;
```
Comment (Snuffleupagus) [inline src/display/editor/freetext.js:514]: Nit:
```suggestion
        const { position } = this.#initialData;
```

File: src/display/editor/freetext.js [hunk 3]
```diff
@@ -502,8 +502,54 @@ class FreeTextEditor extends AnnotationEditor {
...
+          case 0:
+            posX = baseX + (position[0] - pageX) / pageWidth;
+            posY = baseY + this.height - (position[1] - pageY) / pageHeight;
+            break;
+          case 90: {
+            posX = baseX + (position[0] - pageX) / pageWidth;
+            posY = baseY - (position[1] - pageY) / pageHeight;
+            const tmp = tx;
+            tx = ty;
+            ty = -tmp;
```
Comment (Snuffleupagus) [inline src/display/editor/freetext.js:530]: Nit: You might be able to do this without the temporary variable?
```suggestion
            [tx, ty] = [ty, -tx];
```

File: src/display/editor/freetext.js [hunk 4]
```diff
@@ -502,8 +502,54 @@ class FreeTextEditor extends AnnotationEditor {
...
+          case 270: {
+            posX =
+              baseX +
+              (position[0] - pageX - this.height * pageHeight) / pageWidth;
+            posY =
+              baseY +
+              (position[1] - pageY - this.width * pageWidth) / pageHeight;
+            const tmp = tx;
+            tx = -ty;
+            ty = tmp;
```
Comment (Snuffleupagus) [inline src/display/editor/freetext.js:548]: Nit: (as above)
```suggestion
            [tx, ty] = [-ty, tx];
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, with the integration-tests passing on the Windows-bot; thank you!
