### PR TITLE
When saving some annotations with the same name, set the value in the parent

### LINKED ISSUE #18630: [Bug]: Form fields with the same name are not updated when the pdf is saved
### Attach (recommended) or Link to PDF file

[same_annotation_name.pdf](https://github.com/user-attachments/files/16673285/same_annotation_name.pdf)

### Web browser and its version

Chrome 127.0.6533.120

### Operating system and its version

Windows 11 Pro 23H2

### PDF.js version

v4.5.136

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open attached file "same_annotation_name.pdf" in the demo viewer.
2. Modify one of both form fields, since they have same name both gonna change.
3. Save the document.
4. Open the document with _Chrome_.
5. The fields are gonna look changed, but when you click on one of them you'll see that the value wasn't changed.

### What is the expected behavior?

The text should look changed in both fields, as it seemed before saving the document in the demo viewer. For example, if you want to do a document where you have some fields repeated, like the name of a person, you want to make them have the same value. This behaviour is useful when you put more than one field with the same name, in this case I am using "Texto1" in both of them.

### What went wrong?

The value hasn't changed, it looks like it did but when you try to modify it again, the old value returns and the modified one is lost.

**Before saving**
image

**After saving**
image
image
image

### Link to a viewer

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by calixteman**
It fixes #18630.

### CODE REVIEW

File: src/core/core_utils.js [hunk 1]
```diff
@@ -146,6 +146,36 @@ function getInheritableProperty({
...
+    if (dict.has("T")) {
+      break;
+    }
+    ref = dict.getRaw("Parent");
+    if (!(ref instanceof Ref)) {
+      return result;
+    }
+    dict = xref.fetch(ref);
+  }
+  if (dict !== firstDict) {
```
Comment (Snuffleupagus) [inline src/core/core_utils.js:172]: In a corrupt PDF, isn't it possible for the `dict`-fetching here to be *any* value (and not necessarily a dictionary)?

Let's assume that it's e.g. the number `5`, and in that case we'd break out of the loop just fine. However the `dict !== firstDict` check would be true and we'd thus incorrectly update the `result`, hence we'd run into trouble when trying to `clone` a non-dictionary in the annotation-code.

Unless I'm missing something, I do believe that we *also* need to check the type here as well.
```suggestion
    dict = xref.fetch(ref);
  }
  if (dict instanceof Dict && dict !== firstDict) {
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, with the comment implemented; thank you.
