### PR TITLE
Rescale the image data when they're really too large

### LINKED ISSUE #17190: Unable to decode image: InvalidStateError
**Attach (recommended) or Link to PDF file here:**
[org_AVA89V01U0$ (Black).pdf](https://github.com/mozilla/pdf.js/files/13180762/org_AVA89V01U0.Black.pdf)

**Configuration:**
- Web browser and its version: Chrome Version 118.0.5993.89 (Official Build) (64-bit)
- Firefox Version 119.0 (64-bit)
- Edge Version 118.0.2088.69 (Official build) (64-bit)
- Operating system and its version: Windows 11 Enterprise Version 10.0.22621 Build 22621
- PDF.js version: 4.0.132 [34781121c] (test viewer)
- Is a browser extension: No

**Steps to reproduce the problem:**
1. Open the file in Acrobat. Main area is blacked out but you can see the edges of a CAD drawing along the borders that includes various characters.
2. Open the file in PDF.js. Only the black rectangle in the center and the blue box in the upper right corner are rendered.

**What is the expected behavior? (add screenshot)**
This is the upper left corner at 200% zoom in Acrobat:
image

**What went wrong? (add screenshot)**
The console on Chrome:
PDF a8c52134c310cca513061a5a2ce6ca91 [1.3 - / -] (PDF.js: 4.0.132 [34781121c])
util.js:367 Warning: Unable to decode image "img_p0_1": "InvalidStateError: The source image could not be decoded.".
util.js:367 Warning: Dependent image isn't ready yet

The console on Firefox:
PDF a8c52134c310cca513061a5a2ce6ca91 [1.3 - / -] (PDF.js: 4.0.132 [34781121c]) [app.js:1561:12](webpack://pdf.js/web/app.js)
Warning: Unable to decode image "img_p0_1": "InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable". [pdf.worker.mjs:339:13](https://mozilla.github.io/pdf.js/build/pdf.worker.mjs)
Warning: Dependent image isn't ready yet 3 [util.js:367:12](webpack://pdf.js/src/shared/util.js)

The console on Edge:
PDF a8c52134c310cca513061a5a2ce6ca91 [1.3 - / -] (PDF.js: 4.0.132 [34781121c])
util.js:367 Warning: Unable to decode image "img_p0_1": "InvalidStateError: The source image could not be decoded.".
2util.js:367 Warning: Dependent image isn't ready yet
util.js:367 Warning: Dependent image isn't ready yet

This is the upper left corner at 200% zoom in Chrome:
image

**Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):**
https://mozilla.github.io/pdf.js/web/viewer.html

### PR DESCRIPTION
**Pull request by calixteman**
It fixes #17190.

### CODE REVIEW

File: src/core/image_resizer.js [hunk 1]
```diff
@@ -268,6 +279,90 @@ class ImageResizer {
     return imgData;
   }
 
+  _rescaleImageData() {
```
Comment (Snuffleupagus) [inline src/core/image_resizer.js:282]: Nit: Can this be private?
```suggestion
  #rescaleImageData() {
```

File: src/core/image_resizer.js [hunk 2]
```diff
@@ -268,6 +279,90 @@ class ImageResizer {
...
+    const { _imgData: imgData } = this;
+    const { data, width, height, kind } = imgData;
+    // K is such as width * height * 4 / 2 ** K <= 2 ** 31 - 1
+    const K = Math.ceil(Math.log2((width * height * 4) / (2 ** 31 - 1)));
```
Comment (Snuffleupagus) [inline src/core/image_resizer.js:286]: Following the suggestion above.
```suggestion
    // K is such as width * height * 4 / 2 ** K <= 2 ** 31 - 1
    const K = Math.ceil(Math.log2((width * height * 4) / MAX_INT_32));
```

Comment (Snuffleupagus) [inline src/core/image_resizer.js:286]: Also, how about introducing a variable to not have to re-compute `width * height * 4` a bunch of times in this method?

**Review by Snuffleupagus — APPROVED** [review]
r=me, with a few suggestions to reduce constant duplication; thank you.
