### PR TITLE
[api-minor] Move to Fluent for the localization (bug 1858715)

### LINKED ISSUE #10075: Replace `webl10n` with Fluent
The `webl10n` library is unmaintained and Fluent is actively maintained, so it may be beneficial to switch to that system. It must be able to somehow read the current locale files though.

### PR DESCRIPTION
**Pull request by calixteman**
- For the generic viewer we use @fluent/dom and @fluent/bundle
- For the builtin pdf viewer in Firefox, we set a localization url and then we rely on document.l10n which is a DOMLocalization object.

### CODE REVIEW

**Review by flodolo — CHANGES_REQUESTED** [review]
The FTL file should have a license header ([example](https://searchfox.org/mozilla-central/source/browser/branding/aurora/locales/en-US/brand.ftl)). Also, leave an empty line at the end.

In general, I have a few questions and notes before diving into details.

### String structure

```
previous =
    .title = Previous Page
previous-label = Previous
```

Can this be a single string? Example:

```
pdfviewer-previous-button = Previous
    .title = Previous Page
```

### String IDs

The other thing is about namespaced and more semantic IDs:
* ID should hint at the role, e.g. `previous-button`. That prevents reuse in different contexts.
* ID should be namespaced, e.g. `pdfviewer-previous-button`.

### Plurals

```
ind-match-count =
    { $total ->
        [1] { $current } of { $total } match
       *[other] { $current } of { $total } matches
    }
```

Use `[one]`, not `[1]`. The latter is used only in specific cases, when it's a real plural but more singular/many.

### Comments

Fluent support [multiple type of comments](https://projectfluent.org/fluent/guide/comments.html): if a comment applies to more strings, you should use a group-level comments, and reset it after the strings. That also allows for simplification, e.g. at the end of the file.

```
# .alt: This is used as a tooltip.
```

No need to call out the attribute, `Used a tooltip is enough`.

**Comment by calixteman** [comment]
> * ID should be namespaced, e.g. `pdfviewer-previous-button`.

Why ? If all the strings have the same prefix then the prefix is useless or am I missing something ?

**Comment by flodolo** [comment]
> Why ? If all the strings have the same prefix then the prefix is useless or am I missing something ?

Strings share the same scope in the Fluent bundle
https://firefox-source-docs.mozilla.org/l10n/fluent/review.html#message-identifiers

Not sure if that's not relevant for the PDF viewer because it only loads this file?

In any case, IDs too short and generic are not allowed in mozilla-central (see the number of linter errors in phabricator), namespacing avoid that issue.

File: gulpfile.mjs [hunk 1]
```diff
@@ -583,6 +584,24 @@ function createImageDecodersBundle(defines) {
     .pipe(tweakWebpackOutput("pdfjsImageDecoders"));
 }
 
+function createFluentBundle(defines) {
```
Comment (Snuffleupagus) [inline gulpfile.mjs:587]: Why do we need this, can't we "simply" leverage import maps *fully* to pull in the relevant code directly in the viewer?

Ideally the relevant build-targets would automatically include the necessary Fluent-code during building.

File: web/genericl10n.js [hunk 2]
```diff
@@ -15,63 +15,63 @@
...
-  pt: "pt-PT",
-  sv: "sv-SE",
-  zh: "zh-CN",
-};
-
-// Try to support "incompletely" specified language codes (see issue 13689).
-function fixupLangCode(langCode) {
-  return PARTIAL_LANG_CODES[langCode?.toLowerCase()] || langCode;
-}
+import { DOMLocalization, FluentBundle, FluentResource } from "pdfjs-fluent";
```
Comment (Snuffleupagus) [inline web/genericl10n.js:18]: As mentioned elsewhere, can't we simply introduce two new import maps and directly import the relevant code here?
```suggestion
import { FluentBundle, FluentResource } from "pdfjs-fluent-bundle";
import { DOMLocalization } from "pdfjs-fluent-dom";

```

File: web/l10n.js [hunk 3]
```diff
@@ -0,0 +1,95 @@
...
+  async getDirection() {
+    return this.#dir;
+  }
+
+  /** @inheritdoc */
+  async get(ids, args = null, fallback) {
+    if (Array.isArray(ids)) {
+      return (await this.#l10n.formatMessages(ids.map(id => ({ id })))).map(
+        message => message.value
+      );
```
Comment (Snuffleupagus) [inline web/l10n.js:50]: This isn't a wonder of readability, given that sheer amount of parenthesis, so could we perhaps introduce a temporary variable to simplify this a little bit?

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]
Does the [`NullL10n` class](https://github.com/mozilla/pdf.js/blob/4ac44b9d6d821471679f7f90eab4cd222b7c09a6/web/l10n_utils.js#L123-L141) still work, e.g. if the viewer is loaded without l10n-data being available, given all the changes made in this patch?
Given that you've removed e.g. [this code](https://github.com/mozilla/pdf.js/pull/17115/files#diff-d7b040092cf6be09a276b785ba03c46e79bc8342cf4ae4fb1bc139dea8513425L3024-L3025) and [this code](https://github.com/mozilla/pdf.js/pull/17115/files#diff-c7bc7f47773a8fd3d5ab47de09fa64842a650f4322c14699acafe136728b0ce8L308) I unfortunately cannot really imagine that this still works as before!?

You also need to update the l10n-import script to account for the new file-extension, see https://github.com/mozilla/pdf.js/blob/master/external/importL10n/locales.mjs

Should we also remove *all* old `viewer.properties` files, since they're unused now?

Does this pass *all* tests, i.e. `gulp test` locally, since we're using localization during browser tests?

**Comment by calixteman** [comment]
> ### String structure
> 
> ```
> previous =
>     .title = Previous Page
> previous-label = Previous
> ```
> Can this be a single string? Example:
> 
> ```
> pdfviewer-previous-button = Previous
>     .title = Previous Page
> ```

Unfortunately, I think it won't work because the two strings are for two different elements:
https://github.com/mozilla/pdf.js/pull/17115/files#diff-4b300cea2df7f3f32d97ec5bd2e71eee41932f0fb52f31516f91dbff0c683409R319-R321

File: web/pdf_layer_viewer.js [hunk 4]
```diff
@@ -94,7 +94,7 @@ class PDFLayerViewer extends BaseTreeViewer {
       element.textContent = this._normalizeTextContent(name);
       return;
     }
-    element.textContent = await this.l10n.get("additional_layers");
+    element.textContent = await this.l10n.get("additional_-layers");
```
Comment (Snuffleupagus) [inline web/pdf_layer_viewer.js:97]: This looks like a typo, looking at the `.ftl` file I'm assuming that you meant:
```suggestion
    element.textContent = await this.l10n.get("additional-layers");
```

File: web/toolbar.js [hunk 5]
```diff
@@ -321,12 +321,13 @@ class Toolbar {
...
-      l10n.get("page_scale_actual"),
-      l10n.get("page_scale_fit"),
-      l10n.get("page_scale_width"),
+    const predefinedValuesPromise = l10n.get([
+      "page-scale-auto",
+      "page-scale-actual",
+      "page-scale-fit",
+      "page-scale-width",
     ]);
+
```
Comment (Snuffleupagus) [inline web/toolbar.js:330]: Nit: Unrelated change.

File: web/l10n.js [hunk 6]
```diff
@@ -0,0 +1,95 @@
...
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+/** @typedef {import("./interfaces").IL10n} IL10n */
+/**
+ * @implements {IL10n}
+ */
```
Comment (Snuffleupagus) [inline web/l10n.js:19]: Nit: Please add a blank line between these two comments.
```suggestion
/** @typedef {import("./interfaces").IL10n} IL10n */

/**
 * @implements {IL10n}
 */
```

File: web/l10n.js [hunk 7]
```diff
@@ -0,0 +1,95 @@
...
+class L10n {
+  #dir;
+
+  #l10n;
+
+  constructor({ lang, isRTL }, l10n = null) {
+    this.lang = L10n.#fixupLangCode(lang);
```
Comment (Snuffleupagus) [inline web/l10n.js:26]: Given that this property ideally should be private as well (but cannot be that given the `GenericL10n` constructor), can we at least make it "semi"-private?
```suggestion
    this._lang = L10n.#fixupLangCode(lang);
```

File: web/l10n_utils.js [hunk 8]
```diff
@@ -24,12 +24,12 @@
  * A subset of the l10n strings in the `l10n/en-US/viewer.properties` file.
  */
 const DEFAULT_L10N_STRINGS = {
-  of_pages: "of {{pagesCount}}",
-  page_of_pages: "({{pageNumber}} of {{pagesCount}})",
+  of_pages: "of { $pagesCount }",
```
Comment (Snuffleupagus) [inline web/l10n_utils.js:27]: *This applies everywhere below as well, and ties into my (previous) question about the general state of `NullL10n` class.*

Given that the `.ftl` file calls this `of-pages`, I don't think this'll work?

**Comment by calixteman** [comment]
> Does the [`NullL10n` class](https://github.com/mozilla/pdf.js/blob/4ac44b9d6d821471679f7f90eab4cd222b7c09a6/web/l10n_utils.js#L123-L141) still work, e.g. if the viewer is loaded without l10n-data being available, given all the changes made in this patch?

Do we want to keep the `NullL10n` stuff ?
Won't `fluent`+`en-US/viewer.ftl` have the same role as `NullL10n` ?
That said, I thought removing it in this patch but I guessed that maybe it'd make this patch a bit too large.
I've the feeling that `NullL10n` is adapted to what we had, but with fluent it doesn't really make sense.

**Comment by Snuffleupagus** [comment]
> Do we want to keep the `NullL10n` stuff ?

Well, unless you want to "break" the *standalone* viewer-components and/or annotationLayer then keeping the `NullL10n`-functionality (in some form) will definitely be necessary.
Please note how that's being used as a *fallback* in situations where the normal l10n-stuff isn't available, i.e. outside of the default viewer use-case.

That said, I've got an idea for how we could address this (keeping a modified `NullL10n`). If you address my initial comments above, especially about the *hopefully unneeded* `createFluentBundle`-functionality, then I'll hopefully be able to outline a possible solution here.

File: src/display/annotation_layer.js [hunk 9]
```diff
@@ -3022,7 +3022,9 @@ class AnnotationLayer {
 
     this.#setAnnotationCanvasMap();
 
-    await this.l10n.translate(layer);
+    if (typeof PDFJSDev === "undefined" || !PDFJSDev.test("MOZCENTRAL")) {
```
Comment (Snuffleupagus) [inline src/display/annotation_layer.js:3025]: [Given this code](https://github.com/mozilla/pdf.js/blob/2a3090224fa60110ad80097002beb42d0f5547cb/src/display/annotation_layer.js#L2918-L2923) I'd kind of expect the following condition here (and similar elsewhere in this patch).
```suggestion
    if (
      typeof PDFJSDev !== "undefined" &&
      PDFJSDev.test("GENERIC && !TESTING") &&
      this.l10n instanceof NullL10n
    ) {
```

File: web/l10n_utils.js [hunk 10]
```diff
@@ -21,102 +21,102 @@
...
+  "pdfjs-page-landmark": "Page { $page }",
+  "pdfjs-thumb-page-title": "Page { $page }",
+  "pdfjs-thumb-page-canvas": "Thumbnail of Page { $page }",
+
+  "pdfjs-find-reached-top": "Reached top of document, continued from bottom",
+  "pdfjs-find-reached-bottom": "Reached end of document, continued from top",
+  "find_match_count[one]": "{ $current } of { $total } match",
+  "find_match_count[other]": "{ $current } of { $total } matches",
+  "find_match_count_limit[one]": "More than { $limit } match",
+  "find_match_count_limit[other]": "More than { $limit } matches",
```
Comment (Snuffleupagus) [inline web/l10n_utils.js:58]: Shouldn't the ids of these strings be updated as well?

File: web/genericl10n.js [hunk 11]
```diff
@@ -15,63 +15,68 @@
...
+      return null;
+    }
+    const url = new URL(path, baseURL);
+    const data = await fetch(url);
+    const text = await data.text();
+    const resource = new FluentResource(text);
+    const bundle = new FluentBundle(lang);
+    const errors = bundle.addResource(resource);
+    if (errors.length) {
+      console.error("L10N errors", errors);
```
Comment (Snuffleupagus) [inline web/genericl10n.js:70]: Nit:
```suggestion
      console.error("L10n errors", errors);
```

File: web/genericl10n.js [hunk 12]
```diff
@@ -15,63 +15,68 @@
...
-    const l10n = await this._ready;
-    return l10n.getLanguage();
+    super({ lang });
+    this.setL10n(
+      new DOMLocalization(
+        [],
+        GenericL10n.#generateBundles.bind(
+          GenericL10n,
+          "en-US",
+          this.getLanguage()
```
Comment (Snuffleupagus) [inline web/genericl10n.js:34]: Given that this method is `async`, how does this work in `#generateBundles` method since that it (according to the JSDocs) expects a string argument?

File: l10n/en-US/viewer.ftl [hunk 13]
```diff
@@ -0,0 +1,387 @@
...
+pdfjs-spread-none-button =
+    .title = Do not join page spreads
+pdfjs-spread-none-button-label = No Spreads
+pdfjs-spread-odd-button =
+    .title = Join page spreads starting with odd-numbered pages
+pdfjs-spread-odd-button-label = Odd Spreads
+pdfjs-spread-even-button =
+    .title = Join page spreads starting with even-numbered pages
+pdfjs-spread-even-button-label = Even Spreads
+# .title: Document properties dialog box
```
Comment (Snuffleupagus) [inline l10n/en-US/viewer.ftl:112]: The beginning of this comment looks like a typo.

File: l10n/en-US/viewer.ftl [hunk 14]
```diff
@@ -0,0 +1,386 @@
...
+    .title = Next Page
+pdfjs-next-button-label = Next
+
+# .title: Tooltip for the pageNumber input.
+pdfjs-page-input =
+    .title = Page
+
+# Variables:
+#   $pagesCount (Number) - the total number of pages in the document
+pdfjs-of-pages = of { $pagesCount }
```
Comment (flodolo) [inline l10n/en-US/viewer.ftl:20]: Can you help me understand where this is used? I wonder why it starts lowercase, and what's before it.

File: l10n/en-US/viewer.ftl [hunk 15]
```diff
@@ -0,0 +1,386 @@
...
+pdfjs-document-properties-page-size-unit-inches = in
+pdfjs-document-properties-page-size-unit-millimeters = mm
+pdfjs-document-properties-page-size-orientation-portrait = portrait
+pdfjs-document-properties-page-size-orientation-landscape = landscape
+pdfjs-document-properties-page-size-name-a-three = A3
+pdfjs-document-properties-page-size-name-a-four = A4
+pdfjs-document-properties-page-size-name-letter = Letter
+pdfjs-document-properties-page-size-name-legal = Legal
+
+# Variables:
```
Comment (flodolo) [inline l10n/en-US/viewer.ftl:158]: You can group these two strings and avoid repeating the comment

```
## Variables:
##   $width (Number) - the width of the (current) page
##   $height (Number) - the height of the (current) page
##   $unit (String) - the unit of measurement of the (current) page
##   $name (String) - the name of the (current) page
##   $orientation (String) - the orientation of the (current) page

pdfjs-document-properties-page-size-dimension-string = { $width } × { $height } { $unit } ({ $orientation })
pdfjs-document-properties-page-size-dimension-name-string = { $width } × { $height } { $unit } ({ $name }, { $orientation })

##

```

File: l10n/en-US/viewer.ftl [hunk 16]
```diff
@@ -0,0 +1,386 @@
...
+pdfjs-document-properties-linearized-yes = Yes
+pdfjs-document-properties-linearized-no = No
+pdfjs-document-properties-close-button = Close
+
+## Print
+
+pdfjs-print-progress-message = Preparing document for printing…
+
+# Variables:
+#   $progress (Number) - per cent value
```
Comment (flodolo) [inline l10n/en-US/viewer.ftl:185]:
```suggestion
#   $progress (Number) - percent value
```

**Review by flodolo — COMMENTED** [review]
Looks great. Only one question and some nits on the comments.

File: l10n/en-US/viewer.ftl (hunk 14 above)
Comment (calixteman) [reply l10n/en-US/viewer.ftl:20]: image

File: web/pdf_document_properties.js [hunk 17]
```diff
@@ -84,9 +84,7 @@ class PDFDocumentProperties {
     });
 
     this._isNonMetricLocale = true; // The default viewer locale is 'en-us'.
```
Comment (Snuffleupagus) [inline web/pdf_document_properties.js:86]: Isn't this line unnecessary now?

File: web/l10n_utils.js [hunk 18]
```diff
@@ -21,102 +21,102 @@
...
+  "pdfjs-editor-resizer-label-bottom-middle": "Bottom middle — resize",
+  "pdfjs-editor-resizer-label-bottom-left": "Bottom left corner — resize",
+  "pdfjs-editor-resizer-label-middle-left": "Middle left — resize",
 };
 if (typeof PDFJSDev === "undefined" || !PDFJSDev.test("MOZCENTRAL")) {
-  DEFAULT_L10N_STRINGS.print_progress_percent = "{{progress}}%";
+  DEFAULT_L10N_STRINGS.print_progress_percent = "{ $progress }%";
 }
 
 function getL10nFallback(key, args) {
```
Comment (Snuffleupagus) [inline web/l10n_utils.js:99]: Do we still need to export this function now?

File: l10n/en-US/viewer.ftl [hunk 19]
```diff
@@ -0,0 +1,370 @@
...
+##   $width (Number) - the width of the (current) page
+##   $height (Number) - the height of the (current) page
+##   $unit (String) - the unit of measurement of the (current) page
+##   $name (String) - the name of the (current) page
+##   $orientation (String) - the orientation of the (current) page
+
+pdfjs-document-properties-page-size-dimension-string = { $width } × { $height } { $unit } ({ $orientation })
+pdfjs-document-properties-page-size-dimension-name-string = { $width } × { $height } { $unit } ({ $name }, { $orientation })
+
+# The linearization status of the document; usually called "Fast Web View" in
```
Comment (flodolo) [inline l10n/en-US/viewer.ftl:169]: Reset the group comment (with an empty one), otherwise it will apply to the 4 next string.

```
pdfjs-document-properties-page-size-dimension-name-string = { $width } × { $height } { $unit } ({ $name }, { $orientation })

##

# The linearization status of the document; usually called "Fast Web View" in
```

**Review by flodolo — APPROVED** [review]

File: web/pdf_sidebar.js [hunk 20]
```diff
@@ -20,6 +20,7 @@ import {
   toggleCheckedBtn,
   toggleExpandedBtn,
 } from "./ui_utils.js";
+import { NullL10n } from "display-l10n_utils";
```
Comment (Snuffleupagus) [inline web/pdf_sidebar.js:23]: I just realized that the `PDFSidebar` is *always assumed* to be initialized with a "proper" l10n-class, since it's not part of the standalone viewer-components [as defined here](https://github.com/mozilla/pdf.js/blob/master/web/pdf_viewer.component.js).

Hence you can actually remove all `NullL10n` stuff in this particular file; sorry about not catching this earlier!

**Review by Snuffleupagus — COMMENTED** [review]
Please run *all* tests, and assuming it passes, I'll try to take a more detailed look ASAP.

**Review by Snuffleupagus — COMMENTED** [review]
Two more questions:
 - Would it be feasible to add (at least) one non-English `viewer.ftl` file, such that it's possible to test that the viewer handles non-default locales correctly?

 - Given that the annotationLayer translation is now handled "automatically", via a `MutationObserver` as far as I understand, are we guaranteed that it's *fully completed* during the reference tests?
   Previously we'd explicitly await translation in the annotationLayer code, which means that after https://github.com/mozilla/pdf.js/blob/2a3090224fa60110ad80097002beb42d0f5547cb/test/driver.js#L250-L251 we'd know that translation has completed *before* rasterizing the annotationLayer.
   It'd be unfortunate if we introduce any intermittent failures during the `annotation`/`form` ref-tests, so is there something (e.g. an event or some DOM property) that the ref-tests could check for (or await) to prevent a future problem there?

**Comment by calixteman** [comment]
> * Would it be feasible to add (at least) one non-English `viewer.ftl` file, such that it's possible to test that the viewer handles non-default locales correctly?

I tested that in copying the english file in `de` directory and in vscode I replaced `= ([a-zA-Z])` by `= X$1` and then with then I appended `#locale=de` to the url.
I can create the file if you prefer, tell me.

> * Given that the annotationLayer translation is now handled "automatically", via a `MutationObserver` as far as I understand, are we guaranteed that it's _fully completed_ during the reference tests?

Good question: I think we could call and await for `translateRoots`:
https://github.com/projectfluent/fluent.js/blob/f07305556f92bf19acfccc9621adf99dd8f434d8/fluent-dom/src/dom_localization.js#L187.

**Comment by flodolo** [comment]
This is the file migrated for German using the recipe in the current Phabricator diff (haven't had time to verify if it's correct yet). Only need to rename from .txt to .ftl

[viewer.txt](https://github.com/mozilla/pdf.js/files/13033377/viewer.txt)

**Comment by Snuffleupagus** [comment]
> I can create the file if you prefer, tell me.

Yes, can you please attach the file from https://github.com/mozilla/pdf.js/pull/17115#issuecomment-1769217978  to this PR (in the correct l10n-directory)?
I want to spend a little time testing this locally (hopefully tomorrow) and that'll help to more easily test all the new stuff.

> Good question: I think we could call and await for `translateRoots`:

While that obviously "works" I believe that it side-steps part of the desired testing unfortunately, since that as far as I understand actually *triggers* translation.
Isn't the thing that we'd *ideally* want to await here the existing translation, that's automatically triggered by adding elements to the annotationLayer (such that the ref-tests work the same as the viewer in that respect)?

File: .eslintrc [hunk 21]
```diff
@@ -42,7 +42,7 @@
     "import/no-mutable-exports": "error",
     "import/no-self-import": "error",
     "import/no-unresolved": ["error", {
-      "ignore": ["display", "pdfjs", "pdfjs-lib", "pdfjs-web", "web"]
+      "ignore": ["display", "pdfjs", "pdfjs-lib", "pdfjs-web", "web", "fluent-bundle", "fluent-dom", ],
```
Comment (Snuffleupagus) [inline .eslintrc:45]: Nit:
```suggestion
      "ignore": ["display", "pdfjs", "pdfjs-lib", "pdfjs-web", "web", "fluent-bundle", "fluent-dom"],
```

**Review by Snuffleupagus — COMMENTED** [review]
There's a couple of other files that we should probably update as well:
 - https://github.com/mozilla/pdf.js/blob/2a3090224fa60110ad80097002beb42d0f5547cb/.gitattributes#L7 should be changed into
   ```
   *.ftl        text eol=lf
   ```
 - https://github.com/mozilla/pdf.js/blob/2a3090224fa60110ad80097002beb42d0f5547cb/.github/CODEOWNERS#L1 should be changed into
    ```
    l10n/en-US/*.ftl @mozilla/pdfjs-l10n
    ```
 - https://github.com/mozilla/pdf.js/blob/2a3090224fa60110ad80097002beb42d0f5547cb/test/webserver.mjs#L36 should be changed into
    ```javascript
    ".ftl": "text/plain", 
    ```

**Comment by calixteman** [comment]
> While that obviously "works" I believe that it side-steps part of the desired testing unfortunately, since that as far as I understand actually _triggers_ translation.
> Isn't the thing that we'd _ideally_ want to await here the existing translation, that's automatically triggered by adding elements to the annotationLayer (such that the ref-tests work the same as the viewer in that respect)?

I don't see anything we can wait for unfortunately... if you've any ideas, I take.

**Comment by calixteman** [comment]
> Yes, can you please attach the file from [#17115 (comment)](https://github.com/mozilla/pdf.js/pull/17115#issuecomment-1769217978) to this PR (in the correct l10n-directory)?

Done.

**Comment by Snuffleupagus** [comment]
Unfortunately I don't believe that l10n during the ref-tests currently work at all with this patch, since I've just tested the following diff which works just fine *in the viewer* but the ref-tests no longer translate as they should (since the annotationLayer-element isn't being "registered" for l10n).
```diff
diff --git a/src/display/annotation_layer.js b/src/display/annotation_layer.js
index 243744581..54ddbd569 100644
--- a/src/display/annotation_layer.js
+++ b/src/display/annotation_layer.js
@@ -2021,7 +2021,7 @@ class PopupAnnotationElement extends AnnotationElement {
 }
 
 class PopupElement {
-  #dateTimePromise = null;
+  #dateObj = null;
 
   #boundKeyDown = this.#keyDown.bind(this);
 
@@ -2078,16 +2078,10 @@ class PopupElement {
     this.#parentRect = parentRect;
     this.#elements = elements;
 
-    const dateObject = PDFDateString.toDateObject(modificationDate);
-    if (dateObject) {
-      // The modification date is shown in the popup instead of the creation
-      // date if it is available and can be parsed correctly, which is
-      // consistent with other viewers such as Adobe Acrobat.
-      this.#dateTimePromise = parent.l10n.get("pdfjs-annotation-date-string", {
-        date: dateObject.toLocaleDateString(),
-        time: dateObject.toLocaleTimeString(),
-      });
-    }
+    // The modification date is shown in the popup instead of the creation
+    // date if it is available and can be parsed correctly, which is
+    // consistent with other viewers such as Adobe Acrobat.
+    this.#dateObj = PDFDateString.toDateObject(modificationDate);
 
     this.trigger = elements.flatMap(e => e.getElementsToTriggerPopup());
     // Attach the event listeners to the trigger element.
@@ -2115,9 +2109,6 @@ class PopupElement {
         if (this.#container.hidden) {
           this.#show();
         }
-        if (this.#dateTimePromise) {
-          await this.#dateTimePromise;
-        }
       });
     }
   }
@@ -2166,11 +2157,14 @@ class PopupElement {
     ({ dir: title.dir, str: title.textContent } = this.#titleObj);
     popup.append(header);
 
-    if (this.#dateTimePromise) {
+    if (this.#dateObj) {
       const modificationDate = document.createElement("span");
       modificationDate.classList.add("popupDate");
-      this.#dateTimePromise.then(localized => {
-        modificationDate.textContent = localized;
+
+      modificationDate.dataset.l10nId = "pdfjs-annotation-date-string";
+      modificationDate.dataset.l10nArgs = JSON.stringify({
+        date: this.#dateObj.toLocaleDateString(),
+        time: this.#dateObj.toLocaleTimeString(),
       });
       header.append(modificationDate);
     }
```

Also, would the diff above make sense to incorporate into this patch to reduce "manual" translation?

---

> I don't see anything we can wait for unfortunately... if you've any ideas, I take.

Unfortunately I don't have a good idea for this. However, to fix the ref-test problem described above the following diff seems to work locally.
```diff
diff --git a/test/driver.js b/test/driver.js
index 8e9026105..dad883ecc 100644
--- a/test/driver.js
+++ b/test/driver.js
@@ -233,6 +233,9 @@ class Rasterize {
         outputScale
       );
 
+      // Ensure that the annotationLayer gets translated.
+      document.l10n.connectRoot(div);
+
       // Rendering annotation layer as HTML.
       const parameters = {
         annotations,
@@ -251,6 +254,9 @@ class Rasterize {
       await annotationLayer.showPopups();
       await document.l10n.translateRoots();
 
+      // All translation should be complete here.
+      document.l10n.disconnectRoot(div);
+
       // Inline SVG images from text annotations.
       await inlineImages(div);
       foreignObject.append(div);
```

File: test/driver.js [hunk 22]
```diff
@@ -249,6 +253,10 @@ class Rasterize {
       });
       await annotationLayer.render(parameters);
       await annotationLayer.showPopups();
+      await document.l10n.translateRoots();
```
Comment (Snuffleupagus) [inline test/driver.js:256]: Please add a comment explaining why we do this here.
```suggestion
      // Translation should happen "automatically" in the annotationLayer,
      // however we cannot await that hence we manually trigger translation
      // here to prevent any intermittent test failures.
      await document.l10n.translateRoots();
```

File: test/integration/find_spec.mjs [hunk 23]
```diff
@@ -93,7 +93,10 @@ describe("find bar", () => {
           await page.waitForSelector(".xfaLayer .highlight");
           const resultElement = await page.waitForSelector("#findResultsCount");
           const resultText = await resultElement.evaluate(el => el.textContent);
-          expect(resultText).toEqual("1 of 1 match");
+          /** Unicode bidi isolation characters. */
+          const FSI = "\u2068";
+          const PDI = "\u2069";
+          expect(resultText).toEqual(`${FSI}1${PDI} of ${FSI}1${PDI} match`);
```
Comment (Snuffleupagus) [inline test/integration/find_spec.mjs:99]: Sorry, but I really don't understand these change; why is this necessary?

File: web/pdf_layer_viewer.js [hunk 24]
```diff
@@ -94,7 +94,7 @@ class PDFLayerViewer extends BaseTreeViewer {
       element.textContent = this._normalizeTextContent(name);
       return;
     }
-    element.textContent = await this.l10n.get("additional_layers");
+    element.textContent = await this.l10n.get("pdfjs-additional-layers");
```
Comment (Snuffleupagus) [inline web/pdf_layer_viewer.js:97]: Given that this component is only used in the default viewer, could we change this line as follows (with suitable modification of the l10n-files) and thus remove `async` from this method?
```suggestion
    element.setAttribute("data-l10n-id", "pdfjs-additional-layers");
```

File: web/toolbar.js [hunk 25]
```diff
@@ -340,7 +344,7 @@ class Toolbar {
     ctx.font = `${style.fontSize} ${style.fontFamily}`;
 
     let maxWidth = 0;
-    for (const predefinedValue of await predefinedValuesPromise) {
+    for (const { predefinedValue } of await predefinedValuesPromise) {
```
Comment (Snuffleupagus) [inline web/toolbar.js:347]: This doesn't work in the viewer, when testing with the `de` locale. However the following seems correct:
```suggestion
    for (const predefinedValue of await predefinedValuesPromise) {
```

File: test/integration/find_spec.mjs (hunk 23 above)
Comment (calixteman) [reply test/integration/find_spec.mjs:99]: Because Fluent adds these markers by default, but it can be changed when creating the bundle:
https://github.com/projectfluent/fluent.js/blob/f07305556f92bf19acfccc9621adf99dd8f434d8/fluent-bundle/src/bundle.ts#L61-L66
TBH, I don't know if we should set `useIsolating` to false or not, so it's why I kept the default.

**Review by Snuffleupagus — APPROVED** [review]
Please run *all* tests one more time, before landing this.
This looks very nice, and seems like an overall simplification of the l10n-handling.

r=me, assuming that all tests still pass; thank you!

**Comment by timvandermeij** [comment]
Nice work @calixteman and @Snuffleupagus for your  L10n patches! This has been quite a chunk of work, but it's great to see that the overall L10n handling is simpler now and we got rid of the old webl10n code.
