### PR TITLE
Only mask char codes of (3, 0) cmap tables in the range of 0xF000 to 0…

### LINKED ISSUE #8187: 3 Of 9 barcode is not generated properly
Link to PDF file (or attach file here):
**PDF file display**
capture_item1

**PDF preview view PDF.js**
capture_item2

Configuration:
- Web browser and its version:  Chrome 50.0.2661.94 m
- Operating system and its version: windows 7
- PDF.js version: v1.6.210
- Is an extension: No

Steps to reproduce the problem:
1. The PDF converts to base64 string 
2. Use the base64 string to generate preview

What is the expected behavior? (add screenshot)
capture_item1

What went wrong? (add screenshot)
3 Of 9 barcode is generated with extra space in the middle

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### PR DESCRIPTION
**Pull request by brendandahl**
…xF0FF.

Fixes #8187

### CODE REVIEW

File: src/core/fonts.js [hunk 1]
```diff
@@ -2406,21 +2406,23 @@ var Font = (function FontClosure() {
...
-          // For (1, 0) cmap tables:
-          // 'single bytes from the string shall be used to look up the
-          // associated glyph descriptions from the subtable'. This means
-          // charcodes in the cmap will be single bytes, so no-op since
-          // glyph.charCode & 0xFF === glyph.charCode
+          // When there is only a (1, 0) cmap table, the char code is a single
+          // byte and it is used directly as the char code.
+
+          // When a (3, 0) cmap table is present, it is used instead but the
+          // spec has special rules for char codes in the range of 0xF00 to
```
Comment (Snuffleupagus) [inline src/core/fonts.js]: Here, and in the commit message as well, I'm assuming that it should be `0xF000` instead to match the code!?

**Review by Snuffleupagus — APPROVED** [review]
r=me, with the comment addressed.
Thank you for the patch!
