### PR TITLE
[JS] Handle correctly choice widgets where the display and the export values are different (issue #15815)

### LINKED ISSUE #15815: "Nationality or citizenship" select field doesn't show/store its'value
Attach (recommended) or Link to PDF file here: https://www.mofa.go.jp/files/000124525.pdf

Configuration:
- Web browser and its version: Firefox Nightly 109.0a1 (2022-12-11)
- Operating system and its version: macOS
- PDF.js version: (whatever is included in that Firefox build)
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the linked PDF
2. Select a value in the "Nationality or citizenship" field

What is the expected behavior? (add screenshot)

The selected value should show in the form

What went wrong? (add screenshot)

Form field stays empty

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): n/a

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

File: src/scripting_api/event.js [hunk 1]
```diff
@@ -170,6 +171,17 @@ class EventDispatcher {
       if (event.willCommit) {
         this.runValidation(source, event);
       } else {
+        if (source.obj._isChoice) {
+          const exportValue = savedChange.changeEx;
+          source.obj.value = exportValue;
```
Comment (Snuffleupagus) [inline src/scripting_api/event.js:176]: Is the `exportValue` variable used for anything, or was this mostly for documentation purposes? If so, maybe just:
```suggestion
          source.obj.value = savedChange.changeEx; // exportValue
```

**Review by Snuffleupagus — APPROVED** [review]
The GitHub Actions warning about https://github.com/mozilla/pdf.js/blob/0fdac9ba708d765d75dd16522021bb22a8fd8234/src/display/annotation_layer.js#L1764 seems correct, so please remove the `event`-argument there as well.

r=me, with the comments addressed and passing tests; thank you!
