### PR TITLE
Don't replace cr by a white space when the last char on the line is an ideographic char

### LINKED ISSUE #15340: Japanese character can't search when there is a new line
Attach (recommended) or Link to PDF file here:
https://www.meti.go.jp/policy/consumer/seian/denan/file/04_cn/scope/haninokaishaku_211228.pdf

Configuration:
- Web browser and its version: Google Chrome 104.0.5112.81
- Operating system and its version: Windows 10 Pro 21H2 19044.1826
- PDF.js version: v2.15.349
- Is a browser extension: No

Steps to reproduce the problem:
1. Search "検知機構" by Ctrl+F.

What went wrong? (add screenshot):
"検知機構" on page 5 must be hit.
If search "検知機 構"  (add space between 機 and 構), it hits.

キャプチャ

When this PDF file is opened by Adobe Reader, there is no problem.

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

File: test/pdfs/.gitignore [hunk 1]
```diff
@@ -538,3 +538,5 @@
 !bug1782186.pdf
 !tracemonkey_a11y.pdf
 !bug1782564.pdf
+!issue15340.pdf
+
```
Comment (Snuffleupagus) [inline test/pdfs/.gitignore:542]: Nit: One new-line too many at the here.

File: web/pdf_find_controller.js [hunk 2]
```diff
@@ -248,6 +248,15 @@ function normalize(text) {
       }
 
       if (p4) {
+        // An ideographic at the end of a line doesn't imply toadd an extra
```
Comment (Snuffleupagus) [inline web/pdf_find_controller.js:251]: Spelling/grammar nit:
```suggestion
        // An ideographic at the end of a line doesn't imply adding an extra
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, looks simple enough!
