### PR TITLE
Adjust the heuristics used when dealing with rectangles, i.e. `re` operators, with zero width/height (issue 12010)

### LINKED ISSUE #12010: Corner rendered incorrectly in figure
Link to PDF file: http://mirrors.ctan.org/graphics/pgf/contrib/circuitikz/doc/circuitikzmanual.pdf (version 1.1.2)

Configuration:
- Web browser and its version: Firefox 77.0.1
- Operating system and its version: Windows 10 1909
- PDF.js version: 2.5.95 (included in Firefox)

Consider the bottom left corner in the figure at the bottom of page 148.

What is the expected behavior?
correct

What went wrong?
wrong

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Fixes #12010

### CODE REVIEW

File: src/display/canvas.js [hunk 1]
```diff
@@ -1185,20 +1185,20 @@ var CanvasGraphics = (function CanvasGraphicsClosure() {
             y = args[j++];
             var width = args[j++];
             var height = args[j++];
-            if (width === 0) {
+            if (width === 0 && ctx.lineWidth < this.getSinglePixelWidth()) {
```
Comment (timvandermeij) [inline src/display/canvas.js:1188]: Can't we do this `getSinglePixelWidth` function call only once? We're doing it four times in the worst case now, and the path construction code is usually quite hot.

**Review by timvandermeij — COMMENTED** [review]
Looks good with the comment addressed and a rebase.

**Comment by timvandermeij** [comment]
Note to self: makeref after this will also apply to the already merged PRs while the Linux bot was down.

File: src/display/canvas.js (hunk 1 above)
Comment (Snuffleupagus) [reply src/display/canvas.js:1188]: > We're doing it four times in the worst case now,

Well, that case *almost never* happens in practice since in most cases both the width *and* height is non-zero.
Hence I did it this way on purpose, since otherwise *every* single `re` operator would unnecessarily require a `this.getSinglePixelWidth()` call.

Comment (timvandermeij) [reply src/display/canvas.js:1188]: That's seems fair; thanks!

**Review by timvandermeij — APPROVED** [review]
