### PR TITLE
Apply transformation matrix to RadialGradient radiuses

### LINKED ISSUE #6006: Radial gradient
The radial gradient in this PDF appears as a small dot.
Maybe the radius is wrong?
https://drive.google.com/file/d/0B0odzw1WMqkGTkFyZGFKamdaNUU/view

### LINKED ISSUE #6296: Radial shading (type 3) too small
http://asymptote.sourceforge.net/gallery/shade.pdf
the radial shading (type 3) is there, but it is too small. (Maybe related to the issue where somebody complained that a radial shading was a single dot)

### PR DESCRIPTION
**Pull request by dsprenkels**
It looked like #6006 was caused by the fact that the transformation matrix of some pattern was only applied to the origin points of the two circles describing the gradient. This change makes it so that also the radii of the circles will be scaled.

Note that this commit does _not_ fix #6296.

~~I have not really tested the commit very thoroughly, using the unit tests. I ran into some problems.~~

Fixes #6006.

### CODE REVIEW

File: src/core/pattern.js [hunk 1]
```diff
@@ -205,6 +205,8 @@ Shadings.RadialAxial = (function RadialAxialClosure() {
       if (matrix) {
         p0 = Util.applyTransform(p0, matrix);
         p1 = Util.applyTransform(p1, matrix);
+        r0 *= matrix[0];
```
Comment (yurydelendik) [inline src/core/pattern.js]: Use Util.singularValueDecompose2dScale https://github.com/mozilla/pdf.js/blob/master/src/shared/util.js#L701 instead of the matrix[0]

**Comment by yurydelendik** [comment]
Please include "eq" test file.

**Comment by Snuffleupagus** [comment]
The PDF file included in this PR seems to be slightly corrupt, since the `xref` table is missing.
(Note that PDF.js warns about this in the console, and that e.g. Adobe Reader prompts you to re-save the file on closing.)

@dsprenkels I hope you don't mind that I took the liberty of linking to a "cleaned-up" version (obtained by running the PDF file through [PDFtk](https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/)) of the PDF file: [issue6006.pdf](https://github.com/mozilla/pdf.js/files/35819/issue6006.pdf)

**Comment by Snuffleupagus** [comment]
> So I know for the next time: is it this or this pdftk?

I'm using the command-line version, called `PDFtk Server` (on Windows), since I didn't personally feel the need for a GUI.

File: src/core/pattern.js [hunk 2]
```diff
@@ -205,6 +205,9 @@ Shadings.RadialAxial = (function RadialAxialClosure() {
       if (matrix) {
         p0 = Util.applyTransform(p0, matrix);
         p1 = Util.applyTransform(p1, matrix);
+        var scale = Util.singularValueDecompose2dScale(matrix);
+        r0 *= scale[0];
```
Comment (yurydelendik) [inline src/core/pattern.js]: notice that r0 can be `null` (see above).

Comment (yurydelendik) [inline src/core/pattern.js]: perform the multiplication only for `shadingType === ShadingType.RADIAL` case

Comment (dsprenkels) [inline src/core/pattern.js]: Good point, that's a nasty mistake.

**Comment by timvandermeij** [comment]
Looks good to me. I'll leave the final review to @yurydelendik.

**Comment by yurydelendik** [comment]
Thank you for the patch.

/botio makeref
