### PR TITLE
[Editor] Add a basic stamp editor  (bug 1790255)

### LINKED ISSUE #16498: Create and save STAMP/Image annotation
I'm trying to add support for dynamically adding a STAMP (image) annotation and saving it with the pdf. It can be useful for example, when submitting a pdf form where a user profile image is required.

[saveNewAnnotations](https://github.com/mozilla/pdf.js/blob/master/src/core/annotation.js#L259) has support only for AnnotationEditorType.FREETEXT and AnnotationEditorType.INK. 
Is it possible to call StampAnnotation..createNewAnnotation(xref, annotation, dependencies)?
What is the format for adding the image data to the stamp annotation?

- PDF.js version: v3.7.107

### PR DESCRIPTION
**Pull request by calixteman**
For now it allows to add a stamp annotation with an image selected from the file system.

### CODE REVIEW

File: src/display/editor/tools.js [hunk 1]
```diff
@@ -59,6 +59,127 @@ class IdManager {
...
+/**
+ * Class to manage the images used by the editors.
+ * The main idea is to try to minimize the memory used by the images.
+ * The images are cached and reused when possible
+ * We use a refCounter to know when an image is not used anymore but we need to
+ * be able to restore an image after a remove+undo, so we keep a file reference
+ * or an url one.
+ */
+class ImageManager {
+  #baseId = window.crypto.randomUUID();
```
Comment (Snuffleupagus) [inline src/display/editor/tools.js:71]: There's a couple of issues with using this:
- The `crypto.randomUUID()` function is not available everywhere just yet *and* it's also limited to only secure contexts; please see https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID
 - The `crypto.getRandomValues()` function should be genererally available, however in Node.js environments `crypto` itself may not be; please see https://nodejs.org/dist/latest-v20.x/docs/api/crypto.html#determining-if-crypto-support-is-unavailable

I wrote a helper function to safely obtain a uuid, which you're most welcome to use here; please see https://github.com/mozilla/pdf.js/pull/16610/files#diff-820af4a764722bb36f3daf6f9cb815fedfece273073b21d858bb8aa5210e411cR1016-R1036

**Comment by Snuffleupagus** [comment]
*Another question that I had, without actually having tested this patch (assuming that it's rebased on top of PR #16588).*
Given that the `bitmap`s will be transferred to the worker-thread e.g. during saving, how does that affect future editing?
Imagine the following sequence of events:
 1. Add a new Stamp-annotation to the PDF document.
 2. Save the PDF document (which will *transfer* the `bitmap` to the worker-thread).
 3. Copy the existing Stamp-annotation and paste it in *another* page.
 4. Save the PDF document again.

Assuming that I understand things correctly, which I'm probably not, won't this cause problems in step 3 (or possibly 4) now?
When copying we'll invoke `StampEditor.serialize` which in turns calls `StampEditor.#serializeBitmap`, and that method tries draw a `bitmap` (to a canvas) that's previously been *transferred* to the worker-thread; does this actually work correctly?

**Comment by calixteman** [comment]
> _Another question that I had, without actually having tested this patch (assuming that it's rebased on top of PR #16588)._ Given that the `bitmap`s will be transferred to the worker-thread e.g. during saving, how does that affect future editing? Imagine the following sequence of events:
> 
>     1. Add a new Stamp-annotation to the PDF document.
> 
>     2. Save the PDF document (which will _transfer_ the `bitmap` to the worker-thread).
> 
>     3. Copy the existing Stamp-annotation and paste it in another page.
> 
>     4. Save the PDF document again.
> 
> 
> Assuming that I understand things correctly, which I'm probably not, won't this cause problems in step 3 (or possibly 4) now? When copying we'll invoke `StampEditor.serialize` which in turns calls `StampEditor.#serializeBitmap`, and that method tries to draw a `bitmap` (to a canvas) that's previously been _transferred_ to the worker-thread; does this actually work correctly?

The image we get from a file or an url, a.k.a the base image, is never exposed. Each time we need it somewhere else it has to be cloned and it's exactly what `serializeBitmap` is supposed to do. 
In the specific case you described above, when we copy the annotation, the image is serialized into an URL in order to have it in the clipboard and when it has been saved, the base image is drawn onto a canvas and we use this canvas to generate a clone of the base image. Hence it should be safe (notice the "should").
That said, I think your comment is highlighting a potential issue with the annotation storage: once an image is transferred, then it's lost, so when we we re-use the storage we must be sure to serialize again the annotation containing the bitmap.
I noticed that we're using a `structuredClone` in the `PrintAnnotationStorage` and I was wondering if it could lead to uselessly clone `ImageBitmap` here. 
Anyway, I just rebased the patch and slightly simplify the way to clone the bitmap in using a `structuredClone`.

**Comment by Snuffleupagus** [comment]
> I noticed that we're using a `structuredClone` in the `PrintAnnotationStorage` and I was wondering if it could lead to uselessly clone `ImageBitmap` here.

Unfortunately I believe that it will lead to a copy of the `bitmap` here, however we can probably re-factor things a bit to avoid that; I'll try to look into that.

File: web/annotation_editor_layer_builder.css [hunk 2]
```diff
@@ -167,3 +168,37 @@
...
+  position: absolute;
+  background: transparent;
+  border-radius: 3px;
+  overflow: auto;
+  width: auto;
+  height: auto;
+  z-index: 1;
+  transform-origin: 0 0;
+  cursor: auto;
+}
```
Comment (Snuffleupagus) [inline web/annotation_editor_layer_builder.css:182]: Could we perhaps reduce some duplication here, by [combing this existing code](https://github.com/mozilla/pdf.js/blob/85b1d35eefae74b578efc5957cd56c9cfc7d9d2b/web/annotation_editor_layer_builder.css#L84-L96) with the new one along these lines?
```css
.annotationEditorLayer :is(.freeTextEditor, .stampEditor)  {
  position: absolute;
  background: transparent;
  border-radius: 3px;
  width: auto;
  height: auto;
  z-index: 1;
  transform-origin: 0 0;
  cursor: auto;
}
.annotationEditorLayer .freeTextEditor {
  padding: calc(var(--freetext-padding) * var(--scale-factor));
  resize: none;
  touch-action: none;
}
.annotationEditorLayer .stampEditor  {
  overflow: auto;
}
```

File: web/app_options.js [hunk 3]
```diff
@@ -103,6 +103,11 @@ const defaultOptions = {
     value: typeof PDFJSDev === "undefined" || !PDFJSDev.test("CHROME"),
     kind: OptionKind.VIEWER + OptionKind.PREFERENCE,
   },
+  enableStampEditor: {
+    /** @type {boolean} */
+    value: true,
+    kind: OptionKind.VIEWER + OptionKind.PREFERENCE,
+  },
```
Comment (Snuffleupagus) [inline web/app_options.js:110]: Is this option/preference intended to be *temporary* during development?
If so, perhaps add a comment to that affect?

File: extensions/chromium/preferences_schema.json [hunk 4]
```diff
@@ -81,6 +81,12 @@
       "description": "Whether to allow execution of active content (JavaScript) by PDF files.",
       "default": false
     },
+    "enableStampEditor": {
+      "title": "Enable stamp annotation editing",
+      "type": "boolean",
+      "description": "Whether to allow editing of stamp annotations.",
+      "default": true
+    },
```
Comment (Snuffleupagus) [inline extensions/chromium/preferences_schema.json:89]: Assuming this is temporary, I don't believe that we want to surface this in the Chrome-addon options-UI; hence you probably want the following.
```suggestion
    "enableStampEditor": {
      "type": "boolean",
      "default": true
    },
```

File: web/pdf_viewer.js [hunk 5]
```diff
@@ -846,7 +846,9 @@ class PDFViewer {
             this.#annotationEditorUIManager = new AnnotationEditorUIManager(
               this.container,
               this.eventBus,
-              pdfDocument?.annotationStorage
+              pdfDocument?.annotationStorage,
+              pdfDocument.filterFactory,
```
Comment (Snuffleupagus) [inline web/pdf_viewer.js:850]: How about we simply pass in the `pdfDocument` reference instead now, and let the Editor access the properties/methods it needs?

File: web/viewer.css [hunk 6]
```diff
@@ -582,6 +583,11 @@ body {
   background-color: var(--toolbar-bg-color);
 }
 
+#editorStampParamsToolbar {
+  inset-inline-end: 96px;
+  background-color: var(--toolbar-bg-color);
+}
+
```
Comment (Snuffleupagus) [inline web/viewer.css:590]: These rules looks unused, can't we wait with adding this until it's actually needed?

File: web/viewer.html [hunk 7]
```diff
@@ -330,10 +330,13 @@
                 <div class="verticalToolbarSeparator hiddenMediumView"></div>
 
                 <div id="editorModeButtons" class="splitToolbarButton toggled" role="radiogroup">
-                  <button id="editorFreeText" class="toolbarButton" disabled="disabled" title="Text" role="radio" aria-checked="false" aria-controls="editorFreeTextParamsToolbar" tabindex="34" data-l10n-id="editor_free_text2">
+                  <button id="editorStamp" class="toolbarButton" hidden="true" disabled="disabled" title="Image" role="radio" aria-checked="false" aria-controls="editorStampParamsToolbar" tabindex="34" data-l10n-id="editor_stamp">
```
Comment (Snuffleupagus) [inline web/viewer.html:333]: Should we actually reference a non-existent DOM element here?
```suggestion
                  <button id="editorStamp" class="toolbarButton" hidden="true" disabled="disabled" title="Image" role="radio" aria-checked="false" tabindex="34" data-l10n-id="editor_stamp">
```

File: web/viewer.js [hunk 8]
```diff
@@ -36,6 +36,13 @@ window.PDFViewerApplication = PDFViewerApplication;
 window.PDFViewerApplicationConstants = AppConstants;
 window.PDFViewerApplicationOptions = AppOptions;
 
+if (AppOptions.get("enableStampEditor") === true) {
+  const editorStampButton = document.getElementById("editorStamp");
+  if (editorStampButton) {
+    editorStampButton.hidden = false;
+  }
+}
+
```
Comment (Snuffleupagus) [inline web/viewer.js:45]: Please move into the following code instead https://github.com/mozilla/pdf.js/blob/8b50836d76bbfd33f203887f4ea431e23f0344e4/web/app.js#L561-L562

**Comment by Snuffleupagus** [comment]
*Having tested this a little bit everything seems to work well, however there's one feature that I feel is "missing" here:*
When inserting a image it's probably going to be very common for the user to need to resize it to make it fit a particular space, and most likely you'll want to maintain the "proper" aspect ratio of the image which currently is *very* difficult.
Hence, when resizing the image, could we maintain the aspect ratio *by default* and e.g. add a toggle (in a stampAnnotation-toolbar) to disable that behaviour?

**Comment by marco-c** [comment]
We could do like most other editing software: the corner ones resize while maintaining aspect ratio, the other four resize without maintaining aspect ratio. This would be simpler than adding other things in the UI.

File: src/display/editor/tools.js [hunk 9]
```diff
@@ -59,6 +60,127 @@ class IdManager {
...
+    } catch (e) {
+      console.error(e);
+      data = null;
+    }
+    this.#cache.set(key, data);
+    if (data) {
+      this.#cache.set(data.id, data);
+    }
+    return data;
+  }
```
Comment (Snuffleupagus) [inline src/display/editor/tools.js:143]: There appears to be fair amount of duplication in these methods, can we perhaps use a helper method to avoid that?
```suggestion
  async #get(key, rawData) {
    this.#cache ||= new Map();
    let data = this.#cache.get(key);
    if (data === null) {
      return data;
    }
    if (data?.bitmap) {
      data.refCounter += 1;
      return data;
    }

    try {
      let image;
      if (typeof rawData === "string") {
        const response = await fetch(rawData);
        image = await response.blob();
      } else {
        image = rawData;
      }
      data ||= {
        bitmap: null,
        id: `image_${this.#baseId}_${this.#id++}`,
        file,
        refCounter: 0,
      };
      data.bitmap = await createImageBitmap(file);
      data.refCounter = 1;
    } catch (e) {
      console.error(e);
      data = null;
    }
    this.#cache.set(key, data);
    if (data) {
      this.#cache.set(data.id, data);
    }
    return data;
  }
  
  async getFromFile(file) {
    const { lastModified, name, size, type } = file;
    return this.#get(`${lastModified}_${name}_${size}_${type}`, file);
  }

  async getFromUrl(url) {
    return this.#get(url, url);
  }
```

**Comment by calixteman** [comment]
> We could do like most other editing software: the corner ones resize while maintaining aspect ratio, the other four resize without maintaining aspect ratio. This would be simpler than adding other things in the UI.

Yes it'd be nice but as far as I know it isn't possible to achieve this with basic css/html (see [resize on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/resize)).
So we'd probably need to implement that stuff by ourselves.

**Comment by Snuffleupagus** [comment]
> > We could do like most other editing software: the corner ones resize while maintaining aspect ratio, the other four resize without maintaining aspect ratio. This would be simpler than adding other things in the UI.
> 
> Yes it'd be nice but as far as I know it isn't possible to achieve this with basic css/html (see [resize on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/resize)). So we'd probably need to implement that stuff by ourselves.

In that case, how about we simply *maintain* the original aspect ratio when resizing stamp-images[1] and worry about "arbitrary" resizing later (in a follow-up)?

---
[1] Looking at the Ink-editor, it only allows resizing with maintained aspect ratio.

**Comment by marco-c** [comment]
I agree with that idea, seems more useful than arbitrary resizing. We can then ask UX for their opinion.

File: src/display/editor/tools.js [hunk 10]
```diff
@@ -59,6 +60,112 @@ class IdManager {
...
+
+  #cache = null;
+
+  async #get(key, rawData) {
+    this.#cache ||= new Map();
+    let data = this.#cache.get(key);
+    if (data === null) {
+      return data;
+    }
+    if (data?.bitmap) {
```
Comment (Snuffleupagus) [inline src/display/editor/tools.js:84]: Looking at similar code in the `getFromId`-method, could we perhaps simplify this a tiny bit?
```suggestion
    if (!data) {
      return null;
    }
    if (data.bitmap) {
```

File: src/display/editor/tools.js [hunk 11]
```diff
@@ -441,14 +552,16 @@ class AnnotationEditorUIManager {
...
-  constructor(container, eventBus, annotationStorage) {
+  constructor(container, eventBus, pdfDocument, pageColors) {
     this.#container = container;
     this.#eventBus = eventBus;
     this.#eventBus._on("editingaction", this.#boundOnEditingAction);
     this.#eventBus._on("pagechanging", this.#boundOnPageChanging);
     this.#eventBus._on("scalechanging", this.#boundOnScaleChanging);
     this.#eventBus._on("rotationchanging", this.#boundOnRotationChanging);
-    this.#annotationStorage = annotationStorage;
+    this.#annotationStorage = pdfDocument?.annotationStorage;
```
Comment (Snuffleupagus) [inline src/display/editor/tools.js:562]: Given the line just below, we can probably access this directly?
```suggestion
    this.#annotationStorage = pdfDocument.annotationStorage;
```

File: src/display/editor/tools.js [hunk 12]
```diff
@@ -472,6 +585,19 @@ class AnnotationEditorUIManager {
     this.#commandManager.destroy();
   }
 
+  get hcmFilter() {
+    return shadow(
+      this,
+      "hcmFilter",
+      this.#filterFactory && this.#pageColors
```
Comment (Snuffleupagus) [inline src/display/editor/tools.js:592]: It shouldn't be possible for the `filterFactory` to be undefined here, since we're getting that from the `pdfDocument`-instance in the constructor now.
```suggestion
      this.#pageColors
```

File: web/annotation_editor_layer_builder.css [hunk 13]
```diff
@@ -80,18 +81,26 @@
...
+  overflow: auto;
+}
+
+.annotationEditorLayer .freeTextEditor {
   padding: calc(var(--freetext-padding) * var(--scale-factor));
   resize: none;
   width: auto;
   height: auto;
-  z-index: 1;
   transform-origin: 0 0;
```
Comment (Snuffleupagus) [inline web/annotation_editor_layer_builder.css:102]: This line looks unnecessary now, given the rules in https://github.com/mozilla/pdf.js/pull/16585/files#diff-52f5d77845bc000fab73ee0756ed15ce132e88c1893bff5a2268402ea99599aaR84

File: web/app.js [hunk 14]
```diff
@@ -560,6 +560,13 @@ const PDFViewerApplication = {
 
     if (appConfig.annotationEditorParams) {
       if (annotationEditorMode !== AnnotationEditorType.DISABLE) {
+        if (AppOptions.get("enableStampEditor") === true) {
+          const editorStampButton = document.getElementById("editorStamp");
+          if (editorStampButton) {
+            editorStampButton.hidden = false;
+          }
+        }
+
```
Comment (Snuffleupagus) [inline web/app.js:569]: We should already have a reference to the DOM element, so please use that here :-)
Furthermore, the Stamp-editor uses `OffScreenCanvas` unconditionally so we *also* need to check that that's supported before displaying the button.
```suggestion
        const editorStampButton = appConfig.toolbar?.editorStampButton;
        if (
          editorStampButton &&
          AppOptions.get("enableStampEditor") &&
          AppOptions.get("isOffscreenCanvasSupported") &&
          FeatureTest.isOffscreenCanvasSupported
        ) {
          editorStampButton.hidden = false;
        }
```

File: src/display/editor/stamp.js [hunk 15]
```diff
@@ -0,0 +1,411 @@
...
+
+  #bitmapUrl = null;
+
+  #canvas = null;
+
+  #observer = null;
+
+  #resizeTimeoutId = null;
+
+  static _type = "stamp";
```
Comment (Snuffleupagus) [inline src/display/editor/stamp.js:38]: *You've probably already thought about this, but:* Once this lands, please don't forget to add the new "stamp"-type to the relevant telemetry code on the platform side.
 - https://searchfox.org/mozilla-central/rev/9a4666e63199bd1bcfc9095f6efec3488c358458/toolkit/components/pdfjs/content/PdfJsTelemetry.sys.mjs#25
 - https://searchfox.org/mozilla-central/rev/9a4666e63199bd1bcfc9095f6efec3488c358458/toolkit/components/pdfjs/metrics.yaml#17-21

**Review by Snuffleupagus — COMMENTED** [review]
I've not really had time to look at the `src/display/editor/stamp.js` file yet, but will try to do that tomorrow.

File: src/display/editor/tools.js (hunk 10 above)
Comment (calixteman) [reply src/display/editor/tools.js]: When data is null it means that we already tryed to load the image but for any reasons it failed.

File: src/display/editor/stamp.js (hunk 15 above)
Comment (calixteman) [reply src/display/editor/stamp.js:38]: Yep it's on my todo.

File: src/display/editor/stamp.js [hunk 16]
```diff
@@ -0,0 +1,411 @@
...
+
+  static updateDefaultParams(_type, _value) {}
+
+  static get defaultPropertiesToUpdate() {
+    return [];
+  }
+
+  get propertiesToUpdate() {
+    return [];
+  }
```
Comment (Snuffleupagus) [inline src/display/editor/stamp.js:55]: Would it perhaps make sense to move dummy-methods such as these into the `AnnotationEditor` base-class instead?

File: src/display/editor/stamp.js [hunk 17]
```diff
@@ -0,0 +1,411 @@
...
+      return;
+    }
+
+    const input = document.createElement("input");
+    input.type = "file";
+    input.accept = "image/*";
+    this.#bitmapPromise = new Promise(resolve => {
+      input.addEventListener("change", async () => {
+        this.#bitmapPromise = null;
+        if (input.files.length === 0) {
```
Comment (Snuffleupagus) [inline src/display/editor/stamp.js:93]: Looking at similar code in the GENERIC viewer, should we perhaps guard this as follows to prevent any issues?
```suggestion
        if (!input.files || input.files.length === 0) {
```

File: src/display/editor/stamp.js [hunk 18]
```diff
@@ -0,0 +1,411 @@
...
+    if (this.width) {
+      width = this.width * pageWidth;
+      height = this.height * pageHeight;
+    } else if (width > 0.75 * pageWidth || height > 0.75 * pageHeight) {
+      // If the the image is too big compared to the page dimensions
+      // (more than 75%) then we scale it down.
+      const factor = Math.min(
+        (0.75 * pageWidth) / width,
+        (0.75 * pageHeight) / height
+      );
```
Comment (Snuffleupagus) [inline src/display/editor/stamp.js:208]: Please change this (percentage) value into named constant instead.

File: src/display/editor/stamp.js [hunk 19]
```diff
@@ -0,0 +1,411 @@
...
+      }
+      if (newHeight > 2 * height) {
+        newHeight =
+          newHeight >= 16384
+            ? Math.floor(newHeight / 2) - 1
+            : Math.ceil(newHeight / 2);
+      }
+
+      const offscreenCanvas = new OffscreenCanvas(newWidth, newHeight);
+      const offscreenCtx = offscreenCanvas.getContext("2d");
```
Comment (Snuffleupagus) [inline src/display/editor/stamp.js:277]: Maybe slightly shorter names?
```suggestion
      const offscreen = new OffscreenCanvas(newWidth, newHeight);
      const ctx = offscreenCanvas.getContext("2d");
```

File: src/display/editor/stamp.js [hunk 20]
```diff
@@ -0,0 +1,411 @@
...
+    if (toUrl) {
+      // We convert to a data url because it's sync and the url can live in the
+      // clipboard.
+      const canvas = document.createElement("canvas");
+      canvas.width = this.#bitmap.width;
+      canvas.height = this.#bitmap.height;
+      const ctx = canvas.getContext("2d");
+      const { width, height } = this.#bitmap;
+      canvas.width = width;
+      canvas.height = height;
```
Comment (Snuffleupagus) [inline src/display/editor/stamp.js:328]: Wait, aren't we setting the canvas width/height to the same values *twice* here?
```suggestion
      const ctx = canvas.getContext("2d");
      const { width, height } = this.#bitmap;
      canvas.width = width;
      canvas.height = height;
```

File: src/display/editor/stamp.js [hunk 21]
```diff
@@ -0,0 +1,411 @@
...
+    this.width = width / parentWidth;
+    this.height = height / parentHeight;
+    this.setDims(width, height);
+    if (this.#resizeTimeoutId !== null) {
+      clearTimeout(this.#resizeTimeoutId);
+    }
+    this.#resizeTimeoutId = setTimeout(() => {
+      this.#resizeTimeoutId = null;
+      this.#drawBitmap(width, height);
+    }, 200);
```
Comment (Snuffleupagus) [inline src/display/editor/stamp.js:247]: Why do we need the timeout? Please add a comment.

File: web/app.js [hunk 22]
```diff
@@ -560,6 +560,18 @@ const PDFViewerApplication = {
...
+          if (
+            editorStampButton &&
+            AppOptions.get("enableStampEditor") &&
+            AppOptions.get("isOffscreenCanvasSupported") &&
+            FeatureTest.isOffscreenCanvasSupported
+          ) {
+            editorStampButton.hidden = false;
+          }
+        }
+
```
Comment (Snuffleupagus) [inline web/app.js:574]: There's some duplication here, so we should be able to remove the outer most `if`-check now.
```suggestion
        const editorStampButton = appConfig.toolbar?.editorStampButton;
        if (
          editorStampButton &&
          AppOptions.get("enableStampEditor") &&
          AppOptions.get("isOffscreenCanvasSupported") &&
          FeatureTest.isOffscreenCanvasSupported
        ) {
          editorStampButton.hidden = false;
        }
 ```

**Review by Snuffleupagus — APPROVED** [review]
r=me, with the final comments addressed and passing tests; thank you!
