### PR TITLE
[api-minor] Use an icc profile for converting CMYK to RGB

### LINKED ISSUE #2218: Broken PDF: Valve employee handbook
http://www.valvesoftware.com/company/Valve_Handbook_LowRes.pdf
- ~~Page backgrounds do not render~~
- Chapter title pages (p. 5, right side), images (p. 6), and block text backgrounds (p. 5, left side) are off-color
- ~~Transparent images hide the text behind them (p. 8, left side)~~
- ~~Timeline renders, then reverts to white page (pp. 15-17)~~
- ~~High memory usage (see #3328 for details).~~

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
I'd expect lots of small movement all over the ref-tests with this patch, but I'd guess the explanation is that you forgot to add `iccUrl` in the https://github.com/mozilla/pdf.js/blob/master/test/driver.js file?

**Comment by calixteman** [comment]
> I'd expect lots of small movement all over the ref-tests with this patch, but I'd guess the explanation is that you forgot to add `iccUrl` in the https://github.com/mozilla/pdf.js/blob/master/test/driver.js file?

Yep I was expecting the same and found this oblivion almost 5 minutes ago :)

File: external/iccs/LICENSE
Comment (Snuffleupagus) [inline external/iccs/LICENSE:1]: This file probably shouldn't be empty.

File: gulpfile.mjs
Comment (Snuffleupagus) [inline gulpfile.mjs:1]: The ICC profiles also need to be copied into `gulp dist`, please see https://github.com/mozilla/pdf.js/blob/af89e77124bf9ccf271d27e3d3f619ce5878c7c4/gulpfile.mjs#L2361-L2378

File: src/core/colorspace_utils.js [hunk 1]
```diff
@@ -285,6 +285,11 @@ class ColorSpaceUtils {
   }
 
   static get cmyk() {
+    try {
+      return shadow(this, "cmyk", new CmykICCBasedCS());
+    } catch {
+      warn("CMYK fallback: DeviceCmykCS");
```
Comment (Snuffleupagus) [inline src/core/colorspace_utils.js:291]: Nit: Let's match the actual spec-name.
```suggestion
      warn("CMYK fallback: DeviceCMYK");
```

File: src/display/api.js [hunk 2]
```diff
@@ -269,6 +269,7 @@ function getDocument(src = {}) {
     (typeof PDFJSDev !== "undefined" && PDFJSDev.test("GENERIC") && isNodeJS
       ? NodeCMapReaderFactory
       : DOMCMapReaderFactory);
+  const iccUrl = getFactoryUrlProp(src.iccUrl);
```
Comment (Snuffleupagus) [inline src/display/api.js:272]: This needs a JSDoc comment, similar to the other factory-urls.

File: src/display/api.js [hunk 3]
```diff
@@ -418,6 +419,7 @@ function getDocument(src = {}) {
       useWasm,
       useWorkerFetch,
       cMapUrl,
+      iccUrl,
```
Comment (Snuffleupagus) [inline src/display/api.js:422]: This property should have a default entry in the following structure as well.
https://github.com/mozilla/pdf.js/blob/af89e77124bf9ccf271d27e3d3f619ce5878c7c4/src/core/evaluator.js#L84-L99

File: src/core/icc_colorspace.js [hunk 4]
```diff
@@ -152,4 +152,21 @@ class IccColorSpace extends ColorSpace {
...
+class CmykICCBasedCS extends IccColorSpace {
+  static #iccUrl;
+
+  constructor() {
+    const filename = "CGATS001Compat-v2-micro.icc";
+    const xhr = new XMLHttpRequest();
+    xhr.open("GET", `${CmykICCBasedCS.#iccUrl}${filename}`, false);
+    xhr.responseType = "arraybuffer";
+    xhr.send(null);
+    super(new Uint8Array(xhr.response), 4);
```
Comment (Snuffleupagus) [inline src/core/icc_colorspace.js:164]: This class will currently have `this.name === "ICCBased"` set, which is "wrong" and will most likely cause bugs since we in various places (e.g. in the `src/core/image.js` file) use the `name`-field to check what type of ColorSpace something is.

Most likely you want something like the following to ensure that this class will still be treated like CMYK as expected.
```suggestion
    xhr.send(null);
    
    super(new Uint8Array(xhr.response), 4);
    this.name = "DeviceCMYK";
```

**Review by Snuffleupagus — COMMENTED** [review]
Leaving a couple of quick comments, especially the `CmykICCBasedCS.prototype.name` field is something that I cannot tell at a glance if it's correct.

File: src/core/jpg.js [hunk 5]
```diff
@@ -1469,140 +1342,12 @@ class JpegImage {
...
-        y *
-          (5.068882914068769e-7 * y +
-            0.0017778369011375071 * k -
-            0.7591454649749609) -
-        k * (0.0003435319965105553 * k + 0.7063770186160144);
-    }
-    // Ensure that only the converted RGB data is returned.
-    return data.subarray(0, offset);
+    ColorSpaceUtils.cmyk.getRgbBuffer(data, 0, data.length / 4, data, 0, 8, 0);
+    return data.subarray(0, (data.length / 4) * 3);
```
Comment (Snuffleupagus) [inline src/core/jpg.js:1346]: Optional nit:
```suggestion
    const count = data.length / 4;
    ColorSpaceUtils.cmyk.getRgbBuffer(data, 0, count, data, 0, 8, 0);
    return data.subarray(0, count * 3);
```

**Review by Snuffleupagus — APPROVED** [review]
While there's a bunch of movement in the ref-tests, this looks like an *overall improvement* when comparing with the rendering in Adobe Reader.

r=me, thank you.
