### PR TITLE
[api-minor] Use a local font or fallback on an embedded one (if it exists) for non-embedded fonts (bug 1766039)

### LINKED ISSUE #13176: Overlapping glyphs in Times New Roman substitute on Ubuntu 18.04 LTS
Attach (recommended) or Link to PDF file here: https://www.cityofpaloalto.org/civicax/filebank/documents/8700

Configuration:
- Web browser and its version: Firefox 87.0
- Operating system and its version: Ubuntu 18.04.5 LTS
- PDF.js version: v2.7.368 to v2.8.322
- Is a browser extension: No

Steps to reproduce the problem:
1. Create a fresh installation of Ubuntu 18.04 LTS without any additional fonts.
2. Download and build any version of pdf.js no older than 45d9ab6.
2. Download the PDF and open it using `web/viewer.html`.

What is the expected behavior? (add screenshot) The document should render with an appropriate sans-serif font, since Ubuntu does not have Times New Roman by default. The correct behavior occurs on Ubuntu 20.04 LTS; the first page of the document is shown in [this screenshot](https://user-images.githubusercontent.com/7880963/113496333-ace42380-94c6-11eb-9559-8698fae2cc28.png).

What went wrong? (add screenshot) On Ubuntu 18.04 LTS, the glyphs overlap (or at least connect), rendering the text difficult to read. This is illustrated in [this screenshot](https://user-images.githubusercontent.com/7880963/113496320-7908fe00-94c6-11eb-898f-4ef09a58ee1a.png). Note how the letters are placed identically in the two images; however, the substitute font in 18.04 has a higher weight and ex-height, causing this issue.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### LINKED ISSUE #14843: Replace most Foxit fonts with Liberation fonts
As seen in https://github.com/mozilla/pdf.js/pull/12726#issuecomment-853375348 the Foxit fonts are not "complete" enough, which leads to broken rendering in some PDF documents.
(This is one reason that we're not always loading the standard font data-files, another being that doing so affects performance according to the discussion in that PR.)

Furthermore, as suggested and agreed upon in https://github.com/mozilla/pdf.js/pull/12726#issuecomment-854841277, https://github.com/mozilla/pdf.js/pull/12726#issuecomment-854916134, and https://github.com/mozilla/pdf.js/pull/12726#issuecomment-854975634, the idea was to replace the Foxit fonts (except `FoxitSymbol.pfb` and `FoxitDingbats.pfb`) with the more complete Liberation fonts instead.

Note that we already have ship *some* Liberation fonts, for use with XFA-documents, and that we thus currently have some duplication in the standard font files. Hence we should replace the `FoxitFixed...` and `FoxitSerif...` fonts with their Liberation equivalents.

/cc @calixteman

### PR DESCRIPTION
**Pull request by calixteman**
- Replace FoxitSans with LiberationSans: LiberationSans is already there (for XFA) and we can use it as a good replacement of FoxitSans.
- For now we just try to substitue standard fonts, the strategy is the following:
  * we try to find a font locally from a hardcoded list;
  * if it fails then we use Liberation as fallback (only for Helvetica for the moment);
  * else we just fallback on the system serif/sansserif/monospace font.

### CODE REVIEW

File: src/core/evaluator.js [hunk 1]
```diff
@@ -402,6 +403,25 @@ class PartialEvaluator {
     return data;
   }
 
+  loadFontInDocument(name) {
+    const cachedData = this.standardFontDataCache.get(name);
+    if (cachedData) {
+      return cachedData;
+    }
```
Comment (Snuffleupagus) [inline src/core/evaluator.js:410]: Sorry, but I really don't see how it's generally correct/safe to re-use that cache here!

A new `this.fetchStandardFontData`-call, from *another* PDF document font, may now end up returning *completely unexpected* data.
Please introduce a new cache for this use-case, following the same patterns as this cache, to avoid any issues now or later; I'd suggest calling it `FontSubstitutionCache`.

File: src/core/evaluator.js [hunk 2]
```diff
@@ -402,6 +403,25 @@ class PartialEvaluator {
...
+    const subst = getFontSubstitution(
```
Comment (Snuffleupagus) [inline src/core/evaluator.js:411]: Please make sure that this code cannot accidentally run in e.g. Node.js environments:
```suggestion
    if (!this.options.useSystemFonts) {
      return null;
    }
    const subst = getFontSubstitution(
```

File: src/core/evaluator.js [hunk 3]
```diff
@@ -422,6 +442,10 @@ class PartialEvaluator {
       filename = standardFontNameToFileName[name];
     let data;
 
+    if (!filename) {
+      return null;
+    }
+
```
Comment (Snuffleupagus) [inline src/core/evaluator.js:448]: What is this code for, since that's not immediately obvious to me?
If this is indeed necessary, it requires a very good comment explaining things.

File: src/core/evaluator.js [hunk 4]
```diff
@@ -402,6 +403,25 @@ class PartialEvaluator {
...
+      this.options.standardFontDataUrl,
+      name
+    );
+    if (!subst) {
+      return null;
+    }
+    const loadedName = subst.args[0];
+    this.standardFontDataCache.set(name, loadedName);
+    this.handler.send("LoadFontInDocument", subst.args);
+    return subst.cssString;
```
Comment (Snuffleupagus) [inline src/core/evaluator.js:422]: Sorry, but I *really* don't like all of the special-handling introduced here and *especially* on the main-thread for this feature!

Why can't we just include/export this data as a regular property on the font, and then handle that on the main-thread instead?
The following `diff` obviously won't work as-is, but to try and illustrate my point of re-using our existing coding-patterns:
```diff
diff --git a/src/display/font_loader.js b/src/display/font_loader.js
index 307c68838..5a5ae0695 100644
--- a/src/display/font_loader.js
+++ b/src/display/font_loader.js
@@ -73,11 +73,15 @@ class FontLoader {

   async bind(font) {
     // Add the font to the DOM only once; skip if the font is already loaded.
-    if (font.attached || font.missingFile) {
+    if (font.attached || font.missingFile || !font.cssFontFamily) {
       return;
     }
     font.attached = true;

+    if (font.cssFontFamily) {
+      return this.loadFont(font.cssFontFamily); // <-- This calls your new method.
+    }
+
     if (this.isFontLoadingAPISupported) {
       const nativeFontFace = font.createNativeFontFace();
       if (nativeFontFace) {
```

The advantage of doing something along these lines is that we don't need to make any changes in the `src/display/api.js` file.

File: src/display/font_loader.js [hunk 5]
```diff
@@ -47,6 +47,13 @@ class FontLoader {
     this._document.fonts.add(nativeFontFace);
   }
 
+  removeNativeFontFace(nativeFontFace) {
+    this.nativeFontFaces = this.nativeFontFaces.filter(
+      x => x !== nativeFontFace
+    );
```
Comment (Snuffleupagus) [inline src/display/font_loader.js:53]: Could we possibly change `this.nativeFontFaces` into a `Set` instead, to avoid having to do this?

File: src/display/font_loader.js [hunk 6]
```diff
@@ -71,6 +78,37 @@ class FontLoader {
     }
   }
 
+  async loadFont(args) {
```
Comment (Snuffleupagus) [inline src/display/font_loader.js:81]: Given that this code shouldn't be reached if `disableFontFace=true` is set, as far as I can tell, can we please assert that?
```suggestion
  async loadFont(args) {
    assert(!this.disableFontFace, "loadFont shouldn't be called when `disableFontFace` is set.")
```

File: web/app_options.js [hunk 7]
```diff
@@ -210,7 +210,9 @@ const defaultOptions = {
   cMapUrl: {
     /** @type {string} */
     value:
-      typeof PDFJSDev === "undefined" ? "../external/bcmaps/" : "../web/cmaps/",
+      typeof PDFJSDev !== "undefined" && PDFJSDev.test("MOZCENTRAL")
+        ? "resource://pdf.js/web/cmaps/"
+        : "../external/bcmaps/",
```
Comment (Snuffleupagus) [inline web/app_options.js:215]: Here, and below, this is breaking the GENERIC viewer. Please follow the same pattern that you introduced in https://github.com/mozilla/pdf.js/blob/797f8d3dca5e0770c83788b3b65387884031caa0/web/app_options.js#L290-L299

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]
I'd really like us to create a new release *before* moving forward with this patch (or any other standard-font data related ones).

File: src/core/evaluator.js (hunk 4 above)
Comment (calixteman) [reply src/core/evaluator.js:422]: My idea was to send the load message as soon as possible on the main thread.
But when looking more in details it seems that there is not that much time.

File: src/display/font_loader.js [hunk 8]
```diff
@@ -71,13 +79,61 @@ class FontLoader {
...
+    );
+
+    const { loadedName, src, style } = info;
+    if (this.#systemFonts.has(src)) {
+      return;
+    }
+    this.#systemFonts.add(src);
+    if (this.isFontLoadingAPISupported) {
+      const fontFace = new FontFace(loadedName, src, style);
+      this.addNativeFontFace(fontFace);
```
Comment (Snuffleupagus) [inline src/display/font_loader.js:95]: Doesn't this call already add the font to the document?
Can't we simply `await fontFace.loaded;` instead just below, similar to what we do elsewhere in this file?

File: src/display/font_loader.js [hunk 9]
```diff
@@ -71,13 +79,61 @@ class FontLoader {
...
+    }
+  }
+
+  get readyPromise() {
+    if (!this.isFontLoadingAPISupported || !this._document) {
+      return Promise.resolve();
+    }
+    return this._document.fonts.ready;
+  }
+
```
Comment (Snuffleupagus) [inline src/display/font_loader.js:124]: We shouldn't need this anymore, nor any of the changes in the `src/display/api.js` file, right?

File: src/core/font_substitutions.js [hunk 10]
```diff
@@ -0,0 +1,271 @@
...
+      ultimate: "monospace",
+      baseName: "courier",
+    },
+  ],
+]);
+
+function makeLocal(local) {
+  let append = "";
+  if (!Array.isArray(local)) {
+    append = local.append;
```
Comment (Snuffleupagus) [inline src/core/font_substitutions.js:240]: Can we please add the leading space here, instead of having to remember do that manually at each entry in the list above?
```suggestion
    append = ` ${local.append};
```

File: src/core/font_substitutions.js [hunk 11]
```diff
@@ -0,0 +1,271 @@
...
+
+  const { local, path, style, ultimate, baseName } = substitution;
+  const loadedName = `${docId}_${baseName}`;
+  let src = makeLocal(local);
+  if (path && basePath !== null) {
+    if (basePath.endsWith("/")) {
+      src += `,url(${basePath}${path})`;
+    } else {
+      src += `,url(${basePath}/${path})`;
+    }
```
Comment (Snuffleupagus) [inline src/core/font_substitutions.js:260]: Please note that the API-option is documented as *requiring* a trailing slash, [please see here](https://github.com/mozilla/pdf.js/blob/797f8d3dca5e0770c83788b3b65387884031caa0/src/display/api.js#L185-L186), hence please simplify this as:
```suggestion
    src += `,url(${basePath}${path})`;
```

File: src/core/fonts.js [hunk 12]
```diff
@@ -82,6 +82,7 @@ const EXPORT_DATA_PROPERTIES = [
   "bold",
   "charProcOperatorList",
   "composite",
+  "systemFontInfo",
```
Comment (Snuffleupagus) [inline src/core/fonts.js:85]: Please keep these properties in alphabetical order :-)

File: src/display/api.js [hunk 13]
```diff
@@ -1516,6 +1516,7 @@ class PDFPageProxy {
       useRequestAnimationFrame: !intentPrint,
       pdfBug: this._pdfBug,
       pageColors,
+      fontLoader: this._transport.fontLoader,
```
Comment (Snuffleupagus) [inline src/display/api.js:1519]: None of the changes in this file are necessary now, please revert them.

File: src/display/font_loader.js (hunk 8 above)
Comment (Snuffleupagus) [reply src/display/font_loader.js:95]: It doesn't appear that this suggestion was included in the changes; was it simply incorrect on my part?

Comment (calixteman) [reply src/display/font_loader.js:95]: I thought `await fontFace.load()` was equivalent.
I replaced the `load()` by `loaded` and it just doesn't work.
In reading the `FontFaceSet::add` [specs](https://w3c.github.io/csswg-drafts/css-font-loading/#dom-fontfaceset-add) I don't see anything telling that the font must be loaded when added to the set.
So I'd say that we should call `load()` here and in `bind` function.
Wdyt ?

Comment (Snuffleupagus) [reply src/display/font_loader.js:95]: Strange, since [our existing code](https://github.com/mozilla/pdf.js/blob/797f8d3dca5e0770c83788b3b65387884031caa0/src/display/font_loader.js#L82-L86) clearly works as-is.
Maybe there's a difference between supplying binary font-data vs a URL to a font-file?

Comment (calixteman) [reply src/display/font_loader.js:95]: When we don't have the buffer, the data need to be fetched and it's fundamentally an async operation.
So my feeling is that it makes sense to have such a difference.

Comment (Snuffleupagus) [reply src/display/font_loader.js:95]: Sounds reasonable, I mostly wanted to understand why there's a difference; thank you!

File: src/display/font_loader.js [hunk 14]
```diff
@@ -71,13 +79,54 @@ class FontLoader {
...
+    }
+
+    if (this._document) {
+      const rule =
+        "@font-face { " +
+        `font-family: ${loadedName};` +
+        `src: ${src};` +
+        `font-style: ${style.style};` +
+        `font-weight: ${style.weight}; }`;
+      this.insertRule(rule);
```
Comment (Snuffleupagus) [inline src/display/font_loader.js:114]: Another question, don't we need to add code [like this one](https://github.com/mozilla/pdf.js/blob/797f8d3dca5e0770c83788b3b65387884031caa0/src/display/font_loader.js#L103-L113) here as well to ensure that we actually wait for the font to be loaded in this case too?

Comment (calixteman) [reply src/display/font_loader.js:114]: I added the code to wait for the font loading... but it doesn't work.
I suppose that the font we create to check its availability is created before the one loaded from `src`.
What's the context of not having font loading api ?

File: src/display/font_loader.js [hunk 15]
```diff
@@ -71,19 +80,54 @@ class FontLoader {
...
+      return;
+    }
+
     if (this.isFontLoadingAPISupported) {
       const nativeFontFace = font.createNativeFontFace();
       if (nativeFontFace) {
         this.addNativeFontFace(nativeFontFace);
         try {
-          await nativeFontFace.loaded;
+          await nativeFontFace.load();
```
Comment (Snuffleupagus) [inline src/display/font_loader.js:130]: Given the size/scope of this patch, I'd probably suggest that we don't add any unnecessary risk by not making this "unrelated" change here.

Comment (Snuffleupagus) [reply src/display/font_loader.js:130]: Looking at https://developer.mozilla.org/en-US/docs/Web/API/FontFace/load it contains the following:
> If the source for the font face was specified as binary data, or the font [status](https://developer.mozilla.org/en-US/docs/Web/API/FontFace/status) property of the font face is anything other than unloaded, then this method does nothing.

**Comment by Snuffleupagus** [comment]
I've not looked at all of the changes, however one thing that immediately jumped out at me is the movement in the following test-cases:
https://github.com/mozilla/pdf.js/blob/4931f293ebc868d0b94f78dace1df84d125086c5/test/test_manifest.json#L2895-L2909

Given that they *explicitly* set `useSystemFonts = false`, there shouldn't be any changes in those tests!?

**Comment by Snuffleupagus** [comment]
*Another quick find:* Looking at e.g. the `artofwar` changes I don't think that this patch handles ArialBlack fonts correctly, since "black" fonts should have a larger font-weight than a bold font.

**Comment by calixteman** [comment]
> I've not looked at all of the changes, however one thing that immediately jumped out at me is the movement in the following test-cases:
> 
> https://github.com/mozilla/pdf.js/blob/4931f293ebc868d0b94f78dace1df84d125086c5/test/test_manifest.json#L2895-L2909
> 
> Given that they _explicitly_ set `useSystemFonts = false`, why is there movement in those cases!?
> 
> _Edit:_ Oh, is this perhaps because we've changed from Foxit to LiberationSans fonts?

Yep exactly.

**Comment by calixteman** [comment]
In most of the case the differences are dues to the fact we chose an other font.
Normally, the font we select should have almost the same metrics but can look different.
I think metrics compatibility is more important than overall aspect: so for it's fine.
The ArialBlack issue should be fixed in the last version of the patch at least on Windows because I didn't find a metric-compatible font on other OSes.

File: src/core/font_substitutions.js [hunk 16]
```diff
@@ -0,0 +1,420 @@
...
+  weight: "bold",
+};
+const ITALIC = {
+  style: "italic",
+  weight: "normal",
+};
+const BOLDITALIC = {
+  style: "italic",
+  weight: "bold",
+};
```
Comment (Snuffleupagus) [inline src/core/font_substitutions.js:31]: That's a nice way to reduce duplication below!

File: src/core/font_substitutions.js [hunk 17]
```diff
@@ -0,0 +1,420 @@
...
+  let prependedPaths = "";
+  if (prepend) {
+    prependedPaths = prepend.map(name => `local(${name})`).join(",") + ",";
+  }
+  return (
+    prependedPaths + local.map(name => `local(${name}${append})`).join(",")
+  );
+}
+
+function getFontSubstitution(docId, basePath, baseFontName, standardFontName) {
```
[the remark this answers is not in the document]
Comment (calixteman) [reply src/core/font_substitutions.js]: Is it better now ?

[the remark this answers is not in the document]
Comment (Snuffleupagus) [reply src/core/font_substitutions.js]: The comments help, thank you!

File: src/core/font_substitutions.js [hunk 18]
```diff
@@ -0,0 +1,454 @@
...
+  let substitution = substitutionMap.get(baseFontName);
+  if (!substitution) {
+    // If not, check if we've a substitution for the standard font.
+    substitution = substitutionMap.get(standardFontName);
+    mustAddBaseFont = true;
+  }
+
+  const loadedName = `${idFactory.getDocId()}_sf_${idFactory.createFontId()}`;
+  // If the baseFontName is not valid we don't want to use it.
+  if (!substitution && validateFontName(baseFontName)) {
```
Comment (Snuffleupagus) [inline src/core/font_substitutions.js:398]: Can't this possibly lead to an error below, if there's no substitution *and* the `baseFontName` is invalid?
```suggestion
  if (!substitution) {
    if (!validateFontName(baseFontName)) {
      return null;
    }
```

File: src/core/font_substitutions.js [hunk 19]
```diff
@@ -0,0 +1,454 @@
...
+    // Maybe we'll be lucky and the OS will have the font.
+    const bold = /bold/gi.test(baseFontName);
+    const italic = /oblique|italic/gi.test(baseFontName);
+    const style =
+      (bold && ((italic && BOLDITALIC) || BOLD)) ||
+      (italic && ITALIC) ||
+      NORMAL;
```
Comment (Snuffleupagus) [inline src/core/font_substitutions.js:405]: While being a tiny bit more code, this would be slightly easier to read at a glance if we format it as follows.
```suggestion
      (bold && italic && BOLDITALIC) ||
      (bold && BOLD)) ||
      (italic && ITALIC) ||
      NORMAL;
```

Comment (calixteman) [reply src/core/font_substitutions.js]: I did that too but I realized that my version has only 2 checks to go to NORMAL when the other one has 3.
But I completely agree with you about the readability so let's go for it.

**Comment by timvandermeij** [comment]
> I'd really like us to create a new release before moving forward with this patch (or any other standard-font data related ones).

The release is done now; interestingly while the `pdfjs-dist` push still failed the NPM push worked even though we thought it wouldn't due to the bot switch (but maybe the old bot picked it up or so). I think we can leave `pdfjs-dist` as-is for now since it hasn't been updated for a number of releases now and instead work on the new release process, especially since all other steps for this release worked.

**Comment by Snuffleupagus** [comment]
There seem to be a number of things I'd classify as outright (or potential) regressions, some example (there's probably more):
 - `firefox-issue5801`, on Windows, now look too "light". It seems that we're (still) not handling ArialBold entirely correctly?
 - `firefox-standard_fonts_system_fonts` (multiple pages), on Linux, the fonts no longer look like Courier. Maybe we're specifying local font-names candidates in the correct order?
 - `firefox-standard_fonts_no_system_fonts` (multiple pages), on Windows and Linux, the Helvetica fonts changed. Was that actually expected, or are the local font-name candidates in the wrong order?
 - `firefox-standard_fonts_no_system_fonts-page8` or `firefox-standard_fonts_main_thread_fetch-page8`, on Windows and Linux, the fonts no longer look bold.

File: src/core/font_substitutions.js [hunk 20]
```diff
@@ -0,0 +1,458 @@
...
+  ],
+  [
+    "Helvetica-BoldOblique",
+    {
+      local: {
+        alias: "Helvetica",
+        append: "Bold Italic",
+      },
+      path: "LiberationSans-BoldItalic.ttf",
+      style: ITALIC,
```
Comment (Snuffleupagus) [inline src/core/font_substitutions.js:151]: This probably explains a test-failure, since it should be:
```suggestion
      style: BOLDITALIC,
```

**Comment by calixteman** [comment]
> There seem to be a number of things I'd classify as outright (or potential) regressions, some examples (there's probably more):
> 
>     * `firefox-issue5801`, on Windows, now look too "light". It seems that we're (still) not handling ArialBlack entirely correctly?
> 

We've `ArialBlack,Bold` and I thought we'll only have a dash instead of a comma

>     * `firefox-standard_fonts_system_fonts` (multiple pages), on Linux, the fonts no longer look like Courier. Maybe we're specifying local font-names candidates in the wrong order?

With my linux setup (Fedora), the first found font is `Liberation Mono` and according to https://wiki.archlinux.org/title/Metric-compatible_fonts  from a metric pov it's the right substitution.
From my pov, metrics compat is a way more important than the visual compat. If people are unhappy they've to embed their font.
But at least the text should be perfectly readable...

File: src/core/font_substitutions.js [hunk 21]
```diff
@@ -0,0 +1,458 @@
...
+ * @param {String} standardFontName The standard font name to use if the base
+ *   font is not available.
+ * @returns an Object with the CSS, the loaded name, the src and the style.
+ */
+function getFontSubstitution(
+  idFactory,
+  localFontPath,
+  baseFontName,
+  standardFontName
+) {
```
Comment (Snuffleupagus) [inline src/core/font_substitutions.js:385]: Given the `ArialBlack,Bold` problem mentioned in https://github.com/mozilla/pdf.js/pull/16363#issuecomment-1540787068, should we perhaps just normalize the name here to avoid having to add loads of alias-entries in the font-substitution map?
```suggestion
) {
  baseFontName = normalizeFontName(baseFontName);
```
Which would be consistent with how we handle names of non-embedded fonts elsewhere see also https://github.com/mozilla/pdf.js/blob/1a2e787e47cfb6178f5eeedc608fd9bd571cf0b3/src/core/fonts_utils.js#L183-L185

Comment (calixteman) [reply src/core/font_substitutions.js:385]: Yep, I do almost the same but with a small variation, tell me wdyt about ?

I found a cache issue in `font_loader`, consequently I removed `#systemFont` set.
The key was only based on `src` which wasn't a good idea because if two fonts have the same `src` (and even the same style) then g_d0_f2 was not loaded (when g_d0_f1 was) and in canvas::setFont we're using g_d0_f2 which is not defined.

In my work on refactoring the text layer I disabled the font cache clearing because we need to have the font for the text layer.

Comment (Snuffleupagus) [reply src/core/font_substitutions.js:385]: > Yep, I do almost the same but with a small variation, tell me wdyt about ?

Do we actually *need* to diverge here, since that small inconsistency feels like it could potentially cause issues (or at least surprises) later on?

Please note that elsewhere when dealing with non-embedded fonts we're using `normalizeFontName`, see e.g. https://github.com/mozilla/pdf.js/blob/1a2e787e47cfb6178f5eeedc608fd9bd571cf0b3/src/core/standard_fonts.js#L883-L887 and https://github.com/mozilla/pdf.js/blob/1a2e787e47cfb6178f5eeedc608fd9bd571cf0b3/src/core/fonts.js#L1134-L1139

Comment (calixteman) [reply src/core/font_substitutions.js:385]: I find a bit strange to remove the spaces since it could lead to concatenate some words and then create a new one.
That said I'm fine with using normalizeFontName.

Comment (Snuffleupagus) [reply src/core/font_substitutions.js:385]: If using `normalizeFontName` works I'd really prefer a that, since a *consistent* handling of non-embedded font names should limit surprises/problems later.

File: src/core/font_substitutions.js [hunk 22]
```diff
@@ -0,0 +1,464 @@
...
+  let mustAddBaseFont = false;
+
+  // It's possible to have a font name with spaces, commas or dashes, hence we
+  // just replace them by a dash.
+  baseFontName = baseFontName
+    .replaceAll(/[\s\-,_]+/g, "-")
+    .replace(/Bold-Italic|Italic-Bold/, "BoldItalic");
```
Comment (Snuffleupagus) [inline src/core/font_substitutions.js:392]: Looking at `issue7835` it seems that we also need to handle `Arial-Black` as well, looking at PR #7839 we probably need to add a `replace("Arial-Black"`, "ArialBlack")` here as well?

**Comment by Snuffleupagus** [comment]
In addition to the previously mentioned bug, does this PR perhaps fix (or improve) any of the following issues?
 - #10878
 - #11840
 - #13176

**Comment by calixteman** [comment]
> Looking at the Windows results in [#16363 (comment)](https://github.com/mozilla/pdf.js/pull/16363#issuecomment-1541794111), there seem to be a couple of regressions:
> 
>     * `firefox-artofwar-page158` is missing a piece of italic text in the middle of the page.

I used `Italic` instead of `Oblique` when falling back on `Helvetica` for `Arial Black`.

> 
>     * `firefox-standard_fonts_no_system_fonts-page7` the text now looks both italic _and_ bold, and it should _only_ be italic.
> 
>     * `firefox-standard_fonts_no_system_fonts-page8` the text is no longer bold (but only italic).

Side effects of wrong copy/paste in `standard_fonts.js`: the fonts path were just permuted.

**Review by Snuffleupagus — APPROVED** [review]
Nit: Please fix the typo in the *commit message*, i.e. replace `[api-mninor]` -> `[api-minor]`

Given the huge amount of movement on the Linux-bot I've not really looked in detail at the results, however the test results look reasonable on the Windows-bot so let's do this :-)

r=me, thank you!

**Comment by calixteman** [comment]
I almost looked at all the tests on linux and I didn't notice something really wrong: just few movements because the new used fonts.

**Comment by paulmenzel** [comment]
This change regressed font rendering for some PDF files: https://bugzilla.mozilla.org/show_bug.cgi?id=1845551

**Comment by calixteman** [comment]
> This change regressed font rendering for some PDF files: https://bugzilla.mozilla.org/show_bug.cgi?id=1845551

This PR is closed now and there is no need to have the same discussion in different places (bugzilla, github, ...)
