### PR TITLE
[api-minor] Fix broken/missing JSDocs and `typedef`s, to allow updating TypeScript to the latest version (issue 14342)

### LINKED ISSUE #14342: Fix broken TypeScript upgrade to version 4.5
The TypeScript development dependency is now pinned to version 4.4.4 because version 4.5 fails for (to us) unknown reasons since nothing really stands out in the 4.5 changelogs. @michael-yx-wu @ineiti @tamuratak Would one you perhaps be able to help out with this given your TypeScript familiarity and previous work on this?

To produce the error:

1. Clone the current master branch.
2. Change `~4.4.4` to `^4.5.2` in `package.json`
3. Run `npm install`
4. Run `gulp typetest` and notice the following errors:

```
Couldn't compile TypeScript test: build/typestest/types/src/display/annotation_layer.d.ts(4,11): error TS2304: Cannot find name 'PDFPage'.
build/typestest/types/src/display/annotation_layer.d.ts(5,15): error TS2304: Cannot find name 'PageViewport'.
build/typestest/types/src/display/annotation_layer.d.ts(6,18): error TS2304: Cannot find name 'IPDFLinkService'.
build/typestest/types/src/display/annotation_layer.d.ts(7,22): error TS2304: Cannot find name 'DownloadManager'.
build/typestest/types/src/display/annotation_layer.d.ts(22,15): error TS2304: Cannot find name 'PageViewport'.
build/typestest/types/src/display/annotation_layer.d.ts(25,11): error TS2304: Cannot find name 'PDFPage'.
build/typestest/types/src/display/annotation_layer.d.ts(26,18): error TS2304: Cannot find name 'IPDFLinkService'.
build/typestest/types/src/display/annotation_layer.d.ts(27,22): error TS2304: Cannot find name 'DownloadManager'.
build/typestest/types/src/display/api.d.ts(415,39): error TS2304: Cannot find name 'Canvas'.
build/typestest/types/src/display/xfa_layer.d.ts(20,38): error TS2304: Cannot find name 'XfaLayerParameters'.
build/typestest/types/web/annotation_layer_builder.d.ts(4,14): error TS2304: Cannot find name 'PDFPage'.
build/typestest/types/web/annotation_layer_builder.d.ts(12,18): error TS2304: Cannot find name 'IPDFLinkService'.
build/typestest/types/web/annotation_layer_builder.d.ts(13,22): error TS2304: Cannot find name 'DownloadManager'.
build/typestest/types/web/annotation_layer_builder.d.ts(17,11): error TS2304: Cannot find name 'IL10n'.
build/typestest/types/web/annotation_layer_builder.d.ts(24,39): error TS2304: Cannot find name 'Canvas'.
build/typestest/types/web/annotation_layer_builder.d.ts(50,14): error TS2304: Cannot find name 'PDFPage'.
build/typestest/types/web/annotation_layer_builder.d.ts(51,18): error TS2304: Cannot find name 'IPDFLinkService'.
build/typestest/types/web/annotation_layer_builder.d.ts(52,22): error TS2304: Cannot find name 'DownloadManager'.
build/typestest/types/web/annotation_layer_builder.d.ts(55,11): error TS2304: Cannot find name 'IL10n'.
build/typestest/types/web/annotation_layer_builder.d.ts(63,39): error TS2304: Cannot find name 'Canvas'.
build/typestest/types/web/annotation_layer_builder.d.ts(72,22): error TS2304: Cannot find name 'PageViewport'.
build/typestest/types/web/annotation_layer_builder.d.ts(97,68): error TS2304: Cannot find name 'PDFPage'.
build/typestest/types/web/annotation_layer_builder.d.ts(97,173): error TS2304: Cannot find name 'IL10n'.
build/typestest/types/web/annotation_layer_builder.d.ts(99,62): error TS2304: Cannot find name 'Canvas'.
build/typestest/types/web/base_viewer.d.ts(13,15): error TS2304: Cannot find name 'EventBus'.
build/typestest/types/web/base_viewer.d.ts(17,18): error TS2304: Cannot find name 'IPDFLinkService'.
build/typestest/types/web/base_viewer.d.ts(85,11): error TS2304: Cannot find name 'IL10n'.
build/typestest/types/web/base_viewer.d.ts(97,15): error TS2304: Cannot find name 'EventBus'.
build/typestest/types/web/base_viewer.d.ts(196,30): error TS2304: Cannot find name 'PDFDocument'.
build/typestest/types/web/base_viewer.d.ts(344,87): error TS2304: Cannot find name 'PageViewport'.
build/typestest/types/web/base_viewer.d.ts(344,154): error TS2304: Cannot find name 'EventBus'.
build/typestest/types/web/base_viewer.d.ts(350,56): error TS2304: Cannot find name 'EventBus'.
build/typestest/types/web/base_viewer.d.ts(368,68): error TS2304: Cannot find name 'PDFPage'.
build/typestest/types/web/base_viewer.d.ts(368,173): error TS2304: Cannot find name 'IL10n'.
build/typestest/types/web/base_viewer.d.ts(370,62): error TS2304: Cannot find name 'Canvas'.
build/typestest/types/web/base_viewer.d.ts(378,61): error TS2304: Cannot find name 'PDFPage'.
build/typestest/types/web/base_viewer.d.ts(383,43): error TS2304: Cannot find name 'PDFPage'.
build/typestest/types/web/interfaces.d.ts(52,68): error TS2304: Cannot find name 'PDFPage'.
build/typestest/types/web/interfaces.d.ts(54,57): error TS2304: Cannot find name 'AnnotationLayerBuilder'.
build/typestest/types/web/interfaces.d.ts(142,43): error TS2304: Cannot find name 'PDFPage'.
build/typestest/types/web/interfaces.d.ts(142,53): error TS2304: Cannot find name 'StructTreeLayerBuilder'.
build/typestest/types/web/interfaces.d.ts(157,87): error TS2304: Cannot find name 'PageViewport'.
build/typestest/types/web/interfaces.d.ts(157,154): error TS2304: Cannot find name 'EventBus'.
build/typestest/types/web/interfaces.d.ts(157,177): error TS2304: Cannot find name 'TextHighlighter'.
build/typestest/types/web/interfaces.d.ts(157,195): error TS2304: Cannot find name 'TextLayerBuilder'.
build/typestest/types/web/interfaces.d.ts(170,61): error TS2304: Cannot find name 'PDFPage'.
build/typestest/types/web/interfaces.d.ts(170,126): error TS2304: Cannot find name 'XfaLayerBuilder'.
build/typestest/types/web/interfaces.d.ts(185,27): error TS2304: Cannot find name 'RenderingStates'.
build/typestest/types/web/pdf_find_controller.d.ts(5,18): error TS2304: Cannot find name 'IPDFLinkService'.
build/typestest/types/web/pdf_find_controller.d.ts(9,15): error TS2304: Cannot find name 'EventBus'.
build/typestest/types/web/pdf_find_controller.d.ts(30,19): error TS2304: Cannot find name 'IPDFLinkService'.
build/typestest/types/web/pdf_find_controller.d.ts(31,16): error TS2304: Cannot find name 'EventBus'.
build/typestest/types/web/pdf_find_controller.d.ts(47,30): error TS2304: Cannot find name 'PDFDocumentProxy'.
build/typestest/types/web/pdf_history.d.ts(5,18): error TS2304: Cannot find name 'IPDFLinkService'.
build/typestest/types/web/pdf_history.d.ts(9,15): error TS2304: Cannot find name 'EventBus'.
build/typestest/types/web/pdf_history.d.ts(48,18): error TS2304: Cannot find name 'IPDFLinkService'.
build/typestest/types/web/pdf_history.d.ts(49,15): error TS2304: Cannot find name 'EventBus'.
build/typestest/types/web/pdf_link_service.d.ts(6,15): error TS2304: Cannot find name 'EventBus'.
build/typestest/types/web/pdf_link_service.d.ts(47,15): error TS2304: Cannot find name 'EventBus'.
build/typestest/types/web/pdf_page_view.d.ts(10,15): error TS2304: Cannot find name 'EventBus'.
build/typestest/types/web/pdf_page_view.d.ts(22,22): error TS2304: Cannot find name 'PageViewport'.
build/typestest/types/web/pdf_page_view.d.ts(28,44): error TS2304: Cannot find name 'OptionalContentConfig'.
build/typestest/types/web/pdf_page_view.d.ts(32,21): error TS2304: Cannot find name 'PDFRenderingQueue'.
build/typestest/types/web/pdf_page_view.d.ts(33,23): error TS2304: Cannot find name 'IPDFTextLayerFactory'.
build/typestest/types/web/pdf_page_view.d.ts(49,29): error TS2304: Cannot find name 'IPDFAnnotationLayerFactory'.
build/typestest/types/web/pdf_page_view.d.ts(50,22): error TS2304: Cannot find name 'IPDFXfaLayerFactory'.
build/typestest/types/web/pdf_page_view.d.ts(51,29): error TS2304: Cannot find name 'IPDFStructTreeLayerFactory'.
build/typestest/types/web/pdf_page_view.d.ts(76,11): error TS2304: Cannot find name 'IL10n'.
build/typestest/types/web/pdf_page_view.d.ts(92,15): error TS2304: Cannot find name 'PageViewport'.
build/typestest/types/web/pdf_page_view.d.ts(94,44): error TS2304: Cannot find name 'OptionalContentConfig'.
build/typestest/types/web/pdf_page_view.d.ts(101,15): error TS2304: Cannot find name 'EventBus'.
build/typestest/types/web/pdf_page_view.d.ts(102,21): error TS2304: Cannot find name 'PDFRenderingQueue'.
build/typestest/types/web/pdf_page_view.d.ts(103,23): error TS2304: Cannot find name 'IPDFTextLayerFactory'.
build/typestest/types/web/pdf_page_view.d.ts(104,29): error TS2304: Cannot find name 'IPDFAnnotationLayerFactory'.
build/typestest/types/web/pdf_page_view.d.ts(105,22): error TS2304: Cannot find name 'IPDFXfaLayerFactory'.
build/typestest/types/web/pdf_page_view.d.ts(107,29): error TS2304: Cannot find name 'IPDFStructTreeLayerFactory'.
build/typestest/types/web/pdf_rendering_queue.d.ts(16,26): error TS2304: Cannot find name 'PDFViewer'.
build/typestest/types/web/pdf_rendering_queue.d.ts(20,44): error TS2304: Cannot find name 'PDFThumbnailViewer'.
build/typestest/types/web/pdf_rendering_queue.d.ts(25,29): error TS2304: Cannot find name 'IRenderableView'.
build/typestest/types/web/pdf_rendering_queue.d.ts(45,26): error TS2304: Cannot find name 'IRenderableView'.
build/typestest/types/web/pdf_rendering_queue.d.ts(53,22): error TS2304: Cannot find name 'IRenderableView'.
build/typestest/types/web/pdf_scripting_manager.d.ts(5,15): error TS2304: Cannot find name 'EventBus'.
build/typestest/types/web/pdf_scripting_manager.d.ts(46,16): error TS2304: Cannot find name 'EventBus'.
build/typestest/types/web/struct_tree_layer_builder.d.ts(3,14): error TS2304: Cannot find name 'PDFPage'.
build/typestest/types/web/struct_tree_layer_builder.d.ts(13,43): error TS2304: Cannot find name 'PDFPage'.
build/typestest/types/web/struct_tree_layer_builder.d.ts(24,14): error TS2304: Cannot find name 'PDFPage'.
build/typestest/types/web/text_highlighter.d.ts(2,21): error TS2304: Cannot find name 'PDFFindController'.
build/typestest/types/web/text_highlighter.d.ts(6,15): error TS2304: Cannot find name 'EventBus'.
build/typestest/types/web/text_highlighter.d.ts(27,21): error TS2304: Cannot find name 'PDFFindController'.
build/typestest/types/web/text_highlighter.d.ts(29,15): error TS2304: Cannot find name 'EventBus'.
build/typestest/types/web/text_layer_builder.d.ts(10,15): error TS2304: Cannot find name 'EventBus'.
build/typestest/types/web/text_layer_builder.d.ts(18,15): error TS2304: Cannot find name 'PageViewport'.
build/typestest/types/web/text_layer_builder.d.ts(23,18): error TS2304: Cannot find name 'TextHighlighter'.
build/typestest/types/web/text_layer_builder.d.ts(43,87): error TS2304: Cannot find name 'PageViewport'.
build/typestest/types/web/text_layer_builder.d.ts(43,154): error TS2304: Cannot find name 'EventBus'.
build/typestest/types/web/text_layer_builder.d.ts(43,177): error TS2304: Cannot find name 'TextHighlighter'.
build/typestest/types/web/xfa_layer_builder.d.ts(4,14): error TS2304: Cannot find name 'PDFPage'.
build/typestest/types/web/xfa_layer_builder.d.ts(6,18): error TS2304: Cannot find name 'IPDFLinkService'.
build/typestest/types/web/xfa_layer_builder.d.ts(19,61): error TS2304: Cannot find name 'PDFPage'.
build/typestest/types/web/xfa_layer_builder.d.ts(35,14): error TS2304: Cannot find name 'PDFPage'.
build/typestest/types/web/xfa_layer_builder.d.ts(37,18): error TS2304: Cannot find name 'IPDFLinkService'.
build/typestest/types/web/xfa_layer_builder.d.ts(48,22): error TS2304: Cannot find name 'PageViewport'.

[13:35:32] 'runTypesTest' errored after 2.46 s
[13:35:32] Error: Command failed: "node_modules/.bin/tsc" -p test/types

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:390:28)
    at ChildProcess.emit (node:domain:537:15)
    at maybeClose (node:internal/child_process:1062:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
    at Process.callbackTrampoline (node:internal/async_hooks:130:17)
[13:35:32] 'typestest' errored after 28 s
```

### PR DESCRIPTION
**Pull request by Snuffleupagus**
This patch circumvents the issues seen when trying to update TypeScript to version `4.5`, by "simply" fixing the broken/missing JSDocs and `typedef`s such that `gulp typestest` now passes.
As always, given that I don't really know anything about TypeScript, I cannot tell if this is a "correct" and/or proper way of doing things; we'll need TypeScript users to help out with testing!

*Please note:* I'm sorry about the size of this patch, but given how intertwined all of this unfortunately is it just didn't seem easy to split this into smaller parts.
However, one good thing about this TypeScript update is that it helped uncover a number of pre-existing bugs in our JSDocs comments.

### CODE REVIEW

File: web/interfaces.js [hunk 1]
```diff
@@ -14,6 +14,21 @@
...
+/** @typedef {import("./annotation_layer_builder").AnnotationLayerBuilder} AnnotationLayerBuilder */
+// eslint-disable-next-line max-len
+/** @typedef {import("./pdf_rendering_queue").RenderingStates} RenderingStates */
+// eslint-disable-next-line max-len
+/** @typedef {import("./struct_tree_builder").StructTreeLayerBuilder} StructTreeLayerBuilder */
+/** @typedef {import("./text_highlighter").TextHighlighter} TextHighlighter */
+// eslint-disable-next-line max-len
+/** @typedef {import("./text_layer_builder").TextLayerBuilder} TextLayerBuilder */
+/** @typedef {import("./ui_utils").EventBus} EventBus */
+/** @typedef {import("./xfa_layer_builder").XfaLayerBuilder} XfaLayerBuilder */
```
Comment (Snuffleupagus) [inline web/interfaces.js:30]: This is introducing a *circular dependency* between types, since e.g. `web/annotation_layer_builder.js` references this file, but both `gulp types` and `gulp typestest` works so I assume this is fine!?

Comment (Snuffleupagus) [reply web/interfaces.js:30]: This is introducing a *circular dependency* between types, since e.g. `web/annotation_layer_builder.js` references types in this file, but both `gulp types` and `gulp typestest` works so I assume this is fine!?

File: web/interfaces.js [hunk 2]
```diff
@@ -14,6 +14,21 @@
...
+
```
Comment (Snuffleupagus) [inline web/interfaces.js:31]: This is introducing a *circular dependency* between types, since e.g. `web/annotation_layer_builder.js` references types in this file, but both `gulp types` and `gulp typestest` works so I assume/hope this is fine!?

If not, we'd probably have to re-factor the actual JavaScript code in order to fix this.

Comment (Snuffleupagus) [reply web/interfaces.js:31]: /cc @michael-yx-wu @ineiti @tamuratak Would (either of) you perhaps be able to answer the question above, and could you also please help with testing this patch?

Comment (Snuffleupagus) [reply web/interfaces.js:31]: /cc @michael-yx-wu @ineiti @tamuratak Would (either of) you perhaps be able to help with testing this patch?

File: src/display/xfa_layer.js [hunk 3]
```diff
@@ -13,9 +13,23 @@
...
+
 import { warn } from "../shared/util.js";
 import { XfaText } from "./xfa_text.js";
 
+/**
+ * @typedef {Object} XfaLayerParameters
+ * @property {PageViewport} viewport
+ * @property {HTMLDivElement} div
+ * @property {Object} xfaHtml
+ * @property {PDFPageProxy} [pdfPage]
```
Comment (timvandermeij) [inline src/display/xfa_layer.js:27]: I don't see `pdfPage` being used anywhere in this file aside from this comment; is that correct?

File: web/xfa_layer_builder.js [hunk 4]
```diff
@@ -54,8 +64,8 @@ class XfaLayerBuilder {
       const parameters = {
         viewport: viewport.clone({ dontFlip: true }),
         div: this.div,
-        xfa: this.xfaHtml,
-        page: null,
```
Comment (timvandermeij) [inline web/xfa_layer_builder.js:58]: Same sort of comment here: is this actually used, and why does the `page` rename only happen here? I would also have expected a similar change in the `XfaLayer` class then, unless I'm missing something here.

**Review by timvandermeij — COMMENTED** [review]
Looks really good to me; while unfortunate that the upgrade failed before, it at least helped to improve the documentation/types here!

File: src/display/annotation_layer.js [hunk 5]
```diff
@@ -1700,7 +1705,7 @@ class PopupElement {
       (!this.contentsObj?.str || this.contentsObj.str === this.richText.str)
     ) {
       XfaLayer.render({
-        xfa: this.richText.html,
+        xfaHtml: this.richText.html,
```
[the remark this answers is not in the document]
Comment (Snuffleupagus) [reply src/display/annotation_layer.js:1708]: > Is the reason for changing this to avoid confusion w.r.t. the parameter's meaning,

Exactly, since the fact that `XfaLayerBuilder` used `xfaHtml` but the `XfaLayer` used `xfa` *really* confused me initially when adding the missing `XfaLayerParameters` typedef.

File: src/display/xfa_layer.js (hunk 3 above)
Comment (Snuffleupagus) [reply src/display/xfa_layer.js:27]: Good catch, that one looks completely unused here!
I'll remove this from the typedef, and also go through the code and make sure that we stop passing in an unused parameter to the `XfaLayer` (since it's just confusing as-is).

File: web/xfa_layer_builder.js (hunk 4 above)
Comment (Snuffleupagus) [reply web/xfa_layer_builder.js:58]: As above, I think this is completely unused and will fix/remove this.

**Comment by Snuffleupagus** [comment]
Hopefully this PR should also help reduce the number of problems whenever *someone* looks into issue #14017, however we (once again) need TypeScript users to help out there!

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you for doing this! It's a nice improvement and it's good that the upgrade blocker is resolved now.

**Comment by ineiti** [comment]
Wow - great work @Snuffleupagus ! I'm not sure I would've been able to do it in a reasonable amount of time...
