### PR TITLE
Consider foo-\nBar as a compound word

### LINKED ISSUE #18693: [Bug]: Can not search what I copy text from original pdf file
### Attach (recommended) or Link to PDF file

[HP Photosmart 420 Series Printer User Manual.pdf](https://github.com/user-attachments/files/16883325/HP.Photosmart.420.Series.Printer.User.Manual.pdf)

### Web browser and its version

Chrome is up to date Version 116.0.5845.97 (Official Build) (64-bit)

### Operating system and its version

Windows 11 professional

### PDF.js version

v4.6.82-legacy

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. go to page 60；
2. select line 6&7 and then「Ctrl+c」to copy；
3. 「Ctrl+f」and then「Ctrl+v」to paste and then「Enter」to search;

It cannot high light what you have copied to search.

### What is the expected behavior?

It can search and high light successfully.

### What went wrong?

image

### Link to a viewer

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by calixteman**
Fixes #18693.

### CODE REVIEW

File: test/unit/pdf_find_controller_spec.js [hunk 1]
```diff
@@ -1137,4 +1137,24 @@ describe("pdf_find_controller", function () {
...
+      },
+      matchesPerPage: [1],
+      selectedMatch: {
+        pageIndex: 0,
+        matchIndex: 0,
+      },
+      pageMatches: [[6]],
+      pageMatchesLength: [[7]],
+    });
+  });
```
Comment (Snuffleupagus) [inline test/unit/pdf_find_controller_spec.js:1159]: Nit: Can we please move this test *before* the `"custom matcher"` block instead, i.e. place it here?
https://github.com/mozilla/pdf.js/blob/0ac7f294cdb84bb0e4a346e890f567a1574f531c/test/unit/pdf_find_controller_spec.js#L1064

**Review by Snuffleupagus — APPROVED** [review]
Hopefully this won't break some other case, but I suppose we'll not know that unless we try :-)

r=me, thank you.
