### PR TITLE
Keep the empty lines in the text fields

### LINKED ISSUE #18036: Extra line breaks are missing when PDF is loaded
Sample PDF file to reproduce this issue:
[sample.pdf](https://github.com/mozilla/pdf.js/files/15180747/sample.pdf)

It seems that the issue https://github.com/mozilla/pdf.js/issues/17492 was not fully fixed.
It's the same steps to reproduce.
1. Load this PDF file at https://mozilla.github.io/pdf.js/web/viewer.html
Actual result:
There is no missing blank line between rows 1 and 2, 3 and 4.
image

Expected result:
The extra line breaks are available if you open this file in Foxit PDF viewer or Google Chrome.
image

### LINKED ISSUE #18130: lieading linebreaks are not preserved in annotations
Link to PDF file here:
[document (19).pdf](https://github.com/mozilla/pdf.js/files/13894933/document.19.pdf)

It is reproducible in https://mozilla.github.io/pdf.js/web/viewer.html
Configuration:

Web browser and its version: Chrome 124.0.6367.208 
Operating system and its version: Windows 11 Pro 10.0.22631
PDF.js version: Latest (https://mozilla.github.io/pdf.js/web/viewer.html)
Is a browser extension: No

Steps to reproduce the problem:

1. Load PDF file into viewer.
2. In the annotation line "Other job experiense", add lieading linebreak.
3. Donwload file.
4. Load into viewer =>Leading linebreak is gone

image

Expected: leading linebreaks are preserved.

### PR DESCRIPTION
**Pull request by calixteman**
It fixes #18036.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
Does this PR also fix issue #18130, since that one looks similar?

**Comment by calixteman** [comment]
> Does this PR also fix issue #18130, since that one looks similar?

Yep it's the same underlying issue.

File: src/core/annotation.js [hunk 1]
```diff
@@ -2934,6 +2935,30 @@ class TextWidgetAnnotation extends WidgetAnnotation {
...
+      return;
+    }
+    const regex = allText.replaceAll(/([.*+?^${}()|[\]\\])|(\s+)/g, (_m, p1) =>
+      p1 ? `\\${p1}` : "\\s+"
+    );
+    this.data.textContent = new RegExp(`^\\s*${regex}\\s*$`).test(
+      this.data.fieldValue
+    )
+      ? this.data.fieldValue.split("\n")
+      : text;
```
Comment (Snuffleupagus) [inline src/core/annotation.js:2959]: Can't this be simplified and shortened a little bit, since we shouldn't need to update `this.data.textContent` unconditionally here?
```suggestion
    if (new RegExp(`^\\s*${regex}\\s*$`).test(this.data.fieldValue)) {
      this.data.textContent = this.data.fieldValue.split("\n");
    }
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, with comments; thank you.
