### PR TITLE
[Editor] Add an editor in the annotation storage only when it's non-empty (#15241)

### LINKED ISSUE #15241: Ink-editor being commited to the AnnotationStorage too soon
Attach (recommended) or Link to PDF file here: N/A

Configuration:
- Web browser and its version: N/A
- Operating system and its version: N/A
- PDF.js version: `master`
- Is a browser extension: N/A

Steps to reproduce the problem:
1. Load http://localhost:8888/web/viewer.html
2. Enable Ink-editing.
3. Reload the viewer, e.g. with <kbd>F5</kbd>.

What is the expected behavior? (add screenshot)
That the viewer *immediately* reloads.

What went wrong? (add screenshot)
The "Do you want to leave this page"-dialog comes up, since the `AnnotationStorage` isn't empty.

---

This is probably fallout from PR #15163, since that one meant that we always initialize the Ink-editor immediately. However I don't believe that it's correct to insert a new Ink-Annotation into the `AnnotationStorage` *unless* the user has actually drawn something.

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

File: src/display/editor/annotation_editor_layer.js [hunk 1]
```diff
@@ -440,6 +440,16 @@ class AnnotationEditorLayer {
     editor.onceAdded();
   }
 
+  /**
+   * Add an editor in the annotation storage.
+   * @param {AnnotationEditor} editor
+   */
+  addToAnnotationStorage(editor) {
+    if (!editor.isEmpty() && !this.annotationStorage.has(editor.id)) {
```
Comment (Snuffleupagus) [inline src/display/editor/annotation_editor_layer.js:448]: I wonder if we should perhaps use the existing `getRawValue` method here, rather than add a new method (i.e. `has`) with a single call-site?

**Review by Snuffleupagus — APPROVED** [review]
r=me, thanks for fixing this so quickly!

File: src/display/editor/annotation_editor_layer.js (hunk 1 above)
Comment (calixteman) [reply src/display/editor/annotation_editor_layer.js:448]: I benchmarked `!!map.get` vs `map.has` and with Firefox `has` is 10% faster when with Chrome it's 25% faster.
Anyway, it isn't really a bottleneck, so I think it doesn't really matters, it's likely a matter of taste here.
If you prefer using `getRawValue`, it's fine for me, just tell me.
