### PR TITLE
Handle PDF files with missing 'endobj' operators, by searching for the "obj" string rather than "endobj" in `XRef.indexObjects` (issue 9105)

### LINKED ISSUE #9105: Invalid root reference when parsing pdf
Trying to read a pdf file using PDFJS.getDocument function. The pdf worker is throwing

UnknownErrorException {
 name: "UnknownErrorException", 
 message: "Invalid root reference", 
 details: "FormatError: Invalid root reference"
}

The error can be easily reproduced calling PDFJS.getDocument(pdfUrl) using the attached pdf
[110229_10312017_6810306.pdf](https://github.com/mozilla/pdf.js/files/1444166/110229_10312017_6810306.pdf)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
This patch refactors the searching for 'endobj', to try and find the next occurance of "obj" and then check if it was in fact an 'endobj' and continue searching otherwise.
This approach is used to avoid having to first find 'endobj', and then re-check the entire contents of the object and having to run (potentially expensive) regular expressions on arbitrary long strings.

Fixes #9105.

---
Replaces PR #9253, since the approach used there would cause needless re-parsing of data and potentially bad regular expression performance.

### CODE REVIEW

File: src/core/obj.js [hunk 1]
```diff
@@ -1147,8 +1148,33 @@ var XRef = (function XRefClosure() {
...
           }
-          var contentLength = skipUntil(buffer, position, endobjBytes) + 7;
-          var content = buffer.subarray(position, position + contentLength);
+          let contentLength, startPos = position + token.length;
+
+          // Find the next "obj" string, rather than "endobj", to ensure that
+          // we won't skip over a new 'obj' operator in corrupt files where
+          // 'endobj' operators are missing (fixes issue9105_reduced.pdf).
+          while (startPos < buffer.length) {
+            let endPos = startPos + skipUntil(buffer, startPos, objBytes) + 4;
```
Comment (timvandermeij) [inline src/core/obj.js]: What does this number 4 stand for? Can we make a constant out of it or add a comment?

File: src/core/obj.js [hunk 2]
```diff
@@ -1147,8 +1148,33 @@ var XRef = (function XRefClosure() {
...
+            contentLength = endPos - position;
+
+            let tokenStr = bytesToString(buffer.subarray(endPos - 8, endPos));
```
Comment (timvandermeij) [inline src/core/obj.js]: What does this number 8 stand for? Can we make a constant out of it or add a comment?

File: src/core/obj.js [hunk 3]
```diff
@@ -1147,8 +1148,33 @@ var XRef = (function XRefClosure() {
...
+            if (endobjRegExp.test(tokenStr)) {
+              break; // Found 'endobj'.
+            } else {
+              let objStartPos = Math.max(endPos - 25, startPos);
```
Comment (timvandermeij) [inline src/core/obj.js]: What does this number 25 stand for? Can we make a constant out of it or add a comment?

File: src/core/obj.js [hunk 4]
```diff
@@ -1147,8 +1148,33 @@ var XRef = (function XRefClosure() {
...
+              let objStr = bytesToString(buffer.subarray(objStartPos, endPos));
+
+              let objToken = /\d+\s+\d+\s+obj[\b\s]$/.exec(objStr);
```
Comment (timvandermeij) [inline src/core/obj.js]: There is an `objRegExp` above which looks very similar. Shouldn't we use that? If not, can we cache this regex?

File: src/core/obj.js (hunk 1 above)
Comment (Snuffleupagus) [reply src/core/obj.js]: There's existing magic numbers in this code, e.g. https://github.com/mozilla/pdf.js/blob/master/src/core/obj.js#L1150, which is why I figured it wouldn't hurt if more were added.

I'll have to think about this, since comments or meaningful constant names could end up bloating this code quite a bit :-(

File: src/core/obj.js (hunk 4 above)
Comment (Snuffleupagus) [reply src/core/obj.js]: The operative work is "similar", not identical ;-)
So no, we cannot use that one since we need to check when *end* of a string here (as opposed to the beginning above), and I'm not sure if caching really matters since this particular code-patch should almost never be hit in practice.

File: src/core/obj.js (hunk 1 above)
Comment (Snuffleupagus) [reply src/core/obj.js]: > What does this number 4 stand for?

`skipUntil` gives us the starting point of `objBytes`, so we need to get the position after it; compare with https://github.com/mozilla/pdf.js/blob/master/src/core/obj.js#L1150.

File: src/core/obj.js (hunk 3 above)
Comment (Snuffleupagus) [reply src/core/obj.js]: Since a `1 0 obj` (or similar) sequence can contain arbitrary whitespace, we need to check enough of the data to ensure that we won't miss e.g. `1     0     obj`.

In this case though, I'd agree that a constant is probably better especially considering that this number is somewhat randomly chosen.

File: src/core/obj.js (hunk 2 above)
Comment (Snuffleupagus) [reply src/core/obj.js]: > What does this number 8 stand for?

It's just to get the end of the stream such that we can check that if e.g. "&nbsp;endobj&nbsp;" was found; i.e. the endobj operator.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you for the fix!
