### PR TITLE
[api-minor] Re-factor how Node.js packages/polyfills are  loaded (issue 17245)

### LINKED ISSUE #17245: 4.0.189: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)
Attach (recommended) or Link to PDF file here: any

Configuration:
- Web browser and its version: Google Chrome 119
- Operating system and its version: macOS 14.1
- PDF.js version: 4.0.189
- Is a browser extension: no

```
  VITE v4.5.0  ready in 457 ms

  ➜  Local:   http://localhost:5273/pdf/
  ➜  Network: http://192.168.10.13:5273/pdf/
  ➜  press h to show help

✘ [ERROR] Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)

    node_modules/.pnpm/pdfjs-dist@4.0.189/node_modules/pdfjs-dist/build/pdf.mjs:16837:53:
      16837 │ /******/ __webpack_exports__ = globalThis.pdfjsLib = await __webpack_exports__;
            ╵                                                      ~~~~~

4:46:45 PM [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/.pnpm/pdfjs-dist@4.0.189/node_modules/pdfjs-dist/build/pdf.mjs:16837:53: ERROR: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)
    at failureErrorWithLog (/Users/xxx/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1649:15)
    at /Users/xxx/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1058:25
    at /Users/xxx/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1525:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### PR DESCRIPTION
**Pull request by Snuffleupagus**
*Please note:* This removes top level await from the GENERIC builds of the PDF.js library.

Despite top level await being supported in all modern browsers/environments, note [the MDN compatibility data](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#browser_compatibility), it seems that many frameworks and build-tools unfortunately have trouble with it.
Hence, in order to reduce the influx of support requests regarding top level await it thus seems that we'll have to try and fix this.

Given that top level await is only needed for Node.js environments, to load packages/polyfills, we re-factor things to limit the asynchronicity to that environment.
The "best" solution, with the least likelihood of causing future problems, would probably be to await the load of Node.js packages/polyfills e.g. at the top of the `getDocument`-function. Unfortunately that doesn't work though, since that's a *synchronous* function that we cannot change without breaking "the world".

Hence we instead await the load of Node.js packages/polyfills together with the `PDFWorker` initialization, since that's the *first point* of asynchronicity during initialization/loading of a PDF document. The reason that this works is that the Node.js packages/polyfills are only needed during fetching of the PDF document respectively during rendering, neither of which can happen *until* the worker has been initialized.
Hopefully this won't cause any future problems, since looking at the history of the PDF.js project I don't believe that we've (thus far) ever needed a Node.js dependency at an earlier point.
This new pattern for accessing Node.js packages/polyfills will also require some care during development *and* importantly reviewing, to ensure that no new top level await is added in the main code-base.

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Node.js is working on an API to sh synchronously load its built-in modules, so in the future conditioanally loading fs&friends won't need to be async anymore :)
https://github.com/nodejs/node/pull/52762

**Comment by Snuffleupagus** [comment]
> Node.js is working on an API to synchronously load its built-in modules, so in the future conditioanally loading fs&friends won't need to be async anymore :)

That looks promising, thanks a lot for the info!

However, even if that was available today it'd not avoid us having to add the `NodePackages` functionality in PDF.js since we also need to load a couple of polyfills (i.e. npm packages) and the new Node.js feature would *not* help us there as far as I understand.

It would obviously *help lessen* the amount of Node.js functionality that we needed to load asynchronously, but this new feature hasn't landed yet and from the outside I cannot tell if/when that will happen.
There's also the important question of when this'll become *generally available*, since unless it's uplifted to the current LTS branches (18 and 20) it'd take many years[1] before we could rely on it unfortunately?

---
[1] Looking at https://github.com/nodejs/release#release-schedule Node.js 18 and 20 are officially supported for (almost) one respectively two more years.

**Comment by nicolo-ribaudo** [comment]
> However, even if that was available today it'd not avoid us having to add the NodePackages functionality in PDF.js since we also need to load a couple of polyfills (i.e. npm packages) and the new Node.js feature would not help us there as far as I understand.

Well, you can do `const require = process.getBuiltinModule("module").createRequire(import.meta.url)` and then require whatever you want.

> It would obviously help lessen the amount of Node.js functionality that we needed to load asynchronously, but this new feature hasn't landed yet and from the outside I cannot tell if/when that will happen.
There's also the important question of when this'll become generally available, since unless it's uplifted to the current LTS branches (18 and 20) it'd take many years[1] before we could rely on it unfortunately?

The TypeScript team is pushing for that to land so that they can migrate to native ESM without async conditional imports for Node.js, so hopefully it'll get backported. I'll ping you if it happens :)

File: src/display/node_utils.js [hunk 1]
```diff
@@ -27,56 +27,90 @@ if (typeof PDFJSDev !== "undefined" && PDFJSDev.test("MOZCENTRAL")) {
...
+          globalThis.Path2D = Path2D;
+        } else {
+          warn("Cannot polyfill `Path2D`, rendering may be broken.");
+        }
+      }
+    },
+    reason => {
+      warn(`loadPackages: ${reason}`);
+
+      packageMap = new Map();
```
Comment (timvandermeij) [inline src/display/node_utils.js:96]: Given that I cannot really see a scenario in which loading native modules can fail, and the optional modules are already handled separately, is there actually a way to hit this `catch` branch? Even if we do, some call sites of `get(name)` for the seem to assume that a valid package is returned, but if loading fails the map will be empty and we'll likely see errors occurring later on in the places where `get(name)` is called.

Shouldn't we just raise a fatal exception here instead of warning, since if we get here I don't really see how we can continue gracefully here without breaking later on in the chain?

File: web/pdfjs.js [hunk 2]
```diff
@@ -13,15 +13,6 @@
  * limitations under the License.
  */
 
-// Ensure that the viewer waits for the library to complete loading,
```
Comment (timvandermeij) [inline web/pdfjs.js:16]: Could you extend the commit message a bit, for future reference, to indicate why we can now safely drop this? I assume this was necessary for top-level await to work, but now that we removed that we don't need it anymore?

**Review by timvandermeij — COMMENTED** [review]
I have two small questions, but other than that this looks good to me.

File: src/display/node_utils.js (hunk 1 above)
Comment (Snuffleupagus) [reply src/display/node_utils.js:96]: We probably shouldn't ever hit this branch, for the reasons you mention, but it still seemed "best" to handle any errors here (however unlikely they might be).

Depending on the PDF document you open *and* how, there might still be cases where none of the Node.js packages/polyfills are actually necessary.
For example, let's assume that you load a "simple" PDF document from a TypedArray in a Node.js environment and want to extract the textContent. Assuming that the fonts are *all embedded*, and don't require CMaps, then none of the Node.js dependencies should be necessary in this case and failing to load should thus not be an issue.

Perhaps I'm overthinking this, but the above was basically my line of thinking when I wrote that code.

File: web/pdfjs.js (hunk 2 above)
Comment (Snuffleupagus) [reply web/pdfjs.js:16]: Sure; please check if the update is sufficient!

File: src/display/node_utils.js (hunk 1 above)
Comment (timvandermeij) [reply src/display/node_utils.js:96]: Good point; I thought we were always bound to hit at least one of those call sites. If not, then I'm happy with the current code indeed.

File: web/pdfjs.js (hunk 2 above)
Comment (timvandermeij) [reply web/pdfjs.js:16]: Yes, this is better indeed.

**Review by timvandermeij — APPROVED** [review]
r=me, with passing Windows tests once the bot is working again. Thank you!

**Comment by schuma7** [comment]
Great to see that this issue is being worked on!

As I'm still struggling to understand how the different pieces of the  project fit together, I quickly wanted to ask if this fix will also get rid of the following top-level await inside `/ pdfjs-dist / legacy / web / pdf_viewer.mjs`:

`/******/ __webpack_exports__ = globalThis.pdfjsViewer = await (globalThis.pdfjsViewerPromise = __webpack_exports__);`

**Comment by Snuffleupagus** [comment]
All test "failures" look like (known) intermittent ones, hence landing this given the previous review.

**Comment by Snuffleupagus** [comment]
@timvandermeij We're waiting until the end of the month, as usual, before the next release right?

(I was promised payment from a user for writing this patch, I want to make sure that clears *before* this is officially released.)

File: src/display/node_utils.js [hunk 3]
```diff
@@ -27,56 +27,90 @@ if (typeof PDFJSDev !== "undefined" && PDFJSDev.test("MOZCENTRAL")) {
...
+      https = await __non_webpack_import__("https"),
+      url = await __non_webpack_import__("url");
 
-    if (DOMMatrix) {
-      globalThis.DOMMatrix = DOMMatrix;
-    } else {
-      warn("Cannot polyfill `DOMMatrix`, rendering may be broken.");
+    // Optional, third-party, packages.
+    let canvas, path2d;
+    if (typeof PDFJSDev !== "undefined" && !PDFJSDev.test("SKIP_BABEL")) {
```
Comment (wojtekmaj) [inline src/display/node_utils.js:45]: @Snuffleupagus Could you please elaborate on that line? This causes the code inside to be removed in generic builds and canvas to be always undefined in Node.js environments. Consequently, it's causing react-pdf unit tests to fail 🤔 Is that intentional?

Comment (Snuffleupagus) [reply src/display/node_utils.js:45]: Most likely you're not using the *correct* build, given the browsers/environments that you want to support; please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

Note also that our CI tests run successfully in Node.js 18, when using a `legacy` build, so I don't think there's anything wrong with this line.

**Comment by jamesryan-dev** [comment]
Was this released in the end?

**Comment by nicolo-ribaudo** [comment]
Yes, in v4.3.136.
