### PR TITLE
Set the text fields font size based on their height

### LINKED ISSUE #14301: Content in some text widgets are not visible
Attach (recommended) or Link to PDF file here:
[formulairecerfa90nov00-1.pdf](https://github.com/mozilla/pdf.js/files/7594316/formulairecerfa90nov00-1.pdf)
or here: http://mdph.cotesdarmor.fr/pdf/formulaires/formulairecerfa90nov00.pdf

Configuration:
- Web browser and its version: Firefox nightly
- Operating system and its version: Windows 10 pro

Steps to reproduce the problem:
1.  Go to page 2:
image
Enter a number in each fields (the input is supposed to be a single number)
2. It's impossible to read what it has been entered, so it isn't possible to check that the inputs are correct and consequently the user will very likely use another pdf viewer.

What is the expected behavior? (add screenshot)
image

What went wrong? (add screenshot)
image

### LINKED ISSUE #14736: <input> elements for annotations inherit some style from viewer.css
STR:
 - open the pdf in https://github.com/mozilla/pdf.js/issues/14685#issue-1172145263
 - open devtools and look at the style for an `<input>`
 - it has `font: message-box` which is defined: https://github.com/mozilla/pdf.js/blob/54d4d345d31abead560e1bc54138af6b9baadd6b/web/viewer.css#L195

According to:
https://developer.mozilla.org/en-US/docs/Web/CSS/font#message-box
this value is for dialog boxes so I think it doesn't make sense to use it for annotation.

### PR DESCRIPTION
**Pull request by calixteman**
- right now we're using the font size from the pdf itself but we use an other font
  in the annotation layer. So this size doesn't really make sense and leads to bad
  rendering (see pdf in #14928);
- use a sans-serif font for the fields containing text;
- text fields allow/disallow scrolling bars (see bit 24 in Ff entry), so use this
  value to hide/show scrollbars in annotation layer.

### CODE REVIEW

File: src/display/annotation_layer.js [hunk 1]
```diff
@@ -897,6 +899,45 @@ class WidgetAnnotationElement extends AnnotationElement {
...
+
+    const style = element.style;
+
+    // TODO: If the font-size is zero, calculate it based on the height and
+    //       width of the element.
+    // Not setting `style.fontSize` will use the default font-size for now.
+
+    // We don't use in the input the font which is in the pdf, so
+    // using the fontSize can lead to bad display.
+    // Hence, we set the fontSize in based on the field height.
```
Comment (Snuffleupagus) [inline src/display/annotation_layer.js:924]: Let's improve the grammar a little bit here, e.g. like so:
```javascript
// We don't use the font, as specified in the PDF document, for the <input>
// element. Hence using the original `fontSize` could look bad, which is why
// it's instead based on the field height.
```

File: src/shared/util.js [hunk 2]
```diff
@@ -18,6 +18,11 @@ import "./compatibility.js";
 const IDENTITY_MATRIX = [1, 0, 0, 1, 0, 0];
 const FONT_IDENTITY_MATRIX = [0.001, 0, 0, 0.001, 0, 0];
 
+// Represent the percentage of the height of a single-line field over
+// the font size.
+// Acrobat seems to use this value.
```
Comment (Snuffleupagus) [inline src/shared/util.js:23]: Nit: Can be moved to the previous line.

**Comment by Snuffleupagus** [comment]
- It seems that a border in `issue13447-annotations-page1` is now missing, was that intended?
 - There's *some* missing borders in `issue12716-page1` and `issue12716-hidpi-page1`, which I'm guessing isn't intended?

**Comment by calixteman** [comment]
About:
 - `issue13447-annotations-page1`: in Acrobat there are no yellow border around the icon and and in specs, in Table 164, the C entry is used here for "The title bar of the annotation’s pop-up window". The C entry is only used as the border color for the Link annotation.
 - `issue12716-page1` there is a very small text field with dimensions 0.025in x 0.025in, before the patch it looks rectangular
image
and with the patch it looks like a square
image
and it's likely due to the padding change

**Review by Snuffleupagus — APPROVED** [review]
Unless I'm overlooking something, I don't believe that the following override is necessary now:
https://github.com/mozilla/pdf.js/blob/d80035b7168f87ffcf25e70abb45cc1c06e74a2d/web/annotation_layer_builder.css#L170

r=me, with the above fixed since this looks overall reasonable to me; thank you!
