### PR TITLE
Use default colors only in forced-colors mode (bug 1778068)

### LINKED ISSUE #15141: Coloured image displaying in black-white
Attach (recommended) or Link to PDF file here:
[KNMI_De_staat_van_ons_klimaat_2021_interactief_DEF.pdf](https://github.com/mozilla/pdf.js/files/9061779/KNMI_De_staat_van_ons_klimaat_2021_interactief_DEF.pdf)

Configuration:
- Web browser and its version: Firefox 102.0
- Operating system and its version: Windows 10 (21H1 build 19043)
- PDF.js version: No idea, doesn't seem to be easily accessible within Firefox
- Is a browser extension: yes, built-in

Steps to reproduce the problem:
1. Open PDF
2. Browse to page 9

What is the expected behavior? (add screenshot)

image

The working image was taking from the PDF within Edge.

What went wrong? (add screenshot)

image

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

Additional notes:

Testing the same PDF on Firefox 102.0 on macOS (12.4) does show the correct image.

Edit: Upon further comparison, there seems to be more going on. At first I thought the blue channel was being stripped, but that would still leave red and green channels for some colours. It starts from the very first page, check the KNMI logo, check the interactive bar at the bottom of page 3 and onwards and the index buttons on page 2. They all got reduced to black.

### PR DESCRIPTION
**Pull request by calixteman**
There is a patch in review for Firefox:
https://phabricator.services.mozilla.com/D151158

### CODE REVIEW

File: web/app.js [hunk 1]
```diff
@@ -516,10 +516,15 @@ const PDFViewerApplication = {
     const container = appConfig.mainContainer,
       viewer = appConfig.viewerContainer;
     const annotationEditorMode = AppOptions.get("annotationEditorMode");
-    const pageColors = {
-      background: AppOptions.get("pageColorsBackground"),
-      foreground: AppOptions.get("pageColorsForeground"),
-    };
+    const pageColors = window.matchMedia("(forced-colors: active)").matches
```
Comment (Snuffleupagus) [inline web/app.js:519]: Generally speaking, it seems a little bit unfortunate to essentially make it impossible for users to specify *custom* values for these PDF.js-specific color preferences.

Looking at the bug, could we perhaps only disable this functionality when the "problematic" (general) Firefox preferences have been set?
*For context:* Years ago we had code which checked the `browser.display.document_color_use` preference; this was removed (since it'd become unused) in https://github.com/mozilla/pdf.js/pull/11521/commits/a977882f54c82cc7239e5238734194881a281137 and https://github.com/mozilla/gecko-dev/commit/7015ab6e166895bab2c6f8af30763b0b66f7b237

Would it make (any) sense to re-instate *similar* checks here, and do something like this instead?
```suggestion
    const pageColors =
      window.matchMedia("(forced-colors: active)").matches || this.supportsDocumentColors
```

**Review by Snuffleupagus — COMMENTED** [review]
*Please see questions inline.*

File: web/app.js [hunk 2]
```diff
@@ -730,6 +732,21 @@ const PDFViewerApplication = {
     return this.externalServices.supportedMouseWheelZoomModifierKeys;
   },
 
+  get useUserDefinedColors() {
```
Comment (Snuffleupagus) [inline web/app.js:735]: Maybe `allowDocumentColorUse` instead here, to have slightly more consistent method names between the the `app.js`, `firefoxcom.js`, and `PdfStreamConverter.jsm` files?

**Comment by Snuffleupagus** [comment]
> Hence I still wonder if we should just change them when in HCM whatever the setting is in Firefox.

Right, the situation here is a bit messy since we "advertised" the pageColors feature in the release notes of version `2.14.305` and we might not want to outright break that!?

How about we try to limit the scope of things here to address the Firefox bug, but still support the HCM-case properly, while also allowing users to override things if desired/needed?
My, very simply, idea would be something like the following (which limits the changes needed here):
 - Add a new `boolean` option/preference, e.g. `forcePageColors`, set to `false` by default. 
 - In `app.js` we [replace this code](https://github.com/mozilla/pdf.js/blob/bde46632d4b09f459acf38b761a882c9cb1ad95d/web/app.js#L519-L522) with
   ```javascript
   const pageColors =
      AppOptions.get("forcePageColors") ||
      window.matchMedia("(forced-colors: active)").matches
        ? {
            background: AppOptions.get("pageColorsBackground"),
            foreground: AppOptions.get("pageColorsForeground"),
          }
        : null;
   ```

**Comment by calixteman** [comment]
Yes I thinks it's the right solution here.
When I read stuff about Canvas & CanvasText, it was always about a11y and I considered that those values were always set to non-default values in HCM.

**Comment by calixteman** [comment]
@Snuffleupagus, I wrote what you proposed.
Once it's merged I'll uplift the patch in beta and release.
It's so painful to not have discovered this issue in nightly & beta.

File: web/app_options.js [hunk 3]
```diff
@@ -138,6 +138,10 @@ const defaultOptions = {
     value: 16777216,
     kind: OptionKind.VIEWER,
   },
+  forcePageColors: {
+    value: false,
```
Comment (Snuffleupagus) [inline web/app_options.js:142]:
```suggestion
    /** @type {boolean} */
    value: false,
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, with missing doc-comment added; thank you!
