### PR TITLE
Let `Lexer.getNumber` treat more invalid "numbers" as zero (issue 15604)

### LINKED ISSUE #15604: Blank page displayed for the pdf document.  FormatError in GetOperatorList()
Attach (recommended) or Link to PDF file here: 
File is attached by the customer in the comments section.

Configuration:
- Web browser and its version:
All browsers(latest versions). Some of the browsers which we tried:
Google Chrome Version 106.0.5249.119
Firefox Version 106.0
	
- Operating system and its version:
Windows but not limited to any OS.
	
- PDF.js version: 2.16.105

- Is a browser extension: No

Steps to reproduce the problem:
1.  Open pdf.js viewer.
2. Click "Open File" button and load the sample document

What is the expected behavior? (add screenshot)
Document should be loaded properly with its contents visible.
Open the same pdf document with Chrome or Edge Or Adobe acrobat reader. Document contents are is properly visible.

What went wrong? (add screenshot)
Blank screen is displayed when the pdf document is opened in pdf.js viewer.

Additional Note:
Errors in the browser console says:

```
app.js:1566 PDF 89d7f33e104f0ecc79eaa525e15c34ee [1.4 iTextSharp™ 5.5.1 ©2000-2014 iText Group NV (AGPL-version) / -] (PDF.js: 2.16.105)
util.js:425 Warning: getOperatorList - ignoring errors during "GetOperatorList: page 0" task: "FormatError: Invalid number:   (charCode 32)".
util.js:425 Warning: getTextContent - ignoring errors during "GetTextContent: page 0" task: "FormatError: Invalid number:   (charCode 32)".
```

### PR DESCRIPTION
**Pull request by Snuffleupagus**
In the referenced PDF document there are "numbers" which consist only of `-.`, and while that's obviously not valid Adobe Reader seems to handle it just fine.
Letting this method ignore more invalid "numbers" was suggested during the review of PR #14543, so let's simply relax our the validation here.

### CODE REVIEW

File: src/core/parser.js [hunk 1]
```diff
@@ -897,21 +897,15 @@ class Lexer {
...
-          return 0;
-        }
-        // This is consistent with Adobe Reader (fixes bug1753983.pdf).
-        if (divideBy === 0 && sign === -1) {
-          warn("Lexer.getNumber - treating a single minus sign as zero.");
-          return 0;
-        }
+        // This is consistent with Adobe Reader (fixes issue9252.pdf,
+        // issue15604.pdf, bug1753983.pdf).
+        warn(`Lexer.getNumber - "${msg}".`);
```
[the remark this answers is not in the document]
Comment (calixteman) [reply src/core/parser.js:905]: Could we have a way to log that stuff and some others only in the local dev environment ?
I really like logs in general (whatever the project is) but I don't really see the value for a normal user, so we could try to keep only for devs if it's possible.
If it isn't, we can keep a warning and add a TODO: "remove this warning in 2023 if it was useless" or something like that.

[the remark this answers is not in the document]
Comment (calixteman) [reply src/core/parser.js:905]: At least for this warning, we should warn only one time.

[the remark this answers is not in the document]
Comment (Snuffleupagus) [reply src/core/parser.js:905]: Let's just go for `info` then, since that won't show up unless you change the `verbosity` level.

File: test/unit/parser_spec.js [hunk 2]
```diff
@@ -151,17 +151,17 @@ describe("parser", function () {
...
 
-        const minusInput = new StringStream("-");
-        const minusLexer = new Lexer(minusInput);
-        expect(minusLexer.getNumber()).toEqual(0);
+          expect(validLexer.getNumber()).toEqual(0);
+        }
 
-        const numbers = ["..", "-.", "+.", "-\r\n.", "+\r\n."];
-        for (const number of numbers) {
+        const invalidNums = ["..", ".-", ".+"];
```
Comment (calixteman) [inline test/unit/parser_spec.js:163]: If "." is valid and is 0, I'd say that ".." is equivalent to 0 0.
From a lexer pov, I'd say that if we have a non-number char after the "." then we return a token 0 for this one and then the lexer creates a new token for the second point, hence"..123" will be equivalent to 0 0.123.

Comment (Snuffleupagus) [reply test/unit/parser_spec.js:163]: Is that actually what Adobe Reader does in this case, since the `Lexer.getNumber` method tries to mimic its behavior?

Comment (Snuffleupagus) [reply test/unit/parser_spec.js:163]: Given that this patch already feels a little risky, I do wonder if we perhaps want to limit the scope a little here?

**Review by calixteman — APPROVED** [review]
LGTM. Thank you.
I'll check how `..` or `.+` are handled in Acrobat.

File: test/unit/parser_spec.js (hunk 2 above)
Comment (calixteman) [reply test/unit/parser_spec.js:163]: So in Acrobat, ".." and ".+" generate an error but ".-" is considered as 0.
The three expressions are ok in Chrome (the parsing doesn't break because of them).
