### PR TITLE
Enforce line width to be at least 1px after applied transform

### LINKED ISSUE #12810: Rendering Issue in Chrome: Lose some green dots in rendering one PDF exported from AutoCAD
[Attach](url
[Test1.pdf](https://github.com/mozilla/pdf.js/files/5763185/Test1.pdf)
)

Configuration:
- Browser: Chrome 87.0.4280.88
- OS: MacOS 10.15.4
- PDF.js version: 2.5.207

Steps to reproduce the problem:
1. Open the viewer.html in above pdf.js package
2. Open the attached **_Test1.pdf_** in the viewer.html

What is the expected behavior? (add screenshot)
All contents should be rendered properly, just like the attached **_right.png_**
right

What went wrong? 
Some green dots in left side are lost, as highlighted in the **_wrong.png_**. And this issue only exists in the Chrome browser, it renders properly in safari and Firefox.
wrong

### PR DESCRIPTION
**Pull request by calixteman**
* add a comment to explain how minimal linewidth is computed.
* when context.linewidth < 1 after transform, firefox and chrome don't render in the same way (issue #12810).
* set lineWidth to 1 after transform and before stroking 
  - aims fix issue #12295   
  - a pixel can be transformed into a rectangle with both heights < 1. A single rescale leads to a rectangle with dim equals to 1 and      the other to something greater than 1. 
* change the way to render rectangle with null dimensions: 
  - right now we rely on the lineWidth set before "re" but      it can be set after "re" and before "S" and in this case the rendering      will be wrong.   
  - render such rectangles as a single line.

### CODE REVIEW

File: src/display/canvas.js [hunk 1]
```diff
@@ -38,8 +38,8 @@ const MIN_FONT_SIZE = 16;
 const MAX_FONT_SIZE = 100;
 const MAX_GROUP_SIZE = 4096;
 
-// Heuristic value used when enforcing minimum line widths.
-const MIN_WIDTH_FACTOR = 0.65;
+// Enforce line to have a minimal width of 1px when transform is applied
```
Comment (Snuffleupagus) [inline src/display/canvas.js:41]: This is a sentence without a period at the end :-)

File: src/display/canvas.js [hunk 2]
```diff
@@ -38,8 +38,8 @@ const MIN_FONT_SIZE = 16;
...
+const MIN_WIDTH_FACTOR = 1.000001;
```
Comment (Snuffleupagus) [inline src/display/canvas.js:42]: Also, given all the different `getSinglePixelWidth` and `MIN_WIDTH_FACTOR` usages throughout this file; are these changes generally correct/safe (as in not regressing existing tests)?

Unfortunately PR #4615 landed without a test-case included, so please also *manually* test the issues/bugs listed there to ensure that you're not regressing anything here!

File: src/shared/util.js [hunk 3]
```diff
@@ -710,19 +710,27 @@ class Util {
   // The SVD can be represented with formula A = USV. We are interested in the
   // matrix S here because it represents the scale values.
   static singularValueDecompose2dScale(m) {
-    const transpose = [m[0], m[2], m[1], m[3]];
+    if (Math.abs(m[1]) <= Number.EPSILON && Math.abs(m[2]) <= Number.EPSILON) {
```
Comment (Snuffleupagus) [inline src/shared/util.js:713]: The changes in this file probably belongs in a *separate commit*, since they seem orthogonal to the rest of the changes.

File: src/shared/util.js [hunk 4]
```diff
@@ -710,19 +710,27 @@ class Util {
...
+    const c = m[2] * m[0] + m[3] * m[1];
+    const d = m[2] * m[2] + m[3] * m[3];
 
     // Solve the second degree polynomial to get roots.
-    const first = (a + d) / 2;
-    const second = Math.sqrt((a + d) * (a + d) - 4 * (a * d - c * b)) / 2;
-    const sx = first + second || 1;
-    const sy = first - second || 1;
+    const sum_a_d = a + d;
+    const second = Math.sqrt(sum_a_d * sum_a_d - 4 * (a * d - c * b));
```
Comment (Snuffleupagus) [inline src/shared/util.js:731]:
```suggestion
    const second = Math.sqrt(sum_a_d ** 2 - 4 * (a * d - c * b));
```

Also, the variable name `second` looks slightly out-of-place here now.

File: src/shared/util.js [hunk 5]
```diff
@@ -710,19 +710,27 @@ class Util {
...
-    const transpose = [m[0], m[2], m[1], m[3]];
+    if (Math.abs(m[1]) <= Number.EPSILON && Math.abs(m[2]) <= Number.EPSILON) {
+      // Diagonal matrix
+      return [Math.abs(m[0]) || 1, Math.abs(m[3]) || 1];
+    }
+
+    if (Math.abs(m[0]) <= Number.EPSILON && Math.abs(m[3]) <= Number.EPSILON) {
+      // Anti-diagonal matrix: scale composed with rotation of +/- 90°
+      return [Math.abs(m[2]) || 1, Math.abs(m[1]) || 1];
+    }
```
Comment (Snuffleupagus) [inline src/shared/util.js:721]: Given the additional checks added here, how much of a performance increase are these changes bringing in the general case (do you at least have some ballpark numbers)?

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]
Besides some inline comment; can we add a reference-test for this?

**Comment by janpe2** [comment]
Does this PR improve also the rendering of issue #12295? The problems in that issue are caused by the existing implementation of `getSinglePixelWidth()` because the scaling factors differ greatly in the horizontal and vertical direction.

File: src/display/canvas.js (hunk 2 above)
Comment (calixteman) [reply src/display/canvas.js]: I checked all the pdf mentioned in the above PR and they all looks good.
I ran locally ref tests and the differences are minimal.
I'd say that with my eyes the rendering on firefox-linux and on acrobat-windows are very close (same screen).
