### PR TITLE
Tweak the `DOMTokenList.toggle` polyfill (issue 10460)

### LINKED ISSUE #10460: Element.classList.toggle does not work in IE
Attach (recommended) or Link to PDF file here:
https://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- Web browser and its version: IE (any version)
- Operating system and its version: Windows 8/10
- PDF.js version: 2.0.943
- Is a browser extension: No

Steps to reproduce the problem:
1. Execute document.getElementsByTagName('body')[0].classList.toggle('test') on the Internet Explorer console

What is the expected behavior? (add screenshot)
Should add or remove a class to an element.

What went wrong? (add screenshot)
Throws an "invalid calling object" error

image

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Fixes #10460.

### CODE REVIEW

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thanks!

File: src/shared/compatibility.js [hunk 1]
```diff
@@ -101,14 +101,17 @@ const hasDOM = typeof window === 'object' && typeof document === 'object';
...
     if (arguments.length > 1) {
       const force = !!arguments[1];
       return (this[force ? 'add' : 'remove'](token), force);
     }
-    return originalDOMTokenListToggle(token);
+
+    if (this.contains(token)) {
+      return (this.remove(token), false);
+    }
+    return (this.add(token), true);
```
Comment (mhuggins) [inline src/shared/compatibility.js]: Arguable, but would it have been work calling the original function?  The main benefit would be that if the underlying implementation to `toggle` changes, then this never needs to change.  i.e.:

```js
return originalDOMTokenListToggle.call(this, token);
```

Comment (mhuggins) [reply src/shared/compatibility.js]: Regardless, thanks for this fix!

Comment (timvandermeij) [reply src/shared/compatibility.js]: I think that's essentially what we had before this fix and it didn't work in IE. Since this is only a polyfill for IE and toggle functionality is trivial, I don't think we need to change this.

Comment (mhuggins) [reply src/shared/compatibility.js]: The original call was this:

```js
return originalDOMTokenListToggle(token);
```

My suggestion, which also fixes the problem in IE, is this:

```js
return originalDOMTokenListToggle.call(this, token);
```

It's ultimately not a big deal since the issue is now fixed.

Comment (timvandermeij) [reply src/shared/compatibility.js]: Ah, I see. The diff in this patch is actually old; in the current code it's minimized to https://github.com/mozilla/pdf.js/blob/master/src/shared/compatibility.js#L110-L113. In the current code I don't think calling the original function is really possible anymore since that one doesn't support the `force` parameter, so then we would need to special-case it and get back to the code in this diff. Indeed it doesn't really matter too much since it's a working polyfill and it will probably be removed once we drop IE support in a later major release anyway.

Comment (mhuggins) [reply src/shared/compatibility.js]: Seems like a moot point then, thanks for calling that out!
