### PR TITLE
Provide a js fallback when the wasm version of openjpeg is failing to load (bug 1935076)

### LINKED ISSUE #18457: [Bug]: PDF not renderable due to CSP not allowing WASM since PDFJS4 - CompileError: WebAssembly.Module(): Refused to compile or instantiate WebAssembly module
### Attach (recommended) or Link to PDF file

[PDFJS-JPEG2000-WebAssembly-Problem.pdf](https://github.com/user-attachments/files/16308816/PDFJS-JPEG2000-WebAssembly-Problem.pdf)

### Web browser and its version

FireFox 128.0, Edge 126.0.2592.102, Chrome 126.0.6478.183

### Operating system and its version

Windows 11 Enterprise 22H2 22621.3880

### PDF.js version

4.4.168

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Have a Content-Security-Policy that does not allow usage of WebAssembly
2. Try to render the PDF file which has `JPXDecode` inside
3. The canvas stays blank and receive a warning on the console

### What is the expected behavior?

The canvas should get painted and no console warnings should happen.
The problematic PDF file was renderable with PDFJS version 3.

### What went wrong?

1. The canvas stays blank.
2. The browser console logs `Warning: Unable to decode image "img_p0_1": "CompileError: WebAssembly.Module(): Refused to compile or instantiate WebAssembly module because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' *.company.tld"".`

### Link to a viewer

_No response_

### Additional context

The PDF was renderable without problems with the same CSP with PDFJS version 3.11.174.

I am not allowed to adjust or weaken the CSP.  

This is the CSP: `default-src 'none'; script-src 'self' *.company.tld; connect-src 'self' *.company.tld; img-src 'self' blob: data: *.company.tld; frame-src 'self' *.company.tld; style-src 'self' 'unsafe-inline' *.company.tld; font-src 'self' *.company.tld; frame-ancestors 'self' *.company.tld; upgrade-insecure-requests;`

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Comment by calixteman** [comment]
@Snuffleupagus I've two problems with this PR:
 - `gulp lint --fix` is taking for ever: it's because of `external/openjpeg/openjpeg_nowasm_fallback.js` but normally no linter should run on it.
 - the `await import` shouldn't be converted into webpack stuff when building for m-c

Could you help me to fix these issues ?

**Comment by calixteman** [comment]
@Snuffleupagus if you see a better way to use the fallback, don't worry to take the ownership of this PR.

**Comment by Snuffleupagus** [comment]
> * `gulp lint --fix` is taking for ever: it's because of `external/openjpeg/openjpeg_nowasm_fallback.js` but normally no linter should run on it.

That folder should already being excluded from linting, given https://github.com/mozilla/pdf.js/blob/34ef74cf0eb47f665a333ef1d7a106718b207577/eslint.config.mjs#L37

Is the problem perhaps rather the `web/wasm/` folder, because if so I believe that the following diff should fix that?
```diff
diff --git a/eslint.config.mjs b/eslint.config.mjs
index 887e013bb..27893feea 100644
--- a/eslint.config.mjs
+++ b/eslint.config.mjs
@@ -39,6 +39,7 @@ export default [
       "test/tmp/",
       "test/pdfs/",
       "web/locale/",
+      "web/wasm/",
       "**/*~/",
     ],
   },
```

> * the `await import` shouldn't be converted into webpack stuff when building for m-c

Yes, that's kind of "expected" unless you explicitly tell Webpack to leave the import alone.
Please refer to the following examples to see how we handle that:
 - https://github.com/mozilla/pdf.js/blob/34ef74cf0eb47f665a333ef1d7a106718b207577/web/app.js#L284-L287
 - https://github.com/mozilla/pdf.js/blob/34ef74cf0eb47f665a333ef1d7a106718b207577/web/generic_scripting.js#L39-L42

**Comment by Snuffleupagus** [comment]
Also, how do we (easily) test this?
Could we e.g. have a test in mozilla-central, since I'm assuming that it should be easy (famous last words) to temporarily disable WebAssembly via a preference during testing?

**Comment by calixteman** [comment]
I just added a ref test to check the nowasm path.
Yep it'd make sense to have one too on the m-c side, I'll try to create a pdf with a monochrome jp2 image and check the pixels.

File: src/core/jpx.js [hunk 1]
```diff
@@ -57,6 +59,28 @@ class JpxImage {
...
       return successCallback(results.instance);
+    } catch (reason) {
+      warn(`JpxImage#instantiateWasm: ${reason}`);
+
+      if (typeof PDFJSDev !== "undefined" && PDFJSDev.test("TESTING")) {
+        this.#wasmUrl ??= "/build/generic/web/wasm/";
+      }
+      const path =
+        (typeof PDFJSDev === "undefined" ? "../" : "") +
+        `${this.#wasmUrl}openjpeg_nowasm_fallback.js`;
```
Comment (Snuffleupagus) [inline src/core/jpx.js:70]: I don't think the pre-processor is "smart" enough to be able to concatenate strings, so I'd suggest just re-writing this as follows instead.
```suggestion
      const path =
        typeof PDFJSDev === "undefined"
          ? `../${this.#wasmUrl}openjpeg_nowasm_fallback.js`
          : `${this.#wasmUrl}openjpeg_nowasm_fallback.js`;
```

File: test/test_manifest.json [hunk 2]
```diff
@@ -10219,6 +10219,17 @@
...
+    "id": "issue17061_nowasm",
+    "file": "pdfs/issue17061.pdf",
+    "md5": "21a1b887b7e657b01e4205b22d1f4378",
+    "rounds": 1,
+    "link": true,
+    "noWasm": true,
+    "firstPage": 1,
+    "lastPage": 5,
+    "type": "eq"
+  },
```
Comment (Snuffleupagus) [inline test/test_manifest.json:10232]: Could we perhaps use a smaller/simpler test-case instead, rather than one with five pages?
The following is probably one of the simplest/smallest JPEG2000 test-cases we have:
https://github.com/mozilla/pdf.js/blob/e3ea92603d17595aad4b1c37c7113cb7dee0c90e/test/test_manifest.json#L6407-L6421

**Comment by Snuffleupagus** [comment]
Do we also want to re-init the new `#importModuleResolver` field in the cleanup method?
https://github.com/mozilla/pdf.js/blob/e3ea92603d17595aad4b1c37c7113cb7dee0c90e/src/core/jpx.js#L108-L110

**Review by Snuffleupagus — COMMENTED** [review]
Should we also change
https://github.com/mozilla/pdf.js/blob/b2a860cfe98111048ab256fe4860b13719f64e70/src/core/jpx.js#L39
to the following (since `this.#buffer` may never be set when we fallback to JS-decoding)?
```javascript
if (!this.#modulePromise) {
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you.

*Reminder:* When updating mozilla-central, the new JS file needs to be added to https://searchfox.org/mozilla-central/source/toolkit/components/pdfjs/jar.mn

**Comment by Snuffleupagus** [comment]
It just occurred to me that the way the `wasmUrl` option is currently implemented won't work correctly in general, now that we also need to be able to `import` a fallback JS file.
This should however *not* affect mozilla-central and I've already got a WIP patch to improve things, so I'd suggest that we land this PR as-is and improve things in a follow-up.
