### PR TITLE
Correctly detect more cases of non-embedded Arial Black fonts (issue 7835)

### LINKED ISSUE #7835: Missing Text
Link to PDF file (or attach file here):
https://dl.dropboxusercontent.com/u/2541471/MissingText.pdf

Configuration:
- Web browser and its version: 54.0.2840.98 (64-bit) and Firefox 50.0
- Operating system and its version: macOS Sierra
- PDF.js version: 1.6.332
- Is an extension: no

Steps to reproduce the problem:
1. Open the referenced PDF. 
2. Notice the text 15-173-
3. The text is suppose to be 15-173-2 as can be seen in Adobe Reader

What is the expected behavior?
missingtext-ar

What went wrong?
Instead of the above, the 2 is dropped as shown in this screenshot:
missingtext-pdfjs

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): Reproduced this using the github hosted version.

### PR DESCRIPTION
**Pull request by Snuffleupagus**
This patch adds support for non-embedded Arial Black fonts, that use a `Arial-Black...` format for the font names.
Also, this patch changes `canvas.js` such that we always render Arial Black fonts with the maximum weight, which actually improves a number of existing test-cases. This should thus explain the test "failures", which are clear improvements compared with e.g. Adobe Reader.

Fixes #7835.

### CODE REVIEW

File: src/display/canvas.js [hunk 1]
```diff
@@ -1359,9 +1359,7 @@ var CanvasGraphics = (function CanvasGraphicsClosure() {
       }
 
       var name = fontObj.loadedName || 'sans-serif';
-      var bold = fontObj.black ? (fontObj.bold ? '900' : 'bold') :
-                                 (fontObj.bold ? 'bold' : 'normal');
-
+      var bold = fontObj.black ? '900' : (fontObj.bold ? 'bold' : 'normal');
```
Comment (yurydelendik) [inline src/display/canvas.js]: Is Arial-Black == Arial-Black-Bold?

Comment (Snuffleupagus) [inline src/display/canvas.js]: In practice this assumption seems to give better, i.e. closer to Adobe Reader, rendering in PDF.js for me locally on Windows (even if it doesn't manifest itself on the bots).
It actually seems that Adobe Reader might simply treat (non-embedded) ArialBlack-Bold the same as ArialBlack.

Comment (Snuffleupagus) [inline src/display/canvas.js]: Having looked at this once more, ordinary `ArialBlack` should use a font weight that maps to `black` to render correctly (see https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#Common_weight_name_mapping).
However, `ArialBlack,Bold` should ideally map to an *even heavier* font weight, but given that no such one exists (in CSS), we will thus simply fallback to normal `ArialBlack` instead.

To me, this seems to give the best possible rendering (at least on Windows) for these non-embedded fonts; otherwise normal `ArialBlack` actually renders too light.

**Review by yurydelendik — APPROVED** [review]
Looks good. Thanks

**Comment by Snuffleupagus** [comment]
Thanks for the review!

/botio makeref
