### PR TITLE
Fallback on font widths if CFF data is broken

### LINKED ISSUE #8591: CFF font widths not parsed properly
When reading the widths in a CFF font we need to fill the width array using default and nominal width (see the spec on how this should work).

### PR DESCRIPTION
**Pull request by yurydelendik**
Fixes #8591

### CODE REVIEW

File: src/core/cff_parser.js [hunk 1]
```diff
@@ -644,7 +648,9 @@ var CFFParser = (function CFFParserClosure() {
                                        globalSubrIndex);
         }
         if (state.width !== null) {
```
Comment (brendandahl) [inline src/core/cff_parser.js]: I thought it was strange that the widths were broken in TaroUTR50SortedList112.pdf so I looked in acrobat. Font "QEGUTH+KozMinPro-Regular" is a cid font so we should also look in the sub font dict's private dict for the nominal width and default width. In acrobat there are valid values there. There's some code above here that gets the private dict see `fdArray[fdIndex].privateDict`

**Review by brendandahl — CHANGES_REQUESTED** [review]
