### PR TITLE
Always flush the current item with MarkedContent stuff when getting text (#15094)

### LINKED ISSUE #15094: Find feature produces some wrong highlightments
Attach (recommended) or Link to PDF file here:
[cd.pdf](https://github.com/mozilla/pdf.js/files/8976190/cd.pdf)

Configuration:
- Web browser and its version: Firefox nightly
- Operating system and its version: Windows 11

Steps to reproduce the problem:
1. Search for `e` and `Highlight all`

image

Something is wrong around the `B(cb, cs)`.
From the `find_controler`:
`...of the blend function B (c b , cs ) shall be the so...`

and from devtools:
image

The problem is the space between `c` and `b`: it's either an extra space in the searched string or a missing one in the html.

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

File: test/unit/api_spec.js [hunk 1]
```diff
@@ -2275,6 +2277,24 @@ Caron Broadcasting, Inc., an Ohio corporation (“Lessee”).`)
       await loadingTask.destroy();
     });
 
+    it("gets text content with or without includeMarkedContent, and compare (issue 15094)", async function () {
+      const loadingTask = getDocument(buildGetDocumentParams("issue15094.pdf"));
```
Comment (Snuffleupagus) [inline test/unit/api_spec.js:2281]: It seems, as far as I can tell, that this issue is also reproducible using page 568 from the `pdf.pdf` file that we already use in the test-suite.
So how about using that document/page here instead, to avoid adding a new test-file?
