### PR TITLE
Try harder to find the next valid JPEG marker when decoding Scan data (issue 8182, issue 8189)

### LINKED ISSUE #8182: PDF with blank pages
[PDF with blank pages.pdf](https://github.com/mozilla/pdf.js/files/861340/PDF.with.blank.pages.pdf)

Configuration:
- Web browser and its version: Firefox 52.0.1 32 Bits
- Operating system and its version: Windows 8.1 64 bits
- PDF.js version: 1.6.315
- Is an extension: No

The pdf opens on firefox but with blank pages, On Chrome and Adobe it works correctly

### LINKED ISSUE #8189: Error: JPEG error: marker was not found. Scanned from Samsung MFP.
Link to PDF file (or attach file here): [scan.pdf](https://github.com/mozilla/pdf.js/files/865245/scan.pdf)

Configuration:
- Web browser and its version: Chrome 56.0.2924.87 (64-bit) and Firefox 52.0.1 (64-bit)
- Operating system and its version: Windows 10 64 bit and Ubuntu 16.10
- PDF.js version: Stable 1.6.210 and Beta 1.7.225
- Is an extension: No

Steps to reproduce the problem:
1. Upload the pdf to the Online demo site https://mozilla.github.io/pdf.js/web/viewer.html
2. All pages are blank

What is the expected behavior? PDF will be rendered properly 
expected

What went wrong? There are pages but no content.  In the developer console of the browser this is the logs:
`PDF a650df87b150696f9e4415aeeaece60c [1.4 CLX-8380 Series / 300] (PDF.js: 1.7.378)
pdf.worker.js:345 Error: JPEG error: marker was not found
/pdf.js/build/pdf.worker.js:345 Error: JPEG error: marker was not found
pdf.worker.js:346     at error (https://mozilla.github.io/pdf.js/build/pdf.worker.js:346:15)
    at decodeScan (https://mozilla.github.io/pdf.js/build/pdf.worker.js:44260:5)
    at JpegImage.parse (https://mozilla.github.io/pdf.js/build/pdf.worker.js:44637:22)
    at JpegStream_ensureBuffer [as ensureBuffer] (https://mozilla.github.io/pdf.js/build/pdf.worker.js:3087:13)
    at JpegStream_getBytes [as getBytes] (https://mozilla.github.io/pdf.js/build/pdf.worker.js:3094:8)
    at PDFImage_getImageBytes [as getImageBytes] (https://mozilla.github.io/pdf.js/build/pdf.worker.js:42687:22)
    at PDFImage_createImageData [as createImageData] (https://mozilla.github.io/pdf.js/build/pdf.worker.js:42619:26)
    at https://mozilla.github.io/pdf.js/build/pdf.worker.js:25799:28
/pdf.js/build/pdf.worker.js:346     at error (https://mozilla.github.io/pdf.js/build/pdf.worker.js:346:15)
    at decodeScan (https://mozilla.github.io/pdf.js/build/pdf.worker.js:44260:5)
    at JpegImage.parse (https://mozilla.github.io/pdf.js/build/pdf.worker.js:44637:22)
    at JpegStream_ensureBuffer [as ensureBuffer] (https://mozilla.github.io/pdf.js/build/pdf.worker.js:3087:13)
    at JpegStream_getBytes [as getBytes] (https://mozilla.github.io/pdf.js/build/pdf.worker.js:3094:8)
    at PDFImage_getImageBytes [as getImageBytes] (https://mozilla.github.io/pdf.js/build/pdf.worker.js:42687:22)
    at PDFImage_createImageData [as createImageData] (https://mozilla.github.io/pdf.js/build/pdf.worker.js:42619:26)
    at https://mozilla.github.io/pdf.js/build/pdf.worker.js:25799:28
`
actual

I think this is also related with #8090 and #8104

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): Tested using mozilla.github.io/pdf.js

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Tentatively fixes #8182 and fixes #8189.

### CODE REVIEW

File: src/core/jpg.js [hunk 1]
```diff
@@ -594,6 +605,39 @@ var JpegImage = (function JpegImageClosure() {
...
+    }
+    var newMarker = peekUint16(newPos);
+    while (!(newMarker >= 0xFFC0 && newMarker <= 0xFFFE)) {
+      newMarker = peekUint16(++newPos);
+      if (newPos >= maxPos) {
+        return null; // Don't attempt to read non-existent data and just return.
+      }
+    }
+    return {
+      invalid: currentMarker.toString('16'),
```
Comment (yurydelendik) [inline src/core/jpg.js]: nit: fix toString arg type `.toString(16)`

File: src/core/jpg.js [hunk 2]
```diff
@@ -594,6 +605,39 @@ var JpegImage = (function JpegImageClosure() {
...
+      return {
+        invalid: null,
+        marker: currentMarker,
+        offset: currentPos,
+      };
+    }
+    var newMarker = peekUint16(newPos);
+    while (!(newMarker >= 0xFFC0 && newMarker <= 0xFFFE)) {
+      newMarker = peekUint16(++newPos);
+      if (newPos >= maxPos) {
```
Comment (yurydelendik) [inline src/core/jpg.js]: Increment newPos and move this  if before peekUint16() call

File: src/core/jpg.js [hunk 3]
```diff
@@ -594,6 +605,39 @@ var JpegImage = (function JpegImageClosure() {
     return a <= 0 ? 0 : a >= 255 ? 255 : a;
   }
 
+  function findNextFileMarker(data, currentPos, startPos) {
+    function peekUint16(pos) {
```
Comment (yurydelendik) [inline src/core/jpg.js]: Can we use readUint16 instead?

**Review by yurydelendik — APPROVED** [review]
Looks good with comments addressed.

File: src/core/jpg.js (hunk 1 above)
Comment (Snuffleupagus) [inline src/core/jpg.js]: Thanks, fixed now.

File: src/core/jpg.js (hunk 2 above)
Comment (Snuffleupagus) [inline src/core/jpg.js]: Sure, it's done.

File: src/core/jpg.js (hunk 3 above)
Comment (Snuffleupagus) [inline src/core/jpg.js]: As agreed on IRC, since already is such a function (see https://github.com/mozilla/pdf.js/blob/cd5acf501e9899f386bb7efc9feded7b2c6e763b/src/core/jpg.js#L600), I'm leaving it as-is.
