### PR TITLE
Use Calibri and Lucida Console, when it's possible, in place of sans-serif and monospaced (bug 1922063)

### LINKED ISSUE #15114: Text-Layer has wrong position in some fonts
Attach (recommended) or Link to PDF file here:
[1000-Seiten.pdf](https://github.com/mozilla/pdf.js/files/9009977/1000-Seiten.pdf)
h

Configuration:
- Web browser and its version: Firefox 102.0  (64bit)
- Operating system and its version: Windows 10 21H2 19044.1706
- PDF.js version: as in latest Firefox
- Is a browser extension: no

Steps to reproduce the problem:
1. Open the attached PDF in Firefox or any pdf.js versions (tried some)
2. Move to page 900
3. Select the text "Gemüsebrühe" in the lower area of the page
image

What is the expected behavior? (add screenshot)
The text-layer should lay exactly over the visible text, like it is in chrome or adobe:  
image

What went wrong? (add screenshot)
The text-layer is way beside the visible text. I think there is a problem resolving the font, which is used in the pdf.
In this screenshot I moved the textlayer of the target section a bit to the bottom to get the problem visible:
image

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Just try the scenario with the attached PDF in any pdf-viewer you like (Chrome, Adobe, Foxit). The problem only occurs in Firefox.

### PR DESCRIPTION
**Pull request by calixteman**
A recent change in Firefox induced too much difference between the text widths computed in using a Canvas and the ones computed by the text layout engine when rendering the text layer. Consequently, the text selection can be bad on Windows with some fonts like Arial or Consolas. This patch is a workaround to try to use in first place some fonts which don't have the problem.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
Can we work-around this in `src/display/text_layer.js` instead, since this feels like the wrong place given that this change affects the API in general (it's basically a breaking change) and may thus cause problems elsewhere?

**Comment by Snuffleupagus** [comment]
Having this as a *temporary* work-around probably can't hurt, assuming it passes all tests of course, however since it's a *browser regression* it would be even better if it can be fixed there instead.

As-is this would still affect older PDF.js versions once the regressing code-change reaches Firefox Release, and it'd likely lead to numerous (future) bug-reports about this problem here at GitHub.

(Tentatively setting the `release-blocker` label, since *if* this is something we want it probably should be included in the upcoming release.)

File: src/display/text_layer.js [hunk 1]
```diff
@@ -300,9 +300,16 @@ class TextLayer {
       angle += Math.PI / 2;
     }
 
-    const fontFamily =
+    let fontFamily =
       (this.#fontInspectorEnabled && style.fontSubstitution) ||
       style.fontFamily;
+
+    // Workaround for bug 1922063.
```
Comment (timvandermeij) [inline src/display/text_layer.js:307]: Should we limit this to Firefox on Windows? While I haven't spotted any regressions for Linux, I'd feel better about landing this now (before the next release) if we can decrease the scope of this workaround as much as possible purely to the browser/OS listed in the bug.

**Review by timvandermeij — APPROVED** [review]
Looks good to me, with the comment below addressed. Especially if the scope of this workaround is reduced I'm fine with including this and making the release directly afterwards if the impact of this issue is deemed large enough.

File: src/shared/util.js [hunk 2]
```diff
@@ -636,9 +636,13 @@ class FeatureTest {
     ) {
       return shadow(this, "platform", {
         isMac: navigator.platform.includes("Mac"),
+        isWindows: navigator.platform.includes("Win"),
+        isFirefox:
+          (typeof PDFJSDev !== "undefined" && PDFJSDev.test("MOZCENTRAL")) ||
+          navigator.userAgent.includes("Firefox"),
```
Comment (Snuffleupagus) [inline src/shared/util.js:642]: Is this guaranteed to be safe, given everywhere that this code might run?
Please make this code a bit more defensive, to prevent any future bugs.
```suggestion
          (typeof navigator?.userAgent=== "string" && navigator.userAgent.includes("Firefox")),
```

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you for the patch!

/botio makeref
