### PR TITLE
[Annotations] Some annotations can have their values stored in the xfa:datasets

### LINKED ISSUE #14685: PDFJS is not able to show prefilled Acroform PDF with data in xfa:dataset
When Using a PDF which has Type 1 embedded fonts, a prefilled PDF that has been filled with tools like IText or PDFBox cannot be handled as is shown as empty by PDF JS.

If however PDFJS has prefilled the PDF the texts are shown.

Update: After discussion further down, now we know that the PDF is actually a hybrid of Acroform and XFA and PDFJS is not able to prefill Acroform with data in the XFA:dataset, although when saving the PDF, PDFJS actually save them in XFA:dataset also.

Attach (recommended) or Link to PDF file here:
[1647183160545.pdf](https://github.com/mozilla/pdf.js/files/8283456/1647183160545.pdf)
Configuration:
- Web browser and its version: Chrome (99)
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. open the attached file in Acrobat Reader
2. open the attached file in PDFJS

What is the expected behavior? 
image

What went wrong? (add screenshot)
image

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
[1647183160545.pdf](https://github.com/mozilla/pdf.js/files/8283456/1647183160545.pdf)

### PR DESCRIPTION
**Pull request by calixteman**
- it aims to fix #14685;
- add a basic object to get values from the parsed datasets;
- these annotations don't have an appearance so we must create one when printing or saving.

### CODE REVIEW

File: src/core/annotation.js [hunk 1]
```diff
@@ -1251,6 +1255,15 @@ class WidgetAnnotation extends Annotation {
     });
     data.defaultFieldValue = this._decodeFormValue(defaultFieldValue);
 
+    if (fieldValue === undefined && params.xfaDatasets) {
+      // Try to figure out if we have something in the xfa dataset.
+      const path = stringToPDFString(dict.get("T") || "");
```
Comment (Snuffleupagus) [inline src/core/annotation.js:1260]: *I don't have time to do a full review right now, but wanted to mention one thing straight away.*

This ought to be available already, via `this._title.str` (note the `setTitle`-call in the `Annotation`- constructor), and you shouldn't need to fetch/parse this again here.

Comment (Snuffleupagus) [inline src/core/annotation.js:1260]: This ought to be available already, via `this._title.str` (note the `setTitle`-call in the `Annotation`- constructor), and you shouldn't need to fetch/parse this again here.

File: src/core/annotation.js [hunk 2]
```diff
@@ -1251,6 +1255,15 @@ class WidgetAnnotation extends Annotation {
...
+      if (path) {
+        data.hasValueFromXFA = true;
```
Comment (Snuffleupagus) [inline src/core/annotation.js:1262]: Please note that by adding a value to the `data` object you're exposing it in the API as well.

Given that we're only using this in the worker-thread, can we please store (and access) this on the class-instance as `this._hasValueFromXFA = true;` instead?

File: src/core/dataset_reader.js [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+    this.node = null;
+  }
+
+  onEndElement(name) {
+    const node = super.onEndElement(name);
+    if (node && name === "xfa:datasets") {
+      this.node = node;
+
+      // We don't need anything else, so just kill the parser.
+      throw new Error();
```
Comment (Snuffleupagus) [inline src/core/dataset_reader.js:31]: To ensure that we can always get helpful/useful error messages we should always provide *some* kind of message string for all errors, hence please do something like:
```javascript
throw new Error("Aborting DatasetXMLParser.");
```

File: src/core/document.js [hunk 4]
```diff
@@ -820,6 +821,47 @@ class PDFDocument {
     });
   }
 
+  get xfaDatasets() {
```
Comment (Snuffleupagus) [inline src/core/document.js:824]: I cannot help but noticing the similarities between this new method and the existing `xfaData` one just below. Hence I wonder if it'd perhaps make sense, in a follow-up PR, to re-factor these two method to remove some of the duplication?

File: src/core/xml_parser.js [hunk 5]
```diff
@@ -328,6 +328,10 @@ class SimpleDOMNode {
       .join("");
   }
 
+  get children() {
+    return this.childNodes;
```
Comment (Snuffleupagus) [inline src/core/xml_parser.js:332]: Given the method just below, it seems that `this.childNodes` could *possibly* be undefined in the general case.
Hence it seems like a good idea to prevent run-time errors elsewhere, by doing:
```javascript
return this.childNodes || [];
```

File: src/core/dataset_reader.js [hunk 6]
```diff
@@ -0,0 +1,70 @@
...
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+import { parseXFAPath } from "./core_utils.js";
+import { SimpleXMLParser } from "./xml_parser.js";
+
+class DataSetXMLParser extends SimpleXMLParser {
```
Comment (Snuffleupagus) [inline src/core/dataset_reader.js:19]: Spelling-nit: Let's call this one `DatasetXMLParser` instead, note the casing, since that'd be consistent with the casing used everywhere else in this patch :-)

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]

File: src/core/document.js (hunk 4 above)
Comment (calixteman) [reply src/core/document.js:824]: Yes you're right, I'll do a follow-up PR.

**Review by Snuffleupagus — APPROVED** [review]
r=me, this looks reasonable; thank you!
