### PR TITLE
Attempt to fix the `Array.prototype.includes` and `String.prototype.includes` polyfills (issue 9514, 9516)

### LINKED ISSUE #9514: Warning: FormatError: Required "loca" table is not found in Internet Explorer
Attach (recommended) or Link to PDF file here:
http://edelman.amsterdam/wp-content/uploads/Terms_Conditions_NL.pdf

Configuration:
- Web browser and its version: Internet Explorer 11 version 11.248.16299.0
- Operating system and its version: Windows 10 Home version 1709 build 16299.248
- PDF.js version: 2.0.391
- Is a browser extension: no

Steps to reproduce the problem:
1. Render the pdf in internet explorer

What is the expected behavior? (add screenshot)
The pdf renders like it does in Chrome
Image of pdf in Chrome

What went wrong? (add screenshot)
The pdf doesn't render the font correctly and renders all sorts of random characters.
Image of pdf in Internet Explorer

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
If the information provided isn't enough I'm willing to create an example.

### LINKED ISSUE #9516: wrong polyfill with IE11 ?
schermata 2018-02-27 alle 15 11 26

Configuration:
- Web browser and its version: IE11
- Operating system and its version: Windows 7
- PDF.js version: not sure, but probably >= 2.0.0
- Is a browser extension: no

Steps to reproduce the problem:
1. open https://mozilla.github.io/pdf.js/web/viewer.html
2. try to use Array.prototype.includes()

What is the expected behavior? (add screenshot)

[1,2].includes(1) should return true, not false

### PR DESCRIPTION
**Pull request by Snuffleupagus**
I don't understand why the previous way importing the polyfills didn't work, and I don't have time to try and figure it out, however this patch seems to fix things.

Fixes #9514.
Fixes #9516.

### CODE REVIEW

File: src/shared/compatibility.js [hunk 1]
```diff
@@ -131,7 +131,7 @@ PDFJS.compatibilityChecked = true;
   if (String.prototype.includes) {
     return;
   }
-  String.prototype.includes = require('core-js/fn/string/includes');
```
Comment (Rob--W) [inline src/shared/compatibility.js]: Just remove the `String.prototype.includes =` part and this should work.

When you import `core-js/fn/string/includes`, then `String.prototype.includes` is already overwritten, which can be seen using the following example:

```
$ node -e 'delete String.prototype.includes; console.log("".includes); require("core-js/fn/string/includes"); console.log("abc".includes("a"))'
undefined
true
```

The exported function from `require('core-js/fn/string/includes')` does not use `this`, but expects the first parameter to be the string, and the other parameters to be the parameters for the string method. I.e. `require('core-js/fn/string/includes')("abc", "b");`. With the current (wrong) code, it becomes require('core-js/fn/string/includes').call("abc", "b")`, which becomes (since `this` is ignored) `require('core-js/fn/string/includes')("b")`, i.e. equivalent to `"b".includes(undefined)`.

The documentation at https://github.com/zloirock/core-js#usage also shows that the intended usage for the default mode is to just call `require` and not use its return value.

**Review by Rob--W — CHANGES_REQUESTED** [review]

File: src/shared/compatibility.js (hunk 1 above)
Comment (Snuffleupagus) [reply src/shared/compatibility.js]: Thank you; I've made the suggested changes and everything seems to work just fine now!

**Review by Rob--W — APPROVED** [review]

**Comment by Rob--W** [comment]
Squashed two bugs in one PR, good one!
