### PR TITLE
Preserve error types during translation

### LINKED ISSUE #11658: Preserve error types (e.g. InvalidPDFException, MissingPDFException)
Configuration:
- Web browser and its version: Chrome 80.0.3987.122 64-bit
- Operating system and its version: Windows 10 1909
- PDF.js version: 2.4.384 (build: 30e0f028)
- Is a browser extension: no

Steps to reproduce the problem:
1. Set a non-existing (404) PDF URL for the viewer
2. Open pdf.js
3. Open DevTools Inspector
4. Find uncaught error of generic error/exception type `Uncaught (in promise) Error: Missing PDF file.`

What is the expected behavior?
4. Find uncaught error of specific error/exception type `Uncaught (in promise) MissingPDFException: Missing PDF file.`

By preserving the exception type, more fine-grained error handling could be performed via client-side logic (e.g. redirect to a search page if a PDF is not found, or to a ticket system in case of invalid PDF files).

Apparently, the error message translation in [app.js](https://github.com/mozilla/pdf.js/blob/30e0f028b54c50b1bfe5d90e878b62003c8e5173/web/app.js#L816) always throws a generic Error instead of re-throwing with the same exception class of the previous exception.

IMHO, changing the exception class should be BC compatible, as the custom exceptions such as [MissingPDFException extend BaseException](https://github.com/mozilla/pdf.js/blob/30e0f028b54c50b1bfe5d90e878b62003c8e5173/src/shared/util.js#L437), which in turn [uses the generic Error as prototype](https://github.com/mozilla/pdf.js/blob/30e0f028b54c50b1bfe5d90e878b62003c8e5173/src/shared/util.js#L407).

Thank you very much!

### PR DESCRIPTION
**Pull request by xelan**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | yes
| Deprecations? | no
| Tickets       | Fix #11658 
| License       | Apache License 2.0

By preserving the exception type, more fine-grained error handling can be performed via client-side logic (e.g. redirect to a search page if a PDF is not found, or to a ticket system in case of invalid PDF files).

The original exception type and its properties (e.g. status code) are preserved by cloning the error object and assigning the translated message. Note that only a shallow clone is performed for simplicity.

Fixes #11658

### CODE REVIEW

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]
This seem like way too much code/complexity for an edge-case, and in a previous PR (see #11689) the consensus was that *if* this should be fixed then simply re-throwing the original exception would be preferable.

**Comment by xelan** [comment]
Ok, if the possible change of the original exception outside of pdf.js is acceptable, I can just rethrow the exception with the translated message, without any cloning :smile:

**Comment by xelan** [comment]
I've pushed the updated, simplified version which rethrows the original exception.

File: web/app.js [hunk 1]
```diff
@@ -817,7 +817,10 @@ const PDFViewerApplication = {
 
         return loadingErrorMessage.then(msg => {
           this.error(msg, { message });
-          throw new Error(msg);
+
+          exception.message = msg;
+
+          throw exception;
```
Comment (Snuffleupagus) [inline web/app.js:823]: This is still modifying, albeit less than the previously, the original exception though.

Why not simply `throw exception;` here, since the translation is mostly intended for the default viewer `errorWrapper`?

Comment (xelan) [reply web/app.js:823]: Thanks for your feedback, @Snuffleupagus!

That would of course also work. However it would be a BC break if an application using pdf.js relies on the translated exception message (e.g. to display user-facing error messages).

Comment (Snuffleupagus) [reply web/app.js:823]: The default viewer was created for usage in Firefox, and is *not* part of the versioned [public API](see https://github.com/mozilla/pdf.js/blob/master/src/display/api.js).
There's also the "viewer components", see https://github.com/mozilla/pdf.js/blob/master/web/pdf_viewer.component.js and the examples in https://github.com/mozilla/pdf.js/tree/master/examples/components, which we also attempt to not break unnecessarily.

For the [default viewer](https://github.com/mozilla/pdf.js/blob/master/web/app.js), while we don't go out of our way to break backwards compatibility, there's absolutely *no guarantees* that there won't be changes; note also that we even ask people not to use it as -is e.g. in http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

---

> [...] if an application using pdf.js relies on the translated exception message (e.g. to display user-facing error messages).

Apart from the above, this particular situation also seem to be enough of an edge-case that I wouldn't really consider the change I suggested above to be a problem.
It'd even be more consistent, since it means that the viewer is now returning *exactly* the same Errors as if the "raw" API was used directly.

Comment (timvandermeij) [reply web/app.js:823]: I agree with the above. This looks good if the original error is re-thrown, i.e., unchanged.

Comment (xelan) [reply web/app.js]: That sounds good, thank you very much for the feedback. I've adapted the code accordingly.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Let's do this. Thank you for your contribution!

**Comment by xelan** [comment]
> Let's do this. Thank you for your contribution!

Great :+1: Your welcome. Thanks for the feedback and the quick and professional handling.
