### PR TITLE
Fix integration tests on Mac

### LINKED ISSUE #17181: Integration tests broken on MacOS because "Control" is used instead of "Meta" for keyboard related tests
Right now a lot of tests are currently broken (hang) because eg. text cannot be selected. This happens because keyboard shortcuts like `Control` + `a` are sent. But those only work on Linux and Windows but fail on MacOS because `Meta` should be used instead.

Here a list of affected integration tests:

https://github.com/search?q=repo%3Amozilla%2Fpdf.js+path%3A%2F%5Etest%5C%2Fintegration%5C%2F%2F+Control&type=code

CC @calixteman

### PR DESCRIPTION
**Pull request by calixteman**
It's mainly a matter of keyboard shortcuts.
And it fixes few intermittents.

### CODE REVIEW

File: test/integration/test_utils.mjs [hunk 1]
```diff
@@ -251,40 +257,160 @@ async function waitForTextLayer(page) {
...
-  await promise;
   await page.waitForFunction(
     sel => {
+      const toolbarHeight = document
+        .querySelector("#toolbarContainer")
+        .getBoundingClientRect().height;
       const element = document.querySelector(sel);
       const { top, bottom } = element.getBoundingClientRect();
-      return Math.abs(top) < 100 || Math.abs(bottom - window.innerHeight) < 100;
+      console.log(sel, top, bottom, toolbarHeight, window.innerHeight);
```
Comment (Snuffleupagus) [inline test/integration/test_utils.mjs:271]: Left-over debug statement?

File: test/integration/test_utils.mjs [hunk 2]
```diff
@@ -34,9 +37,8 @@ function loadAndWait(filename, selector, zoom, pageSetup) {
       });
 
       let url = `${global.integrationBaseUrl}?file=/test/pdfs/${filename}`;
-      if (zoom) {
-        url += `#zoom=${zoom}`;
-      }
+      url += `#zoom=${zoom ?? "page-fit"}`;
```
Comment (Snuffleupagus) [inline test/integration/test_utils.mjs:40]: This feels somewhat unrelated to the title "Fix integration tests on Mac", why do we need this?

**Review by Snuffleupagus — COMMENTED** [review]
> It's mainly a matter of keyboard shortcuts.
> And it fixes few intermittents.

Could these two things perhaps be split into *two separate* commits (but in the same PR), since fixing the keyboard shortcuts feels like a mostly mechanical change and given the size of this it's a bit difficult to (easily) spot the "intermittents"-part?

File: test/integration/test_utils.mjs (hunk 2 above)
Comment (calixteman) [reply test/integration/test_utils.mjs:40]: I've a macbook and its screen is not that big, so some element we want to click on weren't visible.
So instead of adding a lot of scrollIntoView everywhere it was easier to just show all the page, so it's related.

**Comment by whimboo** [comment]
Closes #17181.

**Comment by whimboo** [comment]
I can confirm that this PR fixes all the issues that I have seen over on #17181 for both Firefox and Chrome with the CDP protocol enabled. Thanks a lot!

File: test/integration/freetext_editor_spec.mjs [hunk 3]
```diff
@@ -2448,12 +2446,12 @@ describe("FreeText Editor", () => {
               return { x, y };
             });
             const oldPos = allPositions[i];
-            expect(Math.round(pos.x - oldPos.x))
+            expect(Math.abs(Math.round(pos.x - oldPos.x) - 39) <= 1)
               .withContext(`In ${browserName}`)
-              .toEqual(39);
-            expect(Math.round(pos.y - oldPos.y))
+              .toEqual(true);
```
Comment (Snuffleupagus) [inline test/integration/freetext_editor_spec.mjs:2451]: Here, and below, can we perhaps make use of built-in Jasmine methods?
```javascript
expect(Math.abs(Math.round(pos.x - oldPos.x) - 39))
  .withContext(`In ${browserName}`)
  .toBeLessThanOrEqual(1);
```

File: test/integration/test_utils.mjs (hunk 2 above)
Comment (Snuffleupagus) [inline test/integration/test_utils.mjs:40]: If the zoom argument is always set, I think this can be a `const` instead?
```javascript
const url =
  `${global.integrationBaseUrl}?file=/test/pdfs/${filename}#zoom=${zoom ?? "page-fit"}`;
```

File: test/integration/test_utils.mjs [hunk 4]
```diff
@@ -251,40 +251,159 @@ async function waitForTextLayer(page) {
...
 
+async function hover(page, selector) {
+  const rect = await page.$eval(selector, el => {
+    const { x, y, width, height } = el.getBoundingClientRect();
+    return { x, y, width, height };
+  });
+  await page.mouse.move(rect.x + rect.width / 2, rect.y + rect.height / 2);
+}
+
+const meta = isMac ? "Meta" : "Control";
```
Comment (Snuffleupagus) [inline test/integration/test_utils.mjs:284]: Would it make sense to tweak the name slightly here, e.g. as follows?
```suggestion
const modifier = isMac ? "Meta" : "Control";
```

File: test/integration/test_utils.mjs [hunk 5]
```diff
@@ -251,40 +251,159 @@ async function waitForTextLayer(page) {
...
+    await page.keyboard.press("y");
+    await page.keyboard.up("Control");
+  }
+}
+async function kbSelectAll(page) {
+  await page.keyboard.down(meta);
+  await page.keyboard.press("a", { commands: ["SelectAll"] });
+  await page.keyboard.up(meta);
+}
+async function kbMetaDown(page) {
```
Comment (Snuffleupagus) [inline test/integration/test_utils.mjs:318]: Assuming that the suggestion above is implemented:
```suggestion
async function kbModifierDown(page) {
```

File: test/integration/test_utils.mjs [hunk 6]
```diff
@@ -251,40 +251,159 @@ async function waitForTextLayer(page) {
...
+  await page.keyboard.down(meta);
+}
+async function kbMetaUp(page) {
```
Comment (Snuffleupagus) [inline test/integration/test_utils.mjs:321]: Assuming that the suggestion above is implemented:
```suggestion
async function kbModifierUp(page) {
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, with a few suggestions and passing test; thank you!

**Comment by timvandermeij** [comment]
Thank you for doing this; extracting those helper functions makes the individual tests easier!
