### PR TITLE
Fix intermittent failure in the viewer alert tests

### LINKED ISSUE #20105: [Bug]: Intermittent failure in the viewer alert tests
### Attach (recommended) or Link to PDF file

N/A

### Web browser and its version

Firefox 140.0.4

### Operating system and its version

Arch Linux

### PDF.js version

5.3.93

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open http://54.193.163.58:8877/ae9ca6e62123620/output.txt (bot logs from PR https://github.com/mozilla/pdf.js/pull/20104).
2. Notice the following failure in the stamp integration test:

```
2) Stamp Editor Basic operations must load a PNG which is bigger than a page
  Message:
[31m    Expected '' to equal 'Image added'.[0m
  Stack:
        at <Jasmine>
        at file:///C:/pdfjs/botio-files-pdfjs/private/ae9ca6e62123620/test/integration/stamp_editor_spec.mjs:129:25
        at async Promise.all (index 0)
        at async UserContext.<anonymous> (file:///C:/pdfjs/botio-files-pdfjs/private/ae9ca6e62123620/test/integration/stamp_editor_spec.mjs:116:7)
```

### What is the expected behavior?

The test should pass consistently.

### What went wrong?

The test fails intermittently.

### Link to a viewer

_No response_

### Additional context

The intermittently failing assertion in this test was introduced in https://github.com/mozilla/pdf.js/pull/20055 and was introduced in four other editor tests too. It's possible to easily reproduce this locally by introducing a delay here which makes the test permafail:

https://github.com/mozilla/pdf.js/blob/daf2cbbfe9d6ad0588fdded9c9a99f57b3121ec3/src/display/editor/stamp.js#L488

### PR DESCRIPTION
**Pull request by timvandermeij**
It takes some time for the viewer alert to be updated after the editor is committed, but the current tests don't await that and proceed too fast to the viewer alert string assertion. This commit fixes the issue by waiting for the expected viewer alert string to appear instead.

Fixes #20105.

### CODE REVIEW

File: test/integration/freetext_editor_spec.mjs [hunk 1]
```diff
@@ -111,8 +111,9 @@ describe("FreeText Editor", () => {
           await waitForSelectedEditor(page, editorSelector);
           await waitForStorageEntries(page, 1);
 
-          const alert = await page.$eval("#viewer-alert", el => el.textContent);
```
Comment (timvandermeij) [inline test/integration/freetext_editor_spec.mjs:114]: Note that, as a small bonus, we don't shadow the `alert` builtin anymore with this change.

**Review by calixteman — APPROVED** [review]
LGTM. Thank you.
