### PR TITLE
[api-minor] Ensure that the `getDocument` Promise is rejected if the `loadingTask` is destroyed, or an `Error` is thrown, inside of the `onPassword` callback (issue 7806)

### LINKED ISSUE #7806: Handle loading abort/failure in password callback
I am using pdf.js for my project and I am facing issue with encrypted pdf's. I am using PDF.js passwordCallback function to provide the password.

```
PDFJS.getDocument(file, null, passwordCB, null).then(function (res) {
    console.log("Document Decrypted);
});
```

Here is the passwordCallback Function

```
var passwordCB = function (passwordFunc, reason) {
      if (reason === 1) {
        passwordFunc(pdfpassword);
      } else {
        console.log("Wrong Password");
      }
    };
```

When a wrong password is provided, the control do not get out of passwordCB function (promise is not returned). It get's stuck until a valid password is provided.

So when user enters a wrong password I have to tell them that the password is wrong and need to get a new password. I am using a custom popup to get the password from user.

Is there a way to break the passwordCallback function and return to the getDocument() promise when a wrong password is entered, so that I can call the getDocument again with the new password that the user enters?

Also, from the source code it is mentioned that the passwordCallback is deprecated.

```
    * @param {function} passwordCallback (deprecated) It is used to request a
    * password if wrong or no password was provided. The callback receives two
    * parameters: function that needs to be called with new password and reason
    * (see {PasswordResponses}).
```

Is there any other way for dealing with password callbacks? Any article or example on this scenario?

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Tentatively fixes #7806 (and replaces PR #7924).

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/pdf.js/7926)

### CODE REVIEW

File: src/display/api.js [hunk 1]
```diff
@@ -1508,28 +1512,28 @@ var WorkerTransport = (function WorkerTransportClosure() {
...
+            loadingTask.onPassword(updatePassword, exception.code);
+            return this._passwordCapability.promise;
+          } catch (ex) { }
         }
-        loadingTask._capability.reject(
-          new PasswordException(exception.message, exception.code));
+        var error = new PasswordException(exception.message, exception.code);
+        loadingTask._capability.reject(error);
+
+        this._passwordCapability.reject(error);
```
Comment (yurydelendik) [inline src/display/api.js]: can you check for `!loadingTask.onPassword` and returned rejected promise (with PasswordException).

File: src/display/api.js [hunk 2]
```diff
@@ -1508,28 +1512,28 @@ var WorkerTransport = (function WorkerTransportClosure() {
...
+        return this._passwordCapability.promise;
       }, this);
 
+
```
Comment (yurydelendik) [inline src/display/api.js]: nit: remove unneeded line

File: src/core/worker.js [hunk 3]
```diff
@@ -671,11 +671,9 @@ var WorkerMessageHandler = {
...
       var onFailure = function(e) {
         if (e instanceof PasswordException) {
-          if (e.code === PasswordResponses.NEED_PASSWORD) {
-            handler.send('NeedPassword', e);
-          } else if (e.code === PasswordResponses.INCORRECT_PASSWORD) {
-            handler.send('IncorrectPassword', e);
-          }
+          handler.sendWithPromise('Password', e).then(function (data) {
+            pdfManager.updatePassword(data.password);
+          });
```
Comment (yurydelendik) [inline src/core/worker.js]: add `.catch(function (e) { handler.send('PasswordException', e); });`. (I'm not sure if we need to re-wrap `e`, but I think this will work out) We need to add 'PasswordException' handler, to abort loading task. `Password` can be `PasswordRequest` to avoid confusion.

Comment (yurydelendik) [inline src/core/worker.js]: The code at pdfManagerReady below looks non-symmetrical to recovery password handling. I think we shall remove pdfManager.passwordChanged/._passwordChangedCapability? The pdfManagerReady call will be called after password update (we need to move pdfManagerReady from being anonymous function to closure before getPdfManager() call).

**Review by yurydelendik — COMMENTED** [review]
It getting really complicated, thanks for working on this issue.

File: src/display/api.js [hunk 4]
```diff
@@ -1435,6 +1436,13 @@ var WorkerTransport = (function WorkerTransportClosure() {
       this.destroyed = true;
       this.destroyCapability = createPromiseCapability();
 
+      if (this._passwordCapability) {
+        var err = new Error('Worker was destroyed during onPassword callback');
+        this.loadingTask._capability.reject(err);
```
Comment (Snuffleupagus) [inline src/display/api.js]: *This is definitely getting more complicated than I imagined; thanks for your in-depth review comments thus far!*

I tried removing that, but it appears to be causing some problems:
When calling `loadingTask.destroy();` in the `onPassword` handler, it seems that the worker might be terminated *before* it has had a chance to send the (new) `PasswordException` (as outlined in comment https://github.com/mozilla/pdf.js/pull/7926/files#r94335620).

The `loadingTask` will thus remain in a pending state, without ever getting either resolved *or* rejected. Note that I'm seeing this both in manual tests in the viewer, as well as in the unit-tests.

How would you propose that we handle this case?
Could/should we use the `WorkerTask` (in worker.js) to track the password promise there, to ensure that worker termination waits for the rejected `_passwordCapability` from api.js?

File: src/core/worker.js (hunk 3 above)
Comment (Snuffleupagus) [inline src/core/worker.js]: > add .catch(function (e) { handler.send('PasswordException', e); });. (I'm not sure if we need to re-wrap e, but I think this will work out)

I complication here is that the exception that we will thus `catch`, is actually a `string` rather than an actual `Error` here since `postMessage` has issues with serializing those.

For now, the patch is still sending the original `PasswordException` in this case, since I'm having trouble getting this to work properly otherwise.

**Comment by Snuffleupagus** [comment]
@yurydelendik Thanks for the in-depth review comments! I've tried to address them, but there's a couple of things I'm entirely sure how to handle, please see https://github.com/mozilla/pdf.js/pull/7926#discussion_r94344712 and https://github.com/mozilla/pdf.js/pull/7926#discussion_r94398272.

**Review by yurydelendik — APPROVED** [review]
Looks good to me. From the comments above I did not get if there are any issues, but that's what I had in mind (except WorkerTask, but it's okay to have it). Thank you for the patch.
