### PR TITLE
[Editor] Add the possibility to update an existing annotation with some new properties when saving or printing

### LINKED ISSUE #15403: Support editing already existing annotations
Attach (recommended) or Link to PDF file here:
[dummy.pdf](https://github.com/mozilla/pdf.js/files/9497274/dummy.pdf)

Configuration:
- Tested in firefox beta and nightly.
- Microsoft Windows 10.
- Whatever pdf.js version comes with firefox beta and nightly.
- No, not an extension.

Steps to reproduce the problem:
1. Add a text annotation (Same thing applies if you used the ink annotation, but for this example we shall just use the text annotation) to the attached dummy.pdf (It can be anything, like foo, bar, foobar, and whatever else you want)
2. Save the PDF under a different name (It could be dummytwo.pdf it doesn't matter as long as its a separate file)

What is the expected behavior? (add screenshot)
I should be able to select the saved annotation (this issue applies to any PDF with saved annotations as well, not just made in pdf.js) and delete it or modify it further.
dummypdf

What went wrong?
I cannot delete it or edit it. As indicated by the screenshot, it acknowledges the existence of the annotation, but I can't delete it or modify it. I should be able to delete annotations or edit annotations made in pdf.js as well as any other PDF reader/writer that can make annotations.

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

File: src/core/document.js [hunk 1]
```diff
@@ -446,6 +472,23 @@ class Page {
...
+        // property). In this case, we replace the old annotation by the new
+        // one.
+        for (let i = 0, ii = newAnnotations.length; i < ii; i++) {
+          const newAnnotation = newAnnotations[i];
+          if (newAnnotation.refToReplace) {
+            const j = annotations.findIndex(
+              a => a.ref === newAnnotation.refToReplace
+            );
+            if (j >= 0) {
+              annotations.splice(j, 1, newAnnotation);
```
Comment (Snuffleupagus) [inline src/core/document.js:485]: Given how Objects, remember that Arrays are essentially a special-case of those, are passed by reference in JavaScript this will modify the cached annotations-data and affect future `getAnnotations`-calls in a way that I cannot imagine is correct/intended here.

Fixing this ought to mean simply adding `annotations = annotations.slice();` e.g. [before this line](https://github.com/mozilla/pdf.js/pull/16523/files#diff-f0385d138acfe65f04aec809ad0522722883e56b6420ccb8f1d2e16b50631c1eR475), another *possible* solution might be to just place [this new line](https://github.com/mozilla/pdf.js/pull/16523/files#diff-f0385d138acfe65f04aec809ad0522722883e56b6420ccb8f1d2e16b50631c1eR491) at that spot instead.

File: src/core/document.js [hunk 2]
```diff
@@ -688,6 +731,20 @@ class Page {
     return shadow(this, "_parsedAnnotations", parsedAnnotations);
   }
 
+  get _idToRefMap() {
+    const promise = this._parsedAnnotations.then(annotations => {
+      const idToRefMap = new Map();
+      for (const annotation of annotations) {
+        if (!annotation) {
```
Comment (Snuffleupagus) [inline src/core/document.js:738]: Please make sure that the `ref`-property actually exists, note a previous comment above.
```suggestion
        if (!annotation?.ref) {
```

File: src/display/annotation_storage.js [hunk 3]
```diff
@@ -176,8 +176,13 @@ class AnnotationStorage {
     const clone = new Map();
 
     for (const [key, val] of this.#storage) {
-      const serialized =
-        val instanceof AnnotationEditor ? val.serialize() : val;
+      let serialized = val;
+      if (val instanceof AnnotationEditor) {
+        serialized = val.serialize();
+        if (!val.hasElementChanged(serialized)) {
+          serialized = null;
```
Comment (Snuffleupagus) [inline src/display/annotation_storage.js:183]: This can be slightly shorter as:
```suggestion
        if (val.hasElementChanged(serialized)) {
          continue;
```

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]
Adding a few comments based on a quick look.

File: src/core/document.js [hunk 4]
```diff
@@ -258,6 +258,22 @@ class Page {
     );
   }
 
+  async replaceIdByRef(annotations, deletedAnnotations) {
+    let idToRefMap = null;
+    for (const annotation of annotations) {
+      if (annotation.id) {
+        idToRefMap ||= await this._idToRefMap;
+        const ref = idToRefMap.get(annotation.id);
```
Comment (Snuffleupagus) [inline src/core/document.js:266]: Don't you need to handle a `ref` not being found here, to prevent issues below in this method (since calling `RefSet.property.put` with `undefined` will throw)?
(As mentioned previously, in some *very rare* cases annotations may be "raw" dictionaries.)
```suggestion
        const ref = idToRefMap.get(annotation.id);
        if (!ref) {
          continue;
        }
```

File: src/core/document.js [hunk 5]
```diff
@@ -401,15 +422,21 @@ class Page {
     const newAnnotationsByPage = !this.xfaFactory
       ? getNewAnnotationsMap(annotationStorage)
       : null;
+    const deletedAnnotations = new RefSet();
 
     let newAnnotationsPromise = Promise.resolve(null);
     if (newAnnotationsByPage) {
       const newAnnotations = newAnnotationsByPage.get(this.pageIndex);
       if (newAnnotations) {
```
Comment (Snuffleupagus) [inline src/core/document.js:430]: Nit: Maybe avoid creating an unnecessary `RefSet`-instance by default?
```suggestion
    let deletedAnnotations = null;

    let newAnnotationsPromise = Promise.resolve(null);
    if (newAnnotationsByPage) {
      const newAnnotations = newAnnotationsByPage.get(this.pageIndex);
      if (newAnnotations) {
        deletedAnnotations = new RefSet();
```

**Review by Snuffleupagus — COMMENTED** [review]
Please also run all tests and I'll try to do a final review during the weekend.

File: src/core/document.js (hunk 4 above)
Comment (calixteman) [reply src/core/document.js:266]: Do you have an example of a pdf containing such annotations ?

File: src/core/document.js [hunk 6]
```diff
@@ -258,6 +258,26 @@ class Page {
...
+  async replaceIdByRef(annotations, deletedAnnotations) {
+    let idToRefMap = null;
+    for (const annotation of annotations) {
+      if (annotation.id) {
+        idToRefMap ||= await this._idToRefMap;
+        const ref = idToRefMap.get(annotation.id);
+        if (!ref) {
+          warn(`A non-linked annotation cannot be modified: ${annotation.id}`);
+          continue;
+        }
```
[the remark this answers is not in the document]
Comment (calixteman) [reply src/core/document.js]: Good idea!
I moved the ref parsing in the Ref object in order to everything in the same place.

File: src/core/primitives.js [hunk 7]
```diff
@@ -279,6 +279,21 @@ class Ref {
...
+      return ref;
+    }
+    const [num, gen] = str.split("R", 2);
+    if (isNaN(num) || (gen && isNaN(gen))) {
+      return null;
+    }
+
+    // eslint-disable-next-line no-restricted-syntax
+    RefCache[str] = ref = new Ref(parseInt(num), !gen ? 0 : parseInt(gen));
+    return ref;
```
Comment (Snuffleupagus) [inline src/core/primitives.js:294]:
```suggestion
    return (RefCache[str] = new Ref(parseInt(m[1]), m[2] ? parseInt(m[2]) : 0));
```

File: src/core/primitives.js [hunk 8]
```diff
@@ -279,6 +279,21 @@ class Ref {
...
 
+  static fromString(str) {
+    let ref = RefCache[str];
+    if (ref) {
+      return ref;
+    }
+    const [num, gen] = str.split("R", 2);
+    if (isNaN(num) || (gen && isNaN(gen))) {
+      return null;
+    }
```
[the remark this answers is not in the document]
Comment (calixteman) [reply src/core/primitives.js:290]: Yep I knew that but I thought it was enough.
Do we have to be that much defensive ?
Aren't devs (other than us) supposed to pass the correct data ?

[the remark this answers is not in the document]
Comment (Snuffleupagus) [reply src/core/primitives.js:290]: Given that this is accessible through the API, and a third-party user may modify the contents of the `AnnotationStorage`, I think that we should ensure that we don't generate any bogus `Ref`s here. Note that even we may, at some future point, end up *accidentally* passing incorrect data this method.

Besides, considering how rarely this will be used I don't really expect proper validate to affect performance noticeably here.

File: src/core/document.js [hunk 9]
```diff
@@ -258,6 +258,24 @@ class Page {
     );
   }
 
+  replaceIdByRef(annotations, deletedAnnotations) {
```
Comment (Snuffleupagus) [inline src/core/document.js:261]: Now that we're able to use modern JavaScript also in the worker-thread, perhaps just do the following?
(The nice thing about using private fields/methods wherever possible, is that ESLint will complain if it ever becomes unused.)
```suggestion
  #replaceIdByRef(annotations, deletedAnnotations) {
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you!
