### PR TITLE
Respect `maxCanvasPixels` when computing canvas dimensions

### LINKED ISSUE #18105: Introduce tests for CSS-only zooming
In PR #18077 we found that we currently don't have any tests for the CSS-only zooming functionality in the viewer. We should ideally implement two (most likely integration) tests:

- a first (basic) test that zooms in to the point where CSS-only zooming is activated and that asserts that the canvas is still rendered correctly;
- a second test that serves as a regression test for #18077 (see https://github.com/mozilla/pdf.js/pull/18077#issuecomment-2110687533).

/cc @nicolo-ribaudo

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
Closes https://github.com/mozilla/pdf.js/issues/18105

Review this PR disabling whitespace changes, since one of the existing tests is indented and it makes the diff quite confusing.

### CODE REVIEW

File: test/integration/viewer_spec.mjs [hunk 1]
```diff
@@ -129,50 +111,177 @@ describe("PDF viewer", () => {
...
+            expect(canvasSize)
+              .withContext(`In ${browserName}`)
+              .toBeLessThan(originalCanvasSize * factor ** 2);
+
+            // Disabled because `canvasSize` is `4_012_800`, which is
+            // close to the limit but somehow a bit more.
+            //
+            //  expect(canvasSize)
+            //    .withContext(`In ${browserName}, MAX_CANVAS_PIXELS`)
+            //    .toBeLessThan(MAX_CANVAS_PIXELS);
```
Comment (nicolo-ribaudo) [inline test/integration/viewer_spec.mjs:281]: This seems like a bug, I will investigate.

File: web/ui_utils.js [hunk 2]
```diff
@@ -306,9 +306,12 @@ function approximateFraction(x) {
   return result;
 }
 
-function roundToDivide(x, div) {
-  const r = x % div;
-  return r === 0 ? x : Math.round(x - r + div);
```
Comment (nicolo-ribaudo) [inline web/ui_utils.js:311]: This logic was introduced by https://github.com/mozilla/pdf.js/pull/6552. By doing `x - (x % div) + div` we were:
- always rounding up, since we were adding 1div to floor<sub>multiples of div</sub>(x)
- given that `div` is an integer, `x - (x % div)` is a multiple of `div` (thus, an integer) and `x - (x % div) + div` is also an integer, so there is no need to `round()`.

Comment (calixteman) [reply web/ui_utils.js:311]: And what's the problem with rounding up instead of flooring ?

Comment (nicolo-ribaudo) [reply web/ui_utils.js:311]: That by rounding up when you are already close to the maximum you end up going above the maximum.

**Comment by nicolo-ribaudo** [comment]
The "PDF viewer CSS-only zoom triggers when going bigger than maxCanvasPixels test correctly configured" failure means that the numbers I hard-coded don't work for these tests on the CI machine.

I picked them based on how big the Firefox/Chrome windows were on my machine when running the tests. Do you know:
- how big the viewport is in the bot
- if I can hard-coded a viewport size?

**Comment by timvandermeij** [comment]
I'm not sure how big the viewport is on the bots, but in general I think we should probably set a fixed viewport size for the integration tests to eliminate any possible differences between configurations (since we also want everything to work correctly locally where window sizes might differ). Fortunately Puppeteer already seems to support this in the `launch()` call, refer to https://pptr.dev/api/puppeteer.browserconnectoptions#properties, and this _should_ not cause other tests to fail (and if they do, we found an implicit dependency on the viewport size which we should then fix).

**Comment by timvandermeij** [comment]
The default viewport property for the `launch()` call turns out to already be set at https://github.com/mozilla/pdf.js/blob/bb73d2a92240a5177268a652f400a98805f83682/test/test.mjs#L888 but it's set to `null` instead of a fixed value. That dates back to my initial commit that introduced Puppeteer, but I don't really know why I set it like that anymore... I would say that we can pick a standard value (maybe 1024x768 or 1280x1024) here which should be fine for any modern configuration.

**Comment by timvandermeij** [comment]
Good point. Alternatively, instead of setting a fixed viewport, it might also be possible to dynamically determine the values in this PR based on the active viewport size which can be fetched using e.g. the approach from https://stackoverflow.com/questions/1248081/how-to-get-the-browser-viewport-dimensions? That way we keep the current viewport behavior while also having a way to adjust the values correctly.

File: web/ui_utils.js [hunk 3]
```diff
@@ -306,9 +307,12 @@ function approximateFraction(x) {
...
+/**
+ * @param {number} x A positive number to round to a multiple of `div`
+ * @param {number} div A natural number
```
Comment (Snuffleupagus) [inline web/ui_utils.js:312]: Nit:
```suggestion
 * @param {number} x - A positive number to round to a multiple of `div`.
 * @param {number} div - A natural number.
```

**Comment by nicolo-ribaudo** [comment]
It turns out that my test was _not_ depending on the viewport dimensions :) The PDF size is guaranteed to be consistent, given that it's always reset to "50%" in `beforeEach`. However, given a fixed PDF size, the canvas size depends on the pixel ratio.

I changed the options to pass a `maxCanvasPixels` based on the pixel ratio, which solves this problem.

File: test/integration/viewer_spec.mjs [hunk 4]
```diff
@@ -178,15 +178,21 @@ describe("PDF viewer", () => {
     describe("triggers when going bigger than maxCanvasPixels", () => {
       let pages;
 
-      const MAX_CANVAS_PIXELS = 4_000_000;
+      const MAX_CANVAS_PIXELS = new Map();
```
Comment (timvandermeij) [inline test/integration/viewer_spec.mjs:181]: Shouldn't all test changes, except for the uncommenting of the previously failing test below, be moved into the first commit instead? That way we have a clear separation where one commit only includes the test, which the failing bit commented out, and one commit that only fixes the found issue and uncomments the failing bit.

Comment (nicolo-ribaudo) [reply test/integration/viewer_spec.mjs:181]: Oh yes, I forgot I had two commits when changing these files.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you for improving this!
