### PR TITLE
Parenthesis in names are not escaped when saving

### LINKED ISSUE #12654: Wrong display and invalid values in AP dictionary of radio button group when filled/saved
Attach (recommended) or Link to PDF file here:
[Subscription-tekMag.pdf](https://github.com/mozilla/pdf.js/files/5591356/Subscription-tekMag.pdf)
[Subscription-tekMag-filled-by-pdfjs.pdf](https://github.com/mozilla/pdf.js/files/5591357/Subscription-tekMag-filled-by-pdfjs.pdf)

Configuration:
- Web browser and its version: FF 83.0
- Operating system and its version: Windows 10 Pro 
- PDF.js version: 2.7.99 / 2.7.295
- Is a browser extension: yes / [no](https://mozilla.github.io/pdf.js/web/viewer.html)

Steps to reproduce the problem:
1. Open document [Subscription-tekMag.pdf](https://github.com/mozilla/pdf.js/files/5591356/Subscription-tekMag.pdf)
2. See the wrong rendered appearances
3. Choose a subscription through the radio button group (Choose your Subscription)
4. Save the document (STRG+S)

What is the expected behavior? 
grafik

What went wrong? 
grafik

Also when the file is saved the AP dictionary has invalid data and the radio button groups are not useable anymore. E.g.:

    /N << /2#20years,#2024#20issues#20(digital#20download#20only) 162 0 R>>

Looks like the name is not escaped correctly.

(The checkbox at the end has also a strange behavior (always locked when saved) - ping me, if I should open an additional issue for this one)

### PR DESCRIPTION
**Pull request by calixteman**
it aims to fix #12654.

### CODE REVIEW

File: src/core/core_utils.js [hunk 1]
```diff
@@ -205,7 +205,13 @@ function escapePDFName(str) {
...
   for (let i = 0, ii = str.length; i < ii; i++) {
     const char = str.charCodeAt(i);
-    if (char < 0x21 || char > 0x7e || char === 0x23) {
+    if (
+      char < 0x21 ||
+      char > 0x7e ||
+      char === 0x23 /* # */ ||
+      char === 0x28 /* ( */ ||
+      char === 0x29 /* ) */
+    ) {
```
Comment (JanSlabon) [inline src/core/core_utils.js:214]: A Name object should escape ALL possible delemitter and not only these 3. So I would say that these are still missing: `<>[]{}\%`

Comment (calixteman) [reply src/core/core_utils.js:214]: That's correct, I'm fixing that, thx.

Comment (timvandermeij) [reply src/core/core_utils.js:214]: For our reference, is this mentioned somewhere in the PDF specification so we can verify this patch? The change itself looks good if for all characters a unit test is available, but it would be good to check with the specification too.

Comment (JanSlabon) [reply src/core/core_utils.js:214]: In PDF 32000-1:2008 it is 7.5.3:

> a) A NUMBER SIGN (23h) (#) in a name shall be written by using its 2-digit hexadecimal code (23), preceded by the NUMBER SIGN.
b ) Any character in a name that is a regular character (other than NUMBER SIGN) shall be written as itself or by using its 2-digit hexadecimal code, preceded by the NUMBER SIGN.
c) Any character that is not a regular character shall be written using its 2-digit hexadecimal code, preceded by the NUMBER SIGN only.

> White space used as part of a name shall always be coded using the 2-digit hexadecimal notation and no white space may intervene between the SOLIDUS and the encoded name.
> Regular characters that are outside the range EXCLAMATION MARK(21h) (!) to TILDE (7Eh) (~) should be written using the hexadecimal notation.

The quoted characters are all delemiter characters (see 7.2.2 Character Set). If you would not escape them a new object will begin ;-)

File: src/core/core_utils.js [hunk 2]
```diff
@@ -205,7 +205,23 @@ function escapePDFName(str) {
   let start = 0;
   for (let i = 0, ii = str.length; i < ii; i++) {
     const char = str.charCodeAt(i);
-    if (char < 0x21 || char > 0x7e || char === 0x23) {
+    // whites or delimiter aren't regular chars
+    // so escape them
```
Comment (Snuffleupagus) [inline src/core/core_utils.js:209]: "whites", did you actually mean "whitespace" here?

Also, please improve the formatting of this comment, since the line-break is just overall confusing (i.e. is this intended to be two sentences, or not):
```suggestion
    // Whitespace or delimiters aren't regular chars, so escape them.
```

File: src/core/core_utils.js (hunk 1 above)
Comment (timvandermeij) [reply src/core/core_utils.js:223]: For future reference: it's in section 7.3.5, not 7.5.3, but it does allow us to check this patch against. Thanks!

Comment (JanSlabon) [reply src/core/core_utils.js:223]: ups, sorry... sure 7.3.5! It was late :-)

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you for fixing this!
