### PR TITLE
[Editor] Extract all the lines when adding a FreeText annotation

### LINKED ISSUE #17079: Text annotations with line breaks lose their first line
Attach (recommended) or Link to PDF file here: Can be reproduced on the demo page: https://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- Web browser and its version: Chrome latest
- Operating system and its version: Windows
 

Steps to reproduce the problem:
**1.  Click the Text annotation button
2. Type something. Press enter key. Type some more
3. Save the PDF**

What is the expected behavior? (add screenshot)
**The new PDF should have the full text annotation**

What went wrong? (add screenshot)
**The first line of the text annotation is omitted**

image

image

### PR DESCRIPTION
**Pull request by calixteman**
Fixes #17079.

### CODE REVIEW

File: src/display/editor/freetext.js [hunk 1]
```diff
@@ -386,13 +386,16 @@ class FreeTextEditor extends AnnotationEditor {
...
-    }
+    // We don't use innerText because there are some bugs with line breaks.
     const buffer = [];
-    for (const div of divs) {
-      buffer.push(div.innerText.replace(/\r\n?|\n/, ""));
+    this.editorDiv.normalize();
+    const nodes = this.editorDiv.childNodes;
+    const EOL_PATTERN = /\r\n?|\n/g;
+    for (let i = 0, ii = nodes.length; i < ii; i++) {
+      const child = nodes[i];
```
Comment (Snuffleupagus) [inline src/display/editor/freetext.js:395]: Can we use for...of iteration instead here, and "simply" this as follows?
```suggestion
    const EOL_PATTERN = /\r\n?|\n/g;
    for (const child of this.editorDiv.childNodes) {
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, with one question; thank you!
