### PR TITLE
Fix the endoffset of the last glyph when it's followed by a null offset in the loca table

### LINKED ISSUE #17671: Some characters are not displayed / rendered.
When we create simple and complex pdfs with Oracle Outside in Technology, we get pdfs as a result where some characters will not be displayed in pdf.js. But rendering / displaying these pdfs in Adobe Acrobat Reader and other web pdf viewer works fine.

Attached you will find a simple Excel converted to pdf with the text: Das ist ein Test
The t is missing , but text layer is working.

[Mappe123.pdf](https://github.com/mozilla/pdf.js/files/14277861/Mappe123.pdf)

Configuration:
- Web browser and its version:
Microsoft Edge (Chromium) Windows Version 121.0.2277.112, Chrome (Mac OS) Version 121.0.6167.160

- Operating system and its version:
Windows 11, MacOS 14.2.1

- PDF.js version:
PDF.js: 4.1.181 and PDF.js: 4.0.379

- Is a browser extension:
no

Steps to reproduce the problem:
1. open attached pdf in pdf.js
2. compare displaying result with adobe acrobat reader (and other)

What is the expected behavior? (add screenshot)
expecteddisplay

What went wrong? (add screenshot)
result

### PR DESCRIPTION
**Pull request by calixteman**
It fixes #17671.

### CODE REVIEW

File: src/core/fonts.js [hunk 1]
```diff
@@ -2117,6 +2117,11 @@ class Font {
         break;
       }
 
+      // If the last offset is 0 in the loca table then we can't compute the
+      // endOffset for the last glyph. So in such a case we set the endOffset
+      // to the end of the data (fixes issue #17671).
+      locaEntries.at(-2).endOffset ||= oldGlyfDataLength;
+
```
Comment (Snuffleupagus) [inline src/core/fonts.js:2124]: This seems somewhat related to existing code above, see https://github.com/mozilla/pdf.js/blob/14874e50b788cb8d2c57cdfa97d37fc0afe6c543/src/core/fonts.js#L2097-L2102

So, should this new block perhaps be placed just after (or somehow combined with) that code instead?

**Review by Snuffleupagus — COMMENTED** [review]
Please run all tests (this is the sort of change where knowing that all tests pass *before* reviewing seems helpful).

File: src/core/fonts.js (hunk 1 above)
Comment (calixteman) [reply src/core/fonts.js:2124]: Before running this loop, the locaEntries array is sorted by the offset when the fix is for the last element (last in term of index).
With the pdf in the bug, entry 10 (offset 0) is moved after entry 0 (offset 0 either), so the last element is now the offset for glyph 9. But for a non-buggy font, the last entry would be at the end because its offset is correct.
So I think it's the right place but I'm not 100% sure.

**Review by Snuffleupagus — APPROVED** [review]
Given the amount of test PDFs with TrueType fonts that exist in the test-suite this should (hopefully) be fine now.

r=me, thank you!
