### PR TITLE
[api-minor] Remove the use of (get/put)ImageData when drawing SMasks (bug 1874013)

### LINKED ISSUE #17785: Slow to render the 1st page of MagPi magazine issue 87
Attach (recommended) or Link to PDF file here:
https://magpi.raspberrypi.com/issues/87/pdf/download (once it autodownloads, it will open in a browser tab with PDFjs)

**Configuration:**
- Web browser and its version: Firefox 123
- Operating system and its version: Fedora 39
- PDF.js version: I don't know (what comes with the browser)
- Is a browser extension: No

**Steps to reproduce the problem:**
1. Open the file

**What went wrong?**

It takes 6-10 seconds to render the 1st page (subsequent pages are not affected). Better than Poppler, but still slow.

----

Corresponding Poppler issue, in case this helps for joint investigation: https://gitlab.freedesktop.org/poppler/poppler/-/issues/1473

### LINKED ISSUE #17838: Slow rendering of PDF with time spent in genericComposeSMask
Attach PDF file here: [d2_cheat_sheet.pdf](https://github.com/mozilla/pdf.js/files/14747604/d2_cheat_sheet.pdf)

Configuration:

- Web browser and its version: Firefox Nightly 2024-03-25
- Operating system and its version: macOS
- PDF.js version: ?
- Is a browser extension: browser-native

Steps to reproduce the problem:
1. Load the PDF

What is the expected behavior? It should draw quickly.

What went wrong? It was slow.

Profile: https://share.firefox.dev/49axVfO

---

The profile shows that all the time is spent waiting for readback in `getImageData` for `genericComposeSMask`.
What does `genericComposeSMask` do? Which APIs would be needed in canvas to allow implementing it on the GPU?

### PR DESCRIPTION
**Pull request by calixteman**
and implement then in using some SVG filters and composition. Composing in using destination-in in order to multiply RGB components by the alpha from the mask isn't perfect: it'd be a way better to natively have alpha masks support, it induces some small rounding errors and consequently computed RGB are approximatively correct.
In term of performance, it's a real improvement, for example, the pdf in issue #17779 is now rendered in few seconds.
There are still some room for improvement, but overall it should be a way better.

### CODE REVIEW

File: src/display/canvas.js [hunk 1]
```diff
@@ -1565,6 +1449,117 @@ class CanvasGraphics {
...
+        maskY + height > maskCanvas.height
+      ) {
+        const canvas = this.cachedCanvases.getCanvas(
+          "maskExtension",
+          width,
+          height
+        );
+        const ctx = canvas.context;
+        ctx.drawImage(maskCanvas, -maskX, -maskY);
+        if (backdrop.some(c => c !== 0)) {
```
Comment (Snuffleupagus) [inline src/display/canvas.js:1512]: Rather than checking this here and below, would it make sense to instead do that in the worker?
With the following change
```diff
diff --git a/src/core/evaluator.js b/src/core/evaluator.js
index b608feed6..fefd88160 100644
--- a/src/core/evaluator.js
+++ b/src/core/evaluator.js
@@ -515,6 +515,10 @@ class PartialEvaluator {
       if (smask?.backdrop) {
         colorSpace ||= ColorSpace.singletons.rgb;
         smask.backdrop = colorSpace.getRgb(smask.backdrop, 0);
+
+        if (smask.backdrop.every(c => c === 0)) {
+          smask.backdrop = null;
+        }
       }

       operatorList.addOp(OPS.beginGroup, [groupOptions]);
```
this line could become
```suggestion
        if (backdrop) {
```

File: src/display/canvas.js [hunk 2]
```diff
@@ -1565,6 +1449,117 @@ class CanvasGraphics {
...
+          ctx.globalCompositeOperation = "destination-atop";
+          ctx.fillStyle = Util.makeHexColor(...backdrop);
+          ctx.fillRect(0, 0, width, height);
+          ctx.globalCompositeOperation = "source-over";
+        }
+
+        maskCanvas = canvas.canvas;
+        maskX = maskY = 0;
+      } else if (backdrop.some(c => c !== 0)) {
```
Comment (Snuffleupagus) [inline src/display/canvas.js:1521]: If the idea above works:
```suggestion
      } else if (backdrop) {
```

**Review by Snuffleupagus — COMMENTED** [review]
This seems generally fine, with the movement in the reference-tests inline with what you'd expect from this sort of patch (since there's mostly off-by-one changes in the pixel-values).

*One thing to note, that however should __not__ block this PR:* This will "break", and essentially regress, SMask rendering in Node.js environments.
Given that the PDF.js library is still usable for general PDF parsing in Node.js, with only rendering affected, combined with Node.js being listed as "mostly" supported in the FAQ this seems fine to me.
Users affected by this should thus be encouraged to implement/polyfill (general) filter-support for Node.js environments.

File: src/display/canvas.js (hunk 1 above)
Comment (calixteman) [reply src/display/canvas.js:1512]: There's already a check here:
https://github.com/mozilla/pdf.js/pull/18029/files#diff-76166cff75cae0ec9c490ae47aebbdadff02dbc1e26caaf93779a1bace64dc47R1498
and if we do what you're proposing, then we won't enter in the above block.
Or am I missing something ?

Comment (Snuffleupagus) [reply src/display/canvas.js:1512]: Missed that, sorry!

**Comment by calixteman** [comment]
> _One thing to note, that however should **not** block this PR:_ This will "break", and essentially regress, SMask rendering in Node.js environments.

Did you already test pdf.js with https://www.npmjs.com/package/skia-canvas ? or with CanvasKit: https://www.npmjs.com/package/canvaskit-wasm ?

**Comment by Snuffleupagus** [comment]
> Did you already test pdf.js with https://www.npmjs.com/package/skia-canvas ? or with CanvasKit: https://www.npmjs.com/package/canvaskit-wasm ?

I've not done that, however it'd probably not help without additional work on the PDF.js side of things. (But as said above that should *not* block this PR.)

Note how nothing filter-related currently works in Node.js, since it's using
https://github.com/mozilla/pdf.js/blob/77e2182b8efc2846fdb60dd8eed70372edc900c5/src/display/node_utils.js#L83
which simply extends
https://github.com/mozilla/pdf.js/blob/77e2182b8efc2846fdb60dd8eed70372edc900c5/src/display/base_factory.js#L18-L38

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you!

**Comment by luckymore** [comment]
Good job, and When are we going to release it?
