### PR TITLE
Set a pages mapper per loaded document

### LINKED ISSUE #20629: [Bug]: Regression: "Invalid page request" when rendering multiple documents concurrently in v5.4.624
### Attach (recommended) or Link to PDF file

Since upgrading from pdf.js v5.4.530 to v5.4.624, rendering multiple PDF documents
concurrently can throw the following error:

    Error: Invalid page request

This happens even when:
- page numbers are valid
- rendering is sequential per document
- GlobalWorkerOptions.workerSrc is set only once

The exact same code works correctly in v5.4.530, without any modifications.

### Web browser and its version

Firefox 147.0.3 (64-bit)

### Operating system and its version

Linux debian 6.12.63+deb13-amd64

### PDF.js version

v5.4.624

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. View the minimal reproducible example (source code):
   https://gist.github.com/josepsanzcamp/c1f35173c39cf6908877fb28905090b6

2. Open the same example running directly in the browser (no build steps required):
   https://gist.githack.com/josepsanzcamp/c1f35173c39cf6908877fb28905090b6/raw/pdfjs-concurrent-documents-regression.html

3. The test renders 4 PDF documents concurrently.
4. Each document renders its pages sequentially, waiting for `render().promise`.
5. In v5.4.624 the error appears intermittently.
6. In v5.4.530 it never happens.

### What is the expected behavior?

All documents should render without errors.

### What went wrong?

Random `Invalid page request` errors are thrown.

### Link to a viewer

https://gist.githack.com/josepsanzcamp/c1f35173c39cf6908877fb28905090b6/raw/pdfjs-concurrent-documents-regression.html

### Additional context

- Adding delays (`setTimeout`) does not prevent the issue
- Rendering a single document works correctly
- Rendering multiple documents without chaining render promises also works
- The issue only appears when multiple documents render concurrently
  and pages are rendered sequentially per document

### PR DESCRIPTION
**Pull request by calixteman**
It fixes #20629.

### CODE REVIEW

File: web/pdf_viewer.js [hunk 1]
```diff
@@ -30,7 +30,6 @@ import {
   AnnotationEditorUIManager,
   AnnotationMode,
   MathClamp,
-  PagesMapper,
```
Comment (timvandermeij) [inline web/pdf_viewer.js:33]: I think that with this change nothing in `web/` uses `PagesMapper` anymore and it can thus be removed from `src/pdf.js` and the associated API surface tests too (that does technically make it an API-breaking change, but then again this functionality is very new and hopefully not used by anyone yet...).

**Review by timvandermeij — APPROVED** [review]
r=me, with the comment addressed and passing tests. Thank you for fixing this!
