### PR TITLE
Fix #7701: additional check for http/https protocols to fix unsafe he…

### LINKED ISSUE #7701: Angular 2/ExpressJS - Refused to get unsafe header “Accept-Ranges”
Using a webapp with NodeJS and ExpressJS as a server (CORS not configured) and Angular 2 for the client. I read here and there that I should enable CORS... I'm not sure where I should enable it and why should I enable CORS. The server is running in localhost.

Configuration:
- Web browser and its version: Chrome 53.0.2785.143
- Operating system and its version: Windows 10
- PDF.js version: 1.5.118 and 1.6.210
- Is an extension: - 

Steps to reproduce the problem:
1. Make a local server with NodeJS and ExpressJS
2. Make an Angular 2 app
3. Use an html input to upload any pdf
4. Read the pdf with FileReader (with .readAsDataURL)
5. Try to open the pdf with pdf.js as follow:

```
PDFJS.disableWorker = true;
PDFJS.getDocument(reader.result).then(function getPdf(pdf) {
        pdf.getPage(1).then(function getPage(page) {

        })
})
```

What is the expected behavior? (add screenshot)
Not getting an error...

What went wrong? (add screenshot)
Getting the following error:

```
pdf.worker.js:43268  -   Refused to get unsafe header "Accept-Ranges"
```

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### PR DESCRIPTION
**Pull request by mukulmishra18**
…ader request.

### CODE REVIEW

File: src/core/network.js [hunk 1]
```diff
@@ -377,6 +377,10 @@ if (typeof PDFJSDev !== 'undefined' && PDFJSDev.test('FIREFOX || MOZCENTRAL')) {
       var networkManager = this._manager;
       var fullRequestXhrId = this._fullRequestId;
       var fullRequestXhr = networkManager.getRequestXhr(fullRequestXhrId);
+      if (networkManager.isHttp) {
```
Comment (Snuffleupagus) [inline src/core/network.js]: Hasn't this condition accidentally become inverted!?
As far as I understand, we want to prevent issues when the request is *not* `http` or `https`, and this condition actually does the opposite!
So, I'd assume that you mean:
```javascript
if (!networkManager.isHttp) {
  return false;
}
```

Also, let's move this code block up to just after the `var networkManager = this._manager;` line instead.

File: src/core/network.js [hunk 2]
```diff
@@ -377,6 +377,10 @@ if (typeof PDFJSDev !== 'undefined' && PDFJSDev.test('FIREFOX || MOZCENTRAL')) {
...
+        return false;
+      }
+
```
Comment (Snuffleupagus) [inline src/core/network.js]: Nit: Please remove trailing whitespace.

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]

File: src/core/network.js (hunk 1 above)
Comment (mukulmishra18) [inline src/core/network.js]: Oh sorry, i accidentally missed  '!'.

> Also, let's move this code block up to just after the var networkManager = this._manager; line instead.

Okay, i will fix that, Thanks.

File: src/core/network.js (hunk 2 above)
Comment (mukulmishra18) [inline src/core/network.js]: Okay, Please find the PR below. Thanks for your review.

**Review by Snuffleupagus — COMMENTED** [review]
Please squash the commits, see https://github.com/mozilla/pdf.js/wiki/Squashing-Commits.

**Comment by mukulmishra18** [comment]
@Snuffleupagus, sorry for that, i am a beginner, and thanks for your advice. I will take care of that from now. Please guide me if i am making any mistake. ThankYou

**Review by Snuffleupagus — APPROVED** [review]

**Comment by Snuffleupagus** [comment]
> sorry for that, I am a beginner, and thanks for your advice. I will take care of that from now.

No worries! For future reference, https://github.com/mozilla/pdf.js/wiki/Contributing contains a lot of useful resources/information about the contribution work flow.

Thank you for the patch!
