### PR TITLE
Attempt to get bundlers to leave Emscripten Compiler generated `URL`s alone (issue 19761)

### LINKED ISSUE #19761: [Bug]: webpack wasm file resolve error in pdf.worker.mjs
### Attach (recommended) or Link to PDF file

This issue isn't specific to any PDF file, but I've created a [demo repository](https://github.com/hubgit/pdfjs-webpack/).

### Web browser and its version

N/A

### Operating system and its version

N/A

### PDF.js version

5.1.91

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Import `pdfjs-dist/build/pdf.worker.mjs`, e.g. by using `PDFJS.GlobalWorkerOptions.workerPort = new Worker(new URL('pdfjs-dist/build/pdf.worker.mjs', import.meta.url))` to configure PDF.js.
2. Run `webpack` to build the project.

### What is the expected behavior?

In PDF.js v4, the project compiles with no errors.

### What went wrong?

In PDF.js v5, an error is thrown for each of `qcms_bg.wasm` and `openjpeg.wasm`:

```
ERROR in ./node_modules/pdfjs-dist/build/pdf.worker.mjs 1833:21-61
Module not found: Error: Can't resolve 'qcms_bg.wasm' in '[...]/node_modules/pdfjs-dist/build'

ERROR in ./node_modules/pdfjs-dist/build/pdf.worker.mjs 5361:13-54
Module not found: Error: Can't resolve 'openjpeg.wasm' in '[...]/node_modules/pdfjs-dist/build'
```

### Link to a viewer

_No response_

### Additional context

The error is thrown because `pdf.worker.mjs` contains this code:

```js
function findWasmBinary() {
  if (Module["locateFile"]) {
    return locateFile("openjpeg.wasm");
  }
  return new URL("openjpeg.wasm", import.meta.url).href;
}
```

and this code:

```js
module_or_path = new URL('qcms_bg.wasm', import.meta.url);
```

and webpack tries to resolve `new URL("openjpeg.wasm", import.meta.url)` by finding `openjpeg.wasm` in the `build` folder.

One way to avoid the error is by using `webpackIgnore: true`:

```js
function findWasmBinary() {
  if (Module["locateFile"]) {
    return locateFile("openjpeg.wasm");
  }
  return new URL(/* webpackIgnore: true */ "openjpeg.wasm", import.meta.url).href;
}
```

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Note that we load all wasm-files manually, however the Emscripten Compiler (emcc) unfortunately generates `URL`s for fallback wasm-file loading.
In the PDF.js build-scripts we work-around that by using suitable Webpack-options, however that apparently doesn't work when third-party users re-bundle our code and we thus try to work-around this by adding "ignore comments" to these `URL`s (similar to how we handle `import`-statements).

### CODE REVIEW

**Review by nicolo-ribaudo — APPROVED** [review]

File: external/builder/babel-plugin-pdfjs-preprocessor.mjs [hunk 1]
```diff
@@ -173,6 +173,36 @@ function babelPluginPDFJSPreprocessor(babel, ctx) {
...
+        if (
+          t.isIdentifier(node.callee, { name: "URL" }) &&
+          node.arguments.length === 2
+        ) {
+          const [arg1, arg2] = node.arguments;
+
+          if (
+            arg1.type === "StringLiteral" &&
+            arg1.value.endsWith(".wasm") &&
+            arg2.type === "MemberExpression"
```
Comment (nicolo-ribaudo) [inline external/builder/babel-plugin-pdfjs-preprocessor.mjs:188]: The Babel plugin changes look good. Out of curiosity, is there any case in the codebase in which this MemberExpression check actually makes a difference?

Comment (Snuffleupagus) [reply external/builder/babel-plugin-pdfjs-preprocessor.mjs:188]: Not right now, as far as I can tell; my idea was just to reduce the risk of a future bug by being more specific.

Ideally we should check that the second argument is explicitly `import.meta.url`, however that seemed (with my limited Babel experience) to be fairly unwieldy so I figured that a simpler check might be good enough!?

Comment (nicolo-ribaudo) [reply external/builder/babel-plugin-pdfjs-preprocessor.mjs:188]: Yeah, I just opened https://github.com/babel/babel/issues/17225 to make it an easier check, but for now it would indeed be annoying to do it.
