### PR TITLE
Fix the "must work properly when selecting undo by keyboard" integration test

### LINKED ISSUE #19872: [Bug]: Intermittent failure in the "must work properly when selecting undo by keyboard" integration test
### Attach (recommended) or Link to PDF file

N/A

### Web browser and its version

Firefox 137.0.2

### Operating system and its version

Arch Linux

### PDF.js version

5.1.91

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

I have found that this integration test is one of the most common remaining intermittents now. The most recent occurrence is in https://github.com/mozilla/pdf.js/pull/19869. From http://54.241.84.105:8877/ac1262cf22c74ac/output.txt:

```
1) Highlight Editor Undo deletion popup has the expected behaviour must work properly when selecting undo by keyboard
  Message:
[31m    ProtocolError: script.callFunction timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.[0m
  Stack:
        at <instance_members_initializer> (file:///home/ubuntu/pdfjs/botio-files-pdfjs/private/ac1262cf22c74ac/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:97:14)
        at new Callback (file:///home/ubuntu/pdfjs/botio-files-pdfjs/private/ac1262cf22c74ac/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:101:16)
        at CallbackRegistry.create (file:///home/ubuntu/pdfjs/botio-files-pdfjs/private/ac1262cf22c74ac/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:20:26)
        at BidiConnection.send (file:///home/ubuntu/pdfjs/botio-files-pdfjs/private/ac1262cf22c74ac/node_modules/puppeteer-core/lib/esm/puppeteer/bidi/Connection.js:51:32)
        at Session.send (file:///home/ubuntu/pdfjs/botio-files-pdfjs/private/ac1262cf22c74ac/node_modules/puppeteer-core/lib/esm/puppeteer/bidi/core/Session.js:134:42)
        at Session.<anonymous> (file:///home/ubuntu/pdfjs/botio-files-pdfjs/private/ac1262cf22c74ac/node_modules/puppeteer-core/lib/esm/puppeteer/util/decorators.js:101:27)
        at WindowRealm.callFunction (file:///home/ubuntu/pdfjs/botio-files-pdfjs/private/ac1262cf22c74ac/node_modules/puppeteer-core/lib/esm/puppeteer/bidi/core/Realm.js:92:51)
        at WindowRealm.<anonymous> (file:///home/ubuntu/pdfjs/botio-files-pdfjs/private/ac1262cf22c74ac/node_modules/puppeteer-core/lib/esm/puppeteer/util/decorators.js:101:27)
        at #evaluate (file:///home/ubuntu/pdfjs/botio-files-pdfjs/private/ac1262cf22c74ac/node_modules/puppeteer-core/lib/esm/puppeteer/bidi/Realm.js:134:42)
        at BidiFrameRealm.evaluateHandle (file:///home/ubuntu/pdfjs/botio-files-pdfjs/private/ac1262cf22c74ac/node_modules/puppeteer-core/lib/esm/puppeteer/bidi/Realm.js:101:36)
```

### What is the expected behavior?

The integration test should pass consistently.

### What went wrong?

The integration test fails intermittently.

### Link to a viewer

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by timvandermeij**
This integration test fails intermittently because the undo button can only be activated if focus can be put on it, and that in turn can only happen if it's visible. The test tried to make sure that the undo bar is visible, but checking for the absence of the `hidden` attribute is unfortunately not enough to assert visibility according to Puppeteer documentation [1]. Moreover, the undo button wasn't checked at all.

To fix the issue we let Puppeteer do the visibility detection for the undo bar by providing the `visible: true` option to `waitForSelector` [2]. This is consistent with the other tests that already do this, and also with the existing code that detects if the undo bar is hidden (which uses the `hidden: true` option of `waitForSelector`). Moreover, we wait for the undo button to be present before putting focus on it.

For consistency, and to avoid intermittent failures elsewhere, we mirror this solution to the other undo bar/button tests of the various editors.

[1] https://pptr.dev/api/puppeteer.elementhandle.isvisible
[2] https://pptr.dev/api/puppeteer.waitforselectoroptions

Fixes #19872.

### CODE REVIEW

**Review by Snuffleupagus — APPROVED** [review]
r=me, since this would be the correct thing to do even if there were no intermittent failures; thank you.

File: test/integration/highlight_editor_spec.mjs [hunk 1]
```diff
@@ -2254,7 +2260,7 @@ describe("Highlight Editor", () => {
           await page.waitForSelector(`${editorSelector} button.delete`);
           await page.click(`${editorSelector} button.delete`);
           await waitForSerialized(page, 0);
-          await page.waitForSelector("#editorUndoBar:not([hidden])");
+          await page.waitForSelector("#editorUndoBar", { visible: true });
 
           await page.waitForSelector("#editorUndoBarCloseButton");
```
Comment (Snuffleupagus) [inline test/integration/highlight_editor_spec.mjs:2265]: Here, and probably elsewhere below, do we not also (at least for consistency) need to wait for this button to be *visible* before clicking on it?

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you.

File: test/integration/highlight_editor_spec.mjs (hunk 1 above)
Comment (timvandermeij) [reply test/integration/highlight_editor_spec.mjs]: Good find! Yes, that'd be a good idea indeed. I have updated the patch to do that now (this was the only usage of that button).
