### PR TITLE
Ensure that `Lexer_getName` does not fail if a `Name` contains in invalid usage of the NUMBER SIGN (#) (issue 6692)

### LINKED ISSUE #6692: pdf.js loads forever on a certain page of this PDF
pdf.js loads forever while trying to load page 11 of this PDF: http://www.inf.ufg.br/~hugoribeiro/OSPs/osp-im.pdf

I also noted that my Kindle Paperwhite has problems rendering the same page (especifically, the monospaced text part), while Evince loads it just fine.

### PR DESCRIPTION
**Pull request by Snuffleupagus**
_This is a regression from PR #3424._

The PDF file in the referenced issue is using `Type3` fonts. In one of those, the `/CharProcs` dictionary contains an entry with the name `/#`. With the changes made in `Lexer_getName` in PR #3424, we're now incrementing the stream position more than we should for the (admittedly rare) case where a "#" character is not followed by a hexDigit.

~~What seems somewhat problematic to me, is that there was no messages printed in the console to indicate what went wrong. Hence I've also added a bit of (defensive) code to the `Type3` font loading, which should make similar issues easier to spot/debug.~~ Removed, since PR #6697 was merged.

It's unfortunate that this has been broken for close to two and a half years before the bug surfaced, but it should at least indicate that this is not a widespread issue.

Fixes #6692.

### CODE REVIEW

File: src/core/parser.js [hunk 1]
```diff
@@ -846,7 +846,11 @@ var Lexer = (function LexerClosure() {
             }
             strBuf.push(String.fromCharCode((x << 4) | x2));
           } else {
-            strBuf.push('#', String.fromCharCode(ch));
+            strBuf.push('#');
+            if (!Lexer.isSpace(ch)) {
+              strBuf.push(String.fromCharCode(ch));
+            }
+            this.stream.skip(-1); // Reset the stream position.
```
Comment (yurydelendik) [inline src/core/parser.js]: I don't think we shall reset position here. Can you move `if (specialChars[ch]) { strBuf.push('#'); break; }` just after we read the character (line 841). 
By reading the [spec](http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/PDF32000_2008.pdf#page=25), I can assume like that is not okay to write '#' without hex code (see "A NUMBER SIGN (23h) (#) in a name shall be written by using its 2-digit hexadecimal code (23), preceded by the NUMBER SIGN."-rule). Can we warn there are well? If we relaxing parsing here, can we also relax it for non-hex digit, e.g. just add '#' with bad character and warn?

Comment (Snuffleupagus) [inline src/core/parser.js]: That sounds better, thank you pointing this out!
I've pushed a new version of the patch, is this what you had in mind?

File: src/core/parser.js [hunk 2]
```diff
@@ -832,17 +832,29 @@ var Lexer = (function LexerClosure() {
...
           if (x !== -1) {
-            var x2 = toHexDigit(this.nextChar());
+            previousCh = ch;
+            ch = this.nextChar();
+            var x2 = toHexDigit(ch);
             if (x2 === -1) {
-              error('Illegal digit in hex char in name: ' + x2);
+              warn('Lexer_getNumber: Illegal digit (' +
+                   String.fromCharCode(ch) + ') in hexadecimal number.');
+              strBuf.push('#', String.fromCharCode(previousCh),
```
Comment (yurydelendik) [inline src/core/parser.js]: Could you add case when specialChars[ch] is not legal name char? (You can keep the same warn message)

File: src/core/parser.js [hunk 3]
```diff
@@ -832,17 +832,29 @@ var Lexer = (function LexerClosure() {
...
     getName: function Lexer_getName() {
-      var ch;
+      var ch, previousCh;
       var strBuf = this.strBuf;
       strBuf.length = 0;
       while ((ch = this.nextChar()) >= 0 && !specialChars[ch]) {
         if (ch === 0x23) { // '#'
           ch = this.nextChar();
+          if (specialChars[ch]) {
+            warn('Lexer_getNumber: ' +
```
Comment (yurydelendik) [inline src/core/parser.js]: nit: here and below "Lexer_getName: .... "

Comment (Snuffleupagus) [inline src/core/parser.js]: This is an embarrassing mistake on my part, thanks for noticing!

File: src/core/parser.js (hunk 2 above)
Comment (Snuffleupagus) [inline src/core/parser.js]: I've tried to address this, and I've also added a unit test. Thanks for the review comments!

**Comment by yurydelendik** [comment]
Looks good, thank you.
