### PR TITLE
Downscale jpeg2000 images, if needed, while decoding them

### LINKED ISSUE #19517: [Bug]: Cannot render some* PDFs with .jp2 embedded images
### Attach (recommended) or Link to PDF file

[pdf-with-jp2.pdf](https://github.com/user-attachments/files/18884587/pdf-with-jp2.pdf)

### Web browser and its version

Chrome, Arc, Firefox, Microsoft Edge

### Operating system and its version

macOS 14.7.4

### PDF.js version

4.10.38

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Upload the attached PDF to a pdf.js-based viewer.
2. See a blank image instead of a red image spawning the whole document.

### What is the expected behavior?

Display the .jp2 image embedded in the PDF document.

### What went wrong?

No image was displayed in the document

### Link to a viewer

_No response_

### Additional context

I'm running into issues rendering PDFs with some embedded .jp2 images. The document is loaded, but the image is not rendered. I see that pdf.js has a WASM compiled openjpeg-based JPX decoder. However, it can not decode the picture embedded in the document and issues the following warning in the browser dev tools console:

```
Warning: Unable to decode image "img_p0_1": "JpxError: Size of tile data exceeds system limits

Failed to decode.

Failed to decode tile 1/1

Failed to decode the codestream in the JP2 file

Failed to decode the image".
```

My limited debugging leads me to believe that we are hitting some of the branches issuing this error ([here is an example](https://github.com/uclouvain/openjpeg/blob/44119c2db51911056e1227e46a0ea883e3d73fbf/src/lib/openjp2/tcd.c#L1004-L1006)) because of the 32-bit memory model WASM compiled build. I may be wrong here, and I need help debugging the exact C code branch that is giving the warning and what we can do about it. I also see that browsers are starting to support [64bit WASM](https://github.com/WebAssembly/memory64), again I'm not sure if compiling a 64-bit WASM openjpeg build is the proper solution as browsers are just starting to support this.

I am attaching a document for testing. The native Chrome PDF viewer ([pdfium](https://github.com/chromium/pdfium)) and macOS Preview can display the document. Interestingly, pdfium also uses openjpeg to decode the image, but I guess the 64-bit native build handles such images.

### PR DESCRIPTION
**Pull request by calixteman**
It fixes #19517.

### CODE REVIEW

**Comment by calixteman** [comment]
The difference in the tests is because this patch changes the way to rescale large images.

File: src/core/jpx.js [hunk 1]
```diff
@@ -119,13 +124,14 @@ class JpxImage {
...
-      module.HEAPU8.set(bytes, ptr);
+      module.writeArrayToMemory(bytes, ptr);
       const ret = module._jp2_decode(
         ptr,
         size,
         numComponents > 0 ? numComponents : 0,
         !!isIndexedColormap,
-        !!smaskInData
+        !!smaskInData,
+        Math.max(0, Math.floor(reducePower ?? 0))
```
Comment (Snuffleupagus) [inline src/core/jpx.js:134]: Can this be simplified, since the default value is zero (above) and it seems (as far as I can tell) that `getReducePowerForJPX` will always return a positive integer?

Comment (Snuffleupagus) [inline src/core/jpx.js:134]: Can this be simplified, since the default value is zero (above) and it seems (as far as I can tell) that `getReducePowerForJPX` will always return a positive integer?

Would the following suffice?
```suggestion
        reducePower
```

File: src/core/image_resizer.js [hunk 2]
```diff
@@ -96,6 +96,30 @@ class ImageResizer {
...
+        // The image is too large, we need to rescale it.
+        return Math.ceil(Math.log2(area / maxJPXArea));
+      }
+      return 0;
+    }
+    const { MAX_DIM, MAX_AREA } = this;
+    const minFactor = Math.max(
+      width / MAX_DIM,
+      height / MAX_DIM,
+      Math.sqrt((width * height) / Math.min(maxJPXArea, MAX_AREA))
```
Comment (Snuffleupagus) [inline src/core/image_resizer.js:118]: Can we use the local variable?
```suggestion
      Math.sqrt(area / Math.min(maxJPXArea, MAX_AREA))
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you.

**Comment by gsamokovarov** [comment]
In my testing, this change does display the documents with big .jp2 images we couldn't display before. Thanks!
