### PR TITLE
[api-minor] Add the pinch-to-zoom feature (bug 1677933)

### LINKED ISSUE #2582: Use more natural zooming on mobile
Right now you have to hit the plus/minus buttons even on mobile in order to zoom the document. This is really strange especially since pinch-to-zoom is active as well. I think the best way to go on mobile is maybe to render at a "natural" size, and let the browser control the zoom, similar to a web page.

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

File: web/app.js [hunk 1]
```diff
@@ -2674,16 +2694,51 @@ function webViewerWheel(evt) {
...
+}
+
+function webViewerTouchEnd(evt) {
+  if (!PDFViewerApplication._touchInfo) {
+    return;
   }
+
+  evt.preventDefault();
+  PDFViewerApplication._touchInfo = null;
+  PDFViewerApplication.rescale(1, {});
```
Comment (Snuffleupagus) [inline web/app.js:2741]: Why not simply `PDFViewerApplication.pdfViewer.refresh()` instead?

File: web/app.js [hunk 2]
```diff
@@ -2674,16 +2694,51 @@ function webViewerWheel(evt) {
...
+  }
+
+  evt.preventDefault();
+  const [touch0, touch1] = evt.touches;
+  const distance =
+    Math.hypot(touch0.pageX - touch1.pageX, touch0.pageY - touch1.pageY) || 1;
+  const scaleFactor = distance / PDFViewerApplication._touchInfo.distance;
+  if (Math.abs(scaleFactor - 1) <= 1e-2) {
+    return;
+  }
```
Comment (Snuffleupagus) [inline web/app.js:2727]: This seems like the sort of thing that would benefit from a comment.

File: web/app.js [hunk 3]
```diff
@@ -2674,16 +2694,51 @@ function webViewerWheel(evt) {
...
+function webViewerTouchMove(evt) {
+  if (!PDFViewerApplication._touchInfo || evt.touches.length !== 2) {
+    return;
+  }
+
+  evt.preventDefault();
+  const [touch0, touch1] = evt.touches;
+  const distance =
+    Math.hypot(touch0.pageX - touch1.pageX, touch0.pageY - touch1.pageY) || 1;
+  const scaleFactor = distance / PDFViewerApplication._touchInfo.distance;
```
Comment (Snuffleupagus) [inline web/app.js:2724]: *A more general question:* Do we actually need to support "arbitrary" pinch-zooming, or could we perhaps convert the distance changes into zoom-`ticks` similar to how the mouse-wheel zooming is implemented?

Unless I'm missing something obvious, it seems to me that that could actually simplify the overall implementation.

File: web/pdf_viewer.js [hunk 4]
```diff
@@ -1088,6 +1088,10 @@ class PDFViewer {
     this._currentScaleValue = newValue.toString();
 
     if (this.#isSameScale(newScale)) {
+      if (drawingDelay === -1 && this.#scaleTimeoutId) {
+        this.refresh();
+        return;
+      }
```
Comment (Snuffleupagus) [inline web/pdf_viewer.js:1094]: I really don't understand what this block is actually for, and what it's trying to fix!?

It also seems to me that this could easily "break" the event-dispatching just below, and given all the different ways in which zooming is invoked I really can't tell if this is *generally* correct/safe unfortunately.

File: web/pdf_viewer.js [hunk 5]
```diff
@@ -2031,6 +2035,12 @@ class PDFViewer {
     this._setScale(newScale, options);
   }
 
+  rescale(scaleFactor, options) {
+    const newScaleValue =
+      Math.round(this._currentScale * scaleFactor * 100) / 100;
+    this._setScale(newScaleValue, options);
+  }
+
```
Comment (Snuffleupagus) [inline web/pdf_viewer.js:2043]: Sorry to say, but I'm not particularly "liking" this new method. Note how changes in this file basically introduces new official viewer-APIs, and I'm not sure if this method is something we want to expose. (Also, there's a bunch of "required" validation currently missing here.)

Let's first address my question above, regarding using zoom-`ticks` instead, before I try to make any suggestions here.

File: web/app.js (hunk 3 above)
Comment (calixteman) [reply web/app.js:2724]: I tested zooming on an android device with the Acrobat app and the Google Drive app and both are supporting "smooth" zooming.
In Firefox, there's a smooth zoom when `apz.allow_zooming` is true and a stepped one else (and I forgot to check that in this patch, I'll update).

File: web/app.js [hunk 6]
```diff
@@ -2674,18 +2702,66 @@ function webViewerWheel(evt) {
...
+      PDFViewerApplication._touchInfo = null;
+      return;
+    }
+
+    const [touch0, touch1] = evt.touches;
+    PDFViewerApplication._touchInfo = {
+      distance:
+        Math.hypot(touch0.pageX - touch1.pageX, touch0.pageY - touch1.pageY) ||
+        1,
+    };
```
Comment (Snuffleupagus) [inline web/app.js:2717]: If this is only going to store *a single* property, at least for now, can't we skip the object and just do the following instead?
```suggestion
    PDFViewerApplication._touchDistance =
        Math.hypot(touch0.pageX - touch1.pageX, touch0.pageY - touch1.pageY) ||
        1;
```

Although, this would probably require that you *explicitly* check `PDFViewerApplication._touchDistance !== null` in the functions below.

File: web/app.js [hunk 7]
```diff
@@ -2674,18 +2702,66 @@ function webViewerWheel(evt) {
...
+  if (PDFViewerApplication.supportsPinchToZoom) {
+    PDFViewerApplication.rescale(scaleFactor, {
+      drawingDelay: AppOptions.get("defaultZoomDelay"),
+    });
+    return;
+  }
+
+  const PIXELS_PER_LINE_SCALE = 30;
+  const delta = (distance - previousDistance) / PIXELS_PER_LINE_SCALE;
+  const ticks = PDFViewerApplication.accumulateWheelTicks(delta);
```
Comment (Snuffleupagus) [inline web/app.js:2747]: Is re-using this generally correct, since a device with both a mouse and a touch-screen (e.g. a laptop) would then have one type of zooming effecting the other as far as I can tell?

Rather you should probably introduce a new method, e.g. named `accumulateTouchTicks` and being essentially a copy of the existing one, that you use instead here?

File: web/app.js [hunk 8]
```diff
@@ -676,6 +681,13 @@ const PDFViewerApplication = {
     this.pdfViewer.currentScaleValue = DEFAULT_SCALE_VALUE;
   },
 
+  rescale(scaleFactor, options) {
+    if (this.pdfViewer.isInPresentationMode) {
+      return;
+    }
+    this.pdfViewer.rescale(scaleFactor, options);
+  },
+
```
Comment (Snuffleupagus) [inline web/app.js:690]: Do we *really* need this, i.e. can't we change the existing `zoomIn`/`zoomOut` methods to also support this use-case as well (and thus call those methods with pinch-zooming as well)?

```javascript
  zoomIn(steps, scaleFactor = null) {
    if (this.pdfViewer.isInPresentationMode) {
      return;
    }
    this.pdfViewer.increaseScale(steps, {
      drawingDelay: AppOptions.get("defaultZoomDelay"),
      scaleFactor,
    });
  },

  zoomOut(steps, scaleFactor = null) {
    if (this.pdfViewer.isInPresentationMode) {
      return;
    }
    this.pdfViewer.decreaseScale(steps, {
      drawingDelay: AppOptions.get("defaultZoomDelay"),
      scaleFactor,
    });
  },
```

And in the `pdf_viewer.js` file we'd make changes like the following:

```javascript
  increaseScale(steps = 1, options = null) {
    if (!this.pdfDocument) {
      return;
    }
    let newScale = this._currentScale;

    if (options?.scaleFactor > 1) {
      newScale = Math.min(
        MAX_SCALE,
        Math.ceil(newScale * options.scaleFactor * 100) / 100
      );
    } else {    
      do {
        newScale = (newScale * DEFAULT_SCALE_DELTA).toFixed(2);
        newScale = Math.ceil(newScale * 10) / 10;
        newScale = Math.min(MAX_SCALE, newScale);
      } while (--steps > 0 && newScale < MAX_SCALE);
    }
    options ||= Object.create(null);
    options.noScroll = false;
    this._setScale(newScale, options);
  }

  decreaseScale(steps = 1, options = null) {
    if (!this.pdfDocument) {
      return;
    }
    let newScale = this._currentScale;

    if (options?.scaleFactor > 0 && options?.scaleFactor < 1) {
      newScale = Math.max(
        MIN_SCALE,
        Math.floor(newScale * options.scaleFactor * 100) / 100
      );
    } else {
      do {
        newScale = (newScale / DEFAULT_SCALE_DELTA).toFixed(2);
        newScale = Math.floor(newScale * 10) / 10;
        newScale = Math.max(MIN_SCALE, newScale);
      } while (--steps > 0 && newScale > MIN_SCALE);
    }
    options ||= Object.create(null);
    options.noScroll = false;
    this._setScale(newScale, options);
  }
```

File: web/pdf_viewer.js [hunk 9]
```diff
@@ -1992,43 +1992,63 @@ class PDFViewer {
 
   /**
    * Increase the current zoom level one, or more, times.
-   * @param {number} [steps] - Defaults to zooming once.
    * @param {Object|null} [options]
    */
-  increaseScale(steps = 1, options = null) {
+  increaseScale(options = null) {
```
Comment (Snuffleupagus) [inline web/pdf_viewer.js:1997]: Sorry, but this is a *breaking change* in the viewer-API which is why I specifically made the suggestion that I did in https://github.com/mozilla/pdf.js/pull/15886#discussion_r1060549906.

Hence if you want to make these change here, then you'll need to add fallback code that handles the old signature as well and also tag the PR with `[api-minor]`. E.g. something like this:
```suggestion
  increaseScale(options = null) {
    if (
      (typeof PDFJSDev === "undefined" || PDFJSDev.test("GENERIC")) &&
      typeof options === "number"
    ) {
      console.error("The `increaseScale` method-signature was updated, please use an object instead.");
      options = { steps: options };
    }
```

File: web/pdf_viewer.js [hunk 10]
```diff
@@ -1992,43 +1992,63 @@ class PDFViewer {
...
-    do {
-      newScale = (newScale * DEFAULT_SCALE_DELTA).toFixed(2);
-      newScale = Math.ceil(newScale * 10) / 10;
-      newScale = Math.min(MAX_SCALE, newScale);
-    } while (--steps > 0 && newScale < MAX_SCALE);
 
     options ||= Object.create(null);
-    options.noScroll = false;
+
+    let newScale;
```
Comment (Snuffleupagus) [inline web/pdf_viewer.js:2004]: Why not just do the following here, to simplify the code below?
```suggestion
    let newScale = this._currentScale;
```

File: web/pdf_viewer.js [hunk 11]
```diff
@@ -1992,43 +1992,63 @@ class PDFViewer {
...
+    if (options.scaleFactor) {
```
Comment (Snuffleupagus) [inline web/pdf_viewer.js:2005]: Not enough validation here, this needs to be
```suggestion
    if (options.scaleFactor > 1) {
```

File: web/pdf_viewer.js [hunk 12]
```diff
@@ -1992,43 +1992,63 @@ class PDFViewer {
...
+    } else {
+      let steps = options.steps ?? 1;
+      newScale = this._currentScale;
+      do {
+        newScale = (newScale * DEFAULT_SCALE_DELTA).toFixed(2);
+        newScale = Math.ceil(newScale * 10) / 10;
+        newScale = Math.min(MAX_SCALE, newScale);
+      } while (--steps > 0 && newScale < MAX_SCALE);
+
+      options.noScroll = false;
```
Comment (Snuffleupagus) [inline web/pdf_viewer.js:2019]: Why don't we do this *unconditionally* in this method, since that ought to limit the amount of re-positioning that we need to do in the `web/app.js` code when pinch-zooming?

File: web/pdf_viewer.js [hunk 13]
```diff
@@ -1992,43 +1992,63 @@ class PDFViewer {
...
     this._setScale(newScale, options);
   }
 
   /**
    * Decrease the current zoom level one, or more, times.
-   * @param {number} [steps] - Defaults to zooming once.
    * @param {Object|null} [options]
    */
-  decreaseScale(steps = 1, options = null) {
+  decreaseScale(options = null) {
```
Comment (Snuffleupagus) [inline web/pdf_viewer.js:2028]:
```suggestion
  decreaseScale(options = null) {
    if (
      (typeof PDFJSDev === "undefined" || PDFJSDev.test("GENERIC")) &&
      typeof options === "number"
    ) {
      console.error("The `decreaseScale` method-signature was updated, please use an object instead.");
      options = { steps: options };
    }
```

File: web/pdf_viewer.js [hunk 14]
```diff
@@ -1992,43 +1992,63 @@ class PDFViewer {
...
-    do {
-      newScale = (newScale / DEFAULT_SCALE_DELTA).toFixed(2);
-      newScale = Math.floor(newScale * 10) / 10;
-      newScale = Math.max(MIN_SCALE, newScale);
-    } while (--steps > 0 && newScale > MIN_SCALE);
 
     options ||= Object.create(null);
-    options.noScroll = false;
+
+    let newScale;
```
Comment (Snuffleupagus) [inline web/pdf_viewer.js:2035]: Why not just do the following here, to simplify the code below?
```suggestion
    let newScale = this._currentScale;
```

File: web/pdf_viewer.js [hunk 15]
```diff
@@ -1992,43 +1992,63 @@ class PDFViewer {
...
+    } else {
+      let steps = options.steps ?? 1;
+      newScale = this._currentScale;
+      do {
+        newScale = (newScale / DEFAULT_SCALE_DELTA).toFixed(2);
+        newScale = Math.floor(newScale * 10) / 10;
+        newScale = Math.max(MIN_SCALE, newScale);
+      } while (--steps > 0 && newScale > MIN_SCALE);
+
+      options.noScroll = false;
```
Comment (Snuffleupagus) [inline web/pdf_viewer.js:2050]: Why don't we do this *unconditionally* in this method, since that ought to limit the amount of re-positioning that we need to do in the `web/app.js` code when pinch-zooming?

File: web/pdf_viewer.js [hunk 16]
```diff
@@ -1992,43 +1992,63 @@ class PDFViewer {
...
-      newScale = (newScale / DEFAULT_SCALE_DELTA).toFixed(2);
-      newScale = Math.floor(newScale * 10) / 10;
-      newScale = Math.max(MIN_SCALE, newScale);
-    } while (--steps > 0 && newScale > MIN_SCALE);
 
     options ||= Object.create(null);
-    options.noScroll = false;
+
+    let newScale;
+    if (options.scaleFactor) {
```
Comment (Snuffleupagus) [inline web/pdf_viewer.js:2036]: Not enough validation here, this needs to be
```suggestion
    if (options.scaleFactor > 0 && options.scaleFactor < 1) {
```

**Review by Snuffleupagus — COMMENTED** [review]
Have you tested that this doesn't interfere with the touch-handling that exists for PresentationMode?

File: web/app.js [hunk 17]
```diff
@@ -2674,18 +2729,96 @@ function webViewerWheel(evt) {
...
+    // The two touches go in almost the same direction.
+    return;
+  }
+
+  evt.preventDefault();
+
+  const previousScale = pdfViewer.currentScale;
+
+  if (supportsPinchToZoom) {
+    PDFViewerApplication.rescale(scaleFactor);
```
Comment (Snuffleupagus) [inline web/app.js:2784]: Also, can't we change this as follows and just remove the `rescale`-method?
```suggestion
    if (scaleFactor < 1) {
      PDFViewerApplication.zoomOut(/* steps = */ null, scaleFactor);
    } else if (scaleFactor > 1) {
      PDFViewerApplication.zoomIn(/* steps = */ null, scaleFactor);
    }
```
Assuming that we also change the existing methods like so:
```javascript
zoomIn(steps, scaleFactor) {
    if (this.pdfViewer.isInPresentationMode) {
      return;
    }
    this.pdfViewer.increaseScale({
      drawingDelay: AppOptions.get("defaultZoomDelay"),
      steps,
      scaleFactor,
    });
  },

  zoomOut(steps, scaleFactor) {
    if (this.pdfViewer.isInPresentationMode) {
      return;
    }
    this.pdfViewer.decreaseScale({
      drawingDelay: AppOptions.get("defaultZoomDelay"),
      steps,
      scaleFactor,
    });
  },
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, since this appears to be working as far as I can tell :-)

(I don't have a computer with a touch-screen, so I used my phone for some quick testing.)

**Comment by calixteman** [comment]
> r=me, since this appears to be working as far as I can tell :-)
> 
> (I don't have a computer with a touch-screen, so I used my phone for some quick testing.)

I wrote the patch on a computer with a touch-screen: it works well for me.
And I tested it on my phone in using the above viewer and it worked well either.
