### PR TITLE
Expose `TextLayerRenderTask` in the TypeScript definitions (issue 15016, PR 14013 follow-up)

### LINKED ISSUE #15016: Export TextLayerRenderTask type
Attach (recommended) or Link to PDF file here: not relevant

Configuration:
- Web browser and its version: `not relevant`
- Operating system and its version: `not relevant`
- PDF.js version: `2.14.305`
- Is a browser extension: `no`

Steps to reproduce the problem:
1. In a webpack project, try to import `TextLayerRenderTask` from pdfjs-dist

What is the expected behavior? (add screenshot)
`TextLayerRenderTask` be exported

What went wrong? (add screenshot)
image

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): `n/a`

We need `TextLayerRenderTask` to be exported for our TypeScript project. Currently, we're just polyfilling the type but it'd be great if this could be officially exported.
image

### PR DESCRIPTION
**Pull request by Snuffleupagus**
While `TextLayerRenderTask` apparently makes sense in TypeScript environments, given that it's being returned by the `renderTextLayer`-function in the API, we really don't want to extend the *public* API by simply exporting the class directly in `src/pdf.js` since it should never be called/initialized manually.
Hence we follow the same pattern as in PR #14013, and add some very basic unit-tests to ensure that `renderTextLayer` always returns a `TextLayerRenderTask`-instance as expected.

### CODE REVIEW

File: src/pdf.js [hunk 1]
```diff
@@ -19,6 +19,8 @@
 /** @typedef {import("./display/api").PDFPageProxy} PDFPageProxy */
 /** @typedef {import("./display/api").RenderTask} RenderTask */
 /** @typedef {import("./display/display_utils").PageViewport} PageViewport */
+// eslint-disable-next-line max-len
+/** @typedef {import("./display/text_layer.js").TextLayerRenderTask} TextLayerRenderTask */
```
Comment (timvandermeij) [inline src/pdf.js:23]: Looking at the lines above this should not have the `.js` extension in the import statement.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you for improving this!
