### PR TITLE
Avoid to have a white line around the canvas

### LINKED ISSUE #18694: [Bug]: White border in viewer for PDFs with background color
### Attach (recommended) or Link to PDF file

[test.pdf](https://github.com/user-attachments/files/16886737/test.pdf)

### Web browser and its version

130.0 (64-Bit)

### Operating system and its version

Windows 10

### PDF.js version

Stable (v4.6.82)

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1.) Create a PDF with a background color other than plain white
2.) Open the PDF in the viewer
3.) Increase/Decrease the zoom level until a white border appears on the right/bottom edge of the page.

### What is the expected behavior?

There is no white line between the PDFs background and the background of the viewer.

grafik

### What went wrong?

grafik

### Link to a viewer

_No response_

### Additional context

It looks like there is a rounding error for the height and width of the `#viewer .page` element. My workaround was to set `background-color: var(--body-bg-color);` in the `.pdfViewer .page` CSS selector.

Maybe related: #18680

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

File: web/pdf_page_view.js [hunk 1]
```diff
@@ -1036,19 +1036,22 @@ class PDFPageView {
...
+    const newWidth = (canvas.width = floorToDivide(
+      width * outputScale.sx,
+      sfx[0]
+    ));
+    const newHeight = (canvas.height = floorToDivide(
+      height * outputScale.sy,
+      sfy[0]
+    ));
+    const scaleX = newWidth / width;
+    const scaleY = newHeight / height;
```
Comment (Snuffleupagus) [inline web/pdf_page_view.js:1048]: Unfortunately this seems wrong, since the condition below will no longer test the *correct* thing now.
```suggestion
    outputScale.sx = newWidth / width;
    outputScale.sy = newHeight / height;
```

File: web/pdf_page_view.js [hunk 2]
```diff
@@ -1036,19 +1036,22 @@ class PDFPageView {
...
 
     // Add the viewport so it's known what it was originally drawn with.
     this.#viewportMap.set(canvas, viewport);
 
     // Rendering area
-    const transform = outputScale.scaled
-      ? [outputScale.sx, 0, 0, outputScale.sy, 0, 0]
-      : null;
+    const transform = outputScale.scaled ? [scaleX, 0, 0, scaleY, 0, 0] : null;
```
Comment (Snuffleupagus) [inline web/pdf_page_view.js:1054]: Given the comment above, this should be reverted.
```suggestion
    const transform = outputScale.scaled
      ? [outputScale.sx, 0, 0, outputScale.sy, 0, 0]
      : null;
```

**Comment by nicolo-ribaudo** [comment]
This looks good to me, does it also still fix the "small movement when the canvas is redrawing" problem you mentioned?

**Comment by calixteman** [comment]
> This looks good to me, does it also still fix the "small movement when the canvas is redrawing" problem you mentioned?

Yes it does for me, doesn't it for you ?

**Comment by Snuffleupagus** [comment]
Comparing https://mozilla.github.io/pdf.js/web/viewer.html and https://github.com/mozilla/pdf.js/pull/18698#issuecomment-2331965085 side-by-side, it does appear that this patch makes the canvas slightly blurry at some zoom levels (e.g. `auto`).

**Comment by Snuffleupagus** [comment]
*I just realized that I wasn't clear before:* The blurriness I'm talking about with this patch is with the default `tracemonkey.pdf` file and `window.devicePixelRatio === 2`, at e.g. the "auto" zoom level.
Hence this patch really doesn't seem acceptable as-is, most unfortunately.

**Comment by calixteman** [comment]
I think it's because the ratio between the canvas width/height and the canvas css width/height is no more exactly equal to 1.5 (my devicePixelRatio).
So I think, we should change the 3rd parameter of the `round` function in the css to have something which uses the denominator found by Farey approximation.
That said maybe having the right ratio helped to just use the right algorithm to downscale the canvas, so maybe (too much maybe in this sentence) using `pixelated` could be the right way to do it.

**Comment by calixteman** [comment]
@Snuffleupagus, what's the real zoom level, as a number, you use ?

**Comment by Snuffleupagus** [comment]
> what's the real zoom level, as a number, you use ?

125 percent; as defined in https://github.com/mozilla/pdf.js/blob/77c7ec6927c0263a0ed2be2b0aae46b655855239/web/ui_utils.js#L22

**Comment by Snuffleupagus** [comment]
Testing with the `tracemonkey.pdf` file, this patch unfortunately still looks worse (for me) compared to `master`.

**Comment by calixteman** [comment]
What do you mean exactly by worse ?
Could you share a screenshot showing both rendering ?

**Comment by Snuffleupagus** [comment]
Here's two screen-shots, from master respectively the patch, where the letters are noticeably more blurry with this patch. (Comparing the images at high magnification might be helpful to see the differences more clearly.)

master

patch

**Comment by nicolo-ribaudo** [comment]
> > The new preview still suffers from blurriness issues unfortunately; there doesn't seem to be any improvement there.
> > Are the [src/display/display_utils.js](https://github.com/mozilla/pdf.js/pull/18698/files#diff-148dd18f1e2ce2f7b3ed63d4a36922f87ebb1103ff2eaf2e9854adee72d280e5) changes perhaps enough to fix the regression as filed, because if so I believe that we should do that _first_ and worry about the other parts of this PR later!?
> 
> Unfortunately it isn't enough. At 70%, the page dims are 555x785 when the canvas css dims are 554x784.

Is this with the test PDF? I'm seeing both as 555x785 :thinking:

**Comment by calixteman** [comment]
@Snuffleupagus, it's because Firefox is using float32 numbers when evaluating a `calc` expression in the css.
But Chrome and Safari seem to use some float64.
/botio-linux preview

File: test/unit/ui_utils_spec.js [hunk 3]
```diff
@@ -627,4 +628,17 @@ describe("ui_utils", function () {
       });
     });
   });
+
+  describe("calcRound", function () {
+    it("", function () {
```
Comment (Snuffleupagus) [inline test/unit/ui_utils_spec.js:633]: This test needs a name :-)
```suggestion
    it("should handle different browsers/environments correctly", function () {
```

File: web/pdf_page_view.js [hunk 4]
```diff
@@ -1036,11 +1041,27 @@ class PDFPageView {
...
+      calcRound(height * outputScale.sy),
+      sfy[0]
+    ));
+    const pageWidth = floorToDivide(calcRound(width), sfx[1]);
+    const pageHeight = floorToDivide(calcRound(height), sfy[1]);
+    outputScale.sx = canvasWidth / pageWidth;
+    outputScale.sy = canvasHeight / pageHeight;
+
+    if (this.#scaleRoundX !== sfx[1]) {
+      this.div.style.setProperty("--scale-round-x", `${sfx[1]}px`);
```
Comment (Snuffleupagus) [inline web/pdf_page_view.js:1058]: This should be available as a local variable.
```suggestion
      div.style.setProperty("--scale-round-x", `${sfx[1]}px`);
```

File: web/pdf_page_view.js [hunk 5]
```diff
@@ -1036,11 +1041,27 @@ class PDFPageView {
...
+      this.#scaleRoundX = sfx[1];
+    }
+    if (this.#scaleRoundY !== sfy[1]) {
+      this.div.style.setProperty("--scale-round-y", `${sfy[1]}px`);
```
Comment (Snuffleupagus) [inline web/pdf_page_view.js:1062]: As above.
```suggestion
      div.style.setProperty("--scale-round-y", `${sfy[1]}px`);
```

File: web/ui_utils.js [hunk 6]
```diff
@@ -862,6 +862,18 @@ function toggleExpandedBtn(button, toggle, view = null) {
   view?.classList.toggle("hidden", !toggle);
 }
 
+// In Firefox, the css calc function uses f32 precision but the Chrome or Safari
+// are using f64 one. So in order to have the same rendering in all browsers, we
+// need to use the right precision in order to have correct dimensions.
+const calcRound = (function () {
+  if (typeof document === "undefined") {
```
Comment (Snuffleupagus) [inline web/ui_utils.js:869]: Given that this should only be needed in order for the unit-tests to run successfully in Node.js, let's copy the approach used in `animationStarted` above.
```suggestion
  if (
    typeof PDFJSDev !== "undefined" &&
    PDFJSDev.test("LIB") &&
    typeof document === "undefined"
  ) {
```

**Review by Snuffleupagus — COMMENTED** [review]
This seems to work much better now.

**Comment by calixteman** [comment]
Having a more or less thin white line on some page sides is a longstanding bug... Thanks to mozregression, I managed to get that the regressor is:
https://github.com/mozilla/pdf.js/pull/6552
That said, nowadays the thin line is a bit too much thick.

**Comment by calixteman** [comment]
I added an integration test to avoid any future regression.

File: test/integration/viewer_spec.mjs [hunk 7]
```diff
@@ -365,4 +368,75 @@ describe("PDF viewer", () => {
...
+            const toolbar = document.querySelector(".toolbar");
+            toolbar.style.display = "none";
+          });
+          await page.waitForSelector(".toolbar", { visible: false });
+          await page.evaluate(() => {
+            const p = document.querySelector(`.page[data-page-number="1"]`);
+            p.style.border = "none";
+          });
+
+          for (let i = 0; true; i++) {
```
Comment (Snuffleupagus) [inline test/integration/viewer_spec.mjs:409]: Can't this be written as follows instead?
```suggestion
          for (let i = 0; ; i++) {
```

File: test/integration/viewer_spec.mjs [hunk 8]
```diff
@@ -365,4 +368,75 @@ describe("PDF viewer", () => {
...
+            // Search for the first red pixel.
+            const j = buffer.indexOf(0xff0000ff);
+            buffer = buffer.slice(j);
+
+            expect(buffer.every(x => x === 0xff0000ff))
+              .withContext(`In ${browserName}, in the ${i}th zoom in`)
+              .toBe(true);
+
+            const currentScale = await page.evaluate(
+              () => window.PDFViewerApplication.pdfViewer._currentScale
```
Comment (Snuffleupagus) [inline test/integration/viewer_spec.mjs:432]: That's a "private" field, can we please avoid accessing it directly?
```suggestion
              () => window.PDFViewerApplication.pdfViewer.currentScale
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, with a few more comments and passing tests; thank you!

**Comment by calixteman** [comment]
FYI, the added integration test is correctly failing on master.

**Comment by calixteman** [comment]
The small movements we've are very likely due to the change in the text (or annotation) layer dimensions where we now round differently (in passing --scale-round-x/y as third parameter).
