### PR TITLE
Fix flickering on text selection

### LINKED ISSUE #17912: Selection flickers on mobile if there is some vertical space between the <span>s in the text layer
**Attach (recommended) or Link to PDF file here:** https://home.barclays/content/dam/home-barclays/documents/investor-relations/ResultAnnouncements/FullYear2023Results/20240306-Barclays%20FY23%20Analyst%20Breakfast%20Sell%20Side%20Meeting.pdf

This also happens in the "Trace-based Just-in-Type ..." PDF, but it's less visible because its lines have a slight overlap (it's only visible in some specific areas of the document where there is more space).

**Configuration:**
- Web browser and its version: Firefox 124.4.0 (it also happens in Chrome for Android, and Safari on iOS)
- Operating system and its version: Android 14
- PDF.js version: Whatever is included in that firefox version
- Is a browser extension: no

**Steps to reproduce the problem:**
1. Select some text
2. Expand the selection across lines

**What is the expected behavior? (add screenshot)**

The selection should roughly follow my finger

**What went wrong? (add screenshot)**

Whenever my finger is between two lines, the selection jumps to the beginning of the page

https://github.com/mozilla/pdf.js/assets/7000710/b6b8199d-9e6f-4e42-b086-7b45ad833f16

**Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):**

I was using the one built-in in Firefox

---

I have a fix for WebKit iOS that doesn't seem to work in Firefox, but I'm experimenting with variations of it.

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
When seleciting on a touch screen device, whenever the finger moves to a blank area (so over `div.textLayer` directly rather than on a `<span>`), the selection jumps to include all the text between the beginning of the `.textLayer` and the selection side that is not being moved.

The existing selection flickering fix when using the mouse cannot be trivially re-used on mobile, because when modifying a selection on a touchscreen device Firefox will not emit any pointer event (and Chrome will emit them inconsistently). Instead, we have to listen to the 'selectionchange' event.

The fix is different in Firefox and Chrome:
- on Firefox, we have to make sure that, when modifying the selection, hovering on blank areas will hover on the `.endOfContent` element rather than on the `.textLayer` element. This is done by adjusting the z-indexes so that `.endOfContent` is above `.textLayer`.
- on Chrome, hovering on blank areas needs to trigger hovering on an element that is either immediately after (or immediately before, depending on which side of the selection the user is moving) the currently selected text. This is done by moving the `.endOfContent` element around between the correct `<span>`s in the text layer.

In Safari mobile it is still broken in random and fun ways, the fix for Safari would be completely different, and out-of-scope for this PR.

<details>
<summary>Before/after videos (mobile)</summary>

<table>
<tr><th></th><th>Before</th><th>After</th></tr>
<tr>
<th>Firefox</th>
<td>

https://github.com/mozilla/pdf.js/assets/7000710/3d43e024-2ffa-4301-9d47-f202b0589cc7

</td>
<td>

https://github.com/mozilla/pdf.js/assets/7000710/2099a4c3-b428-4f88-b103-9e95069dee92

</td>
</tr>
<tr>
<th>Chrome</th>
<td>

https://github.com/mozilla/pdf.js/assets/7000710/0b6510d3-3912-46fa-8f3a-87998df539c9

</td>
<td>

https://github.com/mozilla/pdf.js/assets/7000710/983a6425-0c2a-49b5-8c70-81e85966e2f0

</td>
</tr>
</table>

</details>
<details>
<summary>Before/after videos (desktop)</summary>

<table>
<tr><th></th><th>Before</th><th>After</th></tr>
<tr>
<th>Chrome</th>
<td>

https://github.com/mozilla/pdf.js/assets/7000710/a0028dd8-04ae-4b3a-b64e-daed1b01911c

</td>
<td>

https://github.com/mozilla/pdf.js/assets/7000710/e03d3a8e-208c-4502-9230-2a1daf31fd0c

</td>
</tr>
<tr>
<th>Firefox (multi-page selection)</th>
<td>

https://github.com/mozilla/pdf.js/assets/7000710/e092233c-60c8-4056-96b2-a67b072ca81a

</td>
<td>

https://github.com/mozilla/pdf.js/assets/7000710/5ddc6930-0ce3-4306-9fc6-d9a2192db434

</td>
</tr>
</table>

</details>

Fixes https://github.com/mozilla/pdf.js/issues/17912

I'm not sure about how to add a test for this, if it's even possible.

### CODE REVIEW

File: web/text_layer_builder.js [hunk 1]
```diff
@@ -209,15 +208,70 @@ class TextLayerBuilder {
...
+        if (!isFirefox) {
+          const modifyStart =
+            prevRange &&
+            (range.compareBoundaryPoints(Range.END_TO_END, prevRange) === 0 ||
+              range.compareBoundaryPoints(Range.START_TO_END, prevRange) === 0);
+          let anchor = modifyStart ? range.startContainer : range.endContainer;
+          if (anchor.nodeType === Node.TEXT_NODE) anchor = anchor.parentNode;
+          // Make sure that we are always only moving .endOfContent to somewhere
+          // directly in .textLayer, and not inside nested spans.
+          anchor = anchor.closest(".textLayer > span");
```
Comment (nicolo-ribaudo) [inline web/text_layer_builder.js:276]: The behavior in Chrome is still not perfect with PDFs that use `.markedContent`: this PR moves the `.endOfContent` before/after `.markedContent`, so all the `<span>s` inside `.markedContent` are considered as a "single block" and the selection will flicker betwen the "correct selection" and selecting the whole `.markedContent` block. I will eventually try to fix it, but for now this is already an improvement compared to the current "flicker over the whole page" behavior.

File: web/text_layer_builder.css [hunk 2]
```diff
@@ -17,7 +17,7 @@
   position: absolute;
   text-align: initial;
   inset: 0;
-  overflow: hidden;
+  overflow: clip;
```
Comment (nicolo-ribaudo) [inline web/text_layer_builder.css:20]: Using `clip` instead of `hidden` is only needed for Chrome and not for Firefox. When selecting text, Chrome was sometimes trying to move it closer to the center of the webview by scrolling the contents of `.textLayer`, misaligning it from the underlying canvas.

The difference between `hidden` and `clip` is that `hidden` still allows scrolling the element's contents through indirect user interactions (for example, when focusing on an element or through `.scrollTo()`), while `clip` completely disables scroll. For this reason, `clip` is also ok in Firefox so I didn't add a `MOZCENTRAL` check.

File: web/text_layer_builder.js [hunk 3]
```diff
@@ -209,15 +208,70 @@ class TextLayerBuilder {
...
+    //    movement that the user does is to move one of the selection bubbles
+    //    to a blank part of the page, the selection will flicker before
+    //    that we can apply the fix.
+    //  - We cannot detect when the user stops interacting with the selection,
+    //    because there is no difference between "the user is still holding
+    //    their finger on the selection 'bubble'" and "the user is lifter their
+    //    finger and then pressed the 'bubble' again". Thus, the .endOfContent
+    //    element will remain active until when the user interacts with the
+    //    page again, triggering a pointerup event.
+    document.addEventListener("selectionchange", () => {
```
Comment (nicolo-ribaudo) [inline web/text_layer_builder.js:237]: Unfortunately you can only listen to `selectionchange` on `document` and not on a specific element. As currently written, this event listener will never be cleaned up and will leak even after that this text layer is removed from the document.

I was thinking of using `MutationObserver` to unregister the event when `div.textLayer` is removed, but maybe you already have some cleanup logic for when removing the `.textLayer`?

**Comment by timvandermeij** [comment]
I'm not sure if it's possible to add an integration test for this kind of change because even though we can probably do the selection with Puppeteer I don't really see what we could assert in the test. In any case, let's first check if all existing tests still pass with this change applied:

/botio test

File: web/text_layer_builder.css [hunk 4]
```diff
@@ -108,12 +108,16 @@
     display: block;
     position: absolute;
     inset: 100% 0 0;
-    z-index: -1;
+    z-index: 0;
```
Comment (calixteman) [inline web/text_layer_builder.css:111]: Why this change ?

File: web/text_layer_builder.js (hunk 3 above)
Comment (Snuffleupagus) [reply web/text_layer_builder.js:237]: We have a `cancel` method, which seems like the appropriate spot to remove this listener.

File: web/text_layer_builder.js [hunk 5]
```diff
@@ -181,26 +181,25 @@ class TextLayerBuilder {
    * clicked. This reduces flickering of the content if the mouse is slowly
    * dragged up or down.
    */
-  #bindMouse() {
+  #bindMouse(end) {
     const { div } = this;
 
+    let isFirefox;
```
Comment (Snuffleupagus) [inline web/text_layer_builder.js:187]: Please define this conditionally instead, to reduce duplication below.
```suggestion
    if (typeof PDFJSDev === "undefined" || !PDFJSDev.test("MOZCENTRAL")) {
      // eslint-disable-next-line no-var
      var isFirefox =
        (typeof PDFJSDev === "undefined" || !PDFJSDev.test("CHROME")) &&
        getComputedStyle(end).getPropertyValue("-moz-user-select") === "none";
      }
```

File: web/text_layer_builder.css (hunk 4 above)
Comment (nicolo-ribaudo) [reply web/text_layer_builder.css:111]: Without this change, `.endOfContent` is below `.textLayer` so, when dragging the selection over an empty space, Firefox's "collision detection" finds `.textLayer` rather than `.endOfContent`, and selects everything from the start of `.textLayer`.

File: web/text_layer_builder.js (hunk 5 above)
Comment (nicolo-ribaudo) [reply web/text_layer_builder.js:187]: This needs to be done lazily, because initially `getComputedStyle(end).getPropertyValue("-moz-user-select")` returns the empty string even on Firefox. If you prefer, I can wrap it in a cached function to avoid repetition:
```js
    if (typeof PDFJSDev === "undefined" || !PDFJSDev.test("MOZCENTRAL")) {
      // eslint-disable-next-line no-var
      var isFirefox = () => {
        const res = (typeof PDFJSDev === "undefined" || !PDFJSDev.test("CHROME")) &&
          getComputedStyle(end).getPropertyValue("-moz-user-select") === "none";
        isFirefox = () => res;
        return res;
      }
    }
```
(I'm caching it because `getComputedStyle` triggers layout recomputation, and `selectionchange` could potentially be fired very frequently)

**Comment by nicolo-ribaudo** [comment]
@timvandermeij Thanks for the tip! The flickering behavior is very consistent/predictable, so if with puppeteer I could simulate "long-tap at (x1,y2) to select, then hold the selection bubble and drag to (x2,y2), and check what is selected" I would be able to add a test.

The problem is the "drag the selection bubble" part, since it's _not_ dragging on the page (the selection bubble is browser UI and doesn't trigger touch events)

**Comment by nicolo-ribaudo** [comment]
I pushed two commits:
- the first one unregisters the `selectionchange` event listeners in `.cancel()`, so that it doesn't leak (fixing https://github.com/mozilla/pdf.js/pull/17923#discussion_r1560860059)
- the second one fixes flickering also in the case of `<span>`s nested inside `.markedContent`, and removes the old anti-flickering code for Chrome when using a mouse (I added a before/after video in the issue description), as I noticed that the mobile fix also improves the selection on desktop. This de-duplicates the `isFirefox ??= ...` check, solving https://github.com/mozilla/pdf.js/pull/17923#discussion_r1565904113.

I still need to investigate testing.

**Comment by timvandermeij** [comment]
> The problem is the "drag the selection bubble" part, since it's not dragging on the page (the selection bubble is browser UI and doesn't trigger touch events)

I have looked that the Puppeteer API documentation, but I can't really find anything related to this. However, if the flickering effects are also consistently visible in Firefox or Chrome on desktop then we might be able to write a test that starts a selection, moves the mouse to certain coordinates and gets the selected text. The Tracemonkey PDF file from your videos can be used for that as well since we already use it for other integration tests. We'd have to try it out to see if it actually works, but it sounds like it might be doable.

(By the way, thank you for providing such detailed issue/PR descriptions, visuals and inline comments! That really helps to understand the change, especially for these kinds of bugs that are usually a bit tricky and difficult to fully test in an automated way, and therefore require additional manual testing.)

File: web/text_layer_builder.js [hunk 6]
```diff
@@ -181,44 +184,116 @@ class TextLayerBuilder {
...
+    let selectingThroughMouse = false;
+    let prevRange = null;
```
Comment (Snuffleupagus) [inline web/text_layer_builder.js:192]: Can we please avoid "dead code" in Firefox, by doing something like the following?
```suggestion
    let selectingThroughMouse = false;
    if (typeof PDFJSDev === "undefined" || !PDFJSDev.test("MOZCENTRAL")) {
      // eslint-disable-next-line no-var
      var isFirefox, prevRange = null;
    }
```

File: web/text_layer_builder.js [hunk 7]
```diff
@@ -181,44 +184,116 @@ class TextLayerBuilder {
...
+
+        if (typeof PDFJSDev === "undefined" || !PDFJSDev.test("MOZCENTRAL")) {
+          // In non-Firefox browsers, when hovering over an empty space (thus,
+          // on .endOfContent), the selection will expand to cover all the text
+          // between the current selection and .endOfContent. By moving
+          // .endOfContent to right after (or before, depending on which side
+          // of the selection the user is moving), we limit the selection jump
+          // to at most cover the enteirety of the <span> where the selection
+          // is being modified.
+          if (!isFirefox) {
```
Comment (Snuffleupagus) [inline web/text_layer_builder.js:265]: Can't these be combined, to reduce indentation below?
```suggestion
        if (
          (typeof PDFJSDev === "undefined" || !PDFJSDev.test("MOZCENTRAL")) &&
          !isFirefox
        ) {
          // In non-Firefox browsers, when hovering over an empty space (thus,
          // on .endOfContent), the selection will expand to cover all the text
          // between the current selection and .endOfContent. By moving
          // .endOfContent to right after (or before, depending on which side
          // of the selection the user is moving), we limit the selection jump
          // to at most cover the enteirety of the <span> where the selection
          // is being modified.
```

File: web/text_layer_builder.css (hunk 4 above)
Comment (calixteman) [reply web/text_layer_builder.css:115]: The z-index change avoids the floating highlight button to be clickable:
image

Comment (nicolo-ribaudo) [reply web/text_layer_builder.css:116]: Whops, I made sure that it worked, then changed how I was applying the z-index, and forgot to re-check. I'll see how to add a test for this too.

File: web/text_layer_builder.js [hunk 8]
```diff
@@ -181,44 +184,116 @@ class TextLayerBuilder {
...
+    //    that we can apply the fix.
+    //  - We cannot detect when the user stops interacting with the selection,
+    //    because there is no difference between "the user is still holding
+    //    their finger on the selection 'bubble'" and "the user is lifter their
+    //    finger and then pressed the 'bubble' again". Thus, the .endOfContent
+    //    element will remain active until when the user interacts with the
+    //    page again, triggering a pointerup event.
+    this.#selectionChangeAbortController?.abort();
+    this.#selectionChangeAbortController = new AbortController();
+    document.addEventListener(
```
Comment (calixteman) [inline web/text_layer_builder.js:234]: Every text layer will add its listener for the `selectionchange` event, would it be possible to avoid that in having only one listener ?

Comment (calixteman) [reply web/text_layer_builder.js:234]: And when the text layer is destroyed (for example when scrolling), the listener isn't removed or did I miss something ?

Comment (nicolo-ribaudo) [reply web/text_layer_builder.js:234]: I could use a WeakMap to go from `.textLayer` to this class, and then in a global event listener I dispatch to the right handler. Let me try.

File: web/text_layer_builder.js [hunk 9]
```diff
@@ -181,44 +184,119 @@ class TextLayerBuilder {
...
       if (typeof PDFJSDev === "undefined" || !PDFJSDev.test("MOZCENTRAL")) {
-        end.style.top = "";
+        div.append(end);
+        end.style.width = "";
+        end.style.height = "";
       }
       end.classList.remove("active");
-    });
+      selectingThroughMouse = false;
+      prevRange = null;
```
[the remark this answers is not in the document]
Comment (nicolo-ribaudo) [reply web/text_layer_builder.js]: Yeah, at the end I'll squash :+1:

**Comment by nicolo-ribaudo** [comment]
@timvandermeij I managed to add a test when using a mouse (which before this PR fails in Chrome), but unfortunately puppeteer's API doesn't seem to allow selecting text emulating a touchscreen input.

File: web/text_layer_builder.js (hunk 8 above)
Comment (calixteman) [reply web/text_layer_builder.js:234]: Ah yes correct: I looked for removeEventListener...

Comment (nicolo-ribaudo) [reply web/text_layer_builder.js:234]: By trying to move to a single global `selectionchange` event listener I realized that:
- multi-page selection are possible (a single selection can span across multiple `.textLayer`s)
- multi-page selection currently flicker everywhere (Firefox&Chrome, mobile&desktop)

**Comment by calixteman** [comment]
In Firefox (desktop), it's possible to reproduce the flickering in setting the pref `layout.accessiblecaret.hide_carets_for_mouse_input` to `false` and in using the blue anchors to modify the selection.

**Comment by nicolo-ribaudo** [comment]
Oh thank you :) Do you think I can use it in any way to write a test with Puppeteer?

**Comment by timvandermeij** [comment]
Yes, Firefox-specific preferences are configured here: https://github.com/mozilla/pdf.js/blob/master/test/test.mjs#L907-L942

**Comment by nicolo-ribaudo** [comment]
I pushed [`7bb30a4` (#17923)](https://github.com/mozilla/pdf.js/pull/17923/commits/7bb30a43663b97e6952beffc022cb339696bd549) to do what suggested by @calixteman in https://github.com/mozilla/pdf.js/pull/17923#discussion_r1568482976. Commit description:

> Handle selectionchange events globally
>    
> This commit moves the selectionchange and pointerup event
> listeners to be shared across multiple TextLayerBuilder
> instances. This has two effects:
>    - we only need to register one global listener that then "dispatches"
>      the DOM updates in the correct .textLayer, rather than having one
>      per instance that needs to be careful about only handling selection
>      changes that affect it.
>    - the fix now works with multi-page selections, which were currently
>      also broken on Firefox desktop

I am working on a test for this multi-page flickering on Firefox desktop, then I'll try if `layout.accessiblecaret.hide_carets_for_mouse_input` lets me test the flickering behavior when using the carets.

File: web/text_layer_builder.js [hunk 10]
```diff
@@ -231,6 +200,135 @@ class TextLayerBuilder {
...
       event.stopPropagation();
     });
+
+    TextLayerBuilder.#textLayers.set(div, end);
+    TextLayerBuilder.#enableGlobalSelectionListener();
+  }
+
+  static #textLayers = new Map();
+
+  static #selectionChangeAbortController = null;
```
Comment (Snuffleupagus) [inline web/text_layer_builder.js:210]: Please note that we place all class fields, whether they are "normal" or `static` ones, at the *top* of the class and sorted alphabetically; hence please move these definitions up.

File: test/integration/highlight_editor_spec.mjs [hunk 11]
```diff
@@ -1760,4 +1760,231 @@ describe("Highlight Editor", () => {
...
+            .withContext(`In ${browserName}, second selection`)
+            .toMatch(/^\(frequently .* We call such a se-$/s);
+
+          await page.mouse.down();
+          await moveInSteps(page, intermediateCaretPos, finalCaretPos, 20);
+          await page.mouse.up();
+
+          expect(await getSelectedText(page))
+            .withContext(`In ${browserName}, third selection`)
+            .toMatch(/^\(frequently .* We call such a se-$/s);
```
Comment (nicolo-ribaudo) [inline test/integration/highlight_editor_spec.mjs:1985]: It's indeed possible to click on the caret and drag it around with Puppeteer :) Before this PR, this test fails with the selection starting at the beginning of the page.

File: test/test.mjs [hunk 12]
```diff
@@ -941,6 +941,8 @@ async function startBrowser({ browserName, headless, startUrl }) {
       "dom.events.asyncClipboard.clipboardItem": true,
       // It's helpful to see where the caret is.
       "accessibility.browsewithcaret": true,
+      "layout.accessiblecaret.enabled": true,
+      "layout.accessiblecaret.hide_carets_for_mouse_input": false,
```
Comment (nicolo-ribaudo) [inline test/test.mjs:945]: Is there a way to pass these two options just for one specific test?

Comment (calixteman) [reply test/test.mjs:945]: I don't know.
@whimboo, do you know if it's possible ?
If not, it'd be nice to have such a feature.

Comment (calixteman) [reply test/test.mjs:945]: So the only way is to open a new browser, this isn't ideal but it's the only solution we've.

Comment (whimboo) [reply test/test.mjs:945]: Yeah, until we have support for chrome scope this is the only solution. The launcher.spec.ts unit tests in Puppeteer have some examples for that as well in case you need some more details.

**Comment by nicolo-ribaudo** [comment]
All tests are passing locally, except for Chrome reftests because they kept timing out while I was trying to generate the reference images.

I had to add one more commit to fix a regression: [`de1e73b` (#17923)](https://github.com/mozilla/pdf.js/pull/17923/commits/de1e73b858cef40627a6fafa1f2f4fcb001c2bc0)

> Explicitly add z-index: 0 to .textLayer
>
> This creates a "stacking context", making sure that the elements
> inside `.textLayer` (on the z axis) remain inside `.textLayer`.
> Without this change, the `<span>`s inside `.textLayer` end up being
> on top of `.annotationLayer`.
> 
> This was caught by the freetext editor integration tests, that
> failed because we were trying to draw on top of some text.

**Comment by nicolo-ribaudo** [comment]
Friendly ping :)

I squashed all the commits into one, making sure that the description includes all the changes done after the original commit.

**Comment by nicolo-ribaudo** [comment]
The CI error seems unrelated -- Node.js 22 was just released and it looks like `canvas` cannot be built when using it.

**Comment by timvandermeij** [comment]
I'll try to have this reviewed in the next couple of days. I already had an initial look and it looks good so far, but there are a few details here and there that I'll need to review more carefully. Moreover, similar to #18019 given the nature of the change it'd feel better if we merge this after the April release (I hope to have that done either today or tomorrow) so it has quite some time to settle and we have time to do any follow-ups should the need for that arise.

**Review by timvandermeij — CHANGES_REQUESTED** [review]
First of all, sorry for the delay in reviewing; it took a bit more time to review this patch than I initially thought, and I wanted to make sure to do an in-depth review because this is quite important code for viewer behavior/experience. That's why I'm really happy with the new integration tests: they result in a lot more confidence in the correctness of the behavior because previously this was only really testable manually, which required even more care to avoid regressions.

I only have a few comments for the tests, but other than fixing the assertions so they pass on the bots too none of them are major or blocking for merging this. Nice work!

File: test/integration/text_layer_spec.mjs [hunk 13]
```diff
@@ -0,0 +1,243 @@
...
+      });
+    });
+
+    describe("using selection carets", () => {
+      let browser;
+      let page;
+
+      beforeAll(async () => {
+        browser = await startBrowser({
+          browserName: "firefox",
```
[the remark this answers is not in the document]
Comment (nicolo-ribaudo) [reply test/integration/text_layer_spec.mjs:162]: My understanding is that the test suite can either be run in Firefox or Firefox+Chrome modes, and that `it`/`describe` blocks are run only once and not once per browser (iteration across the browsers happens in `loadAndWait`, which is run _inside_ the tests). I will add a comment, but this test is running only for Firefox because there is no concept of "running the test suite for Chrome".

**Comment by nicolo-ribaudo** [comment]
I relaxed the assertions in the test by changing them to "the selection must be XYZ, but if there are a couple of characters before/after it's ok".

> Also, it seems like the carets test is not working in Firefox on Linux in headless mode (but it works in non-headless mode, or headless on MacOS). I'm investigating it.

The reason for this was that we were starting the selection on the _edge_ of the `<span>`, and in Firefox headless on Linux if was clicking on the underlying element rather than on the `<span>` itself. I added 1px to `middleLeftPosition`'s `x` and it fixed it.

File: test/integration/text_layer_spec.mjs [hunk 14]
```diff
@@ -0,0 +1,292 @@
...
+        );
+      });
+    });
+
+    describe("using selection carets", () => {
+      let browser;
+      let page;
+
+      beforeAll(async () => {
+        // Chrome does not support simluating caret-based selection, so this
```
Comment (Snuffleupagus) [inline test/integration/text_layer_spec.mjs:208]: Spelling-nit:
```suggestion
        // Chrome does not support simulating caret-based selection, so this
```

File: test/integration/text_layer_spec.mjs [hunk 15]
```diff
@@ -0,0 +1,243 @@
...
+
+            await page.mouse.move(positionStart.x, positionStart.y);
+            await page.mouse.down();
+            await moveInSteps(page, positionStart, positionEnd, 20);
+            await page.mouse.up();
+
+            expect(await getSelectedText(page))
+              .withContext(`In ${browserName}`)
+              .toBe(
+                browserName === "chrome"
```
[the remark this answers is not in the document]
Comment (nicolo-ribaudo) [reply test/integration/text_layer_spec.mjs]: > but I would expect the "a se-" bit at the end to be included in both browsers.

When quickly moving the mouse at the end of a line, Firefox doesn't select all the text but stops earlier (it selects everything if you move the mouse slower, or move it back, so it's not a problem in practice):

https://github.com/mozilla/pdf.js/assets/7000710/dd55a116-5a22-42fe-a5cc-32dfbf60001e

**Comment by timvandermeij** [comment]
The Linux bot is green now (the reported failures are known intermittents that we already track in #17931 in #16934, so they are unrelated to this patch), but the Windows bot still contains some assertion errors for the integration tests. You can find the assertion errors at the bottom of the logs at http://54.193.163.58:8877/e6e46cd33c757e6/output.txt.

Looking at the logs I noticed that there are some newline differences in the expected outputs. If I have to _guess_ (but I don't have a Windows machine at the moment to verify), I suspect at least one of the assertions to fail on Windows because https://github.com/mozilla/pdf.js/pull/17923/files#diff-996e1915aba8cc96ca5782e7c258d49a50f8b4adac9e7444258ab4933fe11bbcR131 uses `\n` while Windows probably uses `\r\n`. I'm not sure if this explains all Windows failures though because they don't all seem to use newlines in the assertions, but perhaps this helps as a first observation...

I don't have further comments on this patch, so once the assertions pass on Windows (and the commits are squashed and rebased onto the current master so the CI is also green again) I think we can merge this :-)

File: test/integration/text_layer_spec.mjs [hunk 16]
```diff
@@ -0,0 +1,292 @@
...
+      jasmine.addAsyncMatchers({
+        // Check that a page has a selection containing the given text, with
+        // some tolerance for extra characters before/after.
+        toHaveRoughlySelected({ pp }) {
+          return {
+            async compare(page, expected) {
+              const TOLERANCE = 10;
+
+              const actual = await page.evaluate(() =>
+                window.getSelection().toString()
```
Comment (timvandermeij) [inline test/integration/text_layer_spec.mjs:57]: We should probably replace `\r\n` with `\n` here, similar to what we do at https://github.com/mozilla/pdf.js/blob/d79aaee62a27c25774100d545a420020b8769717/test/integration/caret_browsing_spec.mjs#L20-L21, to eliminate Windows-specific differences and so the integration tests such as the one at https://github.com/mozilla/pdf.js/pull/17923/files#diff-996e1915aba8cc96ca5782e7c258d49a50f8b4adac9e7444258ab4933fe11bbcR131 can simply consistently use `\n` only.

File: test/integration/text_layer_spec.mjs [hunk 17]
```diff
@@ -54,7 +54,8 @@ describe("Text layer", () => {
               const TOLERANCE = 10;
 
               const actual = await page.evaluate(() =>
-                window.getSelection().toString()
+                // We need to replace EOL on Windows to match the expected string.
```
Comment (nicolo-ribaudo) [inline test/integration/text_layer_spec.mjs:57]:
```suggestion
                // We need to normalize EOL for Windows
```

**Comment by nicolo-ribaudo** [comment]
Rebased!

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
@nicolo-ribaudo We're down to just one failure on Windows now, so we have improved since the last fixup. Looking at the logs above, could this be a problem with the "roughly equals" function given that the assertions look _very_ close at least on a quick glance?

**Comment by nicolo-ribaudo** [comment]
@timvandermeij I relaxed the assertion a bit, hopefully it will pass now.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Nice work; thank you for the effort you put into this!
