### PR TITLE
XFA - Add the possibily to layout and measure text

### LINKED ISSUE #13500: XFA use of CDATA in exData section causes unhandled exception
Attach (recommended) or Link to PDF file here:
[Acrobat.pdf](https://github.com/mozilla/pdf.js/files/6602628/Acrobat.pdf)

Configuration:
- Web browser and its version: Firefox 89.0 x64
- Operating system and its version: Windows 10.0.19043.985
- PDF.js version: pr/13479 at ec1dd06c
- Is a browser extension: No

Steps to reproduce the problem:
1. enable XFA support
2. Open Acrobat.pdf

What is the expected behavior? (add screenshot)
PDF renders 
image

What went wrong? (add screenshot)
Receive console error. PDF is not loaded
```
TypeError: this.exData[$content][$text] is not a function
```
This appears to be caused by the use of `CDATA` in `exData` tags containing XHTML content. For example:
```xml
<exData contentType="text/html"><![CDATA[<body xfa:APIVersion="2.7.0.0" xmlns="http://www.w3.org/1999/xhtml" xmlns:xfa="http://www.xfa.org/schema/xfa-data/1.0/"><p style="letter-spacing:0in;text-align:left"><span style="xfa-spacerun:yes;font-family:Arial Black;kerning-mode:pair;font-size:8.742pt;color:#e44b25"> </span></p><p style="letter-spacing:0in;text-align:left"><span style="font-family:Arial Black;kerning-mode:pair;font-size:8.742pt;color:#e44b25;xfa-spacerun:yes">CLIENT INFORMATION</span></p></body>]]></exData>
```
(Removal of CDATA wrapper in a simpler example made the error go away)
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### PR DESCRIPTION
**Pull request by calixteman**
- some containers doesn't always have their 2 dimensions and those dimensions re based on contents;
  - so in order to measure text, we must get the glyph widths (for the xfa fonts) before starting the layout;
  - implement a word-wrap algorithm;
  - handle font change during text layout.

### CODE REVIEW

File: src/core/xfa/factory.js [hunk 1]
```diff
@@ -22,28 +22,61 @@ class XFAFactory {
...
-      return [0, 0, parseInt(width), parseInt(height)];
-    });
+    try {
+      this.pages = this.form[$toHTML]();
+      this.dims = this.pages.children.map(c => {
+        const { width, height } = c.attributes.style;
+        return [0, 0, parseInt(width), parseInt(height)];
+      });
+    } catch (e) {
+      console.log(e);
```
Comment (Snuffleupagus) [inline src/core/xfa/factory.js:42]: Please use `warn` instead, since we should never use `console.log(...)` *directly* in code residing in the `src/` folder.

**Comment by marco-c** [comment]
I'm assuming this is going to fix #13500?

**Comment by marco-c** [comment]
There seems to be a regression at least in firefox-hsbc_closure-page1.

**Comment by calixteman** [comment]
There are still an issue with `hsbc_closure-page3` so I slightly increase the width factor from 1.1 to 1.2.

**Comment by marco-c** [comment]
> There is still an issue with `hsbc_closure-page3` so I slightly increase the width factor from 1.1 to 1.2.

There's still a minor issue ("IBAN:" the ":" is on the following line)

**Comment by calixteman** [comment]
I don't understand why the issue is still there (`hsbc_closure-page3`)...
Normally the font used to render the "Non" (bottom left) is Arial and is embedded in the pdf.
And on my screen at least the "o" is almost a circle when I load the pdf locally when it isn't really a circle on the images reftest.
So maybe something is wrong with fonts in xfa reftests, I need to investigate.

**Comment by calixteman** [comment]
And of course I cannot reproduce locally, it seems that the font is correct.
The "O" are not the same from this png I generated locally.

**Comment by calixteman** [comment]
Finally tests are ok...

File: src/core/worker.js [hunk 2]
```diff
@@ -203,6 +198,17 @@ class WorkerMessageHandler {
           })
           .then(() => finishWorkerTask(task));
       }
+
+      const [numPages, fingerprint] = await Promise.all([
+        pdfManager.ensureDoc("numPages"),
+        pdfManager.ensureDoc("fingerprint"),
+      ]);
+
+      // Get htmlForXfa after numPages to avoid to create HTML 2 times.
```
Comment (marco-c) [inline src/core/worker.js:207]: Nit: 
```suggestion
      // Get htmlForXfa after numPages to avoid to create HTML twice.
```

File: src/core/xfa/template.js [hunk 3]
```diff
@@ -2622,7 +2660,7 @@ class Font extends XFAObject {
     ]);
     this.posture = getStringOption(attributes.posture, ["normal", "italic"]);
     this.size = getMeasurement(attributes.size, "10pt");
-    this.typeface = attributes.typeface || "";
+    this.typeface = attributes.typeface || "Myriad Pro";
```
Comment (marco-c) [inline src/core/xfa/template.js:2663]: Why "Myriad Pro" as the default?

**Review by marco-c — APPROVED** [review]
