### PR TITLE
Replace our `URL` polyfill with the one from `core-js`

### LINKED ISSUE #10280: pdfjs-dist npm update from 2.0.489 to 2.0.943 causes webpack error: Can't resolve 'babel-runtime/regenerator'
After updating our npm package for pdfjs-dist from 2.0.**489** to 2.0.**943**, webpack fails to build.
If we downgrade back to version 2.0.489 all is well again and the errors go away.

Here's a copy of the webpack build log showing the failures:
```
 10% building 1/1 modules 0 activei ｢wds｣: Project is running at http://localhost:8081/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from C:\xxxxxx\Website\dist                                                                                                                                                                                                                                                                                                                                                         × ｢wdm｣:    2471 modules
ERROR in ./node_modules/pdfjs-dist/lib/core/pdf_manager.js
Module not found: Error: Can't resolve 'babel-runtime/regenerator' in 'C:\xxxxxx\Website\node_modules\pdfjs-dist\lib\core'

ERROR in ./node_modules/pdfjs-dist/lib/core/evaluator.js
Module not found: Error: Can't resolve 'babel-runtime/regenerator' in 'C:\xxxxxx\Website\node_modules\pdfjs-dist\lib\core'

ERROR in ./node_modules/pdfjs-dist/lib/core/obj.js
Module not found: Error: Can't resolve 'babel-runtime/regenerator' in 'C:\xxxxxx\Website\node_modules\pdfjs-dist\lib\core'

ERROR in ./node_modules/pdfjs-dist/lib/display/fetch_stream.js
Module not found: Error: Can't resolve 'babel-runtime/regenerator' in 'C:\xxxxxx\Website\node_modules\pdfjs-dist\lib\display'

ERROR in ./node_modules/pdfjs-dist/lib/display/network.js
Module not found: Error: Can't resolve 'babel-runtime/regenerator' in 'C:\xxxxxx\Website\node_modules\pdfjs-dist\lib\display'

ERROR in ./node_modules/pdfjs-dist/lib/display/node_stream.js
Module not found: Error: Can't resolve 'babel-runtime/regenerator' in 'C:\xxxxxx\Website\node_modules\pdfjs-dist\lib\display'

ERROR in ./node_modules/pdfjs-dist/lib/display/transport_stream.js
Module not found: Error: Can't resolve 'babel-runtime/regenerator' in 'C:\xxxxxx\Website\node_modules\pdfjs-dist\lib\display'

ERROR in ./node_modules/pdfjs-dist/lib/shared/message_handler.js
Module not found: Error: Can't resolve 'babel-runtime/regenerator' in 'C:\xxxxxx\Website\node_modules\pdfjs-dist\lib\shared'

ERROR in ./node_modules/pdfjs-dist/lib/web/ui_utils.js
Module not found: Error: Can't resolve 'babel-runtime/regenerator' in 'C:\xxxxxx\Website\node_modules\pdfjs-dist\lib\web'
i ｢wdm｣: Failed to compile.
```

Configuration:
- Chrome: latest
- Windows 10 Professional: Latest updates
- PDF.js version: 2.0.**943**
- Is a browser extension: No

What is the expected behavior? (add screenshot)
For the webpack build to succeed.

What went wrong? (add screenshot)
The webpack build fails, citing errors in the pdfjs-dist npm package for: 
**`Module not found: Error: Can't resolve 'babel-runtime/regenerator'`** 

Package.json excerpt follows:
```
{
 ...
 "engines": {
    "node": ">= 8.9.0"
  },
  "private": true,
  "devDependencies": {
    "@babel/core": "^7.1.6",
    "@babel/plugin-proposal-class-properties": "^7.1.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/preset-env": "^7.1.6",
    "babel-eslint": "^10.0.1",
    "babel-loader": "^8.0.4",
    "clean-webpack-plugin": "^1.0.0",
    "copy-webpack-plugin": "^4.6.0",
    "css-loader": "^1.0.1",
    "eslint": "^5.9.0",
    "file-loader": "^2.0.0",
    "html-loader": "^0.5.5",
    "html-webpack-plugin": "^3.2.0",
    "http-server": "^0.11.1",
    "less": "^3.8.1",
    "less-loader": "^4.1.0",
    "mini-css-extract-plugin": "^0.4.4",
    "optimize-css-assets-webpack-plugin": "^5.0.1",
    "style-loader": "^0.23.1",
    "webpack": "^4.26.0",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "^3.1.10"
  },
  "dependencies": {
    "@babel/polyfill": "^7.0.0",
    "bootstrap": "^3.3.7",
    "font-awesome": "^4.7.0",
    "jquery": "^3.3.1",
    "jquery-ui": "^1.12.1",
    "moment": "^2.22.2",
    "pdfjs-dist": "^2.0.943",
    "popper.js": "^1.14.5",
    "uuid": "^3.3.2",
    "whatwg-fetch": "^3.0.0"
  }
}
```

### LINKED ISSUE #10490: Investigate replacing the `URL` polyfill with the, upcoming, one from core-js
An *upcoming* release of core-js, see https://github.com/zloirock/core-js/releases/tag/v3.0.0-beta.5, will include a `URL` polyfill. Since various core-js polyfills are already in use, and with good results, once the core-js `URL` polyfill is officially released it would probably be a good idea to try and use it instead of including/maintaining one in the PDF.js library; see https://github.com/mozilla/pdf.js/blob/master/external/url/url-lib.js.

### PR DESCRIPTION
**Pull request by timvandermeij**
Fixes #10490.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
> Do you perhaps have time to check if the viewer still works in IE and Edge with these commits applied?

Unfortunately it does *not* work in IE11, with errors being thrown inside of https://github.com/zloirock/core-js/blob/a2b5534edae71a72ae297b85902b80d7a8e4ce40/packages/core-js/internals/internal-state.js#L16-L23

**Comment by Snuffleupagus** [comment]
I just found https://github.com/zloirock/core-js/issues/514, which seems very much relevant here. Basically you'll need to add `node_modules`, or perhaps just `node_modules[\\\/]core-js`, to the `babel-loader` exclude option at https://github.com/mozilla/pdf.js/blob/d7c7f1555182ac19eb6261c0e035289b281f0d8c/gulpfile.js#L188

Looking at https://github.com/babel/babel-loader it seems to suggest excluding the entire `node_modules` directory, but I'm not sure if there'd be any side-effects from doing that!?

Quickly testing this PR locally with `exclude: /(node_modules[\\\/]core-js|src[\\\/]core[\\\/](glyphlist|unicode))/,` seemed to work, but it'd probably be a good idea to diff the built files with/without that to ensure that nothing looks trivially broken.

File: src/shared/compatibility.js [hunk 1]
```diff
@@ -205,23 +205,53 @@ const hasDOM = typeof window === 'object' && typeof document === 'object';
...
+    // The current image decoders don't use the `URL` constructor, so it
+    // doesn't need to be polyfilled for the IMAGE_DECODERS build target.
+    return;
+  }
+  if (typeof PDFJSDev !== 'undefined' && !PDFJSDev.test('GENERIC')) {
+    // The `URL` constructor is assumed to be available in the extension builds.
+    return;
+  }
+
+  let isURLSupported = false;
```
Comment (Snuffleupagus) [inline src/shared/compatibility.js]: Given that `core-js` should have its own [feature detection](https://github.com/zloirock/core-js/blob/master/packages/core-js/internals/native-url.js), could/should all of this code simply be replaced by `require('core-js/web/url');` instead?

Comment (Snuffleupagus) [inline src/shared/compatibility.js]: Given that `core-js` should have its own [feature detection](https://github.com/zloirock/core-js/blob/master/packages/core-js/internals/native-url.js), could/should all of this code simply be replaced by just `require('core-js/web/url');` instead?

**Review by Snuffleupagus — COMMENTED** [review]
Please remove the `url` mention from https://github.com/mozilla/pdf.js/blob/33252920398f34142ece1fea7899a98935441cc7/gulpfile.js#L555 as well.

**Comment by timvandermeij** [comment]
Thank you for helping out with testing this! I'll make the changes soon and make sure to diff the results. I'll start with `node_modules[\\\/]core-js` since that looks like the safest option given that there is no real need to exclude the entire `node_modules` folder. I think you're right about leaving the feature detection to `core-js` as well; I didn't know that it had that.

**Comment by timvandermeij** [comment]
I have made the requested changes. I also made a diff of the built files of the `generic` target and nothing seemed trivially broken to me, but I would like to ask to test this in IE again just make sure that everything works as intended since excluding `core-js` would only really impact browsers like IE anyway as most of the polyfills we have left are for IE.

**Review by Snuffleupagus — APPROVED** [review]
The viewer loaded successfully in IE11, so this seem to work fine now :-)

Looks good to me, thanks for doing this!

File: src/shared/compatibility.js [hunk 2]
```diff
@@ -205,23 +205,37 @@ const hasDOM = typeof window === 'object' && typeof document === 'object';
...
+  if (typeof PDFJSDev !== 'undefined' && PDFJSDev.test('IMAGE_DECODERS')) {
+    // The current image decoders don't use the `URL` constructor, so it
+    // doesn't need to be polyfilled for the IMAGE_DECODERS build target.
+    return;
+  }
+  if (typeof PDFJSDev !== 'undefined' && !PDFJSDev.test('GENERIC')) {
+    // The `URL` constructor is assumed to be available in the extension builds.
+    return;
+  }
+  globalScope.URL = require('core-js/web/url');
```
Comment (Snuffleupagus) [inline src/shared/compatibility.js]: Actually, can you please check if *only* `require('core-js/web/url');` is sufficient, without the explicit assignment, since that's probably a better pattern in general here!?
