### PR TITLE
[Editor] Always give the focus to the ink editor when starting drawing (bug 1867588)

### LINKED ISSUE #17373: Editor cannot be selected, and editing-state getting mixed up
Attach (recommended) or Link to PDF file here: N/A

Configuration:
- Web browser and its version: N/A
- Operating system and its version: N/A
- PDF.js version: 4.0.303 [a3637e653]
- Is a browser extension: N/A

Steps to reproduce the problem:
1. Open https://mozilla.github.io/pdf.js/web/viewer.html#page=1
2. Enable InkEditing.
3. Draw something on *the first* page (but do *not* hit e.g. <kbd>Esc</kbd>).
4. Scroll down to the second page.
5. Draw something on *the second* page.
6. Disable InkEditing.
7. Re-enable InkEditing.
8. Select the drawing on *the second* page (works fine).
9. Scroll up to the first page.
10. Try to select the drawing on *the first* page.

What is the expected behavior? (add screenshot)
The drawing becomes selected.

What went wrong? (add screenshot)
You cannot select the previous drawing on *the first* page with the mouse. (Furthermore, if you enable FreeText- or Stamp-Editing instead you can still draw on the page.)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): N/A

/cc @calixteman Can you please take a look?
Note that I *suspect* that this might be a regression, but I've unfortunately not had time to bisect yet.

### PR DESCRIPTION
**Pull request by calixteman**
This way, when the editor is blurred, it can be committed and everything works fine.
It fixes issue #17373.

### CODE REVIEW

File: test/integration/ink_editor_spec.mjs [hunk 1]
```diff
@@ -256,4 +257,44 @@ describe("Ink Editor", () => {
       );
     });
   });
+
+  fdescribe("Ink editor must be committed when blurred", () => {
```
Comment (Snuffleupagus) [inline test/integration/ink_editor_spec.mjs:261]:
```suggestion
  describe("Ink editor must be committed when blurred", () => {
```

**Review by Snuffleupagus — APPROVED** [review]
Please don't forget to re-enable all integration tests.

r=me, thank you!
