### PR TITLE
Fix the group bbox when the numbers are too big

### LINKED ISSUE #20872: Form XObject with extreme BBox values causes blank white page in Chromium-based browsers
### Description

Some PDFs contain Form XObjects with astronomically large BBox values (e.g. `±8.988e76 ≈ Number.MAX_VALUE / 20`), used to express "no clipping / cover the entire page". When pdf.js renders such a PDF in a Chromium-based browser, the entire page is blank white.

### Steps to reproduce

1. Open a PDF containing a Form XObject with BBox `[-8.988e76, -8.988e76, 8.988e76, 8.988e76]` in a Chromium-based browser
2. The page renders as entirely blank white

This does not affect Firefox (Gecko uses double precision for path coordinates).

### Expected behavior

The page renders normally. An extreme BBox intended as "no clipping" should be treated as covering the full page.

### Environment

- pdf.js version: 5.5.207
- Browser: Chromium-based (Chrome, Edge, Electron, etc.)

### PR DESCRIPTION
**Pull request by calixteman**
It fixes #20872.

### CODE REVIEW

**Review by timvandermeij — APPROVED** [review]
r=me, with passing tests. Thank you!

File: src/core/evaluator.js [hunk 1]
```diff
@@ -483,6 +483,10 @@ class PartialEvaluator {
     const { dict } = xobj;
     const matrix = lookupMatrix(dict.getArray("Matrix"), null);
     const bbox = lookupNormalRect(dict.getArray("BBox"), null);
+    let f32bbox = bbox && new Float32Array(bbox);
+    if (f32bbox.some(x => !isFinite(x))) {
```
Comment (Snuffleupagus) [inline src/core/evaluator.js]: Sorry, but won't this line throw when `bbox === null`?
```suggestion
    if (f32bbox?.some(x => !isFinite(x))) {
```

**Review by timvandermeij — APPROVED** [review]
