### PR TITLE
Fix several issues with radial/axial shadings and tiling patterns.

### LINKED ISSUE #13325: Graphics problems on PDF in web viewer
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 90.0.4430.93
- Operating system and its version: macOs Big Sur 11.2.3
- PDF.js version: 2.7.570
- Is a browser extension: No

Steps to reproduce the problem:
1. Load the attached pdf in https://mozilla.github.io/pdf.js/web/viewer.html
2. Go to page 46. Dotted lines are missing in the graphics (see screenshot from acrobat reader)

What is the expected behavior? (add screenshot) See the screenshot
[Technical_Guide_UK.pdf](https://github.com/mozilla/pdf.js/files/6413001/Technical_Guide_UK.pdf)
Screenshot 2021-05-03 at 07 46 09

### PR DESCRIPTION
**Pull request by brendandahl**
Previously, we set the base transformation and pattern matrix
directly to the main rendering ctx of the page, however doing this
caused the current transform to be lost. This would cause issues
with things like shear missing so the pattern was misaligned or when
stroke was used the scale of the line width or dash would be wrong.
Instead we should leave the current transform and use setTransfrom
on the pattern so it is applied correctly. For axial and radial shadings I had
to create a temporary canvas to draw the shading so I could in turn
use setTransform.

Fixes: #13325, #6769, #7847, #11018, #11597, #11473

The following already in the corpus are improved:
issue8078-page1
issue1877-page1

### CODE REVIEW

File: src/display/pattern_helper.js [hunk 1]
```diff
@@ -37,21 +37,57 @@ ShadingIRs.RadialAxial = {
...
           const c = colorStops[i];
           grad.addColorStop(c[0], c[1]);
         }
-        return grad;
+
+        tmpCtx.fillStyle = grad;
+        tmpCtx.fill();
+
+        const pattern = ctx.createPattern(tmpCanvas.canvas, "repeat");
+        pattern.setTransform(new DOMMatrix(ctx.mozCurrentTransformInverse));
```
Comment (Snuffleupagus) [inline src/display/pattern_helper.js:89]: I *really* don't want to complicate this patch in any way (especially for the `MOZCENTRAL` build), given how much it improves the pattern handling, but are we worried about people using the general PDF.js library in older Firefox versions?

---

According to https://developer.mozilla.org/en-US/docs/Web/API/CanvasPattern/setTransform#browser_compatibility, using a `DOMMatrix` as the argument has only been supported since Firefox 79 (the current ESR is still on the 78 branch).

**Review by Snuffleupagus — APPROVED** [review]
Looks great to me, thank you!

**Comment by brendandahl** [comment]
Now also fixes #11473.

**Review by Snuffleupagus — APPROVED** [review]

**Comment by Snuffleupagus** [comment]
Fixes #10955 as well, right?

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thanks a lot for fixing this!

/botio makeref
