### PR TITLE
When zooming replace the css-zoomed canvas by the new one only when rendering is finished

### LINKED ISSUE #18622: [Regression] The `zoomLayer`-functionality is broken after PR 17817
### Attach (recommended) or Link to PDF file

[wuppertal_2012.pdf](https://github.com/user-attachments/files/16648028/wuppertal_2012.pdf)

### Web browser and its version

N/A

### Operating system and its version

N/A

### PDF.js version

`master`, or any version after PR #17817

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Load the attached PDF document in the viewer.
2. Wait until initial rendering is complete.
3. Change the zoom level to e.g. `page-width`. (It must be a zoom operation that triggers *immediately*, i.e. not using `defaultZoomDelay`.)

### What is the expected behavior?

That the previously rendered canvas, as stored in `this.zoomLayer` on the `PDFPageView`-instance, is visible while the new canvas renders *in the background*.

Note that you need a fairly slow rendering page to easily spot this, which is probably why the issue has gone unnoticed.

### What went wrong?

The new canvas renders visibly, which `this.zoomLayer` is intended to avoid (such that the page is "usable" while re-rendering occurs.)

### Link to a viewer

_No response_

### Additional context

`git bisect` gave the following output, i.e. this points to PR #17817:
```
918b500ca5075f8b03167ef276c990e6987190ca is the first bad commit
commit 918b500ca5075f8b03167ef276c990e6987190ca
Author: Calixte Denizet <calixte.denizet@gmail.com>
Date:   Thu Mar 21 12:51:08 2024 +0100

    Avoid wrong scrolling when calling zoomReset

    The goal of this patch is to fix the test:
    https://searchfox.org/mozilla-central/source/toolkit/components/pdfjs/test/browser_pdfjs_zoom.js

    It's a regression due to #17790.

 test/integration/viewer_spec.mjs       | 32 ++++++++++++++++++++++++++++++++
 web/annotation_editor_layer_builder.js |  1 -
 web/pdf_page_view.js                   |  7 ++++++-
 3 files changed, 38 insertions(+), 2 deletions(-)
```

/cc @calixteman

### PR DESCRIPTION
**Pull request by calixteman**
It fixes #18622.

It avoids to recreate a canvasWrapper element in order minimize the DOM operations.

### CODE REVIEW

File: web/pdf_page_view.js [hunk 1]
```diff
@@ -1006,20 +980,27 @@ class PDFPageView {
...
-      if (!hasHCM || isLastShow) {
-        canvas.hidden = false;
+      if ((!prevCanvas && !hasHCM) || isLastShow) {
+        if (prevCanvas) {
+          prevCanvas.replaceWith(canvas);
+          prevCanvas.width = prevCanvas.height = 0;
+        } else if (hasHCM) {
+          canvasWrapper.append(canvas);
+        }
         showCanvas = null; // Only invoke the function once.
```
Comment (nicolo-ribaudo) [inline web/pdf_page_view.js:1001]: I'm a bit confused by the logic here. If `prevCanvas` exists and `hasHCM` is false, the first `(!prevCanvas && !hasHCM)` is `false` and thus we'll not show the new canvas until when `isLastShow` is true. This seems to contradict the comment above "Keep the canvas hidden until the first draw callback,"

File: web/pdf_page_view.js [hunk 2]
```diff
@@ -1006,20 +980,27 @@ class PDFPageView {
 
     // Keep the canvas hidden until the first draw callback, or until drawing
     // is complete when `!this.renderingQueue`, to prevent black flickering.
```
Comment (nicolo-ribaudo) [inline web/pdf_page_view.js:982]: This comments needs to be updated, since we are not keeping the canvas hidden until the first draw callback anymore (at least, not when we are re-drawing).

Comment (Snuffleupagus) [inline web/pdf_page_view.js:982]: Unfortunately it seems that the new implementation doesn't prevent the "black flickering" that this comment talks about since scrolling *very quickly* through the viewer, using the default `tracemonkey.pdf`, will now trigger this effect intermittently.

File: web/pdf_page_view.js [hunk 3]
```diff
@@ -508,33 +509,22 @@ class PDFPageView {
...
-    // resources immediately, which can greatly reduce memory consumption.
-    zoomLayerCanvas.width = 0;
-    zoomLayerCanvas.height = 0;
-
-    if (removeFromDOM) {
-      // Note: `ChildNode.remove` doesn't throw if the parent node is undefined.
-      this.zoomLayer.remove();
-    }
-    this.zoomLayer = null;
+    canvas.remove();
```
Comment (Snuffleupagus) [inline web/pdf_page_view.js:517]: Shouldn't the `canvas` be removed from the `#viewportMap` as well?

Comment (calixteman) [reply web/pdf_page_view.js:517]: The `#viewportMap` is a `WeakMap` so we don't care, right ?

File: web/pdf_page_view.js [hunk 4]
```diff
@@ -365,6 +366,8 @@ class PDFPageView {
 
   destroy() {
     this.reset();
+    this.#canvasWrapper?.remove();
+    this.#canvasWrapper = null;
```
[the remark this answers is not in the document]
Comment (calixteman) [reply web/pdf_page_view.js]: Ah I just noticed that too and I removed them.

File: web/pdf_page_view.js [hunk 5]
```diff
@@ -590,16 +580,10 @@ class PDFPageView {
...
-        this.#viewportMap.delete(this.canvas);
-        // Zeroing the width and height causes Firefox to release graphics
-        // resources immediately, which can greatly reduce memory consumption.
-        this.canvas.width = 0;
-        this.canvas.height = 0;
-        delete this.canvas;
-      }
-      this._resetZoomLayer();
+    if (!keepCanvasWrapper && this.#canvasWrapper) {
+      this.#canvasWrapper.remove();
```
Comment (Snuffleupagus) [inline web/pdf_page_view.js:584]: Isn't the DOM element already removed above, courtesy of the following line?
https://github.com/mozilla/pdf.js/blob/f4b09e9a62343f820da9a0eeee1baafbdc8d4e8f/web/pdf_page_view.js#L557

If that's accurate, maybe just add a comment here about it already being removed?

File: web/pdf_page_view.js [hunk 6]
```diff
@@ -805,41 +781,37 @@ class PDFPageView {
...
-    ) {
-      throw new Error("Expected `target` to be a canvas.");
+    const { canvas } = this;
+    if (!canvas) {
+      return;
     }
-    if (!target.hasAttribute("zooming")) {
-      target.setAttribute("zooming", true);
-      const { style } = target;
+    if (!canvas.hasAttribute("zooming")) {
```
Comment (Snuffleupagus) [inline web/pdf_page_view.js:794]: Not directly related to this patch, but I wonder if we still need the following CSS rule?
https://github.com/mozilla/pdf.js/blob/a4eb8407c1b3695be0d1f91791f393655b476dd9/web/pdf_viewer.css#L95-L98
Note that since a little while back, all `canvas`es have those properties set:
https://github.com/mozilla/pdf.js/blob/a4eb8407c1b3695be0d1f91791f393655b476dd9/web/pdf_viewer.css#L88-L89

File: web/pdf_page_view.js [hunk 7]
```diff
@@ -1004,22 +978,36 @@ class PDFPageView {
     const canvas = document.createElement("canvas");
     canvas.setAttribute("role", "presentation");
 
-    // Keep the canvas hidden until the first draw callback, or until drawing
-    // is complete when `!this.renderingQueue`, to prevent black flickering.
-    canvas.hidden = true;
```
Comment (Snuffleupagus) [inline web/pdf_page_view.js:1009]: If this is being removed, can we also the following CSS now?
https://github.com/mozilla/pdf.js/blob/a4eb8407c1b3695be0d1f91791f393655b476dd9/web/pdf_viewer.css#L91-L93

File: web/pdf_page_view.js [hunk 8]
```diff
@@ -805,41 +781,32 @@ class PDFPageView {
...
         const { width, height } = this.viewport;
         // Scale x and y because of the rotation.
-        scaleX = height / width;
-        scaleY = width / height;
+        const scaleX = height / width;
+        const scaleY = width / height;
+        canvas.style.transform = `rotate(${relativeRotation}deg) scale(${scaleX},${scaleY})`;
+      } else if (absRotation === 180) {
+        canvas.style.transform = `rotate(${relativeRotation}deg)`;
       }
```
Comment (Snuffleupagus) [inline web/pdf_page_view.js:809]: When using CSS-only zooming, which can be enabled by setting the option `maxCanvasPixels = 0`, things seem to break when the page is rotated back to the initial state.
```suggestion
        canvas.style.transform = `rotate(${relativeRotation}deg)`;
      } else {
        canvas.style.transform = ""; // absRotation === 0
      }
      
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, besides fixing a regression this patch feels like an overall improvement of this code; thank you.
