### PR TITLE
Strip out a reserved operator (9) from CFF char strings (fixes issue #15784)

### LINKED ISSUE #15784: Text in PDF missing
Attach (recommended) or Link to PDF file here:
[RE93815363.pdf](https://github.com/mozilla/pdf.js/files/10154659/RE93815363.pdf)

Configuration:
- Web browser and its version: Chrome Version 108.0.5359.95 (Offizieller Build) (64-Bit)
- Operating system and its version: Windows 10 21H2
- PDF.js version: Current nightly (3.2.37 [99cfef882]) and 3.0.279 [d0823066c]
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the PDF

What is the expected behavior? (add screenshot)
image

What went wrong? (add screenshot)
image

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

File: src/core/cff_parser.js [hunk 1]
```diff
@@ -108,38 +108,38 @@ const CFFStandardStrings = [
...
+  /* 0 */ null,
+  /* 1 */ { id: "hstem", min: 2, stackClearing: true, stem: true },
+  /* 2 */ null,
+  /* 3 */ { id: "vstem", min: 2, stackClearing: true, stem: true },
+  /* 4 */ { id: "vmoveto", min: 1, stackClearing: true },
+  /* 5 */ { id: "rlineto", min: 2, resetStack: true },
+  /* 6 */ { id: "hlineto", min: 1, resetStack: true },
+  /* 7 */ { id: "vlineto", min: 1, resetStack: true },
+  /* 8 */ { id: "rrcurveto", min: 6, resetStack: true },
+  /* 9 */ null,
```
Comment (Snuffleupagus) [inline src/core/cff_parser.js:120]: These comments are definitely helpful, but can we perhaps add one space to make the complete list line-up better?
```suggestion
  /*  0 */ null,
  /*  1 */ { id: "hstem", min: 2, stackClearing: true, stem: true },
  /*  2 */ null,
  /*  3 */ { id: "vstem", min: 2, stackClearing: true, stem: true },
  /*  4 */ { id: "vmoveto", min: 1, stackClearing: true },
  /*  5 */ { id: "rlineto", min: 2, resetStack: true },
  /*  6 */ { id: "hlineto", min: 1, resetStack: true },
  /*  7 */ { id: "vlineto", min: 1, resetStack: true },
  /*  8 */ { id: "rrcurveto", min: 6, resetStack: true },
  /*  9 */ null,
```

File: src/core/cff_parser.js [hunk 2]
```diff
@@ -673,6 +679,9 @@ class CFFParser {
         }
       }
     }
+    if (length !== data.length) {
+      data[length] = 14;
```
Comment (Snuffleupagus) [inline src/core/cff_parser.js:683]: Unless I'm missing something obvious, this only works as long as *a single* `9` operator is found.
For the general case, I believe that you actually need something like:
```suggestion
    if (length < data.length) {
      data.fill(/* endchar = */ 14, length);
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, with the comments addressed and passing tests; thank you!

File: src/core/cff_parser.js (hunk 2 above)
Comment (calixteman) [reply src/core/cff_parser.js:683]: I thought that the stuff after 14 would be ignored it's why I added only one 14.

Comment (Snuffleupagus) [reply src/core/cff_parser.js:683]: > I thought that the stuff after 14 would be ignored it's why I added only one 14.

That does sound reasonable; however I wonder if it's overall safer to have multiple `endchar`s rather than potentially unused "garbage" data at the end of a glyph?
*Please note:* I have no idea if this really matters, I'm just asking.
