### PR TITLE
[Editor] Allow to edit FreeText annotations

### LINKED ISSUE #15403: Support editing already existing annotations
Attach (recommended) or Link to PDF file here:
[dummy.pdf](https://github.com/mozilla/pdf.js/files/9497274/dummy.pdf)

Configuration:
- Tested in firefox beta and nightly.
- Microsoft Windows 10.
- Whatever pdf.js version comes with firefox beta and nightly.
- No, not an extension.

Steps to reproduce the problem:
1. Add a text annotation (Same thing applies if you used the ink annotation, but for this example we shall just use the text annotation) to the attached dummy.pdf (It can be anything, like foo, bar, foobar, and whatever else you want)
2. Save the PDF under a different name (It could be dummytwo.pdf it doesn't matter as long as its a separate file)

What is the expected behavior? (add screenshot)
I should be able to select the saved annotation (this issue applies to any PDF with saved annotations as well, not just made in pdf.js) and delete it or modify it further.
dummypdf

What went wrong?
I cannot delete it or edit it. As indicated by the screenshot, it acknowledges the existence of the annotation, but I can't delete it or modify it. I should be able to delete annotations or edit annotations made in pdf.js as well as any other PDF reader/writer that can make annotations.

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

File: src/display/editor/editor.js [hunk 1]
```diff
@@ -52,6 +52,22 @@ class AnnotationEditor {
...
+
+    serialize() {
+      return {
+        id: this.annotationElementId,
+        deleted: true,
+        pageIndex: this.pageIndex,
+      };
+    }
+  };
+
```
Comment (Snuffleupagus) [inline src/display/editor/editor.js:70]: Why is this defined "inline" here, since that feels strange/unnecessary?
I really think that we should simply format this as a normal `class FakeEditor extends AnnotationEditor { ... }` placed *after* [this line instead](https://github.com/mozilla/pdf.js/blob/9af50dc358fe4e4fa1ca93db1f5eb5560391f382/src/display/editor/editor.js#L613).

File: src/display/editor/freetext.js [hunk 2]
```diff
@@ -537,24 +568,65 @@ class FreeTextEditor extends AnnotationEditor {
...
+    return (
+      serialized.value !== value ||
+      serialized.fontSize !== fontSize ||
+      serialized.rect.some((x, i) => Math.abs(x - rect[i]) >= 1) ||
+      serialized.color.some((c, i) => c !== color[i]) ||
+      serialized.pageIndex !== pageIndex
+    );
+  }
+
+  #cheatInitialRect(delayed = false) {
```
Comment (Snuffleupagus) [inline src/display/editor/freetext.js:617]: Please add a comment explaining what this method does, and when and why we need it, since the name doesn't feel all that clear to me.

File: src/display/editor/annotation_editor_layer.js [hunk 3]
```diff
@@ -234,11 +259,26 @@ class AnnotationEditorLayer {
...
   attach(editor) {
     this.#editors.set(editor.id, editor);
+    if (
+      editor.annotationElementId &&
+      this.#uiManager.isDeletedAnnotationElement(editor.annotationElementId)
+    ) {
+      this.#uiManager.removeDeletedAnnotationElement(
+        editor.annotationElementId
+      );
+      editor.deleted = false;
```
Comment (Snuffleupagus) [inline src/display/editor/annotation_editor_layer.js:269]: Would it perhaps make sense, and be less error-prone, if we simply pass the `editor` to the `removeDeletedAnnotationElement`-method instead?
That way you could set the `editor.deleted = false;` line in that method and we'd not have to worry about remembering to do that manually here.

File: src/display/editor/annotation_editor_layer.js [hunk 4]
```diff
@@ -234,11 +259,26 @@ class AnnotationEditorLayer {
...
   }
 
   detach(editor) {
     this.#editors.delete(editor.id);
     this.#accessibilityManager?.removePointerInTextLayer(editor.contentDiv);
+
+    const { annotationElementId } = editor;
+    if (!this.#isDisabling && annotationElementId) {
+      editor.deleted = true;
+      this.#uiManager.addDeletedAnnotationElement(annotationElementId);
```
Comment (Snuffleupagus) [inline src/display/editor/annotation_editor_layer.js:280]: *Similar question as just above.*

File: test/integration/freetext_editor_spec.js [hunk 5]
```diff
@@ -837,4 +839,219 @@ describe("Editor", () => {
...
+
+          const editorIds = await getEditors(page, "freeText");
+          expect(editorIds.length).withContext(`In ${browserName}`).toEqual(6);
+
+          // All the current annotations should be serialized as null objects
+          // because they haven't been edited yet.
+          const serialized = await getSerialized(page);
+          expect(serialized).withContext(`In ${browserName}`).toEqual([]);
+
+          // DnD doesn't work well for the moment hence the test is disabled.
```
Comment (Snuffleupagus) [inline test/integration/freetext_editor_spec.js:867]: Is there an existing (upstream) bug or issue that we can reference here, so that we can eventually re-enable this test at some future point?

Comment (calixteman) [reply test/integration/freetext_editor_spec.js]: I finally managed to make it running with Chrome but not with Firefox (see https://bugzilla.mozilla.org/show_bug.cgi?id=1838638).

**Review by Snuffleupagus — APPROVED** [review]
This looks generally reasonable, although I've not looked at every little detail. However, given that this only applies when the user manually enables the FreeText-editor that should limit risk here.

Maybe this sort of change would benefit from uplifting to mozilla-central ASAP such that we can get some real-world testing done?

r=me, thank you!
