### PR TITLE
Always use the absolute value of the line thickness (issue 19633)

### LINKED ISSUE #19633: [Bug]: Issue with line thickness
### Attach (recommended) or Link to PDF file

[Pagine estratte senza titolo.pdf](https://github.com/user-attachments/files/19159893/Pagine.estratte.senza.titolo.pdf)

### Web browser and its version

Chrome 134.0.6998.35

### Operating system and its version

Windows 10 Pro 22H2

### PDF.js version

4.10.38

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

In the online demo page load this PDF and you can see the problem.

### What is the expected behavior?

The line thickness should be as on the original pdf

### What went wrong?

The thickness line is wrong.

Image

### Link to a viewer

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

File: src/core/evaluator.js [hunk 1]
```diff
@@ -2212,6 +2212,12 @@ class PartialEvaluator {
               })
             );
             return;
+          case OPS.setLineWidth:
+            // The thickness should be a non-negative number, as per spec.
+            // When the value is negative, Acrobat and Poppler take the absolute
+            // value while PDFium takes the max of 0 and the value.
+            args[0] = Math.abs(args[0]);
```
Comment (Snuffleupagus) [inline src/core/evaluator.js:2219]: We should probably also check that it's a number, and ignore it otherwise (with a warning?) to prevent issues?

Comment (Snuffleupagus) [reply src/core/evaluator.js:2219]: The lineWidth can also be set in a /ExtGState dictionary, hence that case needs to be handled as well:
https://github.com/mozilla/pdf.js/blob/d008452e80ca00eec32983b7ab139885e6bc9f56/src/core/evaluator.js#L1124

File: src/core/evaluator.js [hunk 2]
```diff
@@ -1122,6 +1122,12 @@ class PartialEvaluator {
         case "Type":
           break;
         case "LW":
+          if (typeof value !== "number") {
+            warn("Line width is not a number");
```
Comment (Snuffleupagus) [inline src/core/evaluator.js:1126]: Please update this one a little bit, to have a more consistent warning format.
```suggestion
            warn(`Invalid LW (line width): ${value}`);
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, with one comment; thank you.
