### PR TITLE
Remove unused OpenJPEG wasm fallback logic

### LINKED ISSUE #19921: [Bug]: Invalid `new URL` usage in `build/pdf.worker.mjs`
### Attach (recommended) or Link to PDF file

n/a

### Web browser and its version

n/a

### Operating system and its version

n/a

### PDF.js version

5.2.133

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

The `pdfjs-dist/build/pdf.worker.mjs` file contains this code:
```js
  if (typeof module_or_path === 'undefined') {
    module_or_path = new URL(
    /*webpackIgnore: true*/
    /*@vite-ignore*/
    'qcms_bg.wasm', import.meta.url);
  }
```
Which resolves to `<something>/pdfjs-dist/build/qcms_bg.wasm`. However, the correct URL is `<something>/pdfjs-dist/wasm/qcms_bg.wasm`.

### What is the expected behavior?

That code is just a fallback for when the path is not explicitly specified by the user. However, it's a fallback that will never work, because it resolves to a file that is guaranteed to not exist.

Either the fallback should be fixed to resolve to the correct file (better), or it should just be removed making the use-provided path required.

Probably fixing the fallback to use the right path would also allow getting rid of the webpack/vite comments.

### What went wrong?

/

### Link to a viewer

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
> Emscripten generates code that allows the caller to provide the Wasm module (thorugh Module.instantiateWasm), with a fallback in case .instantiateWasm is not provided. We always define instantiateWasm, so we can hard-code the check and let our dead code elimination logic remove the unused fallback.
>
> This commit also improved the dead code elimination logic so that if a function declaration becomes unused as a result of removing dead code, the function itself is removed.

Closes https://github.com/mozilla/pdf.js/issues/19921.

The diff for `pdf.worker.mjs` in the generic build is now:
```diff
--- ./docs/pdf.worker.old.mjs	2025-05-13 14:04:39.175001871 +0200
+++ ./docs/pdf.worker.new.mjs	2025-05-13 14:09:39.280078580 +0200
@@ -5338,12 +5338,6 @@
     };
     var _scriptName = import.meta.url;
     var scriptDirectory = "";
-    function locateFile(path) {
-      if (Module["locateFile"]) {
-        return Module["locateFile"](path, scriptDirectory);
-      }
-      return scriptDirectory + path;
-    }
     var readAsync, readBinary;
     if (ENVIRONMENT_IS_WEB || ENVIRONMENT_IS_WORKER) {
       try {
@@ -5430,58 +5424,6 @@
       throw e;
     }
     var wasmBinaryFile;
-    function findWasmBinary() {
-      if (Module["locateFile"]) {
-        return locateFile("openjpeg.wasm");
-      }
-      return new URL(
-      /*webpackIgnore: true*/
-      /*@vite-ignore*/
-      "openjpeg.wasm", import.meta.url).href;
-    }
-    function getBinarySync(file) {
-      if (file == wasmBinaryFile && wasmBinary) {
-        return new Uint8Array(wasmBinary);
-      }
-      if (readBinary) {
-        return readBinary(file);
-      }
-      throw "both async and sync fetching of the wasm failed";
-    }
-    async function getWasmBinary(binaryFile) {
-      if (!wasmBinary) {
-        try {
-          var response = await readAsync(binaryFile);
-          return new Uint8Array(response);
-        } catch {}
-      }
-      return getBinarySync(binaryFile);
-    }
-    async function instantiateArrayBuffer(binaryFile, imports) {
-      try {
-        var binary = await getWasmBinary(binaryFile);
-        var instance = await WebAssembly.instantiate(binary, imports);
-        return instance;
-      } catch (reason) {
-        err(`failed to asynchronously prepare wasm: ${reason}`);
-        abort(reason);
-      }
-    }
-    async function instantiateAsync(binary, binaryFile, imports) {
-      if (!binary && typeof WebAssembly.instantiateStreaming == "function") {
-        try {
-          var response = fetch(binaryFile, {
-            credentials: "same-origin"
-          });
-          var instantiationResult = await WebAssembly.instantiateStreaming(response, imports);
-          return instantiationResult;
-        } catch (reason) {
-          err(`wasm streaming compile failed: ${reason}`);
-          err("falling back to ArrayBuffer instantiation");
-        }
-      }
-      return instantiateArrayBuffer(binaryFile, imports);
-    }
     function getWasmImports() {
       return {
         a: wasmImports
@@ -5496,26 +5438,12 @@
         return wasmExports;
       }
       addRunDependency("wasm-instantiate");
-      function receiveInstantiationResult(result) {
-        return receiveInstance(result["instance"]);
-      }
       var info = getWasmImports();
-      if (Module["instantiateWasm"]) {
-        return new Promise((resolve, reject) => {
-          Module["instantiateWasm"](info, (mod, inst) => {
-            resolve(receiveInstance(mod, inst));
-          });
+      return new Promise((resolve, reject) => {
+        Module["instantiateWasm"](info, (mod, inst) => {
+          resolve(receiveInstance(mod, inst));
         });
-      }
-      wasmBinaryFile ??= findWasmBinary();
-      try {
-        var result = await instantiateAsync(wasmBinary, wasmBinaryFile, info);
-        var exports = receiveInstantiationResult(result);
-        return exports;
-      } catch (e) {
-        readyPromiseReject(e);
-        return Promise.reject(e);
-      }
+      });
     }
     class ExitStatus {
       name = "ExitStatus";
@@ -9396,9 +9324,6 @@
   }
   return visitor.buffer;
 }
-function parseJbig2(data) {
-  throw new Error("Not implemented: parseJbig2");
-}
 class SimpleSegmentVisitor {
   onPageInformation(info) {
     this.currentPageInfo = info;
@@ -57200,7 +57125,7 @@
       docId,
       apiVersion
     } = docParams;
-    const workerVersion = "5.2.183";
+    const workerVersion = "5.2.184";
     if (apiVersion !== workerVersion) {
       throw new Error(`The API version "${apiVersion}" does not match ` + `the Worker version "${workerVersion}".`);
     }
@@ -57733,8 +57658,8 @@
 
 ;// ./src/pdf.worker.js
 
-const pdfjsVersion = "5.2.183";
-const pdfjsBuild = "3f1ecc1ba";
+const pdfjsVersion = "5.2.184";
+const pdfjsBuild = "8e82502d6";
 globalThis.pdfjsWorker = {
   WorkerMessageHandler: WorkerMessageHandler
 };
```

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Oh well, the unused code removal is working properly, so the tests for the transform need to be updated to actually use those functions :)

File: external/builder/fixtures_babel/comments.js [hunk 1]
```diff
@@ -24,3 +26,4 @@ function f3() {
     "4";
   }
 }
+f3();
```
Comment (Snuffleupagus) [inline external/builder/fixtures_babel/comments.js:29]: Nit: Missing new line at the end here.

**Review by Snuffleupagus — COMMENTED** [review]
Please also fix the typo in the commit message: `OpenJPG` -> `OpenJPEG`.

File: external/builder/babel-plugin-pdfjs-preprocessor.mjs [hunk 2]
```diff
@@ -173,6 +192,19 @@ function babelPluginPDFJSPreprocessor(babel, ctx) {
...
       },
+      MemberExpression(path) {
+        // The Emscripten Compiler (emcc) generates code that allows the caller
+        // to provide the Wasm module (thorugh Module.instantiateWasm), with
+        // a fallback in case .instantiateWasm is not provided.
+        // We always define instantiateWasm, so we can hard-code the check
+        // and let our dead code elimination logic remove the unused fallback.
+        if (
+          path.parentPath.isIfStatement({ test: path.node }) &&
+          path.matchesPattern("Module.instantiateWasm")
```
Comment (Snuffleupagus) [inline external/builder/babel-plugin-pdfjs-preprocessor.mjs:203]: Would it be possible to add test(s) for this part in particular (in addition to the new ones already in the patch), such that we'll be "warned" if in the a future emcc changes the output format and thus breaks the dead code elimination?

**Comment by nicolo-ribaudo** [comment]
Rebased to include the changes that removed `import.meta.url` from qcms.

I couldn't find a nice way to test for this, instead I made the webpack build fail (after emitting the files) if the generated bundle contains `new URL(..., import.meta.url)`).

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you.

**Comment by johan44co** [comment]
Potentially, the removal of the fallback is making issues now:

Bildschirmfoto 2025-07-01 um 10 59 35

**Comment by nicolo-ribaudo** [comment]
This PR only removes unused code. It seems like you forgot to pass the `wasmUrl` parameter? (It's required since v5.0)

**Comment by cjlozanoDev** [comment]
> This PR only removes unused code. It seems like you forgot to pass the `wasmUrl` parameter? (It's required since v5.0)
Captura de pantalla 2025-07-03 a las 18 22 27

It happens to me exactly like the guy above. 

In my code I have this:

import * as pdfjsLib from 'pdfjs-dist'
import 'pdfjs-dist/build/pdf.worker.min.mjs'

const loadPdf = async () => {
  const canvas = pdfCanvas.value
  const context = canvas.getContext('2d')

  const loadingTask = pdfjsLib.getDocument({ data: base64ToUint8Array(pdfBase64.value) })
  
  ......
  
  
i tried copying the openjpeg.wasm file from the library's wasm folder from node_modules to my public folder. Then I did this: 

```
const loadingTask = pdfjsLib.getDocument({
data: base64ToUint8Array(pdfBase64.value),
workerOptions: {
     wasmUrl: '/openjpeg.wasm',  // copy from node_modules/pdfjsdist in my directory public
     wasmFallbackUrl: '/openjpeg_nowasm_fallback.js',  // copy from node_modules/pdfjsdist in my directory public
     standardFontDataUrl: '/standard_fonts/' // copy from node_modules/pdfjsdist in my directory public
   }
})
```

I've tried many ways and can't get it to work. With the previous version, I was able to load PDFs with JPX images without any problem.

Can you please tell me how to configure this now?

Thank you!

**Comment by johan44co** [comment]
The issue was solved by passing the wasmUrl parameter, the wasm folder can be found in the pdfjs-dist package or using a CDN:

```
pdfjs.getDocument({
  url: "...",
  wasmUrl: `https://unpkg.com/pdfjs-dist@${pdfjs.version}/wasm/`,
})
```

**Comment by cjlozanoDev** [comment]
> The issue was solved by passing the wasmUrl parameter, the wasm folder can be found in the pdfjs-dist package or using a CDN:
> 
> ```
> pdfjs.getDocument({
>   url: "...",
>   wasmUrl: `https://unpkg.com/pdfjs-dist@${pdfjs.version}/wasm/`,
> })
> ```
> 
> 

Thanks a lot.

I was going to comment that I'd solved it. In my case, I copied the wasm from the pdfjsdist folder in Node Modules to a directory in my project. In a Vite project, I copy it directly to public. With Webpack, if there's no public folder, I use a plugin to configure the copy to the desired folder and have it compiled. This way, it'll be available at runtime (so it's a URL). Finally, as you've mentioned, I pass the wasmUrl parameter pointing to this folder, which is copied to the configured address. Thanks again for your response.
