### PR TITLE
[Editor] Dispatch an event when some global states are changing (bug 1777695)

### LINKED ISSUE #15041: Support copying and pasting by right click context menu
Currently to copy and paste an added element, the user needs to select it and press CTRL+C and CTRL+V. It would be nice to also support context menu option.

### PR DESCRIPTION
**Pull request by calixteman**
- this way the context menu in Firefox can take into account what we
  have in the clipboard, if an editor is selected, ...
- when the user will click on a context menu item, an action will be
  triggered, hence this patch adds what is required to handle it;
- some tests will be added in the Firefox' patch.

### CODE REVIEW

File: web/firefoxcom.js [hunk 1]
```diff
@@ -384,6 +398,10 @@ class FirefoxExternalServices extends DefaultExternalServices {
     return new FirefoxPreferences();
   }
 
+  static setEditorStates(data) {
+    FirefoxCom.request("setEditorStates", data);
```
Comment (Snuffleupagus) [inline web/firefoxcom.js:402]: For consistency with existing methods, in the `FirefoxExternalServices`-class, maybe use:
```suggestion
  static updateEditorStates(data) {
    FirefoxCom.request("updateEditorStates", data);
```

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]

File: src/display/editor/editor.js [hunk 2]
```diff
@@ -218,11 +218,27 @@ class AnnotationEditor {
...
     return this.div;
   }
 
+  /**
+   * Onmousedown callback.
+   * @param {MouseEvent} event
+   */
+  mousedown(event) {
+    if (event.button !== 0) {
+      // Avoid to focus this editor because of a right click.
```
Comment (Snuffleupagus) [inline src/display/editor/editor.js:237]: Maybe tweak the comment slightly, now that the condition was updated above?
```suggestion
      // Avoid to focus this editor because of a non-left click.
```

File: src/display/editor/tools.js [hunk 3]
```diff
@@ -377,8 +405,54 @@ class AnnotationEditorUIManager {
...
+    isEmpty: true,
+    hasEmptyClipboard: true,
+    hasSomethingToUndo: false,
+    hasSomethingToRedo: false,
+    hasSelectedEditor: false,
+  };
+
   constructor(eventBus) {
     this.#eventBus = eventBus;
+    this.#eventBus._on("editingaction", this.#boundOnEditingAction);
```
Comment (Snuffleupagus) [inline src/display/editor/tools.js:421]: It doesn't seem that anything is ever removing this listener, as far as I can tell?
That means that when multiple documents have been opened in the GENERIC viewer, there'll be a number of old (and stale) listeners still around. While "editingaction"-support will *currently* only be implemented in Firefox, this is nonetheless something that we should fix here to prevent any future issues.

Basically, I think that the simplest solution would be to add e.g. a `destroy`-method to this class and having it run:
```javascript
this.#eventBus._off("editingaction", this.#boundOnEditingAction);
```
Then, in the viewer, remove line https://github.com/mozilla/pdf.js/blob/a1ac1a61b75064ef274f69da4aa0da7be9a575dd/web/base_viewer.js#L902
and instead add
```javascript
if (this.#annotationEditorUIManager) {
  this.#annotationEditorUIManager.destroy();
  this.#annotationEditorUIManager = null;
}
```
just after line https://github.com/mozilla/pdf.js/blob/a1ac1a61b75064ef274f69da4aa0da7be9a575dd/web/base_viewer.js#L642

**Review by Snuffleupagus — APPROVED** [review]
