### PR TITLE
Set 'dropEffect' based on 'effectAllowed' for drag-and-drop in the viewer (issue 14942)

### LINKED ISSUE #14942: Drop pdf document when dragging from mail app do not work
When I drag and drop a pdf from local directory pdf.js works fine and document gets displayed. But when the file dragged from mail app pdf.js do not display pdf.

Attach (recommended) or Link to PDF file here: not important, any pdf could be used to reproduce the issue.

Configuration:
- Web browser and its version: Chrome Version 101.0.4951.64 (Official Build) (arm64) (the same issue on other browsers)
- Operating system and its version: MacOS Monterey version 12.4 (but the same happens on windows based systems)
- PDF.js version: 2.10.562 and later
- Is a browser extension: no (not sure what is it)

Steps to reproduce the problem:
1. prepare an email with a pdf document
2. drag and drop pdf directly from the mail app

What is the expected behavior?
pdf.js should display a document

What went wrong?
pdf.js do **not** display a document

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### PR DESCRIPTION
**Pull request by Pldi23**
[Issue #14942 ](https://github.com/mozilla/pdf.js/issues/14942)

Applied the solution suggested in comments

### CODE REVIEW

File: web/app.js [hunk 1]
```diff
@@ -2187,7 +2187,11 @@ function webViewerInitialized() {
     appConfig.mainContainer.addEventListener("dragover", function (evt) {
       evt.preventDefault();
 
-      evt.dataTransfer.dropEffect = "move";
+      evt.dataTransfer.dropEffect =
+        evt.dataTransfer.effectAllowed === "all" ||
+        evt.dataTransfer.effectAllowed === "uninitialized"
+          ? "move"
+          : evt.dataTransfer.effectAllowed;
```
Comment (Snuffleupagus) [inline web/app.js:2194]: Let's reduce some unnecessary repetition here, by introducing a temporary variable:
```javascript
const { effectAllowed } = evt.dataTransfer;
evt.dataTransfer.dropEffect =
  effectAllowed === "all" || effectAllowed === "uninitialized"
  ? "move"
  : effectAllowed;
```

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]
Can you please use the standard names in the commit message, since that seems a little clearer. And please also include a link to https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/effectAllowed in the commit message.

E.g. with the commit message looking something like this:
```
Set `dropEffect` based on `effectAllowed` for drag-and-drop in the viewer (issue 14942)

See https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/effectAllowed
```

File: web/app.js (hunk 1 above)
Comment (Snuffleupagus) [reply web/app.js:2194]: Wait, this will now also support "none" which would thus break drag-and-drop here. I don't think that we actually want that, so based on https://github.com/mozilla/pdf.js/issues/14942#issuecomment-1132715355 it seems that we should perhaps just special-case the "copy"-case instead:
```javascript
evt.dataTransfer.dropEffect =
  evt.dataTransfer.effectAllowed  === "copy" ? "copy" : "move";
```

Comment (Pldi23) [reply web/app.js]: applied in [b1941f8](https://github.com/mozilla/pdf.js/pull/14948/commits/b1941f89ea09cbdb10a281926ee8351bf7faf62e)

Comment (Snuffleupagus) [reply web/app.js]: Thank you; please also squash the commits, see https://github.com/mozilla/pdf.js/wiki/Squashing-Commits

Comment (Pldi23) [reply web/app.js]: yep, squashed

**Comment by calixteman** [comment]
Some double quotes are likely missing here:
https://github.com/HorizenOfficial/botio/blob/0cf5a068d8c534b518577be1d2b2ae2895581f81/lib/module.js#L107

**Comment by Snuffleupagus** [comment]
> Some double quotes are likely missing here: https://github.com/HorizenOfficial/botio/blob/0cf5a068d8c534b518577be1d2b2ae2895581f81/lib/module.js#L107

Or perhaps in https://github.com/arturadib/botio/blob/master/lib/module.js, which I believe is what powers https://github.com/mozilla/botio-files-pdfjs

**Review by Snuffleupagus — APPROVED** [review]
Thank you!
