### PR TITLE
Don't try to collect a nonexistent field because of an invalid ref

### LINKED ISSUE #17232: Form annotation not shown because of UnknownErrorException
Hello,
When I upload the pdf in attachment, it fails to show the form annotation.
Could you please help?

Additional info: the original files comes from https://www.overzeesesocialezekerheid.be/nl/documenten/aanvraag-beeindiging-aansluiting.pdf
I have opened the original pdf with the default pdf tool (Preview) in MacOS, selected and deleted the signature field.
Thanks!

Attach (recommended) or Link to PDF file here:
This is the file where the signature field has been deleted.
[aanvraag-beeindiging-aansluiting.pdf](https://github.com/mozilla/pdf.js/files/13280636/aanvraag-beeindiging-aansluiting.pdf)

Configuration:
- Web browser and its version: Chrome Version 118.0.5993.118 (Official Build) (64-bit)
- Operating system and its version: Windows 10 Enterprise 21H2
- PDF.js version: 4.0.191 [72338ce05]
- Is a browser extension: No

Steps to reproduce the problem:
1. Go to https://mozilla.github.io/pdf.js/web/viewer.html
2. Upload the file in attachment.

What is the expected behavior? 
If we open the pdf in Foxit or Adobe Reader, the first field shows "my own name"
2023-11-07_14h52_45

What went wrong? 
2023-11-07_14h54_27

The file is shown but there are no annotation in the form. Moreover, an exception is thrown in the console.

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

File: src/core/document.js [hunk 1]
```diff
@@ -1713,6 +1713,9 @@ class PDFDocument {
 
   #collectFieldObjects(name, fieldRef, promises, annotationGlobals) {
     const field = this.xref.fetchIfRef(fieldRef);
+    if (!field) {
```
Comment (Snuffleupagus) [inline src/core/document.js:1716]: This could still cause errors in a corrupt PDF document, please ensure that it's actually a dictionary since the code below currently assumes that.
```suggestion
    if (!(field instanceof Dict)) {
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, with the comment addressed; thank you!
