### PR TITLE
Use appearance stream to render locked annotations (bug 1723568)

### LINKED ISSUE #16120: Watermark not displayed properly
Attach (recommended) or Link to PDF file here:
[document_signature.pdf](https://github.com/mozilla/pdf.js/files/10908004/document_signature.pdf)

Configuration:
- Web browser and its version:Google Chrome 110.0.5481.100 (Official Build) (64-bit)
- Operating system and its version: Windows 10 Enterprise
- PDF.js version: 2.5.207
- Is a browser extension: no

Steps to reproduce the problem:
1. go to https://mozilla.github.io/pdf.js/web/viewer.html 
2. click on Open File button
3. choose attached pdf

What is the expected behavior? (add screenshot)
correct

What went wrong? (add screenshot)
wrong
Sandbox watermark is not displayed as in original file.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

File: src/core/annotation.js [hunk 1]
```diff
@@ -514,6 +514,13 @@ class Annotation {
     this._isOffscreenCanvasSupported = params.isOffscreenCanvasSupported;
     this._fallbackFontDict = null;
     this._needAppearances = false;
+
+    // The annotation cannot be changed (neither its position/visibility nor its
+    // contents), hence we can just display its appearance and don't generate
+    // a HTML element for it.
+    const isLocked = !!(this.flags & AnnotationFlag.LOCKED);
+    const isContentLocked = !!(this.flags & AnnotationFlag.LOCKEDCONTENTS);
+    this.data.noHTML = isLocked && isContentLocked;
```
Comment (Snuffleupagus) [inline src/core/annotation.js:523]: Can we please just move this code up a little bit, such that we can directly set `noHTML: isLocked && isContentLocked,` in the `this.data` object?

**Review by Snuffleupagus — APPROVED** [review]
r=me, this was simpler than I expected; thank you!
