### PR TITLE
Override the minimum font size when rendering the text layer

### LINKED ISSUE #14426: Highlight went wrong when the text font-size less than the minimum font-size of the browser
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
- Operating system and its version: Intel Mac OS X 10_15_7
- PDF.js version: the latest
- Is a browser extension: no

Steps to reproduce the problem:
1. open the demo in chrome https://mozilla.github.io/pdf.js/web/viewer.html
2. search any word in the pdf, such as 'JavaScript'
3. zoom out the pdf until the minimum font-size less than 12px, and you will see the problem

What is the expected behavior? (add screenshot)
image

What went wrong? (add screenshot)
image

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): 
https://mozilla.github.io/pdf.js/web/viewer.html

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
Fixes https://github.com/mozilla/pdf.js/issues/14426

Commit message:

> **Overrride the minimum font size when rendering the text layer**
>
> Browsers have an accessibility option that allows user to enforce a minimum font size for all text rendered in the page, regardless of what the font-size CSS property says. For example, it can be found in Firefox under `font.minimum-size.x-western`.
>
> When rendering the <span>s in the text layer, this causes the text layer to not be aligned anymore with the underlying canvas. While normally accessibility features should not be worked around, in this case it is *not* improving accessibility:
> - the text is transparent, so making it bigger doesn't make it more readable
> - the selection UX for users with that accessibility option enabled is worse than for other users (it's basically unusable).
>
> While there is tecnically no way to ignore that minimum font size, this commit does it by multiplying all the `font-size`s in the text layer by minFontSize, and then scaling all the `<span>`s down by 1/minFontSize.

This PR detects the min font size similarly to https://github.com/mozilla/pdf.js/pull/14427, with a few changes:
- the minimum font size is only computed once, rather than for every rendered element
- I used `getBoundingClientRect().height` rather than `getComputedStyle().fontSize`, because `getComputedStyle().fontSize` returns the minimum font size in Chrome and Safari but not in Firefox (https://bugzilla.mozilla.org/show_bug.cgi?id=1903360)

~~Marking as draft because I still have to run all the tests locally, and add a new test.~~

### CODE REVIEW

File: src/display/text_layer.js [hunk 1]
```diff
@@ -452,6 +467,27 @@ class TextLayer {
...
+  /**
+   * @returns {number} The minimum font size enforced by the browser
+   */
+  static #getMinFontSize() {
+    if (this.#minFontSize === null) {
+      const div = document.createElement("div");
+      div.style.opacity = 0;
+      div.style.lineHeight = 1;
+      div.style.fontSize = "1px";
+      div.innerHTML = "X";
```
Comment (Snuffleupagus) [inline src/display/text_layer.js:479]: Is this actually necessary, or can the *safer* `textContent` be used instead?

File: src/display/text_layer.js [hunk 2]
```diff
@@ -452,6 +467,27 @@ class TextLayer {
...
+  static #getMinFontSize() {
+    if (this.#minFontSize === null) {
+      const div = document.createElement("div");
+      div.style.opacity = 0;
+      div.style.lineHeight = 1;
+      div.style.fontSize = "1px";
+      div.textContent = "X";
+      document.body.append(div);
+      // In `display:block` elements contain a single line of text,
+      // the height matched the line height (which, when set to 1,
```
Comment (nicolo-ribaudo) [inline src/display/text_layer.js:482]:
```suggestion
      // the height matches the line height (which, when set to 1,
```

**Comment by timvandermeij** [comment]
Nit for the commit message: s/Overrride/Override.

Let's trigger a round of tests:

/botio test

**Comment by nicolo-ribaudo** [comment]
Uhm, taking a look at the failures 🤔 It didn't fail locally for some reason

**Comment by timvandermeij** [comment]
Note that most of them are known intermittents, see https://github.com/mozilla/pdf.js/issues?q=is%3Aopen+is%3Aissue+label%3Aintermittent for the associated issues, so I think only the `Text layer when the browser enforces a minimum font size renders spans with the right size` failure in the Windows logs is actually relevant for this PR.

**Comment by nicolo-ribaudo** [comment]
There was some variability on the exact number of pixels across different platforms (and across different browsers on the same OS, even if the test only checks Firefox), so I relaxed the assertion to be "the with must be within 3% of 315px". Without the fix the width is more than 200% of the expected with, so a 3% tolerance is ok to verify that the fix is being applied.

I don't have access to a windows machine, could you re-run the bot?

**Comment by nicolo-ribaudo** [comment]
One of the two remaining windows failures is a flaky tests (https://github.com/mozilla/pdf.js/issues/17931), the other one is a timeout also related to pasting (`Stamp Editor Copy and paste a stamp with an alt text must check that the pasted image has an alt text`).

**Review by timvandermeij — APPROVED** [review]
The change looks good to me, but I'd also prefer a review from @Snuffleupagus to make sure that the comments/concerns from the original PR #14427 are fully resolved here. Thanks!

**Comment by Snuffleupagus** [comment]
Unfortunately it seems that the new integration test added in this PR has intermittent shutdown issues, based on the logs in http://54.241.84.105:8877/dbd55648b66ba65/output.txt:
```
[32m.[0mTEST-PASSED | renders spans with the right size
JavaScript warning: http://127.0.0.1:34837/build/generic/build/pdf.mjs, line 10681: Script terminated by timeout at:
#getMinFontSize@http://127.0.0.1:34837/build/generic/build/pdf.mjs:10681:25
#appendText@http://127.0.0.1:34837/build/generic/build/pdf.mjs:10573:71
#processItems@http://127.0.0.1:34837/build/generic/build/pdf.mjs:10534:23
render/pump/<@http://127.0.0.1:34837/build/generic/build/pdf.mjs:10453:27
```

**Comment by timvandermeij** [comment]
I think the problem is that pretty much all integration tests call `closePages` in the `afterAll` handler, which ensures that proper cleanup is done using the `testingClose` method; see https://github.com/mozilla/pdf.js/blob/658b5fab5dffaf2d1a2006fb4573f2f910282452/test/integration/test_utils.mjs#L83-L94. However, in this new integration test, and notably also in other tests in this file, this pattern is not used and a separate browser is spawned instead. This is for good reason, but instead of only calling `browser.close()`, which doesn't do any cleanup of PDF.js, we should make sure the tests that spawn a new browser use the same cleanup mechanism as the regular tests that don't do that.

We have a reference to the pages in the separate browser in these tests, so I think we should be able to simply call https://github.com/mozilla/pdf.js/blob/658b5fab5dffaf2d1a2006fb4573f2f910282452/test/integration/test_utils.mjs#L83-L94 with an array of said pages to fix the issue. (This should also be done for the other integration tests in this file that spawn a separate browser, but in a separate commit since that is more-or-less a follow-up on previous PRs.)

**Comment by timvandermeij** [comment]
I have fixed the issue for the existing test in https://github.com/mozilla/pdf.js/pull/18317/commits/f4053c2b3e84fce7090451042193bdc01a18da87, which should make it a bit easier to mirror that approach for this test and that _should_ solve the shutdown issue identified above.

**Comment by nicolo-ribaudo** [comment]
Thank you! I'll rebase and fix it.

**Comment by timvandermeij** [comment]
Could you rebase this patch once more onto the current master branch, now that all other test framework fixes have landed? I'll retrigger the tests here afterwards.

**Comment by nicolo-ribaudo** [comment]
Done 👍

**Comment by nicolo-ribaudo** [comment]
The remaining failure on Linux is https://github.com/mozilla/pdf.js/issues/17931.

File: src/display/text_layer.js [hunk 3]
```diff
@@ -114,6 +116,7 @@ class TextLayer {
       div: null,
       properties: null,
       ctx: null,
+      minFontSize: null,
```
Comment (Snuffleupagus) [inline src/display/text_layer.js:119]: Could we not compute the value directly here instead?

(Note that the pre-existing `ctx` case is slightly "special", since that one depends on the `lang`-property which isn't available at this point.)

File: src/display/text_layer.js [hunk 4]
```diff
@@ -326,7 +331,11 @@ class TextLayer {
       divStyle.left = `${scaleFactorStr}${left.toFixed(2)}px)`;
       divStyle.top = `${scaleFactorStr}${top.toFixed(2)}px)`;
     }
-    divStyle.fontSize = `${scaleFactorStr}${fontHeight.toFixed(2)}px)`;
+    // We multiply the font size by #getMinFontSize(), and then #layout will
+    // scale the element by 1/#getMinFontSize(). This allows us to effectively
+    // ignore the minimum font size enforced by the browser, so that the text
+    // layer <span>s can always match the size of the text in the canvas.
+    divStyle.fontSize = `${scaleFactorStr}${(TextLayer.#getMinFontSize() * fontHeight).toFixed(2)}px)`;
```
Comment (Snuffleupagus) [inline src/display/text_layer.js:338]: Any reason to not use the already cached value here?
```suggestion
    divStyle.fontSize = `${scaleFactorStr}${(this.#layoutTextParams.minFontSize * fontHeight).toFixed(2)}px)`;
```

Comment (nicolo-ribaudo) [reply src/display/text_layer.js]: This made me realize that, given that `TextLayer.#getMinFontSize()` always returns the same value anyway, I don't even need to store it in `this.#layoutTextParams`.

With this, plus your suggestion in the other comment to just compute it in the constructor, I simplified a big how we access the computed `minFontSize` to just always grab it from `TextLayer.#minFontSize`.

File: src/display/text_layer.js [hunk 5]
```diff
@@ -456,6 +469,25 @@ class TextLayer {
     return canvasContext;
   }
 
+  /**
+   * @returns {number} The minimum font size enforced by the browser
```
Comment (Snuffleupagus) [inline src/display/text_layer.js:473]: This method no longer returns anything.
```suggestion
   * Compute the minimum font size enforced by the browser.
```

File: src/display/text_layer.js [hunk 6]
```diff
@@ -456,6 +469,25 @@ class TextLayer {
...
+      div.style.lineHeight = 1;
+      div.style.fontSize = "1px";
+      div.textContent = "X";
+      document.body.append(div);
+      // In `display:block` elements contain a single line of text,
+      // the height matches the line height (which, when set to 1,
+      // matches the actual font size).
+      this.#minFontSize = div.getBoundingClientRect().height;
+      div.remove();
+    }
```
Comment (Snuffleupagus) [inline src/display/text_layer.js:488]: Maybe use an early return here?
```suggestion
    if (this.#minFontSize !== null) {
      return;
    }
    const div = document.createElement("div");
    div.style.opacity = 0;
    div.style.lineHeight = 1;
    div.style.fontSize = "1px";
    div.textContent = "X";
    document.body.append(div);
    // In `display:block` elements contain a single line of text,
    // the height matches the line height (which, when set to 1,
    // matches the actual font size).
    this.#minFontSize = div.getBoundingClientRect().height;
    div.remove();
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, with the final comments addressed and all tests passing; thank you!

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you for fixing this!

**Comment by nicolo-ribaudo** [comment]
Thanks for the reviews!
