### PR TITLE
[api-minor] Improve performances with image masks (bug 857031)

### LINKED ISSUE #14652: PDF rendering is quite slow with some PDFs, compared to other viewers
**Attach (recommended) or Link to PDF file here:**
[Floor2.pdf](https://github.com/mozilla/pdf.js/files/8214771/Floor2.pdf)

**Configuration:**
- Web browser and its version: Chrome 99.0.4844.51
- Operating system and its version: macOS monterey 12.2.1 (21D62)
- PDF.js version: newest
- Is a browser extension: no

**Steps to reproduce the problem:**
1. Open the attached PDF with the official viewer: https://mozilla.github.io/pdf.js/web/viewer.html
2. Try zooming in/out, move the PDF around, etc.

**What is the expected behavior? (add screenshot)**
It should be quicker. I tried opening the same PDF with "preview" on mac, and with chrome, and they both render the PDF much-much faster, without any noticable loading/hanging.

**What went wrong? (add screenshot)**
It takes quite a while to load up/render the PDF, and then when I start zooming in and out, it often just turns white, and it hangs for 5-10 seconds before I can see something again.

By the way, I noticed this issue in a complex project, where we use the pdf.js javascript API to render certain parts of the PDF (with a defined viewbox), but it's much easier to reproduce the issue with the official PDF viewer. I sometimes had performance issues before, but in those cases other viewers weren't really any better for those PDFs. With this particular PDF, other viewers/renderers can outperform PDF.js by a lot.

So maybe someone here can find the reason behind it, and even fix it.

### PR DESCRIPTION
**Pull request by calixteman**
- it's the second part of the fix for https://bugzilla.mozilla.org/show_bug.cgi?id=857031;
- some image masks can be used several times but at different positions;
- an image need to be pre-process before to be rendered:
  * rescale it;
  * use the fill color/pattern.
- the two operations above are time consuming so we can cache the generated canvas;
- the cache key is based on the current transform matrix (without the translation part)
  and the current fill color when it isn't a pattern.
- the rendering of the pdf in the above bug is really faster than without this patch.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
I'll hopefully have time to look at this tomorrow, however in the meantime I've got one immediate suggestion:
Let's do an update on mozilla-central now, such that e.g. PR #14754 and this one won't land in the exact same Firefox Nightly.

Given the sort of changes that are being made in these PRs, there's always a regression risk (since our test-coverage is likely not perfect) and it seems much easier to figure out *exactly* where something broke if we space-out the landing slightly.

File: src/core/evaluator.js [hunk 1]
```diff
@@ -1676,6 +1677,9 @@ class PartialEvaluator {
               const localImage = localImageCache.getByName(name);
               if (localImage) {
                 operatorList.addOp(localImage.fn, localImage.args);
+                if (localImage.args.length !== 0 && localImage.args[0].count) {
```
Comment (Snuffleupagus) [inline src/core/evaluator.js:1680]: Here, and similarly below, this will check for a `count` property even for OPS where that doesn't make sense. For "normal" images, note how the *first* argument is a string.

Hence, please change this to be explicit about what's intended in these cases:
```javascript
if (
  localImage.fn === OPS.paintImageMaskXObject &&
  localImage.args[0] &&
  localImage.args[0].count > 0
) {
```

File: src/core/evaluator.js [hunk 2]
```diff
@@ -675,6 +675,7 @@ class PartialEvaluator {
           width: imgData.width,
           height: imgData.height,
           interpolate: imgData.interpolate,
+          count: 1,
```
Comment (Snuffleupagus) [inline src/core/evaluator.js:678]: Won't the `QueueOptimizer` potentially break this, or at make things less efficient, unless this new parameter is *also* added to the list in:
https://github.com/mozilla/pdf.js/blob/fffce7910e63038cc15cd01522a768ee86e081be/src/core/operator_list.js#L253-L265

File: src/display/canvas.js [hunk 3]
```diff
@@ -1275,6 +1281,21 @@ class CanvasGraphics {
     this.cachedCanvases.clear();
     this.cachedPatterns.clear();
 
+    for (const cache of this._cachedBitmaps) {
+      for (const result of cache.values()) {
+        if (result instanceof ImageBitmap) {
+          result.close();
```
Comment (Snuffleupagus) [inline src/display/canvas.js:1287]: Are these `ImageBitmap`s the same ones that are cached in the API, in `PDFPageProxy.objs`?
Because if so, won't closing them here break the next rendering when e.g. zooming is done in the viewer for pages where [this code](https://github.com/mozilla/pdf.js/blob/fffce7910e63038cc15cd01522a768ee86e081be/src/display/api.js#L2800-L2803) *is not* being hit?

Naively, it seems to me that we should *not* be releasing `ImageBitmap` here and simply let the existing caching in the API handle that.

File: src/display/canvas.js [hunk 4]
```diff
@@ -1121,6 +1125,8 @@ class CanvasGraphics {
     }
     this._cachedScaleForStroking = null;
     this._cachedGetSinglePixelWidth = null;
+    this._cachedBitmaps = [];
+    this._cachedBitmapsMap = new WeakMap();
```
Comment (Snuffleupagus) [inline src/display/canvas.js:1129]: Do we need *two* different, but closely related, caches here since it feels like it's adding some overall complexity to the code?

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]

File: src/display/canvas.js (hunk 4 above)
Comment (calixteman) [reply src/display/canvas.js:1129]: Yep it's because I chose a WeakMap and I added this array in order to be able to clean up the data at the end.
But likely a WeakMap is useless here and a Map should be enough.

File: src/display/canvas.js [hunk 5]
```diff
@@ -1275,6 +1280,16 @@ class CanvasGraphics {
     this.cachedCanvases.clear();
     this.cachedPatterns.clear();
 
+    for (const cache of this._cachedBitmapsMap.values()) {
+      for (const canvas of cache.values()) {
+        if (canvas instanceof HTMLCanvasElement) {
```
Comment (Snuffleupagus) [inline src/display/canvas.js:1285]: This code-path can be taken in Node.js environments as well, right?
In that case I don't believe that `HTMLCanvasElement` exists, which would throw an Error here and break things. Hence please add a `typeof HTMLCanvasElement !== undefined` check to avoid any problems.

File: src/display/canvas.js [hunk 6]
```diff
@@ -1349,19 +1365,60 @@ class CanvasGraphics {
...
     const fillColor = this.current.fillColor;
     const isPatternFill = this.current.patternFill;
-    const maskCanvas = this.cachedCanvases.getCanvas(
-      "maskCanvas",
-      width,
-      height
-    );
-    const maskCtx = maskCanvas.context;
-    putBinaryImageMask(maskCtx, img);
+    const objToCanvas = ctx.mozCurrentTransform;
```
Comment (Snuffleupagus) [inline src/display/canvas.js:1368]: I know that you're just moving pre-existing code, but how about giving this variable a more appropriate name (since I don't see how `objToCanvas` actually makes sense)?

File: src/display/canvas.js [hunk 7]
```diff
@@ -1349,19 +1365,60 @@ class CanvasGraphics {
...
+      // In case we've a pattern fill we just keep the scaled version of
+      // the image.
+      // Only the scaling part matters, the translation part is just used
+      // to compute offsets.
+      // TODO: handle the case of a pattern fill if it's possible.
+      const withoutTranslation = objToCanvas.slice(0, 4);
+      cacheKey = isPatternFill
+        ? withoutTranslation
+        : [withoutTranslation, fillColor];
+      cacheKey = JSON.stringify(cacheKey);
```
Comment (Snuffleupagus) [inline src/display/canvas.js:1383]: Nit: Maybe just doing something like this instead?
```javascript
cacheKey = JSON.stringify(
  isPatternFill ? withoutTranslation : [withoutTranslation, fillColor]
);
```

File: src/display/canvas.js [hunk 8]
```diff
@@ -1349,19 +1365,60 @@ class CanvasGraphics {
...
-      "maskCanvas",
-      width,
-      height
-    );
-    const maskCtx = maskCanvas.context;
-    putBinaryImageMask(maskCtx, img);
+    const objToCanvas = ctx.mozCurrentTransform;
+
+    let cache, cacheKey, scaled, maskCanvas;
+    if ((img.bitmap || img.data) && img.count >= 2) {
```
Comment (Snuffleupagus) [inline src/display/canvas.js:1371]: Nit: Maybe using `... && img.count > 1` instead?

**Review by Snuffleupagus — APPROVED** [review]
I don't *think* that the integration-test failures are related to this patch, since similar failures were observed elsewhere as well.

---

How about adding *the first page* of the document in bug 857031 as a linked reference-test, to ensure that we have proper test-coverage for all this new code?

r=me, since this looks reasonable (although the `src/display/canvas.js`-code is one part of the code-base that I'm finding quite difficult to navigate at times).
