### PR TITLE
Don't detect nw.js as node.js

### LINKED ISSUE #9071: Error: Protocol "blob:" not supported. Expected "https:" could not be cloned.
Fails to open drag&dropped file when running in NW.js. This is regression from version 1.8.581 where the file could be opened.

Configuration:
- Web browser and its version:  NW.js (0.26.0)
- Operating system and its version: Windows 10
- PDF.js version: 1.10.86 (worked before with version 1.8.581)
- Is a browser extension: yes (I think NW.js runs it internally as an extension)

Steps to reproduce the problem:
1. Create a NW.js application:
1a: Create `package.json`:
~~~json
{
	"name": "pdfjs-bug",
	"version": "1.0.0",
	"dependencies": {
		"nw": "0.26.0-sdk",
		"pdfjs-dist": "1.10.86",
		"copyfiles": "1.2.0"
	},
	"scripts": {
		"start": "copyfiles -f node_modules/pdfjs-dist/build/pdf.js node_modules/pdfjs-dist/build/pdf.worker.js src && nw src"
	}
} 
~~~
1b. Create `src/package.json`:
~~~json
{
	"name": "PDFJS",
	"main": "index.html"
}
~~~
1c. Create `src/index.html`:
~~~html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>Test</title>
		<script src="pdf.js"></script>
	</head>
	<body>
		DROP<br />
		<script>
const el = document.documentElement;
el.ondragover = e => {
	e.preventDefault();
};
el.ondrop = e => {
	e.preventDefault();
	const file = e.dataTransfer.files[0];
	const url = URL.createObjectURL(file);
	PDFJS.getDocument(url).then(pdf => document.body.insertAdjacentHTML('beforeend', pdf.numPages + '<br />'));
};
		</script>
	</body>
</html>
~~~
2. Install and run the NW.js application.
2a. Install the application with `npm install`.
2b. Run the application with `npm start`.
3. Drag&drop any PDF file from filesystem to the application.

What is the expected behavior? (add screenshot)
The number of pages is shown on the page.

What went wrong? (add screenshot)
The number of pages is not shown. Exception is logged into the console:

~~~
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Worker': Error: Protocol "blob:" not supported. Expected "https:" could not be cloned.
    at MessageHandler.postMessage (chrome-extension://abnijbeggncckhejmpopebkmidpfinlj/pdf.js:1390:19)
    at sendStreamRequest (chrome-extension://abnijbeggncckhejmpopebkmidpfinlj/pdf.js:1207:14)
    at chrome-extension://abnijbeggncckhejmpopebkmidpfinlj/pdf.js:1272:7
    at <anonymous>
index.html:1 Uncaught (in promise) UnknownErrorExceptiondetails: "UnknownErrorException: Cannot read property 'headersReady' of null"message: "Cannot read property 'headersReady' of null"name: "UnknownErrorException"__proto__: Error
    at UnknownErrorExceptionClosure (chrome-extension://abnijbeggncckhejmpopebkmidpfinlj/pdf.js:443:37)
    at Object.<anonymous> (chrome-extension://abnijbeggncckhejmpopebkmidpfinlj/pdf.js:446:2)
    at __w_pdfjs_require__ (chrome-extension://abnijbeggncckhejmpopebkmidpfinlj/pdf.js:45:30)
    at Object._typeof (chrome-extension://abnijbeggncckhejmpopebkmidpfinlj/pdf.js:8064:23)
    at __w_pdfjs_require__ (chrome-extension://abnijbeggncckhejmpopebkmidpfinlj/pdf.js:45:30)
    at Object.defineProperty.value (chrome-extension://abnijbeggncckhejmpopebkmidpfinlj/pdf.js:88:18)
    at chrome-extension://abnijbeggncckhejmpopebkmidpfinlj/pdf.js:91:10
    at webpackUniversalModuleDefinition (chrome-extension://abnijbeggncckhejmpopebkmidpfinlj/pdf.js:24:59)
    at chrome-extension://abnijbeggncckhejmpopebkmidpfinlj/pdf.js:25:3
~~~

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### PR DESCRIPTION
**Pull request by romainptit**
nw.js is chrome plus nodejs.
It will succeed everywhere chrome succeeds, but fail in many cases where nodejs succeeds (see issue 9071).
So it's safer to consider it as a browser context rather than a nodejs context.

Fixes #9071.

### CODE REVIEW

**Comment by morille** [comment]
Here is the nw.js documentation that explains `process.versions['nw']`
[http://docs.nwjs.io/en/latest/References/Changes%20to%20Node/](url)

File: src/shared/is_node.js [hunk 1]
```diff
@@ -15,5 +15,7 @@
 /* globals module, process */
 
 module.exports = function isNodeJS() {
-  return typeof process === 'object' && process + '' === '[object process]';
+  return typeof process === 'object' &&
+    process + '' === '[object process]' &&
+    !process.versions['nw'];
```
Comment (timvandermeij) [inline src/shared/is_node.js]: Can you change it to something like this for readability and explanation of why we exclude NW.js?

```javascript
// Exclude NW.js since, even though it's based on Node.js,
// it works like a browser.
return typeof process === 'object' &&
       process + '' === '[object process]' &&
       !process.versions['nw'];
```

**Review by timvandermeij — COMMENTED** [review]
Once this is done, please squash the commits into one; refer to https://github.com/mozilla/pdf.js/wiki/Squashing-Commits for how to do that easily. Thank you!

**Comment by morille** [comment]
Done, thanks for the doc.

File: src/shared/is_node.js [hunk 2]
```diff
@@ -15,5 +15,10 @@
 /* globals module, process */
 
 module.exports = function isNodeJS() {
-  return typeof process === 'object' && process + '' === '[object process]';
+  // NW.js is a browser context, but copies some node objects.
+  // For more information see the 'Separate Context Mode' doc:
+  // http://docs.nwjs.io/en/latest/
```
Comment (Snuffleupagus) [inline src/shared/is_node.js]: Why not link *directly* to the relevant page instead, to save people from having to search around for the referenced content?
Please just change this entire comment to something like this instead (note that URL in comments are except from the general line-length limit): 
```javascript
// NW.js is a browser context, but copies some Node.js objects; see
// http://docs.nwjs.io/en/latest/For%20Users/Advanced/JavaScript%20Contexts%20in%20NW.js/#separate-context-mode
```

Comment (morille) [reply src/shared/is_node.js]: NW.js doc evolves so I prefered to not give a link that could be broken later, then harder to resolve than domain name + section name.

**Comment by morille** [comment]
Done and squashed.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Let's do this. Thank you!
