### PR TITLE
[JS] Make the date parser less strict

### LINKED ISSUE #15490: Form Field with date format is handled incorrectly for different browsers.
Attach (recommended) or Link to PDF file here:
[PDF mit Datum_edit.pdf](https://github.com/mozilla/pdf.js/files/9622672/PDF.mit.Datum_edit.pdf)

Configuration:
- Web browser and its version: Chrome Version 105.0.5195.127 (Offizieller Build) (64-Bit) / Firefox 105.0 (64-Bit)
- Operating system and its version: Windows 11 Pro 21H2 (German de-DE)
- PDF.js version: v2.16.105
- Is a browser extension: no
- PDF is in en-EN, but same behaviour for de-DE (or de-AT, which was the original problem)

Steps to reproduce the problem in **Chrome**:
1. Open attached PDF with PDFjs in Chrome
2. Enter a date into a date field (e.g. field labeled "von") in the format "d.M.yyyy" (e.g. skipping the leading zero from 01.09.2022 -> 1.9.2022)
3. Click out of the Field to lose focus
4. Date is displayed in format "MM.dd.yyyy"

What is the expected behavior? (add screenshot)
Date is displayed in original format OR date is displayed in "dd.MM.yyyy" format OR an error is shown in the browser stating the format is invalid

Steps to reproduce the problem in **Firefox**:
1. Open attached PDF with PDFjs in Firefox
2. Enter a date into a date field (e.g. field labeled "von") in the format "d.M.yyyy"
3. Click out of the Field to lose focus
4. An Error is shown in the browser stating the format is invalid.

What is the expected behavior? (add screenshot)
Date is displayed in original format OR date is displayed in "dd.MM.yyyy" format OR an error is shown in the browser stating the format is invalid

What went wrong? (add screenshot)
As far as I can tell, the browsers support different date Formats when parsing a string to a date. 
With chrome the date beeing swapped can easily be overlooked. 
Entering "1.9.2022" in a date field and instead of the 1st of september you get the 9th of january can be fatal.

### PR DESCRIPTION
**Pull request by calixteman**
and display the expected date formt as a tooltip.

### CODE REVIEW

File: src/core/annotation.js [hunk 1]
```diff
@@ -2780,6 +2781,25 @@ class TextWidgetAnnotation extends WidgetAnnotation {
       !this.hasFieldFlag(AnnotationFieldFlag.FILESELECT) &&
       this.data.maxLen !== 0;
     this.data.doNotScroll = this.hasFieldFlag(AnnotationFieldFlag.DONOTSCROLL);
+
+    // Check if we have a date or time.
+    const {
```
Comment (timvandermeij) [inline src/core/annotation.js:2786]: Would this perhaps fit on a single line, so it's a bit more compact, if formatted like `const { data: { actions } } = this;` ?

File: src/core/annotation.js [hunk 2]
```diff
@@ -2780,6 +2781,25 @@ class TextWidgetAnnotation extends WidgetAnnotation {
...
+      data: { actions },
+    } = this;
+    if (actions?.Keystroke?.[0]) {
```
Comment (timvandermeij) [inline src/core/annotation.js]: Could there be multiple actions defined here, and if so, should we perhaps loop over them and break if we find a match instead of always picking the first one?

File: src/display/annotation_layer.js [hunk 3]
```diff
@@ -1293,6 +1293,7 @@ class TextWidgetAnnotationElement extends WidgetAnnotationElement {
       element.disabled = this.data.readOnly;
       element.name = this.data.fieldName;
       element.tabIndex = 0;
+      element.title = this.data.dateFormat || this.data.timeFormat || "";
```
Comment (timvandermeij) [inline src/display/annotation_layer.js]: Should we perhaps do this instead to avoid setting the title attribute at all if we don't have a good tooltip value? I'm not sure if an empty `title` property is not displayed at all or if it would result in a visual tooltip without any contents.

```
if (this.data.dateFormat || this.data.timeFormat) {
  element.title = this.data.dateFormat || this.data.timeFormat;
}
```

**Review by timvandermeij — APPROVED** [review]
Looks good to me, with the questions addressed. Thanks!

File: src/core/annotation.js (hunk 1 above)
Comment (calixteman) [reply src/core/annotation.js:2786]: `gulp lint` formatted it like this.
