### PR TITLE
XFA - Implement aspect property on image element

### LINKED ISSUE #13634: Image not scaled proportionality
Attach (recommended) or Link to PDF file here:
https://guichet.public.lu/dam-assets/catalogue-formulaires/tva/tva-option-aic-pers-morales/tva-option-aic-pers-morale-DE.pdf

Configuration:
- Web browser and its version: Firefox Nightly 91.0a1 (2021-06-26) (64-bit)
- Operating system and its version: Windows 10.0.19043.1052
- PDF.js version: N/A

Steps to reproduce the problem:
1. enableXFA in Firefox Nightly
2. Open form

What is the expected behavior? (add screenshot)
Header image is scaled properly
image

What went wrong? (add screenshot)
Image is scaled to fit
image

### PR DESCRIPTION
**Pull request by calixteman**
- it aims to fix issue #13634;
  - move some img-related functions in test/drivers.js in order to have images in xfa reftests.

### CODE REVIEW

**Comment by calixteman** [comment]
A lot of xfa contains image so a lot of failure in reftests are expected.

/botio test

File: test/driver.js [hunk 1]
```diff
@@ -66,6 +66,51 @@ function writeSVG(svgElement, ctx, resolve, reject) {
...
+      xhr.responseType = "blob";
+      xhr.onload = function () {
+        const reader = new FileReader();
+        reader.onloadend = function () {
+          resolve(reader.result);
+        };
+        reader.readAsDataURL(xhr.response);
+      };
+      xhr.onerror = function (e) {
+        reject(new Error("Error fetching inline annotation image " + e));
```
Comment (Snuffleupagus) [inline test/driver.js:83]: Nit: Let's remove the "annotation " part, since the function is now used more generally.

File: test/driver.js [hunk 2]
```diff
@@ -66,6 +66,51 @@ function writeSVG(svgElement, ctx, resolve, reject) {
...
+    imagePromises.push(imagePromise);
+  }
+  return imagePromises;
+}
+
+async function resolveImages(node) {
+  const images = node.getElementsByTagName("img");
+  const imagePromises = inlineImages(images);
+
+  await Promise.all(imagePromises).then(function (data) {
```
Comment (marco-c) [inline test/driver.js:97]: Nit: since you are in an async function, you could avoid the `then' and so reduce the indentation level:
```
await Promise.all(imagePromises);
const loadedPromises = [];
...
```

File: test/driver.js [hunk 3]
```diff
@@ -233,25 +254,7 @@ var rasterizeAnnotationLayer = (function rasterizeAnnotationLayerClosure() {
...
-                  images[i].onerror = function (e) {
-                    rejectImage(new Error("Error loading image " + e));
-                  };
-                })
-              );
-            }
-            return loadedPromises;
-          });
-
+          await resolveImages(div);
```
Comment (marco-c) [inline test/driver.js:257]: `await resolveImages(div)` is a list of promises, shouldn't you await them via `await Promise.all(await resolveImages(div))`?

Comment (marco-c) [reply test/driver.js:257]: Or, you could add `await Promise.all(loadedPromises)` at the end of `resolveImages` and keep the code here as it is.

File: test/driver.js [hunk 4]
```diff
@@ -66,6 +66,51 @@ function writeSVG(svgElement, ctx, resolve, reject) {
   };
 }
 
+function inlineImages(images) {
+  const imagePromises = [];
+  for (let i = 0, ii = images.length; i < ii; i++) {
+    const imagePromise = new Promise(function (resolve, reject) {
```
Comment (marco-c) [inline test/driver.js:72]: Nit: 
```suggestion
    imagePromises.push(new Promise(function (resolve, reject) {
      ...
    }));
```
so you don't need the intermediate `imagePromise` variable.

File: test/driver.js (hunk 2 above)
Comment (Snuffleupagus) [reply test/driver.js:97]: You probably mean `const data = await Promise.all(imagePromises);` here, since otherwise this function would be broken :-)

File: test/driver.js (hunk 3 above)
Comment (Snuffleupagus) [reply test/driver.js:257]: The *second* suggestion is definitely the preferred way of doing things here!

---

Given that this patch only moves pre-existing code, it's actually quite interesting that old issue this hasn't caused any bugs (as far as we know).

File: test/driver.js (hunk 2 above)
Comment (marco-c) [reply test/driver.js:97]: Yep :)

File: test/driver.js (hunk 3 above)
Comment (calixteman) [reply test/driver.js:260]: I locally got some errors because tiff images are not rendered by neither firefox nor chrome which is expected.
So I disabled promise rejection for image failures for the xfa reftests.

**Review by marco-c — APPROVED** [review]
