### PR TITLE
Avoid to have a mail link with string having the format ddd@d.dddd

### LINKED ISSUE #20523: [Bug]: Incorrectly recognize numbers as email address
### Attach (recommended) or Link to PDF file

In trading statements, sometimes the amount can be marked as something like `262@0.302304` which means there are 262 shares each with an earning or cost of 0.302304. This, however, is recognized as an email address in PDF.js, making it hard to copy the numbers from the statement. This is not at all a valid email address. It should probably try to exclude such case in the autolinker.

### Web browser and its version

Firefox 146.0.1

### Operating system and its version

Ubuntu 25.10

### PDF.js version

5.4.396 (builtin Firefox)

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. open a PDF file with numbers like `262@0.302304`, for example: [test.pdf](https://github.com/user-attachments/files/24301079/test.pdf)
2. hover the pointer over the numbers

### What is the expected behavior?

The numbers should not be highlighted, and shouldn't be clickable.

### What went wrong?

The numbers are highlighted and, when clicked, opened as a mailto link.

### Link to a viewer

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by calixteman**
It fixes #20523.

### CODE REVIEW

File: web/autolinker.js [hunk 1]
```diff
@@ -150,7 +150,11 @@ class Autolinker {
         url.startsWith("https://")
       ) {
         raw = url;
-      } else if (URL.canParse(`http://${emailDomain}`)) {
+      } else if (
+        !emailDomain ||
+        URL.parse(`http://${emailDomain}`)?.hostname.toLowerCase() ===
+          emailDomain.toLowerCase()
```
Comment (upsuper) [inline web/autolinker.js]: Rather than checking `toLowerCase()` is equal across parsing, would it be better that we instead just check whether the parsed host name is IPv4 address? I mean something like
```js
/^\d+\.\d+\.\d+\.\d+$/.test(URL.parse(`http://${emailDomain}`)?.hostname)
```

According to [RFC 5321](https://www.rfc-editor.org/rfc/rfc5321.html), a IPv4 address can be used after `@` only in a bracketed address-literal form like `user@[8.8.8.8]`, and in address like `user@8.8.8.8`, the later part should be treated as domain name and go through DNS to resolve, which renders it practically unusable (there is no TLD consists of pure digits).

Also this new check in its current form would rule out IDN as domain. Is that intended and desirable? For example, `用户@例子.广告` is considered to be a valid [international email](https://en.wikipedia.org/wiki/International_email), but `URL.parse('http://例子.广告').hostname` would be `xn--fsqu00a.xn--4rr70v`. It's probably not accepted by the initial regex anyway, though.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you for improving this!
