### PR TITLE
Normalize fullwidth, halfwidth and circled chars when searching

### LINKED ISSUE #15690: FindController not supports FULLWIDTH LATIN CAPITAL
Attach (recommended) or Link to PDF file here:
[fullwidth.pdf](https://github.com/mozilla/pdf.js/files/10002370/fullwidth.pdf)

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version: 2.15.349
- Is a browser extension: no

Steps to reproduce the problem:
1. open this [link](https://mozilla.github.io/pdf.js/web/viewer.html)
2. open the attached `fullwidth.pdf` file
3. toggle find bar, and typing a halfwidth character `O` to see the find result.
4. replace the query string with fullwidth character `Ｏ` and see the result again.

What is the expected behavior? (add screenshot)

convert find bar "query string" and page "textContent" to halfwidth to matches the find results.
or and a option to "ignore fullwidth and/or halfwidth capital case"

截屏2022-11-14 19 27 10
(↑ matches)

 

What went wrong? (add screenshot)

can't matches fullwidth characters with halfwidth characters.

截屏2022-11-14 19 26 36
(↑ not match)
 
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

File: web/pdf_find_controller.js [hunk 1]
```diff
@@ -202,8 +208,22 @@ function normalize(text) {
       }
 
       if (p2) {
-        const hasTrailingDashEOL = p2.endsWith("\n");
-        const len = hasTrailingDashEOL ? p2.length - 2 : p2.length;
+        // Use the NFKC representation to normalize the char.
+        let replacement = CHARACTERS_TO_NORMALIZE[p2];
+        if (!replacement) {
+          replacement = CHARACTERS_TO_NORMALIZE[p2] = p2.normalize("NFKC");
+        }
```
Comment (Snuffleupagus) [inline web/pdf_find_controller.js:215]: By adding to the existing `CHARACTERS_TO_NORMALIZE` object you may end up *subtly changing* the logic if a PDF document contains some pages with, and some pages without, syllables since we create two different regular expressions in that case.

I'd suggest adding e.g.
```javascript
const NFKC_CHARS_TO_NORMALIZE = {};
```
after line https://github.com/mozilla/pdf.js/blob/3078e2c1d9c3d1e6bf79709f2680dfca6b35cc9d/web/pdf_find_controller.js#L48
and then also simplify this code as follows:
```suggestion
        const replacement = NFKC_CHARS_TO_NORMALIZE[p2] ||= p2.normalize("NFKC");
```

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]

**Review by Snuffleupagus — APPROVED** [review]
r=me, with passing unit/integration tests; thank you!
