### PR TITLE
Flush the current chunk when the font changed because of a restore op (issue #14755)

### LINKED ISSUE #14755: getTextContent doesn't always return the right fontRef
Attach (recommended) or Link to PDF file here: [test8.pdf](https://github.com/mozilla/pdf.js/files/8428431/test8.pdf)

Configuration:
- Web browser and its version: Chrome Version 98.0.4758.102 (64 bits)
- Operating system and its version: Windows 10 (64bits)
- PDF.js version: v2.13.216
- Is a browser extension: No

**Steps to reproduce the problem:**
1. getTextContent on the only page of the document
2. check the fontRef of the item that contains "ou une liturgie"

```javascript
let textContent = await page.getTextContent();
textContent.items.forEach((item) => {
  if (item.str.includes('ou une liturgie')) console.log(item);
});
```

**What is the expected behavior?**
On this particular example when using the chrome debugger I can see the fontRef used to render the glyphs of (part of) this item is `d_d0_f3`

**What went wrong?**
The item that get logged out has a fontRef `g_d0_f4`.

I think I isolated the problem to this particular pattern of OPS: (ignoring irrelevant OPS here)
```
- setFont d_d0_f3
- [...do stuff, showText...]
- save
- setFont d_d0_f4
- showText ") "
- restore
- showText "ou une liturgie de clairvoyance (par exemple"
```
This should return two different items with different fonts in my opinion (or is this PDF file broken in some way ? It renders fine though). What I get is the item with the str value of `) ou une liturgie de clairvoyance (par exemple` and fontRef `g_d0_f4`.

---

I found a fix, but I'm not sure it's very elegant the way I did it.
In the `function buildTextContentItem` in the file [`src/core/evaluator.js:2633`](https://github.com/mozilla/pdf.js/blob/master/src/core/evaluator.js#L2633) I added at the top : 
```javascript
if (textContentItem.initialized && textContentItem.fontName != textState.font.loadedName) {
  flushTextContentItem();
}
```
With this, I get to separate items, each with it's own correct fontRef.

I think handling the `restore` case in the switch ([same file, line 2861](https://github.com/mozilla/pdf.js/blob/master/src/core/evaluator.js#L2861)) would be a lot cleaner but I don't know enough of the specifics of this library to be sure. Is always trying to `flushTextContentItem()` when reading a `restore` OPS valid ?

Anyway, thanks a lot for your time !

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

File: test/unit/api_spec.js [hunk 1]
```diff
@@ -2682,6 +2682,44 @@ Caron Broadcasting, Inc., an Ohio corporation (“Lessee”).`)
...
+      });
+      expect(items).toEqual([
+        jasmine.objectContaining({
+          str: "ABC",
+          dir: "ltr",
+          width: 20.56,
+          height: 10,
+          transform: [10, 0, 0, 10, 100, 100],
+          hasEOL: false,
+        }),
```
Comment (Snuffleupagus) [inline test/unit/api_spec.js:2700]: Here, and below, I don't *think* that you need to use `jasmine.objectContaining` if you're comparing against a "complete" object. Hence the following ought to work as well:
```suggestion
        {
          str: "ABC",
          dir: "ltr",
          width: 20.56,
          height: 10,
          transform: [10, 0, 0, 10, 100, 100],
          hasEOL: false,
        },
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you!
