### PR TITLE
Fix text selection with hdpi screens (#15229)

### LINKED ISSUE #15229: Text selection is not correct on hdpi
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox nightly
- Operating system and its version: Windows 11

Steps to reproduce the problem:
1. Open tracemonkey.pdf 
2. Zoom at 80%

I get:
image

My screen resolution is 3840x2160 and the global scale is 150%.

If I change  the scale setting in `System > Display` to 100%, the selection is correct:
image

The text is measured here:
https://github.com/mozilla/pdf.js/blob/8ebd2d3dfd0c32086314014f8006c91913c2f746/src/display/text_layer.js#L695

and it returns the same value whatever the screen I use is.

So I think we must take into account the `window.devicePixelRatio` value when computing the text width.

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

File: src/display/text_layer.js [hunk 1]
```diff
@@ -166,6 +166,8 @@ function appendText(task, geom, styles, ctx) {
   textDiv.style.fontSize = `${fontHeight}px`;
   textDiv.style.fontFamily = style.fontFamily;
 
+  textDivProperties.fontSize = fontHeight;
```
Comment (Snuffleupagus) [inline src/display/text_layer.js:169]: Please add a default value for the `fontSize`-property in the object definitions above, see https://github.com/mozilla/pdf.js/blob/8ebd2d3dfd0c32086314014f8006c91913c2f746/src/display/text_layer.js#L123-L141

File: src/display/text_layer.js [hunk 2]
```diff
@@ -595,6 +597,7 @@ class TextLayerRenderTask {
     this._capability = createPromiseCapability();
     this._renderTimer = null;
     this._bounds = [];
+    this._devicePixelRatio = window.devicePixelRatio;
```
Comment (Snuffleupagus) [inline src/display/text_layer.js:600]: To prevent issues in non-browser environments, please change this to:
```suggestion
    this._devicePixelRatio = globalThis.devicePixelRatio || 1;
```

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]
Given that we have a couple of other `measureText`-usages in the code-base, are any of those similarly affected?
If so that can, and maybe even should, be handled in follow-up patches.

Also, I'm assuming that there's no particularly good way to test this?

**Comment by calixteman** [comment]
> Given that we have a couple of other `measureText`-usages in the code-base, are any of those similarly affected? If so that can, and maybe even should, be handled in follow-up patches.
> 

Yep, I'm in favor of follow-up patches.

> Also, I'm assuming that there's no particularly good way to test this?

I have no idea on how to do that.
Here's a screenshot from my HDMI screen (pixelRatio == 1.5):
image

For people having a pixel ration equal to 1, it should be impactless and for the other it cannot be worst than it is right now.
I tested with different pixelRatio settings in the Windows parameters stuff (System > Display > Scale & Layout > Scale), and everything is ok.
