### PR TITLE
[Annotation] Fix printing/saving for annotations containing some non-ascii chars and with no fonts to handle them (bug 1666824)

### LINKED ISSUE #12264: Printing/saving issue with chars in textfield which aren't in the default font
In order to render these characters we need to have a font to render them.
So the first thing is to find such a font and in order to save the data we need to embed it (with Adobe reader on mac the font is embedded but it isn't with pdfium under linux), it means that we need to get a ttf file or an otf one.
I looked at google font server but in order to get a ttf I need to cheat with the user agent and then I get a cors issue because of that.
Anyway if we can get a ttf file, it seems possible (after reading src/core/fonts.js) to subset it to get only the used glyphs and then it'd avoid to embed the entire ttf file.
If we can't get a font file then for printing we could probably cheat in creating a "fake" font and for saving we could not embed the font (which is a pity).
Any thoughts ?

### PR DESCRIPTION
**Pull request by calixteman**
- For text fields
  * when printing, we generate a fake font which contains some widths computed thanks to
   an OffscreenCanvas and its method measureText.
   In order to avoid to have to layout the glyphs ourselves, we just render all of them
   in one call in the showText method in using the system sans-serif/monospace fonts.
  * when saving, we continue to create the appearance streams if the fonts contain the char
   but when a char is missing, we just set, in the AcroForm dict, the flag /NeedAppearances
   to true and remove the appearance stream. This way, we let the different readers handle
   the rendering of the strings.
- For FreeText annotations
   * when printing, we use the same trick as for text fields.
   * there is no need to save an appearance since Acrobat is able to infer one from the
    Content entry.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
Given the sheer amount of code/complexity here, this will take me a little time to get around to. Anyway, this also doesn't seem like something we want to "rush" to land just before the upcoming `3.0` release.

**Comment by calixteman** [comment]
> Given the sheer amount of code/complexity here, this will take me a little time to get around to. Anyway, this also doesn't seem like something we want to "rush" to land just before the upcoming `3.0` release.

Yep, no worries.
The original bug is 2 years old so it can wait for few days/weeks. Take the time you need to review it.

File: src/display/canvas.js [hunk 1]
```diff
@@ -2275,6 +2275,21 @@ class CanvasGraphics {
 
     ctx.lineWidth = lineWidth;
 
+    if (glyphsLength && glyphs[0].isInInvalidPDFjsFont) {
```
Comment (Snuffleupagus) [inline src/display/canvas.js:2278]: Given that the property in question is a `Font`-instance one, rather than one that depends e.g. the `charCode`, this shouldn't be added to each and every `Glyph`-instance like this.
Hence, please just export `isInvalidPDFjsFont` the same way that we do for all other font-properties (see e.g. `exportData` in `src/core/fonts.js`) and then do:
```suggestion
    if (font.isInvalidPDFjsFont) {
```

Note that I'm also suggesting an ever so slightly shorter name for the new property.

File: src/core/default_appearance.js [hunk 2]
```diff
@@ -102,4 +116,488 @@ function createDefaultAppearance({ fontSize, fontName, fontColor }) {
   )}`;
 }
 
-export { createDefaultAppearance, getPdfColor, parseDefaultAppearance };
+function canUseFakeFont() {
+  return FeatureTest.isOffscreenCanvasSupported;
```
Comment (Snuffleupagus) [inline src/core/default_appearance.js:120]: This must take the newly added `isOffscreenCanvasSupported` API-option into account as well, please note how this is done in e.g. `src/core/image.js` (was introduced in PR #15542).

**Review by Snuffleupagus — COMMENTED** [review]
*Just a couple comments, based on things I've noticed from a very brief skim.*

File: src/core/annotation.js [hunk 3]
```diff
@@ -1815,86 +1818,115 @@ class WidgetAnnotation extends Annotation {
...
-      0,
-      this.data.rect[2] - this.data.rect[0],
-      this.data.rect[3] - this.data.rect[1],
-    ];
+    const dict = new Dict(xref);
+    originalDict.forEachRaw((key, val) => {
+      if (key !== "AP") {
+        dict.set(key, val);
+      }
+    });
```
Comment (Snuffleupagus) [inline src/core/annotation.js:1840]: Do we really need to add a new method in the `Dict`-class for a single call-site, or could we perhaps just re-factor this code a little bit?
```suggestion
    for (const key of originalDict.getKeys()) {
      if (key !== "AP") {
        dict.set(key, originalDict.getRaw(key));
      }
    }
```

File: src/shared/util.js [hunk 4]
```diff
@@ -1053,6 +1055,16 @@ function isAscii(str) {
   return /^[\x00-\x7F]*$/.test(str);
 }
 
+function fromUTF16(str) {
```
Comment (Snuffleupagus) [inline src/shared/util.js:1058]: *This applies to the new helper functions below as well.*

Do we need this on both threads? If not, can we perhaps move it to `src/core/core_utils.js` instead?

**Review by Snuffleupagus — COMMENTED** [review]
Would it be at all feasible to split this into a couple of separate commits?
I'm having a really though time trying to review this as-is, given the sheer size and complexity of the changes, and I fear that I may end up overlooking (or just not understanding) many things.

**Comment by calixteman** [comment]
> Would it be at all feasible to split this into a couple of separate commits? I'm having a really though time trying to review this as-is, given the sheer size and complexity of the changes, and I fear that I may end up overlooking (or just not understanding) many things.

I discovered `/NeedAppearances` few days ago and I think I can use it here in order to avoid to have to render something when saving and it'll help to reduce the size of this patch.

File: src/core/annotation.js [hunk 5]
```diff
@@ -1824,89 +1829,115 @@ class WidgetAnnotation extends Annotation {
...
-      evaluator,
-      task,
-      annotationStorage
-    );
-    if (appearance === null) {
-      return null;
+    let appearance = null;
+    if (!this._needAppearances) {
+      // No need to create an appearance: the pdf has the flag /NeedAppearances
+      // which means that it's up to the reader to produce an appearance.
```
Comment (Snuffleupagus) [inline src/core/annotation.js:1835]: Doesn't the condition and comment contradict each other, since `this._needAppearances === false` is the default value when the /NeedAppearances flag *does not* exist?

File: src/core/xref.js [hunk 6]
```diff
@@ -42,18 +42,32 @@ class XRef {
...
     this.stats = new DocStats(pdfManager.msgHandler);
-    this._newRefNum = null;
+    this._newRefNumForPrinting = null;
+    this._newRefNumForSaving = null;
   }
 
-  getNewRef() {
-    if (this._newRefNum === null) {
-      this._newRefNum = this.entries.length || 1;
+  getNewRefForPrinting() {
```
Comment (Snuffleupagus) [inline src/core/xref.js:49]: Do we actually need two *slightly different* ways of generating new Refs, since that feels somewhat error-prone?
In any case, isn't there potentially a risk that if the circumstances are "just right" these methods could return the same Ref and thus break the document?

File: src/core/document.js [hunk 7]
```diff
@@ -390,8 +390,9 @@ class Page {
       "XObject",
     ]);
 
+    const { xref } = this;
```
Comment (Snuffleupagus) [inline src/core/document.js:393]: The changes in this file looks unrelated, and can be reverted as far as I can tell.

File: src/core/annotation.js [hunk 8]
```diff
@@ -3326,6 +3484,28 @@ class FreeTextAnnotation extends MarkupAnnotation {
...
 
     this.data.annotationType = AnnotationType.FREETEXT;
+    this.setDefaultAppearance(parameters);
+    if (
+      !this.appearance &&
+      ((parameters.pdfManager &&
+        parameters.pdfManager.evaluatorOptions.isOffscreenCanvasSupported) ||
+        parameters.isOffscreenCanvasSupported) &&
+      canUseFakeFont()
+    ) {
```
[the remark this answers is not in the document]
Comment (calixteman) [reply src/core/annotation.js:3494]: In general, a FreeText annotation can have no appearance (normally it's required to have a DA but irl some don't have), in such a case Acrobat, Foxit and Preview render it based on its content.
So when a user save an annotation, we can just skip the generation of an appearance stream, but it means that we must be able to render it again when the pdf is opened (after a saving).
FYI, in Edge, when saving a newly added annotation with some non-latin chars, no DA is generated.
So finally, this patch helps to partially fix https://github.com/mozilla/pdf.js/issues/6810.

File: src/core/writer.js [hunk 9]
```diff
@@ -150,52 +150,68 @@ function writeXFADataForAcroform(str, newRefs) {
...
+  xfaData,
+  xfaDatasetsRef,
+  hasXfaDatasetsEntry,
+  acroFormRef,
+  acroForm,
+  newRefs,
+  xref,
+}) {
+  if (xref === null) {
+    return;
```
Comment (Snuffleupagus) [inline src/core/writer.js:214]: I know that you're only moving existing code around, but can this actually happen in practice?

File: src/core/annotation.js [hunk 10]
```diff
@@ -3326,6 +3484,28 @@ class FreeTextAnnotation extends MarkupAnnotation {
     super(parameters);
 
     this.data.annotationType = AnnotationType.FREETEXT;
+    this.setDefaultAppearance(parameters);
+    if (
+      !this.appearance &&
+      ((parameters.pdfManager &&
+        parameters.pdfManager.evaluatorOptions.isOffscreenCanvasSupported) ||
```
Comment (Snuffleupagus) [inline src/core/annotation.js:3491]: Should we perhaps just add the following
```javascript
isOffscreenCanvasSupported:
  pdfManager.evaluatorOptions.isOffscreenCanvasSupported
```
to this structure https://github.com/mozilla/pdf.js/blob/7e5008f0ff013cc2b8f2af10db7f007e7cafe0de/src/core/annotation.js#L132-L146
so that we can remove these two lines here?

**Review by Snuffleupagus — COMMENTED** [review]
I've gone through `src/core/default_appearance.js` and despite the amount of code it actually looked reasonably straightforward :-)

However I still need to carefully go through the Annotation-code, which is the part of this patch that feels the most complicated/complex to me.

File: src/core/xref.js (hunk 6 above)
Comment (calixteman) [reply src/core/xref.js:49]: When saving, we use some new ref only to write them but we never consume them: I mean we never get the object associated with them.
Before the patch, we were only using some new refs in the saving context.
Now, the situation is a bit different:
 - when we've a `FreeText` with no appearance, we create a `FakeUnicodeFont` which uses some references and these one must be persistent;
 - when printing we can create some `FakeUnicodeFont` which don't have to live once the printing is done, but the printing is done async, so must take to have persistent refs at least during all the printing session;
 - when saving, it's the same as before: so the refs don't have to be persistent after the saving is done.

When saving we just have to add some new ref after the last existing ref (in the pdf) whatever the number of FreeText annotations without AP or the number of time the document has been printed: it's why I think we must have something specific for saving.

In the current state of this patch, nothing is done to cleanup the refs added during the printing: it's a pity we should do something, but we must take care to not cleanup the refs added for the FreeText without AP.

Anyway, I'm not super happy with the new method names, and I agree that the implementation is not ideal.
Would you have any suggestions ?

Comment (Snuffleupagus) [reply src/core/xref.js:49]: Good overview, thank you!

Perhaps better method names would indeed be helpful as a start, so how about something like:
 - `getNewPermanentRef` - for use with printing.
 - `getNewTemporaryRef` - for use with saving.
 - `resetNewTemporaryRef`

File: src/core/document.js [hunk 11]
```diff
@@ -515,6 +515,7 @@ class Page {
           /* lastChunk = */ true,
           /* separateAnnots = */ { form, canvas }
         );
+
```
Comment (Snuffleupagus) [inline src/core/document.js:518]: Unrelated change, please revert.

File: src/core/fonts.js [hunk 12]
```diff
@@ -922,12 +923,15 @@ class Font {
...
     this.type = type;
     this.subtype = subtype;
+    this.isInvalidPDFjsFont = name.startsWith("InvalidPDFjsFont");
 
     let fallbackName = "sans-serif";
-    if (this.isMonospace) {
-      fallbackName = "monospace";
-    } else if (this.isSerifFont) {
-      fallbackName = "serif";
+    if (!this.isInvalidPDFjsFont) {
```
Comment (Snuffleupagus) [inline src/core/fonts.js:929]: Why can the `fallbackName` not take any other value than "sans-serif" when a FakeFont is being used?
If this is indeed necessary, a comment would probably not hurt :-)

File: test/unit/test_utils.js [hunk 13]
```diff
@@ -116,6 +126,10 @@ class XRefMock {
   async fetchIfRefAsync(obj) {
     return this.fetchIfRef(obj);
   }
+
+  addEntry(ref, obj) {
+    this._map[ref.toString()] = obj;
+  }
```
Comment (Snuffleupagus) [inline test/unit/test_utils.js:132]: This "full" `XRef` class no longer has such a method, so this one should probably be removed as well?

File: test/unit/test_utils.js [hunk 14]
```diff
@@ -87,14 +88,23 @@ class XRefMock {
...
 
-  resetNewRef() {
+  getNewTemporaryRef() {
+    if (this._newTemporaryRefNum === null) {
+      this._newTemporaryRefNum = Object.keys(this._map).length || 1;
+    }
+    return Ref.get(this._newTemporaryRefNum++, 0);
+  }
+
+  resetNewRefForSaving() {
```
Comment (Snuffleupagus) [inline test/unit/test_utils.js:107]: This method name is no longer correct...

File: test/unit/test_utils.js [hunk 15]
```diff
@@ -87,14 +88,23 @@ class XRefMock {
...
     this.newRef = null;
```
Comment (Snuffleupagus) [inline test/unit/test_utils.js:108]: ... and neither is this property name.

File: src/core/worker.js [hunk 16]
```diff
@@ -661,28 +664,32 @@ class WorkerMessageHandler {
...
               info: infoObj,
               fileIds: xref.trailer.get("ID") || null,
               startXRef,
               filename,
             };
           }
-          xref.resetNewRef();
 
-          return incrementalUpdate({
+          const data = incrementalUpdate({
```
Comment (Snuffleupagus) [inline src/core/worker.js:676]: Can this function call ever throw, because if so we're not resetting the temporary Refs which could potentially cause issues later on?
Would it make sense to do something along these lines instead?
```suggestion
          try {
            const data = incrementalUpdate({ ... });
            xref.resetNewTemporaryRef();
            return data;
          } catch (reason) {
            xref.resetNewTemporaryRef();
            throw reason;
          }
```

File: test/driver.js [hunk 17]
```diff
@@ -479,7 +479,22 @@ class Driver {
           enableXfa: task.enableXfa,
           styleElement: xfaStyleElement,
         });
-        loadingTask.promise.then(
+        let promise = loadingTask.promise;
+
+        if (task.save && task.annotationStorage) {
+          promise = loadingTask.promise.then(async doc => {
```
Comment (Snuffleupagus) [inline test/driver.js:485]: Is it ever expected that `save` is set but an `annotationStorage` isn't provided in the manifest?
If not, we should probably make that case an error:
```suggestion
        if (task.save) {
          if (!task.annotationStorage) {
            promise = Promise.reject("Missing `annotationStorage` entry.");
          } else {
            promise = loadingTask.promise.then(async doc => {
              ...
```

File: test/unit/writer_spec.js [hunk 18]
```diff
@@ -194,6 +194,7 @@ describe("Writer", function () {
         "\n" +
         "789 0 obj\n" +
         "<< /XFA [(preamble) 123 0 R (datasets) 101112 0 R (postamble) 456 0 R]>>\n" +
+        "endobj\n" +
```
Comment (Snuffleupagus) [inline test/unit/writer_spec.js:197]: Were we previously, in some cases, potentially generating invalid PDF documents when saving XFA forms or was this just an artifact of the dummy-data used in the unit-test?

**Review by Snuffleupagus — COMMENTED** [review]
A little bit further; I trying to find time to look at the `src/core/annotation.js` changes as soon as possible.

File: src/core/annotation.js [hunk 19]
```diff
@@ -1477,6 +1504,7 @@ class MarkupAnnotation extends Annotation {
     return new this.prototype.constructor({
       dict: annotationDict,
       xref,
+      isOffscreenCanvasSupported: params && params.isOffscreenCanvasSupported,
```
Comment (Snuffleupagus) [inline src/core/annotation.js:1507]: Could we perhaps just change https://github.com/mozilla/pdf.js/blob/f7449563ef8722df30c2988fe571236ab9eb89f9/src/core/annotation.js#L316
to
```javascript
InkAnnotation.createNewPrintAnnotation(xref, annotation, {
  isOffscreenCanvasSupported,
});
```
such that we can assume that `params` is always defined and thus do the following here?
```suggestion
      isOffscreenCanvasSupported: params.isOffscreenCanvasSupported,
```

File: src/core/annotation.js [hunk 20]
```diff
@@ -1824,89 +1835,116 @@ class WidgetAnnotation extends Annotation {
...
 
-    const appearanceDict = new Dict(xref);
-    appearanceDict.set("Length", appearance.length);
-    appearanceDict.set("Subtype", Name.get("Form"));
-    appearanceDict.set("Resources", this._getSaveFieldResources(xref));
-    appearanceDict.set("BBox", bbox);
+    const encrypt = xref.encrypt;
+    const originalTransform = !encrypt
+      ? null
+      : encrypt.createCipherTransform(this.ref.num, this.ref.gen);
```
Comment (Snuffleupagus) [inline src/core/annotation.js:1891]: Maybe just invert the condition?
```suggestion
    const originalTransform = encrypt
      ? encrypt.createCipherTransform(this.ref.num, this.ref.gen);
      : null;
```

File: src/core/annotation.js [hunk 21]
```diff
@@ -1961,8 +1999,12 @@ class WidgetAnnotation extends Annotation {
     }
 
     let lineCount = -1;
+    let lines;
     if (this.data.multiLine) {
-      lineCount = value.split(/\r\n|\r|\n/).length;
+      lines = value.split(/\r\n|\r|\n/).map(line => line.normalize("NFKC"));
```
Comment (Snuffleupagus) [inline src/core/annotation.js:2004]: Here, and below, we could probably use the slightly shorter `/\r\n?|\n/` regular expression instead (as we do elsewhere in the code-base).

Also, can you please add a brief comment explaining what that particular normalization mode does and why it was chosen here?

File: src/core/annotation.js [hunk 22]
```diff
@@ -1824,89 +1835,116 @@ class WidgetAnnotation extends Annotation {
...
+      if (rotationMatrix !== IDENTITY_MATRIX) {
+        // The matrix isn't the identity one.
+        appearanceDict.set("Matrix", rotationMatrix);
+      }
+
+      writeObject(newRef, appearanceStream, buffer, newTransform);
+
+      changes.push(
+        // data for the new AP
+        { ref: newRef, data: buffer.join(""), xfa: null }
```
Comment (Snuffleupagus) [inline src/core/annotation.js:1934]: Do we want to include the `needAppearances` parameter here as well, for consistency?

File: src/core/annotation.js [hunk 23]
```diff
@@ -1985,23 +2027,101 @@ class WidgetAnnotation extends Annotation {
...
+      const encodedString = font.encodeString(line);
+      if (encodedString.length > 1) {
+        encodingError = true;
+      }
+      encodedLines.push(encodedString.join(""));
+    }
+
+    if (encodingError && intent & RenderingIntentFlag.SAVE) {
+      // We don't have a way to render the field, so we just rely on the
+      // /NeedAppearances trick to let the different sofware render correctly
```
Comment (Snuffleupagus) [inline src/core/annotation.js:2050]: Generally speaking, thanks a lot for adding these comments since that definitely helps!

Here, and below, a few spelling/grammar nits:
```suggestion
      // /NeedAppearances trick to let the different software correctly render
```

File: src/core/annotation.js [hunk 24]
```diff
@@ -1985,23 +2027,101 @@ class WidgetAnnotation extends Annotation {
...
+      // this pdf.
+      return { needAppearances: true };
+    }
+
+    // We check that the font is able to encode the string.
+    if (encodingError && this._isOffscreenCanvasSupported) {
+      // If it can't then we fallback on fake unicode font (mapped on sans-serif
```
Comment (Snuffleupagus) [inline src/core/annotation.js:2057]:
```suggestion
      // If it can't then we fallback on fake unicode font (mapped to sans-serif
```

File: src/core/annotation.js [hunk 25]
```diff
@@ -1985,23 +2027,101 @@ class WidgetAnnotation extends Annotation {
...
+      // for the rendering).
+      // It means that a printed form can be rendered differently (it depends on
+      // the sans-serif font) but at leat we've something to render.
```
Comment (Snuffleupagus) [inline src/core/annotation.js:2060]:
```suggestion
      // the sans-serif font) but at least we've something to render.
```

File: src/core/annotation.js [hunk 26]
```diff
@@ -1985,23 +2027,101 @@ class WidgetAnnotation extends Annotation {
...
+      // In an ideal world the associated font should handle correctly the
```
Comment (Snuffleupagus) [inline src/core/annotation.js:2061]:
```suggestion
      // In an ideal world the associated font should correctly handle the
```

File: src/core/annotation.js [hunk 27]
```diff
@@ -1985,23 +2027,101 @@ class WidgetAnnotation extends Annotation {
...
+        { fontName, fontSize: 0 },
+        resources
+      );
+
+      for (let i = 0, ii = encodedLines.length; i < ii; i++) {
+        encodedLines[i] = stringToUTF16String(lines[i]);
+      }
+
+      const savedDefaultAppearance = Object.assign(
+        {},
```
Comment (Snuffleupagus) [inline src/core/annotation.js:2092]: To avoid problems in custom implementation, where JS primitives have been modified, we usually do:
```suggestion
        Object.create(null),
```

File: src/core/annotation.js [hunk 28]
```diff
@@ -1985,23 +2027,101 @@ class WidgetAnnotation extends Annotation {
...
+      const newFont = resources.getRaw("Font");
+
+      if (this._fieldResources.mergedResources.has("Font")) {
+        const oldFont = this._fieldResources.mergedResources.get("Font");
+        for (const key of newFont.getKeys()) {
+          oldFont.set(key, newFont.getRaw(key));
+        }
+      } else {
+        this._fieldResources.mergedResources.set("Font", newFont);
+      }
```
Comment (Snuffleupagus) [inline src/core/annotation.js:2077]: Would this perhaps be generally safer, and more future-proof, if we used the `Dict.merge` functionality instead?
```suggestion
      this._fieldResources.mergedResources = Dict.merge({
        xref: evaluator.xref,
        dictArray: [this._fieldResources.mergedResources, resources],
        mergeSubDicts: true,
      });
```

**Review by Snuffleupagus — COMMENTED** [review]
I've gone through about half of the `src/core/annotation.js` changes now, and it seems reasonable so far :-)
When this round of comments are addressed, let's run all tests to see where we're at!

File: src/core/annotation.js (hunk 28 above)
Comment (calixteman) [reply src/core/annotation.js:2077]: My first version was using it but it wasn't working correctly with `issue12233.pdf`.
If you enter `مرحبا بالعالم` in `Address 1` field and then print the pdf, you'll just get some garbage.
It's because the font is a ref and:
https://github.com/mozilla/pdf.js/blob/master/src/core/primitives.js#L267
Maybe we could fix that and use `merge` but I didn't want to add more complexity to this patch and spend too much time on something not directly related, so I think we could address that in an other patch.

File: src/core/annotation.js [hunk 29]
```diff
@@ -3326,6 +3508,22 @@ class FreeTextAnnotation extends MarkupAnnotation {
...
+      const fontData = this.data.defaultAppearanceData;
+      this.appearance = fakeUnicodeFont.createAppearance(
+        this._contents.str,
+        this.rectangle,
+        this.rotation,
+        fontData.fontSize || 10,
+        fontData.fontColor
+      );
+      this._streams.push(this.appearance, FakeUnicodeFont.toUnicodeStream);
+    }
```
Comment (Snuffleupagus) [inline src/core/annotation.js:3526]: Would it make sense to warn when OffscreenCanvas isn't available, to make it clear why it's potentially not working correctly?
```suggestion
    } else if (!this._isOffscreenCanvasSupported) {
      warn("FreeTextAnnotation: OffscreenCanvas is not supported, annotation may not render correctly.");
    }
```

**Comment by calixteman** [comment]
The unit test failures are due a missing `evaluatorOptions` in the mock: I'm fixing.

**Comment by calixteman** [comment]
The text baseline shift and font size change are because before the top padding wasn't taken into account to compute the total line height.
About `160F-2019.pdf`, I printed into PDF from Firefox and Acrobat and then open them (I took this screenshot at 400%):
image

The position is correct and the font size is slightly different.
About `issue14052.pdf`, the problem different: right now we only use the field height to guess the font size, so from this point of view, it's an improvement since the text better fits into the field.
I've a WIP, locally to take into consideration the width when the field is auto-sized.

**Comment by Snuffleupagus** [comment]
> The text baseline shift and font size change are because before the top padding wasn't taken into account to compute the total line height.

*Possibly a stupid question, but:* In that case, should we perhaps *reduce* the defaultPadding to offset some of this effect?

https://github.com/mozilla/pdf.js/blob/f7449563ef8722df30c2988fe571236ab9eb89f9/src/core/annotation.js#L1968

**Comment by calixteman** [comment]
Arff... I forgot to fix unit tests.

**Review by Snuffleupagus — APPROVED** [review]
