### PR TITLE
Sanitize the glyph bounding box

### LINKED ISSUE #15816: Some Text is not rendering and printing properly!
@Snuffleupagus

There is still a problem with the issue you closed, so I register the issue again.
[Some Text is not rendering properly! #15813](https://github.com/mozilla/pdf.js/issues/15813)

As you mentioned, there seems to be no problem if the PDF opens at https://mozilla.github.io/pdf.js/web/viewer.html.

However, when printing the PDF, the texts aren't displayed properly.
The error is made when running pdfTest7.html that I made.
And the console log is the same one!

console log :
pdf.js:4732 OTS parsing error: glyf: Failed to parse table
Warning: Failed to load font 'g_d0_f6': 'SyntaxError: Invalid font data in ArrayBuffer.'.

I think It's not a good idea to say that there's nothing wrong with just opening the PDF on https://mozilla.github.io/pdf.js/web/viewer.html.
Moreover, the error occurred when printing on that URL.

Also, if there is the error opening PDF in the example HTML(pdfTest7.html) (https://mozilla.github.io/pdf.js/examples/), we had better correct the error for PDFJS library.

Please check the issue I asked correctly!

I would appreciate your advice on how to solve it.

### LINKED ISSUE #16300: OTS parsing error: glyf: Failed to parse table. Failed to load font 'g_d1_f3': 'SyntaxError: Invalid font data in ArrayBuffer.'.
Attach (recommended) or Link to PDF file here:

[PDF TEST.pdf](https://github.com/mozilla/pdf.js/files/11242244/PDF.TEST.pdf)

Configuration:
- Web browser and its version:  Chrome Version 112.0.5615.49 (Official Build) (x86_64)
- Operating system and its version: MacOs Monterey 12.6.4
- PDF.js version: https://mozilla.github.io/pdf.js/web/viewer.html
- Is a browser extension: No

Steps to reproduce the problem:
1.  Go to https://mozilla.github.io/pdf.js/web/viewer.html
2. Load the pdf

What is the expected behavior?
Load without warning

What went wrong? (add screenshot)
image

```OTS parsing error: glyf: Failed to parse table
Warning: Failed to load font 'g_d1_f3': 'SyntaxError: Invalid font data in ArrayBuffer.'.
```

Link to a viewer 
https://mozilla.github.io/pdf.js/web/viewer.html

### PR DESCRIPTION
**Pull request by calixteman**
- if the contours count is lower than -1, the glyph is really likely wrong so just remove it from the font;
- if a contour has the repeat flag then repeats count mustn't be 0.

### CODE REVIEW

File: src/core/fonts.js [hunk 1]
```diff
@@ -2096,6 +2153,11 @@ class Font {
         break;
       }
 
+      const xMin = signedInt16(tables.head.data[36], tables.head.data[37]);
+      const yMin = signedInt16(tables.head.data[38], tables.head.data[39]);
+      const xMax = signedInt16(tables.head.data[40], tables.head.data[41]);
+      const yMax = signedInt16(tables.head.data[42], tables.head.data[43]);
+
```
Comment (Snuffleupagus) [inline src/core/fonts.js:2160]: Shouldn't this be written as follows, since otherwise you're not actually using the `head`-parameter that you're now passing to this function?
```suggestion
      const xMin = signedInt16(head.data[36], head.data[37]);
      const yMin = signedInt16(head.data[38], head.data[39]);
      const xMax = signedInt16(head.data[40], head.data[41]);
      const yMax = signedInt16(head.data[42], head.data[43]);

```

**Review by Snuffleupagus — COMMENTED** [review]
Let's run all tests *before* I look at this in detail, since changes to this part of the code-base carry a larger than normal risk of breaking *something* :-)

File: src/core/fonts.js [hunk 2]
```diff
@@ -1853,22 +1853,74 @@ class Font {
...
       const glyphProfile = {
         length: 0,
         sizeOfInstructions: 0,
       };
-      if (sourceEnd - sourceStart <= 12) {
-        // glyph with data less than 12 is invalid one
+      if (
+        sourceStart < 0 ||
+        sourceStart >= source.length ||
+        sourceEnd >= source.length + 1 ||
```
Comment (Snuffleupagus) [inline src/core/fonts.js:1869]: Couldn't this be a tiny bit shorter, if written follows?
```suggestion
        sourceEnd > source.length ||
```

**Review by Snuffleupagus — COMMENTED** [review]
How does the slight horizontal glyph-movement in `artofwar` compare with e.g. Adobe Reader?

**Comment by calixteman** [comment]
> How does the slight horizontal glyph-movement in `artofwar` compare with e.g. Adobe Reader?

Finally the OTS was just complaining about the wrong bbox for a glyph but it doesn't care about having glyph bboxes which aren't included in the font bbox.

**Comment by Snuffleupagus** [comment]
Testing this patch locally, I noticed that there's still some problem with the PDF document from issue #16300 since the following *warnings* are logged in the console:
```
downloadable font: glyf: Number of contour points exceeds maxp maxPoints, adjusting limit. (font-family: "g_d4_f3" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
downloadable font: glyf: Extra bytes at end of the glyph: 74 (font-family: "g_d4_f3" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
```

**Comment by calixteman** [comment]
> Testing this patch locally, I noticed that there's still some problem with the PDF document from issue #16300 since the following _warnings_ are logged in the console:
> 
> ```
> downloadable font: glyf: Number of contour points exceeds maxp maxPoints, adjusting limit. (font-family: "g_d4_f3" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
> downloadable font: glyf: Extra bytes at end of the glyph: 74 (font-family: "g_d4_f3" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
> ```

I noticed these warnings too but they're just warnings... so they don't avoid to load the font.
The glyph 0 has a wrong bbox (x/yMin/Max aren't correctly sorted), once the bbox is fixed we have this `extra bytes at end ...` which is due to the presence of the flag REPEAT but the repeats count is 0... and then we've extra data likely because the repeats count is wrong (but I don't really feel like fixing it). And the maxp issue occurs in the same glyph.
A way to fix errors and warnings is just remove this glyph which is very likely just garbage.
My idea was to not be too much aggressive in just removing the glyph because of the wrong bbox, but that said I'm fine to remove it. Wdyt ?

**Comment by Snuffleupagus** [comment]
> A way to fix errors and warnings is just remove this glyph which is very likely just garbage.
> My idea was to not be too much aggressive in just removing the glyph because of the wrong bbox, but that said I'm fine to remove it. Wdyt ?

Sure, let's keep it as-is for now. (We can always revisit this, if that ever becomes necessary e.g. with a future OTS version.)

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you!
