### PR TITLE
[Editor] Avoid to have a stamp editor resizing itself

### LINKED ISSUE #18715: [Bug]: An added stamp annotation is resizing itself
### Attach (recommended) or Link to PDF file

Whatever pdf.

### Web browser and its version

Firefox nightly

### Operating system and its version

Windows 11

### PDF.js version

master

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Add a stamp annotation
2. Eventually change the zoom level

### What is the expected behavior?

Nothing.

### What went wrong?

The annotation is resizing itself

### Link to a viewer

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by calixteman**
Fixes #18715.

### CODE REVIEW

File: test/integration/stamp_editor_spec.mjs [hunk 1]
```diff
@@ -1097,4 +1098,47 @@ describe("Stamp Editor", () => {
...
+        pages.map(async ([browserName, page]) => {
+          const getDims = () =>
+            page.evaluate(sel => {
+              const bbox = document.querySelector(sel).getBoundingClientRect();
+              return `${bbox.width}::${bbox.height}`;
+            }, editorSelector);
+          const initialDims = await getDims();
+          for (let i = 0; i < 50; i++) {
+            // eslint-disable-next-line no-restricted-syntax
+            await waitForTimeout(10);
```
Comment (Snuffleupagus) [inline test/integration/stamp_editor_spec.mjs:1135]: Is there no better way to handle this, since we've seen repeatedly that using "arbitrary" timeouts often leads to intermittent test failures?
(Ideally we should get rid of that helper function completely.)

**Comment by timvandermeij** [comment]
Thank you for looking into this because in #18708 I thought it was caused by the Puppeteer update. Note that while this fixes _most_ of the regressions from https://github.com/mozilla/pdf.js/pull/18698#issuecomment-2336406803 it doesn't address the highlight annotation one, so for that we should file a follow-up issue.

File: test/integration/stamp_editor_spec.mjs (hunk 1 above)
Comment (timvandermeij) [reply test/integration/stamp_editor_spec.mjs:1135]: In the issue it's stated that this happens when the zoom level is changed, so perhaps we can use that property to immediately trigger the bug? I agree that waiting for a more-or-less arbitrary time should be avoided unless there is really no other way (since especially on the slower Windows bot that's bound to fail intermittently).

Comment (calixteman) [reply test/integration/stamp_editor_spec.mjs:1135]: The zoom level doesn't have to be changed: in patch #18698 we changed the way to compute the size of the page and so we can have some differences (depending on the zoom level) when computing:
https://github.com/mozilla/pdf.js/blob/8e5f06d77d5ebc9ff66d5d57f99109b553ff4e8a/src/display/editor/editor.js#L665
This difference combined with https://github.com/mozilla/pdf.js/blob/8e5f06d77d5ebc9ff66d5d57f99109b553ff4e8a/src/display/editor/stamp.js#L556 (which is removed in this patch) just changes constantly the size (which is updated thanks to a ResizeObserver).

That said, here the waitTimeout isn't a problem: we aren't waiting for something but we're just waiting for nothing to happen !
So of course if the resize is triggered after ~500ms we'll be stuck, but I think it's very unlikely.

This is the second time we've this bug (see #16797) and I don't want to have it a third time, so a test is absolutely required.
That said, if you can imagine a better way to test that stuff, please tell me.

Comment (Snuffleupagus) [reply test/integration/stamp_editor_spec.mjs:1135]: > [...] we aren't waiting for something but we're just waiting for nothing to happen !

Can you please add a (short) comment about this, to aid future readers of this code?

**Review by Snuffleupagus — APPROVED** [review]
r=me, with a comment added; thank you.
