### PR TITLE
Render large images even if they're larger than the canvas limits (bug 1720282)

### LINKED ISSUE #6741: PDF with huge embedded image is displayed as a blank page
PDF: [DC000933-uncompressed.pdf](https://github.com/mozilla/pdf.js/files/57455/DC000933-uncompressed.pdf)

If I open the above PDF in Chrome or Firefox, it is shown as blank at best. Firefox sometimes crashes if I (re)load a couple of times (even at a fresh start-up). I haven't built Firefox with symbols, but GDB shows that the stack trace ends in `mozalloc_abort`, which suggets that this segfault is caused by a memory allocation error.

This PDF is quite unusual, it has a width and height with excessive values:

```
<< /Contents 10 0 R /MediaBox [ 0 0 4444 2592 ] /Parent 6 0 R /Resources << /ExtGState << /G0 11 0 R /G1 12 0 R /G2 13 0 R >> /ProcSet [ /ImageB /ImageC /ImageI ] /XObject << /I0 14 0 R >> >> /Type /Page >>

...

<< /BitsPerComponent 1 /ColorSpace /DeviceGray /DecodeParms << /Columns 24688 /K -1 /Rows 14400 >> /Filter /CCITTFaxDecode /Height 14400 /Name /I0 /Subtype /Image /Type /XObject /Width 24688 /Length 972551 >>
```

It was allegedly created by MetaPrint.

### LINKED ISSUE #8076: Page in PDF not loading completely in Firefox, missing image in Chromium
Link to PDF file: https://www.personalausweisportal.de/SharedDocs/Downloads/DE/Flyer-und-Broschueren/eID_Broschuere.pdf?__blob=publicationFile&v=1 (sha512sum 62e4a6a96257f219d1f1fc1c644eea86b17c056486a91a159e4cc0085347b3bc3c3d1a4e06eae204e1dce92f507afa5d55c21604584ffa852efb7fb303f9f846)

Configuration:
- Web browser and its version: Chromium 53.0.2785.143-0ubuntu0.14.04.1.1145, Firefox 51.0.1+build2-0ubuntu0.14.04.2
- Operating system and its version: Ubuntu 14.04
- PDF.js version: https://mozilla.github.io/pdf.js/web/viewer.html
- Is an extension: Issues happen in the Chromium pdf.js extension, Firefox's native pdf.js and the aforementioned online version of pdf.js

Steps to reproduce the problem:
1. Open the PDF in pdf.js and scroll to the last page.

What is the expected behavior?
The last page renders like in the following screenshot of the page in Evince:
Last page in Evince

What went wrong?
In Firefox: Page doesn't finish loading (loading animation doesn't disappear), page is only partially loaded:
Last page in pdf.js in Firefox
In Chromium: Loading animation disappears, but the QR code is blank (white):
Last page in pdf.js in Chromium

The PDF appears to have been created by "Adobe InDesign CS5.5 (7.5.3)".

### LINKED ISSUE #12307: PDF Image Not Being Rendered
Attach (recommended) or Link to PDF file here: https://drive.google.com/file/d/1fwumi5lTjjA1enmeQVSC-tDJAZLL3pyI/view

Configuration:
- Web browser and its version: 
Chrome Version 85.0.4183.83 
Firefox 80.0 (64-bit)
(worked in Microsoft Edge 44.17763.831.0)
- Operating system and its version:
Windows 10 v1809 build 17763.1397
- PDF.js version: 2.2.228, also tested using viewer at https://mozilla.github.io/pdf.js/web/viewer.html (2.5.207?)
- Is a browser extension: no

Steps to reproduce the problem:
1. Open the linked PDF in Adobe Reader or Acrobat, or a browser. The images are rendered.
2. Open the linked PDF in pdf.js using Chrome or Firefox. Most or all of the images are not rendered.

What is the expected behavior? (add screenshot)
For the images in the PDF to be displayed in pdf.js for all browsers:
https://drive.google.com/file/d/15_9mRv2p-1c3AUOGKIJ7w2u2heV4Mt4M/view

What went wrong? (add screenshot)
The images were not displayed in Chrome or Firefox.
In Chrome, some parts of the PDF was rendered and there were no reported issues:
https://drive.google.com/file/d/1REE9qOP5UQirDs-ZKEhcWykvWY3w8ORv/view

In Firefox an error was reported in the UI:
https://drive.google.com/file/d/1nLl4Rd3aq9DYtTOc3seRWLsWbP1nbSJL/view

In Microsoft Edge using pdfj.js v2.2.228 the complete PDF was displayed. The viewer at https://mozilla.github.io/pdf.js/web/viewer.html didn't work with Edge.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

### LINKED ISSUE #13643: Cannot open a pdf with a large jpx image
Attach (recommended) or Link to PDF file here:
[3.pdf](https://github.com/mozilla/pdf.js/files/6725880/3.pdf)

Configuration:
- Web browser and its version: Firefox nightly
- Operating system and its version: Debian testing
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. Open the attached pdf

What is the expected behavior? (add screenshot)
Display the image

What went wrong? (add screenshot)
Nothing is displayed but an error in console:
```
An error occurred while rendering the page.
PDF.js v2.10.201 (build: 9de0916fd)
Message: 
Stack: putBinaryImageData@resource://pdf.js/build/pdf.js:4873:13
paintInlineImageXObject@resource://pdf.js/build/pdf.js:6445:27
paintImageXObject@resource://pdf.js/build/pdf.js:6393:12
executeOperatorList@resource://pdf.js/build/pdf.js:5128:22
_next@resource://pdf.js/build/pdf.js:3878:39
_scheduleNext/<@resource://pdf.js/build/pdf.js:3866:16
viewer.js:1186:15
    _otherError resource://pdf.js/web/viewer.js:1186
```

I found this pdf in:
https://bugs.chromium.org/p/pdfium/issues/detail?id=1698&q=&can=1

### PR DESCRIPTION
**Pull request by calixteman**
The idea is to encode large image in BMP format (which is very simple and doesn't
require to compute any checksums) and then use createImageBitmap with a BMP blob
(which doesn't suffer of the Canvas/ImageData limits).
From a performance point of view, it isn't crazy (generating a large blob + decoding
it on the main thread is really not ideal) but at least we've something to display
which is a way better than a blank page (and one can notice that most of the time is
spent in decoding the image from the pdf stream).

### CODE REVIEW

**Comment by benbro** [comment]
I've tested this PR with the [PDF](https://github.com/mozilla/pdf.js/files/10784480/bug.pdf) from https://github.com/mozilla/pdf.js/issues/16073.
It does render the arrows above the text but it's still very slow. Is it slow because of the large image? Is there anyway to improve it?

**Comment by hobob0t** [comment]
glad to see progress on this! I stopped using firefox since I view large image PDFs for work (Building plans that have been scanned in)

**Comment by devalberg** [comment]
Would this pull request consider iOS's canvas size as well? We're experiencing a problem where documents with large images would render fine for all browsers except those in iOS, simply because of the smaller canvas area it supports (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas).

I know that this library is primarily developed and targeted for Firefox, but I don't think it would hurt to possibly resolve this for iOS along the way, since it could also be utilizing the resize function but just smaller?

File: src/core/image_resizer.js [hunk 1]
```diff
@@ -0,0 +1,320 @@
...
+      "MAX_AREA",
+      this._guessMax(MIN_IMAGE_DIM, this.MAX_DIM, 0) ** 2
+    );
+  }
+
+  static _guessMax(start, end, defaultHeight) {
+    while (start < end) {
+      const middle = Math.floor((start + end) / 2);
+      const height = defaultHeight || middle;
+      const offscreen = new OffscreenCanvas(middle, height);
```
Comment (Snuffleupagus) [inline src/core/image_resizer.js:70]: Nit: How about the following name, since that's what all other spots in the code-base use? 
```suggestion
      const canvas = new OffscreenCanvas(middle, height);
```

File: src/core/image_resizer.js [hunk 2]
```diff
@@ -0,0 +1,320 @@
...
+      // eslint-disable-next-line no-unused-vars
+      const ctx = offscreen.getContext("2d");
```
[the remark this answers is not in the document]
Comment (Snuffleupagus) [reply src/core/image_resizer.js:72]: This warning seems correct, why did you add the `eslint-disable` above when the variable is completely unused?

[the remark this answers is not in the document]
Comment (calixteman) [reply src/core/image_resizer.js:72]: Because else `transferToImageBitmap` is complaining (i.e. throwing an exception) that the canvas has no context, you can try it in the console:
```
new OffscreenCanvas(1, 1).transferToImageBitmap()
```

[the remark this answers is not in the document]
Comment (Snuffleupagus) [reply src/core/image_resizer.js]: Ah, that's the bit of context I was missing! The updated patch, with the added comment, is good since there's no longer any risk that someone tries to "fix" the eslint-disable by removing code,

File: src/core/image_resizer.js [hunk 3]
```diff
@@ -0,0 +1,320 @@
...
+import { FeatureTest, ImageKind, shadow } from "../shared/util.js";
+
+const MIN_IMAGE_DIM = 2048;
+const MAX_IMAGE_DIM = 65536;
+
+// Large images are encoded in using the BMP format (it's a way faster than
+// encoding in PNG because there are no checksums to compute).
+// Unfortunately, createImageBitmap will create a task in the main thread in
+// order to build the bitmap, hence the main thread is blocked during the
+// decoding which can be a bit long (see bug 1817244).
```
Comment (Snuffleupagus) [inline src/core/image_resizer.js:25]: Blocking the main-thread seems less than ideal, any chance that we can get https://bugzilla.mozilla.org/show_bug.cgi?id=1817244 fixed (or at least assigned) before moving forward with this PR?

File: src/core/image_resizer.js [hunk 4]
```diff
@@ -0,0 +1,320 @@
...
+// When bug 1759728 is fixed we can remove the BMP workaround and at least it
+// should be a way faster to create the bitmap.
```
Comment (Snuffleupagus) [inline src/core/image_resizer.js:27]: Given that https://bugzilla.mozilla.org/show_bug.cgi?id=1759728 has patches now, it might make sense to wait for that to land before moving forward with this PR?

Comment (marco-c) [reply src/core/image_resizer.js:27]: It will likely take a while, and maybe not happen at all, as that change is a bit controversial.

Comment (calixteman) [reply src/core/image_resizer.js:27]: As far as I know, even with the mentioned bug fixed we'll still block the main thread so it won't be ideal either.
As I mentioned in my first comment, it's really not ideal but a way better than a blank page.
Here is a profile with the pdf I added in the test suite:
https://share.firefox.dev/3SJoj5k

We spend around half a second in guessing the max-dims/area: it's improvable for Firefox in getting them from prefs.
We spend around 1.3s to decode the image and move it to a BMP, 1.1s to decode the BMP in the main thread and 0.9s to resize it. And I think it's acceptable (at least compared to the current situation).

We can potentially see some new issues when zooming: the images will be large enough to not fit the 2Mpix limit and consequently they'll be removed once the rendering is done which induce to get it from the worker on each redraw. We could maybe have a different strategy here for large images:
 - we cache them for 5/10 s,
 - once an image expires, we can move  it on a canvas (with `transferFromImageBitmap`), then export the canvas to a png blob (which should really reduce the memory use), and keep the blob for 20/30s. We'll have some overhead when drawing the png but nothing compared to recreate the image from the worker.

I think we could resize it in the worker in tiling it, then rescale each tile and draw them in a smaller canvas but we need to figure out how it works at the tiles junctions (we could probably get a slightly larger tile and then recover the extra pixels with the ones of the next tile).

They're different improvements we can do in the future but this patch is just a version 1.0 and really it improves the current situation.

Comment (Snuffleupagus) [reply src/core/image_resizer.js:27]: > We can potentially see some new issues when zooming: the images will be large enough to not fit the 2Mpix limit and consequently they'll be removed once the rendering is done which induce to get it from the worker on each redraw. We could maybe have a different strategy here for large images:

One thing that I've been wondering, for some time, is if we should perhaps consider simply increasing that limit a bit?

That value originated in PR #2317, and in the decade that have passed the amount of RAM available in (most) devices should have increased a fair bit. (And we also do a better job when it comes to detecting repeated images at both the page and document level, which also helps.)

Another thing we could potentially try is to instead have a total maximum size *per page*, rather than the current image-specific limit?

Anyway, I'd agree that all of this seems better suited for possible follow-up work.

Comment (calixteman) [reply src/core/image_resizer.js:27]: I began to have a look on tiling the original image and rescale each tiles and overall it's slightly slower but at least it doesn't block the main thread. The only concern I've is about the quality on the tile junction.
Anyway I'd prefer for now having this solution blocking the main thread but where the quality of the reduction is good.
I think we could add more reftests and then we could try the tiling strategy in a v2 and we could at least compare the quality of the reduction based on the reftests (if they show something wrong).

Comment (calixteman) [reply src/core/image_resizer.js:27]: And it's worth noticing that it's overall slower and I only test in supposing the width lower than 32767 which allows to take an image chunk as a pixel array slice. If we have to chunkify along the width we'll have a lot of extra memcpies.

File: src/core/image.js [hunk 5]
```diff
@@ -847,6 +886,9 @@ class PDFImage {
     }
 
     imgData.data = data;
+    if (isOffscreenCanvasSupported && mustBeResized) {
```
Comment (Snuffleupagus) [inline src/core/image.js:889]: Nit: Given the definition it looks like the following would be sufficient.
```suggestion
    if (mustBeResized) {
```

File: src/core/image_resizer.js [hunk 6]
```diff
@@ -0,0 +1,326 @@
...
+      "MAX_AREA",
+      this._guessMax(MIN_IMAGE_DIM, this.MAX_DIM, 0) ** 2
+    );
+  }
+
+  static _guessMax(start, end, defaultHeight) {
+    while (start < end) {
+      const middle = Math.floor((start + end) / 2);
+      const height = defaultHeight || middle;
+      let width;
```
Comment (Snuffleupagus) [inline src/core/image_resizer.js:71]: Nit: By initializing this to zero the `catch`-handler further down can just be empty.
```suggestion
      let width = 0;
```

File: src/core/image_resizer.js [hunk 7]
```diff
@@ -0,0 +1,326 @@
...
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+import { FeatureTest, ImageKind, shadow } from "../shared/util.js";
+
+const MIN_IMAGE_DIM = 2048;
+const MAX_IMAGE_DIM = 65536;
```
Comment (Snuffleupagus) [inline src/core/image_resizer.js:19]: Another question that I just had is even trying such a large value makes sense in general?

Is there any browser that would support a `65536 x 65536` pixel image, and would that really be meaningful anyway? Hence I wonder if we could just use a slightly lower value, e.g. half the current one, since that might slightly speed up the binary searching in `_guessMax0` by not trying "ridiculousness" large canvas-sizes?

File: src/core/image_resizer.js [hunk 8]
```diff
@@ -0,0 +1,389 @@
...
+      MAX_DIM,
+      MAX_ERROR,
+      0
+    );
+    this._hasMaxArea = true;
+    const maxArea = this._goodSquareLength ** 2;
+
+    shadow(this, "MAX_AREA", maxArea);
+
+    return area > maxArea;
```
Comment (Snuffleupagus) [inline src/core/image_resizer.js:83]: Can we please utilize the setter instead, to reduce the amount of manual handling here?
```suggestion
    this.MAX_AREA = this._goodSquareLength ** 2;
    
    return area > this.MAX_AREA;
```

File: src/core/image_resizer.js (hunk 7 above)
Comment (calixteman) [reply src/core/image_resizer.js]: Chrome is fine with large dimensions but the main thing the total area:
https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/graphics/skia/skia_utils.h;l=61-69?q=kMaxCanvasArea&ss=chromium%2Fchromium%2Fsrc

`_guessMax` is really fast to guess the max dimensions because the final image is very small (height is 1) but it's a way more slower when trying to guess the max area.
Anyway for Firefox, we'll get the max are thanks to the prefs, we could maybe hard code the above value for Chrome.

**Comment by Snuffleupagus** [comment]
Is there anything else that you want to add in the initial patch, or are the TODOs things that you want to look into in follow-ups?

**Comment by calixteman** [comment]
I'll implement the last TODO tomorrow to use the max canvas area from the Firefox prefs but in a follow-up patch.

File: src/core/image.js [hunk 9]
```diff
@@ -763,6 +798,10 @@ class PDFImage {
                 drawHeight,
                 forceRGB: true,
               });
+              if (isOffscreenCanvasSupported) {
```
Comment (Snuffleupagus) [inline src/core/image.js:801]: This would be a tiny bit clearer, and consistent with other code in this file, as follows:
```suggestion
              if (mustBeResized) {
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, looks good to me and all tests pass; thank you!
