### PR TITLE
[api-minor] Allow loading pdf fonts into another document.

### LINKED ISSUE #12152: Fix pull request #12131 so it can be merged again
It looks like the only problem that required us to do a revert of the patch is the fact that the unit tests in #12131 don't pass locally. However, they don't even run at all on the bots, hence we thought this was safe to merge given that all tests passed.

@timvandermeij Investigate why the bots did not run the test so this won't happen again.
@jsg2021 Could you improve the unit test so that we can try merging the patch again? Note the comment on the PR about what fails. In particular, we need to make sure that the tests work locally too; you can do that by running `gulp unittest` to test in the browser and `gulp unittestcli` to test in Node.js. Both should pass in order for the patch to be merged again. Thanks!

### PR DESCRIPTION
**Pull request by jsg2021**
Addresses PR #12131 browser test failures.
Fixes #12152

### CODE REVIEW

File: test/unit/custom_spec.js [hunk 1]
```diff
@@ -107,3 +107,129 @@ describe("custom canvas rendering", function () {
       .catch(done.fail);
   });
 });
+
+describe("alternate document context", function () {
+  const global = typeof globalThis !== "undefined" ? globalThis : window;
```
Comment (Snuffleupagus) [inline test/unit/custom_spec.js:112]: Sorry, but this isn't correct. The whole point of `globalThis` is that it's always defined, and in a "normal" browser context `globalThis === window`.

Hence please remove this line, and change `global` to `globalThis` below.

File: test/unit/custom_spec.js [hunk 2]
```diff
@@ -107,3 +107,129 @@ describe("custom canvas rendering", function () {
       .catch(done.fail);
   });
 });
+
+describe("alternate document context", function () {
```
Comment (Snuffleupagus) [inline test/unit/custom_spec.js:111]: Also, not that I look at this again a much better name would be `"custom ownerDocument"`, since that's actually consistent with the parameter name.

File: test/unit/custom_spec.js [hunk 3]
```diff
@@ -107,3 +107,129 @@ describe("custom canvas rendering", function () {
...
+        Object.assign(element, {
+          remove() {
+            this.remove.called = true;
+          },
+        });
+      }
+      elements.push(element);
+      return element;
+    };
+    const altDocument = {
```
Comment (Snuffleupagus) [inline test/unit/custom_spec.js:154]: `ownerDocument`, here and elsewhere.

File: test/unit/custom_spec.js [hunk 4]
```diff
@@ -107,3 +107,129 @@ describe("custom canvas rendering", function () {
       .catch(done.fail);
   });
 });
+
+describe("alternate document context", function () {
+  const global = typeof globalThis !== "undefined" ? globalThis : window;
+  const FontFace = global.FontFace;
+
+  const ourFont = font => /g_d\d+_f1/.test(font.family);
```
Comment (Snuffleupagus) [inline test/unit/custom_spec.js:115]: `checkFont` seems like a better name.

File: test/unit/custom_spec.js [hunk 5]
```diff
@@ -107,3 +107,129 @@ describe("custom canvas rendering", function () {
...
+  const ourFontRule = rule =>
+    /^@font-face {font-family:"g_d\d+_f1";src:/.test(rule);
+  const has = (fn, iterable) => !![...iterable].find(fn);
```
Comment (Snuffleupagus) [inline test/unit/custom_spec.js:118]: Both this function name, its implementation, and its usage all seem a slightly unclear; can you please re-factor the checking to be a bit more straightforward and easy to follow?

File: test/unit/custom_spec.js [hunk 6]
```diff
@@ -107,3 +107,129 @@ describe("custom canvas rendering", function () {
       .catch(done.fail);
   });
 });
+
+describe("alternate document context", function () {
+  const global = typeof globalThis !== "undefined" ? globalThis : window;
+  const FontFace = global.FontFace;
+
+  const ourFont = font => /g_d\d+_f1/.test(font.family);
+  const ourFontRule = rule =>
```
Comment (Snuffleupagus) [inline test/unit/custom_spec.js:116]: `checkFontFaceRule` seems like a better name.

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]

File: test/unit/custom_spec.js (hunk 1 above)
Comment (jsg2021) [reply test/unit/custom_spec.js]: This was my first inclination. I didn't know how far back you wanted to support. 

Sorry, for the irritation￼.

File: src/display/api.js [hunk 7]
```diff
@@ -981,9 +987,10 @@ class PDFDocumentProxy {
  * Proxy to a PDFPage in the worker thread.
  */
 class PDFPageProxy {
-  constructor(pageIndex, pageInfo, transport, pdfBug = false) {
+  constructor(pageIndex, pageInfo, transport, ownerDocument, pdfBug = false) {
```
Comment (timvandermeij) [inline src/display/api.js:990]: Should we use the `ownerDocument = globalThis.document` fallback here too since the parameter is optional?

File: test/unit/custom_spec.js [hunk 8]
```diff
@@ -107,3 +107,131 @@ describe("custom canvas rendering", function () {
...
+    expect(collectionMatches(ownerDocument.fonts, checkFont)).toBeTruthy();
+    await doc.destroy();
+    await loadingTask.destroy();
+    CanvasFactory.destroy(canvasAndCtx);
+    expect(ownerDocument.fonts.size).toBe(0);
+  });
+
+  it("should use given document for loading fonts (with CSS rules)", async function () {
+    const { ownerDocument, elements, CanvasFactory } = getMocks();
+    ownerDocument.fonts = null;
```
Comment (timvandermeij) [inline test/unit/custom_spec.js:206]: Is this line necessary? You're creating new mocks in each test, so this will be an empty set by default, but since you're only checking the style tags in this test that shouldn't matter, right?

**Review by timvandermeij — APPROVED** [review]
Looks good to me with these final comments addressed and a rebase. r? @Snuffleupagus for a final check to make sure all is fine now. Thanks!

File: src/display/api.js (hunk 7 above)
Comment (jsg2021) [reply src/display/api.js:990]: it probably shouldn't be optional internally, and only optional on public api

File: test/unit/custom_spec.js (hunk 8 above)
Comment (jsg2021) [reply test/unit/custom_spec.js:206]: that line is what triggers the font loader to fallback. If the document has a truthy value at that key it tries to use that api.

**Comment by jsg2021** [comment]
rebased:)

File: test/unit/custom_spec.js (hunk 8 above)
Comment (timvandermeij) [reply test/unit/custom_spec.js:206]: Ah, I didn't know that. Thanks!

File: src/display/api.js (hunk 7 above)
Comment (timvandermeij) [reply src/display/api.js:984]: That seems alright. Thanks!

**Comment by timvandermeij** [comment]
Ping @Snuffleupagus for a final check to make sure I didn't miss anything here so we can merge this again.

**Comment by Snuffleupagus** [comment]
> Gentle ping @Snuffleupagus if you have time for a final check to make sure I didn't miss anything.

Sorry about the delay here, I've been swamped with other things!

Unfortunately I still believe that https://github.com/mozilla/pdf.js/pull/12154#discussion_r464066181 applies here, even in the latest version of the patch, since https://github.com/mozilla/pdf.js/pull/12154/files#diff-348626e82475ec3536e620f4e5508f75R117-R118 looks quite cryptic and it's not (at least to me) *immediately* obvious what's actually happing there without *very careful* reading of the code.

@timvandermeij What's your opinion of this specific part of the unit-tests, since I worry that this admittedly clever but very terse checker function may hurt maintainability of these tests?

**Comment by jsg2021** [comment]
@Snuffleupagus I'm struggling to understand. Is there a builtin assertion I could use? How is this cryptic? We just want to verify the set or list has the item matching our pattern?

**Comment by jsg2021** [comment]
@Snuffleupagus I've updated to add a custom matcher which makes the callsite look like this:
https://github.com/mozilla/pdf.js/pull/12154/commits/a32ec02381bd466841c66eab8555d439b6827a73#diff-348626e82475ec3536e620f4e5508f75R230
```js
expect(ownerDocument.fonts).toContainElementMatching(checkFont);
```

The custom matcher is here: https://github.com/mozilla/pdf.js/pull/12154/commits/a32ec02381bd466841c66eab8555d439b6827a73#diff-348626e82475ec3536e620f4e5508f75R22-R54
and it replaces:
```js
const collectionMatches = (iterable, matcherFunction) =>
    Array.from(iterable).find(matcherFunction) !== undefined;
```

**Comment by timvandermeij** [comment]
Oof, that's indeed _a lot_ more code for something that's not that difficult. Compared to what it was in the first iteration I think

```javascript
const collectionMatches = (iterable, matcherFunction) =>
    Array.from(iterable).find(matcherFunction) !== undefined;
```

was the most clear. Maybe it would help to not make it a variable like this but just inline the check? So:

```javascript
Array.from(ownerDocument.fonts).find(checkFont) !== undefined
```

I think `collectionMatches` is fine, at least I also don't see a shorter/more clear alternative here.

**Comment by jsg2021** [comment]
Suggestion incorporated and rebased.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you!

**Comment by jsg2021** [comment]
@timvandermeij What does the release schedule look like?

**Comment by timvandermeij** [comment]
We don't have a fixed release schedule. I believe every week or so the code is merged into Firefox Nightly so the builds get tested by users, and NPM releases are usually made when a number of `[api-minor]` patches have landed or when lots of community members request a release. We're currently in the process of implementing support for AcroForms and layers, two big features, so I think we'll make a release after that's done.

**Comment by jsg2021** [comment]
I look forward for the next npm release of pdfjs-dist 😊
