### PR TITLE
[api-minor] Allow loading pdf fonts into another document.

### LINKED ISSUE #8271: Font lost when rendered in an iframe
I'm trying to use an iframe to print a PDF easily, everything is ok but the fonts.

Configuration:
- Web browser and its version: chrome 57
- Operating system and its version: MacOS Sierra 10.12.7
- PDF.js version: pdfjs-dist 1.8.177

Steps to reproduce the problem:
1. Dynamically create an iframe with a canvas, render the pdf in the canvas

Here is my print function which takes the pdfDoc as parameter (from `PDFJS.getDocument(url)`)

```javascript
function print(pdfDoc) {
      if (!pdfDoc || !pdfDoc.numPages) {
        return ;
      }

      var scale = 5;
      var iframe = window.document.createElement('iframe');
      var doc = iframe.contentDocument || iframe.contentWindow.document;
    
      window.document.body.append(iframe);

      doc.open();
      doc.write(
        '<!DOCTYPE html>' +
          '<html>' +
            '<head>' +
              '<style>' +
                '* {margin: 0 !important; padding: 0 !important}' +
                'div{width:612pt; height:792pt;}' +
                'canvas{width:100%; height:100%;}' +
            '</style>' +
          '</head>' +
          '<body></body>' +
        '</html>'
      );
      doc.close();

      function renderPage(num) {
        console.log('Rendering page %d of %d', num, pdfDoc.numPages);

        return pdfDoc
          .getPage(num)
          .then(function (page) {
            var div = doc.createElement('div');
            var canvas = doc.createElement('canvas');
            div.appendChild(canvas);
            doc.body.appendChild(div);
            var viewport = page.getViewport(scale);
            var ctx = canvas.getContext('2d');
            canvas.width = viewport.width;
            canvas.height = viewport.height;
            return page.render({canvasContext: ctx, viewport: viewport}).promise;
          })
          .then(function () {
            if (num < pdfDoc.numPages) {
              return renderPage(num + 1);
            }
          });
      }

      renderPage(1)
        .then(function () {
          iframe.contentWindow.print();
          iframe.remove();
        });
    }
```

On the left, the main page canvas, on the right, the iframe canvas.

image

The rendering in the iframe seems to not embed the fonts.

### PR DESCRIPTION
**Pull request by jsg2021**
This adds support to specify a document context the pdf will render into when getting the pdf document. I wanted to automatically infer the document, based on the container element, but the fonts are loaded in a way that is detached from the viewer. So this makes the getDocument support a param `ownerDocumentContext` (better name suggestions are welcome)

Fixes #8271

### CODE REVIEW

File: src/display/api.js [hunk 1]
```diff
@@ -1942,6 +1942,7 @@ class WorkerTransport {
     this.loadingTask = loadingTask;
     this.commonObjs = new PDFObjects();
     this.fontLoader = new FontLoader({
+      ownerDocumentContext: params.ownerDocumentContext,
```
Comment (Snuffleupagus) [inline src/display/api.js:1945]: Please move this to the bottom of the list instead, to be consistent with ordering used in ` src/display/font_loader.js`.

File: src/display/font_loader.js [hunk 2]
```diff
@@ -25,28 +25,35 @@ import {
...
+    docId,
+    onUnsupportedFeature,
+    ownerDocumentContext = globalThis.document,
+  }) {
     if (this.constructor === BaseFontLoader) {
       unreachable("Cannot initialize BaseFontLoader.");
     }
     this.docId = docId;
     this._onUnsupportedFeature = onUnsupportedFeature;
+    this._ownerDocumentContext = ownerDocumentContext;
```
Comment (Snuffleupagus) [inline src/display/font_loader.js:38]: Why not simply `this._document = ownerDocument;` instead, to reduce the verbosity in the rest of the code?

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]
> (better name suggestions are welcome)

How about simply `ownerDocument`, which seems like slightly less of a mouthful :-)

Also, please note that all `getDocument` parameters should be documented in https://github.com/mozilla/pdf.js/blob/403816040ef64ae17758439948771c2920f96ac4/src/display/api.js#L100-L170

Furthermore, would it be possible to add a unit-test to ensure that this works (and continues to work) correctly?
A suitable place for the test might be in https://github.com/mozilla/pdf.js/blob/master/test/unit/custom_spec.js

---

Finally, please see https://github.com/mozilla/pdf.js/wiki/Squashing-Commits

**Comment by jsg2021** [comment]
I'll make those changes 😊 

I was avoiding _document and ownerDocument to attempt to avoid confusion with the pdf document. though, that's not really referenced throughout the fontloader. I'll use those names. 😊

File: src/display/api.js (hunk 1 above)
Comment (jsg2021) [reply src/display/api.js:1945]: Will do

File: src/display/api.js [hunk 3]
```diff
@@ -152,6 +152,9 @@ function setPDFNetworkStreamFactory(pdfNetworkStreamFactory) {
  *   parsed font data from the worker-thread. This may be useful for debugging
  *   purposes (and backwards compatibility), but note that it will lead to
  *   increased memory usage. The default value is `false`.
+ * @property {HTMLDocument} [ownerDocument] - Specify an explicit document
+ *   context to create elements for and to load resouces into, such as
```
Comment (Snuffleupagus) [inline src/display/api.js:156]: Should `for` perhaps be replaced by `with` above?

Also, please fix the spelling of `resouces` -> `resources` here.

File: src/display/api.js [hunk 4]
```diff
@@ -152,6 +152,9 @@ function setPDFNetworkStreamFactory(pdfNetworkStreamFactory) {
...
+ *   fonts. Defaults to the current document.
```
Comment (Snuffleupagus) [inline src/display/api.js:157]: @timvandermeij Do you think this documentation is clear enough for users, or do you have any suggestions for e.g. improved wording here (or any other suggests about the overall implementation)?

File: test/unit/custom_spec.js [hunk 5]
```diff
@@ -107,3 +107,91 @@ describe("custom canvas rendering", function () {
...
+
+  let CanvasFactory;
+
+  beforeAll(() => {
+    global.FontFace = class {};
+    CanvasFactory = isNodeJS ? new NodeCanvasFactory() : new DOMCanvasFactory();
+  });
+
+  afterAll(() => {
+    global.FontFace = FontFace;
```
Comment (Snuffleupagus) [inline test/unit/custom_spec.js:122]: Please also add `CanvasFactory = null;` here.

File: test/unit/custom_spec.js [hunk 6]
```diff
@@ -107,3 +107,91 @@ describe("custom canvas rendering", function () {
...
+        this.cssRules.push(rule);
+      },
+    };
+    const getDocumentParams = buildGetDocumentParams(
+      "TrueType_without_cmap.pdf",
+      {
+        disableFontFace: false,
+        ownerDocument: {
+          fonts: null,
+          createElement(x) {
```
Comment (Snuffleupagus) [inline test/unit/custom_spec.js:167]: As a rule we don't want to use one-letter variable/argument names, since those are generally too non-descriptive.

File: test/unit/custom_spec.js [hunk 7]
```diff
@@ -107,3 +107,91 @@ describe("custom canvas rendering", function () {
...
+    const viewport = page.getViewport({ scale: 1 });
+    const canvasAndCtx = CanvasFactory.create(viewport.width, viewport.height);
+
+    await page.render({
+      canvasContext: canvasAndCtx.context,
+      viewport,
+    }).promise;
+
+    expect(domDoc.fonts.size).toBe(1);
+
```
Comment (Snuffleupagus) [inline test/unit/custom_spec.js:148]: You should also be destroying the `CanvasFactory` as well, both here and in the next test.

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]

File: src/display/api.js (hunk 3 above)
Comment (jsg2021) [reply src/display/api.js]: derp. Sorry about that.

File: test/unit/custom_spec.js (hunk 6 above)
Comment (jsg2021) [reply test/unit/custom_spec.js]: Yeah, was going for a minimum viable mock for the interface. I've updated,

File: test/unit/custom_spec.js [hunk 8]
```diff
@@ -107,3 +107,97 @@ describe("custom canvas rendering", function () {
...
+    const viewport = page.getViewport({ scale: 1 });
+    const canvasAndCtx = CanvasFactory.create(viewport.width, viewport.height);
+
+    await page.render({
+      canvasContext: canvasAndCtx.context,
+      viewport,
+    }).promise;
+
+    expect(domDoc.fonts.size).toBe(1);
```
Comment (timvandermeij) [inline test/unit/custom_spec.js:149]: Is there not something we can assert about the font here as well, for example its name? Just to make sure that the expected font is loaded.

File: test/unit/custom_spec.js [hunk 9]
```diff
@@ -107,3 +107,97 @@ describe("custom canvas rendering", function () {
...
+    const domDoc = { fonts: new Set() };
+    const getDocumentParams = buildGetDocumentParams(
+      "TrueType_without_cmap.pdf",
+      {
+        disableFontFace: false,
+        ownerDocument: domDoc,
+      }
+    );
+
+    const task = getDocument(getDocumentParams);
```
Comment (timvandermeij) [inline test/unit/custom_spec.js:136]: I think this is usually called `loadingTask` in other tests.

File: test/unit/custom_spec.js [hunk 10]
```diff
@@ -107,3 +107,97 @@ describe("custom canvas rendering", function () {
...
+
+    expect(domDoc.fonts.size).toBe(1);
+
+    await doc.destroy();
+    await task.destroy();
+    CanvasFactory.destroy(canvasAndCtx);
+    expect(domDoc.fonts.size).toBe(0);
+  });
+
+  it("should use given document for loading fonts (legacy path)", async function () {
```
Comment (timvandermeij) [inline test/unit/custom_spec.js:157]: It could be that I'm missing a bit of knowledge about the font loader here, but what legacy path is meant here?

**Review by timvandermeij — COMMENTED** [review]
Looks good to me aside from these comments.

File: test/unit/custom_spec.js (hunk 8 above)
Comment (jsg2021) [reply test/unit/custom_spec.js:149]: We can assert the font name was loaded.

File: test/unit/custom_spec.js (hunk 10 above)
Comment (jsg2021) [reply test/unit/custom_spec.js:157]: There are two paths. One path adds `FontFace` instances directly to `document.fonts` and the other creates a `<style>` element and appends `@font-face` rules to it.

**Comment by jsg2021** [comment]
I just had an idea, and if it works, it would make this fix 100% transparent. :) 

now that the document is plumbed through, I might be able to set ownerDocument on the pdfDocument in viewer.setDocument.

File: src/display/display_utils.js [hunk 11]
```diff
@@ -65,11 +65,16 @@ class BaseCanvasFactory {
...
+    super();
+    this._document = ownerDocument;
+  }
+
   create(width, height) {
     if (width <= 0 || height <= 0) {
       throw new Error("Invalid canvas size");
     }
-    const canvas = document.createElement("canvas");
+    const canvas = this._document.createElement("canvas");
```
Comment (Snuffleupagus) [inline src/display/display_utils.js:77]: Is this actually a *necessary* change for this patch though, since I cannot imagine that the exact `document` which you use to just *create* the element matters!?

This would e.g. make the `DOMCanvasFactory` and `NodeCanvasFactory` interfaces slightly different (which you'd want to avoid).

File: test/unit/custom_spec.js [hunk 12]
```diff
@@ -107,3 +107,104 @@ describe("custom canvas rendering", function () {
...
+
+    await page.render({
+      canvasContext: canvasAndCtx.context,
+      viewport,
+    }).promise;
+
+    expect(domDoc.fonts.size).toBe(1);
+    const [font] = Array.from(domDoc.fonts);
+    console.dir(font);
+    expect(font.family).toMatch(/g_d[0-9a-f]+_f1/);
```
Comment (Snuffleupagus) [inline test/unit/custom_spec.js:154]: This regular expression, and the one below, isn't entirely correct since the `docId` is always a number and nothing else. Hence you should drop the `a-f` part, and this can be simplified to `/g_d\d+_f1/` (similarily below).

File: test/unit/custom_spec.js (hunk 10 above)
Comment (Snuffleupagus) [reply test/unit/custom_spec.js:162]: Probably clearer to call this test `should use given document for loading fonts (with CSS rules)`.

File: test/unit/custom_spec.js [hunk 13]
```diff
@@ -107,3 +107,104 @@ describe("custom canvas rendering", function () {
...
+    };
+    CanvasFactory = isNodeJS ? new NodeCanvasFactory() : new DOMCanvasFactory();
+  });
+
+  afterAll(() => {
+    global.FontFace = FontFace;
+    CanvasFactory = null;
+  });
+
+  it("should use given document for loading fonts", async function () {
```
Comment (Snuffleupagus) [inline test/unit/custom_spec.js:128]: Probably clearer to call this test `should use given document for loading fonts (with Font Loading API)`.

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]

File: src/display/display_utils.js (hunk 11 above)
Comment (jsg2021) [reply src/display/display_utils.js:77]: Yes. The canvas only has access to the resources owned by the creating (owner) document. So, calls to measure/draw text will be inaccurate without this. 

I didn't just change this without cause, I still had missing fonts on some pages. Patching the creation of canvases to use the owner document fixes it.

The interface is the same. They have an optional argument for the constructor (Node version doesn't care, so it ignores) I could explicitly add that to the node constructor?

File: test/unit/custom_spec.js (hunk 13 above)
Comment (jsg2021) [reply test/unit/custom_spec.js:128]: I'll update the test names to use those labels.

File: test/unit/custom_spec.js (hunk 12 above)
Comment (jsg2021) [reply test/unit/custom_spec.js:154]: I didn't find the source of that string, so I went with a safe-ish pattern. I'm trying to tread lightly and respectfully with my changes. 😊 

I'll simplify the patterns.

File: src/display/display_utils.js (hunk 11 above)
Comment (jsg2021) [reply src/display/display_utils.js:77]: If you insert (adopt) a canvas created in a foreign document into a new document, it will gain access to fonts loaded in your document and lose access to fonts from its original document. This point is especially important for scratch/off-screen canvases.

**Comment by jsg2021** [comment]
> I just had an idea, and if it works, it would make this fix 100% transparent. :)
> 
> now that the document is plumbed through, I might be able to set ownerDocument on the pdfDocument in viewer.setDocument.

After testing this idea, it turns out it won't work. The document is already in use by the time `setDocument` gets called. We will just have to set ownerDocument when calling `getDocument` from the API if we intend to render the viewer in another document.

File: test/unit/custom_spec.js [hunk 14]
```diff
@@ -107,3 +107,104 @@ describe("custom canvas rendering", function () {
...
+    const canvasAndCtx = CanvasFactory.create(viewport.width, viewport.height);
+
+    await page.render({
+      canvasContext: canvasAndCtx.context,
+      viewport,
+    }).promise;
+
+    expect(domDoc.fonts.size).toBe(1);
+    const [font] = Array.from(domDoc.fonts);
+    console.dir(font);
```
Comment (timvandermeij) [inline test/unit/custom_spec.js:153]: Left-over debug print should be removed.

File: test/unit/custom_spec.js [hunk 15]
```diff
@@ -107,3 +107,104 @@ describe("custom canvas rendering", function () {
...
+    expect(font.family).toMatch(/g_d\d+_f1/);
+
+    await doc.destroy();
+    await loadingTask.destroy();
+    CanvasFactory.destroy(canvasAndCtx);
+    expect(domDoc.fonts.size).toBe(0);
```
Comment (timvandermeij) [inline test/unit/custom_spec.js:159]: Can/should we do a similar check in the test below?

File: test/unit/custom_spec.js [hunk 16]
```diff
@@ -107,3 +107,104 @@ describe("custom canvas rendering", function () {
...
+      "TrueType_without_cmap.pdf",
+      {
+        disableFontFace: false,
+        ownerDocument: domDoc,
+      }
+    );
+
+    const loadingTask = getDocument(getDocumentParams);
+    const doc = await loadingTask.promise;
+
```
Comment (timvandermeij) [inline test/unit/custom_spec.js:140]: Let's remove this newline like in the test below.

File: test/unit/custom_spec.js [hunk 17]
```diff
@@ -107,3 +107,104 @@ describe("custom canvas rendering", function () {
...
+describe("alternate document context", function () {
+  const FontFace = global.FontFace;
+
+  let CanvasFactory;
+
+  beforeAll(() => {
+    global.FontFace = function MockFontFace(name) {
+      this.family = name;
+    };
+    CanvasFactory = isNodeJS ? new NodeCanvasFactory() : new DOMCanvasFactory();
```
Comment (timvandermeij) [inline test/unit/custom_spec.js:120]: The `DOMCanvasFactory` gets no parameter here, even though that was added above. Is that expected?

**Review by timvandermeij — COMMENTED** [review]
Looks good to me with these final comments addressed. If @Snuffleupagus is also happy with it, we can merge it.

File: test/unit/custom_spec.js (hunk 15 above)
Comment (jsg2021) [reply test/unit/custom_spec.js:159]: yep

File: test/unit/custom_spec.js (hunk 17 above)
Comment (jsg2021) [reply test/unit/custom_spec.js]: I've added it

File: src/display/api.js [hunk 18]
```diff
@@ -152,6 +152,9 @@ function setPDFNetworkStreamFactory(pdfNetworkStreamFactory) {
  *   parsed font data from the worker-thread. This may be useful for debugging
  *   purposes (and backwards compatibility), but note that it will lead to
  *   increased memory usage. The default value is `false`.
+ * @property {HTMLDocument} [ownerDocument] - Specify an explicit document
+ *   context to create elements with and to load resources into, such as
+ *   fonts. Defaults to the current document.
```
Comment (Snuffleupagus) [inline src/display/api.js:157]: This *might* flow a little better with:
```suggestion
 * @property {HTMLDocument} [ownerDocument] - Specify an explicit document
 *   context to create elements with and to load resources, such as fonts,
 *   into. Defaults to the current document.
```

File: src/display/display_utils.js [hunk 19]
```diff
@@ -65,11 +65,16 @@ class BaseCanvasFactory {
 }
 
 class DOMCanvasFactory extends BaseCanvasFactory {
+  constructor(ownerDocument = globalThis.document) {
```
Comment (Snuffleupagus) [inline src/display/display_utils.js:68]: This needs to be future-proof, to avoid issues if/when we need to add more parameters here; hence please change to
```suggestion
  constructor({ ownerDocument = globalThis.document, } = {}) {
```
and update the call-site in `src/display/api.js` accordingly.

File: src/display/api.js (hunk 18 above)
Comment (Snuffleupagus) [reply src/display/api.js:157]: Furthermore, please add a default value [after this line](https://github.com/mozilla/pdf.js/blob/c5663f2f6b95680c9b7ce0c0f1e0021aa22deebe/src/display/api.js#L270), similar to the other `getDocument` options:
```javascript
if (typeof params.ownerDocument === "undefined") {
  params.ownerDocument = globalThis.document;
}
```

File: src/display/api.js [hunk 20]
```diff
@@ -907,9 +910,10 @@ class PDFDocumentProxy {
  * @alias PDFPageProxy
  */
 class PDFPageProxy {
-  constructor(pageIndex, pageInfo, transport, pdfBug = false) {
+  constructor(pageIndex, pageInfo, transport, ownerDocument, pdfBug = false) {
     this._pageIndex = pageIndex;
     this._pageInfo = pageInfo;
+    this._document = ownerDocument;
```
Comment (Snuffleupagus) [inline src/display/api.js:916]: Please keep the `ownerDocument` name here, given the updated `DOMCanvasFactory` signature (see comment above).

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]
Looks OK to me, with the final comments addressed and all test passing.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you for your contribution! (The reference tests failures are unrelated intermittents.)

**Comment by jsg2021** [comment]
awesome 😊

File: test/unit/custom_spec.js [hunk 21]
```diff
@@ -107,3 +107,119 @@ describe("custom canvas rendering", function () {
       .catch(done.fail);
   });
 });
+
+describe("alternate document context", function () {
+  const FontFace = global.FontFace;
```
Comment (Snuffleupagus) [inline test/unit/custom_spec.js:112]: This is completely wrong, since `global` isn't actually defined other than in Node.js and these unit-tests now fail in browsers with `ReferenceError: global is not defined ...`

Fixing that locally, however, *still* causes these tests to fail, now with `TypeError: canvas.getContext is not a function ...` in browsers.

When reviewing this, I simply assumed that the new unit-tests were actually *tested* and thus working, but looking at them again I'm no longer sure that they're doing the right thing in general unfortunately. (E.g. the `ownerDocument` probably *needs* to be a valid `HTMLDocument`-instance, rather than a regular object.)

It's strange that this didn't cause the bots to fail, but it's clear from the logs that these new tests didn't even run. Unfortunately I cannot see an *immediate* fix for the unit-tests, and just removing the unit-tests seem like the wrong approach.

@timvandermeij Can you please back out this patch, since this shouldn't have landed as-is.

Comment (timvandermeij) [reply test/unit/custom_spec.js:112]: This patch is now reverted. It's indeed really not great that Jasmine doesn't even run the test and therefore the bots think all is fine. I'll try to find out why that happens since we want to get a failed test if that ever happens.
