### PR TITLE
[JS] Fix few bugs present in the pdf for issue #14862

### LINKED ISSUE #14705: Set Textfield-Value with Javascript not working as expected
**Demo PDF:**

[js_set_textfield_value.pdf](https://github.com/mozilla/pdf.js/files/8323371/js_set_textfield_value.pdf)

**Configuration:**
- Web browser and its version: Chrome Version 99.0.4844.74 (Offizieller Build) (64-Bit)
- Operating system and its version: Windows 10
- PDF.js version: Online Demo Viewer( https://mozilla.github.io/pdf.js/web/viewer.html )

**Steps to reproduce the problem:**
1. Load example pdf into demo viewer( https://mozilla.github.io/pdf.js/web/viewer.html )
2. Enter Something into the Textfield
3. Toggle Checkbox to change the value of the Textfield
=> Not Working

The Problem only occurs after something was put in the Textfield manually, if you load the pdf into the viewer and just toggle the checkbox the textfield value is changed as expected

**Link to a viewer** (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

### LINKED ISSUE #14862: Too much recursion in a form with some embedded JS
Attach (recommended) or Link to PDF file here:
[it201_fill_in_2d.pdf](https://github.com/mozilla/pdf.js/files/8598902/it201_fill_in_2d.pdf)
The original url is:
https://www.tax.ny.gov/pdf/current_forms/it/it201_fill_in_2d.pdf

Configuration:
- Web browser and its version: Firefox nightly
- Operating system and its version: windows 11

Steps to reproduce the problem:
1. Click in "Your first name" field
2. then click in "Your last name" field

What went wrong?
Open the devtools: some errors because of "too much recursion" are displayed.

### PR DESCRIPTION
**Pull request by calixteman**
- since resetForm function reset a field value a calculateNow is consequently triggered.
  But the calculate callback can itself call resetForm, hence an infinite recursive loop.
  So basically, prevent calculeNow to be triggered by itself.
- in Firefox, the letters entered in some fields were duplicated: "AaBb" instead of "AB".
  It was mainly because beforeInput was triggering a Keystroke which was itself triggering
  an input value update and then the input event was triggered.
  So in order to avoid that, beforeInput calls preventDefault and then it's up to the JS to
  handle the event.
- fields have a property valueAsString which returns the value as a string. In the
  implementation it was wrongly used to store the formatted value of a field (2€ when the user
  entered 2). So this patch implements correctly valueAsString.
- non-rendered fields can be updated in using JS but when they're, they must take some properties
  in the annotationStorage. It was implemented for field values, but it wasn't for
  display, colors, ...
- it fixes #14862 and #14705.

### CODE REVIEW

File: src/display/annotation_layer.js [hunk 1]
```diff
@@ -297,6 +297,110 @@ class AnnotationElement {
     return container;
   }
 
+  get _commonActions() {
```
Comment (Snuffleupagus) [inline src/display/annotation_layer.js:300]: All of the code in this method is just copy-pasted from its previous position, so I don't really have to "review it" here, right?

File: src/display/annotation_layer.js [hunk 2]
```diff
@@ -297,6 +297,110 @@ class AnnotationElement {
...
+    if (!storedData) {
+      return;
+    }
+
+    const commonActions = this._commonActions;
+    for (const [actionName, detail] of Object.entries(storedData)) {
+      const action = commonActions[actionName];
+      if (action) {
+        action({ detail, target: element });
+        // The action is been consumed: no need to keep it.
```
Comment (Snuffleupagus) [inline src/display/annotation_layer.js:398]: Please replace "is" with "has" here, i.e.
`// The action has been consumed: no need to keep it.`

File: src/display/annotation_layer.js [hunk 3]
```diff
@@ -962,32 +988,29 @@ class TextWidgetAnnotationElement extends WidgetAnnotationElement {
...
-                formattedValue: elementData.formattedValue,
+                formattedValue,
               });
             },
             selRange(event) {
-              const [selStart, selEnd] = event.detail.selRange;
-              if (selStart >= 0 && selEnd < event.target.value.length) {
-                event.target.setSelectionRange(selStart, selEnd);
-              }
+              event.target.setSelectionRange(...event.detail.selRange);
```
Comment (Snuffleupagus) [inline src/display/annotation_layer.js:1013]: This looks nicer :-)

File: src/display/annotation_layer.js [hunk 4]
```diff
@@ -297,6 +297,110 @@ class AnnotationElement {
...
+    }
+  }
+
+  _setDefaultPropertiesFromJS(element) {
+    if (!this.enableScripting) {
+      return;
+    }
+
+    // Some properties may have been updated thanks to JS.
+    const storedData = this.annotationStorage.getMutableValue(this.data.id);
```
Comment (Snuffleupagus) [inline src/display/annotation_layer.js:388]: As mentioned elsewhere: `getMutableValue` -> `getRawValue`.

**Review by Snuffleupagus — APPROVED** [review]
r=me, with the comments fixed and all tests passing; thank you!

File: src/display/annotation_layer.js (hunk 1 above)
Comment (calixteman) [reply src/display/annotation_layer.js:300]: Yes no need to review it.

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]

File: src/scripting_api/doc.js [hunk 5]
```diff
@@ -1103,30 +1111,52 @@ class Doc extends PDFObject {
   }
 
   resetForm(aFields = null) {
-    if (aFields && !Array.isArray(aFields) && typeof aFields === "object") {
+    // Handle the case resetForm({ aFields: ... })
+    if (typeof aFields === "object") {
```
[the remark this answers is not in the document]
Comment (calixteman) [reply src/scripting_api/doc.js:1115]: Good catch (I didn't know that). I'll fix few other similar errors.

**Comment by Snuffleupagus** [comment]
Also, it seems that the `Interaction in 160F-2019.pdf must reset all` test is timing out consistently now.

**Comment by calixteman** [comment]
> Also, it seems that the `Interaction in 160F-2019.pdf must reset all` test is timing out consistently now.

It's very likely because of the error you caught (the typeof thing).

**Comment by calixteman** [comment]
@Snuffleupagus, are you still ok with this change ?
