### PR TITLE
pdf2svg.js: provides ReadableSVGStream class to serialize a SVG as a stream

### LINKED ISSUE #8434: SVG: "RangeError: Invalid string length"
Steps to reproduce (attached file)
[invalidstringlength.pdf](https://github.com/mozilla/pdf.js/files/1021334/invalidstringlength.pdf)

````
npm install
gulp dist
node examples/node/pdf2svg.js /tmp/invalidstringlength.pdf
````

Console:
````
# Document Loaded
Number of Pages: 1

# Page 1
Size: 595.32x841.92

Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented graphic state BM
Warning: Unimplemented graphic state ca
Warning: Unimplemented graphic state BM
Warning: Unimplemented graphic state ca
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Error: RangeError: Invalid string length
````

### PR DESCRIPTION
**Pull request by Rob--W**
As usual, see the commit message for a detailed description.

This fixes #8434, but only if the system has enough memory to fit the other data structures of PDF.js. On 64-bit systems, the heap size is about 1.5G, and that appears to be enough memory for the example from #8434. If you use a 32-bit system, the default heap size is half of that, and Node.js crashes due to OOM (tested using Node.js 7.10.0).

If the example crashes, try forcing a (bigger) heap size using the `--max_old_space_size` flag:

```sh
node --max_old_space_size=1000 examples/node/pdf2svg.js /tmp/invalidstringlength.pdf
```

The generated SVG file has a size of 265MB (while the original PDF is 2MB), mostly used by 37 gigantic data-URLs. This can surely be improved, but that is out of the scope for this issue.

### CODE REVIEW

File: examples/node/domstubs.js [hunk 1]
```diff
@@ -94,39 +94,102 @@ DOMElement.prototype = {
...
   },
+
+  // This method is offered for convenience. It is recommended to directly use
+  // getSerializer because that allows you to process the chunks as they come
+  // instead of requiring the whole image to fit in memory.
+  toString: function DOMElement_toString() {
+    var buf = [];
+    var serializer = this.getSerializer();
+    var chunk;
+    while ( (chunk = serializer.getNext()) !== null) {
```
Comment (timvandermeij) [inline examples/node/domstubs.js]: Nit: remove the space before the second parenthesis

File: examples/node/pdf2svg.js [hunk 2]
```diff
@@ -17,32 +20,65 @@ var pdfjsLib = require('pdfjs-dist');
...
-// Get filename from the path
+/**
+ * A readable stream which offers a stream representing the serialization of a
+ * given DOM element (as defined by domstubs.js).
+ *
+ * @param {object} options
+ * @param {DOMElement} options.svgElement The element to serialize
+ */
+function ReadableSVGStream(options) {
+  if (!(this instanceof ReadableSVGStream))
```
Comment (timvandermeij) [inline examples/node/pdf2svg.js]: Nit: add curly brackets around single-line bodies as well for consistency with the other code

File: examples/node/pdf2svg.js [hunk 3]
```diff
@@ -69,13 +105,14 @@ pdfjsLib.getDocument({
         var svgGfx = new pdfjsLib.SVGGraphics(page.commonObjs, page.objs);
         svgGfx.embedFonts = true;
         return svgGfx.getSVG(opList, viewport).then(function (svg) {
-          var svgDump = svg.toString();
-          return new Promise(function(resolve) {
-            writeToFile(svgDump, pageNum, resolve);
+          return writeSvgToFile(svg, getFilePathForPage(pageNum)).then(function () {
+            console.log('Page: ' + pageNum);
+          }, function(err) {
+            console.log('Error ' + err);
```
Comment (timvandermeij) [inline examples/node/pdf2svg.js]: Nit: can we add a colon here as well for readability?

**Review by timvandermeij — COMMENTED** [review]
Drive-by comments. If you could fix these while you rebase, that would be great.

**Comment by Rob--W** [comment]
Rebased and addressed nits. @timvandermeij Please take another look.

**Comment by doublex** [comment]
@Rob--W @timvandermeij 
This patch fixes my "out of memory" issues.

File: examples/node/domstubs.js [hunk 4]
```diff
@@ -91,39 +91,102 @@ DOMElement.prototype = {
...
   },
+
+  // This method is offered for convenience. It is recommended to directly use
+  // getSerializer because that allows you to process the chunks as they come
+  // instead of requiring the whole image to fit in memory.
+  toString: function DOMElement_toString() {
+    var buf = [];
+    var serializer = this.getSerializer();
+    var chunk;
+    while ((chunk = serializer.getNext()) !== null) {
```
Comment (Rob--W) [inline examples/node/domstubs.js]: @doublex I updated this PR, and changed this line, as follows:

```diff
--- a/examples/node/pdf2svg.js
+++ b/examples/node/pdf2svg.js
@@ -56,7 +56,7 @@ util.inherits(ReadableSVGStream, stream.Readable);
 // Implements https://nodejs.org/api/stream.html#stream_readable_read_size_1
 ReadableSVGStream.prototype._read = function() {
   var chunk;
-  while ((chunk = this.serializer.getNext())) {
+  while ((chunk = this.serializer.getNext()) !== null) {
     if (!this.push(chunk)) {
       return;
     }
```

This is necessary, because otherwise the SVG file is truncated too early (e.g. when a SVG node has no text content).

**Comment by timvandermeij** [comment]
I'm not noticing any difference with and without this patch applied. Taking the `invalidstringlength.pdf` file, the current master branch produces a 2.2 MB SVG file (as opposed to the mentioned 265 MB) and it completes successfully without errors. For `core-dump.pdf`, it crashes at page 30 due to OOM, also when this patch is applied. Raising and lowering the heap size (500, 1000, 2000) gives the same results for both the master branch and this patch.

Any idea what's going on? Can you reproduce this?

**Comment by Rob--W** [comment]
The resulting file should be byte-for-byte identical, because this only changes how the data is generated (incremental & streaming instead of the whole PDF page at once).

The generated file has a smaller size than originally described because meanwhile #8620 has landed, which reduces the size of the embedded image.

If you want to see a concrete change in behavior, revert #8620 and compare the result before and after applying this PR.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Looks good; thank you!
