### PR TITLE
Fix intermittent failure in the "supports specifying a custom origin" viewer integration test

### LINKED ISSUE #19951: [Bug]: Intermittent failure in the "supports specifying a custom origin" viewer integration test
### Attach (recommended) or Link to PDF file

N/A

### Web browser and its version

Firefox 138.0.3

### Operating system and its version

Arch Linux

### PDF.js version

5.2.133

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

The following traceback showed up recently as one of the most occurring intermittents (the most recent one from http://54.193.163.58:8877/13f5eafa0bf6ee8/output.txt):

```
3) PDF viewer Zoom origin supports specifiying a custom origin
  Message:
[31m    In firefox, zoom in: Expected 'Hence, recording and compiling a trace speculates that the path andtyping will be exactly as they were during recording for subsequentiterations of the loop.Every compiled trace contains all the guards (checks) requiredto validate the speculation. If one of the guards fails (if controlﬂow is different, or a value of a different type is generated), thetrace exits. If an exit becomes hot, the VM can record a branchtrace starting at the exit to cover the new path. In this way, the VMrecords a trace tree covering all the hot paths through the loop.Nested loops can be difﬁcult to optimize for tracing VMs. Ina na¨ıve implementation, inner loops would become hot ﬁrst, andthe VM would start tracing there. When the inner loop exits, theVM would detect that a different branch was taken. The VM wouldtry to record a branch trace, and ﬁnd that the trace reaches not theinner loop header, but the outer loop header. At this point, the VMcould continue tracing until it reaches the inner loop heade ... to be 'guards'.[0m
  Stack:
        at <Jasmine>
        at file:///C:/pdfjs/botio-files-pdfjs/private/13f5eafa0bf6ee8/test/integration/viewer_spec.mjs:87:14
        at async Promise.all (index 0)
        at async UserContext.<anonymous> (file:///C:/pdfjs/botio-files-pdfjs/private/13f5eafa0bf6ee8/test/integration/viewer_spec.mjs:62:7)
  Message:
[31m    In firefox, zoom out: Expected 'Hence, recording and compiling a trace speculates that the path andtyping will be exactly as they were during recording for subsequentiterations of the loop.Every compiled trace contains all the guards (checks) requiredto validate the speculation. If one of the guards fails (if controlﬂow is different, or a value of a different type is generated), thetrace exits. If an exit becomes hot, the VM can record a branchtrace starting at the exit to cover the new path. In this way, the VMrecords a trace tree covering all the hot paths through the loop.Nested loops can be difﬁcult to optimize for tracing VMs. Ina na¨ıve implementation, inner loops would become hot ﬁrst, andthe VM would start tracing there. When the inner loop exits, theVM would detect that a different branch was taken. The VM wouldtry to record a branch trace, and ﬁnd that the trace reaches not theinner loop header, but the outer loop header. At this point, the VMcould continue tracing until it reaches the inner loop heade ... to be 'guards'.[0m
  Stack:
        at <Jasmine>
        at file:///C:/pdfjs/botio-files-pdfjs/private/13f5eafa0bf6ee8/test/integration/viewer_spec.mjs:101:14
        at async Promise.all (index 0)
        at async UserContext.<anonymous> (file:///C:/pdfjs/botio-files-pdfjs/private/13f5eafa0bf6ee8/test/integration/viewer_spec.mjs:62:7
```

### What is the expected behavior?

The integration test should pass consistently.

### What went wrong?

The integration test fails intermittently.

### Link to a viewer

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by timvandermeij**
The problem in the original code is that `getTextAt` is called too early and therefore returns unexpected text content. This can happen because we call `increaseScale` and then wait for the page's text layer to be visible, but it can take some time before the zoom actually occurs/completes in the viewer and in the meantime the old (pre-zoom) text layer may still be visible, causing us to continue too soon because we don't validate that we're dealing with the post-zoom text layer.

This commit fixes the issue by simply waiting for the expected text to show up at the given origin coordinates, which makes the test work independent of viewer actions/timing.

Fixes #19951.

### CODE REVIEW

File: test/integration/viewer_spec.mjs [hunk 1]
```diff
@@ -81,10 +65,9 @@ describe("PDF viewer", () => {
             },
             [originX, originY]
           );
-          const textAfterZoomIn = await getTextAt(page, 2, originX, originY);
-          expect(textAfterZoomIn)
-            .withContext(`In ${browserName}, zoom in`)
-            .toBe(text);
+          await page.waitForFunction(
+            `document.elementFromPoint(${originX}, ${originY})?.textContent === "${text}"`
+          );
```
Comment (Snuffleupagus) [inline test/integration/viewer_spec.mjs:70]: > This can happen because we call `increaseScale` and then wait for the page's text layer to be visible, but it can take some time before the zoom actually occurs/completes in the viewer and in the meantime the old (pre-zoom) text layer may still be visible, causing us to continue too soon because we don't validate that we're dealing with the post-zoom text layer.

Possibly a stupid question, but isn't there a theoretical risk that these new checks could also target the "old" textLayer if the timing is just right?
Would it be even safer if we awaited the "textlayerrendered" event, before checking the textContent?

**Review by calixteman — APPROVED** [review]
LGTM. Thank you.

File: test/integration/viewer_spec.mjs [hunk 2]
```diff
@@ -42,23 +42,41 @@ describe("PDF viewer", () => {
...
+          }
+        };
+        window.PDFViewerApplication.eventBus.on("textlayerrendered", callback);
+      });
+
+      await page.evaluate(
+        (scaleFactor, origin) => {
+          window.PDFViewerApplication.pdfViewer.updateScale({
+            drawingDelay: 0,
+            steps: 1,
```
Comment (Snuffleupagus) [inline test/integration/viewer_spec.mjs:63]: This line shouldn't be necessary, since `steps` isn't used when a `scaleFactor` is provided; [please see this code](https://github.com/mozilla/pdf.js/blob/712d502561a29df3378dd7fb7cca7a22e4a48ea9/web/pdf_viewer.js#L2289-L2301).
```suggestion
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you.
