### PR TITLE
Use `adjustWidths` for TrueType fonts if we handle them as OpenType (issue 5027, issue 5084, issue 6556, bug 1204903)

### LINKED ISSUE #5027: Character spacing is too small
Characters are all bunched together throughout this file:
https://d5me67xtse2u5.cloudfront.net/documents/1962.35/OutgoingWireRequest.pdf

Bug posted and screenshot taken using OSX Firefox 30. Looks exactly the same via https://mozilla.github.io/pdf.js/web/viewer.html

Looks fine in Adobe Reader and Chrome Viewer. Looks even worse in OSX Preview (completely garbled characters).

Firefox (ignore the spinner in the middle I think, it was a one time issue):
pdfjs-rendering

Adobe Reader:
adobereader-rendering

OSX Preview:
preview-rendering

Firebug console output:
PDF d7112575b73945963bab53a586be0 [1.5 - / -] (PDF.js: 0.8.1181)
Warning: AcroForm/XFA is not supported

Note also that upon initial viewing (and when I took the screenshot) I did not get the "Does not support forms, open in another viewer" prompt. That prompt only appeared when I did a reload in order to get the firebug console output. And regardless, other PDFs which have forms at least display properly even if you can't fill them out.

### LINKED ISSUE #5084: Text rendering issue (incorrect text positioning)
PDF: http://www3.zippyshare.com/v/30063668/file.html

untitled

OS: Windows 8.1
Browsers:
Firefox 30.0
Chrome 36.0
I.E. 11

### LINKED ISSUE #5213: Overlapping text
untitled
Overlapping text, pls check attached file, thank you!

### LINKED ISSUE #6556: Squashed characters of PDFs generated by TCPDF
Our PDF documents are generated using TCPDF 6.2.9. When viewing them in a local PDF viewer (like Evince) everything looks fine:

result-evince

However, when viewing the same PDF in Firefox (→ pdf.js, Firefox 41.0.2 on Ubuntu 15.10) the single letters seem to get squashed:

result-pdf js

The font used is [Roboto](https://www.google.com/fonts/specimen/Roboto). I've uploaded a sample PDF to [http://fallgaeuer.fusonic.net/SamplePdf.pdf](http://fallgaeuer.fusonic.net/SamplePdf.pdf).

Information from the JS console:

```
PDF 94753378c76d8179f7e3f37d9f290f25 [1.7 TCPDF 6.2.9 (http://www.tcpdf.org) / TCPDF] (PDF.js: 1.1.215)
```

### PR DESCRIPTION
**Pull request by Snuffleupagus**
In `Font_checkAndRepair` we can decide that a font isn't TrueType, and instead parse it as CFF. In that case it's quite possible that the `fontMatrix` will be changed, and without calling `adjustWidths` we're failing to update the glyph widths correctly.

Fixes #5027.
Fixes #5084.
Fixes #6556.
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1204903.

**Edit:** Also fixes #5213.

### CODE REVIEW

File: src/core/fonts.js [hunk 1]
```diff
@@ -2647,6 +2647,8 @@ var Font = (function FontClosure() {
         // view of the sanitizer
         data = this.checkAndRepair(name, file, properties);
         if (this.isOpenType) {
+          adjustWidths(properties);
```
Comment (timvandermeij) [inline src/core/fonts.js]: We *might* end up parsing the font as CFF, but we could also not enter https://github.com/Snuffleupagus/pdf.js/blob/adjustWidths/src/core/fonts.js#L4078 and not use CFF in the end. I'm not sure what will happen if we call `adjustWidths` for that case too, so it might be more safe to only call this if we know for sure that CFF parsing has been done.

**Comment by Snuffleupagus** [comment]
@timvandermeij Thanks for asking lots of questions about this on IRC! I've updated the patch to hopefully cover all cases where the `fontMatrix` can change after the font file has been processed.

/botio test

**Comment by timvandermeij** [comment]
This looks better to me! Let's remake the reference images just to be sure.

/botio makeref

**Comment by timvandermeij** [comment]
Thank you for the patch!
