### PR TITLE
Don't stop calculating field values when a Calculate callback throws

### LINKED ISSUE #18561: [Bug]: PDF.js not Performing Calculations on Interactive PDF Forms
### Attach (recommended) or Link to PDF file

[Lowes Measure sheet (2).pdf](https://github.com/user-attachments/files/16494500/Lowes.Measure.sheet.2.pdf)

### Web browser and its version

Mozilla

### Operating system and its version

Linux

### PDF.js version

v4.5.136

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open the attached PDF document in Adobe Reader.
2. Enter values in the input fields.
3. Observe that the total is automatically calculated using the hidden per-unit price field.
4. Open the same PDF document using PDF.js.
5. Enter values in the input fields.
6. Notice that the total is not calculated.

### What is the expected behavior?

PDF.js should perform the same calculations as Adobe Reader when values are entered into the input fields.

image

### What went wrong?

PDF.js does not perform the calculations, and the total remains unchanged when values are entered into the input fields.

image

### Link to a viewer

_No response_

### Additional context

I am experiencing an issue with PDF.js when it comes to interactive PDF forms that involve calculations. I have a PDF document containing input fields for user data entry and hidden fields that perform calculations based on the input values. Specifically, when I open the document in Adobe Reader, entering values in the input fields automatically retrieves a per-unit price from a hidden field and calculates the total by multiplying the per-unit price by the quantity entered. However, this calculation is not happening when I open the same document using PDF.js.

### PR DESCRIPTION
**Pull request by calixteman**
It fixes #18561.

### CODE REVIEW

File: test/integration/scripting_spec.mjs [hunk 1]
```diff
@@ -2510,4 +2510,42 @@ describe("Interaction", () => {
       );
     });
   });
+
+  describe("Calculate field value even if one callback throws", () => {
+    let pages;
+    let otherPages;
```
Comment (timvandermeij) [inline test/integration/scripting_spec.mjs:2516]: `otherPages` is unused in this test and can be removed. I have created PR #18567 to remove it from the other tests where it's unused.

File: test/integration/scripting_spec.mjs [hunk 2]
```diff
@@ -2510,4 +2510,42 @@ describe("Interaction", () => {
...
+      await Promise.all(
+        pages.map(async ([browserName, page], i) => {
+          await waitForScripting(page);
+
+          const inputSelector = getSelector("24R");
+          await page.click(inputSelector);
+          await page.type(inputSelector, "123");
+          await page.click(getSelector("25R"));
+          await page.waitForFunction(
+            `${getQuerySelector("28R")}.value !== "0"`
```
Comment (timvandermeij) [inline test/integration/scripting_spec.mjs:2542]: Let's use `=== "12300"` here so we can remove everything below.

File: test/integration/scripting_spec.mjs [hunk 3]
```diff
@@ -2510,4 +2510,42 @@ describe("Interaction", () => {
...
+      );
+      pages = await loadAndWait("issue18561.pdf", getSelector("24R"));
+    });
+
+    afterAll(async () => {
+      await closePages(pages);
+      await Promise.all(otherPages.map(page => page.close()));
+    });
+
+    it("must check that the product are null", async () => {
```
Comment (timvandermeij) [inline test/integration/scripting_spec.mjs:2532]: This description doesn't seem to reflect what's being tested here; shouldn't it be something like `must continue field value calculation on callback errors` or so?

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you for improving this!
