### PR TITLE
[JS] Fix few errors around AFSpecial_Keystroke

### LINKED ISSUE #14306: AForm validation rejects valid fields
## Attach (recommended) or Link to PDF file here:
The PDF itself is semi-sensitive. I'm happy to provide via unsecured channels, just can't quite post it publicly.

## Configuration:
- Web browser and its version: Firefox 94.0.1
- Operating system and its version: Mac OS 11.6
- PDF.js version: Tested with 2.11.298 (in above Firefox) and git master (5e2aec7dd)

## What is the expected behavior? (add screenshot)
I should be able to fill AForm-validated fields with valid values:
- I should be able to type "123-45-6789" into an SSN field
- I should be able to type "867-5309" into a phone field

## What went wrong? (add screenshot)
I got validation errors instead, when trying to insert the dashes. If I try to not insert the dashes, it lets me while editing, but throws an error when leaving the field.
Screen Shot 2021-11-24 at 11 33 53 AM
Screen Shot 2021-11-24 at 11 37 13 AM
Screen Shot 2021-11-24 at 11 38 29 AM
Screen Shot 2021-11-24 at 11 38 44 AM

## Additional info

For zip codes, the while-typing validation doesn't limit length - I can type as many numbers as I want, and am only complained at once I exit the field.

I've dug into this and will open a PR shortly with more details, but there are other even stranger quirks around internal deletions/insertions as well.

### PR DESCRIPTION
**Pull request by calixteman**
- @cincodenada found some errors which are fixed in this patch;
 - it partially fixes issue #14306;
 - add some tests.

### CODE REVIEW

File: src/scripting_api/aform.js [hunk 1]
```diff
@@ -564,7 +564,7 @@ class AForm {
           event.change.length +
           event.selStart -
           event.selEnd;
-        if (finalLen >= 8) {
+        if (finalLen > 8 || event.value[0] === "(") {
```
Comment (Snuffleupagus) [inline src/scripting_api/aform.js:567]: Assuming that `event.value` is indeed a string, perhaps it'd be a little bit clearer to use `startsWith` for the comparison rather than array notation?

**Review by Snuffleupagus — APPROVED** [review]
Looking at the rest of the `AFSpecial_Keystroke` method (to try and understand this code better), I cannot help thinking that the following block is redundant:
https://github.com/mozilla/pdf.js/blob/290cbc523281cb86fdf0117cf8f2cae521518fb9/src/scripting_api/aform.js#L549-L551
given that we're throwing the exact same error in the `default` of the switch just below:
https://github.com/mozilla/pdf.js/blob/290cbc523281cb86fdf0117cf8f2cae521518fb9/src/scripting_api/aform.js#L576-L577

---

r=me, since the patch looks reasonable.
