### PR TITLE
Correctly handle files with a hash sign in their names (bug 1894166)

### LINKED ISSUE #10632: problem opening filename with hash (#)
Attach (recommended) or Link to PDF file here:
Any PDF with hash in filename.
In my case "Example #1.pdf"

Configuration:
- Web browser and its version:
Firefox 65.0.2
Chrome 72.0.3626.121

- Operating system and its version:
Windows 10 Pro
Version 10.0.17134 build 17134

- PDF.js version:
2.6.5

- Is a browser extension:

Steps to reproduce the problem:
<iframe src="/assets/scripts/pdf/web/viewer.html?file=%2F09%20-%20Ricerche%2FExample%20%231.pdf"></iframe>

What is the expected behavior? (add screenshot)
Show the PDF

What went wrong? (add screenshot)
immagine

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### LINKED ISSUE #19990: [Bug]: Cannot display full file name if it contains sharp symbol (#)
### Attach (recommended) or Link to PDF file

[test#1.pdf](https://github.com/user-attachments/files/20607253/test.1.pdf)

### Web browser and its version

any

### Operating system and its version

window10

### PDF.js version

latest

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1.Open demo https://mozilla.github.io/pdf.js/web/viewer.html
2.Open local pdf file : test#1.pdf

### What is the expected behavior?

display full file name: test#1.pdf

### What went wrong?

The title of viewer.html is "1.pdf", and so is the download file name.

Image

### Link to a viewer

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by calixteman**
It fixes #19990.

### CODE REVIEW

File: src/display/display_utils.js [hunk 1]
```diff
@@ -338,27 +338,32 @@ function getPdfFilenameFromUrl(url, defaultFilename = "document.pdf") {
     warn('getPdfFilenameFromUrl: ignore "data:"-URL for performance reasons.');
     return defaultFilename;
   }
-  const reURI = /^(?:(?:[^:]+:)?\/\/[^/]+)?([^?#]*)(\?[^#]*)?(#.*)?$/;
-  //              SCHEME        HOST        1.PATH  2.QUERY   3.REF
+  const reURI = /^(([^:]+:)?\/\/[^/]+)?([^?#]*)(\?[^#]*)?(#.*)?$/;
```
Comment (nicolo-ribaudo) [inline src/display/display_utils.js]: Would it be possible to use `new URL(...)` to parse the URL, rather than a regexp? URL parsing is incredibly complex and has a lot of edge cases.

**Review by timvandermeij — APPROVED** [review]
r=me; thank you for improving this!

File: src/display/display_utils.js (hunk 1 above)
Comment (timvandermeij) [reply src/display/display_utils.js]: I also like this suggestion; thanks!

File: src/display/display_utils.js [hunk 2]
```diff
@@ -338,31 +338,82 @@ function getPdfFilenameFromUrl(url, defaultFilename = "document.pdf") {
...
+    // If the URL is invalid, return the default filename.
+    return defaultFilename;
+  }
+
+  const decode = name => {
+    try {
+      let decoded = decodeURIComponent(name);
+      if (decoded.includes("/")) {
+        decoded = decoded.split("/").at(-1);
+        if (decoded.test(/^\.pdf$/i)) {
```
Comment (Snuffleupagus) [inline src/display/display_utils.js:374]: @calixteman While rebasing patches I noticed this new code, and as far as I can tell this line will *always* throw!? Currently that's obscured by it being placed inside a `try`-block.

Here `decoded` is a string, and String-instances don't have a `test`-method; try running the following in the console:
```javascript
var decoded = "abc";
decoded.test(/^\.pdf$/i)
```
which results in:
```
Uncaught TypeError: decoded.test is not a function
    <anonymous> debugger eval code:2
debugger eval code:2:9
```

This can be "fixed" by swapping the order, i.e. `/^\.pdf$/i.test(decoded)`, however I don't really understand this code to know if that's correct.
