### PR TITLE
Convert examples/node/pdf2png/pdf2png.js to await/async

### LINKED ISSUE #14126: Convert examples/node/pdf2png/pdf2png.js to await/async
**Please do not work on this issue unless you have applied to the outreachy project.**

The [node/pdf2png/pdf2png.js](https://github.com/mozilla/pdf.js/blob/master/examples/node/pdf2png/pdf2png.js) example currently uses the older style of `promise.then` and callbacks. Convert it to use an `async` function and `await` style.

### PR DESCRIPTION
**Pull request by janekotovich**
### Because

Pdf2png.js uses chain of promises

### This pull request

Convert examples/node/pdf2png/pdf2png.js to await/async

### Issue that this pull request solves

Closes: #14126

### Checklist

Put an x in the boxes that apply

  

- [x] My commit is GPG signed.
- [ ] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

### CODE REVIEW

File: examples/node/pdf2png/pdf2png.js [hunk 1]
```diff
@@ -70,41 +70,41 @@ const loadingTask = pdfjsLib.getDocument({
...
-      const canvasAndContext = canvasFactory.create(
-        viewport.width,
-        viewport.height
-      );
-      const renderContext = {
-        canvasContext: canvasAndContext.context,
-        viewport,
-        canvasFactory,
-      };
-
```
Comment (Snuffleupagus) [inline examples/node/pdf2png/pdf2png.js:91]: Please don't remove this blank line (since it aids readability of the code).

File: examples/node/pdf2png/pdf2png.js [hunk 2]
```diff
@@ -70,41 +70,41 @@ const loadingTask = pdfjsLib.getDocument({
...
+      viewport.height
+    );
+    const renderContext = {
+      canvasContext: canvasAndContext.context,
+      viewport,
+      canvasFactory,
+    };
+    const renderTask = page.render(renderContext);
+    (async function () {
+      await renderTask;
```
Comment (Snuffleupagus) [inline examples/node/pdf2png/pdf2png.js:94]: Note that `renderTask` is *not* a Promise; please see https://github.com/mozilla/pdf.js/blob/f6d9d91965a97c80b6f5b335a27cdb4d36b1b9e2/src/display/api.js#L3171-L3203

Hence these lines should read:
```javascript

    const renderTask = page.render(renderContext);
    await renderTask.promise;
```
and there's no need to add *another* [IIFE](https://developer.mozilla.org/en-US/docs/Glossary/IIFE) here since you're already inside of an async function from above.

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]

**Comment by janekotovich** [comment]
@Snuffleupagus Thanks heaps for help and sorry for misunderstanding.
I took into account all advices and hope this time pull req would be good 🤗
I tested patch with:
gulp dist-install 
gulp server
npm install
npm install canvas
cd examples/node/pdf2png
node pdf2png.js
and all seemed to work well. Let me know If you prefer me squashing commits in one 😊
Regards, Jane

**Review by Snuffleupagus — APPROVED** [review]
r=me; thank you for the patch!
