### PR TITLE
[api-minor] Simplify min/max computations in constructPath (bug 1135277)

### LINKED ISSUE #2765: TilingType
http://pubs.usgs.gov/sim/3067/pdf/sim3067sheet-2.pdf does not have black lines where it should in pdf.js. This is probably because of the warning in the console:

> Warning: TODO: TilingType: 3

... that gets printed 125 times in a row.

Since enough other PDFs want this, perhaps it's finally time to attempt a _complete_ implementation?

### PR DESCRIPTION
**Pull request by calixteman**
- most of the time the current transform is a scaling one (modulo translation),
  hence it's possible to avoid to apply the transform on each bbox and then apply
  it a posteriori;
- compute the bbox when it's possible in the worker.

### CODE REVIEW

File: src/core/evaluator.js [hunk 1]
```diff
@@ -1377,6 +1379,27 @@ class PartialEvaluator {
       const opArgs = operatorList.argsArray[lastIndex];
       opArgs[0].push(fn);
       Array.prototype.push.apply(opArgs[1], args);
+      minMax = opArgs[2];
+    }
+
+    // Compute min/max in the worker instead of the main thread.
+    // If the current matrix (when drawing) is a scaling one
+    // then min/max can easily be computed in using those values.
```
Comment (Snuffleupagus) [inline src/core/evaluator.js:1387]: Grammar nits (assuming I'm understanding the code properly):
```javascript
// If the current matrix (when drawing) has a scaling of one
// then min/max can be easily computed by using those values.
```

File: src/display/canvas.js [hunk 2]
```diff
@@ -1853,6 +1882,15 @@ class CanvasGraphics {
           break;
       }
     }
+
+    if (isScalingMatrix) {
+      Util.scaleMinMax(currentTransform, minMaxForBezier);
+      current.minX = Math.min(current.minX, minMaxForBezier[0]);
+      current.maxX = Math.max(current.maxX, minMaxForBezier[1]);
+      current.minY = Math.min(current.minY, minMaxForBezier[2]);
+      current.maxY = Math.max(current.maxY, [3]);
```
Comment (Snuffleupagus) [inline src/display/canvas.js:1891]: This `[3]`-part looks like a simple typo, right?
If the patch passes all tests like this, then we'd probably want some better test-coverage here...

---

How about instead adding a new method for this code, rather than defining it inline like this?
Maybe something like the following (with perhaps a better name), placed e.g. somewhere [around here](https://github.com/mozilla/pdf.js/blob/379125c37ff58cfb86e3bbd2eca5760fb2fcb061/src/display/canvas.js#L612):
```javascript
updateScalingPathMinMax(transform, minMax) [
  Util.scaleMinMax(transform, minMax):
  this.minX = Math.min(this.minX, minMax[0]);
  this.maxX = Math.max(this.maxX, minMax[1]);
  this.minY = Math.min(this.minY, minMax[2]);
  this.maxY = Math.max(this.maxY, minMax[3]);
}
```

File: src/core/evaluator.js [hunk 3]
```diff
@@ -1377,6 +1379,27 @@ class PartialEvaluator {
...
+        minMax[1] = Math.max(minMax[1], args[0], args[0] + args[2]);
+        minMax[2] = Math.min(minMax[2], args[1], args[1] + args[3]);
+        minMax[3] = Math.max(minMax[3], args[1], args[1] + args[3]);
+        break;
+      case OPS.moveTo:
+      case OPS.lineTo:
+        minMax[0] = Math.min(minMax[0], args[0]);
+        minMax[1] = Math.max(minMax[1], args[0]);
+        minMax[2] = Math.min(minMax[2], args[1]);
+        minMax[3] = Math.max(minMax[3], args[1]);
```
Comment (Snuffleupagus) [inline src/core/evaluator.js:1402]: Please add a `break;` here as well, to prevent a possible future bug if this code is ever moved around.

File: src/display/canvas.js [hunk 4]
```diff
@@ -604,8 +604,15 @@ class CanvasExtraState {
...
   }
 
-  updateCurvePathMinMax(transform, x0, y0, x1, y1, x2, y2, x3, y3) {
+  updateCurvePathMinMax(transform, x0, y0, x1, y1, x2, y2, x3, y3, minMax) {
     const box = Util.bezierBoundingBox(x0, y0, x1, y1, x2, y2, x3, y3);
+    if (minMax) {
+      minMax[0] = Math.min(minMax[0], box[0], box[2]);
+      minMax[1] = Math.min(minMax[1], box[0], box[2]);
+      minMax[2] = Math.min(minMax[2], box[1], box[3]);
+      minMax[3] = Math.min(minMax[3], box[1], box[3]);
```
Comment (Snuffleupagus) [inline src/display/canvas.js:613]: Are all of these lines actually *supposed* to use `Math.min(...)`, or was there a bit too much copy-pasting happening here?

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]
Out of curiosity, what sort of improvement (e.g. in percent) did you see with this patch?

File: src/shared/util.js [hunk 5]
```diff
@@ -720,6 +720,57 @@ class Util {
     return `#${hexNumbers[r]}${hexNumbers[g]}${hexNumbers[b]}`;
   }
 
+  static scaleMinMax(transform, minMax) {
+    // Apply a scaling matrix to some min/max values.
+    // If a scaling factor is negative then min and max must be
+    // swaped.
```
Comment (Snuffleupagus) [inline src/shared/util.js:726]: Maybe place this comment just *above* the method instead?

**Comment by calixteman** [comment]
> Out of curiosity, what sort of improvement (e.g. in percent) did you see with this patch?

It isn't a crazy optimization, I just noticed that in different profiles it was the main bottleneck inside `constructPath` and thought that it shouldn't.
With the pdf in bug 1135277, ~1s was spent in `updatePathMinMax` in the main thread and with the patch ~20ms (and ~200ms extra time in the worker in `buildPath`).
In the different profiles I read in the last days, `updatePathMinMax` takes something around 3, 4%.
