### PR TITLE
[Editor] Hide visible popups when editing

### LINKED ISSUE #16576: [Regression] Popups are no longer closed during editing
Attach (recommended) or Link to PDF file here: https://github.com/mozilla/pdf.js/blob/master/test/pdfs/annotation-freetext.pdf

Configuration:
- Web browser and its version: N/A
- Operating system and its version: N/A
- PDF.js version: `master`, regression from PR #16552
- Is a browser extension: N/A

Steps to reproduce the problem:
1. Open the `annotation-freetext.pdf` document.
2. Click on the blue "FreeText content"-text to open the Popup.
3. Enable FreeText-editing.

What is the expected behavior? (add screenshot)
The Popup closes when editing starts, and re-appears once editing is disabled, as was the case prior to PR #16552.

What went wrong? (add screenshot)
The Popup stays visible during editing, which means that it could "get in the way" visually.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): N/A

/cc @calixteman

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

File: src/display/annotation_layer.js [hunk 1]
```diff
@@ -573,16 +573,22 @@ class AnnotationElement {
     return fields;
   }
 
-  show() {
+  show(restorePreviousePopup = true) {
```
Comment (Snuffleupagus) [inline src/display/annotation_layer.js:576]: This parameter *appears* completely unused, since I cannot find a call-site setting it, why do we need it?
Also, having an optional parameter where `undefined` implies `true` might generally not be the most logical?
(Note that the spelling is slightly wrong: `restorePreviousPopup`.)

File: src/display/annotation_layer.js [hunk 2]
```diff
@@ -573,16 +573,22 @@ class AnnotationElement {
...
+    }
   }
 
   hide() {
     if (this.container) {
       this.container.hidden = true;
     }
+    if (this.popup) {
+      this.popup.forceHide();
+    }
```
Comment (Snuffleupagus) [inline src/display/annotation_layer.js:591]:
```suggestion
    this.popup?.forceHide();
```

File: src/display/annotation_layer.js [hunk 3]
```diff
@@ -2145,6 +2156,26 @@ class PopupElement {
     this.#container.style.zIndex =
       parseInt(this.#container.style.zIndex) - 1000;
   }
+
+  forceHide() {
+    this.#wasVisible = this.isVisible;
+    if (!this.#wasVisible) {
+      return;
+    }
+    this.#container.hidden = true;
```
Comment (Snuffleupagus) [inline src/display/annotation_layer.js:2165]: To prevent any possible future inconsistencies in internal state, should we perhaps call `this.#hide();` here instead to "properly" hide it?

File: src/display/annotation_layer.js [hunk 4]
```diff
@@ -2145,6 +2156,26 @@ class PopupElement {
...
+  }
+
+  restoreVisibility() {
+    if (!this.#wasVisible) {
+      return;
+    }
+    this.#wasVisible = false;
+    this.#container.hidden = false;
```
Comment (Snuffleupagus) [inline src/display/annotation_layer.js:2173]: As above, should this perhaps be `this.#show();` instead?

File: src/display/annotation_layer.js [hunk 5]
```diff
@@ -2145,6 +2156,26 @@ class PopupElement {
...
+
+  forceHide() {
+    this.#wasVisible = this.isVisible;
+    if (!this.#wasVisible) {
+      return;
+    }
+    this.#container.hidden = true;
+  }
+
+  restoreVisibility() {
```
Comment (Snuffleupagus) [inline src/display/annotation_layer.js:2168]: Naming things is hard, but should we perhaps call this `maybeShow` instead to more clearly indicate that it's the "inverse" of the `forceHide` method above?

File: src/display/annotation_layer.js [hunk 6]
```diff
@@ -1880,6 +1885,10 @@ class PopupAnnotationElement extends AnnotationElement {
       this.elements.map(e => e.data.id).join(",")
     );
 
+    for (const element of this.elements) {
+      element.popup = popup;
+    }
```
Comment (Snuffleupagus) [inline src/display/annotation_layer.js:1890]: We're now looping through `this.elements` twice in a row, which seems slightly unnecessary; how about the following instead?
```suggestion

    const ids = [];
    for (const element of this.elements) {
      ids.push(element.data.id);
      element.popup = popup;
    }
    this.container.setAttribute("aria-controls", ids.join(","));
```

File: src/display/annotation_layer.js (hunk 3 above)
Comment (calixteman) [reply src/display/annotation_layer.js:2165]: The "problem" in using `#hide` or `#show` is that they're checking the `pinned` state.
So here we just hide whatever the state of the popup is (pinned or not).
We could of course use them but I had the feeling it was "too much" complexity for such a thing.

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you!
