### PR TITLE
Fix how patterns are applied to image mask objects.

### LINKED ISSUE #13372: Incorrect rendering of shading pattern +  stencil
Attach (recommended) or Link to PDF file here:
[PATTYP2.pdf](https://github.com/mozilla/pdf.js/files/6471935/PATTYP2.pdf)

Configuration:
- Web browser and its version: FF 88.0.1
- Operating system and its version: W10.0.19042.985
- PDF.js version: https://mozilla.github.io/pdf.js/web/viewer.html

Steps to reproduce the problem:
1. open file to display

What is the expected behavior? (add screenshot)
grafik

What went wrong? (add screenshot)
grafik

(memo for me: when fixed, check the files in https://issues.apache.org/jira/browse/PDFBOX-1958 )

### PR DESCRIPTION
**Pull request by brendandahl**
Note, this only really fixes Radial/Axial shading patterns with masks.
I'm guessing tiling patterns and mesh patterns would also be broken
if applied like the test pdf. Hopefully I'll have some time to make
test cases for the other shadings.

Fixes #13372

### CODE REVIEW

File: src/display/canvas.js [hunk 1]
```diff
@@ -193,6 +197,18 @@ function addContextCurrentTransform(ctx) {
   };
 }
 
+function getAdjustmentTransformation(transform, width, height) {
+  // The pattern will be created at the size of the current page or form
+  // object, but the the mask is usually scaled differently and
```
Comment (Snuffleupagus) [inline src/display/canvas.js:202]: Nit: `the the` -> `the`

**Review by Snuffleupagus — APPROVED** [review]
r=me, with the comment nit fixed; thank you!
