### PR TITLE
Reset all the canvas states after rendering each annotations (#14105)

### LINKED ISSUE #9461: Text appears inverted and is misplaced
Attach (recommended) or Link to PDF file here:
[f1.pdf](https://github.com/mozilla/pdf.js/files/1705010/f1.pdf)

Configuration:
- Web browser and its version: Chrome version 64.0.3282.119
- Operating system and its version: Windows 10
- PDF.js version: 2.0.332
- Is a browser extension: no, added as a npm package in project

Steps to reproduce the problem:
1. View the attached pdf using pdfjs, text (E1T) appears at wrong place and is inverted
2. sign in the "acknowledged by Customer signature" text box, and save the document. The signature is viewed at wrong place again.

What is the expected behavior? (add screenshot)
screen shot 2018-02-07 at 2 46 33 pm

What went wrong? (add screenshot)
screen shot 2018-02-07 at 2 47 39 pm

image-1 9

### LINKED ISSUE #14105: stamps are not rendered correctly
PDF file:
[Stamp_Problem.pdf](https://github.com/mozilla/pdf.js/files/7291567/Stamp_Problem.pdf)

Configuration:

- Web browser and its version: current Firefox, Chrome 
- Operating system and its version: Windows 10 
- PDF.js version: current (2.10.377), using viewer from demo site

Steps to reproduce the problem:
Open the attached pdf in a viewer.
If you open the pdf with Acrobat or with integrated Chrome PDF Viewer etc. it looks like in screenshot 1.
If you open it with pdf-js in Chrome, Firefox, Edge or use the integrated PDFViewer of Firefox it looks like screenshot 2.

expected behavior:

The stamps are rendered on top of the table and shown correctly

image

What went wrong:

the stamps are only visible on top of the table lines

image

### PR DESCRIPTION
**Pull request by calixteman**
- each annotation must be rendered independently of the others. So
  after having rendered each annotation, the canvas states are reset
  in order to have something clean to render the next one.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
It looks this patch causes `Warning: Tried to restore a ctx when the stack was already empty.` to be printed in the console for every single page that contain Annotations, which seems a little annoying.

Furthermore, the `endDrawing`-method was probably implemented to only be called *at very the end* of drawing, so is there a risk that something breaks if we now call it twice per page?
For example: While we don't really support the `imageLayer`-parameter, we should probably not call its `endLayout` method until the actual *last* `endDrawing`-call.

**Review by Snuffleupagus — APPROVED** [review]
r=me, with passing tests; thank you!

**Comment by calixteman** [comment]
So `issue8047` was failing because there is an extra wrong `Q` command in the `On` state appearance:
```
BT
/26EBF91525C1400B96AF9B0E30E84747 8.74 Tf
2.853 2.08489006823351 Td
(4) Tj
ET
Q
```
After thinking about, I think the correct way to fix that stuff is to reset the states for each annotation: the rendering of an annotation is independent of the others.

File: src/display/canvas.js [hunk 1]
```diff
@@ -2973,19 +2977,25 @@ class CanvasGraphics {
...
   }
 
-  endAnnotations() {
-    this.restore();
-  }
+  endAnnotations() {}
 
   beginAnnotation(id, rect, transform, matrix, hasOwnCanvas) {
+    this.ctx.save();
     this.save();
```
Comment (Snuffleupagus) [inline src/display/canvas.js:2993]: This `this.save`-call used to be "balanced" by `this.restore`-call in the old `endAnnotation`-method below, [note this code](https://github.com/mozilla/pdf.js/pull/14998/files#diff-76166cff75cae0ec9c490ae47aebbdadff02dbc1e26caaf93779a1bace64dc47L3053).

Unless I'm missing something that's no longer the case, and I thus wonder if this could possibly become a problem?

I can obviously see that there's a `this.restore`-call in the `#restoreInitialState`-method, but that one doesn't run unconditionally.

Comment (calixteman) [reply src/display/canvas.js:2993]: `this.save` pushes a state in `stateStack` and `#restoreInitialState` restore until `stateStack` is empty so it should do the job.
So `save` is balanced with a `#restoreInitialState`.

**Comment by Snuffleupagus** [comment]
Another question (possibly stupid on my part), looking at the latest version of the patch where you reset for every Annotation:

Would the code possibly become a *tiny* bit simpler if we [place this code](https://github.com/mozilla/pdf.js/pull/14998/files#diff-76166cff75cae0ec9c490ae47aebbdadff02dbc1e26caaf93779a1bace64dc47R2984-R2985) at the start of the `beginAnnotation`-method, rather than having that in both of the `beginAnnotations` and `endAnnotation` methods?

**Comment by calixteman** [comment]
I've the feeling that the "restore" code  should be in `endFoo`, hence the one in `beginAnnotations` should likely be in a `endPageDrawing` but it can be a matter of taste.
I tried your suggestion, it works well and it avoids a bit of redundancy.
What do you prefer ?

**Comment by Snuffleupagus** [comment]
> I've the feeling that the "restore" code should be in `endFoo`, hence the one in `beginAnnotations` should likely be in a `endPageDrawing` but it can be a matter of taste.

That'd essentially require introducing a new *custom* operator, since we currently don't have a specific operator to signal "end of opList", which I'd generally suggest that we don't do unless absolutely necessary.

> I tried your suggestion, it works well and it avoids a bit of redundancy.
> What do you prefer ?

Indeed I thought that less code would be nice, and having it at the start of each individual `beginAnnotation`-call makes it very what's happening. Hence this option would be my preference :-)

**Review by Snuffleupagus — APPROVED** [review]

**Comment by ljhaust** [comment]
Can you tell me why it needs to be modified like this? Is it because this PDF doesn't comply with Adobe's specifications, so it requires these adjustments and modifications @calixteman
