### PR TITLE
Fallback to using the `name` table to infer the encoding for TrueType fonts missing such data (issue 15910)

### LINKED ISSUE #15910: Some ä are ‰ in the text layer
Attach (recommended) or Link to PDF file here:
[German-amyuni.pdf](https://github.com/mozilla/pdf.js/files/10381935/German-amyuni.pdf)

Configuration:
- Web browser and its version: Firefox nightly
- Operating system and its version: Windows 11

Steps to reproduce the problem:
1. Select all, copy and paste

What is the expected behavior? (copy/paste from Acrobat)
```
Allgäu Käferhofen 10
aufgeführte
gemäß
Amyuni PDF Creator 5.5.2.7 rev 10052 ActiveX - Copyright (c) 2001-2018, AMYUNI Technologies Inc.
http://www.amyuni.com
```

What went wrong? (copy/paste from Firefox)
```
K‰ferhofen 10Allg‰u
aufgeführte
gemäß
Amyuni PDF Creator 5.5.2.7 rev 10052 ActiveX - Copyright (c) 2001-2018, AMYUNI Technologies Inc.
http://www.amyuni.com
```

### PR DESCRIPTION
**Pull request by Snuffleupagus**
The relevant TrueType font is missing both /ToUnicode *and* /Encoding entires, either of which would have prevented the (current) broken textLayer rendering. My first idea was that we could use the `post` table in the TrueType font, see https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6post.html, to get the actual glyphNames and amend the fallback ToUnicode-map that way. Unfortunately that didn't work, since the `post` table only contained ".notdef" and "" (i.e. empty string) entries.

Instead we try to use the `name` table in the TrueType font, see https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6name.html, to determine if the platform is Windows and thus fallback to generate a ToUnicode-map from the `WinAnsiEncoding`.

### CODE REVIEW

File: src/core/fonts.js [hunk 1]
```diff
@@ -133,7 +134,53 @@ function adjustWidths(properties) {
...
+  if (!isSymbolicFont) {
+    return; // A non-symbolic font should default to `StandardEncoding`.
+  }
+
+  // Try to infer if the fallback encoding should really be `WinAnsiEncoding`.
+  if (properties.defaultEncoding === WinAnsiEncoding) {
+    return;
+  }
+  for (const r of nameRecords) {
+    if (!(r.platform === 3 && r.encoding === 1 && r.language === 0x409)) {
```
Comment (calixteman) [inline src/core/fonts.js:159]: nit: add a comment with https://learn.microsoft.com/en-us/typography/opentype/spec/name#windows-language-ids to explain the 0x409.

**Comment by Snuffleupagus** [comment]
Also, with these changes, it's not entirely clear to me if we actually need the TrueType-branch since for a Symbolic font we'll always overwrite the encoding with `MacRomanEncoding` just below!?
https://github.com/mozilla/pdf.js/blob/d8d5545e03d2c7a17b414a65684a745389f2a614/src/core/evaluator.js#L3488-L3494

File: src/core/fonts.js (hunk 1 above)
Comment (Snuffleupagus) [reply src/core/fonts.js:159]: Well, I was just copying from here: https://github.com/mozilla/pdf.js/blob/d8d5545e03d2c7a17b414a65684a745389f2a614/src/core/fonts.js#L2213-L2219

Comment (Snuffleupagus) [reply src/core/fonts.js]: I've added to two new helper functions, with documentation links.

File: src/core/fonts.js [hunk 2]
```diff
@@ -133,7 +134,56 @@ function adjustWidths(properties) {
...
+  }
+  if (!isSymbolicFont) {
+    return; // A non-symbolic font should default to `StandardEncoding`.
+  }
+  if (nameRecords.length === 0) {
+    return;
+  }
+
+  // Try to infer if the fallback encoding should really be `WinAnsiEncoding`.
+  if (properties.defaultEncoding === WinAnsiEncoding) {
```
Comment (calixteman) [inline src/core/fonts.js:158]: nit: I think it should be before the previous check.

Comment (Snuffleupagus) [reply src/core/fonts.js:158]: Well, I wrote it this way since it's not impossible to imagine that we'll need to extend this function sometime in the future to check for e.g. `MacRomanEncoding` as well. In that case, I believe that the current order makes more sense.

Also, please note that for TrueType fonts that have /ToUnicode or /Encoding data we'll break well before reaching these checks.

**Comment by calixteman** [comment]
> Also, with these changes, it's not entirely clear to me if we actually need the TrueType-branch since for a Symbolic font we'll always overwrite the encoding with `MacRomanEncoding` just below!?
> 
> https://github.com/mozilla/pdf.js/blob/d8d5545e03d2c7a17b414a65684a745389f2a614/src/core/evaluator.js#L3488-L3494

I don't know either and I don't have any opinions.

**Review by calixteman — APPROVED** [review]
LGTM. Thank you.
