### PR TITLE
Consider a ttf font with both Symbolic and Nonsymbolic flags set with a Differences array in the encoding dict as non-symbolic

### LINKED ISSUE #20232: [Bug]: Rendering specific characters
### Attach (recommended) or Link to PDF file

 [test.pdf](https://github.com/user-attachments/files/22140584/test.pdf)

### Web browser and its version

 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 YaBrowser/25.8.0.0 Safari/537.36

### Operating system and its version

Windows 11 PRO 24H2 26100.4946

### PDF.js version

5.4.149

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

Open attached file on https://mozilla.github.io/pdf.js/web/viewer.html in any browser

### What is the expected behavior?

Image

### What went wrong?

Image

### Link to a viewer

https://mozilla.github.io/pdf.js/web/viewer.html

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by calixteman**
It fixes #20232.

### CODE REVIEW

File: src/core/evaluator.js [hunk 1]
```diff
@@ -3663,6 +3663,21 @@ class PartialEvaluator {
     } else {
       const isSymbolicFont = !!(properties.flags & FontFlags.Symbolic);
       const isNonsymbolicFont = !!(properties.flags & FontFlags.Nonsymbolic);
+
+      // The PDF specs state that the flags Symbolic and Nonsymbolic must be
+      // mutually exclusive. However, some fonts are marked as both.
+      // In that case we ignore the Symbolic flag when there are a Differences
```
Comment (timvandermeij) [inline src/core/evaluator.js]: Nit: s/there are/there is

**Review by timvandermeij — APPROVED** [review]
r=me, with one (optional) comment and passing tests. Thanks!

File: test/pdfs/issue20232.pdf.link [hunk 2]
```diff
@@ -0,0 +1 @@
+https://github.com/user-attachments/files/22140584/test.pdf
```
Comment (timvandermeij) [inline test/pdfs/issue20232.pdf.link]: Since the file is called `test` and doesn't seem to contain much, I wonder if we can just use it as-is instead of as a linked test case? (In-repo PDFs are always a bit easier to deal with.)

**Review by timvandermeij — APPROVED** [review]
