### PR TITLE
Search for destinations in both /Names and /Dests dictionaries (issue 19474)

### LINKED ISSUE #19474: [Bug]: Destinations don't work in PDFs with a mix of named destinations via Root/Dests and Root/Names/Dests
### Attach (recommended) or Link to PDF file

[result.pdf](https://github.com/user-attachments/files/18765986/result.pdf)

### Web browser and its version

Firefix, 134.0.2

### Operating system and its version

Windows 10

### PDF.js version

v4.10.38

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open the PDF
2. Click on "A (via name object)" in the bookmark pane - nothing happens and you will find an error in the console (goToDestination: "null" is not a valid destination array, for dest="A"). Destination is defined in root/Dests dictionary.
3. Click on "B (via string object)" works as this destination can be found in the name tree (root/dests/names)
4. Click on "C (via name object)" - nothing happens + error in the console - same as 2.

The same issue is reproducable with link annotations on page 4.

### What is the expected behavior?

The destinations behind the names should be opened.

### What went wrong?

As soon as named destinations are defined in both (root/Dests and root/Names/Dests) pdf.js will only search in root/Names/Dests and will ignore root/Dests.

### Link to a viewer

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Currently we only use either one of them, preferring the NameTree when it's available.

### CODE REVIEW

File: test/unit/api_spec.js [hunk 1]
```diff
@@ -1320,6 +1333,15 @@ describe("api", function () {
       await loadingTask.destroy();
     });
 
+    it("gets a destination, from /Names (NameTree) respectively /Dests dictionary", async function () {
```
Comment (JanSlabon) [inline test/unit/api_spec.js:1336]: This test "only" accesses a sinlge destination in the /Dests entry of the root dictionary.

I would suggets to add another test, that access another destination which is resolved through the /Dests name tree of the /Names dictionary ("B") for completion.

**Review by calixteman — APPROVED** [review]
LGTM. Thank you.
