### PR TITLE
XFA - Return html element for the different possible value

### LINKED ISSUE #13536: HSBC XFA "Compte" field not pre-filled
Attach (recommended) or Link to PDF file here:
https://web.archive.org/web/20210607145115/https://www.hsbc.fr/content/dam/hsbc/fr/docs/pib/Contestation-Transaction-Carte-Bancaire.pdf
(in the test corpus)

What is the expected behavior? (add screenshot)
image

What went wrong? (add screenshot)
image

### PR DESCRIPTION
**Pull request by calixteman**
- it aims to fix #13536.

### CODE REVIEW

File: src/core/xfa/template.js [hunk 1]
```diff
@@ -615,7 +615,14 @@ class BooleanElement extends Option01 {
...
   [$toHTML](availableSpace) {
-    return HTMLResult.success(this[$content] === 1);
+    return HTMLResult.success({
+      name: "span",
+      attributes: {
+        class: ["xfaRich"],
+        style: {},
+      },
+      value: this[$content] === 1,
+    });
```
Comment (marco-c) [inline src/core/xfa/template.js:625]: this code is all very similar between the different objects, what if you moved it to a base class and made all classes inherit this method?
or even just extract the code to a method and call it in all places

File: src/core/xfa/template.js [hunk 2]
```diff
@@ -4782,12 +4820,20 @@ class Time extends StringObject {
   }
 
   [$finalize]() {
-    // TODO
-    this[$content] = new Date(this[$content]);
+    // TODO.
```
Comment (marco-c) [inline src/core/xfa/template.js:4823]: What's left TODO here?

**Review by marco-c — APPROVED** [review]
