### PR TITLE
Skip extra objects in object stream in using offsets

### LINKED ISSUE #13130: Rendering font error
Attach (recommended) or Link to PDF file here:  [test.pdf](https://akmer.aikucun.com/a94a8fe5ccb19ba61c4c0873d391e987982fbbd3_1616477914120_83.pdf)

Configuration:
- Web browser and its version: chrome 87.0.4280.88
- Operating system and its version: windows10
- PDF.js version: 2.6.347
- Is a browser extension:

Steps to reproduce the problem:
1. just open 

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
image

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### PR DESCRIPTION
**Pull request by calixteman**
It aims to fix #13130.

### CODE REVIEW

File: src/core/stream.js [hunk 1]
```diff
@@ -123,6 +123,7 @@ var Stream = (function StreamClosure() {
       this.start = this.pos;
     },
     makeSubStream: function Stream_makeSubStream(start, length, dict) {
+      length = length !== undefined ? length : this.bytes.buffer.length;
```
Comment (Snuffleupagus) [inline src/core/stream.js:126]: Can we please use more "consistent" formatting between the various `makeSubStream`-methods?
I.e. let's change this to the follow, since you also don't need to update the `length` when it's already set.
```suggestion
      if (length === undefined) {
        length = this.bytes.buffer.length;
      }
```

File: src/core/obj.js [hunk 2]
```diff
@@ -2172,10 +2173,25 @@ var XRef = (function XRefClosure() {
...
+        offsets[i] = offset;
       }
+
+      const start = (stream.start || 0) + first;
       const entries = new Array(n);
       // read stream objects for cache
       for (let i = 0; i < n; ++i) {
+        const length = i < n - 1 ? offsets[i + 1] - offsets[i] : undefined;
+        if (length < 0) {
+          throw new FormatError("invalid offset in the ObjStm stream");
```
Comment (Snuffleupagus) [inline src/core/obj.js:2185]: Nit: 
```suggestion
          throw new FormatError("Invalid offset in the ObjStm stream.");
```

File: src/core/obj.js [hunk 3]
```diff
@@ -2172,10 +2173,25 @@ var XRef = (function XRefClosure() {
...
+          lexer: new Lexer(
+            stream.makeSubStream(start + offsets[i], length, stream.dict)
+          ),
+          xref: this,
+          allowStreams: true,
+        });
+
         const obj = parser.getObj();
         entries[i] = obj;
         // The ObjStm should not contain 'endobj'. If it's present, skip over it
```
Comment (Snuffleupagus) [inline src/core/obj.js:2197]: This will obviously require testing, but given that you're now *replacing* the parser for each loop iteration my question is if the `endobj` special-case here still necessary with this patch?

File: test/pdfs/.gitignore [hunk 4]
```diff
@@ -36,6 +36,7 @@
 !issue7115.pdf
 !issue7180.pdf
 !issue7769.pdf
+!issue13130.pdf
```
Comment (Snuffleupagus) [inline test/pdfs/.gitignore:39]: This ought to be a `link`ed test-case instead, since it's not a reduced one (and the copyright situation is unclear).

File: test/test_manifest.json [hunk 5]
```diff
@@ -18,6 +18,12 @@
        "type": "eq",
        "renderTaskOnContinue": true
     },
+    {  "id": "issue13130",
+       "file": "pdfs/issue13130.pdf",
+       "md5": "318518299132fe3b52252ca43a69a23e",
+       "rounds": 1,
+       "type": "eq"
+    },
```
Comment (Snuffleupagus) [inline test/test_manifest.json:26]: You probably don't need to test *all* pages, hence adding `"firstPage": 2,` and `"lastPage": 2,` here would suffice as far as I can tell.

**Review by Snuffleupagus — COMMENTED** [review]
This looks reasonable, based on a cursory glance at the code, but I've not tested it yet :-)

I've added a couple of comments, but given the nature of the code I'd also like a little time to really think this through before signing off on it.

File: src/core/stream.js (hunk 1 above)
Comment (Snuffleupagus) [reply src/core/stream.js:126]: Actually, is it even necessary to handle the `length === undefined` case at all in *this* method?
Given that https://github.com/mozilla/pdf.js/blob/ba76dd4000c0efa570558dd56d551b773bb4e856/src/core/stream.js#L36 ought to assign a correct `this.end` value already, since `start + undefined === NaN` and we'd fallback to `this.bytes.length`.

File: src/core/obj.js (hunk 3 above)
Comment (calixteman) [reply src/core/obj.js:2197]: I looked into `bug1037816.pdf` and yes we have these `endobj` as  garbage at the end of the chunk.
So having a new Parser with the correct starting offset helps to skip those.
So it shouldn't be a regression to remove that stuff.

Comment (Snuffleupagus) [reply src/core/obj.js]: I've just tested all of the files listed in https://github.com/mozilla/pdf.js/blob/ba76dd4000c0efa570558dd56d551b773bb4e856/src/core/obj.js#L2182 and all of them still work fine with this code removed :-)

---

Can you please also change https://github.com/mozilla/pdf.js/blob/ba76dd4000c0efa570558dd56d551b773bb4e856/test/test_manifest.json#L2040 to an `eq` test instead, as part of this patch, since it's not generally *guaranteed* that just a `load` test catches all kind of /XRef-parsing errors?

**Review by Snuffleupagus — APPROVED** [review]
r=me, with the final comment addressed and all tests passing; thank you!

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you for fixing this!

/botio makeref
