### PR TITLE
Fix the default appearance of a Polygon annotation when a fill color is provided

### LINKED ISSUE #20062: [Bug]: PolygonAnnotation fill not rendered (only outline) in PDF.js web viewer, but works in Acrobat and Edge
### Attach (recommended) or Link to PDF file

[document.pdf](https://github.com/user-attachments/files/21099399/document.pdf)

### Web browser and its version

Edge-138.0.3351.65

### Operating system and its version

Win11- 26100.4349

### PDF.js version

5.3.93

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Create a PDF with a PolygonAnnotation that has both a stroke and a fill color (libraries(https://github.com/highkite/pdfAnnotate)).(The pdf uploaded)
2. Open the PDF in the PDF.js web viewer.
3. Observe that only the polygon's outline is visible, with no fill.
4. Open the same PDF in Acrobat or Edge and observe that the polygon is correctly filled.

### What is the expected behavior?

Expected behavior
The polygon annotation should be rendered with both its outline and fill color, consistent with Acrobat and Edge.
Acrobat:
Image
Edge:

Image

### What went wrong?

 When displaying a PDF containing PolygonAnnotation (with fill color) using the PDF.js web viewer, only the outline of the polygon is rendered. The fill color is missing. However, the same PDF displays correctly (with both fill and outline) in Adobe Acrobat and Microsoft Edge's built-in PDF viewer.

### Link to a viewer

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by calixteman**
It fixes #20062.

### CODE REVIEW

File: src/core/annotation.js [hunk 1]
```diff
@@ -4337,6 +4337,24 @@ class PolylineAnnotation extends MarkupAnnotation {
...
+      let fillColor = getRgbColor(dict.getArray("IC"), null);
+      if (fillColor) {
+        fillColor = getPdfColorArray(fillColor);
+      }
+
+      let operator;
+      if (fillColor) {
+        if (this.color) {
+          operator = fillColor.every((c, i) => c === strokeColor[i])
+            ? "F"
```
Comment (timvandermeij) [inline src/core/annotation.js]: According to https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf#page=143&zoom=auto,-219,769 we should probably replace `F` here and three lines below with `f` given the following paragraph about `F`:

```
Equivalent to f; included only for compatibility. Although PDF reader applications shall be able to accept this operator, PDF writer applications should use f instead.
```

**Review by timvandermeij — APPROVED** [review]
r=me, with the comment below addressed. Thank you for fixing this!
