### PR TITLE
[api-minor][Editor] Don't use the editor parent which can be null.

### LINKED ISSUE #15780: When annotaion exceeds 10 pages, print and download are abnormal
Attach (recommended) or Link to PDF file here: https://mozilla.github.io/pdf.js/legacy/web/viewer.html

Configuration:
- Web browser and its version: Google 版本 104.0.5112.79（正式版本） （64 位）
- Operating system and its version: linux
- PDF.js version: v3.0.279
- Is a browser extension:

Steps to reproduce the problem:
1. add annotation on page 1
2. add annotation on page 11
3. print

What is the expected behavior? (add screenshot)
print with annotation
What went wrong? (add screenshot)
report error：
editor.js:298 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'viewportBaseDimensions')
    at InkEditor.getRect (editor.js:298:53)
    at InkEditor.serialize (ink.js:1065:23)
    at get serializable [as serializable] (annotation_storage.js:168:47)
    at new PrintAnnotationStorage (annotation_storage.js:204:49)
    at get print [as print] (annotation_storage.js:153:12)
    at app.js:1683:52
    at async Promise.all (index 1)
image

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/legacy/web/viewer.html

### PR DESCRIPTION
**Pull request by calixteman**
An annotation editor layer can be destroyed when it's invisible, hence some
annotations can have a null parent but when printing/saving or when changing
font size, color, ... of all added annotations (when selected with ctrl+a) we
still need to have some parent properties especially the page dimensions, global
scale factor and global rotation angle.
This patch aims to remove all the references to the parent in the editor instances
except in some cases where an editor should obviously have one.
It fixes #15780.

### CODE REVIEW

File: test/integration/freetext_editor_spec.js [hunk 1]
```diff
@@ -512,4 +497,96 @@ describe("Editor", () => {
...
+
+            const annotationLayerSelector = `${pageSelector} > .annotationEditorLayer`;
+            await page.waitForSelector(annotationLayerSelector, {
+              visible: true,
+              timeout: 0,
+            });
+            await page.waitForTimeout(50);
+            if (![1, 14].includes(pageNumber)) {
+              continue;
+            }
```
Comment (Snuffleupagus) [inline test/integration/freetext_editor_spec.js:536]: Why are we skipping the first/last page here?

File: src/display/editor/editor.js [hunk 2]
```diff
@@ -92,6 +93,15 @@ class AnnotationEditor {
     this.div.style.zIndex = this.#zIndex;
   }
 
+  setParent(parent) {
+    if (parent === null) {
+      this._serialized = this.serialize();
```
Comment (Snuffleupagus) [inline src/display/editor/editor.js:98]: It might be overall safer to just do this unconditionally here, however it might not always be necessary?
Unless I'm misunderstanding things, looking at https://github.com/mozilla/pdf.js/blob/67e1c37e0fea06951ece8c457c2b39d2ee2a683f/src/display/editor/annotation_editor_layer.js#L285-L293 it seems that we'd really only need to "cache" the serializable data if the current editor actually exists in the annotationStorage?

File: src/display/editor/tools.js [hunk 3]
```diff
@@ -646,6 +695,18 @@ class AnnotationEditorUIManager {
...
 
+  getViewParameters() {
+    return this.#viewParameters;
+  }
+
+  getCurrentLayer() {
+    return this.#allLayers.get(this.#currentPageIndex);
+  }
+
+  getCurrentPageIndex() {
```
Comment (Snuffleupagus) [inline src/display/editor/tools.js:706]: Similarly, I'd prefer getters for these ones as well.

File: web/pdf_viewer.js [hunk 4]
```diff
@@ -730,7 +730,9 @@ class PDFViewer {
           } else if (isValidAnnotationEditorMode(mode)) {
             this.#annotationEditorUIManager = new AnnotationEditorUIManager(
               this.container,
-              this.eventBus
+              this.eventBus,
+              this.pdfDocument?.annotationStorage,
+              this.currentScale
```
Comment (Snuffleupagus) [inline web/pdf_viewer.js:735]: I suppose that there isn't a "simpler" way of obtaining the initial scale, inside of the editor code itself (e.g. using the `viewport`), without having to pass it in manually like this?

**Comment by Snuffleupagus** [comment]
Also, something that just occurred to me: Is this perhaps something that we want to try and uplift?
If so, would it make sense to land the previous (much smaller) patch first and then make the larger re-factoring later to mitigate risks?

**Comment by calixteman** [comment]
> Also, something that just occurred to me: Is this perhaps something that we want to try and uplift? If so, would it make sense to land the previous (much smaller) patch first and then make the larger re-factoring later to mitigate risks?

Good question, let me think (chat with @marco-c) about it.

File: src/display/editor/ink.js [hunk 5]
```diff
@@ -268,6 +268,22 @@ class InkEditor extends AnnotationEditor {
     super.remove();
   }
 
+  setParent(parent) {
+    if (!this.parent && parent) {
+      this._uiManager.removeScalingListener(this);
+    } else if (this.parent && parent === null) {
+      this._uiManager.addScalingListener(this);
+    }
```
[the remark this answers is not in the document]
Comment (calixteman) [reply src/display/editor/ink.js:276]: In the second case: the `ink` editor is removed from the view but it can be resized thanks to a zoom and when it's serialized we use the global scale factor:
https://github.com/mozilla/pdf.js/blob/c63906305055d27380ba2f94099a9fe9bb4c1017/src/display/editor/ink.js#L1081
And in the first case, the editor will be visible and will react to the scale changes (through the `ResizeObserver`).

[the remark this answers is not in the document]
Comment (Snuffleupagus) [reply src/display/editor/ink.js:276]: Maybe add a short comment describing those different cases?
The `ResizeObserver`-case wasn't immediately obvious, at least to me, when looking at this in isolation.

[the remark this answers is not in the document]
Comment (calixteman) [reply src/display/editor/ink.js:276]: Yep I was doing that.

**Review by Snuffleupagus — APPROVED** [review]
r=me, since I'm assuming that you've tested this carefully locally (given the amount of changes); thank you!
