### PR TITLE
Move the svg definitions in its own div

### LINKED ISSUE #16135: [Regression] The SVG-filters take up space at the bottom of the viewer
Attach (recommended) or Link to PDF file here: https://github.com/mozilla/pdf.js/blob/master/test/pdfs/issue6931_reduced.pdf

Configuration:
- Web browser and its version: Firefox Nightly 112
- Operating system and its version: Windows 11
- PDF.js version: 3.5.34 [a0ef5a4ae]
- Is a browser extension: N/A

Steps to reproduce the problem:
1. Load https://mozilla.github.io/pdf.js/web/viewer.html
2. Open `issue6931_reduced.pdf` in the demo viewer.

What is the expected behavior? (add screenshot)
That the `<svg>`-element for the filters doesn't take up any space in the viewer.

What went wrong? (add screenshot)
The `<svg>`-element is adding space at the bottom of the viewer, which breaks the scrollbar.
Please see the red marking in the following screen-shot:

filter

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): N/A

/cc @calixteman

### PR DESCRIPTION
**Pull request by calixteman**
This way the svg element doesn't take up space in the viewer. Fixes issue #16135.

### CODE REVIEW

File: src/display/display_utils.js [hunk 1]
```diff
@@ -67,14 +67,15 @@ class FilterFactory {
 
   get #defs() {
     if (!this.#_defs) {
+      const div = this.#document.createElement("div");
+      div.setAttribute("id", "svgDefinitions");
```
Comment (Snuffleupagus) [inline src/display/display_utils.js:71]: The `FilterFactory` functionality is exposed in the *general* API, hence a solution that requires the default viewer CSS-file in order to work unfortunately doesn't really work.
While it's not as nice, I do believe that you'll need to set the CSS rules inline here.

File: src/display/display_utils.js [hunk 2]
```diff
@@ -67,14 +67,23 @@ class FilterFactory {
...
```
Comment (Snuffleupagus) [inline src/display/display_utils.js:71]: With the CSS now being inlined, I don't believe that we need an `id` anymore and this line can probably just be removed.

**Review by Snuffleupagus — APPROVED** [review]
r=me, with one more suggestion; thank you!
