### PR TITLE
Add an option to enable/disable hardware acceleration (bug 1902012)

### LINKED ISSUE #18241: PDF freezes when opened with Firefox with HW Acceleration ON despite very powerful PC specs
Attach (recommended) or Link to PDF file here: 
[31) Statistica Inferenziale 6 + Prove d'ipotesi.pdf](https://github.com/user-attachments/files/15816166/31.Statistica.Inferenziale.6.%2B.Prove.d.ipotesi.pdf)

Configuration:
- Web browser and its version: FF 127 stable branch 64 bit
- Operating system and its version: Windows 11 Pro 23h2 (22631.3737) - Ryzen 7800x3d - 4070ti S - 32gb DDR5 6000mhz - 2TB nvme SSD
- PDF.js version: Don't know, whatever comes by default with FF127
- Is a browser extension: I've disabled them all

Steps to reproduce the problem:
1. open the pdf I sent with HW acceleration ON (you probably need to have same cpu/gpu, can't say for sure)
2. scroll down till the bottom
3. see it freeze like in my video 

What is the expected behavior? (add screenshot)
https://github.com/mozilla/pdf.js/assets/73554423/72143257-c0d3-43d0-bc66-bf22bb5ab225

What went wrong? (add screenshot)
https://github.com/mozilla/pdf.js/assets/73554423/2e01810f-865f-43fb-bebf-76bcfef37ba2

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

File: src/display/api.js [hunk 1]
```diff
@@ -213,6 +213,8 @@ const DefaultStandardFontDataFactory =
  *   when creating canvases. The default value is {new DOMCanvasFactory()}.
  * @property {Object} [filterFactory] - A factory instance that will be used
  *   to create SVG filters when rendering some images on the main canvas.
+ * @property {boolean} [enableHardwareAcceleration] - Enables hardware
```
Comment (Snuffleupagus) [inline src/display/api.js:216]: *Name bike-shedding:* Since HWA should be a well known acronym, how about using a slightly shorter name through this patch? 
```suggestion
 * @property {boolean} [enableHWA] - Enables hardware
```

File: src/display/base_factory.js [hunk 2]
```diff
@@ -46,10 +46,13 @@ class BaseFilterFactory {
 }
 
 class BaseCanvasFactory {
-  constructor() {
+  #enableHardwareAcceleration = false;
+
+  constructor(enableHardwareAcceleration = false) {
```
Comment (Snuffleupagus) [inline src/display/base_factory.js:51]: Please keep the constructor signatures consistent in the base- and extending-classes.
```suggestion
  constructor({ enableHardwareAcceleration = false }) {
```

File: web/app.js [hunk 3]
```diff
@@ -465,6 +465,7 @@ const PDFViewerApplication = {
       pageColors,
       mlManager: this.mlManager,
       abortSignal: this._globalAbortController.signal,
+      enableHardwareAcceleration: AppOptions.get("enableHardwareAcceleration"),
```
Comment (Snuffleupagus) [inline web/app.js:468]: Shouldn't the thumbnail viewer also use this parameter?

Comment (calixteman) [reply web/app.js:468]: Good question. I wondered the same and I checked on my mac, it's almost 6 times slower to disable hwa.
For this specific case, I think it's fine to send the image in the gpu: it's a very basic operation which should work well.
So I think we shouldn't disable hwa here, I know it feels a bit inconsistent but it's likely better. That said it's something we change in the future if it's too bad.

Comment (Snuffleupagus) [reply web/app.js]: Sorry to ask, but did you actually test the "right" thing?
Please note that the thumbnail viewer may also *render* pages from scratch, and not just downsize existing ones from `PDFViewer`, and in that particular case I'd assume that this option would help just as in the viewer itself.

Comment (calixteman) [reply web/app.js]: Good point: I just tested resizing. I'll update my patch.

File: src/display/api.js [hunk 4]
```diff
@@ -314,8 +316,9 @@ function getDocument(src) {
           standardFontDataUrl &&
           isValidFetchUrl(cMapUrl, document.baseURI) &&
           isValidFetchUrl(standardFontDataUrl, document.baseURI));
+  const enableHWA = src.enableHWA === true;
```
Comment (Snuffleupagus) [inline src/display/api.js:319]: Please move this line up, to e.g. *just after* this line:
https://github.com/mozilla/pdf.js/blob/341ff40e74259d304665efba997484f819ef2d0d/src/display/api.js#L299

Note that the parameters in this "list" are described by the following comment, which isn't really accurate for `enableHWA`:
https://github.com/mozilla/pdf.js/blob/341ff40e74259d304665efba997484f819ef2d0d/src/display/api.js#L301

File: web/app_options.js [hunk 5]
```diff
@@ -310,6 +310,11 @@ const defaultOptions = {
     value: "",
     kind: OptionKind.API,
   },
+  enableHWA: {
+    /** @type {boolean} */
+    value: false,
+    kind: OptionKind.API + OptionKind.PREFERENCE + OptionKind.VIEWER,
```
Comment (Snuffleupagus) [inline web/app_options.js:316]: Nit: Let's keep the preference kind last for overall consistent.
```suggestion
    kind: OptionKind.API + OptionKind.VIEWER + OptionKind.PREFERENCE,
```

File: web/pdf_page_view.js [hunk 6]
```diff
@@ -163,6 +167,7 @@ class PDFPageView {
     this.maxCanvasPixels =
       options.maxCanvasPixels ?? AppOptions.get("maxCanvasPixels");
     this.pageColors = options.pageColors || null;
+    this.#enableHWA = !!options.enableHWA;
```
Comment (Snuffleupagus) [inline web/pdf_page_view.js:170]: For consistency with the other viewer components:
```suggestion
    this.#enableHWA = options.enableHWA || false;;
```

File: src/display/node_utils.js [hunk 7]
```diff
@@ -117,6 +117,10 @@ const fetchData = function (url) {
 class NodeFilterFactory extends BaseFilterFactory {}
 
 class NodeCanvasFactory extends BaseCanvasFactory {
+  constructor(options = {}) {
+    super(options);
+  }
+
```
Comment (Snuffleupagus) [inline src/display/node_utils.js:123]: Do we still need this code now, or can we just remove this?
```suggestion
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, with the final comments addressed; thank you!

**Comment by qwer1304** [comment]
Why isn't the option exposed in Chrome's options?
("title": "Enable HW acceleration" is missing below line 48  in extensions/chromium/preferences_schema.json)

**Comment by Rob--W** [comment]
While disabling HWA unconditionally will certainly fix some issues associated with https://bugzilla.mozilla.org/show_bug.cgi?id=1902012, I wonder whether doing this unconditionally by default is the correct approach to take.

Do we have any data that shows that turning off HWA unconditionally is going to have a larger positive impact than the performance loss on systems where HWA outperforms software rendering?

Browsers usually have hardware blocklists to selectively disable HWA on systems that are known to have issues with HWA. Additionally, users can override the browser defaults, `chrome://flags/#disable-accelerated-2d-canvas` in Chrome, or `gfx.canvas.accelerated`=false in about:config in Firefox.

This patch does not only add an option to disable HWA, it already disables HWA in situations where the PDF.js code is expected to read back data, by specifying `willReadFrequently:true` unconditionally.

**Comment by calixteman** [comment]
@Rob--W, I wasn't so happy to disable hwa for the exact reasons you gave (and tbh I was pretty reluctant).
We've now some performance tests in m-c and I hope we'll have some numbers soon.
An other thing we could do is to create a Nimbus experiment to try measure if there are significant difference when rendering the first page for the different cohorts.

**Comment by Rob--W** [comment]
If there are doubts about disabling unconditionally, could we change the default to true (so that the use of HWA is controlled by the browser/user)? The mere existence of the setting now enables others to opt out if they want to deploy PDF.js in an environment where HWA is an issue.

PDF.js + HWA has been out in the wild for many years at this point, whereas HWA off is a new change here. I think that it would be lower risk to default to true (since it is the same as before), and then experiment with turning it off in cohorts. If that shows a noticeable performance difference, then the default can change.

**Comment by marco-c** [comment]
IIRC canvas acceleration has only been available recently in Firefox, so effectively it's only a short time HWA has been really enabled in Firefox.
I think we can quickly estimate the effects by running the perf tests and comparing, this will give us a good initial idea.

**Comment by Rob--W** [comment]
It's indeed relatively new, but not trivial either (1.5 years).

HWA canvas has been enabled on Linux+macOS since Firefox 110 (https://bugzilla.mozilla.org/show_bug.cgi?id=1806058), on Android since Firefox 113 (https://bugzilla.mozilla.org/show_bug.cgi?id=1825182). Interestingly, canvas HWA seems not enabled on Windows: https://searchfox.org/mozilla-central/rev/94f839e924ba6c69f3e0d062d4c6cc4fee7cad5b/modules/libpref/init/StaticPrefList.yaml#5706-5715

In Chrome, HWA canvas has been around for 12 years, judging by the announcement at https://developer.chrome.com/blog/taking-advantage-of-gpu-acceleration-in-the-2d-canvas/

If there is a desire to turn off HWA by default, I'd like it to be enabled by default in the Chrome extension (I can submit a patch), unless there is data that shows that HWA off-by-default offers a better experience.

> I think we can quickly estimate the effects by running the perf tests and comparing, this will give us a good initial idea.

Is this only in Firefox, or does it also cover other browser engines such as Chromium?

**Comment by qwer1304** [comment]
At least I can tell you that I've been having issues when HWA was turned off in pdf.js running in Chrome as listed in issue 18242. That's why I asked about making it a user controlled option in Chrome. After enabling it, the weird issues have gone away (for the meantime).
It's worth mentioning that it seems that the pdf.js option is NOT completely equivalent to the Chrome's flag option (chrome://flags/#disable-accelerated-2d-canvas), since I've been having issues even with the HWA disabled in Chrome whilst it was enabled in pdf.js. Only after enabling HWA in pdf.js have the issues gone away.
