### PR TITLE
Fix automatic zoom under spread mode

### LINKED ISSUE #12699: Automatic zoom not correct with odd or even spreads
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox nightly
- Operating system and its version: linux debian

Steps to reproduce the problem:
1. open https://mozilla.github.io/pdf.js/web/viewer.html 
2. set spread to odd or even and zoom to automatic

What is the expected behavior? (add screenshot)
image

What went wrong? (add screenshot)
image

### PR DESCRIPTION
**Pull request by calixteman**
Fixes #12699.

### CODE REVIEW

File: web/base_viewer.js [hunk 1]
```diff
@@ -1475,6 +1481,7 @@ class BaseViewer {
     }
     this._setCurrentPageNumber(pageNumber, /* resetCurrentPageView = */ true);
     this.update();
+    this._setScale(this._currentScaleValue, true);
```
Comment (Snuffleupagus) [inline web/base_viewer.js:1484]: Please do exactly that same as in https://github.com/mozilla/pdf.js/blob/d784af3f38d5604b653c06fb40a6fe6a021d45d3/web/base_viewer.js#L1412-L1416 here as well, since this call shouldn't be needed unconditionally!

File: web/base_viewer.js [hunk 2]
```diff
@@ -735,6 +735,11 @@ class BaseViewer {
       if (!currentPage) {
         return;
       }
+      const factor =
+        this.spreadMode === SpreadMode.NONE || this._isScrollModeHorizontal
+          ? 1
+          : 2;
```
Comment (Snuffleupagus) [inline web/base_viewer.js:741]: I don't believe that the above condition is correct in *all* situations, what about e.g. PresentationMode and/or the `PDFSinglePageViewer`?

To address all of this, let's add a new (private) getter above, and use that instead, e.g. something like:
```javascript
  /**
   * @private
   */
  get _pageWidthScaleFactor() {
    if (
      this.spreadMode !== SpreadMode.NONE &&
      this.scrollMode !== ScrollMode.HORIZONTAL &&
      !this.isInPresentationMode()
    ) {
      return 2;
    }
    return 1;
  }
```
and also the following dummy in `web/pdf_single_page_viewer.js`:
```javascript
  get _pageWidthScaleFactor() {
    return 1;
  }
```

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]

**Comment by timvandermeij** [comment]
Those commits look similar. Should they be squashed into one?

**Comment by calixteman** [comment]
> Those commits look related to each other. Should they be squashed into one?

Yes they can.

File: web/base_viewer.js [hunk 3]
```diff
@@ -1475,6 +1491,9 @@ class BaseViewer {
     }
     this._setCurrentPageNumber(pageNumber, /* resetCurrentPageView = */ true);
     this.update();
+    if (this._currentScaleValue && isNaN(this._currentScaleValue)) {
```
Comment (timvandermeij) [inline web/base_viewer.js:1494]: If I look at https://github.com/mozilla/pdf.js/blob/d784af3f38d5604b653c06fb40a6fe6a021d45d3/web/base_viewer.js#L1412-L1416 this happens _before_ `_setCurrentPageNumber` and `update`. Shouldn't that be done here as well?

**Review by timvandermeij — COMMENTED** [review]
Looks good to me with this final comment addressed.

File: web/base_viewer.js (hunk 3 above)
Comment (Snuffleupagus) [reply web/base_viewer.js:1494]: > Shouldn't that be done here as well?

That's correct, since otherwise there's a risk that the active page changes.

File: web/base_viewer.js [hunk 4]
```diff
@@ -735,6 +749,7 @@ class BaseViewer {
       if (!currentPage) {
         return;
       }
+
```
Comment (Snuffleupagus) [inline web/base_viewer.js:752]: Nit: Unrelated change, please revert.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you for fixing this!
