### PR TITLE
Fix types to make "gulp typestest" succeeding

### LINKED ISSUE #20616: [Feature]: Re-enable the types tests
### Is the feature relevant to the Firefox PDF Viewer?

No

### Feature description

In https://github.com/mozilla/pdf.js/pull/20607 we temporarily disabled the types tests. This issue tracks re-enabling it later, which would involve updating the various `@typedef` lines.

### Other PDF viewers

_No response_

### PR DESCRIPTION
**Pull request by calixteman**
Fixes #20616.

### CODE REVIEW

File: src/display/editor/annotation_editor_layer.js [hunk 1]
```diff
@@ -23,6 +23,7 @@
 /** @typedef {import("../draw_layer.js").DrawLayer} DrawLayer */
 // eslint-disable-next-line max-len
 /** @typedef {import("../src/display/struct_tree_layer_builder.js").StructTreeLayerBuilder} StructTreeLayerBuilder */
+/** @typedef {import("../../../web/l10n.js").L10n} L10n */
```
Comment (timvandermeij) [inline src/display/editor/annotation_editor_layer.js]: The line above this one points to `../src/display/struct_tree_layer_builder.js` but there is no `src` folder in the top-level folder that `..` refers to, and the struct tree builder lives in the `web/` folder instead. I assume that one is incorrect, and should be `../../../web/struct_tree_layer_builder.js` instead?

File: src/display/annotation_layer.js [hunk 2]
```diff
@@ -23,6 +23,10 @@
 /** @typedef {import("../../web/struct_tree_layer_builder.js").StructTreeLayerBuilder} StructTreeLayerBuilder */
 // eslint-disable-next-line max-len
 /** @typedef {import("../../web/comment_manager.js").CommentManager} CommentManager */
+// eslint-disable-next-line max-len
```
Comment (timvandermeij) [inline src/display/annotation_layer.js:26]: If `npx gulp typestest` passes again with these changes, please also undo the change from https://github.com/mozilla/pdf.js/commit/aa4d0f7c077e336b7fe4f93871159156de057710 in the scope of this MR to activate it again in the CI.

**Review by timvandermeij — APPROVED** [review]
r=me, with the comments addressed. Thanks!
