### PR TITLE
Fix error on empty response headers

### LINKED ISSUE #18957: [Bug]: pdfjs-dist not working in chrome
### Attach (recommended) or Link to PDF file

Every PDF

### Web browser and its version

Google Chrome: 130.0.6723.59

### Operating system and its version

macOS 15.0.1

### PDF.js version

pdfjs-dist: 4.7.76

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. use pdfjs-dist in a web-app as follows:
```ts
import * as pdfJS from 'pdfjs-dist';
pdfJS.GlobalWorkerOptions.workerSrc = window.location.origin + '/pdf.worker.min.js';

export default pdfJS;
```
2. build your own pdf viewer
3. open the web-app in chrome

### What is the expected behavior?

The file should be displayed correctly, like in safari.

### What went wrong?

```js
Uncaught TypeError: Failed to construct 'Headers': Invalid name
    at PDFNetworkStreamFullRequestReader._onHeadersReceived (pdfjs-dist.js?v=b25d4dee:10221:29)
    at NetworkManager.onStateChange (pdfjs-dist.js?v=b25d4dee:10109:22)
```

### Link to a viewer

_No response_

### Additional context

The error has only occurred since version 4.7.76. In version 4.6.82 everything works without errors.
Looks like the error occurred [here](https://github.com/mozilla/pdf.js/blob/master/src/display/network.js#L276-L285).

### PR DESCRIPTION
**Pull request by andriivitiv**
Fixes https://github.com/mozilla/pdf.js/issues/18957

https://github.com/mozilla/pdf.js/pull/18682 introduced a regression that causes the following error:

```
Uncaught TypeError: Failed to construct 'Headers': Invalid name
    at PDFNetworkStreamFullRequestReader._onHeadersReceived (pdf.mjs:10214:29)
    at NetworkManager.onStateChange (pdf.mjs:10103:22)
```

The mentioned PR replaced a call to `getResponseHeader()` with `getAllResponseHeaders()` without handling cases where it may return null or an empty string. Quote from the [docs](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/getAllResponseHeaders#return_value):

> Returns:
>
>A string representing all of the response's headers (except those whose field name is Set-Cookie) separated by CRLF, or null if no response has been received. If a network error happened, an empty string is returned.

## Reproduction steps

Run the following code and observe the error in the console. Note that the URL is intentionally set to an invalid value to simulate network error

```js
<script src="//mozilla.github.io/pdf.js/build/pdf.mjs" type="module"></script>

<script type="module">
  var url = 'blob:';

  pdfjsLib.GlobalWorkerOptions.workerSrc = '//mozilla.github.io/pdf.js/build/pdf.worker.mjs';

  var loadingTask = pdfjsLib.getDocument(url);
  loadingTask.promise
    .then((pdf) => console.log('PDF loaded'))
    .catch((reason) => console.error(reason));

</script>
```

### CODE REVIEW

File: src/display/network.js [hunk 1]
```diff
@@ -273,16 +273,17 @@ class PDFNetworkStreamFullRequestReader {
...
+    const responseHeadersMap = rawResponseHeaders
+      ? rawResponseHeaders
+          .trim()
+          .split(/[\r\n]+/)
+          .map(x => {
+            const [key, ...val] = x.split(": ");
+            return [key, val.join(": ")];
+          })
+      : [];
+    const responseHeaders = new Headers(responseHeadersMap);
```
Comment (Snuffleupagus) [inline src/display/network.js:286]: The name `responseHeadersMap` feels a little strange here, since it's not a `Map` but actually an `Array`.
Anyway, that temporary variable shouldn't be needed if this is just re-written as follows.
```suggestion
    const responseHeaders = new Headers(
      rawResponseHeaders
        ? rawResponseHeaders
            .trim()
            .split(/[\r\n]+/)
            .map(x => {
              const [key, ...val] = x.split(": ");
              return [key, val.join(": ")];
            })
        : []
    );
 ```

**Review by Snuffleupagus — COMMENTED** [review]
Please also include the information under `Reproduction steps`, from https://github.com/mozilla/pdf.js/pull/19010#issue-2636267539, in the *commit message* as well.

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you.
