### PR TITLE
Fix loca table when offsets aren't in ascending order.

### LINKED ISSUE #7074: Text not displaying at all, images are fine
I've tried multiple browsers and the latest version of pdf.js. The text in the PDF does not show at all, but images and shapes appear fine.

Here is the PDF:

[EE-Summer-2015-for-web Original.pdf](https://github.com/mozilla/pdf.js/files/164771/EE-Summer-2015-for-web.Original.pdf)

And a screenshot from the pdf.js example viewer:

screen shot 2016-03-09 at 08 56 27

The PDF as shown in Preview on a Mac:

screen shot 2016-03-09 at 08 56 41

Sorry that I don't have any insight at all at the moment! Please let me know if you need anything else.

Thanks,

Dan

### PR DESCRIPTION
**Pull request by brendandahl**
Fixes #7074 and #9263 

note: I shouldn't have pushed this branch to pdf.js, but it's there so I'll delete after.

### CODE REVIEW

File: src/core/fonts.js [hunk 1]
```diff
@@ -1759,6 +1759,11 @@ var Font = (function FontClosure() {
         var locaCount = dupFirstEntry ? numGlyphs - 1 : numGlyphs;
         for (i = 0, j = itemSize; i < locaCount; i++, j += itemSize) {
           var endOffset = itemDecode(locaData, j);
+          // The spec says the offsets should be in ascending order, however
+          // some fonts use the offset of 0 to mark a glyph as missing.
+          if (endOffset < startOffset) {
```
Comment (Snuffleupagus) [inline src/core/fonts.js]: Just from reading the comment above, I'd sort of expect this condition to read `if (endOffset === 0) {` instead, which seems like it would fix the issues without the regression (although I've not run tests).

Comment (brendandahl) [reply src/core/fonts.js]: I was hoping this would be a more general fix, but turns out there are other bad loca tables. In issue1257 it goes 598,74,74

**Review by Snuffleupagus — APPROVED** [review]
Looks good, thanks!
