### PR TITLE
Fix autolinking with highlighted search results

### LINKED ISSUE #19465: [Bug]: Auto-linking breaks when page is scrolled into view during searching
### Attach (recommended) or Link to PDF file

https://github.com/mozilla/pdf.js/blob/master/test/pdfs/issue3115r.pdf.link

### Web browser and its version

N/A

### Operating system and its version

N/A

### PDF.js version

`master`, or any version after PR #19110

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Load http://localhost:8888/web/viewer.html?file=/test/pdfs/issue3115r.pdf#disableHistory=true
2. Open the findbar.
3. Search for the string `rich.edu`.

### What is the expected behavior?

That auto-linking works as expected on page 22 (36 of 171).

### What went wrong?

Auto-linking breaks, with the following error:
```
renderView: DOMException: Index or size is negative or greater than the allowed amount
    createLinkAnnotation http://localhost:8888/web/autolinker.js:78
    processLinks http://localhost:8888/web/autolinker.js:132
    processLinks http://localhost:8888/web/autolinker.js:132
    resultPromise http://localhost:8888/web/pdf_page_view.js:1117
    draw http://localhost:8888/web/pdf_page_view.js:1099
    renderView http://localhost:8888/web/pdf_rendering_queue.js:196
    forceRendering http://localhost:8888/web/pdf_viewer.js:1849
    promise callback*forceRendering http://localhost:8888/web/pdf_viewer.js:1848
    renderHighestPriority http://localhost:8888/web/pdf_rendering_queue.js:79
    update http://localhost:8888/web/pdf_viewer.js:1677
    _scrollUpdate http://localhost:8888/web/pdf_viewer.js:1239
    viewAreaElementScrolled http://localhost:8888/web/ui_utils.js:153
    debounceScroll http://localhost:8888/web/ui_utils.js:138
    watchScroll http://localhost:8888/web/ui_utils.js:166
    PDFViewer http://localhost:8888/web/pdf_viewer.js:355
    _initializeViewerComponents http://localhost:8888/web/app.js:473
    initialize http://localhost:8888/web/app.js:257
    run http://localhost:8888/web/app.js:704
    webViewerLoad http://localhost:8888/web/viewer.js:294
    <anonymous> http://localhost:8888/web/viewer.js:305
pdf_rendering_queue.js:204:21

```

### Link to a viewer

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
> The current logic assumes that all spans in the text layer contain only one text node, and thus that the position information returned by `highlighter._convertMatches` can be directly used on the element's only child.
> 
> This is not true in case of highlighted search results: they will be injected in the DOM as `<span>` elements, causing the `<span>`s in the text layer to have more than one child.
>
> This patch fixes the problem by properly converting the (span, offset) pair in a (textNode, offset) pair that points to the right text node.

Fixes https://github.com/mozilla/pdf.js/issues/19465

### CODE REVIEW

File: test/integration/autolinker_spec.mjs [hunk 1]
```diff
@@ -178,4 +183,49 @@ describe("autolinker", function () {
...
+        null,
+        { enableAutoLinking: true }
+      );
+    });
+
+    afterAll(async () => {
+      await closePages(pages);
+    });
+
+    it("shuold work", async () => {
```
Comment (Snuffleupagus) [inline test/integration/autolinker_spec.mjs:204]: Spelling-nit :-)
```suggestion
    it("should work", async () => {
```

Comment (nicolo-ribaudo) [reply test/integration/autolinker_spec.mjs:204]: Whops

File: web/autolinker.js [hunk 2]
```diff
@@ -69,13 +69,55 @@ function calculateLinkPosition(range, pdfPageView) {
...
+      continue;
+    }
+
+    while (!currentContainer.nextSibling && currentContainer !== container) {
+      currentContainer = currentContainer.parentNode;
+    }
+    if (currentContainer !== container) {
+      currentContainer = currentContainer.nextSibling;
+    }
+  } while (currentContainer !== container);
```
Comment (Snuffleupagus) [inline web/autolinker.js:108]: Possibly a stupid question, but depending on the DOM structure could `currentContainer.parentNode === null` possibly happen and if so is that a situation that this code should handle?

Comment (nicolo-ribaudo) [reply web/autolinker.js:108]: All the nodes we visit here are descendans of `container`, so they all have a parent. We never exit out of `container`'s subtree because of the `currentContainer !== container` checks that we do when going "up towards the root" (`.parentNode`) and "right" (`.nextSibling`).

**Comment by nicolo-ribaudo** [comment]
I didn't see that failure locally, I'll check what it is.

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you.
