### PR TITLE
Refactor the toolbar html & css to improve its overall accessibility (bug 1171799, bug 1855695)

### LINKED ISSUE #9557: Tab order
Configuration:
- Web browser and its version: ALL
- Operating system and its version: ALL
- PDF.js version: Last

Steps to reproduce the problem:
1. In the HTML mark-up elements have tabindex attributs set to positive values.

Don't use positive tabindex values such as tabindex="10". By dynamic changes through JavaScript DOM manipulation such as showing and hideng contents, this coding causes inconsistancies and the keyboard focus does not move through the content as expected.

Inplement appropriate ARIA landmark roles to enable screen reader users and users of other ARIA browser add-ons to better navigate in the document content:
* set the role="main" on the parent element for the document content,
* Set the role="navigation" (or `<nav>` tag instead of `<div>`) for the parent element of the navigational toolbar with buttons Back, Forward, etc.

### PR DESCRIPTION
**Pull request by calixteman**
The first goal of this patch was to remove the tabindex because it helps to improve overall a11y. That led to move some html elements associated with the buttons which helped to position these elements relatively to their buttons.
Consequently it was easy to change the toolbar height (configurable in Firefox with the pref browser.uidensity): it's the second goal of this patch. For a11y reasons we want to be able to change the height of the toolbar to make the buttons larger.

### CODE REVIEW

File: web/pdf_find_bar.js [hunk 1]
```diff
@@ -25,8 +25,6 @@ const MATCHES_COUNT_LIMIT = 1000;
  * is done by PDFFindController.
  */
 class PDFFindBar {
-  #resizeObserver = new ResizeObserver(this.#resizeObserverCallback.bind(this));
```
Comment (Snuffleupagus) [inline web/pdf_find_bar.js:28]: If this is being removed, then https://github.com/mozilla/pdf.js/blob/790470c1aadf4dc6c4e8ff00364b87ecea4d7bd7/web/app.js#L2132 is probably unnecessary.

File: web/viewer.css [hunk 2]
```diff
@@ -321,31 +327,45 @@ body {
...
-  cursor: default;
-  font: message-box;
-}
-
-:is(.toolbar, .editorParamsToolbar, .findbar, #sidebarContainer)
-  :is(input, button, select),
-.secondaryToolbar :is(input, button, a, select) {
-  outline: none;
+#sidebarContainer :is(input, button, select) {
+  /*outline: none;*/
```
Comment (Snuffleupagus) [inline web/viewer.css:331]: This should either be uncommented, or the line removed if it's actually unnecessary.

File: web/viewer.css [hunk 3]
```diff
@@ -1103,18 +647,15 @@ a:is(.toolbarButton, .secondaryToolbarButton)[href="#"] {
...
-  margin-inline-start: 7px;
+  &:focus {
+    border-color: #0a84ff;
+  }
 }
 
 #pageNumber {
-  -moz-appearance: textfield; /* hides the spinner in moz */
+  -moz-appearance: textfield;
+  /* hides the spinner in moz */
```
Comment (Snuffleupagus) [inline web/viewer.css:658]: Look unrelated, please revert.

File: web/viewer.css [hunk 4]
```diff
@@ -1379,47 +912,56 @@ dialog :link {
...
+
 .grab-to-pan-grabbing {
   position: fixed;
   background: rgb(0 0 0 / 0);
   display: block;
   inset: 0;
   overflow: hidden;
-  z-index: 50000; /* should be higher than anything else in PDF.js! */
+  z-index: 50000;
+  /* should be higher than anything else in PDF.js! */
```
Comment (Snuffleupagus) [inline web/viewer.css:964]: Look unrelated, please revert.

File: web/toolbar.js [hunk 5]
```diff
@@ -270,10 +273,17 @@ class Toolbar {
     );
 
     const isDisable = mode === AnnotationEditorType.DISABLE;
-    editorFreeTextButton.disabled = isDisable;
-    editorHighlightButton.disabled = isDisable;
-    editorInkButton.disabled = isDisable;
-    editorStampButton.disabled = isDisable;
+    if (isDisable) {
```
Comment (timvandermeij) [inline web/toolbar.js:276]: Looking at https://developer.mozilla.org/en-US/docs/Web/API/Element/toggleAttribute#examples could we perhaps simplify this by using `toggleAttribute`?

Comment (calixteman) [reply web/toolbar.js:276]: I didn't know this function.

File: web/ui_utils.js [hunk 6]
```diff
@@ -851,6 +851,9 @@ function apiPageModeToSidebarView(mode) {
 function toggleCheckedBtn(button, toggle, view = null) {
   button.classList.toggle("toggled", toggle);
   button.setAttribute("aria-checked", toggle);
+  if (button.parentElement.classList.contains("toolbarButtonWithContainer")) {
+    button.setAttribute("aria-expanded", toggle);
+  }
```
Comment (Snuffleupagus) [inline web/ui_utils.js:856]: Why is this necessary, since it feels like you're now "mixing" the `toggleCheckedBtn` and `toggleExpandedBtn` helper functions?

Also, having the query the DOM this way feels somewhat unfortunately and potentially brittle as well.

Comment (calixteman) [reply web/ui_utils.js:856]: Right, maybe using toggleExpandedBtn is the right thing to do here. I didn't change that in this patch so it's a pre-exisiting bug.

**Comment by Snuffleupagus** [comment]
A couple of quick observations, with `master` on the left and this patch on the right, see also the markings in the image attached below:
 - The sidebar buttons are now (a lot) larger than the other buttons.
 - The toolbar bottom border is too dark when the sidebar is open.
 - The toolbar bottom border is no longer visible where it "meets" the pages of the document.



Other observations, with `master` on the left and this patch on the right, see also the markings in the image attached below:
 - There's less horizontal space around the toolbar separators, is this intentional?
 - The secondaryToolbar, also applies to the findbar and the editorToolbars, now longer have an outlined "arrow" which means that it blends in with the document.

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]
*Unfortunately there's still a number of (easily) spotted issues here:*

 - The findbar resizing looks *really bad* with a lot of wasted space, please revert those changes!
   Quite frankly this doesn't belong in this PR, and generally speaking if a CSS-only solution cannot be made to work/look as good as the current solution then we need to keep the JS-code.
 - All dropdown menus seem to be slightly off *horizontally*. The screen-shot shows the findbar, but the secondaryToolbar and the editing-toolbars are similarly affected.

findbar

---

 - The dropdown-arrows still don't have an outline all around; note the right-hand side in the (zoomed in) screen-shot below.

dropdown

---

 - There's no longer any visible separators in the secondaryToolbar.

separators

**Comment by calixteman** [comment]
About the separators on the secondary toolbar, it's a pre-existing bug.
The color of the separator depends on its position, a way to see it (at least for me), is to add `position: relative; top: 1px` and increase the `top` in devtools: I can see the color of the changing. It's probably why I can see it but you can't.
I'll fix it (I think I've a fix).

**Comment by Snuffleupagus** [comment]
It seems that when the findbar resizes the height of the match-counter DOM-element changes, which looks a little bit strange; see the following screen-shots.
 - When the viewer is large large
 - When the viewer is small small

**Comment by Snuffleupagus** [comment]
It seems that the `loadingBar` is now placed slightly higher up than before, with the computed `top`-value being 30px with the patch vs 32px in master, meaning that it basically "touches" the toolbar-buttons which looks a little strange.

**Comment by Snuffleupagus** [comment]
This patch breaks the `indeterminate` loadingBar animation, since it no longer moves at all; can be reproduced e.g. by running the following code in the console:
```
PDFViewerApplication.loadingBar.percent = NaN;
PDFViewerApplication.loadingBar.show(); 
```

File: web/viewer.html [hunk 7]
```diff
@@ -421,6 +238,211 @@
...
+                          <span class="editorParamsLabel" data-l10n-id="pdfjs-editor-stamp-add-image-button-label">Add image</span>
+                        </button>
+                      </div>
+                    </div>
+                  </div>
+                </div>
+
+                <div id="editorModeSeparator" class="verticalToolbarSeparator"></div>
+
+                <div id="printDownloadButtons" class="toolbarHorizontalGroup hiddenMediumView">
```
Comment (Snuffleupagus) [inline web/viewer.html:322]: Nit: Is this `id` actually used for anything?

File: web/viewer.html [hunk 8]
```diff
@@ -644,7 +666,7 @@
               <button id="altTextSettingsCloseButton" type="button" class="primaryButton" tabindex="0"><span data-l10n-id="pdfjs-editor-alt-text-settings-close-button">Close</span></button>
             </div>
           </div>
-        </dialog>
+        </dialog>
```
Comment (Snuffleupagus) [inline web/viewer.html:669]: Please remove the trailing spaces.
```suggestion
        </dialog>
```

File: web/viewer.html [hunk 9]
```diff
@@ -421,6 +238,211 @@
...
+
+                <div class="verticalToolbarSeparator hiddenMediumView"></div>
+
+                <div id="secondaryToolbarToggle" class="toolbarButtonWithContainer">
+                  <button id="secondaryToolbarToggleButton" class="toolbarButton" type="button" title="Tools" tabindex="0" data-l10n-id="pdfjs-tools-button" aria-expanded="false" aria-haspopup="true" aria-controls="secondaryToolbar">
+                    <span data-l10n-id="pdfjs-tools-button-label">Tools</span>
+                  </button>
+                  <div id="secondaryToolbar" class="hidden doorHangerRight">
+                    <div id="secondaryToolbarButtonContainer" class="menuContainer">
+          <!--#if GENERIC-->
```
Comment (Snuffleupagus) [inline web/viewer.html:340]: Here, and elsewhere below, these kind of (old) pre-processor statements don't actually work correctly if there's leading spaces on the lines.
(Note that these comments are still present in the *built* `viewer.html` file, which is how I noticed this.)
```suggestion
<!--#if GENERIC-->
```

File: web/viewer.html [hunk 10]
```diff
@@ -421,6 +238,211 @@
...
+                      <button id="secondaryOpenFile" class="toolbarButton labeled" type="button" title="Open File" tabindex="0" data-l10n-id="pdfjs-open-file-button">
+                        <span data-l10n-id="pdfjs-open-file-button-label">Open</span>
+                      </button>
+          <!--#endif-->
```
Comment (Snuffleupagus) [inline web/viewer.html:344]:
```suggestion
<!--#endif-->
```

File: web/viewer.html [hunk 11]
```diff
@@ -421,6 +238,211 @@
...
+                          <span data-l10n-id="pdfjs-print-button-label">Print</span>
+                        </button>
+
+                        <button id="secondaryDownload" class="toolbarButton labeled" type="button" title="Save" tabindex="0" data-l10n-id="pdfjs-save-button">
+                          <span data-l10n-id="pdfjs-save-button-label">Save</span>
+                        </button>
+
+          <!--#if !GENERIC-->
+          <!--            <div class="horizontalToolbarSeparator"></div>-->
+          <!--#endif-->
```
Comment (Snuffleupagus) [inline web/viewer.html:357]:
```suggestion
<!--#if !GENERIC-->
<!--                      <div class="horizontalToolbarSeparator"></div>-->
<!--#endif-->
```

File: web/viewer.html [hunk 12]
```diff
@@ -421,6 +238,211 @@
...
+                      </div>
+
+          <!--#if GENERIC-->
```
Comment (Snuffleupagus) [inline web/viewer.html:360]:
```suggestion
<!--#if GENERIC-->
```

File: web/viewer.html [hunk 13]
```diff
@@ -421,6 +238,211 @@
...
+                      <div class="horizontalToolbarSeparator"></div>
+          <!--#endif-->
```
Comment (Snuffleupagus) [inline web/viewer.html:362]:
```suggestion
<!--#endif-->
```

**Review by Snuffleupagus — COMMENTED** [review]
I've not yet looked at the CSS changes (will try to do that tomorrow), but leaving a few comments based on an initial look at the code.

Additionally, there's also the inconsistencies/bugs found in:
 - https://github.com/mozilla/pdf.js/pull/18385#issuecomment-2364558863
 - https://github.com/mozilla/pdf.js/pull/18385#issuecomment-2364604528
 - https://github.com/mozilla/pdf.js/pull/18385#issuecomment-2364609505

File: web/viewer.css [hunk 14]
```diff
@@ -1371,208 +1077,650 @@ dialog :link {
...
+      .glimmer {
+        @keyframes progressIndeterminate {
+          0% {
+            transform: translateX(calc(-142px * var(--dir-factor)));
+          }
+
+          100% {
+            transform: translateX(0);
+          }
+        }
```
Comment (Snuffleupagus) [inline web/viewer.css:1639]: It *seems* that `@keyframes` definitions perhaps cannot be nested like this, since moving it back to the "top level" as before fixes the animation.

**Review by Snuffleupagus — COMMENTED** [review]
*I've left additional comments, and also found one more regression.*

The `currentOutlineItem`-button is "broken" now, since it's both too small and incorrectly positioned.
Also, the separator (i.e. a `.verticalToolbarSeparator` element) that is placed before the button is no longer visible.
   
currentOutlineItem

File: web/viewer.css [hunk 15]
```diff
@@ -1371,208 +1077,650 @@ dialog :link {
...
+      transform-origin: calc(50% - 50% * var(--dir-factor)) 0;
+      height: 100%;
+      background-color: var(--progressBar-color);
+      overflow: hidden;
+      transition: transform 200ms;
+    }
+
+    &.indeterminate .progress {
+      transform: none;
+      background-color: var(--progressBar-blend-color);
```
[the remark this answers is not in the document]
Comment (calixteman) [reply web/viewer.css:1627]: I've absolutly no idea about how/why this line has been changed...

File: web/viewer.css [hunk 16]
```diff
@@ -1217,76 +983,16 @@ dialog :link {
...
-      color: var(--doorhanger-hover-color);
-    }
-
-    > span {
-      display: unset;
-      padding-inline-end: 4px;
-    }
-  }
-}
-
```
[the remark this answers is not in the document]
Comment (calixteman) [reply web/viewer.css:1262]: That's a fair point. Most of the time, the css has been moved under their parent.
I didn't move everything, some `x { ...} x {...}` are still there, I kept myself from moving everything and I tried to just move the stuff which was under the toolbar.
So I moved back toolbarButton and few others.

File: web/viewer.css [hunk 17]
```diff
@@ -1372,129 +1271,110 @@ dialog :link {
...
       width: 200px;
+      padding: 5px var(--input-horizontal-padding);
 
       /*#if !MOZCENTRAL*/
       &::-webkit-input-placeholder {
         color: rgb(191 191 191);
       }
-      /*#endif*/
 
+      /*#endif*/
```
Comment (Snuffleupagus) [inline web/viewer.css:1316]: Please move this line back up.

File: web/viewer.css [hunk 18]
```diff
@@ -1372,129 +1271,110 @@ dialog :link {
...
+      padding-block: 4px;
+
+      &:empty {
+        display: none;
+      }
+    }
+
+    &:has(> :is(#findResultsCount, #findMsg):not(:empty)) {
+      display: inline flex;
     }
```
Comment (Snuffleupagus) [inline web/viewer.css:1349]: Nit: Rather than placing this rule "between" the `#findResultsCount` and `#findMsg` blocks, can we please move it either before or after instead?

**Review by Snuffleupagus — APPROVED** [review]
This looks a lot better now, compared to the initial version(s) of the patch, and there's no longer any *immediately* obvious regressions present in the preview.
Let's try to land this, although I fully expect that follow-up patches will be necessary once more testing is done.

r=me, thank you.

File: web/viewer.css (hunk 17 above)
Comment (calixteman) [reply web/viewer.css:1316]: pfff... I'll fix the preprocessor and/or add a linting rule but it's painful (the same for the html).

**Comment by Snuffleupagus** [comment]
One more thing: The `viewBookmark` button now has a "pointer"-cursor, rather than the "default"-cursor used by all other secondaryToolbar buttons.

**Comment by Snuffleupagus** [comment]
> The last version I just pushed fix the color of the icons and the height of the menu items when the text is on two lines (visible with locale=it) in the secondary toolbar.

Good catch, however that seems to be a slight change when compared to `master` and I don't know if this is intended?
Now the icon is vertically centred on the secondaryToolbar-button, whereas previously it had the same offset from the top of the secondaryToolbar-button regardless of how many lines the text is broken onto.

**Comment by marco-c** [comment]
> > The last version I just pushed fix the color of the icons and the height of the menu items when the text is on two lines (visible with locale=it) in the secondary toolbar.
> 
> Good catch, however there still seems to be a slight change when compared to `master` and I don't know if this is intended? Now the icon is vertically centred on the secondaryToolbar-button, whereas previously it had the same offset from the top of the secondaryToolbar-button regardless of how many lines the text is broken onto.

Personally I find the behavior after the patch to be nicer than the behavior before the patch.

**Comment by calixteman** [comment]
From my point of view, vertically centering icons is the right thing to do, because when I look everywhere around me (github ui, devtools ui, files explorer in Windows, ...) the icons are centered.

**Review by timvandermeij — APPROVED** [review]
I also think that overall this is an improvement, and the increased usage of CSS nesting should improve maintainability and make future changes safer. I haven't had time to look through all code changes, but I haven't found anything that stood out from a cursory look, and mainly focused on comparing and testing the preview viewer. I only have two observations, which may or may not be intended (so feel free to disregard them). Thank you for all your work on this patch!

1. The "Text not found" label feels a bit close to the border of the findbar when the viewport is small; previously it had more padding which felt a bit more consistent because the padding between the buttons and the labels was equal. Compare the following screenshots from before/after this patch:

afbeelding afbeelding

2. The icons in the secondary toolbar are more gray than before. Compare the following screenshots from before/after this patch (this is better visible when opening the old/new viewers in two tabs, opening the secondary toolbar in both and switching between the tabs):

afbeelding afbeelding

**Comment by calixteman** [comment]
@timvandermeij, did you try with the last build ?
because for me the colors of the icons are exactly the same in both viewers.

About the `Text not found` thing I'll fix it.

File: web/viewer.css [hunk 19]
```diff
@@ -1559,13 +1453,261 @@ dialog :link {
...
-    margin: auto;
-    left: auto;
-    position: inherit;
-    transform: none;
+.toolbarLabel {
+  width: max-content;
+  min-width: 16px;
+  height: 100%;
+  padding-inline: 4px;
+  margin-inline: 4px;
```
Comment (Snuffleupagus) [inline web/viewer.css:1461]: This was changed in the latest update, related to https://github.com/mozilla/pdf.js/pull/18385#issuecomment-2369296425, however that also affects the positioning e.g. the `numPages` label and potentially *other* elements as well.
Maybe that shouldn't be changed unconditionally like this, but only for elements in the findbar?
