### PR TITLE
Add the possibility to copy all the pdf text whatever the rendered pages are (bug 1788035)

### LINKED ISSUE #1995: select all (ctrl + a) should attach only content
actual result by press Ctrl+A to select all content 

http://www.abload.de/img/1pcs45.png

### LINKED ISSUE #13317: Add some integration tests to check that copied & pasted text is correct.
See https://github.com/mozilla/pdf.js/pull/13257#pullrequestreview-648550425

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

File: web/pdf_viewer.js [hunk 1]
```diff
@@ -82,6 +82,8 @@ function isValidAnnotationEditorMode(mode) {
  * @typedef {Object} PDFViewerOptions
  * @property {HTMLDivElement} container - The container for the viewer element.
  * @property {HTMLDivElement} [viewer] - The viewer element.
+ * @property {HTMLDivElement} [hiddenElement] - The hidden element used to check
```
Comment (Snuffleupagus) [inline web/pdf_viewer.js:85]: Here, and elsewhere, should we perhaps name this e.g. `copyElement` instead to more clearly indicate its actual use?

File: web/viewer.css [hunk 2]
```diff
@@ -224,6 +224,15 @@ body {
...
 
+#hiddenElement {
+  position: absolute;
+  top: 0;
+  left: 0;
+  width: 0;
+  height: 0;
+  display: none;
+}
+
```
Comment (Snuffleupagus) [inline web/viewer.css:235]: *The comment above applies here as well.*

**Review by Snuffleupagus — COMMENTED** [review]
A couple of the review comments regard performance in very long PDF document, and a related question is if we perhaps need a way for the user to cancel the text-extraction (e.g. with <kbd>Esc</kbd>) if it's slow?
(Possibly we can defer that until later though, since people will hopefully not try to copy all of the PDF specification.)

Does this perhaps also fix the remaining part of issue #1995?

**Comment by timvandermeij** [comment]
Note that the copy/paste integration tests alone might already fix #13317 and in general seem like a very good idea to have, so if we don't end up merging this functionality in itself (for example if performance concerns are too big) those tests can still be landed in a separate PR as far as I can tell. Nice work!

File: web/pdf_viewer.js [hunk 3]
```diff
@@ -638,6 +649,94 @@ class PDFViewer {
...
+
+      this.getAllText()
+        .then(async text => {
+          if (text !== null) {
+            try {
+              await navigator.clipboard.writeText(text);
+            } catch (e) {
+              console.warn(`Cannot write data in clipboard: ${e.message}.`);
+            }
+          }
```
Comment (Snuffleupagus) [inline web/pdf_viewer.js:721]: Maybe just handle the error in the new `catch`-handler below, to reduce some duplication?
```suggestion
          if (text !== null) {
            await navigator.clipboard.writeText(text);
          }
```

File: web/pdf_viewer.js [hunk 4]
```diff
@@ -638,6 +649,94 @@ class PDFViewer {
...
+        })
+        .catch(reason => {
+          console.warning(
```
Comment (Snuffleupagus) [inline web/pdf_viewer.js:724]:
```suggestion
          console.warn(
```

File: web/pdf_viewer.js [hunk 5]
```diff
@@ -661,6 +760,7 @@ class PDFViewer {
     if (!pdfDocument) {
       return;
     }
+
```
Comment (Snuffleupagus) [inline web/pdf_viewer.js:763]: Nit: Unrelated change.

File: web/pdf_viewer.js [hunk 6]
```diff
@@ -872,6 +972,10 @@ class PDFViewer {
         if (this.defaultRenderingQueue) {
           this.update();
         }
+
+        if (this.#hiddenCopyElement) {
+          document.addEventListener("copy", this.#copyCallbackBound);
+        }
```
Comment (Snuffleupagus) [inline web/pdf_viewer.js:978]: Sorry, but isn't this still too early since no page has rendered yet?

I think that the "correct" spot would be *after* this code instead: https://github.com/mozilla/pdf.js/pull/16286/files#diff-4238fc7e96d72f4095859850f3d24a9298ec2dc8bd96437214a02dccbd48385cR905-R914

Comment (calixteman) [reply web/pdf_viewer.js:978]: I just picked up the wrong `}`. Thank you for noticing that.

**Review by Snuffleupagus — APPROVED** [review]
r=me, with passing tests; thank you!

**Comment by calixteman** [comment]
It works locally of course... Maybe ctrl+c is coming too quickly after ctrl+a.
/botio integrationtest

**Comment by calixteman** [comment]
So it worked (on linux at least) in increasing the time to wait to 500ms. I hope it isn't a new potential intermittent...
