### PR TITLE
Ensure that we cancel any pending rendering operations when the viewer is closed (issue 7274)

### LINKED ISSUE #7274: "TypeError: pageView is undefined" during pdf.js tests
Noticed when looking at Treeherder logs.
http://archive.mozilla.org/pub/firefox/try-builds/ryanvm@gmail.com-bfecb53c1626b14dab001068ddfe3fd686854802/try-linux64/try_ubuntu64_vm_test-mochitest-e10s-browser-chrome-1-bm54-tests1-linux64-build223.txt.gz

INFO -  JavaScript error: resource://pdf.js/web/viewer.js, line 8148: TypeError: pageView is undefined

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Tentative PR that fixes #7274.

@yurydelendik r?

---

This change is [Reviewable](https://reviewable.io/reviews/mozilla/pdf.js/7514)

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
@yurydelendik Review ping?

**Comment by Snuffleupagus** [comment]
@yurydelendik Review ping?

/botio-linux preview

File: web/pdf_page_view.js [hunk 1]
```diff
@@ -320,6 +331,7 @@ var PDFPageView = (function PDFPageViewClosure() {
     draw: function PDFPageView_draw() {
       if (this.renderingState !== RenderingStates.INITIAL) {
         console.error('Must be in new state before drawing');
+        return Promise.resolve(undefined);
```
Comment (yurydelendik) [inline web/pdf_page_view.js]: This has a little bit weird meaning, can we replace it with reject or cache the promise returned below?

File: web/pdf_thumbnail_viewer.js [hunk 2]
```diff
@@ -135,15 +135,16 @@ var PDFThumbnailViewer = (function PDFThumbnailViewerClosure() {
       this.thumbnails = [];
       this._pagesRotation = 0;
       this._pagesRequests = [];
+
+      var container = this.container;
+      while (container.hasChildNodes()) {
```
Comment (yurydelendik) [inline web/pdf_thumbnail_viewer.js]: `this.container.textContent = '';` -- I think it will be easier to read (we can prefix it with the comment about the intent)

**Review by yurydelendik — CHANGES_REQUESTED** [review]
Looks good after comments are addressed. Thanks

File: web/pdf_page_view.js (hunk 1 above)
Comment (Snuffleupagus) [inline web/pdf_page_view.js]: I was simply trying to bring this code in line with the existing code in `PDFThumbnailView`, please see https://github.com/mozilla/pdf.js/blob/master/web/pdf_thumbnail_view.js#L277.
Do you want me to change both of them to e.g. `Promise.reject(...)` instead?

File: web/pdf_thumbnail_viewer.js (hunk 2 above)
Comment (Snuffleupagus) [inline web/pdf_thumbnail_viewer.js]: Similar to the above, I was trying to make this be the same as the existing code in `PDFViewer`, please see https://github.com/mozilla/pdf.js/blob/master/web/pdf_viewer.js#L419.
Do you want both of those files changed here?

Comment (yurydelendik) [inline web/pdf_thumbnail_viewer.js]: Yeah, let's change both here.

File: web/pdf_page_view.js (hunk 1 above)
Comment (yurydelendik) [inline web/pdf_page_view.js]: I see. Not sure if we want to change both. For pages, we fall through to start new rendering (e.g. for different scale). For thumbs, we don't care about scale or if image is set after page rendering. Maybe we just leave it without change, just add comments for intent? Or, we reject in both cases, it try to catch places when we are failing during testing?

File: web/pdf_thumbnail_viewer.js (hunk 2 above)
Comment (Snuffleupagus) [inline web/pdf_thumbnail_viewer.js]: I've updated both files.

File: web/pdf_page_view.js (hunk 1 above)
Comment (Snuffleupagus) [inline web/pdf_page_view.js]: > Not sure if we want to change both. For pages, we fall through to start new rendering (e.g. for different scale). For thumbs, we don't care about scale or if image is set after page rendering.

Really good point about the differences between pages/thumbnails! After thinking about this, I'm no longer sure that we want to make too many functionaly changes here.

The only change I've made in the updated patch, is to add a `this.reset();` call for the `PDFPageView` case, since I think that we should ensure that we reset various state on fall-through.
Please do let me know if you don't think this is appropriate!

File: web/app.js [hunk 3]
```diff
@@ -1626,18 +1632,8 @@ function webViewerPageRendered(e) {
...
 
 function webViewerTextLayerRendered(e) {
-  var pageIndex = e.pageNumber - 1;
-  var pageView = PDFViewerApplication.pdfViewer.getPageView(pageIndex);
-
-//#if !PRODUCTION
-  if (true) {
-    return;
-  }
-//#endif
```
Comment (yurydelendik) [inline web/app.js]: We need to keep this if to preserve functionality in the non-build viewer

**Review by yurydelendik — APPROVED** [review]
Looks good. Can you revert change with `!PRODUCTION`? I'll refactor that later.

**Comment by timvandermeij** [comment]
Merging with r=yurydelendik. Thank you for the patch!
