### PR TITLE
Make the toolbar buttons usable with keyboard when Page Fit is used

### LINKED ISSUE #17071: Cannot use the keyboard to "click" on the toolbar buttons when Page Fit is used
This bug is so weird that I wonder if I'm doing something wrong...
That said  here's a STR:
 - open a pdf and set `Page Fit`;
 - with the keyboard, move the focus on a toolbar button, e.g. the freetext one;
 - press Enter key

nothing is happening.
If I change to `Automatic Zoom` then everything is ok.

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]
Sorry, but I think that there's a number of "issues" with this:
 - Does the problem not apply in the same way to `spacebar` as well?
 - This ignores the `shift` + `Enter` case, which I don't think is intended? Please note [this part of the code](https://github.com/mozilla/pdf.js/blob/c4c24c6d18225e74ce1fec9e8b1b82b3c134cc95/web/app.js#L3226-L3240).
 - Last, but definitely not least, this is adding *even more* special-cases to an already somewhat complex event handler. Can you please see if it's possible to integrate this a little bit better into the existing checks, e.g. by re-factoring the code, to simplify things?

**Comment by Snuffleupagus** [comment]
While the updated patch is indeed much simpler, I do wonder if it's not catching way too many cases now?

With this patch if you click on one of the toolbar-buttons you now need to *manually* click on the viewer (or `tab` to it) in order for it to receive e.g. any keyboard-scrolling events. This is changing behaviour that's existed for *years* and it's likely to catch users off guard (and probably lead to bug reports).

File: web/app.js [hunk 1]
```diff
@@ -3100,6 +3100,7 @@ function webViewerKeyDown(evt) {
     curElementTagName === "INPUT" ||
     curElementTagName === "TEXTAREA" ||
     curElementTagName === "SELECT" ||
+    curElementTagName === "BUTTON" ||
```
Comment (Snuffleupagus) [inline web/app.js:3103]: Could we "fix" patch by changing this as follows?
```suggestion
    (curElementTagName === "BUTTON" &&
      (evt.keyCode === /* Enter = */ 13 || evt.keyCode === /* Space = */ 32)) ||
```

**Review by Snuffleupagus — APPROVED** [review]
