### PR TITLE
[Editor] Avoid an exception when undoing the deletion of a pre-existing annotation

### LINKED ISSUE #18849: [Bug]: Deleting and restoring an edited Stamp-annotation is broken
### Attach (recommended) or Link to PDF file

https://github.com/mozilla/pdf.js/blob/master/test/pdfs/annotation-stamp.pdf

### Web browser and its version

N/A

### Operating system and its version

N/A

### PDF.js version

master

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Load https://mozilla.github.io/pdf.js/web/viewer.html
2. Open the `annotation-stamp.pdf` file.
3. Double-click on the "APPROVED"-image to enable Stamp-editing.
4. Delete the editor, either with <kbd>Del</kbd> or the editing-toolbar button.
5. Restore the editor, with <kbd>Ctrl</kbd>+<kbd>Z</kbd>.

### What is the expected behavior?

That the editor is restored.

### What went wrong?

The editor is *not* restored, and the following is printed in the console:
```
TypeError: can't access property "type", image is undefined
    #get tools.js:138
    getFromUrl tools.js:183
    getFromId tools.js:200
    #getBitmap stamp.js:226
    rebuild stamp.js:334
    addOrRebuild annotation_editor_layer.js:585
    #addEditorToLayer tools.js:1873
    undo tools.js:2057
    undo tools.js:354
    undo tools.js:1993
    exec tools.js:478
    keydown tools.js:1444
    #addKeyboardManager tools.js:1263
    AnnotationEditorUIManager tools.js:817
    setDocument pdf_viewer.js:893
    promise callback*setDocument pdf_viewer.js:866
    load app.js:1264
    open app.js:1070
    promise callback*open app.js:1068
    onFileInputChange app.js:2250
    dispatch event_utils.js:115
    run app.js:730
    run app.js:724
    webViewerLoad viewer.js:255
    <anonymous> viewer.js:266
tools.js:167:14
```

### Link to a viewer

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by calixteman**
It fixes #18849.

When such an annotation is deleted, we make sure that there are some data to restore.
The version of this patch was making undoing a svg deletion buggy, so it's fixed now and an integration test has been added for this case.

### CODE REVIEW

File: test/integration/stamp_editor_spec.mjs [hunk 1]
```diff
@@ -1388,4 +1427,50 @@ describe("Stamp Editor", () => {
...
+
+    beforeAll(async () => {
+      pages = await loadAndWait("stamps.pdf", getAnnotationSelector("37R"));
+    });
+
+    afterAll(async () => {
+      await closePages(pages);
+    });
+
+    it("must move an annotation", async () => {
```
Comment (Snuffleupagus) [inline test/integration/stamp_editor_spec.mjs:1442]: This test name looks like a bit too much copy-and-paste happening :-)

**Review by Snuffleupagus — APPROVED** [review]
r=me, with the name fixed; thank you.
