### PR TITLE
Don't throw when there isn't enough data to get block info in flate stream

### LINKED ISSUE #17332: Signature is missing in Signed PDFs
Attach (recommended) or Link to PDF file here:
[test(1).pdf](https://github.com/mozilla/pdf.js/files/13463186/test.1.pdf)

Configuration:
- Web browser and its version: Microsoft Edge 119.0.2151.72
- Operating system and its version: Windows10
- PDF.js version: 4.0.189
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the attached/linked PDF file using PDF.js.
2. Navigate to the page with the electronic stamp.

What is the expected behavior? (add screenshot)
The electronic stamp should be displayed correctly on the signed PDF document.

What went wrong? (add screenshot)
The electronic stamp is not rendering/displaying.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

### PR DESCRIPTION
**Pull request by calixteman**
but just ends the stream.

### CODE REVIEW

File: src/core/flate_stream.js [hunk 1]
```diff
@@ -238,6 +238,11 @@ class FlateStream extends DecodeStream {
     return [codes, maxLen];
   }
 
+  endsStreamOnError(err) {
```
Comment (Snuffleupagus) [inline src/core/flate_stream.js:241]: How about making this private instead, since nothing should ever access it from the outside?
```suggestion
  #endStreamOnError(err) {
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you!

File: src/core/flate_stream.js (hunk 1 above)
Comment (calixteman) [reply src/core/flate_stream.js:241]: I wonder if it's useful/helpful to warn here, wdyt ?

Comment (Snuffleupagus) [reply src/core/flate_stream.js:241]: You could change it to `info` instead, since that's not printed by default (but can still be enabled by changing the `verbosity`-option).
