### PR TITLE
Break text chunks only if the base font is different

### LINKED ISSUE #20956: [Bug]: Text shouldn't be cutted when the font is changing but with the same underlying font
### Attach (recommended) or Link to PDF file

[nutrition-rgo.pdf](https://github.com/user-attachments/files/26179672/nutrition-rgo.pdf)

### Web browser and its version

Firefox nightly

### Operating system and its version

Windows 11

### PDF.js version

master

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open the pdf
2. Check the text layer: it contains a way too much spans

There a lot of font variations but the base font is almost always the same.

### What is the expected behavior?

We should have less spans.

### What went wrong?

We have too much spans

### Link to a viewer

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by calixteman**
It fixes #20956.

### CODE REVIEW

File: src/core/evaluator.js [hunk 1]
```diff
@@ -2962,8 +2962,10 @@ class PartialEvaluator {
     function buildTextContentItem({ chars, extraSpacing }) {
       if (
         currentTextState !== textState &&
-        (currentTextState.fontName !== textState.fontName ||
-          currentTextState.fontSize !== textState.fontSize)
+        (currentTextState.fontSize !== textState.fontSize ||
+          (currentTextState.fontName !== textState.fontName &&
+            (currentTextState?.font.name !== textState.font.name ||
```
Comment (timvandermeij) [inline src/core/evaluator.js]: Is the `?.` here actually necessary, since we don't use it for the other checks either?

**Review by timvandermeij — APPROVED** [review]
r=me, with the comment addressed. Thanks!
