### PR TITLE
Validate explicit destinations on the worker-thread to prevent `DataCloneError` (issue 17981)

### LINKED ISSUE #17981: Unhandled Rejection for getAnnotations
Attach (recommended) or Link to PDF file here:
[unhandled_get_annotations.pdf](https://github.com/mozilla/pdf.js/files/15061082/unhandled_get_annotations.pdf)

Configuration:
- PDF.js version: pdfjs-dist@2.12.313

Steps to reproduce the problem:
```
const pdfjsLib = require('pdfjs-dist')
const loadingTask pdfjsLib.getDocument(arrayBuffer)
loadingTask.promise.then(instance => {
    pdf.getPage(1).getAnnotations()
        .then(annotations => console.log(annotations)
        .catch(error => console.error(error))
})
```

What went wrong? (add screenshot)
Cannot catch the error.
image

### PR DESCRIPTION
**Pull request by Snuffleupagus**
*Note:* This borrows a helper function from the viewer, however the code cannot be directly shared since the worker-thread has access to various primitives.

### CODE REVIEW

File: web/pdf_link_service.js [hunk 1]
```diff
@@ -549,59 +546,53 @@ class PDFLinkService {
...
+    const [page, zoom, ...args] = dest;
     if (
       !(
         typeof page === "object" &&
-        Number.isInteger(page.num) &&
-        Number.isInteger(page.gen)
+        Number.isInteger(page?.num) &&
+        Number.isInteger(page?.gen)
       ) &&
-      !(Number.isInteger(page) && page >= 0)
```
Comment (timvandermeij) [inline web/pdf_link_service.js:567]: `Number.isInteger(-1)` is also true, so shouldn't we still guard against negative page numbers here (and also in the mostly-copied worker variant above)?

**Review by timvandermeij — APPROVED** [review]
r=me, with the comment below answered/addressed. Thanks!

File: web/pdf_link_service.js (hunk 1 above)
Comment (Snuffleupagus) [reply web/pdf_link_service.js:567]: We have an old guard, which should be sufficient to prevent any issues here: https://github.com/mozilla/pdf.js/blob/7d1eabe2bd8e8becc37a1d0051bb2e9b361104cf/web/pdf_link_service.js#L214-L220

Moving the `page >= 0` check into the worker caused some annotation unit-tests to fail, and given the overall changes in this patch I'd rather err on the side of not imposing *too many* restrictions here (for a "harmless" case).

Comment (timvandermeij) [reply web/pdf_link_service.js:567]: I agree; this should then be sufficient, and otherwise we can always amend this later if we actually run into such cases (which I think to this date we haven't actually seen).
