### PR TITLE
JBIG2 halftone regions and pattern dictionaries

### LINKED ISSUE #7663: JBIG2 throws errors and displays blank pages in PDF
https://fraser.stlouisfed.org/docs/publications/employment/1970s/1970-1974/empl_081971.pdf

Configuration:
- Web browser and its version: Firefox 49.0
- Operating system and its version: OSX 10.11.3 
- PDF.js version: 1.5.281
- Is an extension:

Steps to reproduce the problem:
1. View the file at https://fraser.stlouisfed.org/docs/publications/employment/1970s/1970-1974/empl_081971.pdf
2. Scroll to page 6. 

What is the expected behavior? (add screenshot) Expected to see images in the PDF file
pdf

What went wrong? (add screenshot) The page displays blank, but you can highlight the embedded OCR text. There are errors about the JBIG2 pattern dictionary thrown in the javascript console.
jbig2error

### PR DESCRIPTION
**Pull request by janpe2**
Fixes #7663.
This pull request adds support for two segment types in the JBIG2 image decoder: halftone region segments and pattern dictionary segments. The support for MMR encoding is still missing. 
Here are some PDF files that contain JBIG2 images with the mentioned segment types:

- The PDF in #7663 (pages 6-18).
- [http://www.cvisiontech.us/jbig2primer/300dpiBW-1-Halftone.pdf](http://www.cvisiontech.us/jbig2primer/300dpiBW-1-Halftone.pdf)
- [http://www.cvisiontech.us/jbig2primer/Lex_bpp.PDF](http://www.cvisiontech.us/jbig2primer/Lex_bpp.PDF)
- Ghostscript bug 691230 [https://bugs.ghostscript.com/attachment.cgi?id=6152](https://bugs.ghostscript.com/attachment.cgi?id=6152)
- [castle_halftone.pdf](https://github.com/mozilla/pdf.js/files/1055278/castle_halftone.pdf)

### CODE REVIEW

File: src/core/jbig2.js [hunk 1]
```diff
@@ -606,6 +606,136 @@ var Jbig2Image = (function Jbig2ImageClosure() {
...
+      at.push({
+        x: -2,
+        y: -2
+      });
+    }
+    var collectiveWidth = (maxPatternIndex + 1)*patternWidth;
+    var collectiveBitmap = decodeBitmap(mmr, collectiveWidth, patternHeight,
+                                        template, false, null, at,
+                                        decodingContext);
+    // Divide collective bitmap into patterns
```
Comment (Snuffleupagus) [inline src/core/jbig2.js]: Nit: please remember to end sentences with a period (applies elsewhere in the patch as well).

File: src/core/jbig2.js [hunk 2]
```diff
@@ -1074,6 +1242,40 @@ var Jbig2Image = (function Jbig2ImageClosure() {
       function SimpleSegmentVisitor_onImmediateLosslessTextRegion() {
       this.onImmediateTextRegion.apply(this, arguments);
     },
+    onPatternDictionary:
+      function SimpleSegmentVisitor_onPatternDictionary(dictionary,
```
Comment (Snuffleupagus) [inline src/core/jbig2.js]: Since we now support ES6, please just use the following formatting when adding *new* code (applies to the methods below as well):
```javascript
onPatternDictionary(dictionary, currentSegment, data, start, end) {
```

**Review by Snuffleupagus — COMMENTED** [review]
Really nice that you decided to contribute to JBIG2 yourself (after PR #8335) :-)

There's a couple of things that needs to be done before this is ready for review:
 - Please add a test-case to the PR (so we can avoid regressions in the future). I'd suggest using the https://github.com/mozilla/pdf.js/files/1055278/castle_halftone.pdf file you added to the PR description. Please see e.g. PR https://github.com/mozilla/pdf.js/pull/8335/files for an example of how to add a linked test-case.
 - Make sure that you run `gulp lint` locally, and fix the errors that it reports.
 - When adding new code, please use `let` instead of `var`.
 - Finally, don't forget to squash the commits, please refer to https://github.com/mozilla/pdf.js/wiki/Squashing-Commits.

File: test/pdfs/pr8491.pdf.link [hunk 3]
```diff
@@ -0,0 +1 @@
+https://github.com/mozilla/pdf.js/files/1055278/castle_halftone.pdf
```
Comment (Snuffleupagus) [inline test/pdfs/pr8491.pdf.link]: Nit: Please add a newline at the end of this file.

File: test/test_manifest.json [hunk 4]
```diff
@@ -3537,5 +3537,12 @@
        "md5": "ced0e2d88cfd5b4d3a55d937ea288af1",
        "rounds": 1,
        "type": "eq"
+    },
+    {  "id": "pr8491",
+       "file": "pdfs/pr8491.pdf.link",
```
Comment (Snuffleupagus) [inline test/test_manifest.json]: I don't think this will work, it needs to read `"file": "pdfs/pr8491.pdf"` instead.

**Review by Snuffleupagus — COMMENTED** [review]
Thanks for updating the patch!

Besides the inline comments, it appears that there are now merge conflicts in the PR.
When resolving this, please don't forget to squash everything into on commit; please see https://github.com/mozilla/pdf.js/wiki/Squashing-Commits.

**Comment by timvandermeij** [comment]
This looks much better already! Could you rebase onto the current master to fix the merge conflicts?

**Comment by Snuffleupagus** [comment]
Sorry to keep bothering you about this, but can you please squash everything into on commit (since there shouldn't be a merge commit in a PR); see https://github.com/mozilla/pdf.js/wiki/Squashing-Commits.

**Comment by Snuffleupagus** [comment]
@yurydelendik Since you wrote the initial JBIG2 implementation, could you please review this patch?

**Comment by janpe2** [comment]
@Snuffleupagus Thank you very much for all the help you provided. And thank you for your patience :)

File: src/core/jbig2.js [hunk 5]
```diff
@@ -607,6 +607,136 @@ var Jbig2Image = (function Jbig2ImageClosure() {
...
+                                        template, false, null, at,
+                                        decodingContext);
+    // Divide collective bitmap into patterns.
+    let patterns = [], i = 0, patternBitmap, xMin, xMax, x, y, row, subX;
+    while (i <= maxPatternIndex) {
+      patternBitmap = [];
+      xMin = patternWidth * i;
+      xMax = xMin + patternWidth;
+      for (y = 0; y < patternHeight; y++) {
+        row = new Uint8Array(patternWidth);
```
Comment (yurydelendik) [inline src/core/jbig2.js]: `row = collectiveBitmap[y].subarray(xMin, xMax)` instead of for-loop below

File: src/core/jbig2.js [hunk 6]
```diff
@@ -607,6 +607,136 @@ var Jbig2Image = (function Jbig2ImageClosure() {
...
+        for (i = 0; i < patternHeight; i++) {
+          regionRow = regionBitmap[y + i];
+          if (!regionRow) {
+            continue;
+          }
+          patternRow = patternBitmap[i];
+          for (j = 0; j < patternWidth; j++) {
+            regionRow[x + j] |= patternRow[j]; // OR
+          }
+        }
```
Comment (yurydelendik) [inline src/core/jbig2.js]: In the past we had performance issues when array is accessed out-of-bounds. Can you create if-check for fast version of copy:

```
  if (x >= 0 && x + patternWidth <= regionWidth && y >= 0 && y + patternHeight <= regionHeight) {
     for (i = 0; i < patternHeight; i++) {
        regionRow = regionBitmap[y + i];
        for (j = 0; j < patternWidth; j++) {
            regionRow[x + j] |= patternRow[j]; // OR
        }
      }
  } else {
     // same loop as above but y + i and x + j is checked for out-of-bound or for-loop use proper bounds
  }
```

**Review by yurydelendik — APPROVED** [review]
Looks good with few minor fixes.

**Comment by timvandermeij** [comment]
Moreover, after fixing these comments, please make sure that the commit remains squashed and amend the commit message to a more descriptive message such as `Implement JBIG2 halftone regions and pattern dictionaries`.

**Comment by timvandermeij** [comment]
@janpe2 Could you fix the comments above so we can merge this? Thank you!

**Comment by Snuffleupagus** [comment]
@yurydelendik Can you please check if the updated patch addresses your previous review comments (since it would be great to get this landed)?

**Comment by Snuffleupagus** [comment]
@yurydelendik Can you please check if the updated patch addresses your previous review comments (since it would be great to get this landed)?

**Review by yurydelendik — APPROVED** [review]
Looks good, thank you.

**Comment by Snuffleupagus** [comment]
@janpe2 Thanks a lot for helping improving the JBIG2 decoder!

Currently there's one (fairly common) feature missing in our JBIG2 decoder, and that's Huffman support; see issue #2073 and the issues/files linked from there.
Since you seem to be familiar with the JBIG2 format, is that perhaps something that you would be interested in looking into next?
