### PR TITLE
[api-minor] Limit the maximum canvas width/height, in addition to its total area (bug 1943094)

### LINKED ISSUE #12957: Bottom third of tall PDF document is clipped/unpainted
Attach (recommended) or Link to PDF file here: [u6-longrange.pdf](https://github.com/mozilla/pdf.js/files/5929134/u6-longrange.pdf)

(original link: http://dl.ubnt.com/qig/u6-longrange , linked from https://store.ui.com/collections/unifi-network-access-points/products/unifi-6-long-range-access-point ("installation guide")

Configuration:
- Web browser and its version: Firefox Nightly 87.0a1 (2021-02-03) (64-bit)
- Operating system and its version: Ubuntu 20.10 and macOS 11.2 Big Sur (reproduced on both)
- PDF.js version: Whatever is currently shipping with Firefox Nightly (I don't recall how to tell)
- Is a browser extension: I'm using the built-in version that comes with Firefox.

Steps to reproduce the problem:
1. View the provided PDF (which is a single extremely-tall page; Ubiquiti seems to do this for their guides for some reason)
2. Try to scroll to the end.

What is the expected behavior?
You should see graphical content all the way to the end of the document.

What went wrong?
About 2/3 of the way through the document, the graphical content is abruptly clipped, and the rest of the document is just blank.
Screenshot of where the content gets clipped (rendering is entirely blank after this point)

### PR DESCRIPTION
**Pull request by Snuffleupagus**
Browsers not only limit the maximum total canvas area, but additionally also limit their maximum width/height which affects PDF documents with e.g. very tall and narrow pages.
To address this we add a new `maxCanvasDim` viewer-option, which in Firefox will use a browser preference, such that both the total canvas area and the width/height will affect when CSS-zooming is used.

### CODE REVIEW

File: web/pdf_page_view.js [hunk 1]
```diff
@@ -78,12 +78,14 @@ import { XfaLayerBuilder } from "./xfa_layer_builder.js";
  * @property {number} [maxCanvasPixels] - The maximum supported canvas size in
  *   total pixels, i.e. width * height. Use `-1` for no limit, or `0` for
  *   CSS-only zooming. The default value is 4096 * 8192 (32 mega-pixels).
+ * @property {number} [maxCanvasDim] - The maximum supported canvas dimension,
+ *   in either width or height. Use `-1` for no limit.
```
Comment (nicolo-ribaudo) [inline web/pdf_page_view.js:82]: Looking at the code, it seems `0` also means "no limit"?

Comment (Snuffleupagus) [reply web/pdf_page_view.js:82]: That wasn't the intention, so I've update the patch to fix that; thanks for spotting the inconsistency.

**Review by calixteman — APPROVED** [review]
LGTM. Thank you.
