### PR TITLE
Use ImageDecoder in order to decode jpeg images (bug 1901223)

### LINKED ISSUE #18088: [performance]: The putBinaryImageData function takes too long and blocks page interaction.
Attach (recommended) or Link to PDF file here:
[example.pdf](
https://github.com/mozilla/pdf.js/files/15305498/example.pdf)

Configuration:
- Web browser and its version: chrome version: 124.0.6367.208
- Operating system and its version: win 11
- PDF.js version: 3.4.120

Steps to reproduce the problem:
1. Render a 30+ page PDF document in a 200 × 200 container
2. After calling the pdfPage rendering function, the page becomes unresponsive.

What is the expected behavior? 
Render normally without blocking user behavior

What went wrong? (add screenshot)
image
image

### LINKED ISSUE #18307: Opening 24 MB PDF file with graphics takes very long and 100 % CPU usage
Attach (recommended) or Link to PDF file here:

[425429.pdf](https://github.com/user-attachments/files/15916204/425429.pdf) from https://www.osce.org/files/f/documents/f/5/425429.pdf, 24 MB, MD5: 63f989b7058bb5bc2a48319ab3ca9139

Configuration:
- Web browser and its version: Firefox Nightly 129.0a1~20240620040816
- Operating system and its version: Debian sid/unstable
- PDF.js version: https://mozilla.github.io/pdf.js/web/viewer.html
- Is a browser extension: no

Steps to reproduce the problem:
1. Open the PDF
2. Notice rendering takes several minutes and usage of one CPU thread is 100 %

What is the expected behavior? (add screenshot)

It should work

What went wrong? (add screenshot)

It didn’t render instantly.

PS: Evince 46.3 also has trouble rendering this.

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
1. Do you have benchmarking results that show (clear) improvements with this patch?

 2. Unfortunately there's failures on both bots, since the logs contain:
     ```
     TEST-UNEXPECTED-FAIL | test failed firefox has not responded in 120s
     ```

**Comment by calixteman** [comment]
> 2\. Unfortunately there's failures on both bots, since the logs contain:

Oh I think I need to update Firefox to take into account the patch made to avoid this timeout.

**Comment by calixteman** [comment]
> 1. Do you have benchmarking results that show (clear) improvements with this patch?

With the pdf in #18307, the time to render drops from ~120s to ~20s !
Of for pdf with a single jpeg image with normal dimensions, the win isn't so important because we've some overhead due the ImageDecoder stuff.
That said, I checked several normal pdfs and the improvement is between 20% and 100%, it depends of the image.

**Comment by Snuffleupagus** [comment]
Before I review this, can you please confirm that you've looked through *all* ref-test results without finding any obvious regressions?

**Comment by calixteman** [comment]
> Before I review this, can you please confirm that you've looked through _all_ ref-test results without finding any obvious regressions?

Yep, I checked the results locally and on the bots and there's nothing obviously wrong.

File: src/core/jpg.js [hunk 1]
```diff
@@ -744,55 +744,111 @@ function findNextFileMarker(data, currentPos, startPos = currentPos) {
...
+    }
+    if (numComponents === 4) {
+      return false;
     }
+    if (numComponents !== 3) {
+      return true;
+    }
+    if (colorTransform === 0) {
+      return false;
+    }
```
Comment (Snuffleupagus) [inline src/core/jpg.js:847]: Can we please write this as follows instead, since I find that a fair bit this easier to read at a glance?
```suggestion
    if (numComponents === 3 && colorTransform === 0) {
      return false;
    }
```

File: src/core/jpg.js [hunk 2]
```diff
@@ -744,55 +744,111 @@ function findNextFileMarker(data, currentPos, startPos = currentPos) {
...
-        const blocksPerColumnForMcu = mcusPerColumn * component.v;
-
-        const blocksBufferSize =
-          64 * blocksPerColumnForMcu * (blocksPerLineForMcu + 1);
-        component.blockData = new Int16Array(blocksBufferSize);
-        component.blocksPerLine = blocksPerLine;
-        component.blocksPerColumn = blocksPerColumn;
+    fileMarker = readUint16(data, offset);
+    offset += 2;
+    markerLoop: while (fileMarker !== /* EOI (End of Image) = */ 0xffd9) {
```
Comment (Snuffleupagus) [inline src/core/jpg.js:817]: Let's add a line-break, to aid readability a little.
```suggestion
    offset += 2;
    
    markerLoop: while (fileMarker !== /* EOI (End of Image) = */ 0xffd9) {
```

File: src/core/jpg.js [hunk 3]
```diff
@@ -744,55 +744,111 @@ function findNextFileMarker(data, currentPos, startPos = currentPos) {
...
+    warn(
+      "readDataBlock - incorrect length, current marker is: " +
+        fileMarker.invalid
+    );
+    endOffset = fileMarker.offset;
+  }
+
+  const array = data.subarray(offset, endOffset);
+  offset += array.length;
+  return { newOffset: offset, appData: array };
```
Comment (Snuffleupagus) [inline src/core/jpg.js:786]: Nit: Sort these alphabetically, since that'd be consistent with [the line below](https://github.com/mozilla/pdf.js/pull/18910/files?diff=split&w=1#diff-143bf2039233dcbb6fca17d52a2104d0e97b2c0199d9db4ce432d4166d3516d3R889)?
```suggestion
  return { appData: array, newOffset: offset };
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, with a few minor (stylistic) comments; thank you.

**Comment by calixteman** [comment]
I missed the Chrome timeout issue on linux bot...

**Comment by Snuffleupagus** [comment]
> I missed the Chrome timeout issue on linux bot...

That shouldn't be related to this PR though, since it's been happening intermittently for maybe a week and is mentioned in https://github.com/mozilla/pdf.js/issues/18928#issue-2600494826.

**Comment by calixteman** [comment]
The guilty pdf takes around 20s to render on Windows with Chrome so 2min seems to be a bit exaggerated: I'll have a look on it.
