### PR TITLE
Display outlines even if one has no title

### LINKED ISSUE #17856: Show outlines even if some of them have no title
Attach (recommended) or Link to PDF file here:
[outline-without-title.pdf](https://github.com/mozilla/pdf.js/files/14808044/outline-without-title.pdf)

For reference the file has been found in here: https://github.com/py-pdf/pypdf/blob/main/resources/outline-without-title.pdf

Configuration:
- Web browser and its version: Firefox nightly
- Operating system and its version: Windows 11

Steps to reproduce the problem:
1. Open the pdf and check outlines

What is the expected behavior? (add screenshot)
We should render the outlines even if one doesn't exist because it has no title.

What went wrong? (add screenshot)
No outlines

The outlines are correctly displayed in either Chrome or in Acrobat.

### PR DESCRIPTION
**Pull request by calixteman**
Fixes #17856.

### CODE REVIEW

File: src/core/catalog.js [hunk 1]
```diff
@@ -334,7 +334,7 @@ class Catalog {
         docBaseUrl: this.baseUrl,
         docAttachments: this.attachments,
       });
-      const title = outlineDict.get("Title");
+      const title = outlineDict.get("Title") || "";
```
Comment (Snuffleupagus) [inline src/core/catalog.js:337]: I'd suggest reverting this line, and *instead* change https://github.com/mozilla/pdf.js/blob/55db43966eaf99b1292ae913fe2ae3eae7d0e8ad/src/core/catalog.js#L360 into the following to *properly* validate the data:
```javascript
title: typeof title === "string" ? stringToPDFString(title) : "", 
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, with the comment addressed; thank you!
