### PR TITLE
[JS] Take into account all the required fields for some computations

### LINKED ISSUE #15568: Few Form fields are not performing the calculation
Link to the PDF file here:
[miscalculation.pdf](https://github.com/mozilla/pdf.js/files/9770820/miscalculation.pdf)

Configuration:
- Web browser and its version: Chrome (106.0.5249.103)
- Operating system and its version: Windows 10
- PDF.js version: 3.0.206
- Is a browser extension: no

Steps to reproduce the problem:
1.  Enter the values as mentioned in the below images. The calculations are not performed on these fields.

What is the expected behavior?
image

What went wrong?
image

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): [Viewer](https://mozilla.github.io/pdf.js/legacy/web/viewer.html)

### PR DESCRIPTION
**Pull request by calixteman**
- Fix Field::getArray in order to collect only the fields which have a value;
- Fix AFSimple_Calculate:
  * allow to have a string with a list of field names as argument;
  * since a field can be non-terminal, use Field::getArray to collect the field under it and then apply the calculation on all the descendants.

### CODE REVIEW

File: src/scripting_api/doc.js [hunk 1]
```diff
@@ -889,6 +889,24 @@ class Doc extends PDFObject {
...
+  _getTerminalChildren(fieldName) {
+    // Get all the descendants which have a value.
+    const children = [];
+    const len = fieldName.length;
+    for (const [name, field] of this._fields.entries()) {
+      if (name.startsWith(fieldName)) {
+        const finalPart = name.slice(len);
+        if (
+          field.obj._hasValue &&
+          (finalPart === "" || finalPart.charAt(0) === ".")
```
Comment (Snuffleupagus) [inline src/scripting_api/doc.js:901]: Maybe use the slightly more modern `startsWith` instead?
```suggestion
          (finalPart === "" || finalPart.startsWith("."))
```

File: src/scripting_api/field.js [hunk 2]
```diff
@@ -393,15 +394,32 @@ class Field extends PDFObject {
   }
 
   getArray() {
+    // Gets the array of terminal child fields (that is, fields that can have
+    // a value for this Field object, the parent field.
```
Comment (Snuffleupagus) [inline src/scripting_api/field.js:398]: Nit: missing closing parenthesis here.
```suggestion
    // a value for this Field object, the parent field).
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, with passing tests.
