### PR TITLE
Fix pattern-filled text (embedded fonts only)

### LINKED ISSUE #3988: incorrect rendering / no "rendering is incorrect" warning
http://stadtmusik-sursee.ch/phocadownload/2013_Chlausmaeaert/2013_Chlausmaert_A5.pdf

web console output (FF 26 Beta 8):

Unknown pseudo-class or pseudo-element 'fullscreen'.  Ruleset ignored due to bad selector. viewer.css:58
12:33:58.724 Unknown pseudo-class or pseudo-element 'fullscreen'.  Ruleset ignored due to bad selector. viewer.css:73
12:33:58.724 Unknown pseudo-class or pseudo-element 'fullscreen'.  Ruleset ignored due to bad selector. viewer.css:81
12:33:58.724 Unknown pseudo-class or pseudo-element 'fullscreen'.  Ruleset ignored due to bad selector. viewer.css:89
12:33:58.725 Unknown property 'box-sizing'.  Declaration dropped. viewer.css:822
12:33:58.725 Unknown pseudo-class or pseudo-element 'selection'.  Ruleset ignored due to bad selector. viewer.css:1225
12:33:59.157 "PDF cc0a252e7914bab8c28dce9e963f31 1.6 Adobe PDF Library 10.0.1 / Adobe InDesign CC (Macintosh) (PDF.js: 0.8.751)"

### LINKED ISSUE #8940: Text horizontally mirrored
Link to PDF file (or attach file here):
[github_example.pdf](https://github.com/mozilla/pdf.js/files/1321283/github_example.pdf)

Configuration:
- Web browser and its version:
Chrome 60.0.3112.113, IE 11.0.9600.18792, Firefox ESR 38.4.0
- Operating system and its version:
Windows 10
- PDF.js version:
1.8.188
- Is an extension:
no

Steps to reproduce the problem:
1. open the attached PDF document in the demo viewer (https://mozilla.github.io/pdf.js/web/viewer.html)

What is the expected behavior? (add screenshot)
Should view two text elements "MUSTER" and "VORANSICHT VORANSICHT" (Overlapping is OK).
2017-09-21 15_19_48-github_example pdf - adobe reader

What went wrong? (add screenshot)
Both texts are horizontally mirrored and on the top of the document.
2017-09-21 15_38_00-32d10e34-f34d-4a50-a6af-7f9a747c2134

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

Regards
Philipp

### PR DESCRIPTION
**Pull request by janpe2**
Fixes #8940
Fixes #5432 (AkzoNobel file)
Fixes #3988 (texts now have gradient fill instead of solid color)

This PR fixes the rendering of texts that have a tiling or shading pattern as a fill color and an embedded font is used.

The problems in the reported issues are caused by `ctx.fillText()`. The glyphs and the pattern would need their own transforms but `ctx.fillText()` uses the same transform for them both. Thus either the text or the pattern gets incorrectly transformed. My solution is to draw glyphs as paths, so I can use a different transform for the pattern and the glyphs. However I can't fix texts that use system fonts because it's impossible to get glyphs as paths from system fonts.

The file test/pdfs/ShowText-ShadingPattern.pdf (test case `ShowText-ShadingPattern`) is rendered better now. The "Arial" text is correct because it uses an embedded font. The "Helvetica" text is still wrong since it uses a system font.

This PR continues the work that was started in PR #6820.

### CODE REVIEW

**Comment by timvandermeij** [comment]
Thank you for looking into this! I'm just adding that at #3988 a new link to the PDF file has been put in the comments.

File: src/core/evaluator.js [hunk 1]
```diff
@@ -584,7 +584,8 @@ var PartialEvaluator = (function PartialEvaluatorClosure() {
       var glyphs = font.charsToGlyphs(chars);
       var isAddToPathSet = !!(state.textRenderingMode &
                               TextRenderingMode.ADD_TO_PATH_FLAG);
-      if (font.data && (isAddToPathSet || this.options.disableFontFace)) {
+      if (font.data && (isAddToPathSet || this.options.disableFontFace ||
+          state.fillColorSpace.name === 'Pattern')) {
```
Comment (Snuffleupagus) [inline src/core/evaluator.js]: Nit: To make it easier to interpret this condition, can you please re-align it as follows instead?
```javascript
if (font.data && (isAddToPathSet || this.options.disableFontFace ||
                  state.fillColorSpace.name === 'Pattern')) {
```

File: src/display/canvas.js [hunk 2]
```diff
@@ -1347,7 +1347,8 @@ var CanvasGraphics = (function CanvasGraphicsClosure() {
       this.moveText(0, this.current.leading);
     },
 
-    paintChar: function CanvasGraphics_paintChar(character, x, y) {
+    paintChar: function CanvasGraphics_paintChar(character, x, y,
```
Comment (Snuffleupagus) [inline src/display/canvas.js]: Nit: Taking full advantage of ES6 syntax, the entire method signature can be simplified to:
```javascript
paintChar(character, x, y, patternTransform) {
```

File: src/display/canvas.js [hunk 3]
```diff
@@ -1536,11 +1545,12 @@ var CanvasGraphics = (function CanvasGraphicsClosure() {
...
             ctx.fillText(character, scaledX, scaledY);
           } else {
-            this.paintChar(character, scaledX, scaledY);
+            this.paintChar(character, scaledX, scaledY, patternTransform);
             if (accent) {
               scaledAccentX = scaledX + accent.offset.x / fontSizeScale;
               scaledAccentY = scaledY - accent.offset.y / fontSizeScale;
-              this.paintChar(accent.fontChar, scaledAccentX, scaledAccentY);
+              this.paintChar(accent.fontChar, scaledAccentX, scaledAccentY,
+                patternTransform);
```
Comment (Snuffleupagus) [inline src/display/canvas.js]: Nit: Let's align this with the arguments above instead.
```javascript
this.paintChar(accent.fontChar, scaledAccentX, scaledAccentY,
               patternTransform);
```

File: src/display/canvas.js [hunk 4]
```diff
@@ -1443,17 +1448,21 @@ var CanvasGraphics = (function CanvasGraphicsClosure() {
...
       ctx.save();
-      ctx.transform.apply(ctx, current.textMatrix);
-      ctx.translate(current.x, current.y + current.textRise);
-
+      let patternTransform;
       if (current.patternFill) {
-        // TODO: Some shading patterns are not applied correctly to text,
-        //       e.g. issues 3988 and 5432, and ShowText-ShadingPattern.pdf.
-        ctx.fillStyle = current.fillColor.getPattern(ctx, this);
+        // TODO: Patterns are not applied correctly to text if a system font
```
Comment (Snuffleupagus) [inline src/display/canvas.js]: Nit: Let's replace `system font` with `non-embedded font` instead here, since that's more inline with the notation used elsewhere in PDF.js.

**Review by Snuffleupagus — APPROVED** [review]
*Sorry for the review delay here!*

This looks like a great improvement over the current state; thank you for the patch!
I've left a couple of comments, basically nits, but other than that the general approach seem fine to me :-)

**Comment by alafr** [comment]
Is it possible to do the same for pattern-stroked text?
[pattern stroked text.pdf](https://github.com/mozilla/pdf.js/files/1537085/pattern.stroked.text.pdf)
