### PR TITLE
Fix integration test with js-colors

### LINKED ISSUE #13022: Integration tests for color scripting support fail
This seems to happen more often now, but interestingly it only seems to happen on Linux. The last run was in https://github.com/mozilla/pdf.js/pull/13021#issuecomment-786012076. @calixteman Could you take a look at this to see if we can make the tests pass again?

The relevant log output is:

```
Failures:
1) Interaction in js-colors.pdf must changes colors
  Message:
[31m    In firefox: Expected 'rgba(0, 54, 255, 0.13)' to equal 'rgb(255, 0, 0)'.[0m
  Stack:
    Error: In firefox: Expected 'rgba(0, 54, 255, 0.13)' to equal 'rgb(255, 0, 0)'.
        at <Jasmine>
        at Promise.all.pages.map (/home/ubuntu/pdfjs/botio-files-pdfjs/private/e2b7f68c964756b/test/integration/scripting_spec.js:661:16)
        at process._tickCallback (internal/process/next_tick.js:68:7)
  Message:
[31m    In firefox: Expected 'rgb(255, 0, 0)' to equal 'rgb(0, 255, 0)'.[0m
  Stack:
    Error: In firefox: Expected 'rgb(255, 0, 0)' to equal 'rgb(0, 255, 0)'.
        at <Jasmine>
        at Promise.all.pages.map (/home/ubuntu/pdfjs/botio-files-pdfjs/private/e2b7f68c964756b/test/integration/scripting_spec.js:667:16)
        at process._tickCallback (internal/process/next_tick.js:68:7)
  Message:
[31m    In firefox: Expected 'rgb(0, 255, 0)' to equal 'rgb(0, 0, 255)'.[0m
  Stack:
    Error: In firefox: Expected 'rgb(0, 255, 0)' to equal 'rgb(0, 0, 255)'.
        at <Jasmine>
        at Promise.all.pages.map (/home/ubuntu/pdfjs/botio-files-pdfjs/private/e2b7f68c964756b/test/integration/scripting_spec.js:676:16)
        at process._tickCallback (internal/process/next_tick.js:68:7)
  Message:
[31m    In firefox: Expected 'rgb(0, 0, 255)' to equal 'rgb(255, 0, 0)'.[0m
  Stack:
    Error: In firefox: Expected 'rgb(0, 0, 255)' to equal 'rgb(255, 0, 0)'.
        at <Jasmine>
        at Promise.all.pages.map (/home/ubuntu/pdfjs/botio-files-pdfjs/private/e2b7f68c964756b/test/integration/scripting_spec.js:661:16)
        at process._tickCallback (internal/process/next_tick.js:68:7)
  Message:
[31m    In firefox: Expected 'rgb(255, 0, 0)' to equal 'rgb(0, 255, 0)'.[0m
  Stack:
    Error: In firefox: Expected 'rgb(255, 0, 0)' to equal 'rgb(0, 255, 0)'.
        at <Jasmine>
        at Promise.all.pages.map (/home/ubuntu/pdfjs/botio-files-pdfjs/private/e2b7f68c964756b/test/integration/scripting_spec.js:667:16)
        at process._tickCallback (internal/process/next_tick.js:68:7)
  Message:
[31m    In firefox: Expected 'rgb(0, 255, 0)' to equal 'rgb(0, 0, 255)'.[0m
  Stack:
    Error: In firefox: Expected 'rgb(0, 255, 0)' to equal 'rgb(0, 0, 255)'.
        at <Jasmine>
        at Promise.all.pages.map (/home/ubuntu/pdfjs/botio-files-pdfjs/private/e2b7f68c964756b/test/integration/scripting_spec.js:676:16)
        at process._tickCallback (internal/process/next_tick.js:68:7)
  Message:
[31m    In firefox: Expected 'rgb(0, 0, 255)' to equal 'rgb(255, 0, 0)'.[0m
  Stack:
    Error: In firefox: Expected 'rgb(0, 0, 255)' to equal 'rgb(255, 0, 0)'.
        at <Jasmine>
        at Promise.all.pages.map (/home/ubuntu/pdfjs/botio-files-pdfjs/private/e2b7f68c964756b/test/integration/scripting_spec.js:661:16)
        at process._tickCallback (internal/process/next_tick.js:68:7)
  Message:
[31m    In firefox: Expected 'rgb(255, 0, 0)' to equal 'rgb(0, 255, 0)'.[0m
  Stack:
    Error: In firefox: Expected 'rgb(255, 0, 0)' to equal 'rgb(0, 255, 0)'.
        at <Jasmine>
        at Promise.all.pages.map (/home/ubuntu/pdfjs/botio-files-pdfjs/private/e2b7f68c964756b/test/integration/scripting_spec.js:667:16)
        at process._tickCallback (internal/process/next_tick.js:68:7)
  Message:
[31m    In firefox: Expected 'rgb(0, 255, 0)' to equal 'rgb(0, 0, 255)'.[0m
  Stack:
    Error: In firefox: Expected 'rgb(0, 255, 0)' to equal 'rgb(0, 0, 255)'.
        at <Jasmine>
        at Promise.all.pages.map (/home/ubuntu/pdfjs/botio-files-pdfjs/private/e2b7f68c964756b/test/integration/scripting_spec.js:676:16)
        at process._tickCallback (internal/process/next_tick.js:68:7)
  Message:
[31m    In firefox: Expected 'rgb(0, 0, 255)' to equal 'rgb(255, 0, 0)'.[0m
  Stack:
    Error: In firefox: Expected 'rgb(0, 0, 255)' to equal 'rgb(255, 0, 0)'.
        at <Jasmine>
        at Promise.all.pages.map (/home/ubuntu/pdfjs/botio-files-pdfjs/private/e2b7f68c964756b/test/integration/scripting_spec.js:661:16)
        at process._tickCallback (internal/process/next_tick.js:68:7)
  Message:
[31m    In firefox: Expected 'rgb(255, 0, 0)' to equal 'rgb(0, 255, 0)'.[0m
  Stack:
    Error: In firefox: Expected 'rgb(255, 0, 0)' to equal 'rgb(0, 255, 0)'.
        at <Jasmine>
        at Promise.all.pages.map (/home/ubuntu/pdfjs/botio-files-pdfjs/private/e2b7f68c964756b/test/integration/scripting_spec.js:667:16)
        at process._tickCallback (internal/process/next_tick.js:68:7)
  Message:
[31m    In firefox: Expected 'rgb(0, 255, 0)' to equal 'rgb(0, 0, 255)'.[0m
  Stack:
    Error: In firefox: Expected 'rgb(0, 255, 0)' to equal 'rgb(0, 0, 255)'.
        at <Jasmine>
        at Promise.all.pages.map (/home/ubuntu/pdfjs/botio-files-pdfjs/private/e2b7f68c964756b/test/integration/scripting_spec.js:676:16)
        at process._tickCallback (internal/process/next_tick.js:68:7)
```

### PR DESCRIPTION
**Pull request by calixteman**
- need to wait for color change to check its value.

Fixes #13022.

### CODE REVIEW

File: test/integration/scripting_spec.js [hunk 1]
```diff
@@ -651,29 +651,35 @@ describe("Interaction", () => {
...
-            color = await page.$eval(
-              ref,
-              el => getComputedStyle(el)["border-top-color"]
-            );
-            expect(color)
-              .withContext(`In ${browserName}`)
-              .toEqual("rgb(0, 0, 255)");
+              await page.click(`[data-annotation-id='${id}R']`);
+              await page.waitForFunction(
+                (r, c, p) =>
```
Comment (Snuffleupagus) [inline test/integration/scripting_spec.js:668]: In this case I'm guessing that `c` is the colour, but it's simply too unclear what either `r` or `p` is supposed to represent.

Hence here, and above, can we please *not use* one (and two) letter variable names since it's hurting readability of the code quite a bit?

---

Also, there seems to be one "s" too many in the test name, so you probably want to change https://github.com/mozilla/pdf.js/blob/061637d3f4e354042307f2029e79c48ab0e72337/test/integration/scripting_spec.js#L641
to use:
```
"must change colors"
```

Comment (calixteman) [reply test/integration/scripting_spec.js:668]: > In this case I'm guessing that `c` is the colour, but it's simply too unclear what either `r` or `p` is supposed to represent.
> 

Here `r, c, p` stands for `ref, current, propName` which are the final args of `waitForFunction`.

> Hence here, and above, can we please _not use_ one (and two) letter variable names since it's hurting readability of the code quite a bit?
> 

Yes I know that but I can't use some already used names because of the linter...

**Comment by timvandermeij** [comment]
It looks like Linux improved, but there are still some errors.

**Comment by calixteman** [comment]
This test is ok locally (on a debian), and I don't really understand why it's failing...

**Comment by timvandermeij** [comment]
Puppeteer just got upgraded to version 8, so let's try again once the reference images in #13024 are done. The logs don't show a clear failure indeed, so perhaps the new version of Puppeteer will improve things.

**Comment by calixteman** [comment]
The color `rgba(0, 54, 255, 0.13)` is the "blue" for an unfocused annotation so it means that the click on the button didn't have any effect.

**Review by timvandermeij — APPROVED** [review]

**Comment by timvandermeij** [comment]
Thank you for fixing this!
