### PR TITLE
[JPX] Throw an exception with the error messages returned by openjpeg

### LINKED ISSUE #17955: Remove OpenJPEG logs from the JPX fuzzer output
The JPX fuzzer currently spams the output with the following log lines:

```
OpenJPEG: Unknown format
```

The JPX code does nicely emit a `JpxError` exception that we catch and handle, but it looks like the C code _additionally_ prints this to the console. We should check if we can disable that somehow, most likely in our C wrapper code (but otherwise doing this in the fuzzer code somehow would probably also suffice).

### PR DESCRIPTION
**Pull request by calixteman**
Fixes #17955.

### CODE REVIEW

File: src/core/jpx.js [hunk 1]
```diff
@@ -18,7 +18,7 @@ import OpenJPEG from "../../external/openjpeg/openjpeg.js";
 
 class JpxError extends BaseException {
   constructor(msg) {
-    super(`JPX error: ${msg}`, "JpxError");
+    super(msg, "JpxError");
```
Comment (Snuffleupagus) [inline src/core/jpx.js:21]: Please don't change this, since it makes JpxError *inconsistent* with the other image-errors (used with JPEG and JBIG2).

Comment (calixteman) [reply src/core/jpx.js:21]: Ok, I found a bit redundant to have "JpxError" and "JPX error" on the same line.

Comment (timvandermeij) [reply src/core/jpx.js]: Yes, what I would expect for #17955 is a message that looks like `JPX error: Unknown format`, so basically "JPX error: " plus what the C code emits as specific reason for the failure.

Comment (calixteman) [reply src/core/jpx.js]: Yep I know, but in the console I get:
`Warning: Unable to decode image "img_p0_1": "JpxError: JPX error: Unknown format".`
From my pov, even if change how we dump the warning in the console, it's still redundant... but maybe just a matter of taste.

Comment (Snuffleupagus) [reply src/core/jpx.js]: In that case, maybe we should consider changing *all* of `Jbig2Error`, `JpegError`, and `JpxError` to just print `msg` instead?
As long as we're consistent that seems fine to me; @timvandermeij thoughts?

Comment (timvandermeij) [reply src/core/jpx.js]: If we do that, we'd also have to update all fuzzers because they rely on this prefix in the error message to separate all expected (handled by our code) errors from unexpected (crashes or otherwise unhandled exceptions) errors; please refer to https://github.com/mozilla/pdf.js/blob/master/test/fuzz/jpx_image.fuzz.js#L10-L14. I guess we could catch `JpxError` explicitly there instead, and that'd arguably be nicer than relying on the error _message_ only, but that'd make this a bigger change that I wouldn't recommend doing in this scope (it'd be fine for a follow-up though).

**Review by timvandermeij — APPROVED** [review]
r=me, with the tests passing. I have checked out this PR locally and confirmed that the fuzzer no longer spams log messages:

```
$ npx jazzer fuzz/jpx_image.fuzz --sync
Dictionary: 4 entries
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 3792403092
INFO: Loaded 1 modules   (512 inline 8-bit counters): 512 [0x7e4cbb0ff010, 0x7e4cbb0ff210), 
INFO: Loaded 1 PC tables (512 PCs): 512 [0x7e4cb2400010,0x7e4cb2402010), 
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: A corpus is not provided, starting from an empty corpus
#2      INITED exec/s: 0 rss: 137Mb
WARNING: no interesting inputs were found so far. Is the code instrumented for coverage?
This may also happen if the target rejected all inputs we tried so far
#65536  pulse  corp: 1/1b lim: 652 exec/s: 21845 rss: 154Mb
#131072 pulse  corp: 1/1b lim: 1300 exec/s: 18724 rss: 154Mb
#262144 pulse  corp: 1/1b lim: 2611 exec/s: 17476 rss: 154Mb
```

Thank you for improving this!
