### PR TITLE
Prevent textLayer errors in documents with unbalanced beginMarkedContent/endMarkedContent operators (issue 15629)

### LINKED ISSUE #15629: Cannot open attached pdf file - TypeError: Cannot read properties of null (reading 'appendChild')
PDF attached here: [SampleWithIssue12.7.pdf](https://github.com/mozilla/pdf.js/files/9871034/SampleWithIssue12.7.pdf)

Configuration:
- Web browser and its version: Chrome, Version 106.0.5249.119 (Official Build) (64-bit)
- Operating system and its version: Windows 10 Pro Version 21H2 OS Build 19044.2130
- PDF.js version: Tested on 2.11.338 and then upgraded to 2.14.305, having the same problem.
- Invoking the library via https://github.com/VadimDez/ng2-pdf-viewer

Steps to reproduce the problem:
1. Open the attached pdf using pdf.js in the Chrome browser
2. It crashed with this error in the console:

```
Error captured:  Error: Uncaught (in promise): TypeError: Cannot read properties of null (reading 'appendChild')
TypeError: Cannot read properties of null (reading 'appendChild')
    at TextLayerRenderTask._processItems (pdf.js:22212:20)
    at pdf.js:22317:20
    at _ZoneDelegate.invoke (zone.js:372:1)
    at Object.onInvoke (core.mjs:25608:1)
    at _ZoneDelegate.invoke (zone.js:371:1)
    at Zone.run (zone.js:134:1)
    at zone.js:1275:1
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25595:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at resolvePromise (zone.js:1211:1)
    at zone.js:1282:1
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25595:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:585:1)
```

What is the expected behavior? 

It should open the pdf file.

What went wrong?

Error screenshot 1
Error screenshot 2

What have I tried/analysis?

I used Nitro PDF and edited the text "Louise Anne Farrar" and changed it slightly.
When I saved the PDF and opened it again in PDF.js, it worked. 
I noticed that the Helvetica font, which has Actual font ArialMT, was now embedded in the document (when I look at the pdf properties). Leads me to suspect that it is related to the embedding of the ArialMT Font, which the original PDF does not appear to have.
It's just a suspicion, don't know if that is the actual issue though.

In addition, I tried to disable **RenderTextMode**, and that also solves the issue, the pdf will then display properly. 
But I don't like this solution because the text is not selectable!!

Any ideas/suggestions?

### PR DESCRIPTION
**Pull request by Snuffleupagus**

### CODE REVIEW

File: src/display/text_layer.js [hunk 1]
```diff
@@ -318,7 +321,13 @@ class TextLayerRenderTask {
           }
           parent.append(this._container);
         } else if (item.type === "endMarkedContent") {
-          this._container = this._container.parentNode;
+          const parent = this._container.parentNode;
+          if (!parent || this._container === this.#initialContainer) {
```
Comment (Snuffleupagus) [inline src/display/text_layer.js:325]: Please note that I originally only added the `parent`-check, however that caused the `text`-tests to layout the text in an incorrect position.

This won't be a problem in the viewer, where an in-memory `DocumentFragment` is being used, however in the test-suite a regular `div` is being used (since that's officially supported) and that one has a parent element which thus necessitated these changes.

Comment (calixteman) [reply src/display/text_layer.js:325]: I think I'd have prefer having the fix in the `evaluator`, because it means that `getTextContent` is still returning some buggy data.
But in the meantime, this fix is very simple and doesn't add that much complexity, when fixing `getTextContent` would likely add more complexity.

**Review by calixteman — APPROVED** [review]
LGTM. Thank you.

File: src/display/text_layer.js (hunk 1 above)
Comment (Snuffleupagus) [reply src/display/text_layer.js:325]: > I think I'd have prefer having the fix in the `evaluator`, because it means that `getTextContent` is still returning some buggy data.

Completely agreed, but I'm thinking we can land this as-is such that it's included in the next release.

> But in the meantime, this fix is very simple and doesn't add that much complexity, when fixing `getTextContent` would likely add more complexity.

It might not be *that* difficult to address actually, I'll try to look into this a bit more later.

Comment (Snuffleupagus) [reply src/display/text_layer.js:325]: I haven't run a single test locally, so I suppose that I might have broken *something*, however my naive idea looks like this: https://github.com/mozilla/pdf.js/compare/master...Snuffleupagus:pdf.js:issue-15629-2

Comment (Snuffleupagus) [reply src/display/text_layer.js:325]: And it passes all `text`-tests locally, so might actually work out.

Comment (Snuffleupagus) [reply src/display/text_layer.js:325]: However, I suppose that one argument against doing that is that the rendering code (in `src/display/canvas.js`) handles unbalanced operators just fine without tracking that in the `PartialEvaluator`.

Comment (calixteman) [reply src/display/text_layer.js:325]: Yep we should do the same for the operatorList, but we can do that later.
