### PR TITLE
[api-minor] Add partial support for the "GoToE" action (issue 8844)

### LINKED ISSUE #8844: Warning: parseDestDictionary: Unsupported Action type "GoToE"
[FileAttached.pdf](https://github.com/mozilla/pdf.js/files/1264140/FileAttached.pdf)

Configuration:
- Chrome
- Windows 10 64-bit
- PDF.js version: Latest master
- Is an extension: no

Steps to reproduce the problem:
1. Produce the file using pdflatex as in [here](https://tex.stackexchange.com/questions/19025/embed-link-to-an-embedded-file)
2. Just open the file (Has embedded attachment + Link to that) 
3. Warning comes out: parseDestDictionary: Unsupported Action type "GoToE"

What is the expected behavior?
Open the attached file, this is perfectly working with Adobe reader.

What went wrong? 
Nothing Happens when the link is clicked

### PR DESCRIPTION
**Pull request by Snuffleupagus**
*Please note:* The referenced issue is the only mention that I can find, in either GitHub or Bugzilla, of "GoToE" actions.
Hence why I've purposely settled for a very simple, and partial, "GoToE" implementation to avoid complicating things initially.[1] In particular, this patch only supports "GoToE" actions that references the /EmbeddedFiles-dict in the PDF document.

See https://web.archive.org/web/20220309040754if_/https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf#G11.2048909

Fixes #8844

---
[1] Usually I always prefer having *real-world* test-cases to work with, whenever I'm implementing new features.

### CODE REVIEW

File: src/core/catalog.js [hunk 1]
```diff
@@ -1527,6 +1532,30 @@ class Catalog {
...
+        case "GoToE":
+          const target = action.get("T");
+          let attachment;
+
+          if (target instanceof Dict) {
+            const relationship = target.get("R");
+            const name = target.get("N");
+
+            if (
+              docAttachments &&
```
Comment (calixteman) [inline src/core/catalog.js:1544]: You can probably move the `docAttachments` check in the above `if`.

File: src/display/annotation_layer.js [hunk 2]
```diff
@@ -679,6 +682,24 @@ class LinkAnnotationElement extends AnnotationElement {
     link.className = "internalLink";
   }
 
+  /**
+   * Bind attachments to the link element.
+   * @param {Object} link
+   * @param {Object} attachment
+   */
+  _bindAttachment(link, attachment) {
```
Comment (calixteman) [inline src/display/annotation_layer.js:690]: The code here is more or less the same as in `web/pdf_outline_viewer.js`, is there any possibility to have it in one place ?

Comment (Snuffleupagus) [reply src/display/annotation_layer.js:690]: Similar yes, but not entirely identical. This problem isn't unique to newly added action though, but exists for most of the older methods.
Hence I think that it'd make sense to consider all of these methods together, and not just piecemeal, which is why a follow-up would be more suited in my opinion. However it's not guaranteed that it'd work out all that nicely, given the slight differences, and I'd also really like to avoid making the `PDFLinkService`-class too "unwieldy" in the process (since users may want to create custom ones).

**Review by calixteman — APPROVED** [review]
LGTM. Thank you.
