### PR TITLE
[Editor] Improve drawing on a touch screen.

### LINKED ISSUE #17446: Pitch zoom problem while ink annotation is on
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome & Safari
- Operating system and its version: Android & IOS
- PDF.js version: 4.0.269
- Is a browser extension: No

Steps to reproduce the problem:
1. Click Ink annotation and draw something.
2. Use finger to pinch zoom in or out, it draw some mess.

What is the expected behavior? zoom in or out without drawing mess.

What went wrong?

### PR DESCRIPTION
**Pull request by calixteman**
- it's now possible to start a drawing with a pen and use fingers to zoom or scroll without interacting with the current drawing;
- it's now possible to draw with a finger and them zoom with two fingers.

### CODE REVIEW

**Comment by Snuffleupagus** [comment]
Does this fix issue #17446, or is more work required?

File: src/display/editor/draw.js [hunk 1]
```diff
@@ -71,10 +71,20 @@ class DrawingEditor extends AnnotationEditor {
 
   static _currentDraw = null;
 
+  static _currentDrawingAC = null;
```
Comment (Snuffleupagus) [inline src/display/editor/draw.js:74]: For all the new fields added in the patch, here and below, could we make them actually private rather than just semi-private?
```suggestion
  static #currentDrawingAC = null;
```

File: src/display/editor/draw.js [hunk 2]
```diff
@@ -639,32 +649,78 @@ class DrawingEditor extends AnnotationEditor {
...
     } = parent;
     const { width: parentWidth, height: parentHeight } =
       target.getBoundingClientRect();
-    const ac = new AbortController();
+
+    const ac = (this._currentDrawingAC = new AbortController());
     const signal = parent.combinedSignal(ac);
 
+    this._currentPointerId ||= pointerId;
+    this._currentPointerType ||= pointerType;
```
Comment (Snuffleupagus) [inline src/display/editor/draw.js:677]: Given that `pointerId` seems to be specified as [a number](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/pointerId#value), it might be zero?
Hence it seems overall safer just change these as follows, to prevent them being changed.
```suggestion
    this._currentPointerId ??= pointerId;
    this._currentPointerType ??= pointerType;
```

File: src/display/editor/draw.js [hunk 3]
```diff
@@ -675,6 +731,18 @@ class DrawingEditor extends AnnotationEditor {
...
+      "touchmove",
+      e => {
+        if (e.timeStamp === this._currentMoveTimestamp) {
+          // This move event is used to draw so we don't want to scroll.
+          stopEvent(e);
+        }
+      },
+      {
+        signal,
+      }
```
Comment (Snuffleupagus) [inline src/display/editor/draw.js:744]: Nit:
```suggestion
      { signal }
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you.
