### PR TITLE
Some jpx images can have a mask

### LINKED ISSUE #18896: [Bug]: JPX image rendering regression after PR 18204
### Attach (recommended) or Link to PDF file

https://sbc.org.pl/Content/403918/PDF/539_2671.pdf

### Web browser and its version

N/A

### Operating system and its version

N/A

### PDF.js version

Any version after https://github.com/mozilla/pdf.js/pull/18204

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

Load the linked PDF document in the viewer.

### What is the expected behavior?

That the image is correctly rendered.

good

### What went wrong?

The image doesn't render, with the following console output:
```
Warning: Unable to decode image "img_p0_2": "IndexSizeError: Index or size is negative or greater than the allowed amount". [pdf.worker.mjs:348:13](resource://pdf.js/build/pdf.worker.mjs)
Warning: Dependent image isn't ready yet [pdf.mjs:391:13](resource://pdf.js/build/pdf.mjs)
```

bad

### Link to a viewer

_No response_

### Additional context

```
196affd8e06148041b885ce63df260e4dab5f8e1 is the first bad commit
commit 196affd8e06148041b885ce63df260e4dab5f8e1
Author: Calixte Denizet <calixte.denizet@gmail.com>
Date:   Mon Jun 3 16:09:26 2024 +0200

    Fix decoding of JPX images having an alpha channel

    When an image has a non-zero SMaskInData it means that the image
    has an alpha channel.
    With JPX images, the colorspace isn't required (by spec) so when we
    don't have it, the JPX decoder will handle the conversion in RGBA
    format.

 external/openjpeg/openjpeg.js  |  2 +-
 src/core/base_stream.js        |  4 +--
 src/core/colorspace.js         | 22 ++++++++++++
 src/core/decode_stream.js      | 12 +++----
 src/core/flate_stream.js       |  2 +-
 src/core/image.js              | 82 ++++++++++++++++++++++++++++++------------
 src/core/jpx.js                |  5 +--
 src/core/jpx_stream.js         |  8 ++---
 test/pdfs/isssue18194.pdf.link |  1 +
 test/pdfs/issue11306.pdf.link  |  1 +
 test/pdfs/issue16782.pdf.link  |  1 +
 test/test_manifest.json        | 25 +++++++++++++
 12 files changed, 126 insertions(+), 39 deletions(-)
 create mode 100644 test/pdfs/isssue18194.pdf.link
 create mode 100644 test/pdfs/issue11306.pdf.link
 create mode 100644 test/pdfs/issue16782.pdf.link
```

*Please note:* The PDF document renders a bit slow, given the large images, however that's already tracked in #17427.

/cc @calixteman

### PR DESCRIPTION
**Pull request by calixteman**
It fixes #18896.

### CODE REVIEW

File: src/core/image.js [hunk 1]
```diff
@@ -705,7 +705,7 @@ class PDFImage {
       isOffscreenCanvasSupported &&
       ImageResizer.needsToBeResized(drawWidth, drawHeight);
 
-    if (this.colorSpace.name === "DeviceRGBA") {
+    if (!this.mask && this.colorSpace.name === "DeviceRGBA") {
```
Comment (Snuffleupagus) [inline src/core/image.js:708]: Should this perhaps ignore all kinds of masks?
```suggestion
    if (!this.smask && !this.mask && this.colorSpace.name === "DeviceRGBA") {
```

File: src/core/colorspace.js [hunk 2]
```diff
@@ -806,6 +862,32 @@ class DeviceRgbaCS extends ColorSpace {
...
+    dest,
+    originalWidth,
+    originalHeight,
+    width,
+    height,
+    actualHeight,
+    bpc,
+    comps,
+    alpha01
+  ) {
```
Comment (Snuffleupagus) [inline src/core/colorspace.js:876]: For consistency, can we please copy the assert used at the top of the [base-class `fillRgb` method](https://github.com/mozilla/pdf.js/blob/e1f9fa4ea54246bbfa974ac75720793b9ff9fd12/src/core/colorspace.js#L130-L151) here as well?
```suggestion
  ) {
    if (typeof PDFJSDev === "undefined" || PDFJSDev.test("TESTING")) {
      assert(
        dest instanceof Uint8ClampedArray,
        'DeviceRgbaCS.fillRgb: Unsupported "dest" type.'
      );
    }
```

**Review by Snuffleupagus — DISMISSED** [review]
r=me, with one more comment; thank you.

**Review by Snuffleupagus — APPROVED** [review]
*(Sorry about the miss-clicks.)*

Seems fine with https://github.com/mozilla/pdf.js/pull/18899#discussion_r1799916312 addressed.
