### PR TITLE
Fix missing annotation parent in using the one from the Fields entry

### LINKED ISSUE #15096: Radio options not rendered when save document
**Sample File:**
[SmartFormAllFields.pdf](https://github.com/mozilla/pdf.js/files/8977707/SmartFormAllFields.pdf)

**Configuration:**
- Web browser and its version: Chrome (102.0.5005.115), Firefox (99.0.1)
- Operating system and its version: MacOS, Windows
- Commit: [a334a21](https://github.com/calixteman/pdf.js/commit/a334a21a1d6324637f4df37a29dfd087fd4559b3)
- Is a browser extension: No

**Steps to reproduce the problem:**
1. Use above sample pdf. 
2. Modify radio options 

**What is the expected behavior?**
1. Only selected radio button should checked when saving document using saveDocument()

**What went wrong?** 
1. When save document radio button not selected properly
Screenshot 2022-06-24 at 10 14 18 PM

### PR DESCRIPTION
**Pull request by calixteman**
Fixes #15096.

### CODE REVIEW

File: src/core/annotation.js [hunk 1]
```diff
@@ -122,6 +122,7 @@ class AnnotationFactory {
     annotationGlobals,
     idFactory,
     collectFields,
+    orphanFields,
```
Comment (Snuffleupagus) [inline src/core/annotation.js:125]: This parameter should be added to the JSDoc just above.

File: src/core/document.js [hunk 2]
```diff
@@ -793,6 +793,7 @@ class Page {
           return [];
         }
 
+        const orphanFields = (await this.fieldObjects)?.orphanFields;
```
Comment (Snuffleupagus) [inline src/core/document.js:796]: I'm not convinced that this is generally safe unfortunately, and it'd also be nice to avoid unnecessarily delaying annotation-parsing here since most documents probably won't have any fieldObjects.

```diff
diff --git a/src/core/document.js b/src/core/document.js
index 68e26e8a2..d5c453d5a 100644
--- a/src/core/document.js
+++ b/src/core/document.js
@@ -787,13 +787,15 @@ class Page {
         if (annots.length === 0) {
           return annots;
         }
-        const annotationGlobals =
-          await this.pdfManager.ensureDoc("annotationGlobals");
+        const [annotationGlobals, fieldObjects] = await Promise.all([
+          this.pdfManager.ensureDoc("annotationGlobals"),
+          this.pdfManager.ensureDoc("fieldObjects"),
+        ]);
         if (!annotationGlobals) {
           return [];
         }

-        const orphanFields = (await this.fieldObjects)?.orphanFields;
+        const orphanFields = fieldObjects?.orphanFields;
         const annotationPromises = [];
         for (const annotationRef of annots) {
           annotationPromises.push(
```

File: src/core/document.js [hunk 3]
```diff
@@ -1815,6 +1819,15 @@ class PDFDocument {
       }
     }
 
+    if (
+      parentRef &&
+      field.get("Subtype") === Name.get("Widget") &&
```
Comment (Snuffleupagus) [inline src/core/document.js:1824]: Given that `Name` objects are cached (similar to `Ref` and `Cmd`) this isn't generally safe, however we have a utility function for such cases.
```suggestion
      isName(field.get("Subtype"), "Widget") &&
```

File: src/core/document.js [hunk 4]
```diff
@@ -1815,6 +1819,15 @@ class PDFDocument {
...
+      !field.getRaw("Parent")
```
Comment (Snuffleupagus) [inline src/core/document.js:1825]: Do we actually need to lookup the Parent, or would a simple exists-check suffice?
```suggestion
      !field.has("Parent")
```

File: test/unit/document_spec.js [hunk 5]
```diff
@@ -213,12 +213,12 @@ describe("document", function () {
       const acroForm = new Dict();
 
       let pdfDocument = getDocument(acroForm);
-      let fields = await pdfDocument.fieldObjects;
+      let fields = (await pdfDocument.fieldObjects) || null;
```
Comment (Snuffleupagus) [inline test/unit/document_spec.js:216]: I don't believe that this is actually necessary, besides we should be testing what the method actually returns.
```suggestion
      let fields = await pdfDocument.fieldObjects:
```

File: test/unit/document_spec.js [hunk 6]
```diff
@@ -213,12 +213,12 @@ describe("document", function () {
...
       expect(fields).toEqual(null);
 
       acroForm.set("Fields", []);
       pdfDocument = getDocument(acroForm);
-      fields = await pdfDocument.fieldObjects;
+      fields = (await pdfDocument.fieldObjects) || null;
```
Comment (Snuffleupagus) [inline test/unit/document_spec.js:221]: I don't believe that this is actually necessary, besides we should be testing what the method actually returns.
```suggestion
      fields = await pdfDocument.fieldObjects;
```

**Review by Snuffleupagus — CHANGES_REQUESTED** [review]

File: src/core/document.js [hunk 7]
```diff
@@ -1815,6 +1822,15 @@ class PDFDocument {
       }
     }
 
+    if (
+      parentRef &&
+      isName(field.get("Subtype"), "Widget") &&
+      !field.has("Parent")
```
Comment (Snuffleupagus) [inline src/core/document.js:1828]: Nit: Maybe swap these lines around, to do the "cheaper" check first?
```suggestion
      !field.has("Parent") &&
      isName(field.get("Subtype"), "Widget")
```

**Review by Snuffleupagus — APPROVED** [review]
r=me, thank you.
